ViridianForest_SouthEntrance_MapScripts::
	.byte 0

Route2_ViridianForest_SouthEntrance_EventScript_Woman1::
	msgbox Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze, MSGBOX_NPC
	end

Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
    .string "Vas cap al Bosc Viridian?\n"
    .string "És un laberint natural, allà dins.\l"
    .string "Ves amb compte de no perdre't.$"

Route2_ViridianForest_SouthEntrance_EventScript_Woman2::
	msgbox Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite, MSGBOX_NPC
	end

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
    .string "Rattata pot ser petit, però no\n"
    .string "subestimis la seva mossegada.\p"
    .string "Ja n'has atrapat un?$"
