SSAnne_2F_Room5_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
    .string "Has anat a la ZONA SAFARI de\n"
    .string "Ciutat Fuchsia?\p"
    .string "Hi ha moltes espècies de Pokémon\n"
    .string "rars.$"

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
    .string "El meu avi i jo pensem que la\n"
    .string "Zona Safari és increïble!\l"
    .string "M'agradaria tornar-hi.$"
