BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "El que necessita un Entrenador…\p"
	.string "Coneixement…\n"
	.string "Estratègia…\l"
	.string "Sort…\l"
	.string "Valor…\l"
	.string "Esperit…\l"
	.string "Valentia…\l"
	.string "I habilitat…\p"
	.string "Bé, jo ho tinc tot!\n"
	.string "Seré imparable a tot arreu!\p"
	.string "Eh? Pokémon?\n"
	.string "Què és això?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Coneixes els Cervells\n"
	.string "de la Frontera?\p"
	.string "Així és com l'Scott anomena els set\n"
	.string "Entrenadors especials que dirigeixen\l"
	.string "les instal·lacions de la Frontera.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "A la Torre de Combat, una noia gran\n"
	.string "em va dir que tinc molt talent\l"
	.string "per als combats!\p"
	.string "M'agraden més els Concursos Pokémon!\p"
	.string "Però no se'm donen bé els Concursos!\p"
	.string "Suposo que tenir talent i que\n"
	.string "t'agradi una cosa no és el mateix.$"

