PewterCity_Museum_2F_MapScripts::
	.byte 0

PewterCity_Museum_2F_EventScript_Man::
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
	end

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "Pedra Lluna, eh?\p"
    .string "Què té d'especial?\n"
    .string "A mi em sembla una pedra normal.$"

PewterCity_Museum_2F_EventScript_OldMan::
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
	end

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "20 de juliol de 1969!\p"
    .string "La humanitat va trepitjar la\n"
    .string "lluna per primera vegada.\p"
    .string "Vaig comprar una tele en color\n"
    .string "per veure aquella notícia.$"

PewterCity_Museum_2F_EventScript_Scientist::
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
	end

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "Aquest mes tenim una exposició\n"
    .string "sobre l'espai.$"

PewterCity_Museum_2F_EventScript_LittleGirl::
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
	end

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "Vull un Pikachu!\n"
    .string "És tan bufó!\p"
    .string "Li he demanat al papa que me'n\n"
    .string "capturi un!$"

PewterCity_Museum_2F_EventScript_BaldingMan::
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
	end

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "Sí, un Pikachu aviat, ho prometo!$"

PewterCity_Museum_2F_EventScript_SpaceShuttle::
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
	end

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "Transbordador Espacial$"

PewterCity_Museum_2F_EventScript_MoonStone::
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
	end

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "Un meteorit que va caure al\n"
    .string "Mt. Moon. Es creu que és una\l"
    .string "Pedra Lluna.$"

