gText_ApprenticeChallenge0::
	.string "Soc l'aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}. Snif… Estic molt nerviós…$"

gText_ApprenticeChallenge1::
	.string "Soc l'aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}! Som-hi!$"

gText_ApprenticeChallenge2::
	.string "Soc l'aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}! Accepta el meu repte!$"

gText_ApprenticeChallenge3::
	.string "Em… Soc l'aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}… Creus que puc guanyar?$"

gText_ApprenticeChallenge4::
	.string "Soc l'aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}! Deixa que et repti!$"

gText_ApprenticeChallenge5::
	.string "Estic molt ocupat, però també\n"
	.string "soc l'aprenent núm. {STR_VAR_2} d'{STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Soc l'aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}. Encantat de conèixer-te!$"

gText_ApprenticeChallenge7::
	.string "Serveixo com a aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}. Puc començar?$"

gText_ApprenticeChallenge8::
	.string "Ei! Soc l'aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}! Ho donaré tot!$"

gText_ApprenticeChallenge9::
	.string "Iuhu! Soc l'aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}! Prepara't!$"

gText_ApprenticeChallenge10::
	.string "Soc l'aprenent núm. 1.000 d'{STR_VAR_1}!\n"
	.string "De fet, soc el núm. {STR_VAR_2}! Som-hi!$"

gText_ApprenticeChallenge11::
	.string "Sí, soc l'aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}! Que comenci la marxa!$"

gText_ApprenticeChallenge12::
	.string "Visca! Soc el que en diuen\n"
	.string "l'aprenent núm. {STR_VAR_2} d'{STR_VAR_1}!$"

gText_ApprenticeChallenge13::
	.string "Cof! Soc l'aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}. Encantat! Cof!$"

gText_ApprenticeChallenge14::
	.string "Quins nervis…\n"
	.string "Soc l'aprenent núm. {STR_VAR_2} d'{STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Soc l'aprenent núm. {STR_VAR_2}\n"
	.string "d'{STR_VAR_1}, i no és cap mentida.$"

gText_ApprenticePleaseTeach0::
	.string "Ets… {PLAYER}?\n"
	.string "Oh! Snif…bua…\p"
	.string "Oh! P-perdona…\n"
	.string "Estic tan nerviós que no puc\l"
	.string "evitar plorar…\p"
	.string "Soc {STR_VAR_1}, i t'admiro\n"
	.string "molt, {PLAYER}.\p"
	.string "Jo… Tenia el somni de conèixer-te\n"
	.string "algun dia i preguntar-te\l"
	.string "sobre Pokémon.\p"
	.string "Si us plau, {PLAYER}!\n"
	.string "Ensenya'm sobre Pokémon!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… P-però…\n"
	.string "Snif… Buaaaaa!\p"
	.string "Si us plau!\n"
	.string "T'ho suplico, si us plau!$"

gText_ApprenticeWhichLevelMode0::
	.string "Ah, de veritat? Ho faràs?\n"
	.string "Genial! Increïble! Uuuuh!\p"
	.string "Oh… Perdona…\n"
	.string "Estic tan content que ploro…\p"
	.string "Em… Doncs digues-me!\n"
	.string "És sobre la Torre de Combat.\p"
	.string "Què seria millor per a mi:\n"
	.string "Nivell 50 o Nivell Obert?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Buaaaaa!\p"
	.string "Oh! Ho sento molt!\n"
	.string "M'has fet tan feliç triant\l"
	.string "el nivell per a mi que ploro…\p"
	.string "Snif…\n"
	.string "Moltes gràcies!\l"
	.string "Torna a parlar amb mi!$"

gText_ApprenticePleaseTeach1::
	.string "Uau! Tu ets {PLAYER}, oi?\n"
	.string "Ets increïblement fort, oi?\p"
	.string "Soc {STR_VAR_1}!\n"
	.string "Acabo de ser Entrenador!\p"
	.string "Si us plau, {PLAYER}!\n"
	.string "Pots ser el meu mestre i\l"
	.string "ensenyar-me molt?$"

gText_ApprenticeRejectTeaching1::
	.string "Oh, per què?\n"
	.string "Si us plau? Si us plauuu?\l"
	.string "Sigues el meu mestre, si us plau!$"

gText_ApprenticeWhichLevelMode1::
	.string "Bé! Genial!\p"
	.string "El primer que volia preguntar-te és\n"
	.string "sobre la Torre de Combat!\p"
	.string "Les sales de Nivell 50 i Nivell Obert…\n"
	.string "Quina seria perfecta per a mi?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, oi? És veritat!\n"
	.string "Ho donaré tot allà!\p"
	.string "Si ens tornem a veure, ensenya'm\n"
	.string "alguna cosa més, mestre!$"

gText_ApprenticePleaseTeach2::
	.string "Em… Ets {PLAYER}?\n"
	.string "Em dic {STR_VAR_1}.\p"
	.string "Vull ser Entrenador Pokémon,\n"
	.string "però no sé què fer…\p"
	.string "Així que he pensat que potser podria\n"
	.string "demanar-te consell perquè\l"
	.string "ets tan famós.\p"
	.string "{PLAYER}, em pots aconsellar?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, però…\p"
	.string "Vull ser Entrenador Pokémon\n"
	.string "de veritat!\p"
	.string "Si us plau, pots respondre\n"
	.string "les meves preguntes?$"

gText_ApprenticeWhichLevelMode2::
	.string "Gràcies!\n"
	.string "Aquí va la primera pregunta!\p"
	.string "La Torre de Combat té dos nivells,\n"
	.string "Nivell 50 i Nivell Obert, oi?\p"
	.string "Quin nivell creus que és més\n"
	.string "adequat per a mi?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, el repte de {STR_VAR_1}?\n"
	.string "Entès!\p"
	.string "Si tinc una altra pregunta, tornaré\n"
	.string "aquí per demanar-te consell!$"

gText_ApprenticePleaseTeach3::
	.string "Oh? Eh? Tu ets…\n"
	.string "No, no pot ser.\p"
	.string "No hi ha manera que algú com jo\n"
	.string "pugui conèixer {PLAYER}.\p"
	.string "…De veritat ets {PLAYER}?\n"
	.string "No em puc creure que et parlo!\p"
	.string "Quan passa una cosa tan bona,\n"
	.string "segur que em passaran coses\l"
	.string "terribles, ho sé…\p"
	.string "…Perdona…\n"
	.string "Soc… {STR_VAR_1}…\p"
	.string "No hi ha res especial en mi\n"
	.string "de què pugui estar orgullós…\p"
	.string "Ni hauria de dir res de mi\n"
	.string "perquè ho oblidaràs…\p"
	.string "Tenia el somni que si et coneixia,\n"
	.string "{PLAYER}, potser podria demanar-te\l"
	.string "consell com a Entrenador.\p"
	.string "Però no crec que hi estiguis\n"
	.string "d'acord.\p"
	.string "…O seràs tan amable de\n"
	.string "donar-me consell?$"

gText_ApprenticeRejectTeaching3::
	.string "Ho sabia…\p"
	.string "Havia de passar perquè soc un\n"
	.string "ningú tan avorrit…\p"
	.string "Però pensava que potser…\n"
	.string "No ho reconsideraràs?\p"
	.string "Però no puc rendir-me així.\n"
	.string "T'ho preguntaré mentre tingui sort!\p"
	.string "Si us plau, seràs tan amable\n"
	.string "de donar-me consell?$"

gText_ApprenticeWhichLevelMode3::
	.string "De veritat? No m'ho crec!\n"
	.string "No em crec que m'aconsellis!\l"
	.string "Jo… Estic tan content…\p"
	.string "El que vull preguntar-te és molt\n"
	.string "trivial, però no em puc decidir…\p"
	.string "A la Torre de Combat, et deixen\n"
	.string "triar Nivell 50 o Nivell Obert.\p"
	.string "Quin creus que fins i tot jo\n"
	.string "podria tenir una oportunitat?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? D'acord!\n"
	.string "Però de veritat creus que algú\l"
	.string "com jo tindria una oportunitat?\p"
	.string "Ho donaré tot, encara que no\n"
	.string "crec que funcioni.\p"
	.string "Moltes gràcies per dedicar\n"
	.string "temps a algú com jo.$"

gText_ApprenticePleaseTeach4::
	.string "Oh! Tu ets {PLAYER}{KUN}, oi?\p"
	.string "He sentit que ets molt bo\n"
	.string "amb els Pokémon!\p"
	.string "Soc {STR_VAR_1}!\n"
	.string "Seré el teu amic!\p"
	.string "Ho sabies?\p"
	.string "No pots guanyar a la Frontera\n"
	.string "de Combat si només saps el que\l"
	.string "ensenyen a l'Escola d'Entrenadors.\p"
	.string "Estic disposat a escoltar el teu\n"
	.string "consell. Hi estaràs d'acord, oi?$"

gText_ApprenticeRejectTeaching4::
	.string "Eh? Per què em rebutges?\n"
	.string "Soc jo qui t'ho demana!\l"
	.string "Has de reconsiderar-ho!$"

gText_ApprenticeWhichLevelMode4::
	.string "D'acord, doncs hi ha una cosa.\n"
	.string "Vull que la decideixis per mi.\p"
	.string "Saps que la Torre de Combat té\n"
	.string "Nivell 50 i Nivell Obert?\p"
	.string "Quin creus que seria bo\n"
	.string "per a mi, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "D'acord, {STR_VAR_1} és adequat per a mi?\n"
	.string "Gràcies!\p"
	.string "Sabent que tu has decidit,\n"
	.string "{PLAYER}{KUN}, no em sabrà tant de greu\l"
	.string "si perdo.\p"
	.string "D'acord, comptaré amb tu!\n"
	.string "Adéu!$"

gText_ApprenticePleaseTeach5::
	.string "Ei, hola! {PLAYER}{KUN}!\n"
	.string "Et conec perquè ets famós!\l"
	.string "Digues-me {STR_VAR_1}! Encantat!\p"
	.string "Soc un Triatleta, així que em\n"
	.string "mantinc en forma mentre crio Pokémon.\p"
	.string "També estic involucrat en altres\n"
	.string "coses com treballar, migdiades,\l"
	.string "balls de saló…\p"
	.string "Estant tan ocupat, no és fàcil\n"
	.string "ser un bon Entrenador.\p"
	.string "Doncs, tinc una proposta!\p"
	.string "Deu haver-hi una raó per la qual ens\n"
	.string "hem trobat. Què tal si comparteixes\l"
	.string "la teva saviesa amb mi, {PLAYER}{KUN}?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, però, si us plau?\n"
	.string "Un noi com jo necessita algú\l"
	.string "com tu, {PLAYER}{KUN}!\p"
	.string "De veritat, necessito el teu consell!$"

gText_ApprenticeWhichLevelMode5::
	.string "Gràcies! Així m'agrada!\n"
	.string "Comencem amb una de fàcil!\p"
	.string "Saps dels dos cursos de la\n"
	.string "Torre de Combat, oi?\l"
	.string "Nivell 50 i Nivell Obert.\p"
	.string "Estant jo tan ocupat, per a quin\n"
	.string "m'hauria de preparar?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, oi? D'acord, entès.\n"
	.string "Trobaré temps i ho intentaré!\p"
	.string "…Ui, he d'anar a treballar!\n"
	.string "Gràcies! Ens veiem!$"

gText_ApprenticePleaseTeach6::
	.string "No pot ser! De debò!\n"
	.string "Ets potser el veritable {PLAYER}?\p"
	.string "A-ha! Genial! Soc {STR_VAR_1},\n"
	.string "molt content de conèixer-te!\p"
	.string "{PLAYER}, ets molt fort,\n"
	.string "oi?\p"
	.string "Tothom parla de tu!\p"
	.string "Oh! Tinc una idea genial!\n"
	.string "Demanaré consell a tu, {PLAYER}!\l"
	.string "Segur que em faré més fort!\p"
	.string "No és una gran idea?\n"
	.string "Si us plau, vull el teu consell!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, pots fer-te el dur,\n"
	.string "però no m'enganyes!\l"
	.string "En realitat vols dir que sí, oi?$"

gText_ApprenticeWhichLevelMode6::
	.string "Bé! Sabia que tindries bon cor,\n"
	.string "{PLAYER}!\p"
	.string "Què t'hauria de preguntar primer?\n"
	.string "…Oh, ja tinc alguna cosa!\p"
	.string "Redoble de tambor, si us plau!\n"
	.string "La pregunta que tinc és…\p"
	.string "Si faig un repte a la Torre de\n"
	.string "Combat, per on hauria d'anar?\p"
	.string "Nivell 50 o Nivell Obert?\n"
	.string "Quin em va més?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh!\n"
	.string "{STR_VAR_1}, dius!\l"
	.string "Gràcies per una resposta genial!\p"
	.string "Crec que això és tot el que volia\n"
	.string "preguntar-te avui.\p"
	.string "Tornem-nos a veure aquí, d'acord?\n"
	.string "Gràcies!$"

gText_ApprenticePleaseTeach7::
	.string "Perdona, però…\n"
	.string "Ets {PLAYER}?\p"
	.string "Soc {STR_VAR_1}, i és un plaer\n"
	.string "conèixer-te.\p"
	.string "Fa temps que t'admiro…\p"
	.string "… … … … … …\p"
	.string "Em… Espero que no et sigui\n"
	.string "massa molèstia, però…\p"
	.string "Puc ser el teu aprenent,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Oh…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…Dec haver-me desmaiat del xoc.\n"
	.string "Perdona, dec haver sentit malament.\p"
	.string "Si us plau! Si us plau, digues\n"
	.string "que m'acceptes com a aprenent!$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh… Estic encantat!\p"
	.string "No vull fer-te perdre el temps,\n"
	.string "així que aconsella'm sobre això.\p"
	.string "Tinc previst fer un repte a la\n"
	.string "Torre de Combat aviat.\p"
	.string "Però hi ha dos nivells…\p"
	.string "Quin seria més adequat per a mi?\n"
	.string "Nivell 50 o Nivell Obert?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} és la teva elecció!\n"
	.string "Entenc. Ho donaré tot!\p"
	.string "Gràcies, {PLAYER}.\n"
	.string "Espero poder comptar amb tu.\l"
	.string "Cuida't!$"

gText_ApprenticePleaseTeach8::
	.string "Ei! Ei! {PLAYER}!\n"
	.string "M'has parlat!\l"
	.string "Estic… Estic tan content!\p"
	.string "Jo! Em dic {STR_VAR_1}!\n"
	.string "Acabo de ser Entrenador!\p"
	.string "Estic encantat de conèixer-te,\n"
	.string "{PLAYER}, el gran nom del Pokémon!\p"
	.string "Oh-oh-oh, ja ho sé!\n"
	.string "Puc demanar-te un favor, {PLAYER}?\p"
	.string "Si us plau, accepta'm com a aprenent!\n"
	.string "Vull aprendre de tu!$"

gText_ApprenticeRejectTeaching8::
	.string "Buaaaaa!\n"
	.string "{PLAYER} m'ha rebutjat…\l"
	.string "És… És una experiència valuosa!\p"
	.string "{PLAYER}, si us plau! Vull sentir\n"
	.string "una resposta afirmativa!\p"
	.string "Et suplico la teva guia!$"

gText_ApprenticeWhichLevelMode8::
	.string "Iiii! {PLAYER} ha dit que sí!\n"
	.string "{PLAYER} ha dit que sí!\p"
	.string "No podré dormir aquesta nit…\n"
	.string "Moltíssimes gràcies!\p"
	.string "Doncs, aquí va la meva pregunta!\p"
	.string "A la Torre de Combat, què em\n"
	.string "convé, Nivell 50 o Nivell Obert?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Perfectament entès!\n"
	.string "Ho entenc perfectament!\l"
	.string "Estic delirant de content!\p"
	.string "Espero que vulguis ensenyar-me\n"
	.string "més coses un altre dia.$"

gText_ApprenticePleaseTeach9::
	.string "Uau! Podries ser…\n"
	.string "Ets potser… {PLAYER}{KUN}?!\l"
	.string "L'Entrenador fort i famós?\l"
	.string "Quina sort tinc!\p"
	.string "Hola, em dic {STR_VAR_1}!\p"
	.string "He estat buscant un mestre\n"
	.string "de Pokémon.\p"
	.string "I amb un temps impecable,\n"
	.string "has aparegut tu, {PLAYER}{KUN}!\p"
	.string "Doncs ja ho tens, {PLAYER}{KUN}!\n"
	.string "Deixa'm ser el teu aprenent!$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah!\n"
	.string "Ets bastant dur…\p"
	.string "No siguis així, si us plau.\n"
	.string "T'ho estic demanant!$"

gText_ApprenticeWhichLevelMode9::
	.string "Oh, sí! Bona resposta!\n"
	.string "Excel·lent, si em permets!\p"
	.string "Què tal un primer consell\n"
	.string "sobre la Torre de Combat?\p"
	.string "Si hi anés, què seria millor?\n"
	.string "Nivell 50 o Nivell Obert?$"

gText_ApprenticeLevelModeThanks9::
	.string "Ajà, {STR_VAR_1} doncs!\n"
	.string "OK, perfecte!\l"
	.string "Aniré a demostrar el que valc!\p"
	.string "D'acord, comptaré amb tu com a\n"
	.string "mentor! Adéu!$"

gText_ApprenticePleaseTeach10::
	.string "Ei, {PLAYER}{KUN}, oi?\n"
	.string "La policia et buscava!\p"
	.string "… … …\n"
	.string "És clar que és mentida!\p"
	.string "Jo soc {STR_VAR_1}. Malgrat les\n"
	.string "aparences, soc el Campió Pokémon!\l"
	.string "…Això també és mentida!\p"
	.string "Però això no és mentida.\n"
	.string "No soc gaire bo en combat.\p"
	.string "Doncs, què tal si et converteixes\n"
	.string "en el meu mestre Pokémon?$"

gText_ApprenticeRejectTeaching10::
	.string "Si et poses fred així,\n"
	.string "et mostraré què faré!\p"
	.string "Buaaa! Buaaa! Buaaa!\n"
	.string "Xip!\p"
	.string "Hahaha, eren LLÀGRIMES FALSES!\p"
	.string "Vinga, si us plau, vols ser\n"
	.string "el meu mestre Pokémon?$"

gText_ApprenticeWhichLevelMode10::
	.string "Visca!\n"
	.string "Et compraré un vaixell!\p"
	.string "És clar que és mentida!\n"
	.string "Però… Gràcies, mestre!\p"
	.string "Saps que hi ha Nivell 50 i\n"
	.string "Nivell Obert a la Torre de Combat?\p"
	.string "No em puc decidir quin nivell\n"
	.string "hauria de provar…\p"
	.string "Pots decidir per mi, mestre?$"

gText_ApprenticeLevelModeThanks10::
	.string "D'acord, doncs {STR_VAR_1} és millor!\n"
	.string "Aniré a l'altre nivell, doncs!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies, mestre!\n"
	.string "Espero que continuïs ensenyant-me!$"

gText_ApprenticePleaseTeach11::
	.string "H-O-L-A!\n"
	.string "I això diu hola, i vol dir ei!\p"
	.string "Soc {STR_VAR_1}, el Mariner\n"
	.string "raper!\p"
	.string "Ara et toca a tu, explica'm una\n"
	.string "mica sobre tu, prova-ho!\p"
	.string "Ajà, ajà!\n"
	.string "{PLAYER}{KUN} és el teu nom,\l"
	.string "i Pokémon és el teu joc!\p"
	.string "I estàs en una edat delicada\n"
	.string "on tot el món és un escenari!\p"
	.string "De totes maneres, vull dir\n"
	.string "que ets el desè Entrenador\l"
	.string "amb qui parlo avui.\p"
	.string "Celebrem-ho!\n"
	.string "Sigues el meu mentor!$"

gText_ApprenticeRejectTeaching11::
	.string "Però!\n"
	.string "Has de col·laborar amb mi!\p"
	.string "No siguis tan esquiu!\n"
	.string "Sigues el meu mentor, si us plau!$"

gText_ApprenticeWhichLevelMode11::
	.string "Això és!\n"
	.string "{PLAYER}, tens esperit!\p"
	.string "Aquí va la meva primera pregunta\n"
	.string "que reclama el teu suggeriment!\p"
	.string "És sobre la Torre de Combat,\n"
	.string "i depèn del meu poder!\p"
	.string "Nivell 50 i Nivell Obert hi ha,\n"
	.string "quin és el bo per a mi?$"

gText_ApprenticeLevelModeThanks11::
	.string "D'acord, {STR_VAR_1} dius!\n"
	.string "Aniré a provar-ho de seguida!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, seguiré les teves paraules!$"

gText_ApprenticePleaseTeach12::
	.string "Ei, no ets {PLAYER}?\n"
	.string "Què hauria de fer? Parlar-te?\l"
	.string "Per què no? Ja t'estic parlant!\p"
	.string "{PLAYER}, et sorprèn que soc?\n"
	.string "Millor que et digui qui soc!\p"
	.string "{STR_VAR_1} és com em pots dir.\n"
	.string "L'estrella més brillant de la\l"
	.string "guitarra, soc jo!\p"
	.string "Em sents?\n"
	.string "Em sents!\p"
	.string "La sort m'acompanya,\n"
	.string "et faré una petició!\p"
	.string "{PLAYER}, deixa'm ser el teu deixeble!\n"
	.string "Vull que m'ensenyis tot!$"

gText_ApprenticeRejectTeaching12::
	.string "Em rebutges, doncs?\n"
	.string "Hauré de tornar-t'ho a demanar!\p"
	.string "{PLAYER}, suplico ser el teu deixeble!\n"
	.string "Necessito que m'ensenyis tot!$"

gText_ApprenticeWhichLevelMode12::
	.string "Sort, sí, iuhu!\n"
	.string "Et faig una pregunta?\p"
	.string "Com que som a prop de la Torre de\n"
	.string "Combat, una pregunta sobre ella?\p"
	.string "De les opcions que veus,\n"
	.string "quina és la bona per a mi?$"

gText_ApprenticeLevelModeThanks12::
	.string "Si {STR_VAR_1} és el que suggereixes,\n"
	.string "deu ser el millor!\p"
	.string "Bé, {PLAYER}, he d'anar per lliure,\n"
	.string "però no m'oblidis.\p"
	.string "Ens veiem, amic llest!$"

gText_ApprenticePleaseTeach13::
	.string "Oh, ei! Tu d'aquí!\n"
	.string "Em pots fer un massatge a l'espatlla?\p"
	.string "…Sí, aquí! Això és!\n"
	.string "Au, au! Oooh, quina meravella!\p"
	.string "Em dic {STR_VAR_1}.\n"
	.string "Faig karate, però el meu cos\l"
	.string "no aguanta l'esforç…\p"
	.string "He decidit combatre amb Pokémon\n"
	.string "i endurir-me.\p"
	.string "Tu ets {PLAYER}{KUN}, oi?\n"
	.string "El CAMPIÓ de la Lliga Pokémon?\p"
	.string "Escolta, pots donar-me\n"
	.string "consell?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, per què?\p"
	.string "No seré cap molèstia, ho prometo!\n"
	.string "Si us plau?$"

gText_ApprenticeWhichLevelMode13::
	.string "Gràcies. Molt amable!\n"
	.string "…Cof! Cof!\p"
	.string "Uf, m'he d'endurir ràpid…\p"
	.string "Aniré a la Torre de Combat de\n"
	.string "seguida, però què seria millor\l"
	.string "per a mi? Nivell 50 o Nivell Obert?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, d'acord. Això és {STR_VAR_1}.\n"
	.string "Hi aniré de seguida.\p"
	.string "Espero poder continuar comptant\n"
	.string "amb tu, ets el meu mentor!$"

gText_ApprenticePleaseTeach14::
	.string "Er… Em…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Si us plau, no em miris així.\n"
	.string "Em fas sentir cohibit.\p"
	.string "Jo… Soc {STR_VAR_1}.\p"
	.string "Em fa molta vergonya dir-ho,\n"
	.string "però exploro ruïnes antigues.\p"
	.string "Em fa encara més vergonya admetre\n"
	.string "que m'interessa la Frontera\l"
	.string "de Combat.\p"
	.string "{PLAYER}{KUN}, tens fama de ser\n"
	.string "un Entrenador dur…\p"
	.string "Em costa dir-ho,\n"
	.string "però vull demanar-te una cosa.\p"
	.string "Pots ser el meu mestre i\n"
	.string "donar-me consell?$"

gText_ApprenticeRejectTeaching14::
	.string "Si us plau, no em rebutgis així!\n"
	.string "No puc viure amb la humiliació.\p"
	.string "Si us plau, sigues el meu mestre!\n"
	.string "Necessito el teu consell!$"

gText_ApprenticeWhichLevelMode14::
	.string "G-gràcies…\p"
	.string "Però si us plau no em miris així.\n"
	.string "Em posa molt nerviós.\p"
	.string "Si us plau, respon-me sense\n"
	.string "mirar-me als ulls.\p"
	.string "A la Torre de Combat…\n"
	.string "Quin nivell hauria d'intentar?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… D'acord!\n"
	.string "Ho provaré.\p"
	.string "Espero poder fer un bon repte\n"
	.string "sense posar-me nerviós…\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a veure, espero\l"
	.string "que m'ajudis igual.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? Sembles ser {PLAYER}{KUN}…\n"
	.string "Però ets de veritat?\p"
	.string "Pots dir-me {STR_VAR_1}.\p"
	.string "He estat considerant la idea\n"
	.string "d'aprendre d'un Entrenador fort.\p"
	.string "Doncs, he de dir que tinc sort que\n"
	.string "hagis aparegut!\l"
	.string "…De veritat ets {PLAYER}{KUN}, oi?\p"
	.string "No, no, si ets real, cap problema.\n"
	.string "Simplement vull que em reconeguis\l"
	.string "com el teu aprenent.$"

gText_ApprenticeRejectTeaching15::
	.string "Oh?\n"
	.string "Però per què rebutjar-me?\p"
	.string "Demano disculpes per dubtar de\n"
	.string "la teva identitat.\p"
	.string "Si us plau, accepta les meves\n"
	.string "disculpes i accepta'm com a aprenent.$"

gText_ApprenticeWhichLevelMode15::
	.string "De veritat m'acceptes?\n"
	.string "No vull celebrar prematurament.\p"
	.string "Si és cert, demano disculpes.\n"
	.string "Però ara necessito el teu consell.\p"
	.string "Si entrés a la Torre de Combat,\n"
	.string "què seria digne de mi?\l"
	.string "Nivell 50 o Nivell Obert?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "N'estàs segur?\p"
	.string "Entenc. Si és el cas, perfecte.\n"
	.string "Et dono les gràcies pel teu temps.\p"
	.string "Sé que puc molestar, però m'alegra\n"
	.string "que m'hagis acceptat.\p"
	.string "Tornem-nos a veure!$"

gText_ApprenticeWhatHeldItem0::
	.string "Ai… Bua…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Tinc un dilema que\n"
	.string "no puc resoldre.\p"
	.string "No puc decidir què hauria de fer\n"
	.string "portar al meu {STR_VAR_1}.\p"
	.string "Digues-me, {PLAYER}.\n"
	.string "Quin objecte li hauria de fer portar?$"

gText_ApprenticeHoldNothing0::
	.string "Oh, de veritat? No hauria de fer\n"
	.string "portar res al meu {STR_VAR_1}?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Oh, d'acord! M'alegra que estigui\n"
	.string "resolt! Genial! Increïble! Uuuuh!\p"
	.string "Moltes gràcies!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, estic tan content…\n"
	.string "Crec que tinc aquest {STR_VAR_1}.\p"
	.string "M'alegra que estigui resolt!\n"
	.string "Genial! Increïble! Uuuuh!\p"
	.string "Moltes gràcies!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Buaaa! Si us plau, no siguis dolent!\p"
	.string "L'objecte {STR_VAR_1} ja me l'havien\n"
	.string "recomanat abans, bua…\p"
	.string "O vols dir que no hauria de fer\n"
	.string "portar res al meu {STR_VAR_2}?$"

gText_ApprenticeWhatHeldItem1::
	.string "Bé! És {PLAYER}!\n"
	.string "Genial! Volia preguntar-te una cosa!\p"
	.string "Fas portar objectes als teus Pokémon?\n"
	.string "Vull fer-ne portar als meus, però…\p"
	.string "Quin objecte seria bo per al\n"
	.string "meu {STR_VAR_1}?\p"
	.string "Què en penses?$"

gText_ApprenticeHoldNothing1::
	.string "Eh? Vols dir que el meu {STR_VAR_1}\n"
	.string "no ha de portar res?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Oh, entenc! Ho faré així!\n"
	.string "Gràcies per ensenyar-me!$"

gText_ApprenticeThanksHeldItem1::
	.string "Oh, uau! Un {STR_VAR_1}, oi?\n"
	.string "D'acord, ho faré!\p"
	.string "Gràcies per ensenyar-me!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, no, no és el que volia dir.\n"
	.string "Vull saber sobre un objecte diferent\l"
	.string "dels que ja conec.\p"
	.string "O vols dir que el meu Pokémon no\n"
	.string "ha de portar res aquest cop?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, hola!\n"
	.string "És sobre el meu {STR_VAR_1}…\p"
	.string "Vull fer-li portar un bon objecte.\n"
	.string "Què seria bo?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, el meu {STR_VAR_1} no ha de\n"
	.string "portar res?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "D'acord, entès!\n"
	.string "Ens veiem!$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, l'objecte {STR_VAR_1}?\n"
	.string "Entès!\p"
	.string "Faré tot el possible per trobar-ne un!\n"
	.string "Ens veiem!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Algú ja m'ha ensenyat sobre\n"
	.string "l'objecte {STR_VAR_1}.\p"
	.string "Vull que el meu Pokémon porti un\n"
	.string "tipus d'objecte diferent.\p"
	.string "O creus que {STR_VAR_2} no ha\n"
	.string "de portar res?$"

gText_ApprenticeWhatHeldItem3::
	.string "Hola, {PLAYER}…\n"
	.string "Perdona la molèstia, però tinc una\l"
	.string "altra cosa que preguntar-te.\p"
	.string "No crec que sigui prou bo per guanyar\n"
	.string "combats sol, així que penso fer\l"
	.string "portar un objecte al meu {STR_VAR_1}.\p"
	.string "Però no sé quin seria bo.\p"
	.string "{PLAYER}, si us plau, pots\n"
	.string "decidir per mi?$"

gText_ApprenticeHoldNothing3::
	.string "Un Pokémon d'algú com jo estaria\n"
	.string "millor sense objecte?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Entenc…\n"
	.string "Dius que no hauria de dependre dels\l"
	.string "objectes. Ho donaré tot!\p"
	.string "Moltes gràcies!$"

gText_ApprenticeThanksHeldItem3::
	.string "L'objecte {STR_VAR_1}, d'acord.\n"
	.string "No sé si el podré aconseguir…\l"
	.string "No! Ho donaré tot per trobar-lo.\p"
	.string "Moltes gràcies!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, però…\n"
	.string "Crec que ja m'han dit això abans…\p"
	.string "Potser és perquè no he gestionat\n"
	.string "bé l'objecte {STR_VAR_1}?\p"
	.string "O vols dir que no hauria de fer\n"
	.string "portar res al meu {STR_VAR_2}?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Volia preguntar-te una cosa.\p"
	.string "Saps que vas decidir quins\n"
	.string "Pokémon hauria de tenir?\p"
	.string "Però mai et vaig preguntar quin\n"
	.string "objecte hauria de portar.\p"
	.string "Ja que m'has donat consell,\n"
	.string "per què no acabar-ho?\p"
	.string "Què seria bo? Vull fer portar\n"
	.string "alguna cosa al meu {STR_VAR_1}.$"

gText_ApprenticeHoldNothing4::
	.string "Oh! El meu {STR_VAR_1} ha de fer-ho\n"
	.string "el millor que pugui sense res?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Si creus que és el millor, ho faré.\p"
	.string "Sabent que tu has decidit,\n"
	.string "{PLAYER}{KUN}, no em sabrà tant de greu\l"
	.string "si perdo.\p"
	.string "D'acord, comptaré amb tu!\n"
	.string "Adéu!$"

gText_ApprenticeThanksHeldItem4::
	.string "L'objecte {STR_VAR_1}, oi?\n"
	.string "No està malament. L'usaré!\p"
	.string "Sabent que tu has decidit,\n"
	.string "{PLAYER}{KUN}, no em sabrà tant de greu\l"
	.string "si perdo.\p"
	.string "D'acord, comptaré amb tu!\n"
	.string "Adéu!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Eh? Què dius?\n"
	.string "Ja m'havies parlat de {STR_VAR_1}\l"
	.string "abans.\p"
	.string "O vols dir que el meu {STR_VAR_2} ha de\n"
	.string "fer-ho sense res?$"

gText_ApprenticeWhatHeldItem5::
	.string "Ei, {PLAYER}{KUN}!\p"
	.string "Tots dos estem ocupats, però\n"
	.string "ens trobem sovint!\p"
	.string "Avui he de caminar, netejar\n"
	.string "i raspallar.\p"
	.string "Ni he tingut temps de comprar\n"
	.string "res per al meu {STR_VAR_1}.\p"
	.string "No tinc temps, així que per què no\n"
	.string "em dius què hauria de fer portar\l"
	.string "al meu {STR_VAR_1}?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, doncs estant jo tan ocupat,\n"
	.string "el meu {STR_VAR_1} no necessita res?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "D'acord, entès.\n"
	.string "No necessitaré temps per això.\p"
	.string "Gràcies per avui!\n"
	.string "Ens veiem!$"

gText_ApprenticeThanksHeldItem5::
	.string "D'acord, entès.\n"
	.string "Trobaré temps per buscar\l"
	.string "l'objecte {STR_VAR_1} que recomanaves.\p"
	.string "M'alegro d'haver trobat un bon\n"
	.string "mentor. Gràcies! Ens veiem!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Eh? Ja sé sobre\n"
	.string "l'objecte {STR_VAR_1}.\p"
	.string "Ah, ja ho entenc.\n"
	.string "Doncs estant jo tan ocupat,\l"
	.string "el meu {STR_VAR_2} no necessita res?$"

gText_ApprenticeWhatHeldItem6::
	.string "Ei, {PLAYER}! Soc jo!\n"
	.string "Necessito el teu consell avui també.\l"
	.string "Si us plau, aconsella'm!\p"
	.string "Redoble de tambor, si us plau!\n"
	.string "La pregunta que tinc és…\p"
	.string "Si vull fer portar un objecte al\n"
	.string "meu {STR_VAR_1}, quin hauria de ser?$"

gText_ApprenticeHoldNothing6::
	.string "De veritat? El meu {STR_VAR_1} no\n"
	.string "necessita portar cap objecte, dius.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "D'acord, faré això!\p"
	.string "Crec que això és tot el que volia\n"
	.string "preguntar-te avui.\p"
	.string "Tornem-nos a veure aquí, d'acord?\n"
	.string "Gràcies!$"

gText_ApprenticeThanksHeldItem6::
	.string "Ajà! Un {STR_VAR_1}.\n"
	.string "Quina elecció tan bona!\l"
	.string "Ho provaré segur!\p"
	.string "Crec que això és tot el que volia\n"
	.string "preguntar-te avui.\p"
	.string "Tornem-nos a veure aquí, d'acord?\n"
	.string "Gràcies!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahah! Que graciós!\n"
	.string "Ja m'havies dit sobre\l"
	.string "l'objecte {STR_VAR_1} abans!\p"
	.string "Estàs bé, {PLAYER}?\p"
	.string "Oh, espera! El meu {STR_VAR_2} no\n"
	.string "necessita portar cap objecte, dius.$"

gText_ApprenticeWhatHeldItem7::
	.string "Hola, {PLAYER}. Espero que\n"
	.string "estiguis bé.\p"
	.string "Puc demanar-te consell?\p"
	.string "En un combat recent, el meu rival\n"
	.string "semblava haver donat un objecte\l"
	.string "al seu Pokémon.\p"
	.string "Com a resultat, vaig perdre…\p"
	.string "No vull quedar-me enrere.\n"
	.string "Voldria fer portar un objecte\l"
	.string "al meu {STR_VAR_1} també.\p"
	.string "M'agradaria que decidissis\n"
	.string "què seria adequat per al meu Pokémon…$"

gText_ApprenticeHoldNothing7::
	.string "Vols dir… El meu Pokémon\n"
	.string "no necessita portar cap objecte?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Ara ho entenc clarament!\n"
	.string "Continuaré així.\p"
	.string "Gràcies, {PLAYER}.\n"
	.string "Espero poder comptar amb tu.\l"
	.string "Cuida't!$"

gText_ApprenticeThanksHeldItem7::
	.string "Un {STR_VAR_1}, doncs!\n"
	.string "L'encarregaré de seguida.\p"
	.string "Gràcies, {PLAYER}.\n"
	.string "Espero poder comptar amb tu.\l"
	.string "Cuida't!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Ja m'ho havies dit,\n"
	.string "i ja el tinc.\p"
	.string "O vols dir… El meu Pokémon\n"
	.string "no necessita portar cap objecte?$"

gText_ApprenticeWhatHeldItem8::
	.string "Ei! {PLAYER}!\n"
	.string "Estic… Estic tan content de veure't!\p"
	.string "Oh-oh-oh! Hi ha una cosa que\n"
	.string "t'havia de preguntar, {PLAYER}!\p"
	.string "Si us plau, decideix què hauria\n"
	.string "de portar el meu {STR_VAR_1}!$"

gText_ApprenticeHoldNothing8::
	.string "Oh, uau! No m'esperava la resposta!\n"
	.string "Doncs, no cal un objecte?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Perfectament entès!\n"
	.string "Continuaré sense objecte!\p"
	.string "Espero que vulguis ensenyar-me\n"
	.string "més coses un altre dia.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! L'usaré!\p"
	.string "Em… Potser tu, {PLAYER}, també\n"
	.string "fas portar aquest objecte\l"
	.string "als teus Pokémon?\p"
	.string "El buscaré segur!\n"
	.string "Espero que vulguis ensenyar-me\l"
	.string "més coses un altre dia.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Oh? Ja m'havies recomanat\n"
	.string "l'objecte {STR_VAR_1} abans.\p"
	.string "O és el millor per portar?\n"
	.string "O vols dir que el meu {STR_VAR_2}\l"
	.string "no necessita portar res?$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola!\n"
	.string "El meu mestre, {PLAYER}{KUN}!\p"
	.string "Vull demanar-te consell sobre\n"
	.string "eines Pokémon.\p"
	.string "Què creus que seria bo que portés\n"
	.string "el meu {STR_VAR_1}?\p"
	.string "No siguis tímid.\n"
	.string "Digues-m'ho!$"

gText_ApprenticeHoldNothing9::
	.string "Oh? Doncs, dius que el meu {STR_VAR_1}\n"
	.string "pot guanyar sense portar res?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Sí, molt bé!\n"
	.string "Ho donaré tot!\p"
	.string "D'acord, gràcies, com sempre!\n"
	.string "Adéu!$"

gText_ApprenticeThanksHeldItem9::
	.string "Ajà, és un {STR_VAR_1}?\n"
	.string "Sí, molt bé!\l"
	.string "En buscaré un de seguida!\p"
	.string "D'acord, gràcies, com sempre!\n"
	.string "Adéu!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "No, no! Ja m'havies parlat de\n"
	.string "l'objecte {STR_VAR_1} abans.\p"
	.string "Oh, espera un moment…\n"
	.string "Doncs, dius que el meu {STR_VAR_2}\l"
	.string "pot guanyar sense portar res?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, ha passat una cosa\n"
	.string "increïble!\p"
	.string "M'he despertat i el meu Pokémon\n"
	.string "tenia 10 PEPITES!\p"
	.string "És clar que és mentida!\n"
	.string "Wahahaha!\p"
	.string "Però això no és mentida.\n"
	.string "No soc gaire bo triant objectes\l"
	.string "per als Pokémon.\p"
	.string "Doncs, per què no decideixes\n"
	.string "què ha de portar el meu {STR_VAR_1},\l"
	.string "mestre?$"

gText_ApprenticeHoldNothing10::
	.string "Què vol dir?\n"
	.string "Que no li faci portar res?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "D'acord, no ha de portar res.\n"
	.string "Doncs hauria de buscar-li alguna cosa!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies, mestre!\n"
	.string "Espero que continuïs ensenyant-me!$"

gText_ApprenticeThanksHeldItem10::
	.string "D'acord, és un {STR_VAR_1}!\n"
	.string "Li faré portar qualsevol altra cosa!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies, mestre!\n"
	.string "Espero que continuïs ensenyant-me!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Em, ja m'ho havies dit abans,\n"
	.string "no?\p"
	.string "No hi ha res més?\p"
	.string "O vols dir que no faci portar\n"
	.string "res al meu {STR_VAR_2}?$"

gText_ApprenticeWhatHeldItem11::
	.string "H-O-L-A!\n"
	.string "I això diu hola!\p"
	.string "El Mariner raper soc jo!\n"
	.string "Et presento una pregunta\l"
	.string "que és molt maca!\p"
	.string "És una pregunta d'objecte\n"
	.string "que reclama el teu suggeriment!\p"
	.string "El meu {STR_VAR_1} necessita un objecte,\n"
	.string "quin hauria de ser, si puc dir-ho?$"

gText_ApprenticeHoldNothing11::
	.string "De veritat?\n"
	.string "El meu {STR_VAR_1} no necessita\l"
	.string "portar res de res?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "D'acord, t'entenc, segur que sí!\n"
	.string "El meu Pokémon anirà sense res!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, seguiré les teves paraules!$"

gText_ApprenticeThanksHeldItem11::
	.string "D'acord, un {STR_VAR_1},\n"
	.string "és el que usaré.\l"
	.string "He fet bé de fer-te triar!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, seguiré les teves paraules!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "D'acord, un {STR_VAR_1}, dius?\n"
	.string "Ja m'ho vas dir l'altre dia.\l"
	.string "Necessito una idea nova.\p"
	.string "O, què, de veritat?\n"
	.string "El meu Pokémon no necessita\l"
	.string "portar res de res?$"

gText_ApprenticeWhatHeldItem12::
	.string "Ei, {PLAYER}!\n"
	.string "T'he trobat avui!\p"
	.string "Què hauria de fer? Demanar consell?\n"
	.string "Per què no? Ja t'estic parlant!\p"
	.string "{PLAYER}, ja n'estàs tip de mi?\n"
	.string "No, impossible.\p"
	.string "M'escoltes?\n"
	.string "Busco consell, d'això es tracta.\p"
	.string "Es tracta d'un objecte per al\n"
	.string "meu {STR_VAR_1} que sigui bo.\l"
	.string "La indecisió em mata.$"

gText_ApprenticeHoldNothing12::
	.string "El meu {STR_VAR_1} no necessita res?\n"
	.string "No ha de portar res?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Si no portar res és el millor,\n"
	.string "faré el que dius!\p"
	.string "Bé, {PLAYER}, he d'anar per lliure,\n"
	.string "però no m'oblidis.\p"
	.string "Ens veiem, amic llest!$"

gText_ApprenticeThanksHeldItem12::
	.string "Si portar l'objecte {STR_VAR_1} és\n"
	.string "el millor, faré el que dius!\p"
	.string "Bé, {PLAYER}, he d'anar per lliure,\n"
	.string "però no m'oblidis.\p"
	.string "Ens veiem, amic llest!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "No he sentit parlar d'aquest\n"
	.string "{STR_VAR_1} abans?\l"
	.string "Segur que sí!\p"
	.string "Necessito alguna cosa nova!\n"
	.string "O, el meu {STR_VAR_2} no necessita res?\l"
	.string "No ha de portar res?$"

gText_ApprenticeWhatHeldItem13::
	.string "Au! Ai! {PLAYER}{KUN}, tinc el braç trencat!\n"
	.string "No el toquis, si us plau!\p"
	.string "Me'l dec haver trencat provant\n"
	.string "objectes amb el meu grup\l"
	.string "de Pokémon.\p"
	.string "Doncs, les coses essent com són,\n"
	.string "necessito que decideixis per mi.\p"
	.string "{PLAYER}{KUN}, què creus que seria bo\n"
	.string "que portés el meu {STR_VAR_1}?$"

gText_ApprenticeHoldNothing13::
	.string "Au…\p"
	.string "Doncs suggeresques que el meu\n"
	.string "{STR_VAR_1} no ha de portar res?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, d'acord. Seria més fàcil\n"
	.string "per a mi, tal com estic ara.\p"
	.string "Espero poder continuar comptant\n"
	.string "amb tu.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, d'acord. Un {STR_VAR_1}.\n"
	.string "El braç del meu Pokémon està bé,\l"
	.string "li faré portar l'objecte de seguida.\p"
	.string "Espero poder continuar comptant\n"
	.string "amb tu.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "No, no, ja m'havies dit sobre\n"
	.string "l'objecte {STR_VAR_1}, recordes?\p"
	.string "Què tal si em dius alguna cosa\n"
	.string "encara millor?\p"
	.string "Oh, espera un moment.\n"
	.string "Doncs suggeresques que el meu\l"
	.string "{STR_VAR_2} no ha de portar res?$"

gText_ApprenticeWhatHeldItem14::
	.string "Er… Em…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Si us plau, no em miris així.\n"
	.string "Els meus Pokémon no tenen res.\p"
	.string "Jo… Em fa molta vergonya, però\n"
	.string "necessito el teu consell.\p"
	.string "No puc decidir quin objecte faria\n"
	.string "fort el meu {STR_VAR_1}.\p"
	.string "{PLAYER}{KUN}, què creus que\n"
	.string "seria bo?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Doncs, creus que seria millor\n"
	.string "si el meu {STR_VAR_1} no tingués objecte?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… D'acord!\n"
	.string "Aniré sense objecte.\p"
	.string "Fa respecte, però.\n"
	.string "No seria massa arriscat?\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a veure, espero\l"
	.string "que m'ajudis igual.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… D'acord!\n"
	.string "Faré servir l'objecte {STR_VAR_1}.\p"
	.string "Fa respecte, però.\n"
	.string "No seria massa arriscat?\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a veure, espero\l"
	.string "que m'ajudis igual.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "P-però ja m'havien dit això.\p"
	.string "Si us plau, no em rebutgis així!\n"
	.string "No puc viure amb la humiliació.\p"
	.string "Oh… Estic traient conclusions?\n"
	.string "Creus que seria millor si\l"
	.string "el meu {STR_VAR_2} no tingués objecte?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm? Sembles ser {PLAYER}{KUN}…\n"
	.string "Però ets de veritat?\l"
	.string "Potser ets un bessó?\p"
	.string "Oh, no, no, no, no et preocupis!\n"
	.string "Si de veritat ets {PLAYER}, si us plau\l"
	.string "oblida la meva falta d'educació.\p"
	.string "El que voldria és més del teu\n"
	.string "bon consell.\p"
	.string "Tinc aquí el meu {STR_VAR_1} i voldria\n"
	.string "fer-li portar un objecte útil.\p"
	.string "Quin seria digne?$"

gText_ApprenticeHoldNothing15::
	.string "Seria millor si no portés res?\n"
	.string "N'estàs segur?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Entenc. Si és el cas, perfecte.\n"
	.string "Et dono les gràcies pel teu temps.\p"
	.string "Tornem-nos a veure!$"

gText_ApprenticeThanksHeldItem15::
	.string "Un {STR_VAR_1}?\n"
	.string "N'estàs segur?\p"
	.string "Entenc. Si és el cas, perfecte.\n"
	.string "Et dono les gràcies pel teu temps.\p"
	.string "Espero que el meu Pokémon en pugui\n"
	.string "fer bon ús.\p"
	.string "Tornem-nos a veure!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "No, no, espera un moment.\n"
	.string "Crec que ja m'ho havies ensenyat.\p"
	.string "Voldria que em recomanessis\n"
	.string "alguna cosa diferent.\p"
	.string "Potser suggereixes que el meu\n"
	.string "{STR_VAR_2} no hauria de portar res?\l"
	.string "N'estàs segur?$"

gText_ApprenticeWhichMonFirst0::
	.string "Buaaa, {PLAYER}!\n"
	.string "Tinc un dilema, bua…\p"
	.string "Vull començar a combatre, però\n"
	.string "no sé què fer.\p"
	.string "Com hauria d'ordenar els meus\n"
	.string "Pokémon perquè siguin més forts?\p"
	.string "Digues-me, {PLAYER}.\n"
	.string "Si fossis jo, quin d'aquests\l"
	.string "Pokémon enviaries primer?$"

gText_ApprenticeMonFirstThanks0::
	.string "El meu {STR_VAR_1} primer?\n"
	.string "Buaaaaa!\p"
	.string "Oh! Ho sento molt!\n"
	.string "M'has fet tan feliç triant el\l"
	.string "primer Pokémon que ploro…\p"
	.string "Moltes gràcies!$"

gText_ApprenticeWhichMonFirst1::
	.string "Bé! És {PLAYER}!\n"
	.string "Genial! Volia preguntar-te una cosa!\p"
	.string "Dels meus Pokémon, quin creus\n"
	.string "que hauria de sortir primer?$"

gText_ApprenticeMonFirstThanks1::
	.string "El meu {STR_VAR_1}? Tens raó.\n"
	.string "D'acord, ho faré!\p"
	.string "Gràcies per ensenyar-me!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, hola!\p"
	.string "Crec que, en un combat, és molt\n"
	.string "important quin Pokémon surt primer.\p"
	.string "Dels Pokémon que tinc, quin\n"
	.string "seria bo enviar primer?$"

gText_ApprenticeMonFirstThanks2::
	.string "El meu {STR_VAR_1} primer?\n"
	.string "D'acord, entès!\p"
	.string "Ens veiem!$"

gText_ApprenticeWhichMonFirst3::
	.string "Hola, {PLAYER}…\n"
	.string "Perdona per molestar-te amb\l"
	.string "una altra pregunta.\p"
	.string "Tinc tan poca confiança que no\n"
	.string "sé què faria sense tu, {PLAYER}.\p"
	.string "Potser és una pèrdua de temps\n"
	.string "preocupar-me'n, però no puc\l"
	.string "decidir una cosa…\p"
	.string "Quin dels meus Pokémon hauria\n"
	.string "d'enviar primer en un combat?$"

gText_ApprenticeMonFirstThanks3::
	.string "El meu {STR_VAR_1}?\n"
	.string "Entès!\p"
	.string "No em puc creure que et molestis\n"
	.string "a respondre les meves preguntes!\p"
	.string "Estic tan agraït que fins i tot\n"
	.string "em parlis… Gràcies!$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN}! Soc jo!\n"
	.string "M'alegro de veure't perquè tinc\l"
	.string "un petit problema.\p"
	.string "No puc decidir com ordenar els meus\n"
	.string "Pokémon. Pots decidir per mi?\p"
	.string "Oh, no cal que decideixis tot\n"
	.string "l'equip ara.\p"
	.string "Què tal decidir només el primer\n"
	.string "Pokémon?$"

gText_ApprenticeMonFirstThanks4::
	.string "El meu {STR_VAR_1}? Genial!\p"
	.string "Sabent que tu has decidit,\n"
	.string "{PLAYER}{KUN}, no em sabrà tant de greu\l"
	.string "si perdo.\p"
	.string "D'acord, comptaré amb tu!\n"
	.string "Adéu!$"

gText_ApprenticeWhichMonFirst5::
	.string "Hola, mestre {PLAYER}{KUN}!\n"
	.string "Avui estic ocupat una altra vegada!\p"
	.string "He de fer ciclisme, compres\n"
	.string "i cantussejar.\p"
	.string "Ni he tingut temps de decidir\n"
	.string "com ordenar el meu equip Pokémon.\p"
	.string "Doncs, per què no revises l'equip?\n"
	.string "Quin hauria de sortir primer?$"

gText_ApprenticeMonFirstThanks5::
	.string "D'acord, entès.\n"
	.string "Almenys tinc temps per posar\l"
	.string "el meu {STR_VAR_1} al capdavant!\p"
	.string "Ui, la meva xicota m'espera!\n"
	.string "Gràcies! Ens veiem!$"

gText_ApprenticeWhichMonFirst6::
	.string "Iuhu! Ei, {PLAYER}!\n"
	.string "Sempre vas amb pinta de dur!\p"
	.string "Escolta, necessito una altra cosa!\n"
	.string "El de sempre!\p"
	.string "Redoble de tambor, si us plau!\n"
	.string "La pregunta és sobre el meu equip.\p"
	.string "Quin Pokémon meu hauria de ser el\n"
	.string "primer en sortir a combatre?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm!\n"
	.string "El meu {STR_VAR_1}, dius!\l"
	.string "Gràcies per una resposta genial!\p"
	.string "Crec que això és tot el que volia\n"
	.string "preguntar-te avui.\p"
	.string "Tornem-nos a veure aquí, d'acord?\n"
	.string "Gràcies!$"

gText_ApprenticeWhichMonFirst7::
	.string "Moltes gràcies per parar-te a\n"
	.string "parlar amb mi, {PLAYER}.\p"
	.string "Sé que abuso de la teva amabilitat,\n"
	.string "però puc demanar-te consell?\p"
	.string "Voldria que decidissis l'ordre\n"
	.string "del meu equip Pokémon.\p"
	.string "M'agradaria que decidissis\n"
	.string "quin Pokémon ha de ser el primer.$"

gText_ApprenticeMonFirstThanks7::
	.string "El meu {STR_VAR_1}!\n"
	.string "El posaré primer de seguida!\p"
	.string "Gràcies, {PLAYER}.\n"
	.string "Espero poder comptar amb tu.\l"
	.string "Cuida't!$"

gText_ApprenticeWhichMonFirst8::
	.string "Ei! {PLAYER}!\n"
	.string "Estic… Estic tan content de veure't!\p"
	.string "Els meus Pokémon s'han tornat\n"
	.string "molt més forts!\p"
	.string "Però no sempre guanyo. Sembla que\n"
	.string "depèn de quin Pokémon va primer.\p"
	.string "{PLAYER}, si us plau, necessito ajuda!\p"
	.string "Decideix quin dels meus Pokémon\n"
	.string "ha de sortir primer!$"

gText_ApprenticeMonFirstThanks8::
	.string "Ai… Estic aclaparat de felicitat…\p"
	.string "És com un somni que tu decideixis\n"
	.string "per mi, {PLAYER}.\p"
	.string "Però perfectament entès!\n"
	.string "El meu {STR_VAR_1} anirà primer!\p"
	.string "Espero que vulguis ensenyar-me\n"
	.string "més coses un altre dia.$"

gText_ApprenticeWhichMonFirst9::
	.string "Hola, hola!\n"
	.string "El meu mentor, {PLAYER}{KUN}!\l"
	.string "Dóna'm el teu savi consell avui!\p"
	.string "Mira, he reunit un equip de\n"
	.string "tres Pokémon. Fins aquí bé.\p"
	.string "Però l'ordre de combat de l'equip\n"
	.string "encara no està decidit.\p"
	.string "Aquí és on entres tu, {PLAYER}{KUN}!\n"
	.string "Decideix quin Pokémon va primer!\p"
	.string "No siguis tímid.\n"
	.string "Digues-m'ho!$"

gText_ApprenticeMonFirstThanks9::
	.string "Ajà, el meu {STR_VAR_1} va primer!\n"
	.string "OK, perfecte!\l"
	.string "Canviaré l'ordre de seguida!\p"
	.string "D'acord, gràcies, com sempre!\n"
	.string "Adéu!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, escolta!\n"
	.string "Una crisi!\p"
	.string "Els meus Pokémon, tots tres, surten\n"
	.string "a combatre alhora!\p"
	.string "És clar que és impossible!\n"
	.string "Wahahaha!\p"
	.string "Però això no és mentida.\n"
	.string "No soc gaire bo decidint com\l"
	.string "ordenar els meus Pokémon.\p"
	.string "Doncs, per què no decideixes per mi\n"
	.string "quin Pokémon va primer, mestre?$"

gText_ApprenticeMonFirstThanks10::
	.string "D'acord, has triat el meu {STR_VAR_1}?\n"
	.string "Faré sortir qualsevol altre primer!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies, mestre!\n"
	.string "Espero que continuïs ensenyant-me!$"

gText_ApprenticeWhichMonFirst11::
	.string "H-O-L-A!\n"
	.string "I això diu hola!\p"
	.string "El Mariner raper soc jo!\n"
	.string "Et presento una pregunta\l"
	.string "que és molt maca!\p"
	.string "És una pregunta d'ordre d'equip\n"
	.string "que reclama el teu suggeriment!\p"
	.string "D'aquest grup, qui hauria de sortir\n"
	.string "primer al lloc indicat?$"

gText_ApprenticeMonFirstThanks11::
	.string "D'acord, t'entenc, segur que sí!\n"
	.string "Els canviaré d'ordre, sí senyor!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, seguiré les teves paraules!$"

gText_ApprenticeWhichMonFirst12::
	.string "Ei, {PLAYER}!\n"
	.string "Com estàs?\p"
	.string "Què hauria de fer? Demanar consell?\n"
	.string "Sí! Tinc alguna cosa a preguntar!\l"
	.string "Em sents?\l"
	.string "Em sents!\p"
	.string "Has de decidir, quin dels meus\n"
	.string "Pokémon és el primer en sortir!\l"
	.string "A combatre, vull dir.$"

gText_ApprenticeMonFirstThanks12::
	.string "El meu {STR_VAR_1}? Sí!\n"
	.string "Va bé, cap problema!\p"
	.string "Bé, {PLAYER}, he d'anar per lliure,\n"
	.string "però no m'oblidis.\p"
	.string "Ens veiem, amic llest!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Uf…ai… {PLAYER}{KUN}…\n"
	.string "M'ha començat a fer mal la panxa…\p"
	.string "…Ja va millorant…\p"
	.string "M'he degut posar malalt de tant\n"
	.string "pensar com ordenar el meu\l"
	.string "grup de Pokémon.\p"
	.string "Doncs, les coses essent com són,\n"
	.string "necessito que decideixis per mi.\p"
	.string "{PLAYER}{KUN}, quin dels meus Pokémon\n"
	.string "ha de sortir primer? Per guanyar.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, d'acord.\n"
	.string "El meu {STR_VAR_1} va primer.\p"
	.string "Canviaré l'ordre després\n"
	.string "de sopar.\p"
	.string "Espero poder continuar comptant\n"
	.string "amb tu.$"

gText_ApprenticeWhichMonFirst14::
	.string "Er… Em…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Si us plau, no em miris així.\n"
	.string "Em fa sentir molt nerviós.\p"
	.string "Em…\n"
	.string "Necessito el teu consell.\p"
	.string "Em fa vergonya dir-ho, però\n"
	.string "he triat el meu equip de 3 Pokémon.\l"
	.string "No puc decidir l'ordre, però.\p"
	.string "Quin Pokémon hauria d'enviar primer\n"
	.string "per semblar almenys competent?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… D'acord!\n"
	.string "Començaré amb el meu {STR_VAR_1}.\p"
	.string "Espero poder-ho fer bé sense\n"
	.string "posar-me nerviós.\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a veure, espero\l"
	.string "que m'ajudis igual.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? Sembles ser {PLAYER}{KUN}…\n"
	.string "Però ets de veritat?\l"
	.string "Potser ets un doble intel·ligent?\p"
	.string "Oh, no, no, no, no et preocupis!\n"
	.string "Si de veritat ets {PLAYER}, si us plau\l"
	.string "oblida la meva falta d'educació.\p"
	.string "El que voldria és el teu bon consell.\p"
	.string "Tinc aquí el meu equip Pokémon.\n"
	.string "Voldria que em diguessis quin\l"
	.string "ha de sortir primer a combatre.$"

gText_ApprenticeMonFirstThanks15::
	.string "El meu {STR_VAR_1}…\n"
	.string "No m'estàs enganyant?\p"
	.string "Entenc. Si és el cas, perfecte.\n"
	.string "Et dono les gràcies pel teu temps.\p"
	.string "Soc com soc, però ho donaré\n"
	.string "tot.\p"
	.string "Tornem-nos a veure!$"

gText_ApprenticeWhichMon0::
	.string "Snif…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Quin moment perfecte!\n"
	.string "Hi ha una cosa que no puc decidir…\p"
	.string "No puc decidir quin Pokémon\n"
	.string "hauria d'usar.\p"
	.string "No puc decidir entre els Pokémon\n"
	.string "{STR_VAR_1} i {STR_VAR_2}…\p"
	.string "{PLAYER}, quin creus que em donaria\n"
	.string "una oportunitat de guanyar?$"

gText_ApprenticeMonThanks0::
	.string "Snif… Entenc!\n"
	.string "Oh! Ho sento molt!\l"
	.string "M'has fet tan feliç que ploro…\p"
	.string "Faré tot el possible per atrapar\n"
	.string "un {STR_VAR_1}!\p"
	.string "Moltes gràcies!$"

gText_ApprenticeWhichMon1::
	.string "Bé! És {PLAYER}!\n"
	.string "Bé, has vingut en bon moment!\l"
	.string "Necessito el teu consell!\p"
	.string "Em, estic confós: hauria d'usar\n"
	.string "el meu {STR_VAR_1} o {STR_VAR_2}…\p"
	.string "Quin creus que hauria de criar,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Oh, doncs el meu {STR_VAR_1} és millor!\n"
	.string "D'acord, ho faré!\p"
	.string "Gràcies per ensenyar-me!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, hola!\n"
	.string "Tinc una pregunta.\p"
	.string "Tinc un dilema sobre si hauria de\n"
	.string "criar un {STR_VAR_1} o {STR_VAR_2}.\p"
	.string "Quin Pokémon creus que serà\n"
	.string "més fort?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} és la teva elecció?\n"
	.string "D'acord, entès!\p"
	.string "Aniré a atrapar un {STR_VAR_1} fort\n"
	.string "de seguida!\p"
	.string "Ens veiem!$"

gText_ApprenticeWhichMon3::
	.string "Hola, {PLAYER}…\p"
	.string "Em… probablement ja t'has oblidat\n"
	.string "d'algú com jo…\p"
	.string "…Però tant se val si em pots\n"
	.string "donar consell…\p"
	.string "No puc decidir quin tipus de\n"
	.string "Pokémon hauria de criar…\p"
	.string "He reduït les opcions als Pokémon\n"
	.string "{STR_VAR_1} i {STR_VAR_2}, però aquí\l"
	.string "m'he encallat…\p"
	.string "{PLAYER}, segurament no vols\n"
	.string "molestar-te, però decideix per mi.$"

gText_ApprenticeMonThanks3::
	.string "Però un {STR_VAR_1} salvatge em farà\n"
	.string "cas?\p"
	.string "Ho intentaré!\p"
	.string "Però podré atrapar-ne un…\n"
	.string "No! Ho donaré tot!\p"
	.string "Gràcies!$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN}! M'alegro de veure't!\n"
	.string "Estava a punt d'anar a buscar-te!\p"
	.string "Pots decidir quin tipus de Pokémon\n"
	.string "hauria d'usar?\p"
	.string "Per exemple…\n"
	.string "Què tal els Pokémon {STR_VAR_1}\l"
	.string "i {STR_VAR_2}?\p"
	.string "Quin creus que seria\n"
	.string "millor?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Genial!\p"
	.string "Sabent que tu has decidit,\n"
	.string "{PLAYER}{KUN}, no em sabrà tant de greu\l"
	.string "si perdo.\p"
	.string "D'acord, comptaré amb tu!\n"
	.string "Adéu!$"

gText_ApprenticeWhichMon5::
	.string "Si no és {PLAYER}{KUN}! Com va?\n"
	.string "Avui estic ocupat com sempre!\p"
	.string "Vull fer-ho bé amb Pokémon, però\n"
	.string "no he pogut decidir quin Pokémon\l"
	.string "hauria d'usar.\p"
	.string "Saps que {STR_VAR_1} semblen forts?\n"
	.string "Però {STR_VAR_2} també impressionen.\p"
	.string "{PLAYER}{KUN}, dóna'm un bon consell!\n"
	.string "Quin seria bo per a mi?$"

gText_ApprenticeMonThanks5::
	.string "D'acord, entès.\n"
	.string "Trobaré temps per atrapar\l"
	.string "el {STR_VAR_1} que m'has recomanat.\p"
	.string "M'alegro d'haver trobat un bon\n"
	.string "mentor. Gràcies! Ens veiem!$"

gText_ApprenticeWhichMon6::
	.string "Oh!\n"
	.string "Bé, és {PLAYER}!\p"
	.string "He anat de seguida a presumir\n"
	.string "als meus amics d'haver-te conegut!\p"
	.string "Necessito el teu consell avui també.\n"
	.string "Per a tu serà fàcil!\p"
	.string "Redoble de tambor, si us plau!\n"
	.string "La pregunta que tinc és…\p"
	.string "Si criés un Pokémon, i les opcions\n"
	.string "fossin {STR_VAR_1} o {STR_VAR_2},\l"
	.string "quin hauria de ser?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, dius!\l"
	.string "Gràcies per una resposta genial!\p"
	.string "Crec que això és tot el que volia\n"
	.string "preguntar-te avui.\p"
	.string "Tornem-nos a veure aquí, d'acord?\n"
	.string "Gràcies!$"

gText_ApprenticeWhichMon7::
	.string "Oh, ets tu, {PLAYER}?\n"
	.string "Estic encantat de veure't!\p"
	.string "Des que soc el teu aprenent,\n"
	.string "la meva confiança ha crescut.\p"
	.string "Crec que estic preparat per criar\n"
	.string "un Pokémon pel meu compte!\p"
	.string "{PLAYER}, puc demanar-te que triïs\n"
	.string "quin Pokémon hauria de criar?\p"
	.string "Les opcions són els Pokémon\n"
	.string "{STR_VAR_1} o {STR_VAR_2}…\l"
	.string "Quin Pokémon és el bo per a mi?$"

gText_ApprenticeMonThanks7::
	.string "Un {STR_VAR_1}, doncs!\n"
	.string "En buscaré un de seguida!\p"
	.string "Gràcies, {PLAYER}.\n"
	.string "Espero poder comptar amb tu.\l"
	.string "Cuida't!$"

gText_ApprenticeWhichMon8::
	.string "Ei! {PLAYER}! T'he tornat a trobar!\n"
	.string "Estic… Estic tan content!\p"
	.string "Oh-oh-oh, ja ho sé!\n"
	.string "No hauria de desaprofitar l'ocasió!\p"
	.string "Puc demanar-te un gran favor,\n"
	.string "{PLAYER}? Tria un Pokémon per a mi!\p"
	.string "Decideix quin seria millor,\n"
	.string "{STR_VAR_1} o {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Uau! Has decidit per mi!\n"
	.string "Criaré un {STR_VAR_1} el millor\l"
	.string "que pugui.\p"
	.string "Espero que vulguis ensenyar-me\n"
	.string "més coses un altre dia.$"

gText_ApprenticeWhichMon9::
	.string "Ei, ei!\n"
	.string "El meu mentor, {PLAYER}{KUN}!\p"
	.string "Hola, t'he estat buscant per\n"
	.string "més del teu savi consell!\p"
	.string "Quin Pokémon seria bo per a mi,\n"
	.string "un {STR_VAR_1} o {STR_VAR_2}?\p"
	.string "No siguis tímid.\n"
	.string "Digues-m'ho!$"

gText_ApprenticeMonThanks9::
	.string "Ajà, un {STR_VAR_1}, doncs!\n"
	.string "OK, perfecte!\l"
	.string "En caçaré un amb una Ball!\p"
	.string "D'acord, gràcies, com sempre!\n"
	.string "Adéu!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, escolta! Gran notícia!\n"
	.string "He atrapat un Pokémon miratge!\p"
	.string "És clar que és mentida!\n"
	.string "Wahahaha!\p"
	.string "Però això no és mentida.\n"
	.string "No soc gaire bo atrapant\l"
	.string "Pokémon.\p"
	.string "Doncs, per què no decideixes per mi\n"
	.string "quin Pokémon hauria d'atrapar,\l"
	.string "mestre?\p"
	.string "Quin seria millor?\n"
	.string "{STR_VAR_1} o {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "D'acord, has triat {STR_VAR_1}?\n"
	.string "Doncs agafaré l'altre!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies, mestre!\n"
	.string "Espero que continuïs ensenyant-me!$"

gText_ApprenticeWhichMon11::
	.string "H-O-L-A!\n"
	.string "I això diu hola!\p"
	.string "El Mariner raper soc jo!\n"
	.string "Segur que recordes qui soc!\p"
	.string "Avui tinc una pregunta de Pokémon\n"
	.string "que reclama el teu suggeriment!\p"
	.string "Puc triar entre {STR_VAR_1}\n"
	.string "i {STR_VAR_2}, ja ho veus.\l"
	.string "Quin he d'atrapar?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, dius, ei, ei!\n"
	.string "N'aniré a buscar un de seguida!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, seguiré les teves paraules!$"

gText_ApprenticeWhichMon12::
	.string "Oh, uau, si és {PLAYER}!\p"
	.string "Què hauria de fer? Demanar consell?\n"
	.string "Per què no? Ja t'estic parlant!\p"
	.string "Fa temps. Trenquem el gel.\n"
	.string "També busco consell!\l"
	.string "Em sents?\l"
	.string "Em sents!\p"
	.string "Els meus Pokémon, quin uso?\n"
	.string "És {STR_VAR_1} o {STR_VAR_2}.\l"
	.string "Quin tries?$"

gText_ApprenticeMonThanks12::
	.string "Si {STR_VAR_1} és el millor,\n"
	.string "faré el que dius!\p"
	.string "Bé, {PLAYER}, he d'anar per lliure,\n"
	.string "però no m'oblidis.\p"
	.string "Ens veiem, amic llest!$"

gText_ApprenticeWhichMon13::
	.string "Oh, hola, {PLAYER}{KUN}…\n"
	.string "Tinc un mal de cap horrible…\p"
	.string "M'he degut preocupar massa pel\n"
	.string "tipus de Pokémon que hauria de criar.\p"
	.string "Doncs, les coses essent com són,\n"
	.string "necessito que decideixis per mi.\p"
	.string "{PLAYER}{KUN}, si hagués de triar entre\n"
	.string "els Pokémon {STR_VAR_1} i\l"
	.string "{STR_VAR_2}, quin hauria de ser?$"

gText_ApprenticeMonThanks13::
	.string "Hm, un {STR_VAR_1}, d'acord.\n"
	.string "N'aniré a buscar un quan millori.\p"
	.string "Espero poder continuar comptant\n"
	.string "amb tu.$"

gText_ApprenticeWhichMon14::
	.string "Er… Em…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Si us plau, no em miris així.\n"
	.string "Em poso molt nerviós…\l"
	.string "Ne… Necessito el teu consell.\p"
	.string "Em… Em fa molta vergonya, però no\n"
	.string "puc decidir quin Pokémon usar.\p"
	.string "Si les opcions fossin {STR_VAR_1} o\n"
	.string "{STR_VAR_2}, quin seria millor?$"

gText_ApprenticeMonThanks14::
	.string "Oh… D'acord!\n"
	.string "Ho donaré tot amb un {STR_VAR_1}.\p"
	.string "Espero poder-ho fer bé sense\n"
	.string "posar-me nerviós.\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a veure, espero\l"
	.string "que m'ajudis igual.$"

gText_ApprenticeWhichMon15::
	.string "Hm? Sembles ser {PLAYER}{KUN}…\n"
	.string "Però ets de veritat?\p"
	.string "No, no, si ets real, cap problema.\n"
	.string "Per cert, voldria demanar-te\l"
	.string "consell.\p"
	.string "És sobre el Pokémon que he d'usar.\p"
	.string "Si les opcions són els Pokémon\n"
	.string "{STR_VAR_1} i {STR_VAR_2}, quin és\l"
	.string "més digne de mi?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "N'estàs segur?\p"
	.string "Entenc. Si és el cas, perfecte.\n"
	.string "Et dono les gràcies pel teu temps.\p"
	.string "Espero que sigui alguna cosa que\n"
	.string "fins i tot jo pugui gestionar.\p"
	.string "Tornem-nos a veure!$"

gText_ApprenticeWhichMove0::
	.string "Buaaa! Oh, {PLAYER}!\n"
	.string "Snif… Xip…\p"
	.string "Tinc un dilema!\n"
	.string "No puc decidir un moviment per\l"
	.string "al meu {STR_VAR_1}…\p"
	.string "Si us plau, {PLAYER}.\n"
	.string "Pots decidir per mi?\p"
	.string "Per al meu {STR_VAR_1}, quin moviment\n"
	.string "seria millor: {STR_VAR_2}\l"
	.string "o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Buaaaaa!\p"
	.string "Oh! Perdona, {PLAYER}!\n"
	.string "M'has fet tan feliç decidint\l"
	.string "el moviment que ploro…\p"
	.string "Snif…\n"
	.string "Moltes gràcies!$"

gText_ApprenticeWhichMove1::
	.string "Bé! Hola, {PLAYER}!\n"
	.string "Necessito el teu consell!\p"
	.string "Vull ensenyar al meu {STR_VAR_1}\n"
	.string "un moviment xulo.\p"
	.string "M'agraden els moviments\n"
	.string "{STR_VAR_2} o {STR_VAR_3}.\l"
	.string "Quin em recomanes?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} és millor? Suposo que sí!\n"
	.string "D'acord, faré això!\p"
	.string "Si ens tornem a veure, ensenya'm\n"
	.string "alguna cosa més, mestre!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, hola!\n"
	.string "És sobre el meu {STR_VAR_1}, estic\l"
	.string "preocupat pels seus moviments.\p"
	.string "Es tracta dels moviments {STR_VAR_2}\n"
	.string "i {STR_VAR_3}.\p"
	.string "Quin és més fort i millor per\n"
	.string "al meu {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} és la teva elecció?\n"
	.string "D'acord, entès!\p"
	.string "Aniré a ensenyar {STR_VAR_1} al\n"
	.string "meu Pokémon de seguida!\p"
	.string "Ens veiem!$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "Soc un desastre, de veritat!\p"
	.string "He decidit criar un Pokémon, però\n"
	.string "ara no puc ni decidir quin\l"
	.string "moviment ensenyar-li…\p"
	.string "Sé que no significa res\n"
	.string "per a tu, {PLAYER}.\p"
	.string "Però per a mi significa molt…\p"
	.string "Si us plau, {PLAYER}, pots triar\n"
	.string "un moviment per al meu {STR_VAR_1}?\p"
	.string "Si poguessis triar entre\n"
	.string "{STR_VAR_2} i {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Entenc!\p"
	.string "Però voldrà aprendre\n"
	.string "{STR_VAR_1} per a mi…\l"
	.string "No! Ho donaré tot!\p"
	.string "Gràcies!$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "Justament esperava veure't!\p"
	.string "Em preguntava quin moviment seria\n"
	.string "adequat per al meu {STR_VAR_1}.\p"
	.string "No em puc decidir, pots\n"
	.string "fer-ho per mi?\p"
	.string "Per exemple… Què tal els moviments\n"
	.string "{STR_VAR_2} i {STR_VAR_3}?\l"
	.string "Quin seria millor?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Genial!\p"
	.string "Sabent que tu has decidit,\n"
	.string "{PLAYER}{KUN}, no em sabrà tant de greu\l"
	.string "si perdo.\p"
	.string "D'acord, comptaré amb tu!\n"
	.string "Adéu!$"

gText_ApprenticeWhichMove5::
	.string "Com puc estar tan ocupat?\n"
	.string "Ei, si és {PLAYER}{KUN}!\l"
	.string "Com va?\p"
	.string "Des que m'he llevat he fet fúting,\n"
	.string "natació i cuina!\p"
	.string "No et creuràs com d'ocupat estic!\p"
	.string "Ni puc decidir quin moviment\n"
	.string "ha d'aprendre el meu {STR_VAR_1}!\p"
	.string "{STR_VAR_2} sembla bo, oi?\n"
	.string "Però {STR_VAR_3} també és decent.\p"
	.string "{PLAYER}{KUN}, dóna'm un bon consell!\n"
	.string "Quin moviment seria bo per a mi?$"

gText_ApprenticeMoveThanks5::
	.string "D'acord, entès.\n"
	.string "Faré un forat a l'agenda per\l"
	.string "ensenyar aquest moviment.\p"
	.string "M'alegro d'haver trobat un bon\n"
	.string "mentor. Gràcies! Ens veiem!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Quina sort!\n"
	.string "T'he tornat a trobar, {PLAYER}!\l"
	.string "Necessito el teu consell avui també.\p"
	.string "Redoble de tambor, si us plau!\n"
	.string "La pregunta que tinc és…\p"
	.string "Per al meu {STR_VAR_1}, quin moviment\n"
	.string "és el més adequat, {STR_VAR_2} o\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, dius!\l"
	.string "Gràcies per una resposta genial!\p"
	.string "Crec que això és tot el que volia\n"
	.string "preguntar-te avui.\p"
	.string "Tornem-nos a veure aquí, d'acord?\n"
	.string "Gràcies!$"

gText_ApprenticeWhichMove7::
	.string "Oh, hola, {PLAYER}.\n"
	.string "Espero que hagis estat bé.\p"
	.string "He de demanar-te consell una altra\n"
	.string "vegada. És sobre el meu {STR_VAR_1}.\p"
	.string "Quin seria el moviment ideal per\n"
	.string "al meu adorable {STR_VAR_1}?\l"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1}, doncs!\n"
	.string "L'ensenyaré de seguida!\p"
	.string "Gràcies, {PLAYER}.\n"
	.string "Espero poder comptar amb tu.\l"
	.string "Cuida't!$"

gText_ApprenticeWhichMove8::
	.string "Ei! {PLAYER}! T'he tornat a trobar!\n"
	.string "Estic… Estic tan content!\p"
	.string "Sempre que em fa falta, tu ets aquí\n"
	.string "per a mi, {PLAYER}!\p"
	.string "Avui vull que em recomanis\n"
	.string "un moviment!\p"
	.string "Tria un moviment per\n"
	.string "al meu {STR_VAR_1}!\p"
	.string "Quin moviment seria millor,\n"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh! Gràcies!\n"
	.string "{STR_VAR_1}, doncs!\l"
	.string "Perfectament entès!\p"
	.string "Espero que vulguis ensenyar-me\n"
	.string "més coses un altre dia.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, molt bé!\n"
	.string "Espero rebre més del teu\l"
	.string "savi consell avui!\p"
	.string "Quin seria el millor moviment per\n"
	.string "al meu {STR_VAR_1}?\p"
	.string "Hauria de ser alguna cosa que\n"
	.string "em fes guanyar de seguida!\p"
	.string "Seria {STR_VAR_2}?\n"
	.string "O {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Ajà, {STR_VAR_1}, doncs!\n"
	.string "Sí, molt bé!\l"
	.string "L'ensenyaré tot seguit!\p"
	.string "D'acord, gràcies, com sempre!\n"
	.string "Adéu!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, és una bogeria!\p"
	.string "El meu Pokémon!\n"
	.string "Ha après sis moviments!\p"
	.string "És clar que és mentida!\n"
	.string "Wahahaha!\p"
	.string "Però això no és mentida.\n"
	.string "No soc gaire bo triant moviments\l"
	.string "per als Pokémon.\p"
	.string "Doncs, per què no decideixes per mi\n"
	.string "quin moviment hauria d'ensenyar?\p"
	.string "{STR_VAR_2} o {STR_VAR_3}: quin\n"
	.string "aniria millor al meu {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "D'acord, has triat {STR_VAR_1}?\n"
	.string "Doncs triaré un altre moviment!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies, mestre!\n"
	.string "Espero que continuïs ensenyant-me!$"

gText_ApprenticeWhichMove11::
	.string "H-O-L-A!\n"
	.string "I això diu hola!\p"
	.string "El Mariner raper soc jo!\n"
	.string "Sempre estic al dia, no preguntis.\p"
	.string "Avui tinc una pregunta de moviment\n"
	.string "que reclama el teu suggeriment!\p"
	.string "{STR_VAR_2} i {STR_VAR_3} són els\n"
	.string "moviments. Quin seria el millor\l"
	.string "per al meu {STR_VAR_1}?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, dius, ei, ei!\n"
	.string "L'ensenyaré de seguida!\p"
	.string "Si mai necessito consell,\n"
	.string "{PLAYER}, seguiré les teves paraules!$"

gText_ApprenticeWhichMove12::
	.string "Oh, sí, si és {PLAYER}!\p"
	.string "Què hauria de fer? Demanar consell?\n"
	.string "Per què no? Ja t'estic parlant!\p"
	.string "{PLAYER}, et sorprenc?\n"
	.string "Vull el teu consell, no ho veus?\p"
	.string "Em sents?\n"
	.string "Em sents!\p"
	.string "El meu {STR_VAR_1}, què hauria d'usar?\n"
	.string "És {STR_VAR_2} o {STR_VAR_3},\l"
	.string "quin tries?$"

gText_ApprenticeMoveThanks12::
	.string "Si {STR_VAR_1} és el millor,\n"
	.string "faré el que dius!\p"
	.string "Bé, {PLAYER}, he d'anar per lliure,\n"
	.string "però no m'oblidis.\p"
	.string "Ens veiem, amic llest!$"

gText_ApprenticeWhichMove13::
	.string "Gahack! Gaah! Oh, {PLAYER}{KUN}…\n"
	.string "Tinc un refredat horrible…\p"
	.string "Vull triar un moviment pel Pokémon,\n"
	.string "però no estic en condicions…\p"
	.string "Doncs, les coses essent com són,\n"
	.string "necessito que decideixis per mi.\p"
	.string "{PLAYER}{KUN}, si hagués de triar entre\n"
	.string "{STR_VAR_2} i {STR_VAR_3} per\l"
	.string "al meu {STR_VAR_1}, quin seria?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, d'acord. Cof!\n"
	.string "L'ensenyaré quan millori.\p"
	.string "Espero poder continuar comptant\n"
	.string "amb tu.$"

gText_ApprenticeWhichMove14::
	.string "Er… Em…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Si us plau, no em miris així.\n"
	.string "Em poso molt nerviós…\l"
	.string "Ne… Necessito el teu consell.\p"
	.string "Em… Em fa molta vergonya, però no\n"
	.string "puc decidir quin moviment ensenyar\l"
	.string "al meu Pokémon.\p"
	.string "És per al meu {STR_VAR_1}.\n"
	.string "Si les opcions fossin {STR_VAR_2} o\l"
	.string "{STR_VAR_3}, quin seria millor?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… D'acord!\n"
	.string "Provaré {STR_VAR_1}.\p"
	.string "Espero poder ensenyar el moviment…\n"
	.string "Quins nervis…\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "Si ens tornem a veure, espero\l"
	.string "que m'ajudis igual.$"

gText_ApprenticeWhichMove15::
	.string "Hm? Sembles ser {PLAYER}{KUN}…\n"
	.string "Però ets de veritat?\p"
	.string "Potser ets un d'aquells imitadors\n"
	.string "populars?\p"
	.string "No, no, si ets real, cap problema.\n"
	.string "No t'enfadis, t'ho asseguro!\p"
	.string "Per cert, voldria demanar-te\n"
	.string "consell.\p"
	.string "És sobre el meu {STR_VAR_1}.\p"
	.string "Quin moviment seria millor per a\n"
	.string "ell, {STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "No hi ha cap dubte?\p"
	.string "Entenc. Si és el cas, perfecte.\n"
	.string "Et dono les gràcies pel teu temps.\p"
	.string "Espero que sigui alguna cosa que\n"
	.string "fins i tot el meu Pokémon pugui\l"
	.string "aprendre.\p"
	.string "Tornem-nos a veure!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER}?\n"
	.string "És {PLAYER}!\l"
	.string "Oh! Snif…bua… Escolta!\p"
	.string "Jo… Quan combato, estic tan nerviós\n"
	.string "que ploro fins i tot si guanyo…\p"
	.string "M'agradaria poder dir alguna cosa\n"
	.string "xula quan guanyo…\p"
	.string "Si us plau, {PLAYER}!\n"
	.string "Podries ensenyar-me alguna cosa\l"
	.string "xula per dir quan guanyi?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Genial! Increïble! Uuuuh!\n"
	.string "És molt xulo!\p"
	.string "Oh… Perdona…\n"
	.string "Estic tan content que ploro…\p"
	.string "Snif… {PLAYER}!\n"
	.string "Moltíssimes gràcies per tot!\p"
	.string "Combatré el millor que pugui\n"
	.string "per tu, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "El pròxim cop… Hauríem de combatre!$"

gText_ApprenticePickWinSpeech1::
	.string "Bé! És {PLAYER}! Hola!\n"
	.string "Volia preguntar-te una cosa!\p"
	.string "Vull dir alguna cosa xula quan\n"
	.string "guanyi un combat.\p"
	.string "Tens alguna frase xula que\n"
	.string "em puguis recomanar?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oh, uau! Això és molt xulo!\n"
	.string "D'acord, diré això!\p"
	.string "Gràcies per ensenyar-me tot!\n"
	.string "Ho donaré tot allà on vagi\l"
	.string "d'ara endavant!\p"
	.string "Quan ens tornem a veure, serà per\n"
	.string "un combat!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, hola!\p"
	.string "Els meus Pokémon i jo estem\n"
	.string "preparats, excepte per una cosa.\p"
	.string "Crec que seria bo tenir alguna cosa\n"
	.string "per cridar quan guanyi.\p"
	.string "Podries pensar alguna cosa bona\n"
	.string "per dir?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Xulo!\n"
	.string "Ho usaré!\p"
	.string "Aniré a combatre per tot arreu.\p"
	.string "Qui sap, potser algun dia combatré\n"
	.string "contra tu, {PLAYER}.\p"
	.string "El pròxim cop, trobem-nos en un\n"
	.string "lloc de combat!$"

gText_ApprenticePickWinSpeech3::
	.string "Hola, {PLAYER}…\n"
	.string "Perdona la molèstia, soc un desastre…\p"
	.string "Fins i tot quan…\n"
	.string "Fins i tot quan guanyo, no tinc res\l"
	.string "especial per dir…\p"
	.string "Sé que no significa res\n"
	.string "per a tu, {PLAYER}.\p"
	.string "Però per a mi significa molt…\p"
	.string "Si us plau, {PLAYER}, què hauria\n"
	.string "de dir si guanyo un combat?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Això és inspirador…\p"
	.string "Em… Està bé que algú com jo\n"
	.string "digui això?\p"
	.string "No! Ho donaré tot!\p"
	.string "{PLAYER}, moltes gràcies per\n"
	.string "aguantar-me tant de temps…\p"
	.string "Prometo que ho donaré tot.\p"
	.string "Segur que oblidaràs algú com jo,\n"
	.string "però tornem-nos a trobar en algun\l"
	.string "lloc!$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Vull que escoltis una cosa.\p"
	.string "Sé que no sempre sembro\n"
	.string "amable o educat…\p"
	.string "Quan guanyo un combat, crec que\n"
	.string "sembro arrogant.\p"
	.string "No vull que la gent em rebutgi,\n"
	.string "així que vull dir alguna cosa\l"
	.string "amable al qui derroto.\p"
	.string "Però no se m'acut res de bo!\n"
	.string "Pots pensar alguna cosa per a mi?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "No està malament!\n"
	.string "Sí, això faré!\p"
	.string "Me n'aniré i aplicaré tot el que\n"
	.string "m'has ensenyat.\p"
	.string "Perdona per haver estat tan\n"
	.string "pesat!\p"
	.string "El pròxim cop, combatrem, d'acord?\n"
	.string "Ens veiem!$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, no puc amb tanta feina!\n"
	.string "Oh, ei, et buscava, {PLAYER}{KUN}.\p"
	.string "Estàs bé com sempre?\n"
	.string "Jo estic igual.\p"
	.string "He de córrer, lluitar i mapejar.\n"
	.string "Per què estic tan ocupat?\p"
	.string "Però encara que estigui ocupat, seria\n"
	.string "maleducat marxar d'una victòria\l"
	.string "sense dir res.\p"
	.string "Doncs, quina frase xula podria\n"
	.string "dir al final? {PLAYER}{KUN}, ajuda'm!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "D'acord, entès.\n"
	.string "Tinc temps per dir això!\p"
	.string "De veritat, m'alegro d'haver trobat\n"
	.string "un bon mentor.\p"
	.string "Trobaré temps per combatre.\p"
	.string "Gràcies per tot, {PLAYER}{KUN}!\n"
	.string "Hem de combatre algun dia!$"

gText_ApprenticePickWinSpeech6::
	.string "He tingut sort una altra vegada!\n"
	.string "{PLAYER}! M'alegro de veure't!\l"
	.string "Com sempre, necessito el teu consell!\p"
	.string "Redoble de tambor, si us plau!\n"
	.string "La darrera pregunta que tinc és…\p"
	.string "Si guanyo un combat i vull acabar\n"
	.string "amb estil, què hauria de dir?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Això… Això és fabulós!\n"
	.string "És digne i xulo! Me l'apunto!\p"
	.string "…Escolta, crec que me'n surto\n"
	.string "bé, no?\p"
	.string "Així que penso reptar altres\n"
	.string "Entrenadors d'ara endavant.\p"
	.string "{PLAYER}, el teu consell m'ha ajudat.\p"
	.string "Potser algun dia ens combatrem!\p"
	.string "Gràcies per tot!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}.\n"
	.string "M'alegro d'haver-te trobat!\p"
	.string "Ja no tinc preocupacions\n"
	.string "respecte als meus Pokémon.\p"
	.string "Soc jo el que em preocupa…\p"
	.string "Saps com un Entrenador diu\n"
	.string "algunes coses en guanyar?\p"
	.string "Sens dubte, m'agradaria poder\n"
	.string "fer-ho també!\p"
	.string "Si us plau, què hauria de dir quan\n"
	.string "guanyi un combat?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah! Aquesta frase! Em renova\n"
	.string "i em fa sentir renascut!\p"
	.string "L'he d'usar de seguida!\p"
	.string "I ara, m'he d'acomiadar,\n"
	.string "{PLAYER}…\p"
	.string "Aniré a combatre contra molts,\n"
	.string "però mai oblidaré els teus\l"
	.string "ensenyaments.\p"
	.string "Potser algun dia…\n"
	.string "Adéu!$"

gText_ApprenticePickWinSpeech8::
	.string "Ei! He vist {PLAYER}!\n"
	.string "Estic… Estic tan content de veure't!\p"
	.string "Oh-oh-oh! Hi ha una cosa que\n"
	.string "t'havia de preguntar!\p"
	.string "Fa poc vaig guanyar un combat.\n"
	.string "Això va ser genial!\p"
	.string "Però em va fer tan feliç que\n"
	.string "em vaig emocionar i no vaig poder\l"
	.string "dir res!\p"
	.string "Doncs, {PLAYER}, si us plau, pensa'm\n"
	.string "una frase per quan guanyi!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Buaaaaa!\n"
	.string "Diré això?!\l"
	.string "Estic… Estic delirant de content!\p"
	.string "M-m-moltes gràcies!\n"
	.string "Ja no tinc res de què penedir-me!\p"
	.string "Ara viatjaré i combatré contra\n"
	.string "tot tipus de gent.\p"
	.string "Tot t'ho dec a tu, {PLAYER}.\n"
	.string "De veritat, moltes gràcies!\p"
	.string "Me n'he d'anar, però trobem-nos\n"
	.string "en un combat algun dia!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, molt bé!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Saps, em ve de gust sortir\n"
	.string "a combatre per aquí i per allà.\p"
	.string "Però abans, vull el teu consell\n"
	.string "una altra vegada!\p"
	.string "Si guanyés un combat, quina seria\n"
	.string "una bona frase per dir al meu\l"
	.string "oponent derrotat?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Ajà, això és genial!\n"
	.string "Sí, molt bé!\l"
	.string "Provaré de dir-ho!\p"
	.string "I ara, és hora de dir adéu!\n"
	.string "Gràcies per tot!\p"
	.string "Fes-me un combat algun dia, d'acord?\n"
	.string "Adéu!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, tenim un problema!\p"
	.string "Quan guanyo un combat, presumeixo\n"
	.string "com a mínim una hora!\p"
	.string "És clar que és mentida!\n"
	.string "Wahahaha!\p"
	.string "Però això no és mentida.\n"
	.string "No soc gaire bo xerrant.\p"
	.string "Doncs, per què no decideixes per mi\n"
	.string "què hauria de dir després de\l"
	.string "guanyar un combat, mestre?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Això hauria de dir, oi?\n"
	.string "Doncs, m'allunyaré d'això!\p"
	.string "És broma!\n"
	.string "Obeïré el teu ensenyament, mestre!\p"
	.string "Gràcies per ensenyar-me tot aquest\n"
	.string "temps, mestre!\p"
	.string "Per fi entenc què és ser\n"
	.string "Entrenador.\p"
	.string "Aniré a guanyar combats contra\n"
	.string "qualsevol Entrenador.\p"
	.string "Potser algun dia seràs tu, mestre!\p"
	.string "Això és tot!\n"
	.string "Adéu, mestre meu!$"

gText_ApprenticePickWinSpeech11::
	.string "H-O-L-A!\n"
	.string "I això diu hola!\p"
	.string "El Mariner raper soc jo!\n"
	.string "Aquesta serà la darrera pregunta,\l"
	.string "no ploris!\p"
	.string "És una pregunta de frase\n"
	.string "que reclama el teu suggeriment!\p"
	.string "Si guanyo un combat, què puc dir\n"
	.string "d'una forma ben maca?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfecte! Això usaré.\n"
	.string "He fet bé de fer-te triar!\p"
	.string "I ara, crec que seria millor\n"
	.string "que alcés el vol!\p"
	.string "Gràcies per tot el que m'has\n"
	.string "ensenyat. Sortiré a combatre!\p"
	.string "B-O-N-V-I-A-T-G-E!\n"
	.string "I això diu bon viatge,\l"
	.string "aquest és el meu homenatge!$"

gText_ApprenticePickWinSpeech12::
	.string "Oh, sí, {PLAYER}!\n"
	.string "T'he trobat avui!\p"
	.string "Què hauria de fer? Demanar-t'ho?\n"
	.string "Per què no? Ja t'ho estic demanant!\p"
	.string "De totes maneres, {PLAYER}…\n"
	.string "Em sents?\l"
	.string "Em sents!\l"
	.string "Necessito més consell!\p"
	.string "Es tracta del que hauria de cridar.\n"
	.string "Alguna cosa xula per dir quan\l"
	.string "un combat acaba bé.\p"
	.string "Vinga, vull sentir-t'ho dir!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "Molt bé, molt bé!\n"
	.string "Ho usaré perquè mola molt!\p"
	.string "Ja no tinc res més a preguntar.\n"
	.string "Només queda dir adéu.\p"
	.string "Però potser algun dia ens trobarem,\n"
	.string "i un de nosaltres serà derrotat.\p"
	.string "Però de veritat és hora de dir adéu.\p"
	.string "Bé, {PLAYER}, he d'anar per lliure,\n"
	.string "però no m'oblidis!\p"
	.string "Cuida't, {PLAYER}!\n"
	.string "T'estimo!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, estic acabat…\n"
	.string "El nas no para de degotar-me…\p"
	.string "Intentava pensar alguna cosa\n"
	.string "xula per dir quan guanyi.\p"
	.string "M'ha inspirat tant que m'ha fet\n"
	.string "plorar i ara no paro de mocar-me…\p"
	.string "Doncs, les coses essent com són,\n"
	.string "necessito que decideixis, {PLAYER}{KUN}.\p"
	.string "Quan guanyi un combat,\n"
	.string "què hauria de dir?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …Això és bo.\n"
	.string "No, és impressionant!\l"
	.string "Em torna a fer plorar!\p"
	.string "Però malgrat les llàgrimes i els\n"
	.string "mocs, usaré aquesta frase!\p"
	.string "Ja no tinc res més a preguntar-te,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "D'ara endavant, som rivals!\n"
	.string "Gràcies per tot!$"

gText_ApprenticePickWinSpeech14::
	.string "Er… Em…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Si us plau, no em miris així.\n"
	.string "Em posa molt nerviós.\p"
	.string "Ne… Necessito el teu consell.\n"
	.string "Serà l'últim cop, però…\p"
	.string "Em fa molta vergonya preguntar-ho,\n"
	.string "però i si guanyo un combat?\l"
	.string "Què hauria de dir?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… D'acord!\n"
	.string "Intentaré dir-ho!\l"
	.string "Potser estaré massa nerviós…\p"
	.string "Gràcies, {PLAYER}{KUN}.\n"
	.string "He de dir adéu ara.\p"
	.string "Obeïré tot el que m'has ensenyat,\n"
	.string "{PLAYER}{KUN}, i ho donaré tot.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? Sembles ser {PLAYER}{KUN}…\n"
	.string "Però ets de veritat?\l"
	.string "Potser una nina de {PLAYER}?\p"
	.string "Oh, no, no, no, no et preocupis!\n"
	.string "Si de veritat ets real, si us plau\l"
	.string "oblida la meva falta d'educació.\p"
	.string "No t'enfadis. Tot el que vull és\n"
	.string "més del teu bon consell.\p"
	.string "Es tracta d'una frase.\p"
	.string "Més concretament, què hauria de dir\n"
	.string "si guanyo un combat?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "Quan guanyi un combat…\p"
	.string "{STR_VAR_1}\p"
	.string "…Parles seriosament?\p"
	.string "Entenc. Si parles seriosament,\n"
	.string "perfecte. Gràcies pel teu temps.\p"
	.string "Espero que fins i tot jo pugui\n"
	.string "fer bon ús d'aquesta frase.\p"
	.string "Sembla que ja no tinc res més\n"
	.string "a preguntar-te.\p"
	.string "Crec que és hora d'acomiadar-me\n"
	.string "i continuar pel meu compte.\p"
	.string "Gràcies, mentor meu!\n"
	.string "Demano disculpes pel meu escepticisme!$"
