FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Us dono la benvinguda a la\n"
	.string "Carpa de Batalla de Fallabor!\p"
	.string "Sóc el vostre guia del Torneig KO!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Ara, voleu acceptar el repte\n"
	.string "del Torneig KO?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Us esperem en una altra ocasió!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "A la Carpa de Batalla de Fallabor,\n"
	.string "duem a terme el Torneig KO.\p"
	.string "Tots els participants entren\n"
	.string "amb un equip de tres Pokémon.\p"
	.string "Els tres Pokémon s'han d'ordenar\n"
	.string "en l'ordre en que apareixeran.\p"
	.string "Durant la batalla, els Pokémon\n"
	.string "sortiran d'un en un en l'ordre\l"
	.string "predeterminat.\p"
	.string "Un cop un Pokémon entra en batalla,\n"
	.string "ha de romandre-hi fins al final\l"
	.string "del combat.\p"
	.string "Si un combat no es resol en\n"
	.string "tres torns, passa a judici.\p"
	.string "Si voleu interrompre el repte,\n"
	.string "deseu el joc, si us plau.\p"
	.string "Si no deseu, no podreu continuar\n"
	.string "amb el vostre repte.\p"
	.string "Si aconseguiu guanyar tres\n"
	.string "Entrenadors seguits, us\l"
	.string "obsequiarem amb un gran premi.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Abans de portar-vos a la Carpa\n"
	.string "de Batalla, he de desar. D'acord?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Oferim dos nivells de repte,\n"
	.string "Nivell 50 i Nivell Obert.\l"
	.string "Quina és la vostra elecció?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Molt bé, ara seleccioneu els\n"
	.string "vostres tres Pokémon, si us plau.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Estimat repte!\p"
	.string "No teniu els tres Pokémon\n"
	.string "necessaris per a participar.\p"
	.string "A més, no poden portar el\n"
	.string "mateix tipus d'objecte.\p"
	.string "Ous{STR_VAR_1} no admesos.\p"
	.string "Quan hàgiu fet els preparatius,\n"
	.string "torneu, si us plau.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Estimat repte!\p"
	.string "No teniu els tres Pokémon\n"
	.string "necessaris per a participar.\p"
	.string "Per a participar, heu de portar\n"
	.string "tres espècies de Pokémon diferents.\p"
	.string "A més, no poden portar el\n"
	.string "mateix tipus d'objecte.\p"
	.string "Ous{STR_VAR_1} no admesos.\p"
	.string "Quan hàgiu fet els preparatius,\n"
	.string "torneu, si us plau.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Ara us guiaré fins\n"
	.string "a la Carpa de Batalla.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Estimat repte!\p"
	.string "No heu desat el joc abans\n"
	.string "d'apagar, oi?\p"
	.string "Malauradament, això ha resultat\n"
	.string "en la vostra descalificació\l"
	.string "del repte.\p"
	.string "Per descomptat, podeu començar\n"
	.string "un repte nou.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Esplèndid! Heu guanyat\n"
	.string "tres Entrenadors seguits!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Espereu mentre deso el joc.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "En commemoració de la vostra\n"
	.string "ratxa de 3 victòries, us oferim\l"
	.string "aquest premi.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} ha rebut el premi\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh?\n"
	.string "La vostra Motxilla sembla plena.\p"
	.string "Us exhortem a fer espai i\n"
	.string "tornar pel vostre premi.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Moltes gràcies per participar!\p"
	.string "Espereu mentre deso el joc.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Us esperem en una altra ocasió!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Estàvem esperant la vostra arribada.\p"
	.string "Abans de portar-vos a la Carpa\n"
	.string "de Batalla, he de desar. Espereu.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Us dono la benvinguda a la\n"
	.string "Carpa de Batalla de Verdanturf!\p"
	.string "Aquí es posa a prova la\n"
	.string "confiança del Entrenador\l"
	.string "envers els seus Pokémon.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Voleu acceptar el repte\n"
	.string "de la Carpa de Batalla de Verdanturf?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "A la Carpa de Batalla de Verdanturf\n"
	.string "hi ha una regla crucial\l"
	.string "que cal respectar.\p"
	.string "Els Entrenadors només poden\n"
	.string "canviar els seus Pokémon.\p"
	.string "Altrament, els Entrenadors\n"
	.string "no poden donar ordres\l"
	.string "als seus Pokémon.\p"
	.string "Els Pokémon han d'actuar\n"
	.string "segons la seva naturalesa\l"
	.string "i batallar sols.\p"
	.string "Heu de confiar en els vostres\n"
	.string "Pokémon i observar-los.\p"
	.string "Si aconseguiu guanyar tres\n"
	.string "Entrenadors seguits, us\l"
	.string "obsequiarem amb un premi.\p"
	.string "Si voleu interrompre el repte,\n"
	.string "deseu el joc, si us plau.\p"
	.string "Si no deseu abans d'interrompre,\n"
	.string "sereu descalificats.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Quan hàgiu enfortit el cor\n"
	.string "i els vostres Pokémon, torneu.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Hi ha dos nivells de dificultat,\n"
	.string "Nivell 50 i Nivell Obert.\l"
	.string "Quin repte trieu?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Ai…\p"
	.string "No teniu els tres Pokémon\n"
	.string "necessaris per al repte.\p"
	.string "Per a participar, heu de portar\n"
	.string "tres espècies de Pokémon diferents.\p"
	.string "A més, no poden portar\n"
	.string "el mateix tipus d'objecte.\p"
	.string "Ous{STR_VAR_1} no admesos.\p"
	.string "Torneu quan hàgiu fet\n"
	.string "els vostres preparatius.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Ai…\p"
	.string "No teniu els tres Pokémon\n"
	.string "necessaris per al repte.\p"
	.string "Per a participar, heu de portar\n"
	.string "tres espècies de Pokémon diferents.\p"
	.string "A més, no poden portar\n"
	.string "el mateix tipus d'objecte.\p"
	.string "Ous{STR_VAR_1} no admesos.\p"
	.string "Torneu quan hàgiu fet\n"
	.string "els vostres preparatius.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bé. Ara heu de seleccionar\n"
	.string "els vostres tres Pokémon.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "He de desar abans de portar-vos\n"
	.string "a la Carpa de Batalla. D'acord?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bé.\n"
	.string "Ara, seguiu-me.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Em sento privilegiat d'haver vist\n"
	.string "les gestes dels vostres Pokémon.\p"
	.string "Els resultats seran registrats.\n"
	.string "Us demano que espereu un moment.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Aconseguir una ratxa de 3 victòries…\p"
	.string "El vincle que uneix el vostre cor\n"
	.string "amb els vostres Pokémon sembla\l"
	.string "ferm i veritable.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "La vostra gesta serà registrada.\n"
	.string "Us demano que espereu un moment.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Per la gesta de la vostra ratxa\n"
	.string "de 3 victòries, us oferim\l"
	.string "aquest premi.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Benvinguts a la Carpa de Batalla\n"
	.string "de Slateport!\p"
	.string "Sóc el vostre guia del Torneig\n"
	.string "d'Intercanvi de Batalla.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Voleu acceptar el repte\n"
	.string "de la Batalla d'Intercanvi?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Aquí a la Carpa de Batalla de\n"
	.string "Slateport duem a terme Batalles\l"
	.string "d'Intercanvi amb Pokémon de lloguer.\p"
	.string "Primer, se us deixaran tres\n"
	.string "Pokémon específics per a l'event.\p"
	.string "Usant els Pokémon de lloguer,\n"
	.string "heu de dur a terme una Batalla\l"
	.string "Individual.\p"
	.string "Si guanyeu, podeu intercanviar\n"
	.string "un dels vostres Pokémon de lloguer.\p"
	.string "Repetiu aquest cicle de batallar\n"
	.string "i intercanviar — si guanyeu tres\l"
	.string "vegades seguides, guanyareu\l"
	.string "un gran premi.\p"
	.string "Si voleu interrompre el repte,\n"
	.string "deseu el joc, si us plau.\p"
	.string "Si no deseu abans d'interrompre,\n"
	.string "sereu descalificats.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Esperem la vostra propera visita.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Quin nivell voleu acceptar?\n"
	.string "Nivell 50 o Nivell 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Abans de començar el repte,\n"
	.string "he de desar les dades. D'acord?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "D'acord, guardaré els vostres\n"
	.string "Pokémon mentre competiu.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Passeu per aquí, si us plau.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Gràcies per participar!\p"
	.string "Us retornaré els vostres Pokémon\n"
	.string "a canvi dels Pokémon de lloguer.\p"
	.string "També he de desar els resultats\n"
	.string "de l'event. Espereu.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Us retornaré els vostres Pokémon\n"
	.string "a canvi dels Pokémon de lloguer.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Felicitats!\n"
	.string "Heu guanyat tres combats seguits!\p"
	.string "Us retornaré els vostres Pokémon\n"
	.string "a canvi dels Pokémon de lloguer.\p"
	.string "També he de desar els resultats\n"
	.string "de l'event. Espereu.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "En reconeixement de la vostra\n"
	.string "ratxa de 3 victòries, us atorguem\l"
	.string "aquest premi.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh?\n"
	.string "Sembla que no teniu espai per a això.\p"
	.string "Feu espai a la Motxilla i\n"
	.string "feu-m'ho saber.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Us estàvem esperant!\p"
	.string "Abans de reprendre el repte,\n"
	.string "he de desar el joc.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Ho sento, però no vau desar\n"
	.string "abans de deixar de jugar.\p"
	.string "Com a resultat, heu estat\n"
	.string "descalificats del repte.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Us retornarem els vostres Pokémon personals.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} ha rebut el premi\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Les regles de la Batalla d'Intercanvi\n"
	.string "estan llistades.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quin apartat voleu llegir?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "En un event de Batalla d'Intercanvi,\n"
	.string "només podeu usar tres Pokémon.\p"
	.string "Tant si llogeu com si intercanvieu,\n"
	.string "el vostre equip no pot tenir dos\l"
	.string "o més Pokémon de la mateixa espècie.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Només podeu intercanviar Pokémon\n"
	.string "amb l'Entrenador que acabeu\l"
	.string "de derrotar.\p"
	.string "Només podeu intercanviar pels\n"
	.string "Pokémon usats per l'Entrenador\l"
	.string "derrotat.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Després de cada batalla guanyada,\n"
	.string "podeu intercanviar un dels Pokémon\l"
	.string "del vostre rival derrotat.\p"
	.string "No podreu intercanviar Pokémon\n"
	.string "amb el tercer Entrenador de l'event.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Hi ha dos punts clau a tenir en\n"
	.string "compte en intercanviar Pokémon.\p"
	.string "Primer, en intercanviar, no podeu\n"
	.string "comprovar les estadístiques del\l"
	.string "Pokémon que rebreu.\p"
	.string "Segon, els Pokémon del vostre equip\n"
	.string "estan ordenats en seqüència, segons\l"
	.string "l'ordre en que els vau llogar.\p"
	.string "Aquesta seqüència no canvia\n"
	.string "ni tan sols en fer intercanvis.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Els Pokémon de la Carpa de Batalla\n"
	.string "de Slateport són tots de lloguer.\p"
	.string "Tots els Pokémon de lloguer es\n"
	.string "mantenen al Nivell 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Les regles de la Carpa de Batalla\n"
	.string "de Verdanturf estan llistades.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quin apartat voleu llegir?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Aquí a la Carpa de Batalla de\n"
	.string "Verdanturf, els Pokémon han de\l"
	.string "pensar i batallar sols.\p"
	.string "A diferència de la natura, els\n"
	.string "Pokémon que viuen amb persones\l"
	.string "es comporten diferent\l"
	.string "segons la seva naturalesa.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Segons la seva naturalesa, un\n"
	.string "Pokémon pot preferir atacar\l"
	.string "sempre.\p"
	.string "Un altre Pokémon pot preferir\n"
	.string "protegir-se de tot dany.\p"
	.string "Un altre pot gaudir de pertorbar\n"
	.string "o confondre els rivals.\p"
	.string "Segons la seva naturalesa, un\n"
	.string "Pokémon tindrà moviments favorits\l"
	.string "que usa bé.\p"
	.string "També pot no agradar-li certs\n"
	.string "moviments que li costen d'usar.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Hi ha moviments ofensius que\n"
	.string "causen dany directe al rival.\p"
	.string "Hi ha moviments defensius usats\n"
	.string "per a preparar-se per als atacs\l"
	.string "enemics o per a recuperar PS.\p"
	.string "I hi ha altres moviments peculiars\n"
	.string "que debiliten els rivals amb\l"
	.string "problemes d'estat com verí\l"
	.string "o paràlisi.\p"
	.string "Els Pokémon consideraran usar\n"
	.string "moviments d'aquestes tres categories.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Sense les ordres del seu Entrenador,\n"
	.string "un Pokémon pot ser incapaç d'usar\l"
	.string "certs moviments eficaçment.\p"
	.string "Un Pokémon no és bo usant cap\n"
	.string "moviment que no li agrada.\p"
	.string "Si un Pokémon només sap moviments\n"
	.string "que no encaixen amb la seva\l"
	.string "naturalesa, sovint no podrà\l"
	.string "rendir al màxim.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Segons la seva naturalesa, un Pokémon\n"
	.string "pot començar a usar moviments que\l"
	.string "no encaixen quan está en dificultats.\p"
	.string "Si un Pokémon comença a comportar-se\n"
	.string "de forma estranya en un moment\l"
	.string "crític, observeu-lo amb atenció.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "En aquesta Carpa de Batalla, els\n"
	.string "nivells dels vostres rivals\l"
	.string "s'ajustaran als vostres Pokémon.\p"
	.string "Tot i això, cap Entrenador al que\n"
	.string "us enfronteu tindrà Pokémon\l"
	.string "per sota del Nivell 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Les regles de la Carpa de Batalla\n"
	.string "de Verdanturf estan llistades.$"
