FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Et dono la benvinguda a la\n"
	.string "Carpa de Combat de Fallabor!\p"
	.string "Sóc el teu guia del Torneig KO!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Doncs bé, vols acceptar el repte\n"
	.string "del Torneig KO?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "T'esperem en una altra ocasió!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "A la Carpa de Combat de Fallabor,\n"
	.string "duem a terme el Torneig KO.\p"
	.string "Tots els participants entren\n"
	.string "amb un equip de tres Pokémon.\p"
	.string "Els tres Pokémon s'han de posar\n"
	.string "en l'ordre en què sortiran.\p"
	.string "Durant el combat, els Pokémon\n"
	.string "sortiran d'un en un en l'ordre\l"
	.string "establert.\p"
	.string "Un cop un Pokémon entra en combat,\n"
	.string "ha de romandre-hi fins al final\l"
	.string "del combat.\p"
	.string "Si un combat no es resol en\n"
	.string "tres torns, el decideixen els jutges.\p"
	.string "Si vols interrompre el repte,\n"
	.string "desa la partida, si us plau.\p"
	.string "Si no la deses, no podràs\n"
	.string "continuar amb el teu repte.\p"
	.string "Si aconsegueixes guanyar tres\n"
	.string "Entrenadors seguits, et\l"
	.string "donarem un bon premi.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Abans de portar-te a la Carpa\n"
	.string "de Combat, he de desar. D'acord?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Oferim dos nivells de repte,\n"
	.string "Nivell 50 i Nivell Obert.\l"
	.string "Quin tries?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Molt bé, ara tria els teus\n"
	.string "tres Pokémon, si us plau.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "{MASC}Estimat{FEM}Estimada{ENDG} aspirant!\p"
	.string "No tens els tres Pokémon\n"
	.string "necessaris per a participar.\p"
	.string "A més, no poden portar el\n"
	.string "mateix tipus d'objecte.\p"
	.string "Els Ous{STR_VAR_1} exclosos.\p"
	.string "Quan hagis fet els preparatius,\n"
	.string "torna, si us plau.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "{MASC}Estimat{FEM}Estimada{ENDG} aspirant!\p"
	.string "No tens els tres Pokémon\n"
	.string "necessaris per a participar.\p"
	.string "Per participar, has de portar\n"
	.string "tres espècies de Pokémon diferents.\p"
	.string "A més, no poden portar el\n"
	.string "mateix tipus d'objecte.\p"
	.string "Els Ous{STR_VAR_1} exclosos.\p"
	.string "Quan hagis fet els preparatius,\n"
	.string "torna, si us plau.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Ara et guiaré fins\n"
	.string "a la Carpa de Combat.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "{MASC}Estimat{FEM}Estimada{ENDG} aspirant!\p"
	.string "No vas desar la partida abans\n"
	.string "d'apagar, oi?\p"
	.string "Ho lamento, però per això\n"
	.string "has quedat fora del repte.\p"
	.string "És clar que pots començar\n"
	.string "un repte nou.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Esplèndid! Has guanyat\n"
	.string "tres Entrenadors seguits!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Espera mentre deso la partida.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "En commemoració de la teva\n"
	.string "ratxa de 3 victòries, t'oferim\l"
	.string "aquest premi.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} ha rebut el premi\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh?\n"
	.string "Sembla que tens la Motxilla plena.\p"
	.string "Fes-hi espai i torna a\n"
	.string "buscar el teu premi.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Moltes gràcies per participar!\p"
	.string "Espera mentre deso la partida.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "T'esperem en una altra ocasió!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "T'estàvem esperant.\p"
	.string "Abans de portar-te a la Carpa\n"
	.string "de Combat, he de desar. Espera.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Et dono la benvinguda a la\n"
	.string "Carpa de Combat de Verdanturf!\p"
	.string "Aquí es posa a prova la\n"
	.string "confiança de l'Entrenador\l"
	.string "envers els seus Pokémon.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Vols acceptar el repte de la\n"
	.string "Carpa de Combat de Verdanturf?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "A la Carpa de Combat de Verdanturf\n"
	.string "hi ha una regla fonamental\l"
	.string "que cal respectar.\p"
	.string "Els Entrenadors només poden\n"
	.string "fer entrar i retirar Pokémon.\p"
	.string "A part d'això, els Entrenadors\n"
	.string "no poden donar ordres\l"
	.string "als seus Pokémon.\p"
	.string "Els Pokémon han d'actuar\n"
	.string "segons la seva naturalesa\l"
	.string "i lluitar sols.\p"
	.string "Has de confiar en els teus\n"
	.string "Pokémon i vetllar per ells.\p"
	.string "Si aconsegueixes guanyar tres\n"
	.string "Entrenadors seguits, et\l"
	.string "donarem un premi.\p"
	.string "Si vols interrompre el repte,\n"
	.string "desa la partida, si us plau.\p"
	.string "Si no la deses abans de plegar,\n"
	.string "et desqualificarem.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Quan hagis enfortit el cor\n"
	.string "i els teus Pokémon, torna.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Hi ha dos nivells de dificultat,\n"
	.string "Nivell 50 i Nivell Obert.\l"
	.string "Quin repte tries?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Ai…\p"
	.string "No tens els tres Pokémon\n"
	.string "necessaris per al repte.\p"
	.string "Per participar, has de portar\n"
	.string "tres espècies de Pokémon diferents.\p"
	.string "A més, no poden portar\n"
	.string "el mateix tipus d'objecte.\p"
	.string "Els Ous{STR_VAR_1} exclosos.\p"
	.string "Torna quan hagis fet\n"
	.string "els teus preparatius.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Ai…\p"
	.string "No tens els tres Pokémon\n"
	.string "necessaris per al repte.\p"
	.string "Per participar, has de portar\n"
	.string "tres espècies de Pokémon diferents.\p"
	.string "A més, no poden portar\n"
	.string "el mateix tipus d'objecte.\p"
	.string "Els Ous{STR_VAR_1} exclosos.\p"
	.string "Torna quan hagis fet\n"
	.string "els teus preparatius.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bé. Ara has de triar\n"
	.string "els teus tres Pokémon.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "He de desar abans de portar-te\n"
	.string "a la Carpa de Combat. D'acord?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bé.\n"
	.string "Ara, segueix-me.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Em sento privilegiat d'haver vist\n"
	.string "les gestes dels teus Pokémon.\p"
	.string "Ara registrarem els resultats.\n"
	.string "Espera un moment, si us plau.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Aconseguir una ratxa de 3 victòries…\p"
	.string "El vincle que uneix el teu cor\n"
	.string "amb els teus Pokémon sembla\l"
	.string "ferm i veritable.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Ara registrarem la teva gesta.\n"
	.string "Espera un moment, si us plau.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Per la gesta de la teva ratxa\n"
	.string "de 3 victòries, t'oferim\l"
	.string "aquest premi.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Et donem la benvinguda a la\n"
	.string "Carpa de Combat de Slateport!\p"
	.string "Sóc el teu guia del Torneig\n"
	.string "de Combat d'Intercanvi.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Vols acceptar el repte\n"
	.string "del Combat d'Intercanvi?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Aquí a la Carpa de Combat de\n"
	.string "Slateport duem a terme Combats\l"
	.string "d'Intercanvi amb Pokémon de lloguer.\p"
	.string "Primer, et deixarem tres Pokémon\n"
	.string "especialment per a l'esdeveniment.\p"
	.string "Amb aquests Pokémon de lloguer,\n"
	.string "hauràs de lliurar un Combat\l"
	.string "Individual.\p"
	.string "Si guanyes, pots intercanviar\n"
	.string "un dels teus Pokémon de lloguer.\p"
	.string "Repeteix aquest cicle de lluitar\n"
	.string "i intercanviar. Si guanyes tres\l"
	.string "cops seguits, t'emportaràs\l"
	.string "un bon premi.\p"
	.string "Si vols interrompre el repte,\n"
	.string "desa la partida, si us plau.\p"
	.string "Si no la deses abans de plegar,\n"
	.string "et desqualificarem.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Esperem la teva propera visita.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "A quin nivell vols competir?\n"
	.string "Nivell 50 o Nivell 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Abans de començar el repte,\n"
	.string "he de desar les dades. D'acord?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "D'acord, et guardaré els teus\n"
	.string "Pokémon mentre competeixes.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Passa per aquí, si us plau.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Gràcies per participar!\p"
	.string "Et tornaré els teus Pokémon\n"
	.string "a canvi dels Pokémon de lloguer.\p"
	.string "També he de desar els resultats\n"
	.string "de l'esdeveniment. Espera.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Et tornaré els teus Pokémon\n"
	.string "a canvi dels Pokémon de lloguer.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Felicitats!\n"
	.string "Has guanyat tres combats seguits!\p"
	.string "Et tornaré els teus Pokémon\n"
	.string "a canvi dels Pokémon de lloguer.\p"
	.string "També he de desar els resultats\n"
	.string "de l'esdeveniment. Espera.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "En reconeixement de la teva\n"
	.string "ratxa de 3 victòries, t'atorguem\l"
	.string "aquest premi.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh?\n"
	.string "Sembla que no tens espai per a això.\p"
	.string "Fes espai a la Motxilla i\n"
	.string "avisa'm.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "T'estàvem esperant!\p"
	.string "Abans de reprendre el repte,\n"
	.string "he de desar el joc.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Em sap greu, però l'últim cop no\n"
	.string "vas desar abans de deixar de jugar.\p"
	.string "Per aquest motiu, t'hem hagut\n"
	.string "de desqualificar del repte.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Et tornarem els teus Pokémon.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} ha rebut el premi\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Aquí hi ha les regles\n"
	.string "del Combat d'Intercanvi.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quin apartat vols llegir?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "En un Combat d'Intercanvi,\n"
	.string "només pots usar tres Pokémon.\p"
	.string "Tant si llogues com si intercanvies,\n"
	.string "el teu equip no pot tenir dos\l"
	.string "o més Pokémon de la mateixa espècie.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Només pots intercanviar Pokémon\n"
	.string "amb l'Entrenador que acabes\l"
	.string "de derrotar.\p"
	.string "Només pots obtenir a canvi els\n"
	.string "Pokémon usats per l'Entrenador\l"
	.string "derrotat.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Després de cada combat guanyat,\n"
	.string "pots obtenir un dels Pokémon\l"
	.string "del rival que has derrotat.\p"
	.string "No podràs intercanviar Pokémon\n"
	.string "amb el tercer Entrenador.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Hi ha dos punts clau a tenir en\n"
	.string "compte en intercanviar Pokémon.\p"
	.string "Primer, en intercanviar, no pots\n"
	.string "comprovar les estadístiques del\l"
	.string "Pokémon que rebràs.\p"
	.string "Segon, els Pokémon del teu equip\n"
	.string "estan col·locats segons l'ordre\l"
	.string "en què els vas llogar.\p"
	.string "Aquest ordre no canvia\n"
	.string "ni tan sols en fer intercanvis.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Els Pokémon de la Carpa de Combat\n"
	.string "de Slateport són tots de lloguer.\p"
	.string "Tots els Pokémon de lloguer es\n"
	.string "mantenen al Nivell 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Aquí hi ha les regles de la\n"
	.string "Carpa de Combat de Verdanturf.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quin apartat vols llegir?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Aquí a la Carpa de Combat de\n"
	.string "Verdanturf, els Pokémon han de\l"
	.string "pensar i lluitar sols.\p"
	.string "A diferència dels salvatges, els\n"
	.string "Pokémon que viuen amb persones\l"
	.string "es comporten diferent\l"
	.string "segons la seva naturalesa.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Segons la seva naturalesa, un\n"
	.string "Pokémon pot preferir atacar\l"
	.string "sempre.\p"
	.string "Un altre Pokémon pot preferir\n"
	.string "protegir-se de tot dany.\p"
	.string "Un altre pot gaudir de pertorbar\n"
	.string "o confondre els rivals.\p"
	.string "Segons la seva naturalesa, un\n"
	.string "Pokémon tindrà moviments preferits\l"
	.string "que sap usar bé.\p"
	.string "També hi pot haver moviments\n"
	.string "que no li agradin i li costi usar.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Hi ha moviments ofensius que\n"
	.string "causen dany directe al rival.\p"
	.string "Hi ha moviments defensius que\n"
	.string "serveixen per preparar-se per als\l"
	.string "atacs o per recuperar PS.\p"
	.string "I hi ha altres moviments peculiars\n"
	.string "que debiliten els rivals amb\l"
	.string "problemes d'estat com el verí\l"
	.string "o la paràlisi.\p"
	.string "Els Pokémon consideraran usar\n"
	.string "moviments d'aquestes tres categories.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Sense les ordres del seu Entrenador,\n"
	.string "un Pokémon pot no ser capaç d'usar\l"
	.string "bé certs moviments.\p"
	.string "Un Pokémon no fa bé cap\n"
	.string "moviment que no li agradi.\p"
	.string "Si un Pokémon només sap moviments\n"
	.string "que no encaixen amb la seva\l"
	.string "naturalesa, sovint no podrà\l"
	.string "rendir al màxim.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Segons la seva naturalesa, un Pokémon\n"
	.string "pot començar a usar moviments que\l"
	.string "no hi encaixen quan està en perill.\p"
	.string "Si un Pokémon comença a comportar-se\n"
	.string "de forma estranya quan està en\l"
	.string "perill, observa'l amb atenció.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "En aquesta Carpa de Combat, els\n"
	.string "nivells dels teus rivals\l"
	.string "s'ajustaran als dels teus Pokémon.\p"
	.string "Tot i això, cap Entrenador amb qui\n"
	.string "t'enfrontis tindrà Pokémon\l"
	.string "per sota del Nivell 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Aquí hi ha les regles de la\n"
	.string "Carpa de Combat de Verdanturf.$"
