BattleDome_Text_Potential1::
	.string "El millor candidat a campió!$"

BattleDome_Text_Potential2::
	.string "Equip de finalistes segur.$"

BattleDome_Text_Potential3::
	.string "Possible finalista entre els tres millors.$"

BattleDome_Text_Potential4::
	.string "Un candidat a quedar primer.$"

BattleDome_Text_Potential5::
	.string "Un equip d'alt potencial.$"

BattleDome_Text_Potential6::
	.string "L'equip sorpresa d'aquest torneig.$"

BattleDome_Text_Potential7::
	.string "Un equip per sobre de la mitjana.$"

BattleDome_Text_Potential8::
	.string "L'equip mitjà d'aquest torneig.$"

BattleDome_Text_Potential9::
	.string "Un equip amb potencial mitjà.$"

BattleDome_Text_Potential10::
	.string "Un equip per sota de la mitjana.$"

BattleDome_Text_Potential11::
	.string "Un equip que cerca la seva primera victòria.$"

BattleDome_Text_Potential12::
	.string "Una victòria omplirà d'orgull aquest equip.$"

BattleDome_Text_Potential13::
	.string "En general, un equip feble.$"

BattleDome_Text_Potential14::
	.string "Un equip amb potencial molt baix.$"

BattleDome_Text_Potential15::
	.string "Un equip poc probable de guanyar el torneig.$"

BattleDome_Text_Potential16::
	.string "L'equip amb menys possibilitats de guanyar.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "La superstar perfecta i invencible!$"

BattleDome_Text_StyleRiskDisaster::
	.string "De vegades arrisca un desastre total.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Habilitat per aguantar llargues batalles.$"

BattleDome_Text_StyleVariesTactics::
	.string "Varia les tàctiques segons l'oponent.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Té un patró de victòria difícil de batre.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "De vegades usa un moviment molt rar.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Usa moviments sorprenents i disruptius.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Vigila constantment els PS en batalla.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Habilitat per acumular i alliberar poder.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Habilitat per debilitar els rivals.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Prefereix tàctiques que depenen de la sort.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Ataca amb una atmosfera règia.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Ataca amb moviments potents i poc PP.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Habilitat per debilitar i llavors atacar.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Batalla aguantant tots els atacs.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Habilitat per desconcertar els rivals.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Usa moviments forts i directes.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Usa moviments forts de forma agressiva.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Batalla esquivant atacs hàbilment.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Habilitat per usar atacs desconcertants.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Usa molts moviments populars.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Té moviments per fer combinacions potents.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Usa atacs d'alta probabilitat.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Usa moviments espectaculars agressivament.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Prioritza l'ofensa per sobre la defensa.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Prioritza la defensa per sobre l'ofensa.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Ataca ràpidament amb moviments forts.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Sovint usa moviments amb efectes addicionals.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Usa una combinació equilibrada de moviments.$"

BattleDome_Text_StyleSampleMessage1::
	.string "Missatge de mostra 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "Missatge de mostra 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "Missatge de mostra 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "Missatge de mostra 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Prioritza PS i Atac.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Prioritza PS i Defensa.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Prioritza PS i Velocitat.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Prioritza PS i At. Esp.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Prioritza PS i Def. Esp.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Prioritza Atac i Defensa.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Prioritza Atac i Velocitat.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Prioritza Atac i At. Esp.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Prioritza Atac i Def. Esp.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Prioritza Defensa i Velocitat.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Prioritza Defensa i At. Esp.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Prioritza Defensa i Def. Esp.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Prioritza Velocitat i At. Esp.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Prioritza Velocitat i Def. Esp.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Prioritza At. Esp. i Def. Esp.$"

BattleDome_Text_EmphasizesHP::
	.string "Prioritza els PS.$"

BattleDome_Text_EmphasizesAtk::
	.string "Prioritza l'Atac.$"

BattleDome_Text_EmphasizesDef::
	.string "Prioritza la Defensa.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Prioritza la Velocitat.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Prioritza l'At. Esp.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Prioritza la Def. Esp.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Descuida PS i Atac.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Descuida PS i Defensa.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Descuida PS i Velocitat.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Descuida PS i At. Esp.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Descuida PS i Def. Esp.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Descuida Atac i Defensa.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Descuida Atac i Velocitat.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Descuida Atac i At. Esp.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Descuida Atac i Def. Esp.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Descuida Defensa i Velocitat.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Descuida Defensa i At. Esp.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Descuida Defensa i Def. Esp.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Descuida Velocitat i At. Esp.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Descuida Velocitat i Def. Esp.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Descuida At. Esp. i Def. Esp.$"

BattleDome_Text_NeglectsHP::
	.string "Descuida els PS.$"

BattleDome_Text_NeglectsAtk::
	.string "Descuida l'Atac.$"

BattleDome_Text_NeglectsDef::
	.string "Descuida la Defensa.$"

BattleDome_Text_NeglectsSpeed::
	.string "Descuida la Velocitat.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Descuida l'At. Esp.$"

BattleDome_Text_NeglectsSpDef::
	.string "Descuida la Def. Esp.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Cria Pokémon de forma equilibrada.$"

BattleDome_Text_LetTheBattleBegin::
	.string "Que comenci la batalla!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} ha guanyat amb {STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} s'ha convertit en el campió!$"

BattleDome_Text_TrainerWonByDefault::
	.string "{STR_VAR_1} ha guanyat per defecte!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} ha guanyat directament per defecte!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} ha guanyat sense usar cap moviment!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} ha guanyat directament sense moviments!$"

BattleDome_Text_Round1Match1::
	.string "Ronda 1, Combat 1$"

BattleDome_Text_Round1Match2::
	.string "Ronda 1, Combat 2$"

BattleDome_Text_Round1Match3::
	.string "Ronda 1, Combat 3$"

BattleDome_Text_Round1Match4::
	.string "Ronda 1, Combat 4$"

BattleDome_Text_Round1Match5::
	.string "Ronda 1, Combat 5$"

BattleDome_Text_Round1Match6::
	.string "Ronda 1, Combat 6$"

BattleDome_Text_Round1Match7::
	.string "Ronda 1, Combat 7$"

BattleDome_Text_Round1Match8::
	.string "Ronda 1, Combat 8$"

BattleDome_Text_Round2Match1::
	.string "Ronda 2, Combat 1$"

BattleDome_Text_Round2Match2::
	.string "Ronda 2, Combat 2$"

BattleDome_Text_Round2Match3::
	.string "Ronda 2, Combat 3$"

BattleDome_Text_Round2Match4::
	.string "Ronda 2, Combat 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Semifinal, Combat 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Semifinal, Combat 2$"

BattleDome_Text_FinalMatch::
	.string "Combat Final$"
