PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "Papà: Hola, {PLAYER}!\p"
	.string "Acabo de rebre una Baia molt rara.\n"
	.string "M'agradaria que te la quedessis.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Si veus Baies creixent en terra\n"
	.string "tova, pots agafar-les.\p"
	.string "Però assegura't de plantar-hi una\n"
	.string "Baia. És qüestió de cortesia.\p"
	.string "Toma, en comparteixo una amb tu.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Amb la pinta que fas, deus ser\n"
	.string "un Entrenador, oi?\p"
	.string "Els Entrenadors sovint fan que\n"
	.string "els Pokémon duguin Baies.\p"
	.string "Depèn de tu si vols cultivar\n"
	.string "Baies o usar-les.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Vaig regar les plantes cada dia.\n"
	.string "Van créixer moltes flors.\p"
	.string "I també em van donar moltes Baies.\p"
	.string "Aquí tens!\n"
	.string "Pots quedar-te-la!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Intentaré amb molt d'esforç fer\n"
	.string "Baies de colors diferents.\p"
	.string "Espero que tu també t'esforcis!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Quines Baies de quin color\n"
	.string "buscaré avui?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "M'encanta usar la màquina\n"
	.string "Triturador de Baies, per això\l"
	.string "les col·lecciono.\p"
	.string "En comparteixo una amb tu, si vols.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Hauries de provar la màquina\n"
	.string "Triturador de Baies amb amics.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Quina Baia plantar?\n"
	.string "Usar-les o guardar-les?\p"
	.string "És divertit pensar-hi.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Les Baies creixen absorbint la llum solar.\p"
	.string "Les ajudem a créixer regant-les\n"
	.string "regularment.\p"
	.string "És una expressió d'amor, oi?$"

Route120_Text_YesYouUnderstand:
	.string "Sí, sí.\n"
	.string "Entens el que vull dir.\p"
	.string "Hauries de prendre-la.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Però és important fer-se\n"
	.string "les pròpies impressions, suposo…\p"
	.string "Pots quedar-te-la.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Crec que aquesta Baia és rara.\n"
	.string "Espero que la cuides amb amor.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Aconseguiré més Baies del\n"
	.string "Mestre de les Baies.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Pensant-hi bé…\p"
	.string "De la mateixa manera que\n"
	.string "el vestit m'escau perfectament,\p"
	.string "una brisa fresca escau al mar.\p"
	.string "I a tu, una Baia t'escau\n"
	.string "perfectament… Per qué serà?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Pensant-hi bé…\p"
	.string "És perquè ets un Entrenador!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Pensant-hi bé…\p"
	.string "Com la senzillesa m'escau,\n"
	.string "els {POKEBLOCK}s escauen als Pokémon.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Em pots dir el Mestre de les Baies.\p"
	.string "Somio amb omplir el món de\n"
	.string "flors boniques, per això cultivo\l"
	.string "Baies i les reparteixo a tothom.\p"
	.string "Te la mereixes!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Per qué ser gasiu?\n"
	.string "Pren-ne una altra!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Assegura't de visitar la\n"
	.string "botiga de flors Pètal Bonic.\p"
	.string "Que les flors omplin el món!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Per avui ja he acabat.\n"
	.string "Torna un altre dia.\p"
	.string "Que les flors omplin el món!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "La manera com el meu marit\n"
	.string "cultiva Baies, oh, és el millor del món.\p"
	.string "Em fa estar orgullosa, és clar.\p"
	.string "Per cert, nen, has sentit\n"
	.string "algun bon refrany darrerament?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! Quin refrany tan notable!\n"
	.string "Inspirador, de debò!\p"
	.string "Vull que te la quedes.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! Un bon refrany.\n"
	.string "Ets força notable.\p"
	.string "Vull que te la quedes.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Els nostres quatre néts haurien de\n"
	.string "ser més experts que el meu marit.\p"
	.string "L'alegria mai no marxa de la meva vida!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Hola!\p"
	.string "Aquesta és la botiga de flors\n"
	.string "Pètal Bonic. Omplint el món de flors!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, vols aprendre\n"
	.string "sobre les Baies?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Com et dius?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Quin nom tan bonic.\p"
	.string "{PLAYER}{KUN}, vols aprendre\n"
	.string "sobre les Baies?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Les Baies creixen en arbres que\n"
	.string "prosperen en terra tova i fèrtil.\p"
	.string "Si agafes Baies, assegura't de\n"
	.string "plantar-ne una a la terra.\p"
	.string "Una Baia plantada aviat brotarà,\n"
	.string "creixerà, florirà belloament,\l"
	.string "i tornarà a donar Baies.\p"
	.string "Vull veure el món sencer\n"
	.string "ple de flors boniques.\l"
	.string "Aquell és el meu somni.\p"
	.string "Ajuda'm, {PLAYER}{KUN}. Planta Baies\n"
	.string "i porta més flors al món.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Les flors porten tanta felicitat\n"
	.string "a la gent, oi?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Hola!\p"
	.string "Com més atenció dones a les flors,\n"
	.string "més bellament floreixen.\p"
	.string "T'agradarà tenir-ne cura. Segur\n"
	.string "que sí. Pots quedar-te-la.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Mentre les plantes de Baies creixen,\n"
	.string "rega-les amb el Regador Wailmer.\p"
	.string "Una altra cosa.\p"
	.string "Si no collides Baies durant un temps,\n"
	.string "cauran al terra.\l"
	.string "Però tornaran a brotar.\p"
	.string "No és increïble?\n"
	.string "Sembla que tinguin voluntat de viure.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Intento ser com les meves germanes\n"
	.string "grans. Jo també cultivo flors!\p"
	.string "Aquí tens!\n"
	.string "És per a tu!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Pots plantar una Baia i fer-la créixer,\n"
	.string "o fer que un Pokémon la dugui.\p"
	.string "Però ara hi ha una màquina que barreja\n"
	.string "Baies i fa llaminadures per als\l"
	.string "Pokémon.\p"
	.string "Jo també en vull!$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hola, com et dius?\p"
	.string "… … …  … … …  … … …\n"
	.string "D'acord. Quin nom tan bonic!\p"
	.string "Em dic Kiri.\p"
	.string "La meva mama i el meu papa em van\n"
	.string "posar aquest nom perquè creixés\l"
	.string "sana i de bon cor.\l"
	.string "Aquell va ser el seu desig.\p"
	.string "Pots quedar-te una d'aquestes.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "La Kiri et donarà també aquesta Baia!\n"
	.string "M'agrada molt!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Em pregunto quin tipus de desig\n"
	.string "hi ha al teu nom.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Primavera, estiu, tardor i hivern.\p"
	.string "Si has nascut a la primavera,\n"
	.string "t'agrada la primavera, i si has\l"
	.string "nascut a l'estiu, t'agrada l'estiu?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Llavors la Kiri ha nascut a la tardor,\n"
	.string "per això m'encanta la tardor!\p"
	.string "Quina estació t'agrada a tu?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "Tant se val…\p"
	.string "Hi ha tantes coses que vull saber…$"
