gText_Birch_Welcome::
    .string "Hola!\n"
    .string "Encantat de conèixer-te!\p"
    .string "Benvingut al món dels Pokémon!\p"
    .string "Em dic Oak.\p"
    .string "La gent m'anomena afectuosament\n"
    .string "el Professor Pokémon.\p"
    .string "$"

gText_Birch_Pokemon::
	.string "Aquest món…\p"
	.string "$"

gText_Birch_MainSpeech::
    .string "…està habitat arreu per\n"
    .string "criatures anomenades Pokémon.\p"
    .string "Per a alguns, els Pokémon són mascotes.\n"
    .string "Altres els fan servir per combatre.\p"
    .string "Pel que fa a mi…\p"
    .string "Jo estudio els Pokémon de professió.\p"
    .string "$"

gText_Birch_AndYouAre::
    .string "Però primer, explica'm una mica sobre\n"
    .string "tu mateix.\p$"

gText_Birch_BoyOrGirl::
	.string "Ets un noi?\n"
	.string "O ets una noia?$"

gText_Birch_WhatsYourName::
    .string "Comencem pel teu nom.\n"
    .string "Com et dius?$"

gText_Birch_SoItsPlayer::
    .string "D'acord…\n"
    .string "Així que et dius {PLAYER}.$"

gText_Birch_ThisIsYourRival::
    .string "Aquest és el meu nét.\p"
    .string "És el teu rival des que tots dos\n"
    .string "éreu nadons.\p"
    .string "…Ehm, com es deia?$"

gText_Birch_ConfirmRivalName::
    .string "…Ehm, era {RIVAL}?$"

gText_Birch_YourePlayer::
    .string "Això mateix! Ara me'n recordo!\n"
    .string "Es diu {RIVAL}!\p$"

gText_Birch_AreYouReady::
    .string "{PLAYER}!\p"
    .string "La teva pròpia llegenda Pokémon\n"
    .string "està a punt de començar!\p"
    .string "Un món de somnis i aventures\n"
    .string "amb Pokémon t'espera! Endavant!\p"
    .string "$"

