gText_Birch_Welcome::
    .string "Hola!\n"
    .string "Encantat de conèixer-te!\p"
    .string "Benvingut al món dels Pokémon!\p"
    .string "Em dic Oak.\p"
    .string "La gent em coneix afectuosament\n"
    .string "com el Professor Pokémon.\p"
    .string "$"

gText_Birch_Pokemon::
	.string "Aquest món…\p"
	.string "$"

gText_Birch_MainSpeech::
    .string "…està habitat arreu per\n"
    .string "criatures anomenades Pokémon.\p"
    .string "Per a algunes persones, els Pokémon\n"
    .string "són mascotes. Altres els usen per\l"
    .string "barallar.\p"
    .string "Quant a mi…\p"
    .string "Estudio els Pokémon professionalment.\p"
    .string "$"

gText_Birch_AndYouAre::
    .string "Però primer, explica'm una mica\n"
    .string "sobre tu.\p$"

gText_Birch_BoyOrGirl::
	.string "Ets un noi?\n"
	.string "O ets una noia?$"

gText_Birch_WhatsYourName::
    .string "Comencem pel teu nom.\n"
    .string "Com et dius?$"

gText_Birch_SoItsPlayer::
    .string "Bé…\n"
    .string "Llavors et dius {PLAYER}.$"

gText_Birch_ThisIsYourRival::
    .string "Aquest és el meu nét.\p"
    .string "Ha estat el teu rival des que\n"
    .string "tots dos éreu bebès.\p"
    .string "…Hmm, com es deia?$"

gText_Birch_ConfirmRivalName::
    .string "…Era {RIVAL}, oi?$"

gText_Birch_YourePlayer::
    .string "Exacte! Ara recordo!\n"
    .string "Es diu {RIVAL}!\p$"

gText_Birch_AreYouReady::
    .string "{PLAYER}!\p"
    .string "La teva pròpia llegenda Pokémon\n"
    .string "està a punt de desplegarse!\p"
    .string "Un món de somnis i aventures\n"
    .string "amb Pokémon t'espera! Endavant!\p"
    .string "$"
