BerryBlender_Text_BlendWithTheBlendMaster:
	.string "Mestre Barrejador: En efecte!\n"
	.string "Jo sóc el Mestre Barrejador!\p"
	.string "Barreja amb mi i veuràs\n"
	.string "la maestria que aporto a la barreja!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "Mestre Barrejador: Hmm! Llavors,\n"
	.string "vols veure la meva maestria en acció?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmm!\p"
	.string "Sembla que ara ets massa ocupat!\p"
	.string "Però no temis!\n"
	.string "Aquí estaré tot el dia!\l"
	.string "Torna ràpid del teu encàrrec!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmm!\p"
	.string "No tens ni una sola Baia!\p"
	.string "Aquí estaré tot el dia!\n"
	.string "Torna ràpid amb algunes Baies!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Per descomptat!\n"
	.string "Per descomptat!\p"
	.string "Per cert…\n"
	.string "Saps com barrejar {POKEBLOCK}S\l"
	.string "a partir de Baies?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmm!\p"
	.string "Però és un procés senzill!\p"
	.string "Quan la fletxa de la Batedora arribi\n"
	.string "al teu marcador, prem el Botó A.\p"
	.string "Això és tot el que has de fer.\p"
	.string "Quan vegis amb quina precisió\n"
	.string "premo el Botó A, entendràs.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Molt bé!\p"
	.string "Comencem, doncs!\p"
	.string "Tots junts amb el Mestre Barrejador,\n"
	.string "anem a la Batedora de Baies!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmm!\p"
	.string "No sembla que tinguis la\n"
	.string "Capseta de {POKEBLOCK}!\p"
	.string "Aquí estaré tot el dia!\n"
	.string "Aconsegueix la Capseta i torna ràpid!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmm!\p"
	.string "La teva Capseta de {POKEBLOCK} sembla plena!\p"
	.string "Aquí estaré tot el dia!\n"
	.string "Usa alguns {POKEBLOCK}S i torna ràpid!$"

BerryBlender_Text_WhoaAwesome:
	.string "Vaja!\n"
	.string "Increïble!$"

BerryBlender_Text_WickedlyFast:
	.string "Velocíssim!$"

BerryBlender_Text_WhatAnExpert:
	.string "Quin expert!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Quan vaig barrejar amb el Mestre,\n"
	.string "vam fer {POKEBLOCK}S increïbles!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Ulls que segueixen la fletxa\n"
	.string "amb intensitat maquinal…\p"
	.string "Una mà que prem el Botó A\n"
	.string "amb precisió de rellotge…\p"
	.string "Tenir aquestes qualitats fa\n"
	.string "el Mestre Barrejador realment gran.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Se suposa que el Mestre Barrejador\n"
	.string "treballa les seves habilitats a les\l"
	.string "muntanyes.\p"
	.string "De vegades, ve a Lilycove\n"
	.string "a barrejar Baies tot el dia.$"
