BerryBlender_Text_BlendWithTheBlendMaster:
	.string "Mestre Barrejador: En efecte!\n"
	.string "Jo sóc el Mestre Barrejador!\p"
	.string "Barreja amb mi i veuràs\n"
	.string "la mestria que aporto a la barreja!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "Mestre Barrejador: Hmm! Llavors,\n"
	.string "vols veure la meva mestria en acció?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmm!\p"
	.string "Sembla que ara estàs massa {MASC}ocupat{FEM}ocupada{ENDG}!\p"
	.string "Però no temis!\n"
	.string "Aquí estaré tot el dia!\l"
	.string "Enllesteix l'encàrrec i torna aviat!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmm!\p"
	.string "No tens ni una sola Baia!\p"
	.string "Aquí estaré tot el dia!\n"
	.string "Torna ràpid amb algunes Baies!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Per descomptat!\n"
	.string "Per descomptat!\p"
	.string "Per cert…\n"
	.string "Saps com barrejar {POKEBLOCK}S\l"
	.string "a partir de Baies?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmm!\p"
	.string "Però és un procés senzill!\p"
	.string "Quan la fletxa de la Batedora arribi\n"
	.string "al teu marcador, prem el Botó A.\p"
	.string "Això és tot el que has de fer.\p"
	.string "Quan vegis amb quina precisió\n"
	.string "premo el Botó A, ho entendràs.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Molt bé!\p"
	.string "Comencem, doncs!\p"
	.string "Tots junts amb el Mestre Barrejador,\n"
	.string "anem a la Batedora de Baies!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmm!\p"
	.string "Sembla que no tens la\n"
	.string "Capseta de {POKEBLOCK}!\p"
	.string "Aquí estaré tot el dia!\n"
	.string "Aconsegueix la Capseta i torna ràpid!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmm!\p"
	.string "La teva Capseta de {POKEBLOCK} sembla plena!\p"
	.string "Aquí estaré tot el dia!\n"
	.string "Usa alguns {POKEBLOCK}S i torna ràpid!$"

BerryBlender_Text_WhoaAwesome:
	.string "Vaja!\n"
	.string "Increïble!$"

BerryBlender_Text_WickedlyFast:
	.string "Velocíssim!$"

BerryBlender_Text_WhatAnExpert:
	.string "Quin expert!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Quan vaig barrejar amb el Mestre,\n"
	.string "vam fer {POKEBLOCK}S increïbles!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Ulls que segueixen la fletxa\n"
	.string "amb intensitat maquinal…\p"
	.string "Una mà que prem el Botó A\n"
	.string "amb precisió de rellotge…\p"
	.string "Aquestes qualitats fan que el\n"
	.string "Mestre Barrejador sigui realment gran.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Diuen que el Mestre Barrejador\n"
	.string "perfecciona la seva tècnica al cor\l"
	.string "de les muntanyes.\p"
	.string "De vegades, ve a Lilycove\n"
	.string "a barrejar Baies tot el dia.$"
