CableClub_Text_WelcomeWhichCableClubService:
	.string "Benvingut al Club de Cable\n"
	.string "Pokémon.\p"
	.string "Quin dels nostres serveis\n"
	.string "vols usar?$"

CableClub_Text_WhichService:
	.string "Quin dels nostres serveis\n"
	.string "vols usar?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Intercanvia Pokémon amb un altre\n"
	.string "jugador usant un cable GBA Game Link.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Pots batallar amb un altre\n"
	.string "Entrenador usant un cable\l"
	.string "GBA Game Link.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Pots usar el Racó de Registres\n"
	.string "amb altres usant un cable\l"
	.string "GBA Game Link.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Tanca aquest menú.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Per a una Batalla Doble, has\n"
	.string "de tenir almenys dos Pokémon.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Per a intercanviar, has de tenir\n"
	.string "almenys dos Pokémon amb tu.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "Un Pokémon que porta la Baia\n"
	.string "{STR_VAR_1} no es pot intercanviar.$"

gText_PleaseWaitForLink::
	.string "Espera, si us plau.\n"
	.string "… … Botó B: Cancel·lar$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Quan tots els jugadors estiguin\n"
	.string "a punt…\l"
	.string "Botó A: Confirmar\l"
	.string "Botó B: Cancel·lar$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Iniciar connexió amb {STR_VAR_1} jugadors.\n"
	.string "Botó A: Confirmar\l"
	.string "Botó B: Cancel·lar$"

gText_AwaitingLinkup::
	.string "Esperant connexió…\n"
	.string "… … Botó B: Cancel·lar$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Cal desar el progrés abans de\n"
	.string "connectar. D'acord?$"

CableClub_Text_PleaseEnter:
	.string "Entra, si us plau.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Ara et guiaré a la teva sala.$"

Text_SomeoneIsNotReadyToLink:
	.string "Algú no està a punt per connectar.\p"
	.string "Torna quan tothom hagi\n"
	.string "fet els preparatius.$"

Text_LinkErrorPleaseReset:
	.string "Ho sento, hi ha un error de\n"
	.string "connexió… Reinicia i prova-ho\l"
	.string "de nou.$"

Text_PlayersMadeDifferentSelections:
	.string "Sembla que els companys de connexió\n"
	.string "han fet seleccions diferents.$"

CableClub_Text_PleaseVisitAgain:
	.string "Torna a visitar-nos quan vulguis.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "El nombre de participants\n"
	.string "és incorrecte.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "La Batalla Individual no es pot\n"
	.string "jugar amb {STR_VAR_1} jugadors.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "La Batalla Doble no es pot\n"
	.string "jugar amb {STR_VAR_1} jugadors.$"

CableClub_Text_NeedFourPlayers:
	.string "Cal que hi hagi quatre jugadors\n"
	.string "per a jugar en aquest mode.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Confirmeu el nombre de jugadors\n"
	.string "i torneu a començar.$"

Text_TerminateLinkConfirmation:
	.string "La connexió s'interromprà si\n"
	.string "surts de la sala. D'acord?$"

Text_TerminateLinkPleaseWait:
	.string "Interrompent connexió…\n"
	.string "Seràs acompanyat fora\l"
	.string "de la sala. Espera.$"

CableClub_Text_TooBusyToNotice:
	.string "Aquest Entrenador és massa ocupat\n"
	.string "per a adonar-se'n…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Genial! He pogut veure el Carnet\n"
	.string "d'Entrenador de {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Genial! He pogut veure el Carnet\n"
	.string "d'Entrenador de {STR_VAR_1}!\p"
	.string "És un carnet {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Col·loca't al teu lloc i\n"
	.string "comença la batalla.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Seu al teu lloc i\n"
	.string "comença l'intercanvi.$"

RecordCorner_Text_ThanksForComing:
	.string "Gràcies per venir.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Les dades del Carnet d'Entrenador\n"
	.string "seran sobreescrites.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "Espero tornar-te a veure!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Ho sento molt.\p"
	.string "Encara no estem preparats per\n"
	.string "dur a terme intercanvis amb\l"
	.string "Entrenadors d'una altra regió…$"

CableClub_Text_OtherTrainerNotReady:
	.string "L'altre Entrenador no està a punt.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Tens almenys un Pokémon\n"
	.string "que no pot ser agafat.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Seu al teu lloc i espera.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} ha enviat\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Ho sento, hi ha un error de\n"
	.string "transmissió.\p"
	.string "No pots barrejar registres amb\n"
	.string "jocs japonesos de Ruby o Sapphire.\p"
	.string "Tampoc pots barrejar registres\n"
	.string "amb Emerald japonès i Ruby o\l"
	.string "Sapphire estrangers alhora.$"

CableClub_Text_AdapterNotConnected:
	.string "L'Adaptador Sense Fils no\n"
	.string "està connectat correctament.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Es demana als participants que\n"
	.string "s'apropin al taulell de recepció.$"

@ Unused
CableClub_Text_Hello:
	.string "Hola!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Espera, si us plau.$"

CableClub_Text_YouMayTradeHere::
	.string "Aquí pots intercanviar els teus\n"
	.string "Pokémon amb un altre Entrenador.$"

CableClub_Text_YouMayBattleHere::
	.string "Aquí pots batallar amb\n"
	.string "els teus amics.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Entre dos i cinc Entrenadors\n"
	.string "poden fer Pols de Baies junts.$"

CableClub_Text_CanMixRecords::
	.string "Els registres de dos a quatre\n"
	.string "jugadors es poden barrejar.$"

CableClub_Text_GuideToVariousServices:
	.string "Una guia dels diversos serveis\n"
	.string "del Club Sense Fils.$"

CableClub_Text_CancelSelectedItem::
	.string "Cancel·la l'element del menú\n"
	.string "seleccionat.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Quin mode de batalla vols?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Torna al pas anterior.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Per usar el servei Tritura-Baies,\n"
	.string "has de tenir almenys una Baia.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Per entrar a la Sala Unió, has\n"
	.string "de tenir almenys dos Pokémon.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Cap Pokémon que porti la Baia\n"
	.string "{STR_VAR_1} pot entrar a la Sala Unió.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Aquesta és la Sala Unió del\n"
	.string "Club Sense Fils Pokémon.\p"
	.string "Malauradament, el vostre\n"
	.string "Adaptador Sense Fils no\l"
	.string "està connectat correctament.\p"
	.string "Torneu aviat.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "Perdoneu!$"

CableClub_Text_PlayerIsWaiting:
	.string "Sembla que {STR_VAR_1} està jugant\n"
	.string "ara mateix.\l"
	.string "Endavant!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Et puc explicar les regles\n"
	.string "dels jocs, si vols.\p"
	.string "Quin joc vols que descrigui?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "\"Salt Pokémon\"\p"
	.string "Fes que el teu Pokémon salti\n"
	.string "la corda de Fuet Planta amb\l"
	.string "el Botó A.\p"
	.string "Només Pokémon d'unes 28\n"
	.string "polzades o menys poden\l"
	.string "participar.\p"
	.string "Els Pokémon que només neden,\n"
	.string "s'enterren o volen no serveixen\l"
	.string "per a saltar.\p"
	.string "Com a resultat, aquells Pokémon\n"
	.string "no poden participar.\p"
	.string "Passen coses bones si tothom\n"
	.string "salta al ritme.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "\"Recol·lecta de Baies de Dodrio\"\p"
	.string "Ordena els tres caps de Dodrio\n"
	.string "per agafar Baies que cauen.\p"
	.string "Prem dreta, amunt o esquerra al\n"
	.string "{PLUS} Control per moure els caps.\p"
	.string "Per a jugar, has de tenir\n"
	.string "un Dodrio.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Si vols jugar a un joc,\n"
	.string "parla amb el vell que hi ha\l"
	.string "al meu costat.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Hola, benvingut!\n"
	.string "Ets aquí per a jugar usant\l"
	.string "Comunicació Sense Fils?\p"
	.string "Pots esperar un moment?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "D'acord, fins aviat!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "L'Adaptador Sense Fils no\n"
	.string "està connectat. Torna quan\l"
	.string "estigui connectat!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "D'acord, a quin joc volies\n"
	.string "jugar?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Quin Pokémon vols apuntar?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "D'acord, ja ho tens tot!\n"
	.string "Que no et guanyin els altres!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Te'n vas?\n"
	.string "Torna aviat!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Sembla que no tens cap Pokémon\n"
	.string "que puguis apuntar…\p"
	.string "Vols que t'expliqui quin tipus\n"
	.string "de Pokémon pot participar?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "\"Salt Pokémon\" admet Pokémon\n"
	.string "d'unes 28 polzades o menys.\p"
	.string "Els que no poden participar\n"
	.string "són els que no poden saltar.\p"
	.string "Ja saps, els que només neden,\n"
	.string "s'enterren o volen.\p"
	.string "Ja ho saps tot.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "Recol·lecta de Baies de Dodrio\n"
	.string "és un joc exclusiu per a Dodrio.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Podries reintentar-ho des\n"
	.string "del principi?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Benvingut al Racó Directe del\n"
	.string "Club Sense Fils Pokémon.\p"
	.string "Aquí pots interactuar directament\n"
	.string "amb els teus amics.\p"
	.string "A quina sala vols entrar?$"

CableClub_Text_TradePokemon:
	.string "Vols intercanviar Pokémon?$"

CableClub_Text_PlayWhichBattleMode:
	.string "En quin mode de batalla\n"
	.string "vols jugar?$"

CableClub_Text_AccessRecordCorner:
	.string "Vols accedir al\n"
	.string "Racó de Registres?$"

CableClub_Text_UseBerryCrush:
	.string "Vols usar el Sistema\n"
	.string "Tritura-Baies?$"

CableClub_Text_ExplainBattleModes:
	.string "Hi ha tres modes de batalla.\p"
	.string "La Batalla Individual és per a\n"
	.string "dos Entrenadors amb un o\l"
	.string "més Pokémon cadascun.\p"
	.string "Cada Entrenador pot tenir un\n"
	.string "Pokémon en batalla alhora.\p"
	.string "La Batalla Doble és per a dos\n"
	.string "Entrenadors amb dos o més\l"
	.string "Pokémon cadascun.\p"
	.string "Cada Entrenador traurà dos\n"
	.string "Pokémon en batalla alhora.\p"
	.string "La Batalla Multi és per a quatre\n"
	.string "Entrenadors amb un o més\l"
	.string "Pokémon cadascun.\p"
	.string "Cada Entrenador pot tenir un\n"
	.string "Pokémon en batalla alhora.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Decidiu quin de vosaltres dos\n"
	.string "serà el Líder.\p"
	.string "L'altre jugador ha de triar\n"
	.string "\"Unir-se al Grup\".$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Decidiu quin de vosaltres quatre\n"
	.string "serà el Líder del Grup.\p"
	.string "Els altres jugadors han de triar\n"
	.string "\"Unir-se al Grup\".$"

CableClub_Text_ChooseGroupLeader:
	.string "Decidiu quin de vosaltres\n"
	.string "serà el Líder del Grup.\p"
	.string "Els altres jugadors han de triar\n"
	.string "\"Unir-se al Grup\".$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Benvingut a la Sala Unió del\n"
	.string "Club Sense Fils Pokémon.\p"
	.string "Aquí pots interactuar directament\n"
	.string "amb altres Entrenadors, alguns\l"
	.string "dels quals potser no coneixes.\p"
	.string "Vols entrar a la Sala?$"

CableClub_Text_UnionRoomInfo:
	.string "Els Entrenadors a la Sala Unió\n"
	.string "seran aquells jugadors al teu\l"
	.string "voltant que també hi han entrat.\p"
	.string "Pots fer moltes coses aquí,\n"
	.string "com intercanviar salutacions.\p"
	.string "Pots entrar dos Pokémon fins\n"
	.string "al Nv. 30 per a una batalla.\p"
	.string "Pots participar en un xat amb\n"
	.string "dues a cinc persones.\p"
	.string "O pots registrar un Pokémon\n"
	.string "per a intercanviar.\p"
	.string "Vols entrar a la Sala?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Espero que gaudeixis del teu\n"
	.string "temps a la Sala Unió.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Hola!\n"
	.string "Em dic Teala.\p"
	.string "Deu ser la teva primera vegada\n"
	.string "aquí dalt.\p"
	.string "Et mostraré com funciona el\n"
	.string "Sistema de Comunicació Sense Fils.\p"
	.string "Primer, t'he de mostrar\n"
	.string "aquest pis del Centre Pokémon.\p"
	.string "Segueix-me, si us plau.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "A l'últim pis, hi ha dues sales.\p"
	.string "Primer, la sala de l'esquerra.\n"
	.string "És la Sala Unió.\p"
	.string "Pots connectar-te amb Entrenadors\n"
	.string "del teu voltant que també hagin\l"
	.string "entrat a la Sala Unió.\p"
	.string "Amb ells, pots fer coses com\n"
	.string "xatejar, batallar i intercanviar.\p"
	.string "Segon, la sala de la dreta\n"
	.string "és el Racó Directe.\p"
	.string "Pots intercanviar o batallar\n"
	.string "Pokémon amb els teus amics\l"
	.string "en aquesta sala.\p"
	.string "Si l'Adaptador Sense Fils no\n"
	.string "està connectat, encara pots\l"
	.string "connectar usant un cable\l"
	.string "GBA Game Link.\p"
	.string "En aquell cas, has d'anar\n"
	.string "al Racó Directe.\p"
	.string "Espero que gaudeixis del Sistema\n"
	.string "de Comunicació Sense Fils.$"

CableClub_Text_AskAboutLinking:
	.string "Hola, {PLAYER}!\p"
	.string "Sóc la Teala, l'encarregada\n"
	.string "del 2n pis del Centre Pokémon.\p"
	.string "Necessites preguntar-me alguna\n"
	.string "cosa sobre la connexió?$"

CableClub_Text_ExplainWirelessClub:
	.string "Et deixo explicar com funciona\n"
	.string "el Club Sense Fils Pokémon.\p"
	.string "En aquest pis de dalt, hi ha\n"
	.string "dues sales.\p"
	.string "Primer, la sala de l'esquerra.\n"
	.string "És la Sala Unió.\p"
	.string "Pots connectar-te amb Entrenadors\n"
	.string "del teu voltant que també hagin\l"
	.string "entrat a la Sala Unió.\p"
	.string "Amb ells, pots fer coses com\n"
	.string "xatejar, batallar i intercanviar.\p"
	.string "Segon, la sala de la dreta\n"
	.string "és el Racó Directe.\p"
	.string "Pots intercanviar o batallar\n"
	.string "Pokémon amb els teus amics\l"
	.string "en aquesta sala.\p"
	.string "De vegades, potser no trobaràs\n"
	.string "els teus amics a la Sala Unió\l"
	.string "o al Racó Directe.\p"
	.string "En aquell cas, apropa't\n"
	.string "més als teus amics.\p"
	.string "Si l'Adaptador Sense Fils no\n"
	.string "està connectat, encara pots\l"
	.string "connectar usant un cable\l"
	.string "GBA Game Link.\p"
	.string "En aquell cas, has d'anar\n"
	.string "al Racó Directe.\p"
	.string "Espero que gaudeixis del Sistema\n"
	.string "de Comunicació Sense Fils.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "Espero que gaudeixis del Sistema\n"
	.string "de Comunicació Sense Fils.$"
