Text_PictureBookShelf:
	.string "Hi ha una col·lecció de llibres de Pokémon.$"

Text_BookShelf:
	.string "Està ple de tot tipus de llibres.$"

Text_PokemonCenterBookShelf:
	.string "Revistes de Pokémon!\n"
	.string "Amic Pokémon…\p"
	.string "Manual Pokémon…\n"
	.string "Pokémon Adorables…$"

Text_Vase:
	.string "Aquest gerro sembla car…\n"
	.string "Has mirat a dins…\p"
	.string "Però estava buit.$"

Text_EmptyTrashCan:
	.string "Està buit.$"

Text_ShopShelf:
	.string "Les prestatgeries estan plenes de\n"
	.string "tota mena de productes Pokémon.$"

Text_Blueprint:
	.string "Un tipus de plànol?\n"
	.string "És massa complicat!$"

Text_Painting:
	.string "És un quadre d'un\n"
	.string "Pokémon llegendari.$"
