gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_3} de {STR_VAR_2}$"

@ Unused
gContestPaintingContest::
	.string "Concurs$"

gContestRankNormal::
	.string "Rang Normal$"

gContestRankSuper::
	.string "Rang Súper$"

gContestRankHyper::
	.string "Rang Hiper$"

gContestRankMaster::
	.string "Rang Màster$"

gContestLink::
	.string "Enllaç$"

gContestCoolness::
	.string "Frescor$"

gContestBeauty::
	.string "Bellesa$"

gContestCuteness::
	.string "Tendresa$"

gContestSmartness::
	.string "Intel·ligència$"

gContestToughness::
	.string "Força$"

gContestPaintingCool1::
	.string "Supercool sense parar:\n"
	.string "l'inestimable {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Ei, hola!\n"
	.string "El guapíssim Pokémon {STR_VAR_1}$"

gContestPaintingCool3::
	.string "El meravellós, fantàstic i\n"
	.string "magnífic {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "L'última Venus d'aquest segle:\n"
	.string "el bellíssim {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "El somriure enlluernador\n"
	.string "i escintil·lant de {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "El gran ídol del Centre Pokémon:\n"
	.string "l'incomparable {STR_VAR_1}$"

gContestPaintingCute1::
	.string "El bonic i dolç {STR_VAR_1}$"

gContestPaintingCute2::
	.string "El retrat guanyador\n"
	.string "del preciós {STR_VAR_1}$"

gContestPaintingCute3::
	.string "Fes-nos l'ullet!\n"
	.string "El bufó Pokémon {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "El mestre de la intel·ligència:\n"
	.string "el savi Pokémon {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}: l'escollit\n"
	.string "d'entre tots els Pokémon$"

gContestPaintingSmart3::
	.string "El moment d'elegància\n"
	.string "de l'excel·lent {STR_VAR_1}$"

gContestPaintingTough1::
	.string "El poderós i musculós\n"
	.string "velocista {STR_VAR_1}$"

gContestPaintingTough2::
	.string "El fort, més fort i\n"
	.string "fortíssim {STR_VAR_1}$"

gContestPaintingTough3::
	.string "El poderós i duríssim\n"
	.string "hiper Pokémon {STR_VAR_1}$"
