@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "Moviment molt atractiu.$"

gText_UserMoreEasilyStartled::
	.string "Després d'usar-lo, l'usuari\n"
	.string "es pertorba més fàcilment.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Actua molt bé, però ja no\n"
	.string "pot tornar a actuar.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Es pot repetir sense\n"
	.string "avorrir el Jutge.$"

gText_AvoidStartledByOthersOnce::
	.string "Pot evitar un cop que\n"
	.string "els altres el pertorbin.$"

gText_AvoidStartledByOthers::
	.string "Pot evitar que els\n"
	.string "altres el pertorbin.$"

gText_AvoidStartledByOthersLittle::
	.string "Pot evitar una mica que\n"
	.string "els altres el pertorbin.$"

gText_UserLessLikelyStartled::
	.string "Després d'usar-lo, l'usuari\n"
	.string "es pertorba menys.$"

gText_SlightlyStartleFrontMon::
	.string "Pertorba una mica el\n"
	.string "Pokémon anterior.$"

gText_SlightlyStartleAppealed::
	.string "Pertorba una mica els\n"
	.string "que ja han actuat.$"

gText_StartleAppealedBeforeUser::
	.string "Pertorba el Pokémon que\n"
	.string "ha actuat abans que ell.$"

gText_StartleAllAppealed::
	.string "Pertorba tots els que\n"
	.string "ja han actuat.$"

gText_BadlyStartleFrontMon::
	.string "Pertorba molt el\n"
	.string "Pokémon anterior.$"

gText_BadlyStartleAppealed::
	.string "Pertorba molt els que\n"
	.string "ja han actuat.$"

gText_StartleAppealedBeforeUser2::
	.string "Pertorba el Pokémon que\n"
	.string "ha actuat abans que ell.$"

gText_StartleAllAppealed2::
	.string "Pertorba tots els que\n"
	.string "ja han actuat.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Aparta l'atenció del\n"
	.string "Jutge dels altres.$"

gText_StartleMonHasJudgesAttention::
	.string "Pertorba el Pokémon que\n"
	.string "té l'atenció del Jutge.$"

gText_JamOthersMissesTurn::
	.string "Pertorba els altres, però\n"
	.string "perd un torn d'actuació.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Pertorba qui ha actuat\n"
	.string "amb el mateix tipus.$"

gText_BadlyStartleCoolAppeals::
	.string "Pertorba molt qui ha\n"
	.string "mostrat Frescor.$"

gText_BadlyStartleBeautyAppeals::
	.string "Pertorba molt qui ha\n"
	.string "mostrat Bellesa.$"

gText_BadlyStartleCuteAppeals::
	.string "Pertorba molt qui ha\n"
	.string "mostrat Tendresa.$"

gText_BadlyStartleSmartAppeals::
	.string "Pertorba molt qui ha\n"
	.string "mostrat Intel·ligència.$"

gText_BadlyStartleToughAppeals::
	.string "Pertorba molt qui ha\n"
	.string "mostrat Força.$"

gText_MakeMonAfterUserNervous::
	.string "Posa nerviós un Pokémon\n"
	.string "que actua després.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Posa nerviosos tots els\n"
	.string "que actuen després.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Empitjora la condició\n"
	.string "dels que han actuat.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Pertorba molt els\n"
	.string "Pokémon en bona condició.$"

gText_AppealGreatIfPerformedFirst::
	.string "Funciona molt bé si\n"
	.string "actua en primer lloc.$"

gText_AppealGreatIfPerformedLast::
	.string "Funciona molt bé si\n"
	.string "actua en últim lloc.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Fa l'actuació tan bona\n"
	.string "com les anteriors.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Fa l'actuació tan bona\n"
	.string "com l'anterior.$"

gText_AppealBetterLaterItsPerformed::
	.string "Funciona millor com més\n"
	.string "tard es fa.$"

gText_AppealVariesDependingOnTiming::
	.string "La qualitat de l'actuació\n"
	.string "varia segons el moment.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Va bé si és del mateix\n"
	.string "tipus que l'anterior.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Va bé si és d'un tipus\n"
	.string "diferent de l'anterior.$"

gText_AffectedByAppealInFront::
	.string "Depèn de com hagi anat\n"
	.string "l'actuació anterior.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Millora la condició de\n"
	.string "l'usuari. Evita els nervis.$"

gText_AppealWorksWellIfConditionGood::
	.string "Funciona bé si la condició\n"
	.string "de l'usuari és bona.$"

gText_NextAppealMadeEarlier::
	.string "Al torn següent, podrà\n"
	.string "actuar abans.$"

gText_NextAppealMadeLater::
	.string "Al torn següent, podrà\n"
	.string "actuar més tard.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Facilita que l'ordre del\n"
	.string "proper torn es barregi.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Barreja l'ordre d'actuació\n"
	.string "del torn següent.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "Emociona el públic en\n"
	.string "qualsevol Concurs.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Pertorba molt tots els que\n"
	.string "han fet bones actuacions.$"

gText_AppealBestMoreCrowdExcited::
	.string "Funciona millor com més\n"
	.string "emocionat està el públic.$"

gText_TemporarilyStopCrowdExcited::
	.string "Atura temporalment que\n"
	.string "el públic s'emocioni.$"

@ Strings for new Summary Screen

gText_FourLine_HighlyAppealingMove::
	.string "Un moviment\nmolt atractiu.$"

gText_FourLine_UserMoreEasilyStartled::
	.string "Després\nd'usar-lo, es\npertorba més\nfàcilment.$"

gText_FourLine_GreatAppealButNoMoreToEnd::
	.string "Actua molt bé,\nperò ja no pot\ntornar a\nactuar.$"

gText_FourLine_UsedRepeatedlyWithoutBoringJudge::
	.string "Es pot repetir\nsense avorrir\nel Jutge.$"

gText_FourLine_AvoidStartledByOthersOnce::
	.string "Pot evitar un\ncop que els\naltres el\npertorbin.$"

gText_FourLine_AvoidStartledByOthers::
	.string "Pot evitar\nque els altres\nel pertorbin.$"

gText_FourLine_AvoidStartledByOthersLittle::
	.string "Pot evitar una\nmica que els\naltres el\npertorbin.$"

gText_FourLine_UserLessLikelyStartled::
	.string "Després\nd'usar-lo, es\npertorba menys\nfàcilment.$"

gText_FourLine_SlightlyStartleFrontMon::
	.string "Pertorba una\nmica el Pokémon\nanterior.$"

gText_FourLine_SlightlyStartleAppealed::
	.string "Pertorba una\nmica els que\nja han actuat.$"

gText_FourLine_StartleAppealedBeforeUser::
	.string "Pertorba el\nPokémon que ha\nactuat abans\nque ell.$"

gText_FourLine_StartleAllAppealed::
	.string "Pertorba tots\nels que ja\nhan actuat.$"

gText_FourLine_BadlyStartleFrontMon::
	.string "Pertorba molt\nel Pokémon\nanterior.$"

gText_FourLine_BadlyStartleAppealed::
	.string "Pertorba molt\nels que ja\nhan actuat.$"

gText_FourLine_StartleAppealedBeforeUser2::
	.string "Pertorba el\nPokémon que ha\nactuat abans\nque ell.$"

gText_FourLine_StartleAllAppealed2::
	.string "Pertorba tots\nels que ja\nhan actuat.$"

gText_FourLine_ShiftJudgesAttentionFromOthers::
	.string "Aparta l'atenció\ndel Jutge dels\naltres.$"

gText_FourLine_StartleMonHasJudgesAttention::
	.string "Pertorba el\nPokémon que\nté l'atenció\ndel Jutge.$"

gText_FourLine_JamOthersMissesTurn::
	.string "Pertorba els\naltres, però\nperd un torn\nd'actuació.$"

gText_FourLine_StartleMonsMadeSameTypeAppeal::
	.string "Pertorba els\nque han actuat\namb el mateix\ntipus.$"

gText_FourLine_BadlyStartleCoolAppeals::
	.string "Pertorba molt\nqui ha\nmostrat\nFrescor.$"

gText_FourLine_BadlyStartleBeautyAppeals::
	.string "Pertorba molt\nqui ha\nmostrat\nBellesa.$"

gText_FourLine_BadlyStartleCuteAppeals::
	.string "Pertorba molt\nqui ha\nmostrat\nTendresa.$"

gText_FourLine_BadlyStartleSmartAppeals::
	.string "Pertorba molt\nqui ha\nmostrat\nIntel·ligència.$"

gText_FourLine_BadlyStartleToughAppeals::
	.string "Pertorba molt\nqui ha\nmostrat\nForça.$"

gText_FourLine_MakeMonAfterUserNervous::
	.string "Posa nerviós\nun Pokémon que\nactua després.$"

gText_FourLine_MakeAllMonsAfterUserNervous::
	.string "Posa nerviosos\ntots els que\nactuen després.$"

gText_FourLine_WorsenConditionOfThoseMadeAppeals::
	.string "Empitjora la\ncondició dels\nque han\nactuat.$"

gText_FourLine_BadlyStartleMonsGoodCondition::
	.string "Pertorba molt\nels Pokémon en\nbona condició.$"

gText_FourLine_AppealGreatIfPerformedFirst::
	.string "Funciona molt\nbé si actua en\nprimer lloc.$"

gText_FourLine_AppealGreatIfPerformedLast::
	.string "Funciona molt\nbé si actua en\núltim lloc.$"

gText_FourLine_AppealAsGoodAsThoseBeforeIt::
	.string "Fa l'actuació\ntan bona com\nles anteriors.$"

gText_FourLine_AppealAsGoodAsOneBeforeIt::
	.string "Fa l'actuació\ntan bona com\nl'anterior.$"

gText_FourLine_AppealBetterLaterItsPerformed::
	.string "Funciona\nmillor com més\ntard es fa.$"

gText_FourLine_AppealVariesDependingOnTiming::
	.string "La qualitat\nde l'actuació\nvaria segons\nel moment.$"

gText_FourLine_WorksWellIfSameTypeAsBefore::
	.string "Va bé si\nté el tipus\nde l'actuació\nanterior.$"

gText_FourLine_WorksWellIfDifferentTypeAsBefore::
	.string "Va bé si\nno té el tipus\nde l'actuació\nanterior.$"

gText_FourLine_AffectedByAppealInFront::
	.string "Depèn de\ncom va anar\nl'actuació\nanterior.$"

gText_FourLine_UpsConditionHelpsPreventNervousness::
	.string "Millora la\ncondició de\nl'usuari. Evita\nels nervis.$"

gText_FourLine_AppealWorksWellIfConditionGood::
	.string "Funciona bé\nsi l'usuari\nestà en bona\ncondició.$"

gText_FourLine_NextAppealMadeEarlier::
	.string "Al torn\nsegüent,\npodrà actuar\nabans.$"

gText_FourLine_NextAppealMadeLater::
	.string "Al torn\nsegüent,\npodrà actuar\nmés tard.$"

gText_FourLine_TurnOrderMoreEasilyScrambled::
	.string "Facilita que\nl'ordre del\nproper torn\nes barregi.$"

gText_FourLine_ScrambleOrderOfNextAppeals::
	.string "Barreja\nl'ordre\nd'actuació del\ntorn següent.$"

gText_FourLine_AppealExcitesAudienceInAnyContest::
	.string "Emociona el\npúblic en\nqualsevol\nConcurs.$"

gText_FourLine_BadlyStartlesMonsGoodAppeals::
	.string "Pertorba molt\nels que han\nfet bones\nactuacions.$"

gText_FourLine_AppealBestMoreCrowdExcited::
	.string "Funciona\nmillor com\nmés emocionat\nestà el públic.$"

gText_FourLine_TemporarilyStopCrowdExcited::
	.string "Atura\ntemporalment\nque el públic\ns'emocioni.$"

@ Unused move names

gText_RainDance::
	.string "Dansa Pluja$"

gText_Rage::
	.string "Fúria$"

gText_FocusEnergy::
	.string "Concentrar-se$"

gText_Hypnosis::
	.string "Hipnosi$"

gText_Softboiled::
	.string "Ou Bullit$"

gText_HornAttack::
	.string "Atac Banya$"

gText_SwordsDance::
	.string "Dansa Espases$"

gText_Conversion::
	.string "Conversió$"

gText_SunnyDay::
	.string "Dia Clar$"

gText_Rest2::
	.string "Descans$"

gText_Vicegrip::
	.string "Presa Forta$"

gText_DefenseCurl::
	.string "Enduriment$"

gText_LockOn::
	.string "Punt de Mira$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "Frescor$"

gContestMoveTypeBeautyText::
	.string "Bellesa$"

gContestMoveTypeCuteText::
	.string "Tendresa$"

gContestMoveTypeSmartText::
	.string "Intel·ligència$"

gContestMoveTypeToughText::
	.string "Força$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "Actuació núm. {STR_VAR_1}!\n"
	.string "Quin moviment es farà?$"

gText_AppealNumButItCantParticipate::
	.string "Actuació núm. {STR_VAR_1}!\n"
	.string "Però no pot participar!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} ha actuat amb\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} observava\n"
	.string "els altres.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "S'ha acabat el\n"
	.string "Temps d'Actuació!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "Però l'actuació ha\n"
	.string "estat pertorbada.$"

gText_FollowedAnotherMonsLead::
	.string "Ha seguit l'exemple\n"
	.string "d'un altre Pokémon.$"

gText_ButItMessedUp::
	.string "Però s'ha equivocat.$"

gText_WentBetterThanUsual::
	.string "Ha anat millor\n"
	.string "que de costum.$"

gText_JudgeLookedAwayForSomeReason::
	.string "Per algun motiu, el Jutge\n"
	.string "ha apartat la mirada.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "S'ha esforçat per\n"
	.string "aprendre dels errors.$"

gText_CantMakeAnyMoreMoves::
	.string "Ja no pot fer\n"
	.string "cap més moviment.$"

gText_WorkedFrighteninglyWell::
	.string "Ha funcionat\n"
	.string "esplèndidament.$"

gText_WorkedHardAsStandoutMon::
	.string "S'ha esforçat tant com\n"
	.string "el Pokémon destacat.$"

gText_JudgedLookedOnExpectantly::
	.string "El Jutge ho ha mirat\n"
	.string "amb expectació.$"

gText_WorkedRatherWell::
	.string "Ha funcionat força bé.$"

gText_WorkedLittleBetterThanUsual::
	.string "Ha funcionat una mica\n"
	.string "millor que de costum.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} no ha\n"
	.string "destacat gens…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} no ha\n"
	.string "destacat gaire…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} ha captat\n"
	.string "una mica d'atenció.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} ha atret\n"
	.string "molta atenció.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} ha acaparat\n"
	.string "tota l'atenció.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} no ha\n"
	.string "actuat.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Expectació per la propera\n"
	.string "actuació de {STR_VAR_1}.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "L'opinió del Jutge sobre\n"
	.string "{STR_VAR_1} no canvia.$"

gText_MonsXChangedPerceptions::
	.string "La {STR_VAR_3} de\n"
	.string "{STR_VAR_1} sorprèn.$"

gText_MonsAppealEffectWoreOff::
	.string "L'efecte de l'actuació\n"
	.string "de {STR_VAR_1} ha passat.$"

gText_SpecialAppealsEffectWoreOff::
	.string "L'efecte de l'actuació\n"
	.string "especial ha passat.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Totes les actuacions han\n"
	.string "quedat iguals.$"

gText_CheapenedMonsAppeal::
	.string "Ha devaluat\n"
	.string "l'actuació de {STR_VAR_2}.$"

gText_CheapenedAppealOfThoseAhead::
	.string "Ha devaluat l'actuació\n"
	.string "dels que anaven davant.$"

gText_StoleAttentionAwayFromMon::
	.string "Ha robat l'atenció\n"
	.string "de {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "Ha devaluat\n"
	.string "l'actuació de {STR_VAR_2}.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "Ha devaluat greument\n"
	.string "les altres actuacions.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Expectació per la propera\n"
	.string "actuació de {STR_VAR_1}.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "Ha devaluat l'actuació\n"
	.string "dels que anaven davant.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "Ha devaluat l'actuació\n"
	.string "preferida del Jutge.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "Les altres actuacions\n"
	.string "valen la meitat.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "Ha brillat per compensar\n"
	.string "que l'han pertorbat.$"

gText_CantParticipateInAppealsAnyMore::
	.string "Ja no pot participar\n"
	.string "en cap actuació.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "Ha commogut el Jutge amb\n"
	.string "una actuació fantàstica.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Creix l'expectació per\n"
	.string "les properes actuacions.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "Ha destacat tant com\n"
	.string "les actuacions especials.$"

gText_StoodOutAsMuchAsMon::
	.string "Ha destacat tant com\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Qui ha estat pertorbat\n"
	.string "ara destaca encara menys.$"

gText_EveryonesAppealsMadeSame::
	.string "Totes les actuacions han\n"
	.string "quedat iguals.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Ara està més pendent\n"
	.string "dels altres Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} no pot actuar\n"
	.string "després d'això.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "S'ha calmat\n"
	.string "una mica.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Ja no fa cas dels\n"
	.string "altres Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Ara està menys pendent\n"
	.string "dels altres Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Ja no es preocupa gaire\n"
	.string "pels altres Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Ha intentat pertorbar\n"
	.string "els altres Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Ha intentat impressionar\n"
	.string "els altres.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "El Jutge ha apartat la\n"
	.string "mirada de {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Ha intentat posar nerviós\n"
	.string "el Pokémon següent.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} s'ha\n"
	.string "posat nerviós.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Ha volgut posar nerviosos\n"
	.string "els Pokémon que esperen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Ha provocat els Pokémon\n"
	.string "que anaven bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} ha tornat\n"
	.string "a estar en forma.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Ha intentat pertorbar els\n"
	.string "que anaven bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "El destacat {STR_VAR_1}\n"
	.string "s'ha esforçat encara més.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "El discret {STR_VAR_1}\n"
	.string "s'ha esforçat molt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "S'ha esforçat tant com\n"
	.string "el Pokémon anterior.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "no ha anat bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "S'ha esforçat tant com\n"
	.string "el Pokémon precedent.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "no ha anat bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "no ha anat bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat una mica bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat força bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat excel·lentment.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha estat un fracàs.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "no ha funcionat gaire bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat una mica bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat força bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat molt bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat excel·lentment.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "És del mateix tipus que\n"
	.string "el Pokémon anterior, bé!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "No és del mateix tipus que\n"
	.string "l'anterior, bé!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Ha destacat molt més\n"
	.string "que el Pokémon anterior.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "No ho ha fet tan bé\n"
	.string "com el Pokémon anterior.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{STR_VAR_1} està en millor\n"
	.string "condició de l'habitual.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{STR_VAR_1}, en ratxa, ha\n"
	.string "fet una gran actuació!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Actuarà abans en el\n"
	.string "proper torn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Actuarà una posició més\n"
	.string "tard en el proper torn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Ha barrejat l'ordre\n"
	.string "del proper torn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "El Jutge mira {STR_VAR_1}\n"
	.string "amb expectació.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "La combinació\n"
	.string "ha agradat.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "La combinació\n"
	.string "ha agradat molt.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "La combinació\n"
	.string "ha estat excel·lent.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} ha aconseguit\n"
	.string "desviar la mirada.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} ha aconseguit\n"
	.string "evitar veure-ho.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} no es\n"
	.string "pertorba per això.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} s'ha\n"
	.string "distret una mica.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "Ha intentat pertorbar\n"
	.string "els altres Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} s'ha distret i\n"
	.string "ha abaixat la mirada.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} s'ha distret i\n"
	.string "s'ha girat d'esquena.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} no ha pogut\n"
	.string "evitar fer un crit.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} no ha pogut\n"
	.string "evitar fer un bot.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} s'ha distret i\n"
	.string "ha ensopegat.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} estava massa\n"
	.string "nerviós per moure's.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "Però s'ha equivocat.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Però no ha aconseguit\n"
	.string "posar nerviós l'objectiu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Però no ha aconseguit\n"
	.string "posar ningú nerviós.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "Però l'han ignorat…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "Però no ha pogut\n"
	.string "millorar la seva condició…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Per la seva mala condició,\n"
	.string "l'actuació ha estat fluixa.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} no ha\n"
	.string "resultat afectat.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "Decepció: {STR_VAR_1}\n"
	.string "ha repetit una actuació.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "La {STR_VAR_3} de\n"
	.string "{STR_VAR_1} triomfa.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "La {STR_VAR_3} de\n"
	.string "{STR_VAR_1} no agrada…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "La {STR_VAR_3} de\n"
	.string "{STR_VAR_1} entusiasma!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} no pot actuar\n"
	.string "el proper torn…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "Ha atret l'atenció\n"
	.string "del públic.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "El públic continua\n"
	.string "observant {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "El públic ignora\n"
	.string "{STR_VAR_2}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "timidesa$"

gText_Contest_Anxiety::
	.string "ansietat$"

gText_Contest_Laziness::
	.string "mandra$"

gText_Contest_Hesitancy::
	.string "indecisió$"

gText_Contest_Fear::
	.string "por$"

gText_Contest_Coolness::
	.string "frescor$"

gText_Contest_Beauty::
	.string "bellesa$"

gText_Contest_Cuteness::
	.string "tendresa$"

gText_Contest_Smartness::
	.string "intel·ligència$"

gText_Contest_Toughness::
	.string "força$"

@ Unused
gText_Tension::
	.string "Tensió$"

gText_CoolMove::
	.string "Moviment de Frescor$"

gText_BeautyMove::
	.string "Moviment de Bellesa$"

gText_CuteMove::
	.string "Moviment de Tendresa$"

gText_SmartMove::
	.string "Moviment d'Intel·ligència$"

gText_ToughMove::
	.string "Moviment de Força$"

gText_3QuestionMarks::
	.string "???$"
