gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_2}'s {STR_VAR_3}$"

@ Unused
gContestPaintingContest::
	.string "Concurs$"

gContestRankNormal::
	.string "Rang Normal$"

gContestRankSuper::
	.string "Rang Súper$"

gContestRankHyper::
	.string "Rang Hiper$"

gContestRankMaster::
	.string "Rang Màster$"

gContestLink::
	.string "Enllaç$"

gContestCoolness::
	.string "Gràcia$"

gContestBeauty::
	.string "Bellesa$"

gContestCuteness::
	.string "Tendresa$"

gContestSmartness::
	.string "Saviesa$"

gContestToughness::
	.string "Potència$"

gContestPaintingCool1::
	.string "Sense parar, supercool--\n"
	.string "l'inestimable {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Ei, hola!\n"
	.string "El guapíssim Pokémon {STR_VAR_1}$"

gContestPaintingCool3::
	.string "El meravellós, fantàstic i\n"
	.string "magnífic {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "L'última Venus d'aquest segle--\n"
	.string "el bellíssim {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "El somriure enlluernador\n"
	.string "i escintil·lant de {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "El super ídol del Centre Pokémon--\n"
	.string "l'incomparable {STR_VAR_1}$"

gContestPaintingCute1::
	.string "El bonic i dolç {STR_VAR_1}$"

gContestPaintingCute2::
	.string "El retrat guanyador\n"
	.string "del preciós {STR_VAR_1}$"

gContestPaintingCute3::
	.string "Fes-nos un guiño!\n"
	.string "El Pokémon maquet {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "El mestre de la saviesa--\n"
	.string "el savi Pokémon {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--l'elegit\n"
	.string "per sobre de tots els Pokémon$"

gContestPaintingSmart3::
	.string "El moment d'elegància\n"
	.string "de l'excel·lent {STR_VAR_1}$"

gContestPaintingTough1::
	.string "El poderós i musculós\n"
	.string "velocista {STR_VAR_1}$"

gContestPaintingTough2::
	.string "El fort, més fort i\n"
	.string "fortíssim {STR_VAR_1}$"

gContestPaintingTough3::
	.string "L'increïblement dur\n"
	.string "hiper Pokémon {STR_VAR_1}$"
