@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Torn perdut$"

gText_LinkStandby4::
	.string "En espera d'enllaç!$"

gText_WinnerIsPlayersMonCongrats::
	.string "El guanyador és {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "Enhorabona!$"

gText_WinnerIsPlayersMon::
	.string "El guanyador és {STR_VAR_2} de {STR_VAR_1}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Judici primari: Núm. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Judici secundari: Núm. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Esdeveniment fix: Núm. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "El moviment usat més sovint:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "El Pokémon més impressionant:\n"
	.string "{STR_VAR_2} de {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Esdeveniment fix: Núm. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "No es farà un programa de TV per\n"
	.string "l'Entrenador que ha perdut.{PAUSE_UNTIL_PRESS}$"
