@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "Un moviment molt atractiu.$"

gText_UserMoreEasilyStartled::
	.string "Després d'aquest moviment,\n"
	.string "l'usuari es pertorba més fàcilment.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Fa una gran actuació, però\n"
	.string "no en pot fer cap més al final.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Es pot usar repetidament\n"
	.string "sense avorriment del Jutge.$"

gText_AvoidStartledByOthersOnce::
	.string "Pot evitar ser pertorbat\n"
	.string "pels altres una vegada.$"

gText_AvoidStartledByOthers::
	.string "Pot evitar ser pertorbat\n"
	.string "pels altres.$"

gText_AvoidStartledByOthersLittle::
	.string "Pot evitar ser pertorbat\n"
	.string "pels altres una mica.$"

gText_UserLessLikelyStartled::
	.string "Després d'aquest moviment,\n"
	.string "l'usuari es pertorba menys.$"

gText_SlightlyStartleFrontMon::
	.string "Pertorba lleugerament el\n"
	.string "Pokémon del davant.$"

gText_SlightlyStartleAppealed::
	.string "Pertorba lleugerament els\n"
	.string "que han actuat.$"

gText_StartleAppealedBeforeUser::
	.string "Pertorba el Pokémon que\n"
	.string "ha actuat abans que l'usuari.$"

gText_StartleAllAppealed::
	.string "Pertorba tots els Pokémon\n"
	.string "que han actuat.$"

gText_BadlyStartleFrontMon::
	.string "Pertorba molt el\n"
	.string "Pokémon del davant.$"

gText_BadlyStartleAppealed::
	.string "Pertorba molt els que\n"
	.string "han actuat.$"

gText_StartleAppealedBeforeUser2::
	.string "Pertorba el Pokémon que\n"
	.string "ha actuat abans que l'usuari.$"

gText_StartleAllAppealed2::
	.string "Pertorba tots els Pokémon\n"
	.string "que han actuat.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Desvia l'atenció del\n"
	.string "Jutge dels altres.$"

gText_StartleMonHasJudgesAttention::
	.string "Pertorba el Pokémon que\n"
	.string "té l'atenció del Jutge.$"

gText_JamOthersMissesTurn::
	.string "Bloqueja els altres i\n"
	.string "perd un torn d'actuació.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Pertorba Pokémon que\n"
	.string "han fet una actuació del mateix tipus.$"

gText_BadlyStartleCoolAppeals::
	.string "Pertorba molt els Pokémon\n"
	.string "amb actuació de Gràcia.$"

gText_BadlyStartleBeautyAppeals::
	.string "Pertorba molt els Pokémon\n"
	.string "amb actuació de Bellesa.$"

gText_BadlyStartleCuteAppeals::
	.string "Pertorba molt els Pokémon\n"
	.string "amb actuació de Tendresa.$"

gText_BadlyStartleSmartAppeals::
	.string "Pertorba molt els Pokémon\n"
	.string "amb actuació de Saviesa.$"

gText_BadlyStartleToughAppeals::
	.string "Pertorba molt els Pokémon\n"
	.string "amb actuació de Potència.$"

gText_MakeMonAfterUserNervous::
	.string "Posa nerviós un Pokémon\n"
	.string "després de l'usuari.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Posa nerviosos tots els\n"
	.string "Pokémon després de l'usuari.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Empitjora la condició dels\n"
	.string "que han actuat.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Pertorba molt els Pokémon\n"
	.string "en bona condició.$"

gText_AppealGreatIfPerformedFirst::
	.string "L'actuació funciona molt bé\n"
	.string "si es fa la primera.$"

gText_AppealGreatIfPerformedLast::
	.string "L'actuació funciona molt bé\n"
	.string "si es fa l'última.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Fa l'actuació tan bona\n"
	.string "com les anteriors.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Fa l'actuació tan bona\n"
	.string "com l'anterior.$"

gText_AppealBetterLaterItsPerformed::
	.string "L'actuació funciona millor\n"
	.string "com més tard es fa.$"

gText_AppealVariesDependingOnTiming::
	.string "La qualitat de l'actuació\n"
	.string "varia segons el moment.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Funciona bé si és del\n"
	.string "mateix tipus que l'anterior.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Funciona bé si és d'un\n"
	.string "tipus diferent a l'anterior.$"

gText_AffectedByAppealInFront::
	.string "Afectat per com va\n"
	.string "l'actuació del davant.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Millora la condició de\n"
	.string "l'usuari. Prevé el nerviosisme.$"

gText_AppealWorksWellIfConditionGood::
	.string "L'actuació funciona bé\n"
	.string "si la condició de l'usuari és bona.$"

gText_NextAppealMadeEarlier::
	.string "La propera actuació es\n"
	.string "pot fer abans al proper torn.$"

gText_NextAppealMadeLater::
	.string "La propera actuació es\n"
	.string "pot fer més tard al proper torn.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Facilita que l'ordre del\n"
	.string "proper torn es barregi.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Barreja l'ordre de les\n"
	.string "actuacions al proper torn.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "Una actuació que emociona\n"
	.string "el públic en qualsevol Concurs.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Pertorba molt tots els\n"
	.string "Pokémon amb bones actuacions.$"

gText_AppealBestMoreCrowdExcited::
	.string "L'actuació funciona millor\n"
	.string "com més emocionat és el públic.$"

gText_TemporarilyStopCrowdExcited::
	.string "Atura temporalment que\n"
	.string "el públic s'emocioni.$"

@ Strings for new Summary Screen

gText_FourLine_HighlyAppealingMove::
	.string "Un moviment\nmolt atractiu.$"

gText_FourLine_UserMoreEasilyStartled::
	.string "Després d'aquest\nmoviment, l'usuari\nes pertorba\nmés fàcilment.$"

gText_FourLine_GreatAppealButNoMoreToEnd::
	.string "Gran actuació,\nperò no en\npot fer més\nal final.$"

gText_FourLine_UsedRepeatedlyWithoutBoringJudge::
	.string "Es pot usar\nrepetidament\nsense avorriment\ndel JUTGE.$"

gText_FourLine_AvoidStartledByOthersOnce::
	.string "Pot evitar\nser pertorbat\npels altres\nuna vegada.$"

gText_FourLine_AvoidStartledByOthers::
	.string "Pot evitar\nser pertorbat\npels altres.$"

gText_FourLine_AvoidStartledByOthersLittle::
	.string "Pot evitar\nser pertorbat\npels altres\nuna mica.$"

gText_FourLine_UserLessLikelyStartled::
	.string "Després d'aquest\nmoviment, l'usuari\nes pertorba\nmenys.$"

gText_FourLine_SlightlyStartleFrontMon::
	.string "Pertorba\nlleugerament el\nPOKéMON\ndel davant.$"

gText_FourLine_SlightlyStartleAppealed::
	.string "Pertorba\nlleugerament els\nque han\nactuat.$"

gText_FourLine_StartleAppealedBeforeUser::
	.string "Pertorba el\nPOKéMON que\nha actuat\nabans que l'usuari.$"

gText_FourLine_StartleAllAppealed::
	.string "Pertorba tots\nels POKéMON\nque han\nactuat.$"

gText_FourLine_BadlyStartleFrontMon::
	.string "Pertorba molt\nel POKéMON\ndel davant.$"

gText_FourLine_BadlyStartleAppealed::
	.string "Pertorba molt\nels que\nhan actuat.$"

gText_FourLine_StartleAppealedBeforeUser2::
	.string "Pertorba el\nPOKéMON que\nha actuat\nabans que l'usuari.$"

gText_FourLine_StartleAllAppealed2::
	.string "Pertorba tots\nels POKéMON\nque han\nactuat.$"

gText_FourLine_ShiftJudgesAttentionFromOthers::
	.string "Desvia l'atenció\ndel JUTGE\ndels altres.$"

gText_FourLine_StartleMonHasJudgesAttention::
	.string "Pertorba el\nPOKéMON que\nté l'atenció\ndel JUTGE.$"

gText_FourLine_JamOthersMissesTurn::
	.string "Bloqueja els\naltres i perd\nun torn\nd'actuació.$"

gText_FourLine_StartleMonsMadeSameTypeAppeal::
	.string "Pertorba POKéMON\nque han fet\nuna actuació\ndel mateix tipus.$"

gText_FourLine_BadlyStartleCoolAppeals::
	.string "Pertorba molt\nPOKéMON\namb actuació\nde GRÀCIA.$"

gText_FourLine_BadlyStartleBeautyAppeals::
	.string "Pertorba molt\nPOKéMON\namb actuació\nde BELLESA.$"

gText_FourLine_BadlyStartleCuteAppeals::
	.string "Pertorba molt\nPOKéMON\namb actuació\nde TENDRESA.$"

gText_FourLine_BadlyStartleSmartAppeals::
	.string "Pertorba molt\nPOKéMON\namb actuació\nde SAVIESA.$"

gText_FourLine_BadlyStartleToughAppeals::
	.string "Pertorba molt\nPOKéMON\namb actuació\nde POTÈNCIA.$"

gText_FourLine_MakeMonAfterUserNervous::
	.string "Posa nerviós\nun POKéMON\ndesprés\nde l'usuari.$"

gText_FourLine_MakeAllMonsAfterUserNervous::
	.string "Posa nerviosos\ntots els POKéMON\ndesprés\nde l'usuari.$"

gText_FourLine_WorsenConditionOfThoseMadeAppeals::
	.string "Empitjora la\ncondició dels\nque han\nactuat.$"

gText_FourLine_BadlyStartleMonsGoodCondition::
	.string "Pertorba molt\nPOKéMON en\nbona condició.$"

gText_FourLine_AppealGreatIfPerformedFirst::
	.string "L'actuació\nfunciona molt bé\nsi es fa\nla primera.$"

gText_FourLine_AppealGreatIfPerformedLast::
	.string "L'actuació\nfunciona molt bé\nsi es fa\nl'última.$"

gText_FourLine_AppealAsGoodAsThoseBeforeIt::
	.string "Fa l'actuació\ntan bona com\nles anteriors.$"

gText_FourLine_AppealAsGoodAsOneBeforeIt::
	.string "Fa l'actuació\ntan bona com\nl'anterior.$"

gText_FourLine_AppealBetterLaterItsPerformed::
	.string "L'actuació\nfunciona millor\ncom més tard\nes fa.$"

gText_FourLine_AppealVariesDependingOnTiming::
	.string "La qualitat\nde l'actuació\nvaria segons\nel moment.$"

gText_FourLine_WorksWellIfSameTypeAsBefore::
	.string "Funciona bé\nsi és del\nmateix tipus que\nl'anterior.$"

gText_FourLine_WorksWellIfDifferentTypeAsBefore::
	.string "Funciona bé\nsi és d'un\ntipus diferent\na l'anterior.$"

gText_FourLine_AffectedByAppealInFront::
	.string "Afectat per\ncom va\nl'actuació\ndel davant.$"

gText_FourLine_UpsConditionHelpsPreventNervousness::
	.string "Millora la\ncondició de\nl'usuari.\nPrevé el nerviosisme.$"

gText_FourLine_AppealWorksWellIfConditionGood::
	.string "L'actuació funciona\nbé si la\ncondició de l'usuari\nés bona.$"

gText_FourLine_NextAppealMadeEarlier::
	.string "La propera\nactuació es pot\nfer abans\nal proper torn.$"

gText_FourLine_NextAppealMadeLater::
	.string "La propera\nactuació es pot\nfer més tard\nal proper torn.$"

gText_FourLine_TurnOrderMoreEasilyScrambled::
	.string "Facilita que\nl'ordre del\nproper torn\nes barregi.$"

gText_FourLine_ScrambleOrderOfNextAppeals::
	.string "Barreja l'ordre\nde les\nactuacions al\nproper torn.$"

gText_FourLine_AppealExcitesAudienceInAnyContest::
	.string "Una actuació\nque emociona\nel públic en\nqualsevol CONCURS.$"

gText_FourLine_BadlyStartlesMonsGoodAppeals::
	.string "Pertorba molt\ntots els POKéMON\namb bones\nactuacions.$"

gText_FourLine_AppealBestMoreCrowdExcited::
	.string "L'actuació\nfunciona millor\ncom més emocionat\nés el públic.$"

gText_FourLine_TemporarilyStopCrowdExcited::
	.string "Atura\ntemporalment\nque el públic\ns'emocioni.$"

@ Unused move names

gText_RainDance::
	.string "Dansa Pluja$"

gText_Rage::
	.string "Fúria$"

gText_FocusEnergy::
	.string "Concentrar-se$"

gText_Hypnosis::
	.string "Hipnosi$"

gText_Softboiled::
	.string "Ou Bullit$"

gText_HornAttack::
	.string "Atac Banya$"

gText_SwordsDance::
	.string "Dansa Espases$"

gText_Conversion::
	.string "Conversió$"

gText_SunnyDay::
	.string "Dia Clar$"

gText_Rest2::
	.string "Descans$"

gText_Vicegrip::
	.string "Presa Forta$"

gText_DefenseCurl::
	.string "Enduriment$"

gText_LockOn::
	.string "Punt de Mira$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "Gràcia$"

gContestMoveTypeBeautyText::
	.string "Bellesa$"

gContestMoveTypeCuteText::
	.string "Tendresa$"

gContestMoveTypeSmartText::
	.string "Saviesa$"

gContestMoveTypeToughText::
	.string "Potència$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "Actuació núm. {STR_VAR_1}!\n"
	.string "Quin moviment es farà?$"

gText_AppealNumButItCantParticipate::
	.string "Actuació núm. {STR_VAR_1}!\n"
	.string "Però no pot participar!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} ha actuat amb\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} estava observant\n"
	.string "els altres.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "S'ha acabat el\n"
	.string "Temps d'Actuació!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "Però l'actuació va\n"
	.string "ser bloquejada.$"

gText_FollowedAnotherMonsLead::
	.string "Va seguir l'exemple\n"
	.string "d'un altre Pokémon.$"

gText_ButItMessedUp::
	.string "Però s'ha equivocat.$"

gText_WentBetterThanUsual::
	.string "Va anar millor\n"
	.string "que de costum.$"

gText_JudgeLookedAwayForSomeReason::
	.string "El Jutge ha mirat cap\n"
	.string "a un altre costat.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "Ha treballat per superar\n"
	.string "els errors passats.$"

gText_CantMakeAnyMoreMoves::
	.string "Ja no pot fer\n"
	.string "cap més moviment.$"

gText_WorkedFrighteninglyWell::
	.string "Ha funcionat\n"
	.string "esplèndidament.$"

gText_WorkedHardAsStandoutMon::
	.string "Ha treballat tan dur\n"
	.string "com el Pokémon destacat.$"

gText_JudgedLookedOnExpectantly::
	.string "El Jutge ho ha mirat\n"
	.string "amb expectació.$"

gText_WorkedRatherWell::
	.string "Ha funcionat força bé.$"

gText_WorkedLittleBetterThanUsual::
	.string "Ha funcionat una mica\n"
	.string "millor que de costum.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} no ha\n"
	.string "destacat gens…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} no ha\n"
	.string "destacat gaire…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} ha captat\n"
	.string "una mica d'atenció.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} ha atret\n"
	.string "molta atenció.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} ha acaparat\n"
	.string "tota l'atenció.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} no ha\n"
	.string "actuat.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Anticipació creixent per\n"
	.string "la propera actuació de {STR_VAR_1}.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "L'opinió del Jutge sobre\n"
	.string "{STR_VAR_1} s'ha mantingut.$"

gText_MonsXChangedPerceptions::
	.string "La {STR_VAR_3} de\n"
	.string "{STR_VAR_1} ha canviat percepcions.$"

gText_MonsAppealEffectWoreOff::
	.string "L'efecte de l'actuació\n"
	.string "de {STR_VAR_1} ha passat.$"

gText_SpecialAppealsEffectWoreOff::
	.string "L'efecte de l'actuació\n"
	.string "especial ha passat.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Totes les actuacions han\n"
	.string "quedat iguals.$"

gText_CheapenedMonsAppeal::
	.string "Ha devaluat\n"
	.string "l'actuació de {STR_VAR_2}.$"

gText_CheapenedAppealOfThoseAhead::
	.string "Ha devaluat l'actuació\n"
	.string "dels que anaven davant.$"

gText_StoleAttentionAwayFromMon::
	.string "Ha robat l'atenció\n"
	.string "de {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "Ha devaluat\n"
	.string "l'actuació de {STR_VAR_2}.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "Ha devaluat greument\n"
	.string "les altres actuacions.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Anticipació creixent per\n"
	.string "la propera actuació de {STR_VAR_1}.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "Ha devaluat l'actuació\n"
	.string "dels que anaven davant.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "Ha devaluat l'actuació\n"
	.string "preferida del Jutge.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "Les actuacions dels altres\n"
	.string "s'han devaluat a la meitat.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "Ha destacat per compensar\n"
	.string "haver estat bloquejat.$"

gText_CantParticipateInAppealsAnyMore::
	.string "Ja no pot participar\n"
	.string "en cap actuació.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "Ha commogut el Jutge\n"
	.string "amb una actuació fantàstica.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Ha crescut l'anticipació\n"
	.string "per les properes actuacions.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "Ha destacat tant com\n"
	.string "les actuacions especials.$"

gText_StoodOutAsMuchAsMon::
	.string "Ha destacat tant com\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Les actuacions bloquejades\n"
	.string "han quedat encara menys notables.$"

gText_EveryonesAppealsMadeSame::
	.string "Totes les actuacions han\n"
	.string "quedat iguals.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Ha pres més consciència\n"
	.string "dels altres Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} no pot actuar\n"
	.string "després d'això.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "S'ha calmat\n"
	.string "una mica.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Ha deixat de prestar\n"
	.string "atenció als altres Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "S'ha tornat menys conscient\n"
	.string "dels altres Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Ha deixat de preocupar-se\n"
	.string "dels altres Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Ha intentat pertorbar\n"
	.string "els altres Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Ha intentat impressionar\n"
	.string "els altres.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "El Jutge ha mirat\n"
	.string "cap a un altre costat de {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Ha intentat posar nerviós\n"
	.string "el proper Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} s'ha\n"
	.string "posat nerviós.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "L'actuació ha intentat\n"
	.string "posar nerviosos els que esperen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Ha provocat els Pokémon\n"
	.string "que anaven bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} ha recuperat\n"
	.string "la seva forma.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Ha intentat bloquejar\n"
	.string "els Pokémon que anaven bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "El destacat {STR_VAR_1}\n"
	.string "s'ha esforçat encara més.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "El poc notat\n"
	.string "{STR_VAR_1} s'ha esforçat molt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "S'ha esforçat tant com\n"
	.string "el Pokémon anterior.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "no ha anat bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "S'ha esforçat tant com\n"
	.string "el Pokémon precedent.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "no ha anat bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "no ha anat bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat una mica bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat força bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat excel·lentment.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha estat un fracàs.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "no ha funcionat gaire bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat una mica bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat força bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat molt bé.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "L'actuació de {STR_VAR_1}\n"
	.string "ha anat excel·lentment.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "És del mateix tipus que\n"
	.string "el Pokémon anterior, bé!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "No és del mateix tipus que\n"
	.string "l'anterior, bé!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Ha destacat molt més\n"
	.string "que el Pokémon anterior.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "No ho ha fet tan bé\n"
	.string "com el Pokémon anterior.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "La condició de {STR_VAR_1}\n"
	.string "ha pujat per sobre de l'habitual.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "L'estat ardent de {STR_VAR_1}\n"
	.string "ha fet una gran actuació!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Ha avançat en la cua\n"
	.string "per a la propera actuació.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Ha endarrerit una posició\n"
	.string "per a la propera actuació.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Ha barrejat\n"
	.string "l'ordre del proper torn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "El Jutge ha mirat\n"
	.string "{STR_VAR_1} amb expectació.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "La combinació d'actuació\n"
	.string "ha anat bé.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "La combinació d'actuació\n"
	.string "ha anat molt bé.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "La combinació d'actuació\n"
	.string "ha anat excel·lentment.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} ha aconseguit\n"
	.string "desviar la mirada.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} ha aconseguit\n"
	.string "evitar veure-ho.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} no es\n"
	.string "pertorba per això.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} s'ha\n"
	.string "distret una mica.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "Ha intentat pertorbar\n"
	.string "els altres Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} ha mirat avall\n"
	.string "per la distracció.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} s'ha girat\n"
	.string "per la distracció.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} no ha pogut\n"
	.string "evitar un crit.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} no ha pogut\n"
	.string "evitar saltar.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} ha ensopegat\n"
	.string "per la distracció.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} estava massa\n"
	.string "nerviós per moure's.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "Però s'ha equivocat.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Però no ha aconseguit\n"
	.string "posar l'objectiu nerviós.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Però no ha aconseguit\n"
	.string "posar ningú nerviós.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "Però ha estat ignorat…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "Però no ha pogut\n"
	.string "millorar la seva condició…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "La seva mala condició\n"
	.string "ha resultat en una actuació feble.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} no ha\n"
	.string "resultat afectat.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} ha decepcionat\n"
	.string "repetint una actuació.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "La {STR_VAR_3}\n"
	.string "de {STR_VAR_1} ha anat genial.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "La {STR_VAR_3}\n"
	.string "de {STR_VAR_1} no ha funcionat bé…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "La {STR_VAR_3}\n"
	.string "de {STR_VAR_1} ha animat el públic.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} no pot actuar\n"
	.string "el proper torn…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "Ha atret l'atenció\n"
	.string "del públic.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "El públic continua\n"
	.string "observant {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_2}\n"
	.string "de {STR_VAR_1} és ignorat.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "timidesa$"

gText_Contest_Anxiety::
	.string "ansietat$"

gText_Contest_Laziness::
	.string "mandra$"

gText_Contest_Hesitancy::
	.string "indecisió$"

gText_Contest_Fear::
	.string "por$"

gText_Contest_Coolness::
	.string "gràcia$"

gText_Contest_Beauty::
	.string "bellesa$"

gText_Contest_Cuteness::
	.string "tendresa$"

gText_Contest_Smartness::
	.string "saviesa$"

gText_Contest_Toughness::
	.string "potència$"

@ Unused
gText_Tension::
	.string "Tensió$"

gText_CoolMove::
	.string "Moviment de Gràcia$"

gText_BeautyMove::
	.string "Moviment de Bellesa$"

gText_CuteMove::
	.string "Moviment de Tendresa$"

gText_SmartMove::
	.string "Moviment de Saviesa$"

gText_ToughMove::
	.string "Moviment de Potència$"

gText_3QuestionMarks::
	.string "???$"
