EventTicket_Text_ShowOldSeaMap:
	.string "El vaixell cap a Slateport és…\p"


	.string "Com dius?\n"


	.string "Podem anar fins a aquest lloc del mapa?\p"


	.string "Conec algú que et pot ajudar millor.\n"


	.string "Espera, si us plau.$"



EventTicket_Text_ThatPass:
	.string "El vaixell cap a Slateport és…\p"


	.string "Oh?\n"


	.string "Aquell Passi…$"



EventTicket_Text_ShowEonTicket:
	.string "Ei, {MASC}company{FEM}companya{ENDG}, ets tu qui ha portat\n"


	.string "aquell Passi tan estrany?\p"


	.string "T'ho dic, intentes arribar a una\n"


	.string "petita illeta perduda molt al sud.\p"


	.string "No se sap què trobarem quan\n"


	.string "hi arribem, {MASC}company{FEM}companya{ENDG}.\l"


	.string "Això m'estremet!\p"


	.string "Tots a bord!$"



EventTicket_Text_SouthernIslandSailBack:
	.string "Ei, {MASC}company{FEM}companya{ENDG}, no hi ha res a\n"


	.string "veure ni a fer en aquesta illeta.\p"


	.string "Tornem a Lilycove, què et sembla?$"



EventTicket_Text_SailHome:
	.string "Molt bé, doncs!\n"


	.string "Tornem cap a casa!$"



EventTicket_Text_AsYouLike:
	.string "D'acord, com vulguis.$"



SouthernIsland_Interior_Text_Sign:
	.string "“Els somnis no són més que\n"


	.string "una altra realitat. No oblidis…”$"



SouthernIsland_Exterior_Text_Sign:
	.string "“Els qui veuen esvair-se els records\n"


	.string "busquen gravar-los al cor…”$"


