EventTicket_Text_OldSeaMapTooFar:
    .string "Què hi ha, jove?\p"


	.string "Què, ets tu qui se suposa que\n"


	.string "té un mapa vell i estripat?\p"


	.string "Deixa'm veure.\n"


	.string "… … … … … …\p"


	.string "Vaja, això queda molt lluny.\n"


	.string "Em temo que no et puc ajudar…$"



EventTicket_Text_BrineyHoldOnASecond:
    .string "Briney: Espera un moment!\p"


	.string "Què és això de rebutjar algú\n"


	.string "a qui dec tant?$"



EventTicket_Text_BrineyLetsSail:
    .string "{PLAYER}{KUN}, ho sento molt.\p"


	.string "Has vingut a demanar-me ajuda,\n"


	.string "i gairebé t'hem rebutjat.\p"


	.string "Deixa'm arreglar-ho.\p"


	.string "Partirem de seguida, és clar!\p"


	.string "Anem a trobar aquesta illa al\n"


	.string "Vell Mapa Marí!$"



EventTicket_Text_OddTicketGetOnBoard:
    .string "Ets tu qui ha portat aquell\n"


	.string "tiquet estrany?\p"


	.string "Allà on vols anar és una illa\n"


	.string "molt, molt llunyana.\p"


	.string "Ningú sap el que hi espera…\p"


	.string "Sols de pensar-ho em bull la sang\n"


	.string "com a mariner!\p"


	.string "Puja a bord, jove!$"



FarawayIsland_Entrance_Text_SailorReturn:
    .string "Quin viatge tan llarg!\p"


	.string "Feia molt de temps que no tenia\n"


	.string "l'oportunitat de navegar a un lloc nou.\n"


	.string "Ja has explorat l'illa?\p"


	.string "Vols tornar a l'Illa Cinabri?$"



BirthIsland_Harbor_Text_SailorReturn:
    .string "Quina illa amb una forma estranya!\n"


	.string "Vols tornar a Lilycove?$"



EventTicket_Text_OddTicketsWhereTo:
    .string "Ets tu qui ha portat\n"


	.string "aquells tiquets estranys?\p"


	.string "… … …Hmm.\p"


	.string "Aquests tiquets et portaran a illes\n"


	.string "molt, molt llunyanes.\p"


	.string "Ningú sap el que hi espera,\n"


	.string "ni el que pot passar-hi.\p"


	.string "Sols de pensar-ho em bull la sang\n"


	.string "com a mariner!\p"


	.string "Puja a bord, jove!\n"


	.string "Cap a on naveguem primer?$"



NavelRock_Harbor_Text_SailorReturn:
    .string "Ho… Ho has sentit?\n"


	.string "Aquell grunyit greu que ve de dins.\p"


	.string "Segur que no és perillós?\n"


	.string "Creus que hauríem de marxar?$"



FarawayIsland_Entrance_Text_Sign:
    .string "L'escriptura s'esvaeix com si\n"


	.string "hagués estat escrita fa molt…\p"


	.string "“…bre, dia 6\n"


	.string "Si algun humà…trepitja aquí…\l"


	.string "de nou…que sigui una bona perso…\l"


	.string "…mb aquesta esperança, me'n va…”$"



FarawayIsland_Interior_Text_Mew:
    .string "Myuu…$"


