EventTicket_Text_ShowOldSeaMap:
	.string "El vaixell cap a Slateport és…\p"
	.string "Perdona'm?\n"
	.string "Podem navegar fins a aquest lloc del mapa?\p"
	.string "Conec algú que et pot ajudar millor.\n"
	.string "Espera, si us plau.$"

EventTicket_Text_ThatPass:
	.string "El vaixell cap a Slateport és…\p"
	.string "Oh?\n"
	.string "Aquell Passi…$"

EventTicket_Text_ShowEonTicket:
	.string "Ei, company, ets tu qui ha portat\n"
	.string "aquell Passi tan estrany?\p"
	.string "T'ho dic, intentes arribar a una\n"
	.string "petita illeta lluny al sud.\p"
	.string "No se sap què trobarem quan\n"
	.string "hi arribem, company.\l"
	.string "Això m'estremet!\p"
	.string "Tots a bord!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Ei, company, no hi ha res per\n"
	.string "veure ni fer en aquesta illeta.\p"
	.string "Tornem a Lilycove, què et sembla?$"

EventTicket_Text_SailHome:
	.string "Molt bé, doncs!\n"
	.string "Tornem cap a casa!$"

EventTicket_Text_AsYouLike:
	.string "D'acord, com vulguis.$"

SouthernIsland_Interior_Text_Sign:
	.string ""Tots els somnis no són més que\n"
	.string "una altra realitat. No oblidis…"$"

SouthernIsland_Exterior_Text_Sign:
	.string ""Aquells els records dels quals s'esvaeixen\n"
	.string "busquen gravar-los al cor…"$"
