@ Battle Tower
gText_AnabelWonSilver::
	.string "És molt decebedor…$"

gText_AnabelDefeatSilver::
	.string "D'acord, ho entenc…$"

gText_AnabelWonGold::
	.string "Ho sento moltíssim…$"

gText_AnabelDefeatGold::
	.string "Gràcies…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Ahahaha! No t'avergonyeixes?\n"
	.string "Tothom ho mira!$"

gText_TuckerDefeatSilver::
	.string "Grr…\n"
	.string "Però, com…$"

gText_TuckerWonGold::
	.string "El meu títol d'As del Domo no és per a res!$"

gText_TuckerDefeatGold::
	.string "Ahahaha!\n"
	.string "Ets inspirador!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "Molt bé!\n"
	.string "Això ha estat una bona lliçó, oi?$"

gText_NolandDefeatSilver::
	.string "Bona feina!\n"
	.string "Saps el que fas!$"

gText_NolandWonGold::
	.string "Ei, ei, ei!\n"
	.string "Ja has acabat?$"

gText_NolandDefeatGold::
	.string "Però, com ha passat?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Humf…$"

gText_LucyDefeatSilver::
	.string "Urk…$"

gText_LucyWonGold::
	.string "Ha!$"

gText_LucyDefeatGold::
	.string "Maleïda!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Au va!\n"
	.string "Has d'esforçar-te més que això!$"

gText_GretaDefeatSilver::
	.string "No pot ser!\n"
	.string "Bona feina!$"

gText_GretaWonGold::
	.string "Heheh!\n"
	.string "Que esperaves?$"

gText_GretaDefeatGold::
	.string "Com?\n"
	.string "Va en serio?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Els teus Pokémon són febles\n"
	.string "perquè tu ets un Entrenador feble!$"

gText_SpenserDefeatSilver::
	.string "Ah…\n"
	.string "Això sí que és una altra cosa…$"

gText_SpenserWonGold::
	.string "Gwahahaha!\n"
	.string "Germans, no tenim res a témer!$"

gText_SpenserDefeatGold::
	.string "Gwah!\n"
	.string "Hahahaha!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Ei! Però, que et passa!\n"
	.string "Fes un esforç! Aixeca't!$"

gText_BrandonDefeatSilver::
	.string "Molt bé! Ho has fet genial!\n"
	.string "T'ho has guanyat!$"

gText_BrandonWonGold::
	.string "Ei! No et rendeixis ara!\n"
	.string "Aixeca't! No perdis la fe en tu!$"

gText_BrandonDefeatGold::
	.string "Molt bé! Ho has aconseguit!\n"
	.string "Has persistit fins al final!$"
