LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Benvingut al Racó de la Loteria Pokémon.\p"
	.string "Tots els compradors dels nostres grans\n"
	.string "magatzems podeu treure un Tiquet Loto.\p"
	.string "Si el número del Tiquet Loto coincideix\n"
	.string "amb el número d'ID d'algun dels teus\l"
	.string "Pokémon, rebràs un regal fabulós.\p"
	.string "Vols treure un Tiquet Loto\n"
	.string "Pokémon?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Torna demà, si us plau.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Torna aviat!$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Tria un Tiquet Loto.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "El número del Tiquet Loto és {STR_VAR_1}.\p"
	.string "He de comprovar si coincideix\n"
	.string "amb algun dels números d'ID dels\l"
	.string "teus Pokémon. Espera, si us plau.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Enhorabona!\p"
	.string "El número d'ID del teu {STR_VAR_1}\n"
	.string "de l'equip coincideix amb el\l"
	.string "número del teu Tiquet Loto!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Enhorabona!\p"
	.string "El número d'ID del teu {STR_VAR_1}\n"
	.string "de l'ordinador coincideix amb el\l"
	.string "número del teu Tiquet Loto!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Ho sento.\n"
	.string "Cap número no ha coincidit.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Han coincidit dos dígits, és el\n"
	.string "tercer premi!\l"
	.string "Has guanyat {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Han coincidit tres dígits, és el\n"
	.string "segon premi!\l"
	.string "Has guanyat {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Han coincidit quatre dígits, és el\n"
	.string "primer premi!\l"
	.string "Has guanyat {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Mare meva, han coincidit els cinc\n"
	.string "dígits!\p"
	.string "Has guanyat el premi gordo!\n"
	.string "Has guanyat {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Oh?\n"
	.string "Sembla que no tens espai per a això.\p"
	.string "Fes espai a la teva Motxilla i\n"
	.string "fes-m'ho saber.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Sí, t'esperava.\p"
	.string "Aquest és el premi que hem estat\n"
	.string "guardant per a tu.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Torna aviat!$"
