@UPDATED
MatchCall_Text_OakRegisterCall:
	.string "Oak: Oh, {PLAYER}{KUN}!\n"
	.string "Veig que tens un Mòbil!\p"
	.string "Deixa'm donar-te el meu número.\p"
	.string "Així podria examinar\n"
	.string "la teva Pokédex fins i tot\l"
	.string "mentre ets al camp.$"

MatchCall_Text_RegisteredOak:
	.string "El Prof. Oak ha registrat\n"
	.string "el seu número al teu Mòbil.$"

MatchCall_Text_RegisteredScott:
	.string "En Scott ha registrat\n"
	.string "el seu número al teu Mòbil.$"

MatchCall_Text_ScottBusy::
	.string "… bip … bip … bip …\p"
	.string "La línia d'en Scott sembla\n"
	.string "estar ocupada…$"

MatchCall_Text_ScottCerulean::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Has arribat a Cerulean City!\p"
	.string "Vas a desafiar la Misty?\n"
	.string "Millor que portis el banyador! Ha!\p"
	.string "Veurem si tenia raó\n"
	.string "sobre tu. Fins al gimnàs!$"

MatchCall_Text_ScottGotBadge2::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Felicitats per aconseguir\n"
	.string "la Medalla Cascada!\p"
	.string "Ja li estàs agafant el truc!$"

MatchCall_Text_ScottVermilion::
	.string "Scott: Ei! Campió en potència!\p"
	.string "He sentit que has arribat\n"
	.string "a Vermilion City!\p"
	.string "Vas a enfrontar-te al Tnt. Surge?\p"
	.string "Genial! Ho estaré mirant!$"

MatchCall_Text_ScottGotBadge3::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Quina batalla! Sabia que\n"
	.string "aconseguiries la Medalla Tro!\p"
	.string "Però ara tot serà més difícil!$"

MatchCall_Text_ScottCeladon::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Llavors has arribat a Celadon!\p"
	.string "Potser faré un descans del\n"
	.string "casino i veuré el teu combat!$"

MatchCall_Text_ScottGotBadge4::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Menys mal que no em vaig perdre\n"
	.string "aquell combat. Quin espectacle!\p"
	.string "T'estàs fent un nom,\n"
	.string "sens dubte!$"

MatchCall_Text_ScottSaffron::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Esperava veure't a Saffron,\n"
	.string "però hi havia soldats\l"
	.string "de l'Equip Rocket pertot!\p"
	.string "En sabies alguna cosa?$"

MatchCall_Text_ScottGotBadge5::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Si la Sabrina m'hagués\n"
	.string "llegit la ment, sabria que\l"
	.string "mai vaig dubtar de tu!\p"
	.string "Molt bé per la Medalla Pantà!$"

MatchCall_Text_ScottFuchsia::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Que dius? Ets a Fuchsia City\n"
	.string "també?\p"
	.string "Com?\n"
	.string "Sí! Sóc a la Zona Safari!\p"
	.string "Perdona, no t'he sentit!\p"
	.string "No et sento amb tots\n"
	.string "aquests Tauros salvatges...\p"
	.string "Sembla que estan a punt\n"
	.string "d'estampir!\p"
	.string "... ... ...\p"
	.string "He d'anar!$"

MatchCall_Text_ScottGotBadge6::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Ni amb els seus trucs\n"
	.string "el Koga tenia possibilitats!\p"
	.string "Quantes medalles portes ara?\p"
	.string "Estàs en una gran ratxa!$"

MatchCall_Text_ScottCinnabar::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Vas a Cinnabar Island\n"
	.string "per enfrontar-te al Blaine?\p"
	.string "Ens veiem allà!$"

MatchCall_Text_ScottGotBadge7::
	.string "Scott: Ei! Campió en potència!\p"
	.string "De debò que es notava\n"
	.string "la calor en aquell combat!\p"
	.string "Però no t'envaneixis!\n"
	.string "A per la propera medalla!$"

MatchCall_Text_ScottFinalBadge::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Doncs, només queda\n"
	.string "una medalla!\p"
	.string "Has sentit que el Líder\n"
	.string "del Gimnàs de Viridian\l"
	.string "ha tornat?\p"
	.string "Ningú sap gaire cosa d'ell,\n"
	.string "això promet ser interessant.$"

MatchCall_Text_ScottPkmnLeague::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Vaja! Les vuit medalles!\p"
	.string "Des que et vaig veure\n"
	.string "enfrontar-te al Brock,\l"
	.string "sabia que eres diferent.\p"
	.string "Però serà suficient per\n"
	.string "vèncer l'Elit Quatre?$"

MatchCall_Text_ScottThisIsIt::
	.string "Scott: Ei! Campió en potència!\p"
	.string "Que puc dir...\n"
	.string "Has arribat a l'Altiplà Índigo.\p"
	.string "Que comenci l'espectacle!$"

MatchCall_Text_ScottBattleTower::
	.string "{PLAYER}!\n"
	.string "Ho has aconseguit.\p"
	.string "Vine a veure'm a la Torre\n"
	.string "de Batalla.\n"
	.string "Tinc alguna cosa per tu…$"

MatchCall_Text_ScottBattleTower2::
	.string "{PLAYER}!\p"
	.string "Estàs gaudint de la Torre\n"
	.string "de Batalla?\p"
	.string "Genial! Segueix apuntant al cim!$"

MatchCall_Text_ScottGameClear::
	.string "Scott: Ei, campió en -!\p"
	.string "Espera, suposo que ara\n"
	.string "simplement és Campió!\p"
	.string "Però, et diré un petit\n"
	.string "secret.\p"
	.string "La teva aventura no acaba\n"
	.string "a la Lliga Pokémon!\p"
	.string "Hi ha un lloc fins i tot millor.\p"
	.string "Però, és tot el que diré\n"
	.string "de moment.\p"
	.string "Tens alguna cosa per\n"
	.string "esperar amb ganes.\p"
	.string "Et trucaré quan estigui llest.$"

MatchCall_Text_Mom1::
	.string "Mare: Oh? {PLAYER}!\p"
	.string "Quina alegria que m'hagis trucat!\p"
	.string "Significa que el teu Mòbil\n"
	.string "funciona correctament!\p"
	.string "Faràs molts amics en el\n"
	.string "viatge, registra'ls també!\p"
	.string "Bé! Bé!\n"
	.string "Sembla que estàs content!\p"
	.string "Hm…\n"
	.string "Com puc saber-ho?\p"
	.string "Perquè sóc la teva mare!\p"
	.string "Ho sé tot sobre tu!\p"
	.string "Hehehehe.\n"
	.string "Fins aviat, estimat!$"

MatchCall_Text_Mom2::
	.string "Mare: He sentit que un home\n"
	.string "molt intel·ligent viu\l"
	.string "prop de Cerulean City.\p"
	.string "Em pregunto quant guanya\n"
	.string "un Pokemaníac...\p"
	.string "Creus que guanya més\n"
	.string "que un entrenador?\p"
	.string "Potser hauries de demanar-li\n"
	.string "consell professional.$"

MatchCall_Text_Mom3::
	.string "Mare: El teu pare i tu…\n"
	.string "Tothom captivat pels Pokémon.\p"
	.string "Quin és l'encant dels Pokémon?\p"
	.string "Jo?\n"
	.string "M'encanten els Pokémon que\l"
	.string "m'ajuden amb les tasques\l"
	.string "del dia a dia.$"

MatchCall_Text_Mom4::
	.string "Mare: Lavender Town…\n"
	.string "Quin lloc tan trist…\p"
	.string "Quan penso en tots aquells\n"
	.string "Pokémon…\p"
	.string "…\p"
	.string "Ho sento, {PLAYER}.'\p"
	.string "No vull posar-te trist, tu també.$"

MatchCall_Text_Mom5::
	.string "Mare: {PLAYER}!\p"
	.string "Justament estava pensant en tu.\p"
	.string "M'agradaria poder ajudar-te\n"
	.string "més en la teva aventura.\p"
	.string "Potser podria guardar\n"
	.string "els teus diners per tu!\p"
	.string "Oh? Tens por que me'ls gastés\n"
	.string "als Grans Magatzems Celadon?\p"
	.string "Quina impertinència!$"

MatchCall_Text_Mom6::
	.string "Mare: Oh, has visitat Fuchsia?\p"
	.string "De jove m'encantava visitar\n"
	.string "la Zona Safari!\p"
	.string "M'encantava el Joc Safari,\n"
	.string "però mai guanyava.\p"
	.string "Sempre em perdia!$"

MatchCall_Text_Mom7::
	.string "Mare: Oh, {PLAYER}!\p"
	.string "Acabo de veure les notícies.\n"
	.string "L'Equip Rocket ha atacat Saffron!\p"
	.string "En quin món vivim.\n"
	.string "Para esment!$"

MatchCall_Text_Mom8::
	.string "Mare: Has visitat Cinnabar Island?\p"
	.string "De jove, els meus amics i jo\n"
	.string "hi anàvem nedant!\p"
	.string "Teníem massa por d'entrar a\n"
	.string "la Mansió Pokémon, però.\p"
	.string "Aquell lloc em posava\n"
	.string "la pell de gallina!$"

MatchCall_Text_Mom9::
	.string "Mare: Hola, {PLAYER}!\p"
	.string "Fa molt que ets per allà.\n"
	.string "Espero que t'ho estiguis\l"
	.string "passant bé!\p"
	.string "Però sempre pots tornar\n"
	.string "a casa si les coses es\l"
	.string "posen massa difícils!$"

MatchCall_Text_MomGameClear::
	.string "Mare: {PLAYER}…\n"
	.string "Sembla que va ser ahir que\n"
	.string "vas sortir de Pallet Town,\l"
	.string "i ara has recorregut Kanto!\p"
	.string "Qui hauria dit que tindries\n"
	.string "aquesta aventura amb els\l"
	.string "teus Pokémon!\p"
	.string "Estic tan orgullosa de tu!$"

MatchCall_Text_RegisteredRival:
	.string "La Daisy ha registrat el número\n"
	.string "d'en {RIVAL} al teu Mòbil.$"

MatchCall_Text_Rival1::
	.string "{RIVAL}: Que? Qui em truca?\p"
	.string "...\p"
	.string "{PLAYER}? Qui t'ha donat\n"
	.string "el meu número?\p"
	.string "Ugh, la meva germana és\n"
	.string "tan pesada.\p"
	.string "No em tornis a trucar!$"

MatchCall_Text_Rival2::
	.string "{RIVAL}: Oh, ets tu, {PLAYER}?\p"
	.string "No t'he sentit amb el soroll\n"
	.string "de totes les medalles\l"
	.string "que estic guanyant.\p"
	.string "Que? En tens una tu també?\p"
	.string "Quina sorpresa!$"

MatchCall_Text_Rival3::
	.string "{RIVAL}: Tornes a trucar-me?\p"
	.string "No pensis que et donaré\n"
	.string "cap consell, {PLAYER}.\p"
	.string "Jo vaig néixer amb\n"
	.string "aquest talent,\l"
	.string "no es pot ensenyar!$"

MatchCall_Text_Rival4::
	.string "{RIVAL}: Oh, {PLAYER}.\p"
	.string "He sentit un rumor que\n"
	.string "vas caure del SS Anne.\p"
	.string "Suposo que era massa bonic\n"
	.string "per ser veritat.$"

MatchCall_Text_Rival5::
	.string "{RIVAL}: Ei, {PLAYER}.\p"
	.string "Has arribat a Celadon?\p"
	.string "Hi ha un gran restaurant,\n"
	.string "però no deixen entrar\l"
	.string "als perdedors com tu! Ha!$"

MatchCall_Text_Rival6::
	.string "{RIVAL}: Ecs, {PLAYER}.\p"
	.string "Per què segueixes trucant-me?\p"
	.string "Estàs com obsessionat\n"
	.string "o alguna cosa.\p"
	.string "No siguis tan estrany!$"

MatchCall_Text_Rival7::
	.string "{RIVAL}: No puc parlar, {PLAYER}.\p"
	.string "M'estic enfrontant a uns\n"
	.string "Entrenadors Guais.'\p"
	.string "Sí, és dos contra un.\p"
	.string "Guanyo sempre en aquestes.$"

MatchCall_Text_Rival8::
	.string "{RIVAL}: Ei, {PLAYER}.\p"
	.string "Això s'està posant real, oi?\p"
	.string "Recordes quan jugàvem junts\n"
	.string "de petits?.\p"
	.string "Qui hauria dit que creixeria\l"
	.string "per ser el futur campió\l"
	.string "de Kanto!$"

MatchCall_Text_Rival9::
	.string "{RIVAL}: {PLAYER}.\p"
	.string "Ho faré.\p"
	.string "Seré el campió.\p"
	.string "Ningú podrà aturar-me.$"

MatchCall_Text_RivalGameClear::
	.string "{RIVAL}: Oh, ets tu, {PLAYER}.\p"
	.string "Truques per fregar-m'ho\n"
	.string "per la cara?\p"
	.string "Escolta, el que va passar\n"
	.string "a la Lliga va ser\l"
	.string "una casualitat total!\p"
	.string "La propera vegada et guanyaré!$"

MatchCall_Text_AideIntro::
	.string "Cedar: ……………\n"
	.string "Hola? Ah, {PLAYER}!\p"
	.string "Sóc en Cedar! Sóc un dels\n"
	.string "ajudants del professor!\p"
	.string "Ens vam conèixer a Pallet Town,\n"
	.string "ho recordes?\p"
	.string "Sí, sí! Molt bé!\p"
	.string "El professor em va donar\n"
	.string "el teu número. Espero que\l"
	.string "no et sembli malament.\p"
	.string "M'ha demanat que t'ajudi\n"
	.string "en el teu viatge, així que\l"
	.string "et tornaré a trucar. Adéu!$"

MatchCall_Text_AideIntro2::
	.string "Cedar: ……………\n"
	.string "Hola? Ah, {PLAYER}!\p"
	.string "Sóc en Cedar! Sóc un dels\n"
	.string "ajudants del professor!\p"
	.string "Et vaig veure al Lab d'en Oak,\n"
	.string "però no vam tenir ocasió\l"
	.string "de parlar.\p"
	.string "El professor em va donar\n"
	.string "el teu número. Espero que\l"
	.string "no et sembli malament.\p"
	.string "M'ha demanat que t'ajudi\n"
	.string "en el teu viatge, així que\l"
	.string "et tornaré a trucar. Adéu!$"

MatchCall_Text_RegisteredOaksAide:
	.string "L'ajudant del Prof. Oak ha\n"
	.string "registrat el seu número\l"
	.string "al teu Mòbil.$"

MatchCall_Text_AideWatchingProgress::
	.string "Cedar: Ah, hola {PLAYER}!\p"
	.string "Com va el teu viatge?\p"
	.string "Molt bé!\p"
	.string "Seguiré el teu progrés!$"

MatchCall_EventScript_AideFlashReady::
	lockall
	pokenavcall MatchCall_Text_AideFlashReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE2
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideFlashReady::
	.string "Cedar: Ah, hola {PLAYER}!\p"
	.string "Felicitats per guanyar\n"
	.string "una altra Medalla!\p"
	.string "El Prof. Oak vol\n"
	.string "donar-te una recompensa.\p"
	.string "Si em trobes a la Ruta 2,\n"
	.string "te la lliuraré!$"

MatchCall_Text_AideOnMyWayRoute2::
	.string "Cedar: Hola, {PLAYER}!\p"
	.string "Estic dirigint-me cap a\n"
	.string "la Ruta 2 ara mateix!\p"
	.string "Crec que he girat malament\n"
	.string "en algun lloc, però.\p"
	.string "He acabat a l'Edifici Est.\p"
	.string "Potser et costarà una\n"
	.string "mica més arribar fins a mi,\l"
	.string "però t'esperaré!$"

MatchCall_EventScript_AideEverstoneReady::
	lockall
	pokenavcall MatchCall_Text_AideEverstoneReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE10
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideEverstoneReady::
	.string "Cedar: Ah, hola {PLAYER}!\p"
	.string "Felicitats per guanyar\n"
	.string "una altra Medalla!\p"
	.string "El Prof. Oak vol\n"
	.string "donar-te una recompensa.\p"
	.string "Si em trobes a la Ruta 10,\n"
	.string "te la lliuraré!$"

MatchCall_Text_AideOnMyWayRoute10::
	.string "Cedar: Hola, {PLAYER}!\p"
	.string "Estic dirigint-me cap a\n"
	.string "la Ruta 10 ara mateix!\p"
	.string "He acabat lluitant contra\n"
	.string "alguns Entrenadors, i el\l"
	.string "meu Pokémon necessita\l"
	.string "descansar.\p"
	.string "Vine al Centre Pokémon!$"

MatchCall_EventScript_AideItemfinderReady::
	lockall
	pokenavcall MatchCall_Text_AideItemfinderReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE11
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideItemfinderReady::
	.string "Cedar: Ah, hola {PLAYER}!\p"
	.string "Felicitats per guanyar\n"
	.string "una altra Medalla!\p"
	.string "El Prof. Oak vol\n"
	.string "donar-te una recompensa.\p"
	.string "Si em trobes a la Ruta 11,\n"
	.string "te la lliuraré!$"

MatchCall_Text_AideOnMyWayRoute11::
	.string "Cedar: Hola, {PLAYER}!\p"
	.string "Estic dirigint-me cap a\n"
	.string "la Ruta 11 ara mateix!\p"
	.string "Volia tenir una bona vista\n"
	.string "de l'oceà, així que\l"
	.string "buscaré un bon lloc.$"

MatchCall_EventScript_AideAmuletCoinReady::
	lockall
	pokenavcall MatchCall_Text_AideAmuletCoinReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE16
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideAmuletCoinReady::
	.string "Cedar: Ah, hola {PLAYER}!\p"
	.string "Felicitats per guanyar\n"
	.string "una altra Medalla!\p"
	.string "El Prof. Oak vol\n"
	.string "donar-te una recompensa.\p"
	.string "Si em trobes a la Ruta 16,\n"
	.string "te la lliuraré!$"

MatchCall_Text_AideOnMyWayRoute16::
	.string "Cedar: Hola, {PLAYER}!\p"
	.string "Estic dirigint-me cap a\n"
	.string "la Ruta 16 ara mateix!\p"
	.string "Hi havia uns nois molt\n"
	.string "intimidants a la Carretera\l"
	.string "Ciclista, així que em\l"
	.string "quedo a la Caseta!$"

MatchCall_EventScript_AideExpShareReady::
	lockall
	pokenavcall MatchCall_Text_AideExpShareReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_HIDE_AIDE_ROUTE15
	clearflag FLAG_QUEUE_AIDE_CALL
	releaseall
	end

MatchCall_Text_AideExpShareReady::
	.string "Cedar: Ah, hola {PLAYER}!\p"
	.string "Felicitats per guanyar\n"
	.string "una altra Medalla!\p"
	.string "El Prof. Oak vol\n"
	.string "donar-te una recompensa.\p"
	.string "Si em trobes a la Ruta 15,\n"
	.string "te la lliuraré!$"

MatchCall_Text_AideOnMyWayRoute15::
	.string "Cedar: Hola, {PLAYER}!\p"
	.string "Estic dirigint-me cap a\n"
	.string "la Ruta 15 ara mateix!\p"
	.string "Has visitat la Zona Safari?\p"
	.string "Vaig intentar atrapar\n"
	.string "un Pokémon molt rar,\l"
	.string "però va fugir!$"

MatchCall_Text_AideGameClear::
	.string "Cedar: Ah, hola {PLAYER}!\p"
	.string "Felicitats per convertir-te\n"
	.string "en campió!\p"
	.string "Espero que les meves\n"
	.string "recompenses t'hagin estat\l"
	.string "útils!$"

MatchCall_Text_RegisteredLooker:
	.string "En Looker ha registrat el seu\n"
	.string "número al teu Mòbil.$"

MatchCall_Text_LookerIntro::
	.string "Looker: L'Equip Rocket…\p"
	.string "No els importa a qui\n"
	.string "fan mal, mentre\l"
	.string "els doni diners!\p"
	.string "Persones…\n"
	.string "Pokémon…\l"
	.string "Hem de protegir-los!\p"
	.string "Per això vaig jurar aturar\n"
	.string "l'Equip Rocket.$"

MatchCall_Text_LookerCeladon::
	.string "Looker: Hola, {PLAYER}!\p"
	.string "Amb la seva operació\n"
	.string "de reclutament a Cerulean\l"
	.string "tancada, hem de trobar\l"
	.string "on s'amaga l'Equip Rocket.\p"
	.string "El meu instint diu\n"
	.string "que és una ciutat propera,\l"
	.string "però podria ser qualsevol.\p"
	.string "Para esment a qualsevol\n"
	.string "cosa sospitosa!$"

MatchCall_Text_LookerRocketHideout::
	.string "Looker: Oh, ets tu, {PLAYER}.\n"
	.string "Gràcies per l'avís sobre\l"
	.string "l'amagatall de l'Equip\l"
	.string "Rocket a Celadon.\p"
	.string "Això segur que alentirà\n"
	.string "la seva operació una estona!$"

MatchCall_Text_LookerSaffron::
	.string "Looker: Ho sento {PLAYER}, però\n"
	.string "no tinc temps de parlar ara!\p"
	.string "Hem interceptat alguns plans\n"
	.string "de l'Equip Rocket, i sembla\l"
	.string "que el seu proper moviment\l"
	.string "serà a Saffron City!\p"
	.string "...que!?\p"
	.string "Que ja hi són?\n"
	.string "Hem tornat a arribar tard!\p"
	.string "Para esment, {PLAYER}!$"

MatchCall_Text_LookerSilphCo::
	.string "Looker: {PLAYER}, gràcies.\p"
	.string "No hem agafat el seu líder,\n"
	.string "però almenys hem salvat\l"
	.string "Saffron City.\p"
	.string "Aviat trobarem qui dóna\n"
	.string "les ordres.\p"
	.string "Els dies de l'Equip Rocket\n"
	.string "estan comptats!$"

MatchCall_Text_LookerGiovanni::
	.string "Looker: El Giovanni potser\n"
	.string "ha escapat, però\l"
	.string "això hauria de ser el final\l"
	.string "de l'Equip Rocket.\p"
	.string "El meu equip et deu una!$"

MatchCall_EventScript_LookerPostgameReady::
	lockall
	pokenavcall MatchCall_Text_LookerPostgameReady
	waitmessage
	delay 30
	closemessage
	clearflag FLAG_QUEUE_LOOKER_POSTGAME_CALL
	setflag FLAG_LOOKER_POSTGAME_STARTED
	clearflag FLAG_HIDE_SILPH_POSTGAME_ROCKET
	releaseall
	end

MatchCall_Text_LookerPostgameReady::
	.string "Looker: {PLAYER}!\p"
	.string "És una emergència!\p"
	.string "L'Equip Rocket ha tornat\n"
	.string "a Saffron City!\p"
	.string "Han pres el President de\n"
	.string "la Silph Co. com a ostatge\l"
	.string "un altre cop...\p"
	.string "...i hi ha alguna cosa més...\p"
	.string "T'ho diré quan vagis aquí.\p"
	.string "Vine a veure'm a Saffron\n"
	.string "de seguida.$"

MatchCall_Text_LookerPostgameWaiting::
	.string "Looker: {PLAYER}!\p"
	.string "Vine ràpid a Saffron City!$"

MatchCall_Text_LookerPostgameCompleted::
	.string "Looker: L'Equip Rocket!\p"
	.string "Ho intentaran tot\n"
	.string "per aconseguir el que volen.\p"
	.string "Per això hem d'estar\n"
	.string "sempre vigilants!\p"
	.string "M'alegra que Kanto tingui\n"
	.string "entrenadors com tu\l"
	.string "ajudant, {PLAYER}.$"

MatchCall_Text_RegisteredBill:
	.string "En Bill ha registrat el seu\n"
	.string "número al teu Mòbil.$"

MatchCall_Text_Bill1::
	.string "Bill: Gràcies per\n"
	.string "ajudar-me allà!\p"
	.string "Convertir-me en Pokémon...\p"
	.string "Amic, quina passada!\p"
	.string "Però m'està donant\n"
	.string "noves idees per\l"
	.string "les meves invencions!\p"
	.string "He d'anar!$"

MatchCall_Text_Bill2::
	.string "Bill: Oh ei, {PLAYER}!\p"
	.string "Has acabat fent servir\n"
	.string "el Tiquet SS?\p"
	.string "Ah sí? Com va ser?\p"
	.string "Ha! Mentre tu navegaves,\n"
	.string "jo tenia unes quantes\l"
	.string "idees noves!\p"
	.string "Passa pel lab la propera\n"
	.string "vegada que siguis a\l"
	.string "Cerulean i te les ensenyaré!$"

MatchCall_Text_Bill3::
	.string "Bill: Ei, {PLAYER}!\p"
	.string "Com funciona l'app DexNav?\p"
	.string "Segur que t'ajuda a omplir\n"
	.string "la PokéDex força ràpid!$"

MatchCall_Text_Bill4::
	.string "Bill: Ei, {PLAYER}!\p"
	.string "Vaja! El líder de l'Equip\n"
	.string "Rocket era el líder del\l"
	.string "Gimnàs de Viridian, també?\p"
	.string "La xarxa estava plena de\n"
	.string "teories, però no crec\l"
	.string "que ningú ho hagués endevinat!\p"
	.string "Qui diria que s'amagava\n"
	.string "a la vista de tothom!\p"
	.string "...\p"
	.string "Això m'ha donat una idea!\p"
	.string "Per què no tornes a la\n"
	.string "Casa del Mar?\p"
	.string "Estaré llest quan hi siguis!$"

MatchCall_Text_Bill5::
	.string "Bill: Ei, {PLAYER}!\p"
	.string "Com funciona l'app DexNav?\p"
	.string "Amb el Mode Detector,\n"
	.string "trobar Pokémon rars\l"
	.string "serà molt fàcil!$"

MatchCall_Text_Bill6::
	.string "Bill: Vaja, {PLAYER}!\p"
	.string "Les imatges de les teves\n"
	.string "batalles estan per tota la xarxa!\p"
	.string "La gent no se'n cansa de tu!\p"
	.string "Espero que les meves\n"
	.string "invencions t'hagin estat\l"
	.string "útils en el teu viatge.\p"
	.string "Jo?\p"
	.string "Em quedaré al lab de moment.\n"
	.string "Potser se m'ocorrerà alguna\l"
	.string "cosa nova!\p"
	.string "Vine a visitar-nos alguna vegada!$"

@Match Call Trainers
MatchCall_WildBattleText1::
	.string "Ei, {PLAYER}!\n"
	.string "Sóc jo, {STR_VAR_1}.\p"
	.string "Acabo d'intentar atrapar\n"
	.string "aquest {STR_VAR_2},\l"
	.string "però ha fugit.\p"
	.string "Estava a punt d'agafar-lo!\p"
	.string "M'ha espatlat el dia…\n"
	.string "En fi, fins aviat!$"

MatchCall_NegativeBattleText1::
	.string "Hola! {PLAYER}{KUN}, hola!\n"
	.string "Sóc {STR_VAR_1}.\p"
	.string "Vaig intentar lluitar\n"
	.string "contra un altre entrenador,\l"
	.string "però vaig perdre.\p"
	.string "Va ser molt decepcionant.\n"
	.string "Fins aviat!$"

MatchCall_PositiveBattleText1::
	.string "Hola! {PLAYER}{KUN}, hola!\n"
	.string "Sóc {STR_VAR_1}!\p"
	.string "Vaig lluitar contra\n"
	.string "un entrenador. Vaig guanyar!\l"
	.string "Vaig guanyar!\p"
	.string "El meu {STR_VAR_2} ha\n"
	.string "treballat molt per mi.\l"
	.string "Estic molt content!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Hola, {PLAYER}!\n"
	.string "Sóc {STR_VAR_1}.\p"
	.string "Oh? Resulta que ets\n"
	.string "a {STR_VAR_2} ara?\p"
	.string "Vols lluitar ara?\n"
	.string "T'esperaré! Fins aviat!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Hola! {PLAYER}, hola!\n"
	.string "Sóc {STR_VAR_1}.\p"
	.string "Vols lluitar amb mi?\p"
	.string "T'esperaré per\n"
	.string "{STR_VAR_2}!$"

MatchCall_BattleFrontierStreakText1::
	.string "Hola! Sóc {STR_VAR_1}.\n"
	.string "He sentit les novetats!\p"
	.string "Diuen que ho has fet\n"
	.string "genial a {STR_VAR_2}.\p"
	.string "Increïble, {STR_VAR_3} victòries\n"
	.string "seguides? Fins aviat!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hola! Sóc {STR_VAR_1}.\n"
	.string "He sentit les novetats!\p"
	.string "Diuen que ho has fet\n"
	.string "genial a {STR_VAR_2}.\p"
	.string "Increïble--{STR_VAR_3} victòries\n"
	.string "seguides? Fins aviat!$"


@MC Group 2
MatchCall_WildBattleText2::
	.string "…Eh, {PLAYER}{KUN}?\n"
	.string "Sóc jo, {STR_VAR_1}.\p"
	.string "Oh, espera! Espera!\n"
	.string "Puc atrapar aquest {STR_VAR_2}…\p"
	.string "Aarrrgh! Ha fugit!\n"
	.string "Estava ben a punt!$"

MatchCall_NegativeBattleText2::
	.string "Ei, {PLAYER}!\n"
	.string "Sóc jo, {STR_VAR_1}.\p"
	.string "Acabo de perdre en\n"
	.string "una batalla.\p"
	.string "Suposo que haig d'entrenar\n"
	.string "més l'equip!$"

MatchCall_PositiveBattleText2::
	.string "Oh, hola, {PLAYER}{KUN}.\n"
	.string "Sóc {STR_VAR_1}.\p"
	.string "Recentment vaig lluitar\n"
	.string "i el meu {STR_VAR_2}\l"
	.string "va ser excepcional!\p"
	.string "M'hauria agradat\n"
	.string "que ho haguessis vist,\l"
	.string "{PLAYER}{KUN}. Adéu!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} al telèfon.\p"
	.string "On ets ara?\n"
	.string "Eh? {STR_VAR_2}?\p"
	.string "Vols lluitar ara?\n"
	.string "T'esperaré. Fins aviat!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Oh, {PLAYER}{KUN}, hola!\n"
	.string "Sóc {STR_VAR_1}!\l"
	.string "Com estan els teus Pokémon?\p"
	.string "Els meus Pokémon milloren.\n"
	.string "T'ho voldria mostrar,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Ara sóc a {STR_VAR_2},\n"
	.string "lluitems si ets a prop.\p"
	.string "Espero veure't aviat!$"

MatchCall_BattleFrontierStreakText2::
	.string "Hola, sóc {STR_VAR_1}!\n"
	.string "He sentit parlar de tu!\p"
	.string "Diuen que vas guanyar\n"
	.string "{STR_VAR_3} batalles seguides\l"
	.string "a {STR_VAR_2}.\p"
	.string "Increïble! Hauré d'esforçar-me\n"
	.string "més, jo també! Fins aviat!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Hola, sóc {STR_VAR_1}!\n"
	.string "He sentit parlar de tu!\p"
	.string "Diuen que vas guanyar\n"
	.string "{STR_VAR_3} batalles seguides\l"
	.string "a {STR_VAR_2}.\p"
	.string "Increïble! Hauré d'esforçar-me\n"
	.string "més, jo també! Fins aviat!$"

@MC Group 3
MatchCall_WildBattleText3::
	.string "Oh, {PLAYER}{KUN}, com estàs?\n"
	.string "Sóc {STR_VAR_1}.\p"
	.string "Has tingut èxit atrapant\n"
	.string "Pokémon últimament?\p"
	.string "Jo estava molt a prop fa\n"
	.string "una estona, però el meu\l"
	.string "objectiu va escapar.\p"
	.string "Haig d'esforçar-me més!\n"
	.string "Fins aviat!$"

MatchCall_NegativeBattleText3::
	.string "Hola, {PLAYER}!\n"
	.string "Sóc {STR_VAR_1}.\p"
	.string "Com et van les coses?\p"
	.string "He seguit lluitant,\n"
	.string "però no guanyo gaire sovint.\p"
	.string "No m'acabo de centrar.\n"
	.string "Bé, cuida't!$"

MatchCall_PositiveBattleText3::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sóc {STR_VAR_1}.\p"
	.string "Has lluitat últimament?\n"
	.string "Avui acabo de guanyar!\p"
	.string "Estic en ratxa! Gahahaha!\n"
	.string "En fi, fins aviat!$"

MatchCall_SameRouteBattleRequestText3::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} al telèfon…\p"
	.string "Oh, resulta que ets\n"
	.string "a {STR_VAR_2}?\p"
	.string "Doncs, lluitem.\n"
	.string "Ara mateix, vull dir.\p"
	.string "Et mostraré els meus Pokémon.\n"
	.string "T'esperaré.$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Ah, hola, {PLAYER}{KUN}!\n"
	.string "Sóc {STR_VAR_1}!\l"
	.string "Estan bé els teus Pokémon?\p"
	.string "Els meus Pokémon estan tan\n"
	.string "sans que no semblen capaços\l"
	.string "de perdre!\p"
	.string "M'encantaria tornar a\n"
	.string "lluitar amb tu.\p"
	.string "Si ets a prop de {STR_VAR_2},\n"
	.string "vine a veure'ns.$"

MatchCall_BattleFrontierStreakText3::
	.string "Ei, {PLAYER}!\n"
	.string "Sóc jo, {STR_VAR_1}.\p"
	.string "He sentit que has arrassat\n"
	.string "a {STR_VAR_2}!\p"
	.string "Una ratxa de {STR_VAR_3}...\n"
	.string "Això és un gran rècord, oi?\p"
	.string "Hauré d'espabilar jo també!\n"
	.string "Fins aviat!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Ei, {PLAYER}!\n"
	.string "Sóc jo, {STR_VAR_1}.\p"
	.string "He sentit que has arrassat\n"
	.string "a {STR_VAR_2}!\p"
	.string "Una ratxa de {STR_VAR_3}...\n"
	.string "Això és un gran rècord, oi?\p"
	.string "Hauré d'espabilar jo també!\n"
	.string "Fins aviat!$"

@MC Group 4
MatchCall_WildBattleText4::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Sóc jo, {STR_VAR_1}.\l"
	.string "Segueixes atrapant Pokémon?\p"
	.string "Jo he intentat atrapar-ne,\n"
	.string "però no és tan fàcil.\p"
	.string "El món dels Pokémon és profund!$"

MatchCall_NegativeBattleText4::
	.string "Ei, {PLAYER}.\n"
	.string "{STR_VAR_1} al telèfon.\p"
	.string "Com et van les coses?\p"
	.string "He lluitat molt,\n"
	.string "però amb poc èxit.\p"
	.string "No agafo el ritme.\n"
	.string "Cuida't.$"

MatchCall_PositiveBattleText4::
	.string "Ei, {PLAYER}!\n"
	.string "Sóc jo, {STR_VAR_1}!\l"
	.string "Com van les teves batalles?\p"
	.string "Jo, l'altre dia vaig lluitar\n"
	.string "i el meu {STR_VAR_2}\l"
	.string "va ser increïble!\p"
	.string "La propera vegada que\n"
	.string "lluitems, {PLAYER},\l"
	.string "no seré jo el que perdi!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} al telèfon.\l"
	.string "Com estan els teus Pokémon?\p"
	.string "Oh, de debò? Ets a\n"
	.string "{STR_VAR_2}?\p"
	.string "Doncs, millor que revanxem.\p"
	.string "Puc esperar, és clar.\n"
	.string "Fins aviat!$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Ei, {PLAYER}!\n"
	.string "Sóc jo, {STR_VAR_1}.\p"
	.string "Els meus Pokémon han\n"
	.string "crescut molt des de l'última\l"
	.string "vegada.\p"
	.string "Vull veure fins a quin\n"
	.string "punt han millorat amb\l"
	.string "els teus, {PLAYER}.\p"
	.string "Doncs, lluitem!\p"
	.string "T'esperaré a la zona de\n"
	.string "{STR_VAR_2}.$"

MatchCall_BattleFrontierStreakText4::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} al telèfon. Que hi ha?\p"
	.string "Corre el rumor que\n"
	.string "has encadenat {STR_VAR_3} victòries\l"
	.string "seguides a {STR_VAR_2}.\p"
	.string "Hauré d'esforçar-me\n"
	.string "jo també. Fins aviat!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} al telèfon. Que hi ha?\p"
	.string "Corre el rumor que\n"
	.string "has encadenat {STR_VAR_3} victòries\l"
	.string "seguides a {STR_VAR_2}.\p"
	.string "Hauré d'esforçar-me\n"
	.string "jo també. Fins aviat!$"

@MC Group 5
MatchCall_WildBattleText5::
	.string "Ei, {PLAYER}!\n"
	.string "Sóc {STR_VAR_1}!\p"
	.string "He estat pensant en intentar\n"
	.string "atrapar alguns Pokémon.\p"
	.string "Però no en trobo cap.\n"
	.string "És tot un misteri per mi!\p"
	.string "Estic al límit!\n"
	.string "Fins aviat!$"

MatchCall_NegativeBattleText5::
	.string "{STR_VAR_1} al telèfon.\n"
	.string "Com et va últimament?\p"
	.string "Ahir vaig perdre\n"
	.string "una batalla,\l"
	.string "i no puc treure-me-la\l"
	.string "del cap.\p"
	.string "He d'elaborar un pla…\n"
	.string "Fins aviat.$"

MatchCall_PositiveBattleText5::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} al telèfon.\p"
	.string "Com et van les coses?\p"
	.string "Estic en una gran ratxa.\n"
	.string "Acabo de guanyar una batalla.\p"
	.string "Quan lluitems la propera\n"
	.string "vegada, no perdré!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Oh, {PLAYER}{KUN}, hola!\n"
	.string "Sóc {STR_VAR_1}!\p"
	.string "Com et mantens?\n"
	.string "Oh, ets a {STR_VAR_2}?\p"
	.string "Oh, doncs no creus\n"
	.string "que hauríem de lluitar?\p"
	.string "No m'esperis massa!$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Ei, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} al telèfon.\l"
	.string "Com et van les coses?\p"
	.string "Els meus Pokémon s'han\n"
	.string "tornat força forts últimament.\p"
	.string "Ei, t'agradaria tornar\n"
	.string "a lluitar amb mi?\p"
	.string "Ens trobem a la zona de\n"
	.string "{STR_VAR_2}, d'acord?$"

MatchCall_BattleFrontierStreakText5::
	.string "Hola, {PLAYER}{KUN}!\n"
	.string "Sóc {STR_VAR_1}.\p"
	.string "Eres a {STR_VAR_2}\n"
	.string "i vas guanyar {STR_VAR_3}\l"
	.string "batalles seguides?\l"
	.string "Vaja, que fort!\p"
	.string "Hauré de treballar\n"
	.string "més els meus Pokémon.\l"
	.string "Fins aviat!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Hola, {PLAYER}{KUN}!\n"
	.string "Sóc {STR_VAR_1}.\p"
	.string "Eres a {STR_VAR_2}\n"
	.string "i vas guanyar {STR_VAR_3}\l"
	.string "batalles seguides?\l"
	.string "Vaja, que fort!\p"
	.string "Jo? Diria que vaig avançant.\n"
	.string "Fins aviat!$"

@MC Personalized Text
MatchCall_PersonalizedText1::
	.string "Nyy… Sóc… {STR_VAR_1}…\n"
	.string "…Snif…\p"
	.string "Avui la mestra m'ha renyat\n"
	.string "a classe.\p"
	.string "Però no la tinc cap mania.\p"
	.string "Em diu exactament\n"
	.string "el que faig malament\l"
	.string "perquè pugui aprendre.\p"
	.string "Segur que aniré a\n"
	.string "l'Escola d'Entrenadors\l"
	.string "demà!\p"
	.string "Fins aviat!$"

MatchCall_PersonalizedText2::
	.string "Sóc {STR_VAR_1}!\p"
	.string "Estic una mica ocupat,\n"
	.string "però t'he de dir que avui\l"
	.string "he guanyat cinc entrenadors\l"
	.string "una altra vegada.\p"
	.string "Si segueixo aquest ritme,\n"
	.string "probablement et guanyaré.\p"
	.string "Crec que serem bons rivals,\n"
	.string "tu i jo. Fins aviat!$"

MatchCall_PersonalizedText3::
	.string "Sóc {STR_VAR_1}, l'expert\n"
	.string "en acampada!\p"
	.string "Quan vam lluitar,\n"
	.string "no podia evitar perdre.\p"
	.string "Al cap i a la fi, la meva\n"
	.string "especialitat és l'acampada.\p"
	.string "Però guanyi o perdi,\n"
	.string "m'agrada lluitar acampat.\p"
	.string "Torna a lluitar amb mi.\n"
	.string "I anem a acampar també!$"

MatchCall_PersonalizedText4::
	.string "Sóc el {STR_VAR_1},\n"
	.string "amant de les muntanyes!\p"
	.string "Des que ens vam conèixer,\n"
	.string "has après a estimar\l"
	.string "les muntanyes?\p"
	.string "Gairebé no et veig\n"
	.string "per les muntanyes…\p"
	.string "La propera vegada, ens\n"
	.string "trobarem per {STR_VAR_2}.$"

MatchCall_PersonalizedText5::
	.string "Sóc jo, {STR_VAR_1}.\p"
	.string "Sóc popular per tenir\n"
	.string "molts Pokémon Insecte, oi?\p"
	.string "Avui he portat uns quants\n"
	.string "dels meus favorits a escola.\p"
	.string "Una noia que m'agrada\n"
	.string "ha plorat!\l"
	.string "Riu si vols.\p"
	.string "Haig d'ensenyar-li\n"
	.string "l'encant dels Insectes.\p"
	.string "Nyy…\n"
	.string "Fins aviat!$"

MatchCall_PersonalizedText6::
	.string "Sóc {STR_VAR_1}!\n"
	.string "Sóc {STR_VAR_1}!\p"
	.string "{STR_VAR_2} és una via\n"
	.string "molt transitada, i m'estan\l"
	.string "desafiant entrenadors de\l"
	.string "tota mena cada dia.\p"
	.string "Avui he guanyat cinc\n"
	.string "batalles i en he perdut\l"
	.string "només tres!\p"
	.string "Com t'ha anat avui?\n"
	.string "Explica-m'ho la propera!$"

MatchCall_PersonalizedText7::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Sóc {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Per avui és tot…$"

MatchCall_PersonalizedText8::
	.string "Ahoi!\n"
	.string "Sóc {STR_VAR_1}!\p"
	.string "Com sempre, pescant\n"
	.string "amb tota l'ànima!\p"
	.string "Hi ha altres llocs on pescar\n"
	.string "a part del mar i els rius?\p"
	.string "Tinc ganes irresistibles\n"
	.string "de pescar a qualsevol lloc!\p"
	.string "Oh, ostres!\n"
	.string "S'ha enredat el fil!\p"
	.string "He d'anar!\n"
	.string "Troba'm nous llocs de pesca!$"

MatchCall_PersonalizedText9::
	.string "Sóc jo, {STR_VAR_1}.\n"
	.string "Com van els teus viatges?\p"
	.string "…Vaja, de debò?\n"
	.string "Sona molt estimulant!\p"
	.string "Crec que podria escriure\n"
	.string "una cançó sobre una de\l"
	.string "les teves aventures.\p"
	.string "…Oh, ei, el sento.\n"
	.string "Sento els riffs al cap.\p"
	.string "He d'escriure bé\n"
	.string "aquesta melodia,\l"
	.string "així que he d'anar! Adéu!$"

MatchCall_PersonalizedText10::
	.string "M'encanten els Pokémon!\n"
	.string "Sóc {STR_VAR_1}!\p"
	.string "Has d'escoltar-me!\n"
	.string "El meu estimat Pokémon…\p"
	.string "Snort! Wahaha!\n"
	.string "No puc dir res més!\l"
	.string "És un secret!\l"
	.string "És massa adorable\l"
	.string "per expressar-ho!\p"
	.string "Oh, el meu estimat\n"
	.string "{STR_VAR_2} vol\l"
	.string "un {POKEBLOCK}!\p"
	.string "Quin cucufeta tan adorable!\p"
	.string "Ho sento, no puc parlar!\n"
	.string "Explica-m'ho la propera!$"

MatchCall_PersonalizedText11::
	.string "Ufufufufu…\n"
	.string "Sóc jo, {STR_VAR_1}…\p"
	.string "Pots endevinar el que veig?\n"
	.string "Un parell de {STR_VAR_2} lluitant.\p"
	.string "Potser intentaré atrapar\n"
	.string "el guanyador…\n"
	.string "Ufufufufufu…\p"
	.string "Jo… estic una mica ocupat.\n"
	.string "He d'anar.$"

MatchCall_PersonalizedText12::
	.string "Sóc {STR_VAR_1}.\p"
	.string "Quan un entrenador fort\n"
	.string "s'apropa, de vegades\l"
	.string "ho presento d'alguna manera.\p"
	.string "Has passat prop, {PLAYER}{KUN}?\n"
	.string "Potser eres tu.\p"
	.string "T'esperaré que vinguis.\n"
	.string "Adéu!$"

MatchCall_PersonalizedText13::
	.string "Vrrrroooooooooooom!\p"
	.string "Ei! Sóc {STR_VAR_1}! Ha! Ha!\p"
	.string "Intentar xatejar…\n"
	.string "Mentre vaig amb la bici…\l"
	.string "És perillós!\p"
	.string "Xategem…una altra vegada…\l"
	.string "No vull xocar!!$"

MatchCall_PersonalizedText14::
	.string "Yahoo, sóc {STR_VAR_1}!\n"
	.string "Com estàs?\p"
	.string "He estat entrenant\n"
	.string "els meus Pokémon\l"
	.string "amb tu com a objectiu.\p"
	.string "No tinc intenció de perdre\n"
	.string "quan lluitems altra vegada.\p"
	.string "No és genial tenir amics\n"
	.string "entrenadors?\l"
	.string "Fins la propera!$"

MatchCall_PersonalizedText15::
	.string "{STR_VAR_1} al telèfon.\p"
	.string "El meu {STR_VAR_2} s'ha\n"
	.string "tornat encara més fort\l"
	.string "que l'última vegada.\p"
	.string "No et tornaré a perdre.\n"
	.string "Espera la propera vegada!\p"
	.string "Fins aviat!$"

MatchCall_PersonalizedText16::
	.string "Ohoho!\p"
	.string "Sóc {STR_VAR_1}! No veig\n"
	.string "l'hora de parlar-te\l"
	.string "del meu estimat Pokémon!\p"
	.string "Si us plau, escolta'm.\n"
	.string "És sobre el meu estimat\l"
	.string "{STR_VAR_2}.\p"
	.string "Quan algú el recull,\n"
	.string "salta directe als meus braços!\p"
	.string "Oh… Oh… Pot haver-hi\n"
	.string "alguna cosa més beatífica?\p"
	.string "Oh, em sembla tan celestial!\p"
	.string "M'alegra tant haver compartit\n"
	.string "part de la meva felicitat\l"
	.string "amb tu.\p"
	.string "Bé, he d'anar.\n"
	.string "Adéu!$"

MatchCall_PersonalizedText17::
	.string "Oh, sóc {STR_VAR_1}, hola.\p"
	.string "He estat nedant molt però\n"
	.string "no arribo a Cinnabar.\p"
	.string "Potser estic donant voltes.\p"
	.string "No, no, no pot ser.\n"
	.string "Wahahaha.\l"
	.string "Cuida't!$"

MatchCall_PersonalizedText18::
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} al telèfon.\p"
	.string "Com estan els teus Pokémon?\p"
	.string "Els meus Pokémon Drac\n"
	.string "semblen en plena forma.\l"
	.string "Fins aviat.$"

MatchCall_PersonalizedText19::
	.string "Sóc {STR_VAR_1}.\p"
	.string "He continuat estudiant\n"
	.string "l'art de fer malabars.\p"
	.string "Però no he tingut\n"
	.string "massa èxit.\p"
	.string "De vegades sento que\n"
	.string "la meva vida és\l"
	.string "com les meves boles...\p"
	.string "Caigudes a terra,\n"
	.string "botant caòticament.\p"
	.string "Adéu!$"

MatchCall_PersonalizedText20::
	.string "Hola, sóc {STR_VAR_1}…\p"
	.string "Estic una mica fart\n"
	.string "d'això de l'Entrenador\l"
	.string "Guai…\p"
	.string "Tothom pensa que sóc\n"
	.string "un Entrenador perfecte,\l"
	.string "i intento estar a\l"
	.string "l'alçada d'aquesta\l"
	.string "expectativa.\p"
	.string "Però suposo que va amb\n"
	.string "ser un Entrenador Guai.\p"
	.string "Hauré de posar-me les piles…\n"
	.string "i aguantar.\p"
	.string "Ets l'única persona a qui\n"
	.string "puc explicar-li això.\p"
	.string "Però quan ens vegem,\n"
	.string "no et preocupis,\l"
	.string "no me'n queixaré!$"
