@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " tan bonic!$"

GiddyText_SoDarling::
	.string " tan adorable!$"

GiddyText_SoRelaxed::
	.string " tan relaxat!$"

GiddyText_SoSunny::
	.string " tan assolellat!$"

GiddyText_SoDesirable::
	.string " tan desitjable!$"

GiddyText_SoExciting::
	.string " tan emocionant!$"

GiddyText_SoAmusing::
	.string " tan divertit!$"

GiddyText_SoMagical::
	.string " tan màgic!$"

GiddyText_Is::
	.string " és$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "No hi estàs d'acord?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Tinc moltes ganes d'anar de vacances.\n"
	.string "Per cas coneixes un lloc bonic?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "He comprat llapis de colors de 120!\n"
	.string "No et sembla meravellós?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "No seria genial poder flotar\n"
	.string "sobre un núvol de bombolles?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Quan escrius a la sorra de la platja,\n"
	.string "s'esborra. Em posa trist.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Com serà el fons del mar?\n"
	.string "Una vegada m'hi encantaria anar!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Quan veus el sol ponent, et fa\n"
	.string "venir ganes de tornar a casa?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Estirar-se a l'herba verda…\n"
	.string "Oh, és tan, tan bonic!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "Les Bases Secretes són meravelloses!\n"
	.string "No notes l'emoció?$"
