MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Aquest moviment només es pot\n"
	.string "aprendre una vegada. D'acord?$"

MoveTutor_Text_SwaggerTeach:
	.string "Ei! El meu Pokémon és increïble!\n"
	.string "És més guai que qualsevol Pokémon!\p"
	.string "Em passejava amb tanta arrogància\n"
	.string "quan el President em va cridar\l"
	.string "l'atenció.\p"
	.string "Això em va treure l'arrogància del cos.\p"
	.string "Si vols, ensenyaré el moviment\n"
	.string "Fanfarroneig a un Pokémon teu.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Com que no? No t'hi pots\n"
	.string "posar a l'ambient?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Molt bé, quin Pokémon vol\n"
	.string "aprendre Fanfarroneig?$"

MoveTutor_Text_SwaggerTaught:
	.string "De ara en endavant lloaré el meu\n"
	.string "Pokémon sense arrogància.$"

MoveTutor_Text_RolloutTeach:
	.string "Sabies que des d'aquí pots anar\n"
	.string "molt lluny sense canviar de\l"
	.string "direcció?\p"
	.string "Potser fins i tot jo podria\n"
	.string "rodar d'aquella manera.\p"
	.string "Creus que el teu Pokémon\n"
	.string "també voldrà rodar?\p"
	.string "Puc ensenyar a un la Rodolada\n"
	.string "si vols.$"

MoveTutor_Text_RolloutDeclined:
	.string "No cal ser tímid.\n"
	.string "Anem a rodar!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, per descomptat! Seria genial\n"
	.string "si el Pokémon s'assemblés a mi.$"

MoveTutor_Text_RolloutTaught:
	.string "Rodar per l'herba em fa feliç.\n"
	.string "Vinga, anem a rodar!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Hi ha un moviment que es fa\n"
	.string "més fort quan s'usa consecutivament.\p"
	.string "És un moviment de tipus Insecte,\n"
	.string "i és increïblement guai.\p"
	.string "Es diu Frenesi Talls.\n"
	.string "Vols que l'ensenyi a un Pokémon?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "No estem en la mateixa\n"
	.string "longitud d'ona.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Hurra!\n"
	.string "Ensenya'm quin Pokémon hauria d'ensenyar.$"

MoveTutor_Text_FuryCutterTaught:
	.string "M'emociona veure si el moviment\n"
	.string "continua colpejant de seguit!$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humf! La meva dona depèn del\n"
	.string "Poder Ocult per estar desperta.\p"
	.string "Hauria de fer una becaina com jo,\n"
	.string "i parlar mentre dorm.\p"
	.string "Puc ensenyar al teu Pokémon com\n"
	.string "Parlar Dormint. T'interessa?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, bé, bé. Tu també vols estar\n"
	.string "despert amb Poder Ocult…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, un nen agraït!\n"
	.string "A quin Pokémon hauria d'ensenyar?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Mai no he encertat el truc de la\n"
	.string "moneda de la meva dona.\p"
	.string "Estaria content si ho encertés\n"
	.string "fins i tot parlant dormint…$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Ja no puc més!\p"
	.string "És completament inútil!\p"
	.string "Sóc un Entrenador de Combat,\n"
	.string "i no puc guanyar al Gimnàs de\l"
	.string "Mossdeep per molt que ho intento!\p"
	.string "Argh! Cop! Cop! Cop!\n"
	.string "Cop! Cop! Cop!\p"
	.string "Ep, no em miris així!\n"
	.string "Només estic colpejant el terra!\p"
	.string "O vols que ensenyi Cop Dinàmic\n"
	.string "al teu Pokémon?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Caram! Fins i tot te'n rius?\n"
	.string "Cop! Cop! Cop!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Què? De debò? Ets bona persona!\n"
	.string "A quin Pokémon hauria d'ensenyar?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Vull que guanyis al Gimnàs de\n"
	.string "Mossdeep amb aquell Cop Dinàmic!$"

MoveTutor_Text_ExplosionTeach:
	.string "No tinc intenció de quedar-me\n"
	.string "encallat aquí per sempre.\p"
	.string "Ja ho veuràs, sortiré a la\n"
	.string "ciutat i em convertiré en un gran èxit.\p"
	.string "En serio, causaré una enorme\n"
	.string "Explosió de popularitat!\p"
	.string "Si m'has sentit, t'ensenyaré\n"
	.string "Explosió al teu Pokémon!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Grr! Em rebutges perquè\n"
	.string "visc al camp?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Bé! Doncs Explosió!\n"
	.string "Quin Pokémon vol explotar?$"

MoveTutor_Text_ExplosionTaught:
	.string "Fa molt que ensenyo els Pokémon\n"
	.string "a usar Explosió, però la meva\l"
	.string "pròpia encara no ha encès…\p"
	.string "Potser és perquè, en el fons,\n"
	.string "prefereixo quedar-me aquí…$"
