gText_ObtainedTheItem::
	.string "Has obtingut {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "La Motxilla està plena…$"

gText_PutItemInPocket::
	.string "{PLAYER} ha guardat {STR_VAR_2}\n"
	.string "a la butxaca {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} ha trobat {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Llàstima!\n"
	.string "La Motxilla està plena…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} ha guardat {STR_VAR_2}\n"
	.string "a la Motxilla.$"

gText_ObtainedTheDecor::
	.string "Has obtingut {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Llàstima! No hi ha espai per\n"
	.string "un altre {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} s'ha transferit\n"
	.string "a l'ordinador.$"
