gText_ObtainedTheItem::
	.string "Has obtingut {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "La motxilla és plena…$"

gText_PutItemInPocket::
	.string "{PLAYER} ha guardat {STR_VAR_2}\n"
	.string "a la butxaca {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} ha trobat un {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Quina llàstima!\n"
	.string "La motxilla és plena…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} ha guardat {STR_VAR_2}\n"
	.string "a la motxilla.$"

gText_ObtainedTheDecor::
	.string "Has obtingut {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Llàstima! No queda lloc per a\n"
	.string "un altre {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} s'ha transferit\n"
	.string "al PC.$"
