Text_BootUpPC:
	.string "{PLAYER} ha engegat el PC.$"

gText_WhichPCShouldBeAccessed::
	.string "A quin PC vols entrar?$"

gText_AccessedSomeonesPC::
	.string "Has entrat al PC d'algú.$"

gText_StorageSystemOpened::
	.string "S'ha obert el Sistema\nd'Emmagatzematge Pokémon.$"

gText_AccessedPlayersPC::
	.string "Has entrat al PC de {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Has entrat al PC del Bill.$"
