Text_BootUpPC:
	.string "{PLAYER} ha encès l'ordinador.$"

gText_WhichPCShouldBeAccessed::
	.string "A quin ordinador vols accedir?$"

gText_AccessedSomeonesPC::
	.string "Has accedit a l'ordinador d'algú.$"

gText_StorageSystemOpened::
	.string "S'ha obert el Sistema\n"
	.string "d'Emmagatzematge Pokémon.$"

gText_AccessedPlayersPC::
	.string "Has accedit a l'ordinador de {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Has accedit a l'ordinador d'en Bill.$"
