Text_BootUpPC:
	.string "{PLAYER} ha encès l'ordinador.$"

gText_WhichPCShouldBeAccessed::
	.string "A quin ordinador vols accedir?$"

gText_AccessedSomeonesPC::
	.string "Ordinador d'algú accedit.$"

gText_StorageSystemOpened::
	.string "Sistema d'emmagatzematge Pokémon obert.$"

gText_AccessedPlayersPC::
	.string "Ordinador d'{PLAYER} accedit.$"

gText_AccessedLanettesPC::
	.string "Ordinador del Bill accedit.$"
