gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} s'ha transferit a\n"
	.string "l'ordinador d'algú.\p"
	.string "S'ha col·locat a la\n"
	.string "Caixa "{STR_VAR_1}."$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} s'ha transferit a\n"
	.string "l'ordinador del Bill.\p"
	.string "S'ha col·locat a la\n"
	.string "Caixa "{STR_VAR_1}."$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "La Caixa "{STR_VAR_3}" de\n"
	.string "l'ordinador d'algú estava plena.\p"
	.string "{STR_VAR_2} s'ha transferit a\n"
	.string "la Caixa "{STR_VAR_1}."$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "La Caixa "{STR_VAR_3}" de\n"
	.string "l'ordinador del Bill estava plena.\p"
	.string "{STR_VAR_2} s'ha transferit a\n"
	.string "la Caixa "{STR_VAR_1}."$"

gText_NoMoreRoomForPokemon::
	.string "Ja no hi ha espai per a Pokémon!\p"
	.string "Les Caixes de Pokémon estan plenes\n"
	.string "i no en caben més!$"

gText_NicknameThisPokemon::
	.string "Vols posar un malnom a\n"
	.string "aquest {STR_VAR_1}?$"
