gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} s'ha transferit al\n"
	.string "PC d'algú.\p"
	.string "S'ha col·locat a la\n"
	.string "caixa “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} s'ha transferit al\n"
	.string "PC del Bill.\p"
	.string "S'ha col·locat a la\n"
	.string "caixa “{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "La caixa “{STR_VAR_3}” del\n"
	.string "PC d'algú era plena.\p"
	.string "{STR_VAR_2} s'ha transferit al\n"
	.string "caixa “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "La caixa “{STR_VAR_3}” del\n"
	.string "PC del Bill era plena.\p"
	.string "{STR_VAR_2} s'ha transferit al\n"
	.string "caixa “{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon::
	.string "Ja no queda lloc per a més Pokémon!\p"
	.string "Les caixes Pokémon són plenes i\n"
	.string "no hi caben més!$"

gText_NicknameThisPokemon::
	.string "Vols posar un sobrenom a\n"
	.string "aquest {STR_VAR_1}?$"
