
gPokeNewsTextSlateport_Upcoming::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "El personatge més popular de\n"


	.string "Slateport, el Gurú de l'Energia,\l"
	.string "torna a ser notícia!\p"


	.string "Promet “donar-ho tot d'aquí a\n"


	.string "exactament {STR_VAR_1} dies!”\p"


	.string "Tot i que no ha volgut aclarir\n"


	.string "en què ho donarà tot, el Gurú de\l"


	.string "l'Energia ha dit: “Estalvieu diners.\l"


	.string "Us anirà bé…”\p"


	.string "Sembla que valdrà la pena visitar\n"


	.string "Slateport aquell dia.\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextSlateport_Ongoing::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Aquesta és la notícia que\n"


	.string "tots esperàveu!\p"


	.string "El Gurú de l'Energia de Slateport\n"


	.string "ho dona tot al Mercat!\p"


	.string "Promet preus de ganga imbatibles\n"


	.string "en Calci i Proteïna!\p"


	.string "Sembla que val la pena visitar\n"


	.string "Slateport. Per què no hi aneu\l"


	.string "a comprar tant com vulgueu?\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextSlateport_Ending::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Aquesta és la notícia que\n"


	.string "tots esperàveu!\p"


	.string "El Gurú de l'Energia de Slateport\n"


	.string "ho dona tot al Mercat!\p"


	.string "Promet preus de ganga imbatibles\n"


	.string "en Calci i Proteïna!\p"


	.string "Segons el Gurú de l'Energia, encara\n"


	.string "li queda força mercaderia.\p"


	.string "Per què no visiteu Slateport per\n"


	.string "fer una agradable compra?\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextGameCorner_Upcoming::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "S'acosta!\n"


	.string "Finalment ve!\p"


	.string "El dia de servei del Sala de Jocs\n"


	.string "arribarà en {STR_VAR_1} dies!\p"


	.string "Fins i tot els que solen tenir\n"


	.string "mala sort podrien tenir-ne de bona\l"
	.string "aquell dia!\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextGameCorner_Ongoing::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Ja és aquí!\n"


	.string "Finalment ha arribat!\p"


	.string "El dia de servei del Sala de Jocs\n"


	.string "finalment ha arribat!\p"


	.string "Podries tenir sort a les Màquines\n"


	.string "i la Ruleta?\p"


	.string "El lloc és Ciutat Mauville.\n"


	.string "Aquest és el lloc!\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextGameCorner_Ending::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Ja és aquí!\n"


	.string "Finalment ha arribat!\p"


	.string "El dia de servei del Sala de Jocs\n"


	.string "finalment ha arribat!\p"


	.string "Podries tenir sort a les Màquines\n"


	.string "i la Ruleta?\p"


	.string "El temps és limitat i gairebé s'acaba.\n"


	.string "El lloc és Ciutat Mauville.\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextLilycove_Upcoming::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Acabem de rebre notícies meravelloses\n"


	.string "dels Grans Magatzems de Lilycove.\p"


	.string "La gran liquidació dels Grans\n"


	.string "Magatzems serà d'aquí a {STR_VAR_1} dies!\p"


	.string "Aquella cosa que sempre has volgut\n"


	.string "podria ser teva!\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextLilycove_Ongoing::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Aquesta és la notícia que\n"


	.string "tots esperàveu!\p"


	.string "La gran liquidació dels Grans\n"


	.string "Magatzems de Lilycove ha arribat!\p"


	.string "Totes aquelles coses amb les quals\n"


	.string "sempre has somiat…\p"


	.string "Potser el destí te les fa\n"


	.string "trobar totes!\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextLilycove_Ending::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Aquesta és la notícia que\n"


	.string "tots esperàveu!\p"


	.string "La gran liquidació dels Grans\n"


	.string "Magatzems de Lilycove ha arribat!\p"


	.string "Totes aquelles coses amb les quals\n"


	.string "sempre has somiat…\p"


	.string "Potser el destí te les fa\n"


	.string "trobar totes!\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextBlendMaster_Upcoming::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Tenim grans notícies per a tothom\n"


	.string "involucrat en la creació de {POKEBLOCK}s.\p"


	.string "El llegendari Mestre Barrejador\n"


	.string "apareixerà a Lilycove d'aquí a\l"


	.string "tan sols {STR_VAR_1} dies!\p"


	.string "Es diu que el Mestre Barrejador\n"


	.string "és el millor de tot Hoenn a l'hora de\l"


	.string "fer girar la Batedora de Baies.\p"


	.string "S'aconsella als qui vulguin fer\n"


	.string "bons {POKEBLOCK}s o veure el Mestre\l"


	.string "en acció que guardin les seves Baies.\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextBlendMaster_Ongoing::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Tenim grans notícies per a tothom\n"


	.string "involucrat en la creació de {POKEBLOCK}s.\p"


	.string "El llegendari Mestre Barrejador\n"


	.string "finalment ha aparegut!\p"


	.string "El Mestre Barrejador fa girar la\n"


	.string "Batedora de Baies a la Sala de\l"


	.string "Concursos de Lilycove.\p"


	.string "Aquells qui vulguin fer bons {POKEBLOCK}s\n"


	.string "o veure el Mestre en acció\l"


	.string "haurien d'afanyar-se a anar a Lilycove.\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextBlendMaster_Ending::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "És increïble!\n"


	.string "Massa increïble, fins i tot!\p"


	.string "La Batedora de Baies gira\n"


	.string "a una velocitat vertiginosa!\p"


	.string "El Mestre Barrejador ha estat\n"


	.string "a l'alçada de la seva reputació!\p"


	.string "El Mestre Barrejador aviat\n"


	.string "deixarà Lilycove.\p"


	.string "Si no has vist el Mestre en acció,\n"


	.string "no perdis aquesta oportunitat!\l"


	.string "Vés a Lilycove ara mateix!\p"


	.string "Això és tot per a les Notícies Pokémon.$"


