gOakDexRatingText_GoodToSeeYou::
	.string "Oak: Que alegria veure't, {PLAYER}!\n"
	.string "Com va la teva Pokédex?\p"
	.string "Deixa'm fer una ullada.$"

gOakDexRatingText_AreYouCurious::
	.string "Oak: Quin plaer tenir notícies\n"
	.string "teves, {PLAYER}!\p"
	.string "Com va la teva Pokédex?\p"
	.string "Mirem-ho...$"

gOakDexRatingText_Cancel::
	.string "Hmm? Oh, encara no has capturat\n"
	.string "prou Pokémon perquè valgui la pena.$"

gOakDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Així doncs, has vist {STR_VAR_1} Pokémon,\n"
	.string "i has capturat {STR_VAR_2} Pokémon…$"

gOakDexRatingText_LessThan10::
	.string "Encara et queda molt per fer.\p"
	.string "Fica't a totes les zones d'herba\n"
	.string "que vegis i busca Pokémon!$"

gOakDexRatingText_LessThan20::
	.string "Sembla que hi vas agafant el truc.\n"
	.string "Però a partir d'ara es complica.$"

gOakDexRatingText_LessThan30::
	.string "Alguns Pokémon només apareixen\n"
	.string "en certes zones o moments del dia.\l"
	.string "Has de ser persistent.$"

gOakDexRatingText_LessThan40::
	.string "Bé, encara hi falten Pokémon,\n"
	.string "però ja comença a semblar\l"
	.string "una Pokédex de veritat.$"

gOakDexRatingText_LessThan50::
	.string "Això va força bé.\n"
	.string "Continua esforçant-te.$"

gOakDexRatingText_LessThan60::
	.string "Fas servir alguna Canya?\n"
	.string "Hi ha molts Pokémon al mar.$"

gOakDexRatingText_LessThan70::
	.string "Hoho! Això s'està convertint\n"
	.string "en una Pokédex ben respectable!$"

gOakDexRatingText_LessThan80::
	.string "Molt bé!\p"
	.string "Crec que pots capturar encara\n"
	.string "més Pokémon si vas a pescar!$"

gOakDexRatingText_LessThan90::
	.string "Meravellós! Deixa'm endevinar…\n"
	.string "T'agrada col·leccionar coses, oi?$"

gOakDexRatingText_LessThan100::
	.string "Estic impressionat!\n"
	.string "Ha d'haver estat difícil!$"

gOakDexRatingText_LessThan110::
	.string "Per fi has arribat a 100 espècies!\n"
	.string "No em puc creure que siguis tan {MASC}bo{FEM}bona{ENDG}!$"

gOakDexRatingText_LessThan120::
	.string "Fins i tot tens les formes\n"
	.string "evolucionades! Genial!$"

gOakDexRatingText_LessThan130::
	.string "Excel·lent! Alguns Pokémon tenen\n"
	.string "maneres molt especials d'evolucionar.\l"
	.string "Pot ser que hagis de buscar-los!$"

gOakDexRatingText_LessThan140::
	.string "Extraordinari!\n"
	.string "Ja ets {MASC}tot un professional{FEM}tota una professional{ENDG}!$"

gOakDexRatingText_LessThan150::
	.string "No em queda res per dir!\n"
	.string "Ara {MASC}el Professor{FEM}la Professora{ENDG} Pokémon ets tu!$"

gOakDexRatingText_LessThan151::
	.string "He sentit uns nens que deien que\n"
	.string "alguns Pokémon rars s'amaguen\l"
	.string "sota els camions!\p"
	.string "Però jo no me'ls crec, eh.$"

gOakDexRatingText_LessThan170::
	.string "Mirant la teva Pokédex, es pot\n"
	.string "tenir una idea molt bona dels\l"
	.string "Pokémon de la regió de Hoenn.$"

gOakDexRatingText_LessThan180::
	.string "Diria que ja pots considerar-te\n"
	.string "{MASC}Professor{FEM}Professora{ENDG} Pokémon, i {MASC}dels bons{FEM}de les bones{ENDG},\l"
	.string "a més!$"

gOakDexRatingText_LessThan190::
	.string "Amb una Pokédex tan completa,\n"
	.string "ets {MASC}un professional{FEM}una professional{ENDG} de veritat!$"

gOakDexRatingText_LessThan200::
	.string "Estàs molt a prop de completar\n"
	.string "aquesta Pokédex.\l"
	.string "Ho noto als ossos!$"

gOakDexRatingText_DexCompleted::
	.string "La teva Pokédex està completa del tot!\n"
	.string "Enhorabona!!$"
