
gPokeNewsTextSlateport_Upcoming::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "El Gurú de l'Energia de Slateport,\n"


	.string "el personatge més popular, torna!\p"


	.string "Promet “anar-hi a tope en\n"


	.string "exactament {STR_VAR_1} dies!”\p"


	.string "Tot i que no ha volgut aclarir a\n"


	.string "qué anirà a tope, el Gurú de\l"


	.string "l'Energia ha dit: “Estalvieu.\l"


	.string "Això serà bo…”\p"


	.string "Sembla que valdrà la pena visitar\n"


	.string "Slateport aquell dia.\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextSlateport_Ongoing::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Aquesta és la notícia que\n"


	.string "tots esperàveu!\p"


	.string "El Gurú de l'Energia de Slateport\n"


	.string "va a tope al Mercat!\p"


	.string "Promet preus de ganga imbatibles\n"


	.string "en Calci i Proteïna!\p"


	.string "Visitar Slateport sembla que\n"


	.string "val la pena. Per qué no anireu\l"


	.string "a comprar fins on podeu?\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextSlateport_Ending::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Aquesta és la notícia que\n"


	.string "tots esperàveu!\p"


	.string "El Gurú de l'Energia de Slateport\n"


	.string "va a tope al Mercat!\p"


	.string "Promet preus de ganga imbatibles\n"


	.string "en Calci i Proteïna!\p"


	.string "Segons el Gurú de l'Energia, encara\n"


	.string "li queda força mercaderia.\p"


	.string "Per qué no visiteu Slateport per\n"


	.string "fer una agradable compra?\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextGameCorner_Upcoming::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "S'acosta!\n"


	.string "Finalment ve!\p"


	.string "El dia de servei del Saló de Jocs\n"


	.string "arribarà en {STR_VAR_1} dies!\p"


	.string "Fins i tot els que solen tenir\n"


	.string "mala sort podrien tenir-ne aquell dia!\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextGameCorner_Ongoing::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Ja és aquí!\n"


	.string "Finalment ha arribat!\p"


	.string "El dia de servei del Saló de Jocs\n"


	.string "finalment ha arribat!\p"


	.string "Podries tenir sort a les Màquines\n"


	.string "i la Ruleta?\p"


	.string "Al Saló de Jocs a Mauville City.\n"


	.string "Aquest és el lloc!\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextGameCorner_Ending::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Ja és aquí!\n"


	.string "Finalment ha arribat!\p"


	.string "El dia de servei del Saló de Jocs\n"


	.string "finalment ha arribat!\p"


	.string "Podries tenir sort a les Màquines\n"


	.string "i la Ruleta?\p"


	.string "El temps és limitat i gairebé s'acaba.\n"


	.string "El lloc és Mauville City.\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextLilycove_Upcoming::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Acabem de rebre notícies meravelloses\n"


	.string "dels Grans Magatzems de Lilycove.\p"


	.string "La venda de liquidació dels Grans\n"


	.string "Magatzems serà en {STR_VAR_1} dies!\p"


	.string "Aquella cosa que sempre has volgut\n"


	.string "podria ser teva!\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextLilycove_Ongoing::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Aquesta és la notícia que\n"


	.string "tots esperàveu!\p"


	.string "La venda de liquidació dels Grans\n"


	.string "Magatzems de Lilycove ha arribat!\p"


	.string "Totes aquelles coses amb les quals\n"


	.string "sempre has somiat…\p"


	.string "Podries tenir encontres fatídics\n"


	.string "amb totes elles!\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextLilycove_Ending::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Aquesta és la notícia que\n"


	.string "tots esperàveu!\p"


	.string "La venda de liquidació dels Grans\n"


	.string "Magatzems de Lilycove ha arribat!\p"


	.string "Totes aquelles coses amb les quals\n"


	.string "sempre has somiat…\p"


	.string "Podries tenir encontres fatídics\n"


	.string "amb totes elles!\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextBlendMaster_Upcoming::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Tenim grans notícies per a tothom\n"


	.string "involucrat en la creació de {POKEBLOCK}s.\p"


	.string "El llegendari Mestre Barrejador\n"


	.string "apareixerà a Lilycove en\l"


	.string "tan sols {STR_VAR_1} dia(es) més!\p"


	.string "Es diu que el Mestre Barrejador\n"


	.string "és el millor de tot Hoenn en\l"


	.string "girar la Batedora de Baies.\p"


	.string "S'aconsella als qui vulguin fer\n"


	.string "bons {POKEBLOCK}s o veure el Mestre\l"


	.string "en acció que guardin les seves Baies.\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextBlendMaster_Ongoing::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "Tenim grans notícies per a tothom\n"


	.string "involucrat en la creació de {POKEBLOCK}s.\p"


	.string "El llegendari Mestre Barrejador\n"


	.string "finalment ha aparegut!\p"


	.string "El Mestre Barrejador gira la\n"


	.string "Batedora de Baies a la Sala de\l"


	.string "Concursos de Lilycove.\p"


	.string "Aquells qui vulguin fer bons {POKEBLOCK}s\n"


	.string "o veure el Mestre en acció\l"


	.string "haurien d'anar ràpid a Lilycove.\p"


	.string "Això és tot per a les Notícies Pokémon.$"



gPokeNewsTextBlendMaster_Ending::
	.string "Benvinguts!\n"


	.string "Hora de les Notícies Pokémon.\p"


	.string "És increïble!\n"


	.string "Massa increïble, fins i tot!\p"


	.string "La Batedora de Baies gira\n"


	.string "a una velocitat vertiginosa!\p"


	.string "El Mestre Barrejador ha estat\n"


	.string "a l'alçada de la seva reputació!\p"


	.string "El Mestre Barrejador aviat\n"


	.string "deixarà Lilycove.\p"


	.string "Si no has vist el Mestre en acció,\n"


	.string "no perdis aquesta oportunitat!\l"


	.string "Vés a Lilycove ara mateix!\p"


	.string "Això és tot per a les Notícies Pokémon.$"


