gOakDexRatingText_GoodToSeeYou::
	.string "OAK: Que alegria veure't, {PLAYER}!\n"
	.string "Com va el teu Pokédex?\p"
	.string "Deixa'm fer una ullada.$"

gOakDexRatingText_AreYouCurious::
	.string "OAK: Quin plaer tenir notícies\n"
	.string "teves, {PLAYER}!\p"
	.string "Com va el teu Pokédex?\p"
	.string "Mirem-ho...$"

gOakDexRatingText_Cancel::
	.string "Hmm? Oh, no has capturat suficients\n"
	.string "Pokémon com per valer la pena.$"

gOakDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Llavors has vist {STR_VAR_1} Pokémon,\n"
	.string "i has capturat {STR_VAR_2} Pokémon…$"

gOakDexRatingText_LessThan10::
	.string "Encara et queda molt per fer.\p"
	.string "Endinsa't a tota gespa que\n"
	.string "vegis i busca POKÉMON!$"

gOakDexRatingText_LessThan20::
	.string "Sembla que li agafes el tranc.\n"
	.string "Però d'aquí en endavant és més difícil.$"

gOakDexRatingText_LessThan30::
	.string "Alguns Pokémon només apareixen\n"
	.string "en certes zones o moments del dia.\l"
	.string "Has de ser persistent.$"

gOakDexRatingText_LessThan40::
	.string "Bé, li falta quantitat,\n"
	.string "però ara comença a assemblar-se\l"
	.string "a un Pokédex.$"

gOakDexRatingText_LessThan50::
	.string "Això va força bé.\n"
	.string "Continua esforçant-te.$"

gOakDexRatingText_LessThan60::
	.string "Uses alguna Canya?\n"
	.string "Hi ha molts Pokémon al mar.$"

gOakDexRatingText_LessThan70::
	.string "Hoho! Això s'està convertint\n"
	.string "en un Pokédex ben respectable!$"

gOakDexRatingText_LessThan80::
	.string "Molt bé!\p"
	.string "Crec que pots capturar encara\n"
	.string "més Pokémon si vas a pescar!$"

gOakDexRatingText_LessThan90::
	.string "Meravellós! Deixa'm endevinar…\n"
	.string "T'agrada col·leccionar coses, oi?$"

gOakDexRatingText_LessThan100::
	.string "Estic impressionat!\n"
	.string "Ha d'haver estat difícil!$"

gOakDexRatingText_LessThan110::
	.string "Finalment has arribat a 100 espècies!\n"
	.string "No puc creure el bé que ho fas!$"

gOakDexRatingText_LessThan120::
	.string "Fins i tot tens les formes\n"
	.string "evolucionades! Super!$"

gOakDexRatingText_LessThan130::
	.string "Excel·lent! Alguns Pokémon tenen\n"
	.string "maneres molt especials d'evolucionar.\l"
	.string "Pot ser que hagis de buscar-los!$"

gOakDexRatingText_LessThan140::
	.string "Extraordinari!\n"
	.string "Ja ets tot un professional!$"

gOakDexRatingText_LessThan150::
	.string "No em queda res per dir!\n"
	.string "Ara ets el Professor Pokémon!$"

gOakDexRatingText_LessThan151::
	.string "He sentit nens parlant de com\n"
	.string "alguns Pokémon rars s'amaguen\l"
	.string "sota dels camions!\p"
	.string "Però no me'ls crec, jo.$"

gOakDexRatingText_LessThan170::
	.string "Mirant el teu Pokédex, un es pot\n"
	.string "fer una idea molt bona dels\l"
	.string "Pokémon de la regió Hoenn.$"

gOakDexRatingText_LessThan180::
	.string "Diria que ja et qualifiques com\n"
	.string "a Professor Pokémon, i un de bo\l"
	.string "a més!$"

gOakDexRatingText_LessThan190::
	.string "Amb un Pokédex tan complet,\n"
	.string "ets un professional de veritat!$"

gOakDexRatingText_LessThan200::
	.string "Estàs molt a prop de completar\n"
	.string "aquest Pokédex.\l"
	.string "Ho noto als ossos!$"

gOakDexRatingText_DexCompleted::
	.string "El teu Pokédex és completament complet!\n"
	.string "Enhorabona!!$"
