Questionnaire_Text_FillOut::
	.string "Hi ha un qüestionari.\n"
	.string "Vols emplenar-lo?$"

Questionnaire_Text_ThankYou::
	.string "Gràcies per prendre't el temps\n"
	.string "d'emplenar el nostre qüestionari.\p"
	.string "Tindrem en compte els teus\n"
	.string "comentaris en el futur.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, hola!\n"
	.string "Coneixes aquestes paraules?\p"
	.string "Això vol dir que deus conèixer\n"
	.string "el Regal Misteriós.\p"
	.string "A partir d'ara, hauries de\n"
	.string "rebre Regals Misteriosos!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Quan hagis desat la partida,\n"
	.string "podràs accedir al Regal Misteriós.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, hola!\n"
	.string "Coneixes aquestes paraules?\p"
	.string "Això vol dir que deus conèixer\n"
	.string "l'Esdeveniment Misteriós.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Quan hagis desat la partida,\n"
	.string "podràs accedir a l'Esdeveniment\l"
	.string "Misteriós.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Gràcies per usar el Sistema\n"
	.string "d'Esdeveniment Misteriós.\p"
	.string "Deus ser {PLAYER}.\n"
	.string "Hi ha un tiquet aquí per a tu.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Sembla que és per usar-lo al\n"
	.string "port de Lilycove.\p"
	.string "Per què no el proves per veure\n"
	.string "de què es tracta?$"
