	.align 2
gText_ConfirmSave::
	.string "Vols desar la partida?$"

gText_AlreadySavedFile::
	.string "Ja hi ha una partida desada.\n"
	.string "La vols sobreescriure?$"

gText_SavingDontTurnOff::
	.string "S'està desant…\n"
	.string "No apaguis la consola.$"

gText_PlayerSavedGame::
	.string "{PLAYER} ha desat la partida.$"

gText_DifferentSaveFile::
	.string "ATENCIÓ!\p"
	.string "Hi ha una altra partida diferent\n"
	.string "que ja està desada.\p"
	.string "Si deses ara, l'aventura de l'altra\n"
	.string "partida, amb els objectes i els\l"
	.string "Pokémon, es perdrà del tot.\p"
	.string "Segur que vols desar ara i\n"
	.string "sobreescriure l'altra partida?$"

gText_SaveError::
	.string "Error en desar.\p"
	.string "Cal canviar la\n"
	.string "memòria de reserva.$"

gText_SavingDontTurnOffPower::
	.string "S'està desant…\n"
	.string "No apaguis la consola.$"
