	.align 2
gText_ConfirmSave::
	.string "Vols desar el joc?$"

gText_AlreadySavedFile::
	.string "Ja hi ha un arxiu desat.\n"
	.string "És correcte sobreescriure'l?$"

gText_SavingDontTurnOff::
	.string "Desant…\n"
	.string "No apagueu la consola.$"

gText_PlayerSavedGame::
	.string "{PLAYER} ha desat el joc.$"

gText_DifferentSaveFile::
	.string "AVÍS!\p"
	.string "Hi ha un arxiu de joc diferent\n"
	.string "que ja estava desat.\p"
	.string "Si deses ara, l'aventura de l'altre\n"
	.string "arxiu, incloent articles i\l"
	.string "Pokémon, es perdrà completament.\p"
	.string "Segur que vols desar ara\n"
	.string "i sobreescriure l'altre arxiu?$"

gText_SaveError::
	.string "Error en desar.\p"
	.string "Canvieu la\n"
	.string "memòria de còpia de seguretat.$"

gText_SavingDontTurnOffPower::
	.string "Desant…\n"
	.string "No apagueu la consola.$"
