SecretBase_Text_Trainer0Intro:
	.string "Ja tens una Base Secreta?\p"
	.string "Vaig anar per aquí i per allà\n"
	.string "fins a triar aquest lloc.\p"
	.string "Com que ja ets aquí, vols\n"
	.string "batallar?$"

SecretBase_Text_Trainer0AcceptBattle:
    .string "D'acord!\n"
    .string "Aquí anem!$"

SecretBase_Text_Trainer0DeclineBattle:
    .string "Ah?\n"
    .string "Oh, ara no pots…$"

SecretBase_Text_Trainer0Defeated::
    .string "Nooo! Ets massa fort!\n"
    .string "Que he perdut… Guarda el secret!$"

SecretBase_Text_Trainer0PostBattle:
    .string "Que et sembla la meva Base Secreta?\n"
    .string "Torna a visitar-me demà.$"

SecretBase_Text_Trainer0PreChampion:
    .string "Ja tens una Base Secreta?\p"
    .string "Vaig anar per aquí i per allà\n"
    .string "fins a triar aquest lloc.\p"
    .string "Vine quan vulguis!$"

SecretBase_Text_Trainer5Intro:
    .string "Hi ha molts llocs on pots fer\n"
    .string "una Base Secreta.\p"
    .string "Però a mi m'agrada més aquest.\n"
    .string "No trobes que és bonic?\p"
    .string "Oh, vols batallar?$"

SecretBase_Text_Trainer5AcceptBattle:
    .string "D'acord, allà anem!$"

SecretBase_Text_Trainer5DeclineBattle:
    .string "Oh…\n"
    .string "Ara no pots, d'acord.$"

SecretBase_Text_Trainer5Defeated::
    .string "Hmm… Hem perdut…\n"
    .string "Però no ho diguis a ningú!\l"
    .string "És un secret confidencial!$"

SecretBase_Text_Trainer5PostBattle:
    .string "Si tornes per aquí,\n"
    .string "espero que em visitis.$"

SecretBase_Text_Trainer5PreChampion:
    .string "Hi ha molts llocs on pots fer\n"
    .string "una Base Secreta.\p"
    .string "Però a mi m'agrada més aquest.\n"
    .string "No trobes que és bonic?$"

SecretBase_Text_Trainer1Intro:
    .string "Aquí és un lloc molt popular.\n"
    .string "Sempre és ocupat.\p"
    .string "Oh! Tu també pensaves\n"
    .string "ocupar aquest lloc?\p"
    .string "Et diré una cosa: pots tenir-lo\n"
    .string "si m'aconsegueixes guanyar.$"

SecretBase_Text_Trainer1AcceptBattle:
    .string "D'acord!\n"
    .string "Defensaré la meva Base Secreta!$"

SecretBase_Text_Trainer1DeclineBattle:
    .string "Ah? És que no?\n"
    .string "No t'interessa aquest lloc?$"

SecretBase_Text_Trainer1Defeated::
    .string "No puc continuar!\n"
    .string "Em rendeixo!$"

SecretBase_Text_Trainer1PostBattle:
    .string "D'acord, quan marxi algun dia,\n"
    .string "aquest lloc serà teu!$"

SecretBase_Text_Trainer1PreChampion:
    .string "Aquí és un lloc molt popular.\n"
    .string "Sempre és ocupat.\p"
    .string "Vaig esperar molt fins que va\n"
    .string "quedar lliure. Finalment és meu!$"

SecretBase_Text_Trainer6Intro:
    .string "Benvingut al meu Lab Pokémon.\p"
    .string "Porto a terme recerca sobre la\n"
    .string "batalla en secret.\p"
    .string "Vols veure com de fort sóc?$"

SecretBase_Text_Trainer6AcceptBattle:
    .string "Hi posaré totes les meves forces!$"

SecretBase_Text_Trainer6DeclineBattle:
    .string "Oh.\n"
    .string "Una altra vegada, doncs!$"

SecretBase_Text_Trainer6Defeated::
    .string "Hmm… Encara em queda molt per\n"
    .string "aprendre. He d'estudiar més.$"

SecretBase_Text_Trainer6PostBattle:
    .string "Gràcies per batallar amb mi.\n"
    .string "Torna a visitar-me demà.$"

SecretBase_Text_Trainer6PreChampion:
    .string "Benvingut al meu Lab Pokémon.\p"
    .string "Porto a terme recerca sobre la\n"
    .string "batalla en secret.$"

SecretBase_Text_Trainer2Intro:
    .string "Una mansió gran és bonica, però\n"
    .string "m'agrada més un lloc com aquest.\p"
    .string "M'agrada perquè ve tot tipus\n"
    .string "de gent a visitar-me.\p"
    .string "Así doncs, vols batallar?$"

SecretBase_Text_Trainer2AcceptBattle:
    .string "Molt bé!$"

SecretBase_Text_Trainer2DeclineBattle:
    .string "Quan estigueu a punt, fes-m'ho saber!$"

SecretBase_Text_Trainer2Defeated::
    .string "Au! Ja estic al terra!\n"
    .string "Però és divertit batallar!$"

SecretBase_Text_Trainer2PostBattle:
    .string "Bé, de totes maneres hauria\n"
    .string "d'anar a comprar decoracions\l"
    .string "i mobles.\p"
    .string "Vull que la meva Base Secreta\n"
    .string "sigui un lloc que tothom gaudeixi.$"

SecretBase_Text_Trainer2PreChampion:
    .string "Una mansió gran és bonica, però\n"
    .string "m'agrada més un lloc com aquest.\p"
    .string "M'agrada perquè ve tot tipus\n"
    .string "de gent a visitar-me.$"

SecretBase_Text_Trainer7Intro:
    .string "M'encanta comprar decoracions\n"
    .string "i mobles.\p"
    .string "També m'encanta criar Pokémon\n"
    .string "igual de tant.\p"
    .string "Si sou tan amable, vol batallar\n"
    .string "amb els meus Pokémon?$"

SecretBase_Text_Trainer7AcceptBattle:
    .string "Gràcies.\n"
    .string "Comencem?$"

SecretBase_Text_Trainer7DeclineBattle:
    .string "Oh.\n"
    .string "Quina decepció…$"

SecretBase_Text_Trainer7Defeated::
    .string "Em rendeixo…$"

SecretBase_Text_Trainer7PostBattle:
    .string "Ha estat molt divertit!\n"
    .string "Ara hauria d'anar a fer compres.$"

SecretBase_Text_Trainer7PreChampion:
    .string "M'encanta comprar decoracions\n"
    .string "i mobles.\p"
    .string "També m'encanta criar Pokémon\n"
    .string "igual de tant.$"

SecretBase_Text_Trainer3Intro:
    .string "Alguns fan les seves Bases Secretes\n"
    .string "en llocs difícils de trobar.\l"
    .string "Volen passar desapercebuts?\p"
    .string "Però com que m'has trobat,\n"
    .string "batallem?$"

SecretBase_Text_Trainer3AcceptBattle:
    .string "No em guanyaràs fàcilment!$"

SecretBase_Text_Trainer3DeclineBattle:
    .string "Oh… Potser estàs cansat de\n"
    .string "buscar aquest lloc?$"

SecretBase_Text_Trainer3Defeated::
    .string "He caigut…$"

SecretBase_Text_Trainer3PostBattle:
    .string "On és la teva Base Secreta?\n"
    .string "Hauria d'anar a visitar-te.$"

SecretBase_Text_Trainer3PreChampion:
    .string "Alguns fan les seves Bases Secretes\n"
    .string "en llocs difícils de trobar.\l"
    .string "Volen passar desapercebuts?$"

SecretBase_Text_Trainer8Intro:
    .string "M'han dit que pots obtenir\n"
    .string "decoracions de diverses maneres.\p"
    .string "Hauríem de fer una cursa per\n"
    .string "veure qui aconsegueix millors\l"
    .string "decoracions i mobles!\p"
    .string "Mentrestant, vols batallar?$"

SecretBase_Text_Trainer8AcceptBattle:
    .string "Aquesta és la meva Base Secreta.\n"
    .string "No puc perdre!$"

SecretBase_Text_Trainer8DeclineBattle:
    .string "Batallaré amb tu quan vulguis.$"

SecretBase_Text_Trainer8Defeated::
    .string "Eh?\n"
    .string "Acabo de perdre?$"

SecretBase_Text_Trainer8PostBattle:
    .string "No perdré a l'hora de col·leccionar\n"
    .string "decoracions. Torna a visitar-me!$"

SecretBase_Text_Trainer8PreChampion:
    .string "M'han dit que pots obtenir\n"
    .string "decoracions de diverses maneres.\p"
    .string "Hauríem de fer una cursa per\n"
    .string "veure qui aconsegueix millors\l"
    .string "decoracions i mobles!$"

SecretBase_Text_Trainer4Intro:
    .string "Vaig trobar un lloc que m'agradava\n"
    .string "i el vaig adornar amb les meves\l"
    .string "decoracions preferides.\p"
    .string "Crío el meu Pokémon preferit\n"
    .string "i en faig cada cop més fort.\p"
    .string "Això és el que faig.\n"
    .string "Vols batallar amb mi?$"

SecretBase_Text_Trainer4AcceptBattle:
    .string "Demostra'm de tot el que ets capaç!$"

SecretBase_Text_Trainer4DeclineBattle:
    .string "Suposo que hi ha moments en\n"
    .string "que no en tens ganes.$"

SecretBase_Text_Trainer4Defeated::
    .string "Ara sé exactament de tot\n"
    .string "el que ets capaç.$"

SecretBase_Text_Trainer4PostBattle:
    .string "Tots dos podem fer-nos més forts.\n"
    .string "Seguim endavant!$"

SecretBase_Text_Trainer4PreChampion:
    .string "Vaig trobar un lloc que m'agradava\n"
    .string "i el vaig adornar amb les meves\l"
    .string "decoracions preferides.\p"
    .string "Crío el meu Pokémon preferit\n"
    .string "i en faig cada cop més fort.\p"
    .string "Cada dia és un gran dia.$"

SecretBase_Text_Trainer9Intro:
    .string "Pots aprendre molt sobre el gust\n"
    .string "i el criteri de les persones\l"
    .string "pel tipus de decoracions que\l"
    .string "tenen i com les mostren.\p"
    .string "Que et sembla el meu gust?\n"
    .string "T'ha deixat sense paraules?\p"
    .string "Vols veure el meu gust en la batalla?$"

SecretBase_Text_Trainer9AcceptBattle:
    .string "Sense aguantar-se!$"

SecretBase_Text_Trainer9DeclineBattle:
    .string "Estaré encantat de demostrar\n"
    .string "el meu estil quan vulguis.$"

SecretBase_Text_Trainer9Defeated::
    .string "Tens un talent suprem!\n"
    .string "El teu poder sembla il·limitat…$"

SecretBase_Text_Trainer9PostBattle:
    .string "Que et sembla el meu estil?\n"
    .string "Continuaré polint-lo!$"

SecretBase_Text_Trainer9PreChampion:
    .string "Pots aprendre molt sobre el gust\n"
    .string "i el criteri de les persones\l"
    .string "pel tipus de decoracions que\l"
    .string "tenen i com les mostren.\p"
    .string "Que et sembla el meu gust?\n"
    .string "T'ha deixat sense paraules?$"
