ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Tens pensat endinsar-te\n"
	.string "aquí a dins?\p"
	.string "I si em portes Sal Shoal i\n"
	.string "Closques Shoal quan tornis?\p"
	.string "Puc fer-te alguna cosa bona si\n"
	.string "em portes els ingredients.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Si em portes quatre de cada,\n"
	.string "Sal Shoal i Closques Shoal,\l"
	.string "puc fer-te un Campanet Closca…\p"
	.string "Pots obtenir aquests ingredients\n"
	.string "cada dia.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, ei! Sal Shoal i Closques Shoal!\n"
	.string "I prou, a més!\p"
	.string "Vols que et faci\n"
	.string "un Campanet Closca?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Molt bé, doncs! Et faré\n"
	.string "un Campanet Closca ara mateix.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Llest! Fet!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Fes que un Pokémon el dugui.\n"
	.string "Li encantarà, segur.\p"
	.string "El tintineig del Campanet Closca…\n"
	.string "És simplement sublim!\p"
	.string "Pots obtenir els ingredients cada dia,\n"
	.string "així que puc fer-ne més.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Ah sí…\n"
	.string "Volia fer un Campanet Closca…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "No tens espai a la Motxilla\n"
	.string "si te'l faig ara.\p"
	.string "Hauries de fer espai i tornar\n"
	.string "per un Campanet Closca.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Aquí hi havia Sal Shoal.\n"
	.string "Però ara no hi ha res.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Aquí hi havia una Closca Shoal.\n"
	.string "Però ara no hi ha res.$"
