Route102_Text_CalvinIntro:
	.string "Si tens Pokémon, ets un Entrenador\n"

	.string "Pokémon oficial!\l"

	.string "No pots rebutjar el meu desafiament!$"


Route102_Text_CalvinDefeated:
	.string "Argh, he perdut…\n"

	.string "Hauria d'haver entrenat més…$"


Route102_Text_CalvinPostBattle:
	.string "Escolta, tu. Si ets fort,\n"

	.string "m'ho hauries d'haver dit abans!$"


Route102_Text_CalvinRegister:
	.string "He estat treballant dur des que\n"

	.string "et vaig veure.\p"

	.string "Vull tornar a combatre amb tu.\n"

	.string "Em registres al teu Pokénav?$"


Route102_Text_CalvinRegisterShort:
	.string "Vull tornar a combatre amb tu.\n"

	.string "Em registres al teu Pokénav?$"


Route102_Text_CalvinRematchIntro:
	.string "Des que vaig perdre contra tu,\n"

	.string "he entrenat els meus Pokémon.\l"

	.string "No pots rebutjar el meu desafiament!$"


Route102_Text_CalvinRematchDefeated:
	.string "Argh, he perdut…\n"

	.string "El meu entrenament no és correcte?$"


Route102_Text_CalvinRematchPostBattle:
	.string "Si et fas més fort,\n"

	.string "jo també em faré més fort.$"


Route102_Text_AllenIntro:
	.string "Acabes de fer-te Entrenador?\n"

	.string "Tots dos som principiants!$"


Route102_Text_AllenDefeated:
	.string "T'he desafiat perquè pensava\n"

	.string "que et podia guanyar…$"


Route102_Text_AllenPostBattle:
	.string "Encara no he guanyat cap cop…\n"

	.string "M'agradaria guanyar aviat…$"


Route102_Text_RickIntro:
	.string "Haha! Les mirades s'han creuat!\n"

	.string "T'atacaré amb els meus Pokémon Insecte!$"


Route102_Text_RickDefeated:
	.string "Au! Fora de combat!$"


Route102_Text_RickPostBattle:
	.string "Si creues la mirada amb un Entrenador,\n"

	.string "l'has de desafiar! És la norma!$"


Route102_Text_TianaIntro:
	.string "Seguiré guanyant per ser\n"

	.string "la millor Entrenadora.\p"

	.string "Ajuda'm a progressar!$"


Route102_Text_TianaDefeated:
	.string "He acabat fent progressar a tu…$"


Route102_Text_TianaPostBattle:
	.string "Per seguir guanyant, veig que haig\n"

	.string "d'atrapar més Pokémon.$"


Route103_Text_DaisyIntro:
	.string "Has sentit l'atracció de la nostra\n"

	.string "fragància reconfortant?$"


Route103_Text_DaisyDefeated:
	.string "No t'has deixat enganyar pel nostre\n"

	.string "aroma…$"


Route103_Text_DaisyPostBattle:
	.string "L'aromateràpia és una forma de\n"

	.string "guarició mental amb fragàncies.$"


Route103_Text_AmyIntro:
	.string "Amy: Soc l'Amy.\n"

	.string "I aquesta és la meva germaneta Liv.\l"

	.string "Combatim juntes!$"


Route103_Text_AmyDefeated:
	.string "Amy: Oh no, hem perdut.$"


Route103_Text_AmyPostBattle:
	.string "Amy: Has de pensar en moltes\n"

	.string "coses quan combats contra\l"

	.string "dos Entrenadors.$"


Route103_Text_AmyNotEnoughPokemon:
	.string "Amy: Oh, només tens un Pokémon\n"

	.string "amb tu.\l"

	.string "Així no pots combatre amb nosaltres.$"


Route103_Text_LivIntro:
	.string "Liv: Combatim juntes com un\n"

	.string "sol equip.$"


Route103_Text_LivDefeated:
	.string "Liv: Oh, hem perdut, germana…$"


Route103_Text_LivPostBattle:
	.string "Liv: Treballem perfectament juntes,\n"

	.string "la meva germana gran i jo…\p"

	.string "Però hem perdut igualment…$"


Route103_Text_AmyLivRegister:
	.string "Liv: De veritat, som molt millors…\n"

	.string "És cert! T'ho demostrarem!$"


Route103_Text_LivNotEnoughPokemon:
	.string "Liv: Si vols combatre amb nosaltres,\n"

	.string "has de tenir dos Pokémon!\l"

	.string "Si no, no és just!$"


Route103_Text_AmyRematchIntro:
	.string "Amy: Soc l'Amy.\n"

	.string "I aquesta és la meva germaneta Liv.\l"

	.string "Combatim juntes!$"


Route103_Text_AmyRematchDefeated:
	.string "Amy: Ohh!\n"

	.string "No hem pogut guanyar un altre cop…$"


Route103_Text_AmyRematchPostBattle:
	.string "Amy: Has de pensar en moltes\n"

	.string "coses quan combats contra\l"

	.string "dos Entrenadors.$"


Route103_Text_AmyRematchNotEnoughPokemon:
	.string "Amy: Oh, només tens un Pokémon\n"

	.string "amb tu.\l"

	.string "Així no pots combatre amb nosaltres.$"


Route103_Text_LivRematchIntro:
	.string "Liv: Combatim juntes com un\n"

	.string "sol equip.$"


Route103_Text_LivRematchDefeated:
	.string "Liv: Ohh, hem tornat a perdre…\n"

	.string "Germana…$"


Route103_Text_LivRematchPostBattle:
	.string "Liv: Treballem perfectament juntes,\n"

	.string "la meva germana gran i jo…\p"

	.string "Però per què hem tornat a perdre?$"


Route103_Text_LivRematchNotEnoughPokemon:
	.string "Liv: Si vols combatre amb nosaltres,\n"

	.string "has de tenir dos Pokémon!\l"

	.string "Si no, no és just!$"


Route103_Text_AndrewIntro:
	.string "Uf! El meu fil de pescar s'ha embolicat!\n"

	.string "Estic frustrat i de mal humor!\l"

	.string "Au va! Combat amb mi!$"


Route103_Text_AndrewDefeated:
	.string "Uf! He perdut!\n"

	.string "Ara estic encara més enfadat!$"


Route103_Text_AndrewPostBattle:
	.string "Uf, encara estic que bullo…\n"

	.string "Grrrrr…$"


Route103_Text_MiguelIntro:
	.string "El meu Pokémon és adorablement bonic!\n"

	.string "No siguis tímid, te'l mostraré!$"


Route103_Text_MiguelDefeated:
	.string "Oh, mare meva!\n"

	.string "El meu estimat Pokémon!$"


Route103_Text_MiguelPostBattle:
	.string "El meu Pokémon és adorable fins i\n"

	.string "tot quan està debilitat!$"


Route103_Text_MiguelRegister:
	.string "Faré que vinguis a veure el meu\n"

	.string "adorable Pokémon un altre cop!$"


Route103_Text_MiguelRematchIntro:
	.string "Ei, tu! El meu adorable Pokémon\n"

	.string "s'ha tornat encara més bonic!$"


Route103_Text_MiguelRematchDefeated:
	.string "Oh!\n"

	.string "El meu estimat Pokémon!$"


Route103_Text_MiguelRematchPostBattle:
	.string "Com més temps passo amb ell,\n"

	.string "més adorable es torna.$"


Route103_Text_PeteIntro:
	.string "Aquesta distància…\n"

	.string "Hauries de nedar-la!$"


Route103_Text_PeteDefeated:
	.string "Oh, molt bé!$"


Route103_Text_PetePostBattle:
	.string "Oh, ara t'entenc.\p"

	.string "Si tingués un Pokémon tan fidel,\n"

	.string "també voldria fer Surf amb ell!$"


Route103_Text_IsabelleIntro:
	.string "Vigila per on vas!\n"

	.string "Xocarem!$"


Route103_Text_IsabelleDefeated:
	.string "Ai…$"


Route103_Text_IsabellePostBattle:
	.string "Nedo malament i estava practicant…\n"

	.string "Perdona per quasi xocar amb tu.$"


Route103_Text_RhettIntro:
	.string "Uau!\n"

	.string "Com has entrat en un espai tan petit?$"


Route103_Text_RhettDefeated:
	.string "Uau!\n"

	.string "El nen és bo!$"


Route103_Text_RhettPostBattle:
	.string "T'agraden els espais estrets\n"

	.string "com aquest?$"


Route103_Text_MarcosIntro:
	.string "El so de la meva guitarra t'ha atret?$"


Route103_Text_MarcosDefeated:
	.string "El meu espectacle en solitari\n"

	.string "s'ha arruïnat…$"


Route103_Text_MarcosPostBattle:
	.string "Tocava la guitarra on hi havia poca\n"

	.string "gent, però s'han aplegat molts fans.\p"

	.string "Potser hauria de fer-me'n professional.$"


Route104_Text_GinaIntro:
	.string "Gina: Va, combat amb els nostres\n"

	.string "Pokémon!$"


Route104_Text_GinaDefeat:
	.string "Gina: Perdre em fa ràbia!$"


Route104_Text_GinaPostBattle:
	.string "Gina: Ets fort!\n"

	.string "Hem d'entrenar molt més!$"


Route104_Text_GinaNotEnoughMons:
	.string "Gina: Oh? Només un Pokémon?\n"

	.string "Doncs no combatrem amb tu.\p"

	.string "Si només té un Pokémon, se sentirà\n"

	.string "sol. No estaria bé.$"


Route104_Text_MiaIntro:
	.string "Mia: Som bessones, així que\n"

	.string "combatim juntes.$"


Route104_Text_MiaDefeat:
	.string "Mia: Hem combat juntes, però\n"

	.string "hem perdut totes dues…$"


Route104_Text_MiaPostBattle:
	.string "Mia: Entrenarem els Pokémon més\n"

	.string "per ser fortes com tu.$"


Route104_Text_MiaNotEnoughMons:
	.string "Mia: Vols combatre amb nosaltres?\p"

	.string "No pot ser si no tens dos Pokémon\n"

	.string "amb tu.\l"

	.string "Som massa fortes per a tu!$"


Route104_Text_IvanIntro:
	.string "Per què guardar el secret?\n"

	.string "Soc l'expert en Pokémon d'Aigua!\p"

	.string "Eh?\n"

	.string "No em coneixes?$"


Route104_Text_IvanDefeat:
	.string "Creia que no era dolent, si és que\n"

	.string "puc dir-ho, però sembla que no…$"


Route104_Text_IvanPostBattle:
	.string "Em vaig enganxar massa a la pesca.\n"

	.string "Vaig oblidar criar els meus Pokémon…$"


Route104_Text_BillyIntro:
	.string "Deixar petjades a la sorra és\n"

	.string "molt divertit!$"


Route104_Text_BillyDefeat:
	.string "Uaah! M'ha entrat sorra a les\n"

	.string "sabatilles! Tota rascosa!$"


Route104_Text_BillyPostBattle:
	.string "Vull deixar petjades a la sorra\n"

	.string "a tot arreu, però desapareixen\l"

	.string "de seguida…$"


Route104_Text_HaleyIntro:
	.string "Hauria de…\n"

	.string "O no hauria de…?\p"

	.string "Va, sí, combat!$"


Route104_Text_HaleyDefeat:
	.string "No hauria d'haver combat…$"


Route104_Text_HaleyPostBattle:
	.string "Si has de decidir i deixes que\n"

	.string "un altre triï per tu,\l"

	.string "te'n penediràs, passi el que\l"

	.string "passi.$"


Route104_Text_HaleyRegister1:
	.string "Ets fort, però hauria de registrar-te\n"

	.string "al meu Pokénav?\l"

	.string "Potser no hauria…\p"

	.string "Va, sí, et registraré!$"


Route104_Text_HaleyRegister2:
	.string "Ets fort, però hauria de registrar-te\n"

	.string "al meu Pokénav?\l"

	.string "Potser no hauria…\p"

	.string "Va, sí, et registraré!$"


Route104_Text_HaleyRematchIntro:
	.string "Vine, combat amb mi!$"


Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"

	.string "Pensava que podia guanyar…$"


Route104_Text_HaleyPostRematch:
	.string "He decidit combatre, així que\n"

	.string "puc acceptar la derrota amb gràcia.\p"

	.string "Però estic disgustada igualment!$"


Route104_Text_WinstonIntro:
	.string "Oh, és clar, accepto el teu repte.\n"

	.string "Tinc molts diners.$"


Route104_Text_WinstonDefeat:
	.string "Per què no he pogut guanyar?$"


Route104_Text_WinstonPostBattle:
	.string "Hi ha coses que els diners no compren.\n"

	.string "Això són els Pokémon…$"


Route104_Text_WinstonRegister1:
	.string "Hm?\n"

	.string "Ah, tens un Pokénav.\p"

	.string "Et registraré amb gust.\n"

	.string "Al cap i a la fi, tinc molts diners.$"


Route104_Text_WinstonRegister2:
	.string "Hm?\n"

	.string "Ah, tens un Pokénav.\p"

	.string "Et registraré amb gust.\n"

	.string "Al cap i a la fi, tinc molts diners.$"


Route104_Text_WinstonRematchIntro:
	.string "Des que vaig perdre contra tu, he\n"

	.string "après moltes coses sobre Pokémon.$"


Route104_Text_WinstonRematchDefeat:
	.string "He tornat a perdre?\n"

	.string "Per què no puc guanyar?$"


Route104_Text_WinstonPostRematch:
	.string "Soc fabulosament ric, però no\n"

	.string "aconsegueixo guanyar amb Pokémon…\p"

	.string "El món Pokémon és tan profund…$"


Route104_Text_CindyIntro:
	.string "El destí ens ha fet trobar.\n"

	.string "Vols un combat?$"


Route104_Text_CindyDefeat:
	.string "Oh, vaja!$"


Route104_Text_CindyPostBattle:
	.string "“Hola” és el principi de “adéu”.\n"

	.string "Espero que ens tornem a veure.$"


Route104_Text_CindyRegister1:
	.string "Hola, ens tornem a trobar.\p"

	.string "Sembla que ens atraiem.\n"

	.string "Registrem-nos als nostres Pokénavs.$"


Route104_Text_CindyRegister2:
	.string "Hauríem de commemorar com\n"

	.string "ens atraiem.\p"

	.string "Registrem-nos als nostres\n"

	.string "Pokénavs.$"


Route104_Text_CindyRematchIntro:
	.string "Hola, ens tornem a trobar.\n"

	.string "Vols un combat?$"


Route104_Text_CindyRematchDefeat:
	.string "Oh, vaja…\n"

	.string "Ho he donat tot…$"


Route104_Text_CindyPostRematch:
	.string "“Hola” és el principi de “adéu”.\n"

	.string "Espero que ens tornem a veure.$"


Route104_Text_DarianIntro:
	.string "He pescat un Pokémon dur de pelar!\p"

	.string "Té una qualitat màgica!\n"

	.string "Segur que és molt dur, sí senyor!$"


Route104_Text_DarianDefeat:
	.string "Però què…$"


Route104_Text_DarianPostBattle:
	.string "Ei, Magikarp, no fas honor al teu\n"

	.string "nom, oi?$"


Route105_Text_FosterIntro:
	.string "Diuen que hi ha una roca mística\n"

	.string "per aquí.\l"

	.string "En saps alguna cosa?$"


Route105_Text_FosterDefeated:
	.string "Pensava massa en la roca, mentre\n"

	.string "els meus Pokémon eren dèbils…$"


Route105_Text_FosterPostBattle:
	.string "Puc passar hores mirant una bona\n"

	.string "roca sense cansar-me'n.$"


Route105_Text_LuisIntro:
	.string "Uf! Pensava que un nen s'ofegava\n"

	.string "quan t'he vist.\p"

	.string "Sembla que estàs bé, què tal\n"

	.string "un combat?$"


Route105_Text_LuisDefeated:
	.string "Glub… Glub…$"


Route105_Text_LuisPostBattle:
	.string "Si t'ofegues, el senyal és moure\n"

	.string "un braç cap a la platja.$"


Route105_Text_DominikIntro:
	.string "Nedar pel mar blau profund…\n"

	.string "És la millor sensació!$"


Route105_Text_DominikDefeated:
	.string "He perdut…\n"

	.string "Ara estic deprimit…$"


Route105_Text_DominikPostBattle:
	.string "Per què el mar és blau?\p"

	.string "Ho vaig aprendre al Museu\n"

	.string "de Slateport, però ho he oblidat.$"


Route105_Text_BeverlyIntro:
	.string "El meu cos pesa menys a l'aigua.\n"

	.string "És com si hagués aprimat!$"


Route105_Text_BeverlyDefeated:
	.string "Estic flotant…$"


Route105_Text_PostBattle:
	.string "El teu pes es redueix a una desena\n"

	.string "part a l'aigua.\p"

	.string "Això vol dir que jo…\n"

	.string "Ei! No et diré el meu pes!$"


Route105_Text_ImaniIntro:
	.string "El cel blau, blau…\n"

	.string "El mar immens…\l"

	.string "Tot és tan tranquil…$"


Route105_Text_ImaniDefeated:
	.string "He perdut mentre descansava!$"


Route105_Text_ImaniPostBattle:
	.string "Vull que em diguin que és relaxant\n"

	.string "estar amb mi. Hihi.$"


Route105_Text_AndresIntro:
	.string "Estic convençut que el mar amaga\n"

	.string "secrets.$"


Route105_Text_AndresDefeated:
	.string "Sí…\n"

	.string "No soc bo combatent…$"


Route105_Text_AndresPostBattle:
	.string "Segur que hi ha molts secrets per\n"

	.string "descobrir als mars del món.\p"

	.string "Penso trobar-los tots!$"


Route105_Text_AndresRegister:
	.string "Eh? Soc tan dèbil, però em vols\n"

	.string "registrar al teu Pokénav?$"


Route105_Text_AndresRematchIntro:
	.string "T'he dit que soc dèbil…\n"

	.string "Segur que vols fer-ho?$"


Route105_Text_AndresRematchDefeated:
	.string "Sí…\n"

	.string "No creia que pogués guanyar.$"


Route105_Text_AndresRematchPostBattle:
	.string "Potser soc dèbil combatent, però\n"

	.string "la meva passió per explorar és\l"

	.string "imbatible.\p"

	.string "Viatjaré per tots els mars\n"

	.string "del món!$"


Route105_Text_JosueIntro:
	.string "Estic esgotat de nedar.\n"

	.string "No hi estic acostumat.\p"

	.string "Necessito un combat per canviar!$"


Route105_Text_JosueDefeated:
	.string "He perdut perquè he combat al mar.$"


Route105_Text_JosuePostBattle:
	.string "Sí, per a mi, el cel és molt millor\n"

	.string "que el mar.$"


Route106_Text_ElliotIntro:
	.string "Què prefereixes, pescar al mar\n"

	.string "o al riu?$"


Route106_Text_ElliotDefeated:
	.string "Com en la pesca d'altura, he perdut\n"

	.string "espectacularment!$"


Route106_Text_ElliotPostBattle:
	.string "Pescar és genial tant al mar com\n"

	.string "al riu.\l"

	.string "Hi estàs d'acord, oi?$"


Route106_Text_ElliotRegister:
	.string "Pescar és genial, però combatre\n"

	.string "també. Ens podem tornar a veure?$"


Route106_Text_ElliotRematchIntro:
	.string "He pescat molts Pokémon.\n"

	.string "Et mostraré un combat impressionant!$"


Route106_Text_ElliotRematchDefeated:
	.string "He tornat a perdre espectacularment!$"


Route106_Text_ElliotRematchPostBattle:
	.string "Guanyis o perdis, els Pokémon\n"

	.string "són genials!\l"

	.string "Hi estàs d'acord, oi?$"


Route106_Text_NedIntro:
	.string "Què fa la gent quan necessita anar\n"

	.string "al lavabo?\p"

	.string "I si pico un peix gros mentre soc\n"

	.string "al lavabo? No puc anar-hi…$"


Route106_Text_NedDefeated:
	.string "He perdut perquè estic aguantant\n"

	.string "les ganes d'anar al lavabo…$"


Route106_Text_NedPostBattle:
	.string "Ai, no! Tinc la sensació que picarà\n"

	.string "un peix gros!$"


Route106_Text_DouglasIntro:
	.string "Hahaha! Corro malament, però a\n"

	.string "l'aigua no m'atraparàs!$"


Route106_Text_DouglasDefeated:
	.string "Em rendeixo!$"


Route106_Text_DouglasPostBattle:
	.string "En una cursa de natació no perdria…$"


Route106_Text_KylaIntro:
	.string "El mar és el meu pati. No seré\n"

	.string "suau perquè siguis un nen!$"


Route106_Text_KylaDefeated:
	.string "Has anat suau amb mi, per\n"

	.string "casualitat?$"


Route106_Text_KylaPostBattle:
	.string "Deixar-se portar per les ones…\n"

	.string "M'encanta! Per què no ho proves?$"


Route107_Text_DarrinIntro:
	.string "Badall…\p"

	.string "M'he degut adormir mentre\n"

	.string "flotava amb les ones.$"


Route107_Text_DarrinDefeated:
	.string "Ahaha, he perdut…\n"

	.string "Crec que faré una becaina…$"


Route107_Text_DarrinPostBattle:
	.string "Flotar i ser bressolat per les ones\n"

	.string "és com dormir en un llit ben\l"

	.string "còmode.$"


Route107_Text_TonyIntro:
	.string "El mar és com el meu pati.\n"

	.string "Combatim!$"


Route107_Text_TonyDefeated:
	.string "He perdut a casa meva…\n"

	.string "Estic en xoc!$"


Route107_Text_TonyPostBattle:
	.string "Nedo pels mars amb el cor ple\n"

	.string "de somnis…\p"

	.string "És una cançó!\n"

	.string "En fi, segueixo nedant.$"


Route107_Text_TonyRegister:
	.string "M'has deixat bocabadat!\n"

	.string "Bé, perquè no m'oblidis…$"


Route107_Text_TonyRematchIntro:
	.string "Nedant pel mar immens,\n"

	.string "el meu Pokémon s'ha fet més fort!$"


Route107_Text_TonyRematchDefeated:
	.string "Quin xoc!\p"

	.string "El meu Pokémon s'ha fet més fort,\n"

	.string "però jo soc dèbil com a Entrenador!$"


Route107_Text_TonyRematchPostBattle:
	.string "El que aprens en combat et fa\n"

	.string "un Entrenador més fort.\l"

	.string "Les ones m'ho han ensenyat.$"


Route107_Text_DeniseIntro:
	.string "Coneixes un poblet que es diu\n"

	.string "Dewford?$"


Route107_Text_DeniseDefeated:
	.string "Odio això!$"


Route107_Text_DenisePostBattle:
	.string "Una dita estranya s'ha posat de moda\n"

	.string "al Saló Dewford.$"


Route107_Text_BethIntro:
	.string "Volies combatre amb mi?\n"

	.string "Endavant, va!$"


Route107_Text_BethDefeated:
	.string "No he estat a la teva alçada.$"


Route107_Text_BethPostBattle:
	.string "Crec que seguiràs millorant.\n"

	.string "Jo també ho intentaré!$"


Route107_Text_LisaIntro:
	.string "Lisa: Et desafiem com a germana\n"

	.string "i germà!$"


Route107_Text_LisaDefeated:
	.string "Lisa: Impressionant.\n"

	.string "Ets d'un altre nivell de força.$"


Route107_Text_LisaPostBattle:
	.string "Lisa: Tens amics que vaguessin a\n"

	.string "la platja amb tu?$"


Route107_Text_LisaNotEnoughPokemon:
	.string "Lisa: Si vols combatre amb nosaltres,\n"

	.string "porta més Pokémon.$"


Route107_Text_RayIntro:
	.string "Ray: Sempre combatim Pokémon,\n"

	.string "la meva germana i jo.\p"

	.string "Sempre perdo, però et podem\n"

	.string "guanyar 2 contra 2!$"


Route107_Text_RayDefeated:
	.string "Ray: Uau, ets d'un nivell superior\n"

	.string "al nostre!$"


Route107_Text_RayPostBattle:
	.string "Ray: La meva germana em va donar\n"

	.string "el meu Pokémon.\l"

	.string "Jo el vaig criar, i ara és el meu\l"

	.string "company important!$"


Route107_Text_RayNotEnoughPokemon:
	.string "Ray: Si vols combatre amb nosaltres,\n"

	.string "porta més Pokémon!$"


Route107_Text_CamronIntro:
	.string "Estic enmig d'un triatló,\n"

	.string "però no estic gens cansat!$"


Route107_Text_CamronDefeated:
	.string "Això m'ha esgotat…$"


Route107_Text_CamronPostBattle:
	.string "Encara em queda nedar i córrer.\p"

	.string "Podré aguantar?$"


Route108_Text_JeromeIntro:
	.string "El meu somni és nedar pels set mars\n"

	.string "del món!$"


Route108_Text_JeromeDefeated:
	.string "Així no podré nedar els set mars…$"


Route108_Text_JeromePostBattle:
	.string "Jugar amb Pokémon marins és un dels\n"

	.string "plaers de nedar!$"


Route108_Text_MatthewIntro:
	.string "Ei! També vas al Vaixell\n"

	.string "Abandonat?$"


Route108_Text_MatthewDefeated:
	.string "M'enfonso!\n"

	.string "Glub… Glub…$"


Route108_Text_MatthewPostBattle:
	.string "Hi ha gent que fins i tot entra dins\n"

	.string "del Vaixell Abandonat.$"


Route108_Text_TaraIntro:
	.string "El meu mentider del xicot em va dir\n"

	.string "que estic molt bé en biquini…$"


Route108_Text_TaraDefeated:
	.string "Oh, vaja!$"


Route108_Text_TaraPostBattle:
	.string "Encara que sigui mentida, m'encanta\n"

	.string "que em diguin que estic molt bé…\l"

	.string "Les noies som tan complicades…$"


Route108_Text_MissyIntro:
	.string "M'encanta el mar!\n"

	.string "Oblido tots els meus mals quan nedo!$"


Route108_Text_MissyDefeated:
	.string "Quan perdo un combat, em poso\n"

	.string "molt estressada!$"


Route108_Text_MissyPostBattle:
	.string "Allibera l'estrès nedant!\n"

	.string "És molt sa!$"


Route108_Text_CoryIntro:
	.string "M'encanten els Pokémon d'Aigua.\n"

	.string "I els altres Pokémon també!$"


Route108_Text_CoryDefeated:
	.string "Buaaa! He perdut!\n"

	.string "Buaaa! Buaaa!$"


Route108_Text_CoryPostBattle:
	.string "Cridar em va bé!\n"

	.string "M'anima!$"


Route108_Text_CoryRegister:
	.string "M'encanten els Entrenadors forts!\n"

	.string "Registra'm al teu Pokénav!$"


Route108_Text_CoryRematchIntro:
	.string "Guanyi o perdi, m'encanta combatre\n"

	.string "al mar!$"


Route108_Text_CoryRematchDefeated:
	.string "Buaaa! He tornat a perdre!\n"

	.string "Buaaa! Buaaa!$"


Route108_Text_CoryRematchPostBattle:
	.string "Si tens un repte davant,\n"

	.string "prova de cridar al mar!$"


Route108_Text_CarolinaIntro:
	.string "Estic molt orgullosa dels meus\n"

	.string "Pokémon. Un combat ràpid!$"


Route108_Text_CarolinaDefeated:
	.string "Això no ha estat gens maco.$"


Route108_Text_CarolinaPostBattle:
	.string "Com que estic al mar, no em faria\n"

	.string "res posar-me un biquini rosa…$"


Route109_Text_DavidIntro:
	.string "Hiya! Mira els meus abdominals!\n"

	.string "Això és estar en forma!$"


Route109_Text_DavidDefeated:
	.string "Aiya!\n"

	.string "He fallat!$"


Route109_Text_DavidPostBattle:
	.string "Hiya!\p"

	.string "Els meus abdominals esculpits no\n"

	.string "tenen res a veure amb els combats!$"


Route109_Text_AliceIntro:
	.string "Vas ben protegit contra el sol?$"


Route109_Text_AliceDefeated:
	.string "Au, au, au!$"


Route109_Text_AlicePostBattle:
	.string "Les galtes són el que es crema més!$"


Route109_Text_HueyIntro:
	.string "He fondejat als ports de tot el món,\n"

	.string "però Slateport és el millor.$"


Route109_Text_HueyDefeated:
	.string "Ets el millor!$"


Route109_Text_HueyPostBattle:
	.string "Al millor port hi havia el millor\n"

	.string "Entrenador…$"


Route109_Text_EdmondIntro:
	.string "Urrrrppp…\n"

	.string "Combat? Amb mi?$"


Route109_Text_EdmondDefeated:
	.string "Urp… Ooooooohhhhhh…\n"

	.string "Urrrrpppp…$"


Route109_Text_EdmondPostBattle:
	.string "Normalment soc més fort!\n"

	.string "Estic marejat com un gos!\p"

	.string "I soc Mariner, però…$"


Route109_Text_RickyIntro:
	.string "Tinc set… M'aniria bé una Soda Pop\n"

	.string "a la Casa de la Platja…$"


Route109_Text_RickyDefeated:
	.string "Ai…$"


Route109_Text_RickyPostBattle:
	.string "Estic famolenc… El meu flotador\n"

	.string "sembla un dònut gegant…$"


Route109_Text_RickyRegister:
	.string "Vols tornar a combatre quan no\n"

	.string "tingui tanta set?$"


Route109_Text_RickyRematchIntro:
	.string "Tinc gana, però tinc prou energia\n"

	.string "per a un combat!$"


Route109_Text_RickyRematchDefeated:
	.string "He perdut…\n"

	.string "És perquè tinc gana…$"


Route109_Text_RickyRematchPostBattle:
	.string "Quan menges a la platja, tot sembla\n"

	.string "que té una mica més de gust.$"


Route109_Text_LolaIntro:
	.string "Trobes que un para-sol de platja\n"

	.string "sembla una flor gegant?$"


Route109_Text_LolaDefeated:
	.string "Mamà!$"


Route109_Text_LolaPostBattle:
	.string "Si mires la platja des del cel,\n"

	.string "sembla un gran jardí de flors!$"


Route109_Text_LolaRegister:
	.string "Jo?\n"

	.string "Soc aquí cada dia!$"


Route109_Text_LolaRematchIntro:
	.string "No tornaré a perdre contra tu!\n"

	.string "Per això tinc el meu flotador!$"


Route109_Text_LolaRematchDefeated:
	.string "Mamà!$"


Route109_Text_LolaRematchPostBattle:
	.string "Si tinc un flotador, la meva\n"

	.string "simpatia i la del meu Pokémon puja!$"


Route109_Text_AustinaIntro:
	.string "No sé nedar sense flotador,\n"

	.string "però no perdré a Pokémon!$"


Route109_Text_AustinaDefeated:
	.string "He perdut pel flotador?$"


Route109_Text_AustinaPostBattle:
	.string "El meu flotador és un accessori.\n"

	.string "No em poden veure sense ell.$"


Route109_Text_GwenIntro:
	.string "Ei, gran Entrenador.\n"

	.string "Vols combatre amb mi?$"


Route109_Text_GwenDefeated:
	.string "Oh, ets fort.$"


Route109_Text_GwenPostBattle:
	.string "Com t'has fet tan fort?$"


Route109_Text_CarterIntro:
	.string "Uahaha! Aquest tio pescarà\n"

	.string "un peix gros!$"


Route109_Text_CarterDefeated:
	.string "Aquest tio acaba de perdre'n un…$"


Route109_Text_CarterPostBattle:
	.string "Aquest tio creu que ets un peix\n"

	.string "gros. No, un futur peix gros!$"


Route109_Text_PaulIntro:
	.string "Paul: Vaja, això ens trenca el rotllo.\p"

	.string "M'agradaria que no molestessis\n"

	.string "la nostra estona preciosa.$"


Route109_Text_PaulDefeated:
	.string "Paul: Em rendeixo.$"


Route109_Text_PaulPostBattle:
	.string "Paul: No diguis a ningú que som\n"

	.string "aquí.\l"

	.string "Aquest és el nostre món privat!$"


Route109_Text_PaulNotEnoughPokemon:
	.string "Paul: Estem bogament enamorats.\n"

	.string "Per això fem combatre els nostres\l"

	.string "Pokémon junts.$"


Route109_Text_MelIntro:
	.string "Mel: Estem, com, totalment\n"

	.string "enamorats.\l"

	.string "El nostre amor escalfa tot Hoenn!$"


Route109_Text_MelDefeated:
	.string "Mel: Hem perdut, i és culpa meva!\n"

	.string "Paul m'odiarà!$"


Route109_Text_MelPostBattle:
	.string "Mel: Paul, estàs enfadat amb mi?\n"

	.string "Sisplau, no t'enfadis.$"


Route109_Text_MelNotEnoughPokemon:
	.string "Mel: Estem, com, profundament\n"

	.string "enamorats.\l"

	.string "Per això fem combatre els nostres\l"

	.string "Pokémon junts.$"


Route109_Text_ChandlerIntro:
	.string "Tatxan! Veus?\n"

	.string "El meu flotador és rodó!$"


Route109_Text_ChandlerDefeated:
	.string "Oh, oh!\n"

	.string "Llàstima!$"


Route109_Text_ChandlerPostBattle:
	.string "Fins i tot després de mostrar-te\n"

	.string "el meu flotador rodó…$"


Route109_Text_HaileyIntro:
	.string "No sé nedar, així que faig veure\n"

	.string "que nedo.$"


Route109_Text_HaileyDefeated:
	.string "Ho sabia!\n"

	.string "No creia que poguéssim guanyar.$"


Route109_Text_HaileyPostBattle:
	.string "Quan aprengui a nedar, crec que\n"

	.string "el meu Pokémon serà més fort.$"


Route109_Text_ElijahIntro:
	.string "Per a un tio tan mascle com jo,\n"

	.string "aquest Pokémon és perfecte!$"


Route109_Text_ElijahDefeated:
	.string "Soc genial fins i tot perdent, eh?$"


Route109_Text_ElijahPostBattle:
	.string "Per a un tio tan mascle com jo,\n"

	.string "un port és l'escenari perfecte!\p"

	.string "Aniré cap a Slateport.$"


Route110_Text_JacobIntro:
	.string "Ep! Vigila!\n"

	.string "Veig que no estàs avesat a la Bici.$"


Route110_Text_JacobDefeated:
	.string "Ep!\n"

	.string "Han fallat els frens!$"


Route110_Text_JacobPostBattle:
	.string "Punxades i problemes de frens\n"

	.string "poden causar lesions greus!\l"

	.string "Revisa bé la teva Bici!$"


Route110_Text_AnthonyIntro:
	.string "Ei, tu!\n"

	.string "Pots seguir el meu ritme?$"


Route110_Text_AnthonyDefeated:
	.string "Xoc i flames!$"


Route110_Text_AnthonyPostBattle:
	.string "La velocitat sola no em farà guanyar.\n"

	.string "Ho he de reconsiderar…$"


Route110_Text_BenjaminIntro:
	.string "No t'espantis si la Bici va ràpid!$"


Route110_Text_BenjaminDefeated:
	.string "No m'hauria d'espantar durant\n"

	.string "els combats Pokémon…$"


Route110_Text_BenjaminPostBattle:
	.string "No cal estressar-se ni patir.\n"

	.string "Calma. Hi ha temps de sobres.$"


Route110_Text_BenjaminRegister:
	.string "Seguiré endavant sense estressar-me.\n"

	.string "Avisa'm si t'animes!$"


Route110_Text_BenjaminRematchIntro:
	.string "No vas una mica massa ràpid?\n"

	.string "Tranquil·litza't i combatim.$"


Route110_Text_BenjaminRematchDefeated:
	.string "No m'he espantat, però he perdut…$"


Route110_Text_BenjaminRematchPostBattle:
	.string "No cal estressar-se ni patir.\n"

	.string "Calma. Hi ha temps de sobres.$"


Route110_Text_JasmineIntro:
	.string "He pedalt sense parar.\n"

	.string "Les meves cuixes són de pedra!$"


Route110_Text_JasmineDefeated:
	.string "Em preocupen les rampes…$"


Route110_Text_JasminePostBattle:
	.string "Oh, tens algunes Medalles de Gimnàs?\n"

	.string "Amb raó ets tan fort!$"


Route110_Text_EdwardIntro:
	.string "He previst les teves intencions!\n"

	.string "És impossible que perdi!$"


Route110_Text_EdwardDefeated:
	.string "No vaig preveure la meva derrota!$"


Route110_Text_EdwardPostBattle:
	.string "Veig el teu futur…\p"

	.string "Hmm…\n"

	.string "Veig una llum brillant…$"


Route110_Text_JaclynIntro:
	.string "Ahahahaha!\n"

	.string "T'enlluerno amb les meves meravelles!$"


Route110_Text_JaclynDefeated:
	.string "He perdut meravellosament!$"


Route110_Text_JaclynPostBattle:
	.string "Has guanyat només perquè ha estat\n"

	.string "un miracle! Sí, un miracle!\l"

	.string "No creguis que guanyaràs sempre!$"


Route110_Text_EdwinIntro:
	.string "Puc veure els teus Pokémon?\n"

	.string "Només una ullada, sisplau?$"


Route110_Text_EdwinDefeated:
	.string "Volia completar la meva\n"

	.string "col·lecció…$"


Route110_Text_EdwinPostBattle:
	.string "Quan veig un Pokémon que no conec,\n"

	.string "s'encén la meva passió col·leccionista!$"


Route110_Text_EdwinRegister:
	.string "També m'agrada col·leccionar\n"

	.string "registres de Match Call…$"


Route110_Text_EdwinRematchIntro:
	.string "Ei, has atrapat Pokémon nous?\p"

	.string "Puc veure els teus Pokémon?\n"

	.string "Només una ullada, sisplau?$"


Route110_Text_EdwinRematchDefeated:
	.string "Els teus Pokémon…\n"

	.string "T'enveig.$"


Route110_Text_EdwinRematchPostBattle:
	.string "Oh, vull fer meus tots els Pokémon\n"

	.string "rars!$"


Route110_Text_DaleIntro:
	.string "Ei!\n"

	.string "No t'acostis per darrere així!$"


Route110_Text_DaleDefeated:
	.string "He perdut!\n"

	.string "Maleït sigui!$"


Route110_Text_DalePostBattle:
	.string "Pescar és tot concentració.\n"

	.string "T'has de fixar en el flotador.$"


Route110_Text_IsabelIntro:
	.string "Ahahaha! Aniria a tot arreu per\n"

	.string "lluir els meus adorables Pokémon.$"


Route110_Text_IsabelDefeated:
	.string "Vaja, això no pot ser.$"


Route110_Text_IsabelPostBattle:
	.string "Potser hauria de lluir els meus\n"

	.string "Pokémon al Club de Fans.$"


Route110_Text_IsabelRegister:
	.string "Ni de bon tros he mostrat tot el\n"

	.string "que puc fer amb els meus Pokémon.\p"

	.string "Et faré el meu públic captiu\n"

	.string "tan sovint com pugui!$"


Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! Estaré encantada de\n"

	.string "lluir els meus Pokémon sempre!$"


Route110_Text_IsabelRematchDefeated:
	.string "Vaja, això no pot ser.$"


Route110_Text_IsabelRematchPostBattle:
	.string "No crec que pugui deixar de lluir\n"

	.string "els meus Pokémon.\p"

	.string "Però combatre també m'agrada!$"


Route110_Text_TimmyIntro:
	.string "He trobat Pokémon ben guais a\n"

	.string "l'herba d'aquí!$"


Route110_Text_TimmyDefeated:
	.string "Ser guai no és prou per guanyar…$"


Route110_Text_TimmyPostBattle:
	.string "És difícil combatre amb Pokémon\n"

	.string "que acabes d'atrapar.$"


Route110_Text_AlyssaIntro:
	.string "He caigut del Pont Ciclable…\p"

	.string "Superaré la vergonya combatent\n"

	.string "amb tu!$"


Route110_Text_AlyssaDefeated:
	.string "Vaja!\n"

	.string "He acabat perdent!$"


Route110_Text_AlyssaPostBattle:
	.string "Caure… Perdre…\n"

	.string "Quina humiliació!$"


Route110_Text_JosephIntro:
	.string "Au! A tota pastilla! Si no t'enganxes\n"

	.string "al ritme, et quedaràs enrere!$"


Route110_Text_JosephDefeated:
	.string "T'has enganxat bé al ritme…$"


Route110_Text_JosephPostBattle:
	.string "Això no em tirarà avall!\n"

	.string "Perdre m'ha fet millor persona!$"


Route110_Text_KalebIntro:
	.string "Quan els Pokémon monos s'ajuden…\n"

	.string "No hi ha res més adorable!$"


Route110_Text_KalebDefeated:
	.string "No tens compassió ni pietat?$"


Route110_Text_KalebPostBattle:
	.string "Va, va, ho heu fet el millor que\n"

	.string "heu pogut, boniconets meus.$"


Route111_Text_DrewIntro:
	.string "Ei! Les Go-Goggles et queden bé.\n"

	.string "Però crec que a mi em queden millor.\p"

	.string "Decidim a qui li queden millor\n"

	.string "amb un combat!$"


Route111_Text_DrewDefeat:
	.string "No veia pels costats per culpa\n"

	.string "de les Go-Goggles.$"


Route111_Text_DrewPostBattle:
	.string "Les Go-Goggles permeten travessar\n"

	.string "les tempestes de sorra.\l"

	.string "Això em fa feliç!$"


Route111_Text_HeidiIntro:
	.string "Faig un pícnic al desert.\p"

	.string "Sempre trobes un Entrenador,\n"

	.string "així que gaudeixo d'un combat!$"


Route111_Text_HeidiDefeat:
	.string "Ohhh! Ets dolent!$"


Route111_Text_HeidiPostBattle:
	.string "Quan combats en una tempesta de\n"

	.string "sorra, vigila els PS del Pokémon.\p"

	.string "Pot caure si no hi pares atenció!$"


Route111_Text_BeauIntro:
	.string "Portar les Go-Goggles em fa sentir\n"

	.string "com un superheroi.\l"

	.string "Ara ningú no em pot guanyar!$"


Route111_Text_BeauDefeat:
	.string "No puc guanyar només amb esperit…$"


Route111_Text_BeauPostBattle:
	.string "Algun dia seré un heroi de veritat.\n"

	.string "Treballaré més per fer-me\l"

	.string "més fort amb els meus Pokémon.$"


Route111_Text_BeckyIntro:
	.string "He sentit que es troben fòssils\n"

	.string "al desert. On deuen ser?$"


Route111_Text_BeckyDefeat:
	.string "M'he quedat curt…$"


Route111_Text_BeckyPostBattle:
	.string "Si troben fòssils al desert,\n"

	.string "deu haver estat un mar abans.$"


Route111_Text_DustyIntro:
	.string "Fa trenta anys que busco ruïnes\n"

	.string "antigues!\l"

	.string "Se'm desafia?$"


Route111_Text_DustyDefeat:
	.string "Mentre buscava ruïnes,\n"

	.string "no he buscat Pokémon forts.$"


Route111_Text_DustyPostBattle:
	.string "Fa trenta anys que busco ruïnes\n"

	.string "antigues!\p"

	.string "No, espera, eren quaranta anys?\n"

	.string "Quants eren?$"


Route111_Text_DustyRegister:
	.string "No he buscat cap Pokémon fort.\p"

	.string "Però, per alguna raó, m'agraden\n"

	.string "molt els Pokénavs.$"


Route111_Text_DustyRematchIntro:
	.string "Fa trenta anys que busco ruïnes\n"

	.string "antigues!\p"

	.string "No, espera, eren quaranta?\n"

	.string "En fi, se'm desafia?$"


Route111_Text_DustyRematchDefeat:
	.string "No he trobat ruïnes ni Pokémon\n"

	.string "forts…$"


Route111_Text_DustyPostRematch:
	.string "Fa trenta anys que busco ruïnes\n"

	.string "antigues!\p"

	.string "No, espera, eren quaranta\n"

	.string "anys que busco?\p"

	.string "Hmm… Podrien ser cinquanta…\n"

	.string "Quant de temps fa que hi soc?$"


Route111_Text_TravisIntro:
	.string "Estic ple d'energia!\n"

	.string "I el meu Pokémon també!$"


Route111_Text_TravisDefeat:
	.string "El meu Pokémon ha perdut l'energia…$"


Route111_Text_TravisPostBattle:
	.string "Quan veig un Entrenador ple\n"

	.string "d'energia, no puc evitar mirar.$"


Route111_Text_IreneIntro:
	.string "No sé on vas,\n"

	.string "però vols combatre?$"


Route111_Text_IreneDefeat:
	.string "Oh, ets indecemment bo!$"


Route111_Text_IrenePostBattle:
	.string "Penso si hauria d'anar al\n"

	.string "Mt. Chimney, però la vista\l"

	.string "d'aquí és molt bonica.$"


Route111_Text_DaisukeIntro:
	.string "Per entrenar-me, desafio tots\n"

	.string "els que trobo!$"


Route111_Text_DaisukeDefeat:
	.string "Em rendeixo!$"


Route111_Text_DaisukePostBattle:
	.string "Només puc seguir entrenant fins que\n"

	.string "pugui derrotar Entrenadors forts\l"

	.string "com tu.$"


Route111_Text_WiltonIntro:
	.string "Mostra'm com has endurit els teus\n"

	.string "Pokémon.$"


Route111_Text_WiltonDefeat:
	.string "Ja veig, els has endurit\n"

	.string "considerablement.$"


Route111_Text_WiltonPostBattle:
	.string "Els Pokémon i els Entrenadors\n"

	.string "aprenen molt combatent.\p"

	.string "L'important és no rendir-se mai\n"

	.string "encara que perdis.$"


Route111_Text_WiltonRegister:
	.string "Hi ha molt a aprendre del teu\n"

	.string "estil d'entrenament.\p"

	.string "Et demano una revenja si\n"

	.string "no et ve de greu.$"


Route111_Text_WiltonRematchIntro:
	.string "Entrenem aquí per pujar al\n"

	.string "següent nivell.\l"

	.string "Queda't i entrena amb nosaltres!$"


Route111_Text_WiltonRematchDefeat:
	.string "Uuh, ets bo!$"


Route111_Text_WiltonPostRematch:
	.string "Si ets tan fort, hauries d'aspirar\n"

	.string "a la Lliga Pokémon.$"


Route111_Text_BrookeIntro:
	.string "Oh, els teus Pokémon semblen actors\n"

	.string "seriosos.\l"

	.string "T'he de demanar una actuació.$"


Route111_Text_BrookeDefeat:
	.string "No només ho semblaven,\n"

	.string "són forts de veritat!$"


Route111_Text_BrookePostBattle:
	.string "Creia que criava bé els Pokémon,\n"

	.string "però encara queda molt per fer.$"


Route111_Text_BrookeRegister:
	.string "M'agradaria fer-me amiga de més\n"

	.string "gent forta com tu!$"


Route111_Text_BrookeRematchIntro:
	.string "Pots fer els Pokémon més forts o\n"

	.string "dèbils segons els moviments\l"

	.string "que els ensenyes.\p"

	.string "Quins moviments coneixen els teus\n"

	.string "Pokémon?$"


Route111_Text_BrookeRematchDefeat:
	.string "Els has ensenyat bons moviments!$"


Route111_Text_BrookePostRematch:
	.string "Potser hauria d'haver impedit que\n"

	.string "el meu Pokémon evolucionés fins\l"

	.string "aprendre millors moviments…$"


Route111_Text_CeliaIntro:
	.string "No hauria d'haver vingut a un lloc\n"

	.string "com aquest per fer un pícnic!$"


Route111_Text_CeliaDefeat:
	.string "Ai!\n"

	.string "De veritat no hauria d'haver vingut!$"


Route111_Text_CeliaPostBattle:
	.string "Amb una tempesta de sorra així, no\n"

	.string "puc preparar el pícnic ni amb les\l"

	.string "Go-Goggles posades…$"


Route111_Text_BryanIntro:
	.string "Com ets de fort?\n"

	.string "Revelarem el secret!$"


Route111_Text_BryanDefeat:
	.string "Oh! La teva força!\n"

	.string "És envoltada de misteri!$"


Route111_Text_BryanPostBattle:
	.string "Aquest desert amaga misteris\n"

	.string "entre les seves sorres!$"


Route111_Text_BrandenIntro:
	.string "Et donaré del meu entrepà\n"

	.string "si perds.$"


Route111_Text_BrandenDefeat:
	.string "Tsc! Pensava que un entrepà\n"

	.string "seria prou suborn…$"


Route111_Text_BrandenPostBattle:
	.string "El meu Sandshrew adora menjar\n"

	.string "els meus entrepans.$"


Route111_Text_TyronIntro:
	.string "Aquesta és la meva mena de Pokémon\n"

	.string "preferida!$"


Route111_Text_TyronDefeat:
	.string "Espera!\n"

	.string "Has vist bé el meu Pokémon?$"


Route111_Text_TyronPostBattle:
	.string "En un combat, gaudeixo molt\n"

	.string "mostrant els meus Pokémon.\p"

	.string "Segur que tothom se sent igual\n"

	.string "quan entra en un combat!$"


Route111_Text_CelinaIntro:
	.string "Mostra'm com posar una mica\n"

	.string "d'emoció a la meva vida.$"


Route111_Text_CelinaDefeat:
	.string "Oh… Vaja…\n"

	.string "Ha estat massa emoció.$"


Route111_Text_CelinaPostBattle:
	.string "El cor encara em bat fort.\n"

	.string "Ets un Entrenador fabulós.$"


Route111_Text_HaydenIntro:
	.string "Quan tens tanta gana com jo,\n"

	.string "no hi ha lloc per la pietat!$"


Route111_Text_HaydenDefeat:
	.string "Ai…$"


Route111_Text_HaydenPostBattle:
	.string "L'estómac em fa soroll!\n"

	.string "Potser puc rostir unes Baies…$"


Route111_Text_BiancaIntro:
	.string "Vens de Mauville?\n"

	.string "Aleshores has d'anar ple d'energia!$"


Route111_Text_BiancaDefeat:
	.string "Oh, là, là!\n"

	.string "Quina pallissa!$"


Route111_Text_BiancaPostBattle:
	.string "Aquesta ruta…\n"

	.string "Et queda un bon tros per viatjar.$"


Route112_Text_BriceIntro:
	.string "Hahahaha!\n"

	.string "Què et sembla un combat?\l"

	.string "Tu i jo!\l"

	.string "Hahahaha!$"


Route112_Text_BriceDefeat:
	.string "He perdut!\n"

	.string "Hahahaha!$"


Route112_Text_BricePostBattle:
	.string "Hahahahaha! M'ha entrat alguna cosa\n"

	.string "pel nas! Hahahaha-atxís!$"


Route112_Text_TrentIntro:
	.string "Les meves cames són sòlides de tant\n"

	.string "pujar i baixar muntanyes.\p"

	.string "No cediran fàcilment,\n"

	.string "amic!$"


Route112_Text_TrentDefeat:
	.string "Au! Se m'han enrampit les cames!$"


Route112_Text_TrentPostBattle:
	.string "Prova de fer senderisme de veritat\n"

	.string "per aquests camins de muntanya\l"

	.string "amb una motxilla pesada.\p"

	.string "Això, amic meu, et posarà en forma\n"

	.string "de debò.$"


Route112_Text_TrentRegister:
	.string "Au, se m'han enrampit les cames.\n"

	.string "Em treus unes benes de la motxilla?\p"

	.string "No, això és el meu Pokénav!\n"

	.string "Va, va, et registraré.$"


Route112_Text_TrentRematchIntro:
	.string "He mantingut la forma caminant.\n"

	.string "De força, en tinc de sobres!$"


Route112_Text_TrentRematchDefeat:
	.string "M'han superat en força?$"


Route112_Text_TrentRematchPostBattle:
	.string "He sentit que hi ha Entrenadors molt\n"

	.string "forts al cim del Mt. Chimney.\p"

	.string "Penso pujar-hi i desafiar-los!$"


Route112_Text_LarryIntro:
	.string "Soc fort.\n"

	.string "No ploraré si perdo.$"


Route112_Text_LarryDefeat:
	.string "Buaaaa!$"


Route112_Text_LarryPostBattle:
	.string "No ploro perquè trobi a faltar\n"

	.string "la meva mama! Snif…$"


Route112_Text_CarolIntro:
	.string "Quan fas un pícnic, simplement\n"

	.string "has de cantar!\l"

	.string "Vine, canta amb mi!$"


Route112_Text_CarolDefeat:
	.string "Oh, ets molt fort!$"


Route112_Text_CarolPostBattle:
	.string "Tant se val si ets bo o dolent\n"

	.string "cantant o amb Pokémon.\p"

	.string "Si et diverteixes més, guanyes!$"


Route112_Text_BryantIntro:
	.string "He atrapat Pokémon calents\n"

	.string "al Camí Ígni! Mira!$"


Route112_Text_BryantDefeat:
	.string "Quin viatge mogut!$"


Route112_Text_BryantPostBattle:
	.string "M'agrada com combats.\n"

	.string "Té un cert estil.$"


Route112_Text_ShaylaIntro:
	.string "Oh, ets un Entrenador adorable!\n"

	.string "Sisplau, un combat romàntic!\l"

	.string "No soc gens dolenta!$"


Route112_Text_ShaylaDefeat:
	.string "Oh, que fort que ets!\n"

	.string "M'has deixat de pedra!$"


Route112_Text_ShaylaPostBattle:
	.string "Estàs ocupat ara?\n"

	.string "Pensava que potser podríem\l"

	.string "fer la revenja ara…\l"

	.string "Però si estàs ocupat, no passa res.$"


Route113_Text_JaylenIntro:
	.string "Saps per què fa tan de fred\n"

	.string "per aquí?$"


Route113_Text_JaylenDefeat:
	.string "Puaj!\n"

	.string "Quina pudor!$"


Route113_Text_JaylenPostBattle:
	.string "La cendra volcànica tapa el sol,\n"

	.string "així que no fa gaire calor.\p"

	.string "Millor per a mi: no suporto la calor!$"


Route113_Text_DillonIntro:
	.string "L'erupció del volcà és la prova\n"

	.string "que la terra és viva.$"


Route113_Text_DillonDefeat:
	.string "Ets increïblement fort!$"


Route113_Text_DillonPostBattle:
	.string "Au! Aiii! No hi veig!\n"

	.string "M'ha entrat cendra als ulls!\p"

	.string "Ho pilles? Cendra i cenra…?\p"

	.string "Va, ha estat dolent, perdona…$"


Route113_Text_MadelineIntro:
	.string "Faig servir el para-sol per protegir\n"

	.string "el meu estimat Numel d'aquesta\l"

	.string "cendra volcànica bruta.$"


Route113_Text_MadelineDefeat:
	.string "Buf, buf…\n"

	.string "Estic esgotada…$"


Route113_Text_MadelinePostBattle:
	.string "Ho fas molt bé.\n"

	.string "He de dir que estic impressionada!$"


Route113_Text_MadelineRegister:
	.string "Vine, posa't sota el meu para-sol.\n"

	.string "Et registraré al meu Pokénav.$"


Route113_Text_MadelineRematchIntro:
	.string "Oh, hola, quant de temps!\n"

	.string "Vols un combat?$"


Route113_Text_MadelineRematchDefeat:
	.string "Oh, fantàstic!$"


Route113_Text_MadelinePostRematch:
	.string "Segueixes fent-ho molt bé.\n"

	.string "He de dir que estic impressionada!$"


Route113_Text_LaoIntro:
	.string "De la cendra sorgeixo! Hiyah!\n"

	.string "Et desafio!$"


Route113_Text_LaoDefeat:
	.string "Amb honor admeto la derrota!$"


Route113_Text_LaoPostBattle:
	.string "He de perfeccionar l'art del\n"

	.string "camuflatge. Et dic adéu.$"


Route113_Text_LaoRegister:
	.string "Yiiyaah! Observa l'antiga tècnica\n"

	.string "ninja de registre de Pokénav!$"


Route113_Text_LaoRematchIntro:
	.string "De la cendra sorgeixo! Hiyah!\n"

	.string "Et desafio!$"


Route113_Text_LaoRematchDefeat:
	.string "Amb honor admeto la derrota!$"


Route113_Text_LaoPostRematch:
	.string "El meu camuflatge perfecte ha estat\n"

	.string "trair per les meves habilitats\l"

	.string "de combat immadures…\p"

	.string "Et dic adéu.$"


Route113_Text_LungIntro:
	.string "Gràcies per trobar-me!\n"

	.string "Però hem de combatre!$"


Route113_Text_LungDefeat:
	.string "Faré servir el meu ninjutsu…\n"

	.string "“Remolí de Cendra Volcànica”!\p"

	.string "…Què?\n"

	.string "Ja s'ha acabat?$"


Route113_Text_LungPostBattle:
	.string "Saps què és dolent d'amagar-se?\n"

	.string "Que fa soledat si no ve ningú.$"


Route113_Text_ToriIntro:
	.string "Tori: Tots dos recollim cendra.\n"

	.string "I també combatim Pokémon.$"


Route113_Text_ToriDefeat:
	.string "Tori: Hem perdut… M'avorreixo, aniré\n"

	.string "a recollir més cendra.$"


Route113_Text_ToriPostBattle:
	.string "Tori: Quanta cendra tenim?\n"

	.string "Espero que prou per una Flauta Blanca.$"


Route113_Text_ToriNotEnoughMons:
	.string "Tori: Volem combatre 2 contra 2.\n"

	.string "Si no, perdríem!$"


Route113_Text_TiaIntro:
	.string "Tia: Tots dos recollim cendra.\n"

	.string "I també combatim Pokémon.$"


Route113_Text_TiaDefeat:
	.string "Tia: No hem pogut guanyar…\n"

	.string "M'avorreixo, vaig a recollir cendra.$"


Route113_Text_TiaPostBattle:
	.string "Tia: Tenim molta cendra!\n"

	.string "Crec que prou per una Flauta Blanca!$"


Route113_Text_TiaNotEnoughMons:
	.string "Tia: Volem combatre 2 contra 2.\n"

	.string "Si no, no guanyarem!$"


Route113_Text_CobyIntro:
	.string "Bah, amb aquestes ales et puc\n"

	.string "apartar d'un cop!$"


Route113_Text_CobyDefeat:
	.string "Co… Què?$"


Route113_Text_CobyPostBattle:
	.string "No sé què dir quan em guanyen\n"

	.string "tan fàcilment…$"


Route113_Text_SophieIntro:
	.string "La calor d'aquí em fa son.\n"

	.string "Combat amb mi per mantenir-me\l"

	.string "desperta.$"


Route113_Text_SophieDefeat:
	.string "Això és un somni.\n"

	.string "N'estic segura…$"


Route113_Text_SophiePostBattle:
	.string "Perdre em fa ràbia…\n"

	.string "Dormiré aquí mateix!\l"

	.string "Zzz!$"


Route113_Text_LawrenceIntro:
	.string "Estaves recollint cendra\n"

	.string "volcànica, potser?$"


Route113_Text_LawrenceDefeat:
	.string "Ehe.\n"

	.string "Ens han guanyat bé.$"


Route113_Text_LawrencePostBattle:
	.string "Jo també m'hauria d'amagar\n"

	.string "sota la cendra.$"


Route113_Text_WyattIntro:
	.string "V-vols combatre amb mi?\n"

	.string "Tot i que acabo d'atrapar el Pokémon?$"


Route113_Text_WyattDefeat:
	.string "E-estàs content de guanyar?\n"

	.string "Només soc jo, eh?$"


Route113_Text_WyattPostBattle:
	.string "Oh, ara vols dir-li alguna cosa\n"

	.string "al perdedor?\p"

	.string "Que guai que ets, no?\n"

	.string "Hmf!$"


Route114_Text_LennyIntro:
	.string "Iodelaihihuu!\p"

	.string "… …\p"

	.string "Has de cridar “iodelaihihuu”\n"

	.string "perquè aquí no fa eco!$"


Route114_Text_LennyDefeat:
	.string "Iodelaihihuu!$"


Route114_Text_LennyPostBattle:
	.string "De petit, creia que hi havia algú\n"

	.string "que em copiava i cridava\l"

	.string "“Iodelaihihuu”.$"


Route114_Text_LucasIntro:
	.string "Si no estàs preparat, no hauries\n"

	.string "de ser a la muntanya!$"


Route114_Text_LucasDefeat:
	.string "Les muntanyes no perdonen…$"


Route114_Text_LucasPostBattle:
	.string "A l'hivern, les muntanyes es tornen\n"

	.string "mortals amb nevades i allaus.$"


Route114_Text_ShaneIntro:
	.string "Acampar és divertit! Pots pescar,\n"

	.string "rostir i explicar històries de por!\p"

	.string "Però el millor de tot són els\n"

	.string "combats Pokémon!$"


Route114_Text_ShaneDefeat:
	.string "Massa fort!$"


Route114_Text_ShanePostBattle:
	.string "Trobo genial que pugui anar\n"

	.string "d'acampada amb els meus Pokémon.$"


Route114_Text_NancyIntro:
	.string "He de fer exercici després de menjar.\n"

	.string "Combatim!$"


Route114_Text_NancyDefeat:
	.string "Oh, no!$"


Route114_Text_NancyPostBattle:
	.string "Acabo de menjar bé.\n"

	.string "Em ve son…$"


Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"

	.string "Vols combatre el meu Pokémon?$"


Route114_Text_SteveDefeat:
	.string "E-El meu Pokémon…$"


Route114_Text_StevePostBattle:
	.string "Un cos gros ple de bonys i dur,\n"

	.string "banyes enormes i ullals feroços…\p"

	.string "Ufufufufu…\n"

	.string "M'agradaria tenir un Pokémon així…$"


Route114_Text_SteveRegister:
	.string "No oblidis el que m'has fet!\n"

	.string "Faré que no ho puguis oblidar!$"


Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"

	.string "Va, combat amb el meu Pokémon…$"


Route114_Text_SteveRematchDefeat:
	.string "Em sento tan afortunat de veure\n"

	.string "els teus Pokémon…$"


Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"

	.string "Quan veig Pokémon combatent,\n"

	.string "se'm posa la pell de gallina…$"


Route114_Text_BernieIntro:
	.string "Si encens un foc, assegura't\n"

	.string "de tenir aigua a mà.$"


Route114_Text_BernieDefeat:
	.string "Gràcies per apagar-me el foc!$"


Route114_Text_BerniePostBattle:
	.string "Has de vigilar molt amb qualsevol\n"

	.string "foc en un bosc.\p"

	.string "Mai subestimis el poder\n"

	.string "del foc.$"


Route114_Text_BernieRegister:
	.string "Has encès el meu esperit.\n"

	.string "Registrem-nos mútuament!$"


Route114_Text_BernieRematchIntro:
	.string "Has après a tenir aigua a mà\n"

	.string "per als focs?$"


Route114_Text_BernieRematchDefeat:
	.string "M'han apagat abans de poder\n"

	.string "encendre'm, suposo.$"


Route114_Text_BerniePostRematch:
	.string "Has de vigilar molt amb qualsevol\n"

	.string "foc en un bosc.\p"

	.string "Mai subestimis el poder\n"

	.string "del foc.$"


Route114_Text_ClaudeIntro:
	.string "Si competíssim pescant, no tindries\n"

	.string "cap oportunitat.\l"

	.string "Així que, endavant amb els Pokémon!$"


Route114_Text_ClaudeDefeat:
	.string "Si fos pesca, hauria guanyat…$"


Route114_Text_ClaudePostBattle:
	.string "Provaré sort a Cascada Meteòrica\n"

	.string "a veure si pico un peix gros.\p"

	.string "Segur que hi ha alguna cosa.\n"

	.string "Ho sé cert.$"


Route114_Text_NolanIntro:
	.string "M'agrada pescar. Però combatre\n"

	.string "també!\p"

	.string "Si algú em desafia, hi soc, encara\n"

	.string "que estigui pescant.$"


Route114_Text_NolanDefeat:
	.string "M'agrada combatre, però això no\n"

	.string "vol dir que en sigui bo…$"


Route114_Text_NolanPostBattle:
	.string "Ara sí que sí!\p"

	.string "Sempre penso això, i per tant no\n"

	.string "puc deixar ni pescar ni Pokémon.$"


Route114_Text_TyraIntro:
	.string "Tyra: Bé, sí.\n"

	.string "Estic d'humor.\l"

	.string "T'ensenyaré una mica sobre Pokémon.$"


Route114_Text_TyraDefeat:
	.string "Tyra: Quin estil de combat\n"

	.string "increïble!$"


Route114_Text_TyraPostBattle:
	.string "Tyra: Estava ensenyant sobre\n"

	.string "Pokémon a la meva alumna Ivy.$"


Route114_Text_TyraNotEnoughMons:
	.string "Tyra: Hihi…\n"

	.string "Si vols combatre amb nosaltres,\l"

	.string "un sol Pokémon no és prou!$"


Route114_Text_IvyIntro:
	.string "Ivy: Qui t'ha ensenyat sobre Pokémon?$"


Route114_Text_IvyDefeat:
	.string "Ivy: Quin estil de combat\n"

	.string "increïble!$"


Route114_Text_IvyPostBattle:
	.string "Ivy: Vaig començar a entrenar\n"

	.string "Pokémon perquè Tyra, la meva\l"

	.string "mentora, m'ho va ensenyar!$"


Route114_Text_IvyNotEnoughMons:
	.string "Ivy: Només tens un Pokémon?\n"

	.string "Se deu sentir sol.$"


Route114_Text_KaiIntro:
	.string "N'he pescat un de gros!\n"

	.string "Enorme, et dic!$"


Route114_Text_KaiDefeat:
	.string "Què ha passat?\n"

	.string "El meu era més petit?$"


Route114_Text_KaiPostBattle:
	.string "D'acord!\n"

	.string "En pescaré un de més gros!$"


Route114_Text_CharlotteIntro:
	.string "Jo!\n"

	.string "No soc només una cara bonica!$"


Route114_Text_CharlotteDefeat:
	.string "Això no ha estat gens maco!$"


Route114_Text_CharlottePostBattle:
	.string "No vull un Pokémon que sigui\n"

	.string "només bonic.\p"

	.string "M'encanten els bonics que tenen\n"

	.string "algun toc especial!$"


Route114_Text_AngelinaIntro:
	.string "Has fet evolucionar molt els teus\n"

	.string "Pokémon?$"


Route114_Text_AngelinaDefeat:
	.string "Oh, ja veig.\n"

	.string "Està bé saber-ho.$"


Route114_Text_AngelinaPostBattle:
	.string "Alguns Pokémon canvien tant quan\n"

	.string "evolucionen que fa impressió!$"


Route115_Text_TimothyIntro:
	.string "Hm…\n"

	.string "Sembles bastant capaç…\l"

	.string "Deixa que t'acompanyi!$"


Route115_Text_TimothyDefeat:
	.string "Ets molt més fort del que\n"

	.string "m'imaginava!$"


Route115_Text_TimothyPostBattle:
	.string "No existeixen els genis nats.\n"

	.string "Tot depèn de l'esforç!\l"

	.string "És el que crec…$"


Route115_Text_TimothyRegister:
	.string "Hmm… Una derrota tan rotunda feia\n"

	.string "molt que no la vivia.\p"

	.string "Si m'ho permets, desitjaria una\n"

	.string "altra oportunitat de combatre.$"


Route115_Text_TimothyRematchIntro:
	.string "Hm… Com sempre, la teva agilitat\n"

	.string "parla per si sola.\l"

	.string "Vine, acompanya'm!$"


Route115_Text_TimothyRematchDefeat:
	.string "Tan fort com sempre!$"


Route115_Text_TimothyPostRematch:
	.string "Tot és qüestió d'esforç!\p"

	.string "He perdut perquè no n'he fet\n"

	.string "prou!$"


Route115_Text_KoichiIntro:
	.string "Tu!\p"

	.string "El meu Machop!\p"

	.string "Exigeix un combat!$"


Route115_Text_KoichiDefeat:
	.string "Au, au, au!$"


Route115_Text_KoichiPostBattle:
	.string "El meu equip de Machop!\p"

	.string "Mentre busquin la força, jo em faré\n"

	.string "fort amb ells!$"


Route115_Text_NobIntro:
	.string "La meva millor habilitat és trencar\n"

	.string "maons amb el front!$"


Route115_Text_NobDefeat:
	.string "Ugwaaaah!\n"

	.string "M'he rebentat el cap!$"


Route115_Text_NobPostBattle:
	.string "He estat ensenyant karate als meus\n"

	.string "Pokémon.\p"

	.string "Sembla que seran millors que jo.\n"

	.string "Estic emocionat!$"


Route115_Text_NobRegister:
	.string "M'impressiones! Dóna'm la revenja\n"

	.string "un cop hagi tornat a entrenar!$"


Route115_Text_NobRematchIntro:
	.string "Des que em vas guanyar, hem entrenat\n"

	.string "dur per millorar.\l"

	.string "Va, dóna'ns la revenja!$"


Route115_Text_NobRematchDefeat:
	.string "Ugwaaah!\n"

	.string "Hem tornat a perdre!$"


Route115_Text_NobPostRematch:
	.string "El meu Pokémon es farà més fort!\n"

	.string "Redoblaré l'entrenament!$"


Route115_Text_CyndyIntro:
	.string "Aquesta platja és el meu lloc secret\n"

	.string "d'entrenament! No et fiquis!$"


Route115_Text_CyndyDefeat:
	.string "No he entrenat prou!$"


Route115_Text_CyndyPostBattle:
	.string "La sorra fa de coixí per reduir\n"

	.string "l'impacte i prevenir lesions.\l"

	.string "És el lloc perfecte per entrenar.$"


Route115_Text_CyndyRegister:
	.string "Va, pots venir aquí lliurement.\n"

	.string "A canvi, vull tornar a combatre.$"


Route115_Text_CyndyRematchIntro:
	.string "Va, comencem el combat!$"


Route115_Text_CyndyRematchDefeat:
	.string "Jo puc combatre, però el Pokémon…$"


Route115_Text_CyndyPostRematch:
	.string "Fins i tot quan perdo, en trec\n"

	.string "alguna satisfacció.\l"

	.string "Deu ser que m'encanten els Pokémon.$"


Route115_Text_HectorIntro:
	.string "Tinc un Pokémon rar!\n"

	.string "Vols que te'l mostri?$"


Route115_Text_HectorDefeat:
	.string "Tu…\n"

	.string "Vols el meu Pokémon, oi?$"


Route115_Text_HectorPostBattle:
	.string "Tinc aquest Pokémon rar.\n"

	.string "N'hi ha prou per sentir-me satisfet.$"


Route115_Text_KyraIntro:
	.string "Combatré mentre corro!\n"

	.string "A veure si em segueixes el ritme!$"


Route115_Text_KyraDefeat:
	.string "Buf, buf…$"


Route115_Text_KyraPostBattle:
	.string "M'he equivocat intentant combatre\n"

	.string "mentre corria!\p"

	.string "Hauria de córrer per calmar-me…$"


Route115_Text_JaidenIntro:
	.string "Pren això!\n"

	.string "Ultra atac Pokémon ninja!$"


Route115_Text_JaidenDefeat:
	.string "Buaaa!\n"

	.string "La nostra estratègia ha fallat!$"


Route115_Text_JaidenPostBattle:
	.string "Però els meus Pokémon eren ultra,\n"

	.string "no?$"


Route115_Text_HeleneIntro:
	.string "Els meus Pokémon tenen la força\n"

	.string "d'un cinturó negre!$"


Route115_Text_HeleneDefeat:
	.string "Quina humiliació!$"


Route115_Text_HelenePostBattle:
	.string "Rarament trobo algú millor\n"

	.string "que jo…\p"

	.string "Ja ho entenc!\n"

	.string "Ets un Líder de Gimnàs, oi?$"


Route115_Text_AlixIntro:
	.string "Les mirades s'han creuat!\n"

	.string "Ja no pots escapar!$"


Route115_Text_AlixDefeat:
	.string "Bah!\n"

	.string "No està malament!$"


Route115_Text_AlixPostBattle:
	.string "Bé, bé.\n"

	.string "Crec que em teletransportaré a casa.$"


Route115_Text_MarleneIntro:
	.string "Has pertorbat la meva meditació…\n"

	.string "En seràs castigat.$"


Route115_Text_MarleneDefeat:
	.string "M'has trencat la concentració!$"


Route115_Text_MarlenePostBattle:
	.string "Meditava amb el meu Pokémon.\n"

	.string "Però aquest lloc no és gaire\l"

	.string "tranquil…$"


Route116_Text_ClarkIntro:
	.string "Si el túnel no s'obre, passaré\n"

	.string "per dalt.$"


Route116_Text_ClarkDefeat:
	.string "Buf… Buf…\n"

	.string "Perdre m'ha cansat…$"


Route116_Text_ClarkPostBattle:
	.string "No és cap problema si no hi ha túnel.\n"

	.string "Per a un Excursionista, les muntanyes\l"

	.string "són camins!$"


Route116_Text_JoeyIntro:
	.string "Els meus Pokémon molen!\n"

	.string "Mira'ls!$"


Route116_Text_JoeyDefeat:
	.string "Au! Un rascament!\n"

	.string "He de posar-me una tireta!$"


Route116_Text_JoeyPostBattle:
	.string "Les tiretes són signe de duresa!\n"

	.string "En tinc una altra!$"


Route116_Text_JoseIntro:
	.string "Els meus Pokémon Insecte són forts!\n"

	.string "Combatim!$"


Route116_Text_JoseDefeat:
	.string "He perdut!\n"

	.string "Pensava que et tenia!$"


Route116_Text_JosePostBattle:
	.string "Els Pokémon Insecte evolucionen\n"

	.string "ràpid.\l"

	.string "Així que es fan forts ràpid.$"


Route116_Text_JaniceIntro:
	.string "Deixa que t'ensenyi com de fort\n"

	.string "és el meu adorable Pokémon!$"


Route116_Text_JaniceDefeat:
	.string "Ets un graó per sobre meu…$"


Route116_Text_JanicePostBattle:
	.string "Pokémon que tinguin simpatia i\n"

	.string "força, això és l'ideal, crec.$"


Route116_Text_JerryIntro:
	.string "Aprenem moltes coses a l'Escola\n"

	.string "d'Entrenadors.\p"

	.string "Vull posar-les a prova de veritat!$"


Route116_Text_JerryDefeat:
	.string "No vaig estudiar prou…\n"

	.string "Per això he perdut.$"


Route116_Text_JerryPostBattle:
	.string "Hauré de repetir alguns cursos\n"

	.string "a l'Escola d'Entrenadors.\l"

	.string "Si no, Roxanne s'enfadarà.$"


Route116_Text_JerryRegister1:
	.string "He après a l'Escola que un Pokénav\n"

	.string "pot registrar Entrenadors.\p"

	.string "No acabo d'entendre què vol dir,\n"

	.string "puc provar-ho?$"


Route116_Text_JerryRegister2:
	.string "He après a l'Escola que un Pokénav\n"

	.string "pot registrar Entrenadors.\p"

	.string "No acabo d'entendre què vol dir,\n"

	.string "puc provar-ho?$"


Route116_Text_JerryRematchIntro:
	.string "He estudiat de debò a l'Escola\n"

	.string "d'Entrenadors.\l"

	.string "No perdré com l'última vegada.$"


Route116_Text_JerryRematchDefeat:
	.string "Eh?\n"

	.string "Però si he estudiat molt!$"


Route116_Text_JerryPostRematch:
	.string "Hauré de repetir alguns cursos\n"

	.string "a l'Escola d'Entrenadors.\l"

	.string "Si no, Roxanne s'enfadarà.$"


Route116_Text_KarenIntro:
	.string "Estudio a l'escola, i també\n"

	.string "de camí a casa!$"


Route116_Text_KarenDefeat:
	.string "Estic en xoc… He perdut?$"


Route116_Text_KarenPostBattle:
	.string "Ai, mai no seré una Entrenadora\n"

	.string "elegant com Roxanne així!$"


Route116_Text_KarenRegister1:
	.string "Oh, uau! Això és un Pokénav?\n"

	.string "Jo també en tinc un! Registra'm!$"


Route116_Text_KarenRegister2:
	.string "Oh, uau! Això és un Pokénav?\n"

	.string "Jo també en tinc un! Registra'm!$"


Route116_Text_KarenRematchIntro:
	.string "He estudiat moltíssim des que et\n"

	.string "vaig veure.\l"

	.string "Has de veure el meu progrés!$"


Route116_Text_KarenRematchDefeat:
	.string "Estic en xoc.\n"

	.string "He tornat a perdre?$"


Route116_Text_KarenPostRematch:
	.string "Has guanyat Roxanne?\n"

	.string "No et puc guanyar, doncs. Encara no.$"


Route116_Text_SarahIntro:
	.string "Que sàpigues que ningú no m'ha\n"

	.string "superat mai en res.$"


Route116_Text_SarahDefeat:
	.string "Oh, mare meva.\n"

	.string "Això és una experiència nova.$"


Route116_Text_SarahPostBattle:
	.string "La meva vida de luxe em permet\n"

	.string "tenir tot el que desitjo.\p"

	.string "Però amb els Pokémon, la meva\n"

	.string "riquesa no serveix de res.$"


Route116_Text_DawsonIntro:
	.string "Quan vegis el pelatge magnífic\n"

	.string "del meu Pokémon, la seva bellesa\l"

	.string "et deixarà indefens!$"


Route116_Text_DawsonDefeat:
	.string "Oh, no, digues que no és veritat!$"


Route116_Text_DawsonPostBattle:
	.string "Oh, no, no, no!\n"

	.string "Has desendreçat el pèl del Pokémon!\l"

	.string "I el meu pentinat també!\l"

	.string "Hauré de trucar el meu perruquer!$"


Route116_Text_DevanIntro:
	.string "Et farem tremolar!$"


Route116_Text_DevanDefeat:
	.string "Aiyiyi!\n"

	.string "Cap competència!$"


Route116_Text_DevanPostBattle:
	.string "Hauria de provar tipus de Pokémon\n"

	.string "diferents, vet aquí.$"


Route116_Text_JohnsonIntro:
	.string "Aquí dalt és un carreró sense sortida.\n"

	.string "M'avorreixo, combatim?$"


Route116_Text_JohnsonDefeat:
	.string "Ha estat divertit tot i perdre.$"


Route116_Text_JohnsonPostBattle:
	.string "Vols quedar-te aquí i fer-me\n"

	.string "companyia?$"


Route117_Text_IsaacIntro:
	.string "Escolta, voldries combatre\n"

	.string "el Pokémon que estic criant?$"


Route117_Text_IsaacDefeat:
	.string "Has criat els teus magníficament…$"


Route117_Text_IsaacPostBattle:
	.string "Pokémon no va només de força.\p"

	.string "Polir un aspecte únic del caràcter\n"

	.string "és una altra manera de gaudir\l"

	.string "dels Pokémon.$"


Route117_Text_IsaacRegister:
	.string "Redoblaré l'entrenament.\n"

	.string "Vindràs a veure'ns?$"


Route117_Text_IsaacRematchIntro:
	.string "Els Pokémon que he estat criant\n"

	.string "fan bona pinta, com sempre.$"


Route117_Text_IsaacRematchDefeat:
	.string "Saps com criar-los bé.\n"

	.string "Potser tens dot de Guarderia…$"


Route117_Text_IsaacPostRematch:
	.string "Els teus Pokémon creixen bé!\n"

	.string "Hauries de presentar-los a Concursos.$"


Route117_Text_LydiaIntro:
	.string "Permet-me avaluar si has criat\n"

	.string "els teus Pokémon correctament.$"


Route117_Text_LydiaDefeat:
	.string "Sí, creixen correctament.$"


Route117_Text_LydiaPostBattle:
	.string "Prova de criar Pokémon prestant més\n"

	.string "atenció als trets del seu caràcter.$"


Route117_Text_LydiaRegister:
	.string "Em fa molt content trobar un\n"

	.string "Entrenador excel·lent com tu.\l"

	.string "Espero tornar-te a veure.$"


Route117_Text_LydiaRematchIntro:
	.string "Deixa'm reavaluar si has criat\n"

	.string "els teus Pokémon correctament.$"


Route117_Text_LydiaRematchDefeat:
	.string "Creixen admirablement.$"


Route117_Text_LydiaPostRematch:
	.string "Els Pokémon semblen preferir\n"

	.string "diferents {POKEBLOCK}s segons\l"

	.string "la seva naturalesa.$"


Route117_Text_DylanIntro:
	.string "Estic enmig d'un triatló, però\n"

	.string "tant se val, combatim!$"


Route117_Text_DylanDefeat:
	.string "M'he quedat sense energia!$"


Route117_Text_DylanPostBattle:
	.string "Potser l'he pifiada…\p"

	.string "Potser he caigut a l'últim lloc\n"

	.string "durant el combat…$"


Route117_Text_DylanRegister:
	.string "Els Pokémon també han de ser forts?\n"

	.string "M'agradaria que m'entrenissis!$"


Route117_Text_DylanRematchIntro:
	.string "Estic en ple triatló, però vaig\n"

	.string "còmodament al davant.\l"

	.string "Un combat ràpid!$"


Route117_Text_DylanRematchDefeat:
	.string "M'he tornat a quedar sense energia!$"


Route117_Text_DylanPostRematch:
	.string "Era el millor nedant i pedalant,\n"

	.string "però amb Pokémon no estic tan\l"

	.string "segur.$"


Route117_Text_MariaIntro:
	.string "Entreno per al triatló amb Pokémon,\n"

	.string "així que estic segura de la velocitat.$"


Route117_Text_MariaDefeat:
	.string "Necessito més pràctiques,\n"

	.string "suposo.$"


Route117_Text_MariaPostBattle:
	.string "L'entrenament només té sentit\n"

	.string "si ho mantens regularment.\p"

	.string "Au! Reprenc l'entrenament!\n"

	.string "Demà!$"


Route117_Text_MariaRegister:
	.string "Sembla que entrenes com cal…\n"

	.string "Si vols, combat amb tu més tard!$"


Route117_Text_MariaRematchIntro:
	.string "Segueixes entrenant?\n"

	.string "Jo sí!\l"

	.string "Deixa que t'ho demostri!$"


Route117_Text_MariaRematchDefeat:
	.string "Necessito més pràctiques,\n"

	.string "suposo.$"


Route117_Text_MariaPostRematch:
	.string "Reprenc l'entrenament demà.\n"

	.string "Combatim un altre dia!$"


Route117_Text_DerekIntro:
	.string "Primer un Caçainsectes!\n"

	.string "Ara un Fanàtic dels Insectes!\p"

	.string "Però el meu amor pels Pokémon\n"

	.string "no ha canviat!$"


Route117_Text_DerekDefeat:
	.string "La meva ineptitud tampoc\n"

	.string "ha canviat…$"


Route117_Text_DerekPostBattle:
	.string "Només he seguit el cor, i ara em\n"

	.string "diuen Fanàtic dels Insectes…\p"

	.string "Però soc expert en Pokémon Insecte,\n"

	.string "és natural que em diguin així.$"


Route117_Text_AnnaIntro:
	.string "Anna: Soc amb la meva bonica\n"

	.string "companya junior. He de fer-ho bé!$"


Route117_Text_AnnaDefeat:
	.string "Anna: Soc amb la meva bonica\n"

	.string "companya junior! Deixa'm guanyar!$"


Route117_Text_AnnaPostBattle:
	.string "Anna: Els teus Pokémon fan bones\n"

	.string "combinacions.\p"

	.string "Diria que només estàs per sota\n"

	.string "de nosaltres!$"


Route117_Text_AnnaAndMegRegister:
	.string "Anna: No ens podem quedar quietes!\n"

	.string "Tornaràs, oi?$"


Route117_Text_AnnaNotEnoughMons:
	.string "Anna: Si vols combatre amb nosaltres,\n"

	.string "porta dos Pokémon.$"


Route117_Text_MegIntro:
	.string "Meg: Faré equip amb la meva sènior\n"

	.string "i et guanyarem!$"


Route117_Text_MegDefeat:
	.string "Meg: Oh, no!\n"

	.string "Perdona, Anna! T'he fallat…$"


Route117_Text_MegPostBattle:
	.string "Meg: He arrossegat l'Anna…\n"

	.string "Si no, hauria guanyat!$"


Route117_Text_MegNotEnoughMons:
	.string "Meg: Només tens un Pokémon?\n"

	.string "No podem combatre amb tu.\p"

	.string "Volem un combat 2 contra 2.$"


Route117_Text_AnnaRematchIntro:
	.string "Anna: No puc seguir perdent davant\n"

	.string "de la meva companya, oi?$"


Route117_Text_AnnaRematchDefeat:
	.string "Anna: No he agafat el ritme.$"


Route117_Text_AnnaPostRematch:
	.string "Anna: Els teus Pokémon fan bones\n"

	.string "combinacions.\p"

	.string "Diria que només estàs per sota\n"

	.string "de nosaltres!$"


Route117_Text_AnnaRematchNotEnoughMons:
	.string "Anna: Si vols combatre amb nosaltres,\n"

	.string "porta dos Pokémon.$"


Route117_Text_MegRematchIntro:
	.string "Meg: Faré equip amb la meva sènior\n"

	.string "i aquest cop guanyarem!$"


Route117_Text_MegRematchDefeat:
	.string "Meg: Massa fort!$"


Route117_Text_MegPostRematch:
	.string "Meg: He combat amb la meva sènior,\n"

	.string "però hem perdut…\p"

	.string "Quin desànim…$"


Route117_Text_MegRematchNotEnoughMons:
	.string "Meg: Només tens un Pokémon?\n"

	.string "No podem combatre amb tu.\p"

	.string "Volem un combat 2 contra 2.$"


Route117_Text_MelinaIntro:
	.string "No és bonic? Combatre mentre\n"

	.string "mires flors boniques?$"


Route117_Text_MelinaDefeat:
	.string "Oh, força impressionant!$"


Route117_Text_MelinaPostBattle:
	.string "Fa molt de gust córrer mentre\n"

	.string "mires les flors.$"


Route117_Text_BrandiIntro:
	.string "Deixa que et mostri el poder\n"

	.string "amagat dels Pokémon Psíquics!$"


Route117_Text_BrandiDefeat:
	.string "Sorprenent!$"


Route117_Text_BrandiPostBattle:
	.string "Els Pokémon Psíquics són complexos.\n"

	.string "Hauries de provar d'atrapar-ne.$"


Route117_Text_AishaIntro:
	.string "Concentra't a guanyar.\n"

	.string "Així és com combat!$"


Route117_Text_AishaDefeat:
	.string "No perdo temps enfadant-me per\n"

	.string "una derrota: prefereixo entrenar.$"


Route117_Text_AishaPostBattle:
	.string "Crec que si et preocupes per perdre,\n"

	.string "tens més probabilitats de perdre.$"


Route118_Text_RoseIntro:
	.string "L'aroma de les flors té un poder\n"

	.string "màgic. Ens purifica cos i ànima.$"


Route118_Text_RoseDefeat:
	.string "Vaja per mi.\n"

	.string "Sembla que he perdut.$"


Route118_Text_RosePostBattle:
	.string "Flors, Pokémon…\n"

	.string "M'agrada tot el que fa bona olor.\p"

	.string "Les coses pudents…\n"

	.string "Millor no.$"


Route118_Text_RoseRegister:
	.string "Snif… Aquesta olor, és un Pokénav!\n"

	.string "Ens hem de registrar!$"


Route118_Text_RoseRematchIntro:
	.string "T'ha atret el dolç aroma\n"

	.string "fins aquí?$"


Route118_Text_RoseRematchDefeat:
	.string "El poder de l'aroma…\n"

	.string "No ha servit de gaire.$"


Route118_Text_RosePostRematch:
	.string "Si fas servir un dolç aroma bé,\n"

	.string "els Pokémon vindran atrets.$"


Route118_Text_PerryIntro:
	.string "Els Pokémon Ocell que volen\n"

	.string "elegantment pel cel… Són genials!$"


Route118_Text_PerryDefeat:
	.string "Urgh…\n"

	.string "He caigut…$"


Route118_Text_PerryPostBattle:
	.string "Tens grans Pokémon.\n"

	.string "Hauré d'entrenar els meus millor.$"


Route118_Text_ChesterIntro:
	.string "Voleu!\n"

	.string "Pokémon Ocell meus!$"


Route118_Text_ChesterDefeat:
	.string "Sí que han volat…$"


Route118_Text_ChesterPostBattle:
	.string "Si es fessin més forts, podrien\n"

	.string "volar més lliurement…$"


Route118_Text_BarnyIntro:
	.string "Soc Pescador, però també Entrenador.\n"

	.string "Estic criant els Pokémon que he pescat.$"


Route118_Text_BarnyDefeat:
	.string "Pensava que el meu entrenament\n"

	.string "anava bé…$"


Route118_Text_BarnyPostBattle:
	.string "No podia guanyar entrenant Pokémon\n"

	.string "mentre pescava…\p"

	.string "Estava fent les coses a mitges?$"


Route118_Text_WadeIntro:
	.string "Per als Pescadors, l'equip és clau.\p"

	.string "Però per als Entrenadors, el clau\n"

	.string "són els Pokémon i el cor!$"


Route118_Text_WadeDefeat:
	.string "M'han guanyat de cor?$"


Route118_Text_WadePostBattle:
	.string "Pensant-ho bé, pescar és un combat\n"

	.string "entre un Pescador i un Pokémon.$"


Route118_Text_DaltonIntro:
	.string "Que la meva melodia et commogui!$"


Route118_Text_DaltonDefeat:
	.string "La-lalala…$"


Route118_Text_DaltonPostBattle:
	.string "Una guitarra elèctrica no sempre\n"

	.string "ha de ser sorollosa…\p"

	.string "Es pot raspejar per treure'n\n"

	.string "una melodia commovdora…$"


Route118_Text_DaltonRegister:
	.string "Quan compongui melodies millors,\n"

	.string "has de venir a escoltar-les, d'acord?$"


Route118_Text_DaltonRematchIntro:
	.string "Una melodia del meu Pokémon i jo…\n"

	.string "La farem arribar a la teva ànima.$"


Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"


Route118_Text_DaltonPostRematch:
	.string "Quan toco, les meves emocions\n"

	.string "haurien d'arribar-te a través\l"

	.string "de la guitarra elèctrica…$"


Route118_Text_DeandreIntro:
	.string "Endavant!\n"

	.string "Pokémon 1, 2 i 3!$"


Route118_Text_DeandreDefeat:
	.string "Pokémon! Esteu bé?\n"

	.string "Pokémon 1, 2 i 3?!$"


Route118_Text_DeandrePostBattle:
	.string "No és genial que tingui un equip\n"

	.string "de combat Pokémon?\p"

	.string "Em pots copiar, no m'importa!$"


Route119_Text_BrentIntro:
	.string "Som el Cercle Mim!\n"

	.string "Imitem el que fas!$"


Route119_Text_BrentDefeat:
	.string "Vaja!\n"

	.string "He perdut!$"


Route119_Text_BrentPostBattle:
	.string "Què té de bo imitar?\p"

	.string "Fufufu…\n"

	.string "Mai ho entendràs…$"


Route119_Text_DonaldIntro:
	.string "Per fi ens trobem!\n"

	.string "Els meus Pokémon Insecte et faran\l"

	.string "companyia!$"


Route119_Text_DonaldDefeat:
	.string "M'agradaria no haver-te trobat mai…$"


Route119_Text_DonaldPostBattle:
	.string "Vull seguir imitant-te.\n"

	.string "Pots afanyar-te i moure't?$"


Route119_Text_TaylorIntro:
	.string "Si fas un pas endavant, nosaltres\n"

	.string "també.\p"

	.string "Si gires a la dreta, nosaltres\n"

	.string "també…$"


Route119_Text_TaylorDefeat:
	.string "Però si guanyes tu, jo perdo…$"


Route119_Text_TaylorPostBattle:
	.string "No puc imitar que guanyes el combat.\n"

	.string "Això és impossible…\l"

	.string "Em fa ràbia…$"


Route119_Text_DougIntro:
	.string "Sí, per fi m'has trobat!\n"

	.string "O intentaves evitar-me?$"


Route119_Text_DougDefeat:
	.string "Uep, quin bon combat!$"


Route119_Text_DougPostBattle:
	.string "Som el Cercle Mim!\n"

	.string "Espero que hagis gaudit del show.$"


Route119_Text_GregIntro:
	.string "No saps qui soc, oi?\p"

	.string "Però jo tampoc et conec.\n"

	.string "Així que, combat!$"


Route119_Text_GregDefeat:
	.string "Ets bastant fort!$"


Route119_Text_GregPostBattle:
	.string "Fins que marxis, seguirem imitant\n"

	.string "tots els teus moviments.$"


Route119_Text_KentIntro:
	.string "El Cercle Mim el formen persones\n"

	.string "a qui els agrada imitar.\p"

	.string "Un combat comença en trobar-nos!$"


Route119_Text_KentDefeat:
	.string "Em rendeixo!$"


Route119_Text_KentPostBattle:
	.string "No vols unir-te al Cercle Mim?$"


Route119_Text_JacksonIntro:
	.string "Qui té el coneixement i la tècnica\n"

	.string "per sobreviure?\p"

	.string "Els Rangers Pokémon, vet aquí!$"


Route119_Text_JacksonDefeat:
	.string "No tenia prou coneixements\n"

	.string "sobre Pokémon…$"


Route119_Text_JacksonPostBattle:
	.string "Allunyar-se de la civilització\n"

	.string "i despertar l'esperit salvatge!\p"

	.string "Aquesta és la nostra visió.$"


Route119_Text_JacksonRegister:
	.string "Espero que em donis la revenja\n"

	.string "sense burlar-te de la meva\l"

	.string "ignorància.$"


Route119_Text_JacksonRematchIntro:
	.string "Recuperaré el meu esperit salvatge\n"

	.string "estant amb Pokémon.$"


Route119_Text_JacksonRematchDefeat:
	.string "Segueixes sent fort!$"


Route119_Text_JacksonPostRematch:
	.string "Creu en els teus Pokémon.\n"

	.string "Creu en tu mateix.\p"

	.string "El camí se't revelarà.$"


Route119_Text_CatherineIntro:
	.string "Oh? Mira't.\p"

	.string "Per a algú d'aventura,\n"

	.string "vas molt lleuger d'equipatge.$"


Route119_Text_CatherineDefeat:
	.string "Els accidents passen quan no\n"

	.string "estàs preparat!$"


Route119_Text_CatherinePostBattle:
	.string "Vas lleuger però ho tens tot.\p"

	.string "Estàs al dia mental i\n"

	.string "físicament.$"


Route119_Text_CatherineRegister:
	.string "Tens un Pokénav?\n"

	.string "És imprescindible per a un\l"

	.string "Entrenador.\p"

	.string "Oh, en tens un!\n"

	.string "Registrem-nos, doncs!$"


Route119_Text_CatherineRematchIntro:
	.string "Com va el teu viatge amb\n"

	.string "Pokémon?$"


Route119_Text_CatherineRematchDefeat:
	.string "Encara em falta alguna cosa…$"


Route119_Text_CatherinePostRematch:
	.string "De la mateixa manera que tu, com a\n"

	.string "Entrenador, depens dels Pokémon,\l"

	.string "ells depenen de tu.$"


Route119_Text_HughIntro:
	.string "L'immens cel amaga promeses!\p"

	.string "Res no es compara a l'emoció\n"

	.string "de volar!$"


Route119_Text_HughDefeat:
	.string "A terra!$"


Route119_Text_HughPostBattle:
	.string "Els meus Pokémon Ocell han fet\n"

	.string "realitat el meu somni de volar!$"


Route119_Text_PhilIntro:
	.string "Et mostraré el veritable potencial\n"

	.string "de mi i els meus Pokémon Ocell!$"


Route119_Text_PhilDefeat:
	.string "Ens ha faltat potencial…$"


Route119_Text_PhilPostBattle:
	.string "Des de petit, sempre he admirat\n"

	.string "els Pokémon Ocell…$"


Route119_Text_YasuIntro:
	.string "Amagar-se a les ombres i viure\n"

	.string "a la foscor… És el meu destí.\p"

	.string "Sorgeixo per desafiar-te!$"


Route119_Text_YasuDefeat:
	.string "Admeto la derrota!$"


Route119_Text_YasuPostBattle:
	.string "Els derrotats en combat tornen\n"

	.string "silenciosament a les ombres.\l"

	.string "Això, també, és el destí…$"


Route119_Text_TakashiIntro:
	.string "Si no vas amb compte,\n"

	.string "et farà mal!$"


Route119_Text_TakashiDefeat:
	.string "Ets sorprenentment bo!$"


Route119_Text_TakashiPostBattle:
	.string "El meu atac sorpresa ha acabat\n"

	.string "en fracàs…$"


Route119_Text_HideoIntro:
	.string "Per amagar un arbre, usa un bosc!$"


Route119_Text_HideoDefeat:
	.string "M'inclino davant la teva\n"

	.string "superioritat.$"


Route119_Text_HideoPostBattle:
	.string "Per amagar un arbre, usa un bosc!\n"

	.string "Per amagar un Pokémon, usa\l"

	.string "un Pokémon!\p"

	.string "No hi ha cap significat ocult\n"

	.string "profund.$"


Route119_Text_ChrisIntro:
	.string "M'has parlat…\n"

	.string "Així que vols desafiar-me!\p"

	.string "Va! Provaré els Pokémon que he\n"

	.string "atrapat fent Surf!$"


Route119_Text_ChrisDefeat:
	.string "No tinc ni idea del que cal\n"

	.string "per guanyar.$"


Route119_Text_ChrisPostBattle:
	.string "Fer Surf amb el meu Pokémon…\p"

	.string "I després pescar des del seu\n"

	.string "llom…\p"

	.string "És un moment indescriptiblement\n"

	.string "luxós!$"


Route119_Text_FabianIntro:
	.string "Dóna'm un acord potent!\n"

	.string "La victòria és meva!\l"

	.string "És la nostra hora de brillar, uè!$"


Route119_Text_FabianDefeat:
	.string "M'has ensenyat qui mana!\n"

	.string "Hem de perdre, oh, no!$"


Route119_Text_FabianPostBattle:
	.string "Dóna'm un altre acord potent!\n"

	.string "Deixa'm sol!\l"

	.string "La teva victòria has d'expiar!$"


Route119_Text_DaytonIntro:
	.string "Hohoho!\n"

	.string "M'agraden els Entrenadors joves!\l"

	.string "Que sigui un bon combat!$"


Route119_Text_DaytonDefeat:
	.string "Ets bastant increïble!\n"

	.string "Hohoho!$"


Route119_Text_DaytonPostBattle:
	.string "Hohoho!\n"

	.string "Intentaré emular l'energia dels\l"

	.string "Entrenadors joves com tu!$"


Route119_Text_RachelIntro:
	.string "On sigui i quan sigui,\n"

	.string "sempre porto el para-sol a mà.$"


Route119_Text_RachelDefeat:
	.string "Oh, però…\n"

	.string "Això no és just.$"


Route119_Text_RachelPostBattle:
	.string "Em preguntes si el para-sol pesa?\n"

	.string "La teva Bossa porta més trastos\l"

	.string "que no porto jo.$"


Route120_Text_ColinIntro:
	.string "Tens moviments que puguin colpejar\n"

	.string "un Pokémon volador?$"


Route120_Text_ColinDefeat:
	.string "M'has superat!$"


Route120_Text_ColinPostBattle:
	.string "El moviment Vol és pràctic,\n"

	.string "no trobes?\p"

	.string "Mentre el Pokémon vola,\n"

	.string "gairebé res no el pot colpejar.$"


Route120_Text_RobertIntro:
	.string "El meu Pokémon és fort!\n"

	.string "I el teu?$"


Route120_Text_RobertDefeat:
	.string "Els teus Pokémon eren més forts…$"


Route120_Text_RobertPostBattle:
	.string "Un Pokémon que creix de mica en mica\n"

	.string "és un en qui pots confiar.$"


Route120_Text_RobertRegister:
	.string "Es pot confiar que milloraràs.\n"

	.string "M'agradaria registrar-te al Pokénav!$"


Route120_Text_RobertRematchIntro:
	.string "Un Pokémon que creix de mica en mica\n"

	.string "és un en qui pots confiar.$"


Route120_Text_RobertRematchDefeat:
	.string "Els teus Pokémon són molt forts.$"


Route120_Text_RobertPostRematch:
	.string "Els meus Pokémon es fan més forts.\n"

	.string "Jo també m'he de fer més fort.$"


Route120_Text_LorenzoIntro:
	.string "Miraré els teus Pokémon per veure\n"

	.string "si estan preparats per la natura.$"


Route120_Text_LorenzoDefeat:
	.string "Amb Pokémon tan forts, no necessites\n"

	.string "que et rescatin!$"


Route120_Text_LorenzoPostBattle:
	.string "Viatjar on vulguis amb Pokémon…\l"

	.string "Aquesta és l'alegria de ser\l"

	.string "Entrenador.$"


Route120_Text_JennaIntro:
	.string "Com va la teva forma física?\n"

	.string "Si no estàs en forma, ho pots\l"

	.string "passar malament en moments clau.$"


Route120_Text_JennaDefeat:
	.string "Estic en plena forma, però…$"


Route120_Text_JennaPostBattle:
	.string "L'exercici és la meva rutina.\n"

	.string "Sempre corro amb el meu Pokémon.$"


Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"

	.string "… … … … … …\l"

	.string "Vols combatre?$"


Route120_Text_JeffreyDefeat:
	.string "Perdut…$"


Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"

	.string "… … … … … …\l"

	.string "Ho intentaré més…$"


Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"

	.string "… … … … … …\l"

	.string "Tens un Pokénav…?$"


Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"

	.string "… … … … … …\l"

	.string "Vols tornar a combatre?$"


Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"

	.string "He tornat a perdre…$"


Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"

	.string "… … … … … …\l"

	.string "Ho intentaré més…\l"

	.string "Pels meus estimats Pokémon Insecte…$"


Route120_Text_JenniferIntro:
	.string "Els Pokémon tenen habilitats\n"

	.string "especials. Per ser de primera,\l"

	.string "aprèn sobre elles.$"


Route120_Text_JenniferDefeat:
	.string "Clarament estàs pensant.$"


Route120_Text_JenniferPostBattle:
	.string "Les habilitats especials dels\n"

	.string "Pokémon canviaran els estils\l"

	.string "de combat.$"


Route120_Text_ChipIntro:
	.string "Qui ets?\p"

	.string "Potser busques unes ruïnes antigues\n"

	.string "de les quals es diu que potser\l"

	.string "existeixen segons la llegenda?$"


Route120_Text_ChipDefeat:
	.string "Quin revés tan vergonyós…$"


Route120_Text_ChipPostBattle:
	.string "Aquella roca gegant… M'agradaria\n"

	.string "creure que conté ruïnes antigues.\l"

	.string "Però no veig cap entrada.$"


Route120_Text_ClarissaIntro:
	.string "Per què porto un para-sol?\p"

	.string "T'ho diré si em guanyes.$"


Route120_Text_ClarissaDefeat:
	.string "Un para-sol no para els atacs\n"

	.string "Pokémon…$"


Route120_Text_ClarissaPostBattle:
	.string "No crec que el sol fort sigui bo\n"

	.string "per al meu Pokémon.\l"

	.string "Així que el protegeixo amb el\l"

	.string "para-sol.$"


Route120_Text_AngelicaIntro:
	.string "Jo, Pokémon, i el meu para-sol…\p"

	.string "Si en falta un, la imatge de\n"

	.string "bellesa es trenca.$"


Route120_Text_AngelicaDefeat:
	.string "Has destrossat la meva bellesa…$"


Route120_Text_AngelicaPostBattle:
	.string "Un para-sol no et quedaria bé.\p"

	.string "Només et faria nosa.$"


Route120_Text_KeigoIntro:
	.string "Adoptaré els moviments dels Pokémon\n"

	.string "per crear noves tècniques ninja.$"


Route120_Text_KeigoDefeat:
	.string "La creació de noves tècniques\n"

	.string "ninja és un somni llunyà…$"


Route120_Text_KeigoPostBattle:
	.string "Potser hauria de fer d'aprenent\n"

	.string "amb un mestre ninja.$"


Route120_Text_RileyIntro:
	.string "Els ninja ens ocultem sota les\n"

	.string "nostres capes de camuflatge.\l"

	.string "Segur que no sabies on era!$"


Route120_Text_RileyDefeat:
	.string "He perdut!\n"

	.string "Hauria de camuflar la vergonya!$"


Route120_Text_RileyPostBattle:
	.string "Les nostres capes de camuflatge\n"

	.string "són totes fetes a mà.$"


Route120_Text_CallieIntro:
	.string "Si no pares atenció,\n"

	.string "et podries fer mal!$"


Route120_Text_CallieDefeat:
	.string "Au!\n"

	.string "M'he fet mal jo!$"


Route120_Text_CalliePostBattle:
	.string "Em pregunto… Hauria de fer\n"

	.string "evolucionar el Pokémon?\l"

	.string "Però és tan maco tal com és…$"


Route120_Text_LeonelIntro:
	.string "El teu equip Pokémon…\n"

	.string "Tens tipus variats?$"


Route120_Text_LeonelDefeat:
	.string "He vist la teva estratègia en acció!$"


Route120_Text_LeonelPostBattle:
	.string "Trobo genial que siguis tan fort\n"

	.string "combatent amb els teus preferits.$"


Route121_Text_VanessaIntro:
	.string "Vols jugar amb el meu adorable\n"

	.string "Pokémon?$"


Route121_Text_VanessaDefeat:
	.string "No em referia a això!$"


Route121_Text_VanessaPostBattle:
	.string "Vaig a un Concurs a Lilycove.\p"

	.string "El meu Pokémon hauria d'arrasar\n"

	.string "a la Classe Mestra.$"


Route121_Text_WalterIntro:
	.string "Amb el meu Pokémon, he viatjat\n"

	.string "als quatre racons del món.\p"

	.string "Podries dir que tinc una certa\n"

	.string "confiança en les meves habilitats.$"


Route121_Text_WalterDefeat:
	.string "Ah, ben jugat.$"


Route121_Text_WalterPostBattle:
	.string "M'agradaria donar la volta al món\n"

	.string "un altre cop amb el meu Pokémon.$"


Route121_Text_WalterRegister:
	.string "Les teves habilitats Pokémon són\n"

	.string "notables.\l"

	.string "Permet-me registrar-te com a record.$"


Route121_Text_WalterRematchIntro:
	.string "Amb el meu Pokémon, he viatjat\n"

	.string "als quatre racons del món.\p"

	.string "Podries dir que tinc una certa\n"

	.string "confiança en les meves habilitats.$"


Route121_Text_WalterRematchDefeat:
	.string "Ah, ben jugat.$"


Route121_Text_WalterPostRematch:
	.string "Tu i el teu Pokémon…\p"

	.string "La vostra destresa es consideraria\n"

	.string "forta fins i tot a l'estranger.$"


Route121_Text_TammyIntro:
	.string "Hi ha poders més enllà de la\n"

	.string "nostra comprensió al món…$"


Route121_Text_TammyDefeat:
	.string "He perdut…$"


Route121_Text_TammyPostBattle:
	.string "Mt. Pyre…\n"

	.string "Hi ha un poder misteriós\l"

	.string "en acció allà…$"


Route121_Text_KateIntro:
	.string "Kate: Juntes, no tenim por!\n"

	.string "Demostrarem com de fortes som!$"


Route121_Text_KateDefeat:
	.string "Kate: He fallat davant la meva\n"

	.string "companya junior…$"


Route121_Text_KatePostBattle:
	.string "Kate: Quan algú depèn de mi,\n"

	.string "tinc la urgència de quedar bé\l"

	.string "davant seu…$"


Route121_Text_KateNotEnoughMons:
	.string "Kate: Si només tens un Pokémon,\n"

	.string "no podem combatre amb tu.\p"

	.string "Seria abusiu.$"


Route121_Text_JoyIntro:
	.string "Joy: Juntes, no tenim por!\n"

	.string "Demostrarem com de fortes som!$"


Route121_Text_JoyDefeat:
	.string "Joy: Perdona'm, Kate!$"


Route121_Text_JoyPostBattle:
	.string "Joy: Ehe, hauré de tornar a entrenar\n"

	.string "amb Kate, la meva sènior.$"


Route121_Text_JoyNotEnoughMons:
	.string "Joy: Necessites almenys dos Pokémon\n"

	.string "si ens vols desafiar!$"


Route121_Text_JessicaIntro:
	.string "Para! Mira bé els meus preciosos\n"

	.string "Pokémon!$"


Route121_Text_JessicaDefeat:
	.string "Oh, com t'atreveixes!\n"

	.string "No t'ho agafis tan seriosament!$"


Route121_Text_JessicaPostBattle:
	.string "Potser aniré a atrapar més Pokémon\n"

	.string "al Safari.$"


Route121_Text_JessicaRegister:
	.string "M'hi he pres amb calma aquest cop!\n"

	.string "El pròxim no serà així!$"


Route121_Text_JessicaRematchIntro:
	.string "Els meus preciosos Pokémon han\n"

	.string "crescut! Mira'ls bé!$"


Route121_Text_JessicaRematchDefeat:
	.string "Oh, com t'atreveixes!\n"

	.string "Encara no t'ho prens amb calma!$"


Route121_Text_JessicaPostRematch:
	.string "Potser aniré a atrapar més Pokémon\n"

	.string "al Safari.$"


Route121_Text_CristinIntro:
	.string "Tinc una rutina.\n"

	.string "Derrotar cinc Entrenadors al dia.\l"

	.string "Endevina: ets el número cinc!$"


Route121_Text_CristinDefeat:
	.string "No!\n"

	.string "Ets horrible!$"


Route121_Text_CristinPostBattle:
	.string "No esperava perdre tan fàcilment…\n"

	.string "El pròxim cop guanyaré!$"


Route121_Text_CristinRegister:
	.string "Ha estat una humiliació total!\n"

	.string "No t'oblidaré…\l"

	.string "Dóna'm el teu Pokénav!$"


Route121_Text_CristinRematchIntro:
	.string "Tinc una nova rutina.\n"

	.string "Derrotar deu Entrenadors al dia.\l"

	.string "Endevina: ets el número deu!$"


Route121_Text_CristinRematchDefeat:
	.string "Espera! Això és injust!\n"

	.string "Exigeixo la revenja!$"


Route121_Text_CristinPostRematch:
	.string "Un oponent que no puc guanyar…\n"

	.string "Snif…\l"

	.string "No m'ho puc creure…$"


Route121_Text_CaleIntro:
	.string "No veus que porto un munt de\n"

	.string "coses?\p"

	.string "I tot i així insistixes que\n"

	.string "combatim?$"


Route121_Text_CaleDefeat:
	.string "És clar que he perdut!\n"

	.string "Porto coses a les dues mans!$"


Route121_Text_CalePostBattle:
	.string "He comprat massa coses als\n"

	.string "Grans Magatzems de Lilycove.\p"

	.string "Són carretera amunt.\n"

	.string "M'agradaria tenir una Bossa com\l"

	.string "la teva.$"


Route121_Text_MylesIntro:
	.string "No hi ha res que m'agradi més que\n"

	.string "veure els Pokémon dels altres!$"


Route121_Text_MylesDefeat:
	.string "Supergenial!$"


Route121_Text_MylesPostBattle:
	.string "Són fantàstics, els teus Pokémon!\n"

	.string "Com els cries?$"


Route121_Text_PatIntro:
	.string "Vull que tothom vegi els Pokémon\n"

	.string "que he criat!$"


Route121_Text_PatDefeat:
	.string "Uau!\n"

	.string "Espectacular!$"


Route121_Text_PatPostBattle:
	.string "Crio cada Pokémon amb el mateix\n"

	.string "amor i cura: no tinc preferits.$"


Route121_Text_MarcelIntro:
	.string "Els meus Pokémon mai han perdut!\n"

	.string "Amb la pròxima victòria, els\l"

	.string "inscriuré a Concursos.$"


Route121_Text_MarcelDefeat:
	.string "Oh, i ara què ha passat?$"


Route121_Text_MarcelPostBattle:
	.string "Potser hauré d'entrenar la colla\n"

	.string "una mica més abans de cap Concurs.$"


Route123_Text_WendyIntro:
	.string "Vols saber com de fort ets?\n"

	.string "Jo seré la prova!$"


Route123_Text_WendyDefeat:
	.string "Has aprovat amb nota!$"


Route123_Text_WendyPostBattle:
	.string "Guanyar-me fins i tot a mi…\n"

	.string "La teva força és meravellosa!$"


Route123_Text_BraxtonIntro:
	.string "Sembla que tens una bona col·lecció\n"

	.string "de Medalles de Gimnàs.\p"

	.string "Deixa'm veure si ets realment digne\n"

	.string "d'aquestes Medalles!$"


Route123_Text_BraxtonDefeat:
	.string "Oh, en ets digne, sens dubte!$"


Route123_Text_BraxtonPostBattle:
	.string "Has honrat les teves Medalles\n"

	.string "en aquest combat!$"


Route123_Text_VioletIntro:
	.string "Diuen que els bons moments estan\n"

	.string "plens de bons aromes.$"


Route123_Text_VioletDefeat:
	.string "Oh…\n"

	.string "Sento l'olor amarg de la misèria…$"


Route123_Text_VioletPostBattle:
	.string "El jardí del Mestre de les Baies\n"

	.string "està ple de fragàncies animadores.$"


Route123_Text_CameronIntro:
	.string "Ser psíquic és qüestió de voluntat.\p"

	.string "M'he obligat a no perdre mai.\n"

	.string "Això em fa fort!$"


Route123_Text_CameronDefeat:
	.string "Estic trist…$"


Route123_Text_CameronPostBattle:
	.string "Ser psíquic és qüestió de voluntat.\n"

	.string "Pensava que no perdria contra tu…$"


Route123_Text_CameronRegister:
	.string "Ho pressenteixo!\n"

	.string "Tu i jo tornarem a combatre!\l"

	.string "No sé si guanyaré, però…\p"

	.string "Deixa'm veure el teu Pokénav.$"


Route123_Text_CameronRematchIntro:
	.string "M'he convençut que ja no perdré\n"

	.string "més. Això em fa fort!$"


Route123_Text_CameronRematchDefeat:
	.string "Estic trist…$"


Route123_Text_CameronPostRematch:
	.string "Hauria d'entrenar al Mt. Pyre…\n"

	.string "Així mai et guanyaré…$"


Route123_Text_JackiIntro:
	.string "No t'alegris massa si els teus\n"

	.string "Pokémon desenvolupen poders\l"

	.string "psíquics.\p"

	.string "Has de refinar-los perquè siguin\n"

	.string "realment útils.$"


Route123_Text_JackiDefeat:
	.string "Superat!$"


Route123_Text_JackiPostBattle:
	.string "Tots tenim poders psíquics.\n"

	.string "Només hem oblidat com fer-los anar.$"


Route123_Text_JackiRegister:
	.string "M'agradaria tornar a enfrontar-me\n"

	.string "a tu. Et va bé?$"


Route123_Text_JackiRematchIntro:
	.string "Has despertat els poders psíquics\n"

	.string "que tens dins?$"


Route123_Text_JackiRematchDefeat:
	.string "Increïble!$"


Route123_Text_JackiPostRematch:
	.string "El teu poder amb els Pokémon…\n"

	.string "Potser és un poder psíquic, també.$"


Route123_Text_MiuIntro:
	.string "Miu: Hola, Entrenador. Espero\n"

	.string "que els teus Pokémon no plorin\l"

	.string "quan perdin.$"


Route123_Text_MiuDefeat:
	.string "Miu: Vaja, hem perdut.$"


Route123_Text_MiuPostBattle:
	.string "Miu: Entrenador, els teus Pokémon\n"

	.string "són forts perquè sou amics.$"


Route123_Text_MiuNotEnoughMons:
	.string "Miu: No és divertit combatre si\n"

	.string "no tens dos Pokémon.$"


Route123_Text_YukiIntro:
	.string "Yuki: D'acord!\n"

	.string "Guanyarem els Pokémon de\l"

	.string "l'Entrenador!$"


Route123_Text_YukiDefeat:
	.string "Yuki: Vaja, hem perdut.$"


Route123_Text_YukiPostBattle:
	.string "Yuki: Per què ets tan fort?\n"

	.string "Mai havíem perdut.$"


Route123_Text_YukiNotEnoughMons:
	.string "Yuki: No és divertit combatre si\n"

	.string "no tens dos Pokémon.$"


Route123_Text_KindraIntro:
	.string "Mt. Pyre…\n"

	.string "On els esperits Pokémon dormen…\l"

	.string "Dormiran els teus Pokémon?$"


Route123_Text_KindraDefeat:
	.string "Desbordant de vitalitat…$"


Route123_Text_KindraPostBattle:
	.string "Mt. Pyre…\n"

	.string "On els esperits Pokémon dormen…\p"

	.string "Deu desbordar un poder que\n"

	.string "apaivaga els esperits…$"


Route123_Text_FernandoIntro:
	.string "T'apagaré els llums mentre\n"

	.string "toco aquesta cançó!$"


Route123_Text_FernandoDefeat:
	.string "Ei, espera!\n"

	.string "Encara tocava la intro!$"


Route123_Text_FernandoPostBattle:
	.string "Ets sòlid com una roca.\n"

	.string "M'agradaria escriure't una cançó.$"


Route123_Text_FernandoRegister:
	.string "El pròxim cop, escolta la cançó\n"

	.string "sencera, d'acord?$"


Route123_Text_FernandoRematchIntro:
	.string "Avui és el dia!\n"

	.string "T'apagaré els llums abans\l"

	.string "d'acabar de cantar!$"


Route123_Text_FernandoRematchDefeat:
	.string "Ei, espera!\n"

	.string "Ni he arribat a la tornada!$"


Route123_Text_FernandoPostRematch:
	.string "Pensava que estaries tan captivat\n"

	.string "per la meva cançó que perdries.$"


Route123_Text_DavisIntro:
	.string "Aquest és el meu Pokémon Insecte\n"

	.string "genial! Me'l va donar el meu germà.$"


Route123_Text_DavisDefeat:
	.string "Buaaaa!\n"

	.string "Dolent!$"


Route123_Text_DavisPostBattle:
	.string "No diguis al meu germà que he\n"

	.string "perdut.\l"

	.string "Ha de ser un secret!$"


Route123_Text_JazmynIntro:
	.string "La meva confiança pujarà si\n"

	.string "guanyo algú fort de veritat!$"


Route123_Text_JazmynDefeat:
	.string "Adéu a la meva confiança…$"


Route123_Text_JazmynPostBattle:
	.string "Diuen que no es pot jutjar una\n"

	.string "persona per l'aspecte.\p"

	.string "Però sovint, l'aspecte no enganya…$"


Route123_Text_FrederickIntro:
	.string "Hola, criatura!\n"

	.string "Tens un moment?$"


Route123_Text_FrederickDefeat:
	.string "Ah, una criatura molt capaç!\n"

	.string "Deixa'm contribuir a la teva paga.$"


Route123_Text_FrederickPostBattle:
	.string "Contribuir a la teva paga?\n"

	.string "No n'hi havia prou amb el premi?$"


Route123_Text_AlbertoIntro:
	.string "T'ho he de dir, els Pokémon Ocell\n"

	.string "són la meva obsessió!\p"

	.string "Els ocells molen!\n"

	.string "Són els millors!$"


Route123_Text_AlbertoDefeat:
	.string "Fins i tot perdent, els Pokémon\n"

	.string "Ocell molen!$"


Route123_Text_AlbertoPostBattle:
	.string "Recullo les plomes dels Pokémon\n"

	.string "Ocell que es dispersen en combat.\p"

	.string "Faré un barret amb plomes\n"

	.string "de Pokémon Ocell.$"


Route123_Text_EdIntro:
	.string "Quan no hi ha Entrenadors a prop,\n"

	.string "faig combatre els meus Pokémon\l"

	.string "entre ells. I jo miro.$"


Route123_Text_EdDefeat:
	.string "M'agraden una mica els teus Pokémon.$"


Route123_Text_EdPostBattle:
	.string "Hehe, et robo les idees de combat!\n"

	.string "Crec que em faran millor.$"


Route123_Text_JonasIntro:
	.string "He parat una emboscada, i un\n"

	.string "Entrenador ha caigut a la trampa!$"


Route123_Text_JonasDefeat:
	.string "Si no perds, com se suposa que\n"

	.string "em divertiré jugant a ninjas?$"


Route123_Text_JonasPostBattle:
	.string "El pròxim cop emboscaré un\n"

	.string "Entrenador que sembli més feble.$"


Route123_Text_KayleyIntro:
	.string "Acabo de comprar aquest para-sol.\n"

	.string "La meva simpatia hauria de pujar\l"

	.string "un terç!$"


Route123_Text_KayleyDefeat:
	.string "Ets millor que jo unes cinc\n"

	.string "vegades!$"


Route123_Text_KayleyPostBattle:
	.string "Fer servir bé els accessoris és\n"

	.string "el secret de l'atractiu de moda.$"


Route124_Text_SpencerIntro:
	.string "Ei, t'has perdut al mar?\p"

	.string "Si guanyes el meu Pokémon,\n"

	.string "et puc servir de guia.$"


Route124_Text_SpencerDefeat:
	.string "He perdut el rumb en combat!$"


Route124_Text_SpencerPostBattle:
	.string "Molta gent perd el rumb al mar.\p"

	.string "Si ets d'aquests, consulta el\n"

	.string "Mapa del Pokénav.$"


Route124_Text_RolandIntro:
	.string "Hm! Vas muntat en un Pokémon en\n"

	.string "lloc de nedar tu…\p"

	.string "T'enveig!$"


Route124_Text_RolandDefeat:
	.string "Oh!\n"

	.string "No puc…$"


Route124_Text_RolandPostBattle:
	.string "Tinc fred…\n"

	.string "He estat massa estona a l'aigua…\p"

	.string "M'agradaria anar muntat en un\n"

	.string "Pokémon com tu…$"


Route124_Text_JennyIntro:
	.string "Si simplement flotes al mar així,\n"

	.string "els Pokémon vénen a jugar.$"


Route124_Text_JennyDefeat:
	.string "Oh, vaja.\n"

	.string "He perdut.$"


Route124_Text_JennyPostBattle:
	.string "Nedant, he notat que alguns\n"

	.string "Pokémon ataquen i altres miren.\p"

	.string "Els Pokémon deuen tenir les seves\n"

	.string "pròpies personalitats.$"


Route124_Text_JennyRegister:
	.string "Per caprici, potser faré que em\n"

	.string "registris al teu Pokénav.$"


Route124_Text_JennyRematchIntro:
	.string "Si flotes al mar així,\n"

	.string "els Entrenadors et desafien!$"


Route124_Text_JennyRematchDefeat:
	.string "Que estrany…\n"

	.string "He tornat a perdre…$"


Route124_Text_JennyPostRematch:
	.string "Això no té res a veure amb res,\n"

	.string "però potser visitaré la Casa Truc.$"


Route124_Text_GraceIntro:
	.string "Estic cansada de nedar…\n"

	.string "Què et sembla un combat?$"


Route124_Text_GraceDefeat:
	.string "No sabia que eres tan fort!$"


Route124_Text_GracePostBattle:
	.string "Tot l'esforç que hi has posat\n"

	.string "t'ha fet tan fort.$"


Route124_Text_ChadIntro:
	.string "Fufufufu… Busseig a grans\n"

	.string "profunditats per amagar-me.\l"

	.string "Sondejar les profunditats és\l"

	.string "la meva especialitat!$"


Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"

	.string "M'enfonso…$"


Route124_Text_ChadPostBattle:
	.string "M'han dit que hi ha un punt\n"

	.string "de Busseig per aquí.\p"

	.string "Em ve de gust tornar a\n"

	.string "baixar…$"


Route124_Text_LilaIntro:
	.string "Lila: Ai…\p"

	.string "Aquí soc al mar, però amb qui?\n"

	.string "Amb el meu germanet!\p"

	.string "Combatim perquè no hi hagi\n"

	.string "de pensar!$"


Route124_Text_LilaDefeat:
	.string "Lila: Roy! Per culpa teva hem\n"

	.string "perdut! T'espera un càstig!$"


Route124_Text_LilaPostBattle:
	.string "Lila: Ai…\p"

	.string "Si en lloc del germanet, tingués\n"

	.string "un xicot maco al costat…$"


Route124_Text_LilaNotEnoughMons:
	.string "Lila: Penses combatre amb nosaltres?\n"

	.string "No, si no tens dos Pokémon.$"


Route124_Text_RoyIntro:
	.string "Roy: La meva germana gran és molt\n"

	.string "bona amb Pokémon!\p"

	.string "No ploris quan perdis!$"


Route124_Text_RoyDefeat:
	.string "Roy: Oh oh…\n"

	.string "La germana em renyarà…$"


Route124_Text_RoyPostBattle:
	.string "Roy: La meva germana fa molta por\n"

	.string "quan s'enfada.\p"

	.string "Per això no té xicot.$"


Route124_Text_LilaRoyRegister:
	.string "Roy: Tornaràs a combatre amb\n"

	.string "nosaltres?\l"

	.string "Però aneu suau, eh?$"


Route124_Text_RoyNotEnoughMons:
	.string "Roy: Volies combatre amb nosaltres?\n"

	.string "Porta dos Pokémon, doncs.$"


Route124_Text_LilaRematchIntro:
	.string "Lila: Ai…\p"

	.string "Aquí soc al mar, però amb qui?\n"

	.string "Amb el meu germanet!\p"

	.string "Oh, ei, quant de temps. Combatim\n"

	.string "per no pensar-hi!$"


Route124_Text_LilaRematchDefeat:
	.string "Lila: Roy!\n"

	.string "Per culpa teva hem tornat a perdre!\p"

	.string "Tindrem una sessió d'entrenament!$"


Route124_Text_LilaPostRematch:
	.string "Lila: Ai…\p"

	.string "Si tingués un xicot maco, faríem\n"

	.string "combinacions precioses…$"


Route124_Text_LilaRematchNotEnoughMons:
	.string "Lila: Penses combatre amb nosaltres?\n"

	.string "No, si no tens dos Pokémon.$"


Route124_Text_RoyRematchIntro:
	.string "Roy: Si perdem, la germana em\n"

	.string "bronca. Hi aniré a tope!$"


Route124_Text_RoyRematchDefeat:
	.string "Roy: Oh oh…\n"

	.string "La germana em tornarà a renyar.$"


Route124_Text_RoyPostRematch:
	.string "Roy: La meva germana fa molta por\n"

	.string "quan s'enfada.\p"

	.string "Em farà entrenar molt dur\n"

	.string "amb Pokémon després…$"


Route124_Text_RoyRematchNotEnoughMons:
	.string "Roy: Volies combatre amb nosaltres?\n"

	.string "Porta dos Pokémon, doncs.$"


Route124_Text_DeclanIntro:
	.string "Aquí soc nedant tot sol en aquest\n"

	.string "mar immens i bonic.\p"

	.string "No hi ha altra paraula.\n"

	.string "Això és patètic!$"


Route124_Text_DeclanDefeat:
	.string "Estic trist.\n"

	.string "Trist com el cel…$"


Route124_Text_DeclanPostBattle:
	.string "Hauria de parlar amb les nadadores\n"

	.string "i convidar-les a nedar.$"


Route124_Text_IsabellaIntro:
	.string "No perdré contra un Entrenador\n"

	.string "surfer.$"


Route124_Text_IsabellaDefeat:
	.string "Només tinc suor als ulls!\n"

	.string "No ploro!$"


Route124_Text_IsabellaPostBattle:
	.string "Per aquí es troben fragments de\n"

	.string "colors bonics.$"


Route125_Text_NolenIntro:
	.string "T'he sentit venir, així que\n"

	.string "t'he esperat!$"


Route125_Text_NolenDefeat:
	.string "Em rendeixo!$"


Route125_Text_NolenPostBattle:
	.string "El so viatja més ràpid per l'aigua\n"

	.string "que per l'aire.$"


Route125_Text_StanIntro:
	.string "Ei!\n"

	.string "Mira els meus Pokémon macos!$"


Route125_Text_StanDefeat:
	.string "He fet aigües…$"


Route125_Text_StanPostBattle:
	.string "Em va encisar l'encant de Horsea,\n"

	.string "i vaig començar a nedar també.$"


Route125_Text_TanyaIntro:
	.string "Estic cansada de nedar.\n"

	.string "Vols combatre?$"


Route125_Text_TanyaDefeat:
	.string "Ets massa!$"


Route125_Text_TanyaPostBattle:
	.string "Uf…\n"

	.string "Cap on queda Mossdeep City?$"


Route125_Text_SharonIntro:
	.string "Vols enfrontar-te als Pokémon\n"

	.string "d'Aigua que he criat?$"


Route125_Text_SharonDefeat:
	.string "Perdut…$"


Route125_Text_SharonPostBattle:
	.string "El teu poder… Ets de veritat.\n"

	.string "Estic impressionada!$"


Route125_Text_ErnestIntro:
	.string "Ei! Soc un Mariner dur i fort!\n"

	.string "He bravejat els mars del món!$"


Route125_Text_ErnestDefeat:
	.string "Grrrooooar!\n"

	.string "No he pogut guanyar!$"


Route125_Text_ErnestPostBattle:
	.string "La marea puja i baixa dins la\n"

	.string "Cova Bajura.\p"

	.string "Per cert, són unes sis hores de\n"

	.string "marea alta a baixa. Ho sabies?$"


Route125_Text_ErnestRegister:
	.string "Registra'm al teu Pokénav\n"

	.string "i et diré una cosa bona.$"


Route125_Text_ErnestRematchIntro:
	.string "Ja és hora que em prengui\n"

	.string "la revenja! Va, combat!$"


Route125_Text_ErnestRematchDefeat:
	.string "No he pogut guanyar!\n"

	.string "De cap de les maneres!$"


Route125_Text_ErnestRematchPostBattle:
	.string "La Cova Bajura…\p"

	.string "Hi ha llocs on pots o no pots\n"

	.string "accedir segons la marea.\p"

	.string "Per cert, són unes sis hores de\n"

	.string "marea alta a baixa. No ho oblidis!$"


Route125_Text_KimIntro:
	.string "Kim: Un vell graciós viu a la Cova\n"

	.string "Bajura. M'ho han dit.\l"

	.string "Tu també el vas a veure?$"


Route125_Text_KimDefeat:
	.string "Kim: Pensava que guanyaríem.$"


Route125_Text_KimPostBattle:
	.string "Kim: Un vell graciós viu a la Cova\n"

	.string "Bajura, oi?\p"

	.string "Anem a veure'l, Iris!$"


Route125_Text_KimNotEnoughMons:
	.string "Kim: No, no, no! Necessites dos\n"

	.string "Pokémon, si no, no val!$"


Route125_Text_IrisIntro:
	.string "Iris: Kim, em pots dir què busquem\n"

	.string "aquí?$"


Route125_Text_IrisDefeat:
	.string "Iris: Oh, casi quasi.$"


Route125_Text_IrisPostBattle:
	.string "Iris: Kim, de veritat entrarem a\n"

	.string "la Cova Bajura?\l"

	.string "Ens mullarem.$"


Route125_Text_IrisNotEnoughMons:
	.string "Iris: Oh, de cap manera faríem\n"

	.string "un combat de 2 contra 1.$"


Route125_Text_PresleyIntro:
	.string "Per què un Criador d'Ocells com jo\n"

	.string "sortiria al mar?$"


Route125_Text_PresleyDefeat:
	.string "D'acord.\n"

	.string "Et diré per què soc aquí.$"


Route125_Text_PresleyPostBattle:
	.string "He posat un missatge en una ampolla\n"

	.string "i l'he llançat al mar.\p"

	.string "Segur que una nadadora el\n"

	.string "trobarà!$"


Route125_Text_AuronIntro:
	.string "Ei! Eres tu qui llençava escombraries\n"

	.string "al mar?$"


Route125_Text_AuronDefeat:
	.string "Oh, no eres tu qui llençava\n"

	.string "escombraries al mar.$"


Route125_Text_AuronPostBattle:
	.string "Abans he trobat una ampolla lletja\n"

	.string "flotant a les ones.\p"

	.string "M'indigna que algú contamini\n"

	.string "el mar!$"


Route126_Text_BarryIntro:
	.string "Nedar és un exercici de cos sencer!\n"

	.string "Et posaràs en forma!$"


Route126_Text_BarryDefeat:
	.string "Ho admeto!\n"

	.string "Guanyes!$"


Route126_Text_BarryPostBattle:
	.string "Gràcies a la meva rutina de natació…\n"

	.string "Mira! Admira aquest físic!$"


Route126_Text_DeanIntro:
	.string "Aquesta muntanya blanca de roca\n"

	.string "imponent és Sootopolis City.$"


Route126_Text_DeanDefeat:
	.string "M'han derrotat?$"


Route126_Text_DeanPostBattle:
	.string "No trobo l'entrada a Sootopolis.\n"

	.string "On deu ser?$"


Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"

	.string "Soc una sirena!$"


Route126_Text_NikkiDefeat:
	.string "La meva fantasia ha esclatat com\n"

	.string "una bombolla! Blub, blub, blub…$"


Route126_Text_NikkiPostBattle:
	.string "M'has derrotat… Vull desaparèixer\n"

	.string "en una onada de desesperació…$"


Route126_Text_BrendaIntro:
	.string "Hola, petit!\n"

	.string "Vols un combat?$"


Route126_Text_BrendaDefeat:
	.string "Oh, nooooo!$"


Route126_Text_BrendaPostBattle:
	.string "M'encanta rebolcar-me amb Pokémon\n"

	.string "al mar!$"


Route126_Text_PabloIntro:
	.string "Mira aquest cos esculpit!\n"

	.string "Estic més definit que un Cinturó\l"

	.string "Negre!$"


Route126_Text_PabloDefeat:
	.string "Ui! Massa fort!\n"

	.string "No està malament!$"


Route126_Text_PabloPostBattle:
	.string "Perdre contra tu m'ha estimulat!\n"

	.string "Entrenaré més dur!$"


Route126_Text_PabloRegister:
	.string "Sí, no estàs gens malament!\n"

	.string "M'agradaria conèixer-te més!$"


Route126_Text_PabloRematchIntro:
	.string "Mira aquest cos preciós!\n"

	.string "Estic més definit que un Nadador!$"


Route126_Text_PabloRematchDefeat:
	.string "Ui! Realment massa fort!\n"

	.string "No està malament!$"


Route126_Text_PabloPostRematch:
	.string "Entrenaré encara més dur!\n"

	.string "Ets un gran motivador!\l"

	.string "Has de tornar!$"


Route126_Text_LeonardoIntro:
	.string "L'any passat no sabia nedar,\n"

	.string "però ara soc un Nadador decent.\p"

	.string "Crec que soc capaç de tot.$"


Route126_Text_LeonardoDefeat:
	.string "Uf, ser cobdiciós no m'ha servit\n"

	.string "de res.$"


Route126_Text_LeonardoPostBattle:
	.string "Si practiques una cosa,\n"

	.string "milloraràs.\p"

	.string "Ets jove: no tinguis por de\n"

	.string "provar coses noves!$"


Route126_Text_IsobelIntro:
	.string "Si t'entra aigua de mar pel nas,\n"

	.string "no és horrible?$"


Route126_Text_IsobelDefeat:
	.string "Ack! Tu…\n"

	.string "Glub!$"


Route126_Text_IsobelPostBattle:
	.string "Ooh, he empassat una mica d'aigua!\n"

	.string "És amarga! És salada!!$"


Route126_Text_SiennaIntro:
	.string "Hi poso tot el cor!$"


Route126_Text_SiennaDefeat:
	.string "Tu hi posaves més cor!$"


Route126_Text_SiennaPostBattle:
	.string "He de refrescar-me ara…\n"

	.string "Crec que bussejaré.$"


Route127_Text_CamdenIntro:
	.string "T'ho veig a la cara.\n"

	.string "Em vols desafiar.$"


Route127_Text_CamdenDefeat:
	.string "Awawawawawa…$"


Route127_Text_CamdenPostBattle:
	.string "Un bon combat em deixa sentint-me\n"

	.string "fresc i serè.$"


Route127_Text_DonnyIntro:
	.string "Tens un rival contra qui odies\n"

	.string "perdre?$"


Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"

	.string "Odio perdre!$"


Route127_Text_DonnyPostBattle:
	.string "Si tens un rival, no tens la sensació\n"

	.string "que has de seguir millorant?$"


Route127_Text_JonahIntro:
	.string "Pescant, he assolit un estat de\n"

	.string "calma serena…\p"

	.string "Permeteu-me demostrar-ho…$"


Route127_Text_JonahDefeat:
	.string "Tot i perdre, el meu cor segueix\n"

	.string "en calma…$"


Route127_Text_JonahPostBattle:
	.string "No importa que no piqui res.\n"

	.string "El fil segueix a l'aigua…$"


Route127_Text_HenryIntro:
	.string "Ep! No em diguis que he enganxat\n"

	.string "un Pokémon de Surf?$"


Route127_Text_HenryDefeat:
	.string "No puc seguir-te el ritme!$"


Route127_Text_HenryPostBattle:
	.string "Seria un problema si pesqués\n"

	.string "un dels teus Pokémon durs!$"


Route127_Text_RogerIntro:
	.string "Ei! Això és un duel entre un fan\n"

	.string "Pokémon i un aficionat de la pesca!$"


Route127_Text_RogerDefeat:
	.string "No! El fil s'ha embolicat!\n"

	.string "S'ha acabat la festa!$"


Route127_Text_RogerPostBattle:
	.string "El meu fil de pescar balla!\n"

	.string "El tango de l'embolic! Hahaha!$"


Route127_Text_AidanIntro:
	.string "Els Pokémon Ocell tenen una visió\n"

	.string "excel·lent.\l"

	.string "Divisen preses des de gran alçada.$"


Route127_Text_AidanDefeat:
	.string "Uf… Em rendeixo.$"


Route127_Text_AidanPostBattle:
	.string "Hi ha molts punts de busseig\n"

	.string "al mar d'aquí.\p"

	.string "Es veuen fàcilment des del cel\n"

	.string "pel seu color més fosc.$"


Route127_Text_KojiIntro:
	.string "Corre descalç.\n"

	.string "Això t'endurarà les plantes!$"


Route127_Text_KojiDefeat:
	.string "Au!\n"

	.string "Se m'ha ficat un còdol sota l'ungla!$"


Route127_Text_KojiPostBattle:
	.string "Anar descalç és genial.\n"

	.string "Però les teves sabatilles també.$"


Route127_Text_KojiRegister:
	.string "Això faig amb els qui em guanyen!\n"

	.string "Espero que ho repetim.$"


Route127_Text_KojiRematchIntro:
	.string "Segueixo corrent descalç cada dia.\n"

	.string "Les meves plantes són dures!$"


Route127_Text_KojiRematchDefeat:
	.string "Au!\n"

	.string "Se m'han clavat còdols als arcs!$"


Route127_Text_KojiPostRematch:
	.string "Vols anar descalç una estona?\n"

	.string "Així puc provar les teves sabatilles?$"


Route127_Text_AthenaIntro:
	.string "Hauríem de fer un combat lent\n"

	.string "i metòdic.$"


Route127_Text_AthenaDefeat:
	.string "No m'has donat temps\n"

	.string "per a cap estratègia.$"


Route127_Text_AthenaPostBattle:
	.string "Quan estic envoltada del mar i cel\n"

	.string "blaus, sembla que el temps s'alenti.$"


Route128_Text_IsaiahIntro:
	.string "Ever Grande City encara queda\n"

	.string "molt lluny…$"


Route128_Text_IsaiahDefeat:
	.string "La meva primera victòria també\n"

	.string "sembla molt llunyana…$"


Route128_Text_IsaiahPostBattle:
	.string "Tota la meva vida he perdut,\n"

	.string "però no em rendiré mai!$"


Route128_Text_IsaiahRegister:
	.string "Sé que ara no soc bo, però crec\n"

	.string "que algun dia guanyaré.\p"

	.string "Registra'm al teu Pokénav, sisplau.$"


Route128_Text_IsaiahRematchIntro:
	.string "Encara em sento bé. Seguiré nedant\n"

	.string "cap a Ever Grande City.$"


Route128_Text_IsaiahRematchDefeat:
	.string "Encara no he tastat la victòria…$"


Route128_Text_IsaiahPostRematch:
	.string "Algun dia arribaré a Ever Grande\n"

	.string "City on algun dia guanyaré…$"


Route128_Text_KatelynIntro:
	.string "En un triatló has de nedar, pedalar\n"

	.string "i córrer una marató.\p"

	.string "És una cursa esgotadora de tres\n"

	.string "proves.$"


Route128_Text_KatelynDefeat:
	.string "Un combat Pokémon també esgota…$"


Route128_Text_KatelynPostBattle:
	.string "Ara he de pedalar, però…\n"

	.string "Estic a punt de llençar la tovallola…$"


Route128_Text_KatelynRegister:
	.string "Bé, treure'n el millor. M'agradaria\n"

	.string "una revenja algun dia.$"


Route128_Text_KatelynRematchIntro:
	.string "Un triatló és llarg. Però el camí\n"

	.string "per ser Campió Pokémon també és\l"

	.string "llarg i esgotador.$"


Route128_Text_KatelynRematchDefeat:
	.string "Un combat Pokémon és realment\n"

	.string "dur i implacable…$"


Route128_Text_KatelynPostRematch:
	.string "Hauries de pensar seriosament\n"

	.string "en els reptes del Camí Victòria.$"


Route128_Text_AlexaIntro:
	.string "Hem treballat tan dur per aspirar\n"

	.string "a la Lliga Pokémon…\p"

	.string "No ens podem permetre perdre!$"


Route128_Text_AlexaDefeat:
	.string "Oh!\n"

	.string "Com ha pogut passar?!$"


Route128_Text_AlexaPostBattle:
	.string "Després de tot el que he fet per\n"

	.string "arribar aquí, no em rendiré per\l"

	.string "un revés.$"


Route128_Text_RubenIntro:
	.string "No hi ha Entrenador més fort que jo!$"


Route128_Text_RubenDefeat:
	.string "No pot ser!$"


Route128_Text_RubenPostBattle:
	.string "Probablement no hi ha Entrenador\n"

	.string "més fort que tu!$"


Route128_Text_WayneIntro:
	.string "Vull visitar Ever Grande, així que\n"

	.string "he pescat un Pokémon que sap\l"

	.string "Cascada per pujar les cascades.$"


Route128_Text_WayneDefeat:
	.string "Estic desconsollat!$"


Route128_Text_WaynePostBattle:
	.string "Uff, quina ràbia!\p"

	.string "El meu Pokémon sap Cascada, però\n"

	.string "no tinc la Medalla de Sootopolis!$"


Route128_Text_HarrisonIntro:
	.string "Fas una pinta de molt dur.\n"

	.string "Em pregunto si puc guanyar?$"


Route128_Text_HarrisonDefeat:
	.string "Au!\n"

	.string "Suposo que era impossible guanyar.$"


Route128_Text_HarrisonPostBattle:
	.string "Hi ha Entrenadors molt durs\n"

	.string "als voltants d'Ever Grande.\p"

	.string "Creus que no estic a l'alçada?$"


Route128_Text_CarleeIntro:
	.string "El sol sembla més intens\n"

	.string "en aquesta zona.$"


Route128_Text_CarleeDefeat:
	.string "No veia bé per culpa de la\n"

	.string "llum del sol.$"


Route128_Text_CarleePostBattle:
	.string "Hauria de tornar aviat.\n"

	.string "He de tornar-me a posar crema.$"


Route129_Text_ChaseIntro:
	.string "És el meu primer triatló.\n"

	.string "Estic tens i nerviós!$"


Route129_Text_ChaseDefeat:
	.string "Wroooaaar!\n"

	.string "No he pogut guanyar!$"


Route129_Text_ChasePostBattle:
	.string "Si estic tot tens, no podré\n"

	.string "donar el màxim.$"


Route129_Text_AllisonIntro:
	.string "Estic enmig d'un triatló,\n"

	.string "però sí, per què no combatem?$"


Route129_Text_AllisonDefeat:
	.string "Estava segura de guanyar!$"


Route129_Text_AllisonPostBattle:
	.string "Saps què és el millor dels\n"

	.string "triatlons?\p"

	.string "Posar a prova els límits de la\n"

	.string "teva força i resistència contra\l"

	.string "la Mare Natura!$"


Route129_Text_ReedIntro:
	.string "Epa, epa!\n"

	.string "Anem-hi!$"


Route129_Text_ReedDefeat:
	.string "Derrotat, derrotat.\n"

	.string "S'ha acabat!$"


Route129_Text_ReedPostBattle:
	.string "No hi ha res per al perdedor.\n"

	.string "Hora de tornar a casa.$"


Route129_Text_TishaIntro:
	.string "Per què tens tanta pressa?\n"

	.string "Anem amb calma.$"


Route129_Text_TishaDefeat:
	.string "Oh, vaja.\n"

	.string "Volia relaxar-me una mica més…$"


Route129_Text_TishaPostBattle:
	.string "No t'agrada equivocar-te quan\n"

	.string "vas amb pressa?\p"

	.string "Per això intento anar amb calma.$"


Route129_Text_ClarenceIntro:
	.string "Fer Surf no és tan fàcil com sembla,\n"

	.string "oi?$"


Route129_Text_ClarenceDefeat:
	.string "Guanyar tampoc és fàcil.$"


Route129_Text_ClarencePostBattle:
	.string "Aspires a la Lliga Pokémon?\n"

	.string "Segueix endavant!$"


Route130_Text_RodneyIntro:
	.string "Quina sorpresa! No esperava trobar\n"

	.string "un Entrenador al mar.\p"

	.string "Crec que hem de combatre!$"


Route130_Text_RodneyDefeat:
	.string "Aquesta criatura és molt dura…$"


Route130_Text_RodneyPostBattle:
	.string "Els teus ulls tenen la mirada\n"

	.string "d'algú que ha superat reptes durs\l"

	.string "i ha guanyat. Et queda bé!$"


Route130_Text_KatieIntro:
	.string "En el mar blau profund,\n"

	.string "el meu cor ferit troba\l"

	.string "consol entre les ones.$"


Route130_Text_KatieDefeat:
	.string "Com el vast mar blau,\n"

	.string "el món dels Pokémon amaga\l"

	.string "profunditats increïbles.$"


Route130_Text_KatiePostBattle:
	.string "Les criatures del món somien\n"

	.string "amb arribar a ser\l"

	.string "el Campió Pokémon.$"


Route130_Text_SantiagoIntro:
	.string "Flotar al mar obert així…\n"

	.string "És pacífic.$"


Route130_Text_SantiagoDefeat:
	.string "Havia de ser menys pacífic!$"


Route130_Text_SantiagoPostBattle:
	.string "Nedar i combatre així…\n"

	.string "Soc un tio feliç…$"


Route131_Text_RichardIntro:
	.string "El mar és ple de Pokémon.\n"

	.string "No és fàcil nedar, et dic.$"


Route131_Text_RichardDefeat:
	.string "Els Pokémon criats per Entrenadors\n"

	.string "són molt durs…$"


Route131_Text_RichardPostBattle:
	.string "Buf… Buf…\n"

	.string "Estic destrossat…\p"

	.string "Anar és fàcil. Tornar és el\n"

	.string "que costa.\p"

	.string "Em quedarà energia per la\n"

	.string "tornada?$"


Route131_Text_HermanIntro:
	.string "El mar… El mar… El mar…\n"

	.string "Mar fins on em dona la vista!\l"

	.string "Estic fart del mar!$"


Route131_Text_HermanDefeat:
	.string "Bah!$"


Route131_Text_HermanPostBattle:
	.string "Estic fart del mar, però nedo.\p"

	.string "Soc un nedador nat!\n"

	.string "Això soc.$"


Route131_Text_SusieIntro:
	.string "Ei, bonic, espera!\n"

	.string "Hauríem de combatre!$"


Route131_Text_SusieDefeat:
	.string "Ets dur malgrat la teva\n"

	.string "aparença!$"


Route131_Text_SusiePostBattle:
	.string "Has vist aquell tio que es queixa\n"

	.string "que està fart del mar?\p"

	.string "Només diu.\n"

	.string "Està perdudament enamorat del mar!$"


Route131_Text_KaraIntro:
	.string "Per què als homes els agraden tant\n"

	.string "els banyadors?\p"

	.string "Tots em miren!$"


Route131_Text_KaraDefeat:
	.string "No puc més!$"


Route131_Text_KaraPostBattle:
	.string "Potser no és el banyador el que\n"

	.string "fa que els homes mirin.\l"

	.string "Deu ser la meva bellesa!$"


Route131_Text_ReliIntro:
	.string "Reli: Treballarem junts com a\n"

	.string "germans per desafiar-te!$"


Route131_Text_ReliDefeat:
	.string "Reli: No hem pogut guanyar ni\n"

	.string "treballant junts…$"


Route131_Text_ReliPostBattle:
	.string "Reli: La gent de Pacifidlog viu\n"

	.string "amb el mar i els Pokémon des\l"

	.string "que neixen.$"


Route131_Text_ReliNotEnoughMons:
	.string "Reli: No tens dos Pokémon?\n"

	.string "No podrem gaudir del combat.$"


Route131_Text_IanIntro:
	.string "Ian: Ho dono tot juntament amb\n"

	.string "la meva germana!$"


Route131_Text_IanDefeat:
	.string "Ian: Ho he donat tot amb la\n"

	.string "germana, però no hem guanyat…$"


Route131_Text_IanPostBattle:
	.string "Ian: Saps que Pacifidlog és\n"

	.string "un poble flotant?\p"

	.string "Doncs, on hi hagi mar,\n"

	.string "allà és Pacifidlog!$"


Route131_Text_IanNotEnoughMons:
	.string "Ian: Si tens dos Pokémon,\n"

	.string "t'ho posarem difícil!$"


Route131_Text_TaliaIntro:
	.string "Si em guanyes, et donaré una\n"

	.string "informació genial!$"


Route131_Text_TaliaDefeat:
	.string "Oh?\n"

	.string "He perdut?$"


Route131_Text_TaliaPostBattle:
	.string "Hi ha un lloc estrany a prop.\n"

	.string "Hi ha una torre enorme.\l"

	.string "Per què no hi fas un cop d'ull?$"


Route131_Text_KevinIntro:
	.string "La gent de Pacifidlog és\n"

	.string "pacífica.\p"

	.string "Mai no s'enfaden.\n"

	.string "Jo tampoc.$"


Route131_Text_KevinDefeat:
	.string "Ups!$"


Route131_Text_KevinPostBattle:
	.string "Tsc! …Oh, espera.\n"

	.string "No estic enfadat. De veritat!\p"

	.string "Però, noi, ets fort!\n"

	.string "Hahaha!$"


Route132_Text_GilbertIntro:
	.string "De petit em refredava sempre, però\n"

	.string "em vaig posar en forma quan vaig\l"

	.string "començar a nedar.$"


Route132_Text_GilbertDefeat:
	.string "Necessito més poder…$"


Route132_Text_GilbertPostBattle:
	.string "Els Entrenadors viatgen per camps\n"

	.string "i muntanyes, així que deuen estar\l"

	.string "en forma.$"


Route132_Text_DanaIntro:
	.string "Intento no nedar on els corrents\n"

	.string "són massa forts.$"


Route132_Text_DanaDefeat:
	.string "Oh, no, sisplau!$"


Route132_Text_DanaPostBattle:
	.string "Si m'emporta el corrent, perdré\n"

	.string "tota orientació…$"


Route132_Text_RonaldIntro:
	.string "Guanyar o perdre, no ho sabràs\n"

	.string "fins que ho provis!$"


Route132_Text_RonaldDefeat:
	.string "Uaah!\n"

	.string "M'he enfonsat en la derrota!$"


Route132_Text_RonaldPostBattle:
	.string "Mai combat quan sé que guanyaré.\n"

	.string "M'agrada combatre al límit entre\l"

	.string "la victòria i la derrota!$"


Route132_Text_KiyoIntro:
	.string "Penso en Pokémon 24 hores al dia.\n"

	.string "Com podries guanyar-me?$"


Route132_Text_KiyoDefeat:
	.string "Perdo.\n"

	.string "Admeto la derrota.$"


Route132_Text_KiyoPostBattle:
	.string "Urggh…\n"

	.string "Ets un fanàtic dels Pokémon, oi?\p"

	.string "Tu també deus pensar en Pokémon\n"

	.string "24 hores al dia, no?$"


Route132_Text_MakaylaIntro:
	.string "Sempre soc amb el meu marit,\n"

	.string "però puc guanyar sense ell.$"


Route132_Text_MakaylaDefeat:
	.string "Oh, suposo que no he estat prou bona.$"


Route132_Text_MakaylaPostBattle:
	.string "Aquell jove de per allà s'assembla\n"

	.string "al meu marit de jove.\p"

	.string "M'està fent posar vermella!$"


Route132_Text_JonathanIntro:
	.string "Algú m'ha estat observant fixament.\n"

	.string "Eres tu?$"


Route132_Text_JonathanDefeat:
	.string "Uau!\n"

	.string "Això sí que és ser fort!$"


Route132_Text_JonathanPostBattle:
	.string "No puc treure'm la sensació que\n"

	.string "algú m'observa.\p"

	.string "No em puc concentrar!$"


Route132_Text_PaxtonIntro:
	.string "On deu haver anat la meva dona?\n"

	.string "Sempre soc amb ella.\l"

	.string "Em pregunto si puc guanyar sol.$"


Route132_Text_PaxtonDefeat:
	.string "Ah, ja veig que no he pogut\n"

	.string "guanyar sol, al final.$"


Route132_Text_PaxtonPostBattle:
	.string "La meva dona em deu estar buscant.\n"

	.string "Millor que la trobi de seguida.$"


Route132_Text_DarcyIntro:
	.string "M'agradava entrenar aquí sola.\n"

	.string "No m'agrada que vingui tanta gent!$"


Route132_Text_DarcyDefeat:
	.string "D'acord! No em queixaré de que\n"

	.string "hi hagi altra gent.$"


Route132_Text_DarcyPostBattle:
	.string "Suposo que puc fer parella amb\n"

	.string "aquell vell i desafiar l'altre equip.$"


Route133_Text_FranklinIntro:
	.string "El corrent t'ha portat aquí també?\n"

	.string "Devia ser cosa del destí.\l"

	.string "Combatim!$"


Route133_Text_FranklinDefeat:
	.string "Fort!\n"

	.string "Massa!$"


Route133_Text_FranklinPostBattle:
	.string "Quina mala sort que un Entrenador\n"

	.string "tan dur com tu derivés fins aquí…\l"

	.string "Dec estar maleït…$"


Route133_Text_DebraIntro:
	.string "He portat una vida de penes…\n"

	.string "M'han abandonat, i he derivat\l"

	.string "fins aquí…$"


Route133_Text_DebraDefeat:
	.string "Una altra derrota…$"


Route133_Text_DebraPostBattle:
	.string "Una vida a la deriva…\n"

	.string "No la vull més!$"


Route133_Text_LindaIntro:
	.string "Benvingut!\n"

	.string "T'esperava!$"


Route133_Text_LindaDefeat:
	.string "No! Sisplau!$"


Route133_Text_LindaPostBattle:
	.string "Un nen Entrenador fort…\n"

	.string "Que molest!$"


Route133_Text_WarrenIntro:
	.string "Vull guanyar com tothom, però no\n"

	.string "criaré Pokémon com tothom.$"


Route133_Text_WarrenDefeat:
	.string "Maleït sigui!\n"

	.string "El meu mètode encara és massa fluix!$"


Route133_Text_WarrenPostBattle:
	.string "És molt més divertit fer les coses\n"

	.string "com vull que no com tothom.\l"

	.string "Vull dir, és obvi!$"


Route133_Text_BeckIntro:
	.string "He vingut fins aquí amb els meus\n"

	.string "Pokémon Ocell.$"


Route133_Text_BeckDefeat:
	.string "Tu…\n"

	.string "Ets increïblement genial!$"


Route133_Text_BeckPostBattle:
	.string "M'agradaria tornar a Fortree,\n"

	.string "però aquest lloc m'agrada també.$"


Route133_Text_MollieIntro:
	.string "Dec haver combat milers de\n"

	.string "vegades. He perdut el compte.$"


Route133_Text_MollieDefeat:
	.string "Potser he perdut milers de cops,\n"

	.string "però una derrota encara fa mal.$"


Route133_Text_MolliePostBattle:
	.string "Segueix així, jove. Per arribar\n"

	.string "a ser com el meu marit i jo.$"


Route133_Text_ConorIntro:
	.string "Els joves es deixen portar massa.\n"

	.string "No tenen direcció.$"


Route133_Text_ConorDefeat:
	.string "Tens un ferm sentit del propòsit.$"


Route133_Text_ConorPostBattle:
	.string "No deixis que els altres et desvïin.\n"

	.string "No perdis la direcció quan creixis.$"


Route134_Text_JackIntro:
	.string "Fins i tot els Pokémon que saben\n"

	.string "nedar són arrossegats pels corrents.$"


Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"


Route134_Text_JackPostBattle:
	.string "Crec que els Pokémon gaudeixen\n"

	.string "dels corrents ràpids d'aquí.$"


Route134_Text_LaurelIntro:
	.string "Els meus Luvdisc busquen un combat\n"

	.string "divertit. T'hi apuntes?$"


Route134_Text_LaurelDefeat:
	.string "Ups!$"


Route134_Text_LaurelPostBattle:
	.string "Hi ha un col·leccionista que busca\n"

	.string "les Escates de Luvdisc.$"


Route134_Text_AlexIntro:
	.string "Au! Prou descans, colla!\n"

	.string "Hora de combatre!$"


Route134_Text_AlexDefeat:
	.string "Un altre cop esgotats…$"


Route134_Text_AlexPostBattle:
	.string "Els meus Pokémon Ocell es cansen\n"

	.string "ràpid després d'un vol llarg…$"


Route134_Text_HitoshiIntro:
	.string "Ets un Entrenador Pokémon.\n"

	.string "No calen paraules. Combat.$"


Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"

	.string "… … … … … …$"


Route134_Text_HitoshiPostBattle:
	.string "He estat jo qui t'ha desafiat,\n"

	.string "i he perdut. Tinc molta vergonya…$"


Route134_Text_AaronIntro:
	.string "La marea salvatge d'aquí serveix\n"

	.string "per fer-nos més forts que mai.$"


Route134_Text_AaronDefeat:
	.string "Admeto la derrota de bon grat.$"


Route134_Text_AaronPostBattle:
	.string "Tornarem a entrenar a Cascada\n"

	.string "Meteòrica.\p"

	.string "Si vols, hauries d'anar-hi també.\n"

	.string "Segur que t'endurarà!$"


Route134_Text_KelvinIntro:
	.string "La-la nostra barca!\n"

	.string "La marea se l'ha endut!$"


Route134_Text_KelvinDefeat:
	.string "Awawawawah!\n"

	.string "Para, sisplau! Para!$"


Route134_Text_KelvinPostBattle:
	.string "Si no podem fer Surf, com se suposa\n"

	.string "que tornarem a casa?\p"

	.string "Sé que un Pokémon debilitat pot\n"

	.string "fer Surf, però no em sembla bé.$"


Route134_Text_MarleyIntro:
	.string "Poden els teus Pokémon esquivar\n"

	.string "els nostres atacs fulgurants?$"


Route134_Text_MarleyDefeat:
	.string "No sabia que existís tal tècnica!\n"

	.string "Ens has derrotat completament.$"


Route134_Text_MarleyPostBattle:
	.string "No he perdut la passió per la\n"

	.string "velocitat. Ho intentaré més.$"


Route134_Text_ReynaIntro:
	.string "Els meus Pokémon no cauen\n"

	.string "fàcilment!$"


Route134_Text_ReynaDefeat:
	.string "De broma!\n"

	.string "Explica'm com he perdut!$"


Route134_Text_ReynaPostBattle:
	.string "Haha!\n"

	.string "Has guanyat, d'acord!\p"

	.string "Tornaré a pujar desafiant\n"

	.string "Entrenadors que trobi pel camí!$"


Route134_Text_HudsonIntro:
	.string "Escolta, has vist un altre Mariner\n"

	.string "per aquí?$"


Route134_Text_HudsonDefeat:
	.string "Això sí que és una cosa!$"


Route134_Text_HudsonPostBattle:
	.string "La nostra barca ha derivat al mar.\p"

	.string "El meu company és una mica tímid,\n"

	.string "i estic preocupat per ell.$"

