gTrickHouse_Mechadoll_Oddish::
	.string "Oddish$"

gTrickHouse_Mechadoll_Poochyena::
	.string "Poochyena$"

gTrickHouse_Mechadoll_Taillow::
	.string "Taillow$"

gTrickHouse_Mechadoll_Azurill::
	.string "Azurill$"

gTrickHouse_Mechadoll_Lotad::
	.string "Lotad$"

gTrickHouse_Mechadoll_Wingull::
	.string "Wingull$"

gTrickHouse_Mechadoll_Dustox::
	.string "Dustox$"

gTrickHouse_Mechadoll_Zubat::
	.string "Zubat$"

gTrickHouse_Mechadoll_Nincada::
	.string "Nincada$"

gTrickHouse_Mechadoll_Ralts::
	.string "Ralts$"

gTrickHouse_Mechadoll_Zigzagoon::
	.string "Zigzagoon$"

gTrickHouse_Mechadoll_Slakoth::
	.string "Slakoth$"

gTrickHouse_Mechadoll_Poochyena2::
	.string "Poochyena$"

gTrickHouse_Mechadoll_Shroomish::
	.string "Shroomish$"

gTrickHouse_Mechadoll_Zigzagoon2::
	.string "Zigzagoon$"

gTrickHouse_Mechadoll_Poochyena3::
	.string "Poochyena$"

gTrickHouse_Mechadoll_Zubat2::
	.string "Zubat$"

gTrickHouse_Mechadoll_Carvanha::
	.string "Carvanha$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "Remei Cremada$"

gTrickHouse_Mechadoll_HarborMail::
	.string "Carta Port$"

gTrickHouse_Mechadoll_SamePrice::
	.string "Mateix preu$"

gTrickHouse_Mechadoll_60Yen::
	.string "¥60$"

gTrickHouse_Mechadoll_55Yen::
	.string "¥55$"

gTrickHouse_Mechadoll_Nothing::
	.string "Res$"

gTrickHouse_Mechadoll_CostMore::
	.string "Costaran més.$"

gTrickHouse_Mechadoll_CostLess::
	.string "Costaran menys.$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "Mateix preu$"

gTrickHouse_Mechadoll_Male::
	.string "Mascle$"

gTrickHouse_Mechadoll_Female::
	.string "Femella$"

gTrickHouse_Mechadoll_Neither::
	.string "Cap dels dos$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "Homes grans$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "Dones grans$"

gTrickHouse_Mechadoll_SameNumber::
	.string "Mateix nombre$"

gTrickHouse_Mechadoll_None::
	.string "Cap$"

gTrickHouse_Mechadoll_One::
	.string "1$"

gTrickHouse_Mechadoll_Two::
	.string "2$"

gTrickHouse_Mechadoll_Two2::
	.string "2$"

gTrickHouse_Mechadoll_Three::
	.string "3$"

gTrickHouse_Mechadoll_Four::
	.string "4$"

gTrickHouse_Mechadoll_Six::
	.string "6$"

gTrickHouse_Mechadoll_Seven::
	.string "7$"

gTrickHouse_Mechadoll_Eight::
	.string "8$"

gTrickHouse_Mechadoll_Six2::
	.string "6$"

gTrickHouse_Mechadoll_Seven2::
	.string "7$"

gTrickHouse_Mechadoll_Eight2::
	.string "8$"
