LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Oh, hola! Has participat en un\n"
	.string "Concurs Pokémon, oi?\l"
	.string "Es nota pel teu Pokémon.\p"
	.string "Sóc reporter. Estic fent un reportatge\n"
	.string "sobre Concursos Pokémon.\p"
	.string "Si no et fa res, estaries disposat\n"
	.string "a respondre unes preguntes?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Oh, vols?\n"
	.string "Gràcies.\p"
	.string "Breument, com descriuries el Concurs\n"
	.string "en què acabes de participar?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Ah, ja veig.\n"
	.string "Un comentari molt instructiu.\p"
	.string "Es nota bé com va ser\n"
	.string "el Concurs.\p"
	.string "Tinc una última pregunta.\p"
	.string "Quan sents la paraula "{STR_VAR_2}",\n"
	.string "quina imatge et ve al cap?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Entenc!\p"
	.string "Així que és així com imagines\n"
	.string "el concepte de "{STR_VAR_2}".\p"
	.string "Gràcies!\n"
	.string "M'has donat bones idees.\p"
	.string "Crec que podré escriure un bon\n"
	.string "reportatge sobre Concursos Pokémon.\p"
	.string "Potser, només potser, aquest\n"
	.string "reportatge arribarà a la televisió.\l"
	.string "Espero que n'estiguis pendent!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, quina llàstima…\p"
	.string "Bé, si trobes una bona història,\n"
	.string "si us plau, comparteix-la amb mi.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Esperaré amb ganes el teu proper\n"
	.string "Concurs Pokémon.$"

gTVBravoTrainerText00::
	.string "Yeah!\n"
	.string "És l'hora de Bravo Entrenador!\p"
	.string "Avui, farem el perfil d'un Pokémon\n"
	.string "que pertany a {STR_VAR_1}.\p"
	.string "Aquest Pokémon presumeix d'un Rang\n"
	.string "{STR_VAR_3} a la Categoria {STR_VAR_2}.$"

gTVBravoTrainerText01::
	.string "Us presentem {STR_VAR_2},\n"
	.string "el {STR_VAR_1}!\p"
	.string "El sobrenom {STR_VAR_2}…\p"
	.string "Fins i tot el sobrenom emet un aire\n"
	.string "que proclama "{STR_VAR_3}"!$"

gTVBravoTrainerText02::
	.string "En fi, quan {STR_VAR_1} va inscriure\n"
	.string "el Pokémon en un Concurs,\l"
	.string "vam aconseguir obtenir unes quantes\l"
	.string "cites apassionades del company fidel.$"

gTVBravoTrainerText03::
	.string "Preguntat sobre el Concurs,\n"
	.string "{STR_VAR_1} va respondre content amb un\l"
	.string "gran somriure: "{STR_VAR_2}!"\p"
	.string "Bé, clar, el Pokémon de {STR_VAR_1}\n"
	.string "va quedar número {STR_VAR_3} al Concurs.\p"
	.string "Aquesta frase li escau perfectament\n"
	.string "a {STR_VAR_1} ara mateix, diria jo!$"

gTVBravoTrainerText04::
	.string "Preguntat sobre el Concurs,\n"
	.string "{STR_VAR_1} va respondre amb un toc\l"
	.string "d'amargor: "{STR_VAR_2}."\p"
	.string "Bé, clar, el Pokémon de {STR_VAR_1}\n"
	.string "va quedar número {STR_VAR_3} al Concurs.\p"
	.string "La decepció de {STR_VAR_1} es nota\n"
	.string "ben clara, diria jo!$"

gTVBravoTrainerText05::
	.string "No voldríeu saber també què\n"
	.string "imagina {STR_VAR_1} que és {STR_VAR_2}?\p"
	.string "Segur que sí!\n"
	.string "Així que ho vam preguntar, és clar!\p"
	.string "La resposta és ben condensada:\n"
	.string ""{STR_VAR_3}!"\p"
	.string "Això és el que el concepte de\n"
	.string "{STR_VAR_2} representa per a {STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "L'últim moviment {STR_VAR_2} usat\n"
	.string "pel {STR_VAR_1} és totalment sobre\l"
	.string ""{STR_VAR_3}"!$"

gTVBravoTrainerText07::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Esperem poder veure {STR_VAR_1}\n"
	.string "arribar encara més amunt!\p"
	.string "Això és tot per avui!\n"
	.string "Fins la propera, adéu!$"

gTVBravoTrainerText08::
	.string "Us presentem el {STR_VAR_1}!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Hola! Ets l'Entrenador que acaba\n"
	.string "de combatre, oi?\p"
	.string "Estic recopilant entrevistes amb\n"
	.string "Entrenadors d'arreu.\p"
	.string "Puc demanar-te unes paraules sobre\n"
	.string "les teves impressions del combat?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Vols? De veritat?\n"
	.string "Gràcies!\l"
	.string "Doncs, ehem…\p"
	.string "Com t'ha anat a la Torre\n"
	.string "de Combat avui?\p"
	.string "Has quedat satisfet amb el combat?\n"
	.string "O n'estàs descontent?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh…\n"
	.string "Perdona la molèstia.\p"
	.string "Si us plau, concedeix-nos una\n"
	.string "entrevista la propera vegada que\l"
	.string "visitis la Torre de Combat.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Bé, és clar!\p"
	.string "Aquesta inconfusible expressió de\n"
	.string "satisfacció a la teva cara…\p"
	.string "És obvi que has tingut un gran\n"
	.string "combat.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, ja veig…\p"
	.string "Bé, certament és difícil fer que un\n"
	.string "combat surti exactament com es\l"
	.string "tenia planejat.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Oh, oh, puc fer una pregunta més?\p"
	.string "Si haguessis de descriure les teves\n"
	.string "impressions sobre aquest combat\l"
	.string "amb una frase, quina seria?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Oh, és increïblement genial!\p"
	.string "Quina frase tan bona!\n"
	.string "Espero que et vagi bé la propera.\p"
	.string "Espero tornar-te a veure!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, ja veig…\p"
	.string "Tot i així, ser del tipus silenciós\n"
	.string "també mola, no creus?\p"
	.string "Espero que em donis l'oportunitat\n"
	.string "de compartir els teus pensaments!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Esperaré amb ganes el teu\n"
	.string "proper combat!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Yeah!\n"
	.string "És l'hora de Bravo Entrenador!\p"
	.string "Avui, farem el perfil de {STR_VAR_1},\n"
	.string "que va acceptar el repte de la\l"
	.string "Torre de Combat!\p"
	.string "Per al repte, {STR_VAR_1} va inscriure\n"
	.string "un formidable {STR_VAR_2}.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "La parella va establir un nou rècord\n"
	.string "de {STR_VAR_2} victòries seguides en\l"
	.string "competició {STR_VAR_1}!\l"
	.string "Bravo, Entrenador!$"

BravoTrainerBattleTower_Text_Lost::
	.string "El duo finalment va sucumbir davant\n"
	.string "{STR_VAR_1} en el combat número {STR_VAR_2}.\l"
	.string "Bon intent, Entrenador!\p"
	.string "Però, bé, és mala sort topar amb\n"
	.string "{STR_VAR_1} tan aviat al repte.\p"
	.string "Hem preguntat a l'Entrenador les\n"
	.string "impressions del combat amb\l"
	.string "{STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "El duo ho va guanyar tot derrotant\n"
	.string "el {STR_VAR_2} de {STR_VAR_1} totalment.\l"
	.string "Bravo, Entrenador!\p"
	.string "Vèncer fins i tot {STR_VAR_1}…\n"
	.string "Desafia tota creença! Increïble!\p"
	.string "Hem preguntat a l'Entrenador les\n"
	.string "impressions del moment de glòria.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Després d'una ratxa de victòries,\n"
	.string "la parella va sucumbir davant el\l"
	.string "{STR_VAR_2} de {STR_VAR_1}, l'últim obstacle.\p"
	.string "Bon intent, Entrenador!\p"
	.string "Tot i així, cal donar-ne mèrit.\n"
	.string "No es veuen moltes combinacions\l"
	.string "famoses com {STR_VAR_1} i {STR_VAR_2}.\p"
	.string "Hem preguntat a l'Entrenador les\n"
	.string "impressions de combatre la parella\l"
	.string "de celebritats.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Això és el que va dir l'Entrenador:\n"
	.string ""Estic satisfet!"\p"
	.string "No és una resposta refrescant?\n"
	.string "Bravo, Entrenador!\p"
	.string "No és fantàstic poder combatre\n"
	.string "amb plena satisfacció?\p"
	.string "Vaig descobrir com de satisfet\n"
	.string "quan vaig sentir l'Entrenador dir:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Això és el que va dir l'Entrenador:\n"
	.string ""No estic satisfet…"\p"
	.string "El nostre Entrenador estava una mica\n"
	.string "deprimit quan ho va dir.\p"
	.string "Tot i així, no és fàcil combatre\n"
	.string "amb plena satisfacció, oi?\p"
	.string "En fi, vaig descobrir com de\n"
	.string "descontent estava quan vaig sentir:$"

BravoTrainerBattleTower_Text_None1::
	.string "Cap$"

BravoTrainerBattleTower_Text_None2::
	.string "Cap$"

BravoTrainerBattleTower_Text_None3::
	.string "Cap$"

BravoTrainerBattleTower_Text_None4::
	.string "Cap$"

BravoTrainerBattleTower_Text_Response::
	.string ""{STR_VAR_1}."$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string ""{STR_VAR_1}."\n"
	.string "No és genial?\p"
	.string "Realment expressa l'alegria de\n"
	.string "{STR_VAR_2}, diria jo.\p"
	.string "Aquell combat amb {STR_VAR_3} al\n"
	.string "final… Realment va ser el que\l"
	.string "en diríem "{STR_VAR_1}"!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string ""{STR_VAR_1}."\n"
	.string "No és ben escaient?\p"
	.string "Aquell combat amb {STR_VAR_3} al\n"
	.string "final… No es pot descriure d'una\l"
	.string "altra manera que "{STR_VAR_1}"!\p"
	.string "La decepció de {STR_VAR_2} es nota\n"
	.string "ben clara, diria jo!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Esperem poder veure {STR_VAR_1}\n"
	.string "arribar encara més amunt!\p"
	.string "Això és tot per avui!\n"
	.string "Fins la propera, adéu!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Uau!\p"
	.string "Es veu clarament que aboquis\n"
	.string "el teu amor al teu {STR_VAR_1}.\p"
	.string "D'acord, es diu {STR_VAR_2}.\p"
	.string "Et puc demanar un favor?\p"
	.string "Sóc reporter de TV i estic fent\n"
	.string "una enquesta sobre Pokémon.\p"
	.string "Estaries disposat a respondre unes\n"
	.string "preguntes senzilles?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Genial! Gràcies!\p"
	.string "D'acord, comencem.\n"
	.string "Necessito respostes ràpides, va?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Quan vas conèixer {STR_VAR_1}\n"
	.string "per primera vegada, què vas sentir?\p"
	.string "Com descriuries els teus sentiments\n"
	.string "en aquell moment?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "El teu {STR_VAR_1} està cuidat amb amor.\p"
	.string "Si l'haguessis de comparar amb\n"
	.string "alguna cosa que t'agrada,\l"
	.string "què seria?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Aquesta pregunta també és sobre\n"
	.string "el teu estimat {STR_VAR_1}.\p"
	.string "Què va ser del {STR_VAR_1} que\n"
	.string "et va atreure?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "D'acord, té sentit.\p"
	.string "La propera pregunta potser és\n"
	.string "una mica difícil.\p"
	.string "Aquí va…\p"
	.string "Què signifiquen els Pokémon per tu?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Entenc!\p"
	.string "Hmhm…\p"
	.string "D'acord!\n"
	.string "Gràcies per ajudar-me.\p"
	.string "Ha estat divertit i instructiu\n"
	.string "xerrar amb tu.\p"
	.string "És possible que la nostra entrevista\n"
	.string "acabi a la TV. Estigues atent!\p"
	.string "D'acord, això és tot.\n"
	.string "Adéu!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, d'acord…\p"
	.string "Bé, si et ve de gust parlar-me\n"
	.string "de Pokémon, seré aquí!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "M'encanta aquesta feina: aprens\n"
	.string "sobre Pokémon fent entrevistes.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Ei, sembla que ets molt proper\n"
	.string "al teu {STR_VAR_1}.\p"
	.string "Saps què?\n"
	.string "Sóc reporter de TV.\p"
	.string "Viatjo entrevistant la gent\n"
	.string "sobre Pokémon.\p"
	.string "Em pregunto si voldries explicar-me\n"
	.string "una mica sobre el teu {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Uau, gràcies!\p"
	.string "D'acord, doncs, explica'm el que\n"
	.string "vulguis sobre el teu {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Uau…\n"
	.string "Quina història tan interessant.\p"
	.string "Realment tens molt de vincle amb\n"
	.string "{STR_VAR_1}, oi?\p"
	.string "Tinc la sensació que la teva\n"
	.string "història farà un gran programa.\p"
	.string "Et prometo que convertiré això en\n"
	.string "un programa entretingut.\l"
	.string "Estigues atent.\p"
	.string "D'acord, això és tot.\n"
	.string "Adéu!$"

gTVFanClubOpinionsText00::
	.string "Som el Club de Fans Pokémon!\p"
	.string "Estem en antena!\p"
	.string "En aquest programa, recollim les\n"
	.string "vostres opinions, i les crido\l"
	.string "en nom vostre!\l"
	.string "No és un concepte fantàstic?\p"
	.string "Avui, us portem aquest reportatge\n"
	.string "de la nostra reportera, que hem\l"
	.string "enviat al Club de Fans Pokémon.\p"
	.string "Qui és el fan Pokémon destacat\n"
	.string "d'avui?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "Sentim què té a dir {STR_VAR_1}\n"
	.string "sobre {STR_VAR_3} el {STR_VAR_2}.\p"
	.string "I cridaré aquestes paraules d'amor\n"
	.string "ben fort per la TV!\p"
	.string "Hoo-hah!\p"
	.string "Cridem!$"

gTVFanClubOpinionsText01::
	.string "Hem preguntat a {STR_VAR_1}: "Quan vas\n"
	.string "veure per primera vegada el teu\l"
	.string "{STR_VAR_2}, quin va ser el teu primer\l"
	.string "pensament?"\p"
	.string ""{STR_VAR_3}!"\p"
	.string "Yeahah! Quin crit tan bo!\p"
	.string "No et porta records d'aquells\n"
	.string "dies passats?$"

gTVFanClubOpinionsText02::
	.string "Hem preguntat a {STR_VAR_1}: "Si\n"
	.string "haguessis de comparar el teu\l"
	.string "{STR_VAR_2} amb alguna cosa, seria…"\p"
	.string "… … … … … … … …\p"
	.string ""{STR_VAR_3}!"\p"
	.string "Oh, quina idea tan original!\p"
	.string "Realment es nota la intensitat\n"
	.string "del sentiment de l'Entrenador\l"
	.string "pel {STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "I vegem…\n"
	.string "Què va ser del {STR_VAR_2}\l"
	.string "que tant va atreure {STR_VAR_1}?\p"
	.string "… … … … … … … …\p"
	.string ""{STR_VAR_3}!"\p"
	.string "Uau! Quina declaració espectacular!\p"
	.string "L'amor de l'Entrenador pel\n"
	.string "{STR_VAR_2} es nota ben clar!$"

gTVFanClubOpinionsText04::
	.string "Hm? Oh, encara hi ha més.\n"
	.string "Vegem-ho!\p"
	.string "A veure…\p"
	.string "Hem preguntat a {STR_VAR_1}: "Què\n"
	.string "signifiquen els Pokémon per tu?"\p"
	.string "… … … … … …\p"
	.string ""{STR_VAR_3}!"\p"
	.string "Bravo!\p"
	.string "El millor crit que he sentit avui!\p"
	.string ""{STR_VAR_3}!"\p"
	.string "Et fa venir ganes de cridar-ho\n"
	.string "una i altra vegada!\p"
	.string "Ara que hem cridat bé, és hora de\n"
	.string "dir adéu fins la propera!\p"
	.string "Doncs, tots plegats, un últim crit!\n"
	.string "Tots a la una…\p"
	.string ""{STR_VAR_3}!"$"

gTVFanClubText00::
	.string "Som el Club de Fans Pokémon!\p"
	.string "Estem en antena!\p"
	.string "Avui, començarem amb el Racó\n"
	.string "de l'Enquesta Pokémon.\p"
	.string "De totes les històries teixides per\n"
	.string "Pokémon i Entrenadors, quin nou\l"
	.string "drama sorprenent ens cridarà\l"
	.string "l'atenció avui?\p"
	.string "A veure…\p"
	.string "Aquesta!\p"
	.string "Començarem amb aquesta carta!\p"
	.string "És una carta de {STR_VAR_1} sobre\n"
	.string "un estimat {STR_VAR_2}.\p"
	.string "Vegem amb quanta passió pot\n"
	.string "expressar l'amor pel {STR_VAR_2}!\l"
	.string "Hmhm…$"

gTVFanClubText01::
	.string "Uau!\n"
	.string "Quina carta tan increïble!$"

gTVFanClubText02::
	.string "M'ha encantat, així que aquí la\n"
	.string "teniu una altra vegada!$"

gTVFanClubText03::
	.string "Una bona carta mereix ser llegida\n"
	.string "una i altra vegada!$"

gTVFanClubText04::
	.string "La part de "{STR_VAR_3}", realment\n"
	.string "accentua l'impacte emocional!\p"
	.string "És una gran carta amb una autèntica\n"
	.string "profunditat sentimental!$"

gTVFanClubText05::
	.string "Especialment la part de "{STR_VAR_3}"!\p"
	.string "M'encanta com s'usa "{STR_VAR_3}"!$"

gTVFanClubText06::
	.string "Per cert, i no és important, però\n"
	.string ""{STR_VAR_3}" és un gran dit.\p"
	.string "Últimament he estat usant\n"
	.string ""{STR_VAR_3}" molt en converses.$"

gTVFanClubText07::
	.string "Si hagués de puntuar aquesta carta,\n"
	.string "li donaria {STR_VAR_3} punts.\p"
	.string "La propera vegada, espero una carta\n"
	.string "encara millor, {STR_VAR_1}!\p"
	.string "Ai, mira quina hora és!\n"
	.string "Hora de dir adéu fins la propera!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\n"
	.string "Potser t'agraden els Pokémon?\p"
	.string "Estic de servei per la cadena de TV.\p"
	.string "Estic recopilant històries sobre\n"
	.string "Pokémon i Entrenadors recents.\p"
	.string "Si no et fa res, podries explicar-me\n"
	.string "alguna cosa sobre tu?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Estic recopilant històries sobre\n"
	.string "Pokémon i Entrenadors recents.\p"
	.string "Si no et fa res, podries explicar-me\n"
	.string "alguna cosa sobre tu?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, vols?\n"
	.string "Gràcies!\p"
	.string "Doncs, si us plau, explica'm alguna\n"
	.string "cosa interessant que hagis viscut\l"
	.string "recentment amb Pokémon.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, ja veig…\p"
	.string "Bé, si tens una història\n"
	.string "interessant, fes-m'ho saber.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, quina història tan edificant!\p"
	.string "M'asseguraré de fer arribar la\n"
	.string "teva història a la televisió.\p"
	.string "S'hauria d'emetre algun dia, crec,\n"
	.string "així que estigues pendent.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmm…\n"
	.string "Tinc una bona història per la TV.\p"
	.string "Millor que l'escrigui de pressa!$"

gTVRecentHappeningsText00::
	.string "Hola, és l'hora de FETS RECENTS.\p"
	.string "Per als Entrenadors Pokémon,\n"
	.string "cada dia és una aventura.\p"
	.string "El que volem fer és presentar-vos\n"
	.string "algunes d'aquestes històries.\p"
	.string "Avui, us portem la història\n"
	.string "de l'Entrenador {STR_VAR_1}.\p"
	.string "Què ha viscut {STR_VAR_1} recentment?\n"
	.string "Descobrim-ho.\p"
	.string "Vegem…$"

gTVRecentHappeningsText01::
	.string "No ha estat instructiu?\p"
	.string "La història dóna una idea clara del\n"
	.string "que {STR_VAR_1} ha viscut recentment.\l"
	.string "És com si hi haguéssim estat!$"

gTVRecentHappeningsText02::
	.string ""{STR_VAR_3}." Això\n"
	.string "accentua la història i li dóna cos.$"

gTVRecentHappeningsText03::
	.string ""{STR_VAR_3}."\n"
	.string "Això dóna sensació de lloc.\l"
	.string "Ens deixa imaginar l'escenari.$"

gTVRecentHappeningsText04::
	.string "La part de "{STR_VAR_3}"\n"
	.string "és molt expressiva.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} ha relatat una història\n"
	.string "meravellosa amb Pokémon.\p"
	.string "I ara la història de {STR_VAR_1} queda\n"
	.string "gravada a la vostra ànima.\p"
	.string "Això és tot per avui.\n"
	.string "Sintonitzeu-nos la propera vegada.$"

gTVMassOutbreakText00::
	.string "Salutacions!\n"
	.string "És l'hora de Notícies Pokémon.\p"
	.string "Acabem de rebre informació d'un\n"
	.string "esdeveniment molt rar.\p"
	.string "S'ha informat d'una aparició\n"
	.string "massiva de {STR_VAR_2} a les rodalies\l"
	.string "de {STR_VAR_1}.\p"
	.string "{STR_VAR_2}, com probablement sabeu,\n"
	.string "és conegut com un Pokémon rar\l"
	.string "i difícil de trobar.\p"
	.string "Sembla una oportunitat rara de\n"
	.string "veure la misteriosa aparició de\l"
	.string "{STR_VAR_2} en estat salvatge.\p"
	.string "Això és tot a Notícies Pokémon.$"

gTV3CheersForPokeblocksText00::
	.string "Presentador: Esperem que estigueu\n"
	.string "de bon humor, "3 Hurres pels\l"
	.string "{POKEBLOCK}s" és aquí!\p"
	.string "Avui, examinem el {POKEBLOCK}\n"
	.string "barrejat per {STR_VAR_1} i companyia.\p"
	.string "Sense demora, deixeu-me donar-lo\n"
	.string "al meu Pokémon gurmet, Gulpin.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "Gulpin: Gubi! Gubii!\p"
	.string "Presentador: I el veredicte és molt\n"
	.string "{STR_VAR_1}! Gulpin diu que fa gust\l"
	.string "de "{STR_VAR_2}!"\p"
	.string "Moltes gràcies, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "L'actuació de {STR_VAR_1} barrejant\n"
	.string "ha deixat molt a desitjar.\p"
	.string "Si aquest Entrenador pogués\n"
	.string "barrejar millor, el {POKEBLOCK}\l"
	.string "seria molt més saborós.$"

gTV3CheersForPokeblocksText03::
	.string "Gulpin: Gubi! Gubii!\p"
	.string "Presentador: Hmm… És massa\n"
	.string "{STR_VAR_1}. Gulpin diu que fa gust\l"
	.string "de "{STR_VAR_2}!"\p"
	.string "Sembla que els errors de {STR_VAR_3}\n"
	.string "han perjudicat la qualitat…$"

gTV3CheersForPokeblocksText04::
	.string "Llàstima que l'esforç de\n"
	.string "{STR_VAR_1} ha estat en va.\p"
	.string "Esperem que {STR_VAR_2} ho faci\n"
	.string "millor la propera vegada!$"

gTV3CheersForPokeblocksText05::
	.string "Sintonitzeu-nos la propera!\n"
	.string "El lema és "3 Hurres pels {POKEBLOCK}s!"$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Ei, hola!\p"
	.string "Sóc un gran fan de {STR_VAR_1}.\n"
	.string "Quina és la teva opinió de\l"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Ja veig, ja veig. Això és el que\n"
	.string "penses de l'Entrenador.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Has oblidat completament\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Sóc un gran fan de {STR_VAR_1}.\n"
	.string "Quina és la teva opinió de\l"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Com de fort puntuaries {STR_VAR_1}\n"
	.string "en una escala de cent?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Has oblidat completament\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, ja veig!\n"
	.string "Hauries de conèixer {STR_VAR_1}.\l"
	.string "Segur que també en seràs fan!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Ja veig, ja veig.\p"
	.string "Gràcies!\n"
	.string "Això és molt útil de saber.\p"
	.string "Compartiré aquesta informació amb\n"
	.string "els altres fans de {STR_VAR_1}.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Aviat hi haurà un especial de TV\n"
	.string "sobre {STR_VAR_1}.\p"
	.string "Espero que el vegis!$"

gTVTrainerFanClubSpecialText00::
	.string "Club de Fans d'Entrenadors\n"
	.string "Especial {STR_VAR_1}!\p"
	.string "Aquesta és una presentació especial\n"
	.string "per als fans de {STR_VAR_1} a Hoenn!\p"
	.string "Avui, fem la pregunta: "Què pensa\n"
	.string "la gent de {STR_VAR_1}?"\p"
	.string "Hem plantejat la pregunta a\n"
	.string "{STR_VAR_2} com a representant.\p"
	.string "Hem preguntat: "En una paraula,\n"
	.string "com descriuries {STR_VAR_1}?"\p"
	.string "La resposta: "{STR_VAR_3}."\p"
	.string "Felicitats a {STR_VAR_2}!\n"
	.string "Quina opinió tan perspicaç!\p"
	.string ""{STR_VAR_3} {STR_VAR_1}."\n"
	.string "Sona tan bé!\p"
	.string "{STR_VAR_2} també ha puntuat la\n"
	.string "força de {STR_VAR_1} de 0 a 100.$"

gTVTrainerFanClubSpecialText01::
	.string "La puntuació ha estat {STR_VAR_3} punts!\n"
	.string "Una puntuació molt alta!\p"
	.string "{STR_VAR_2} té clarament\n"
	.string "{STR_VAR_1} en alta estima.$"

gTVTrainerFanClubSpecialText02::
	.string "La puntuació ha estat {STR_VAR_3} punts!\n"
	.string "Una puntuació força bona.\p"
	.string "{STR_VAR_2} deu considerar\n"
	.string "{STR_VAR_1} un rival.$"

gTVTrainerFanClubSpecialText03::
	.string "La puntuació ha estat {STR_VAR_3} punts!\n"
	.string "Una puntuació més aviat baixa.\p"
	.string "{STR_VAR_2} deu considerar\n"
	.string "{STR_VAR_1} un simple company.$"

gTVTrainerFanClubSpecialText04::
	.string "La puntuació ha estat {STR_VAR_3} punt(s)!\n"
	.string "Una puntuació terrible.\p"
	.string "{STR_VAR_2} deu considerar\n"
	.string "{STR_VAR_1} un subordinat.$"

gTVTrainerFanClubSpecialText05::
	.string "Aquí ho teniu, amics!\p"
	.string "Crec que tots hem après alguna cosa\n"
	.string "nova sobre {STR_VAR_1}.\p"
	.string "Per acabar, us deixo amb les\n"
	.string "paraules de {STR_VAR_2}.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "I ara, és l'hora de…\n"
	.string "El Programa del Jutge de Noms.\p"
	.string "Us dic la fortuna del vostre Pokémon\n"
	.string "pel sobrenom que li heu posat.\p"
	.string "Ofereixo consells, i són consells\n"
	.string "útils els que ofereixo.\p"
	.string "Avui, faré una lectura del\n"
	.string "sobrenom {STR_VAR_3} del Pokémon\l"
	.string "{STR_VAR_2} de {STR_VAR_1}.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "Aquest sobrenom és…$"

gTVNameRaterText01::
	.string "Un sobrenom que insinua talent\n"
	.string "de moltes maneres.\p"
	.string "Animo aquest Entrenador a tenir\n"
	.string "coratge i acceptar molts reptes.$"

gTVNameRaterText02::
	.string "Un sobrenom que complementa\n"
	.string "perfectament {STR_VAR_1}, el nom de\l"
	.string "l'Entrenador.\p"
	.string "Suggereix que forjareu una bona\n"
	.string "aliança amb un temps precís.$"

gTVNameRaterText03::
	.string "Un sobrenom digne d'un Pokémon\n"
	.string "únic i individual!\p"
	.string "Si es cria bé, la singularitat\n"
	.string "d'aquest Pokémon floirà!$"

gTVNameRaterText04::
	.string "Un sobrenom que nodrirà el costat\n"
	.string "afectuós i compassiu del Pokémon.\p"
	.string "Si es cria bé, aquest Pokémon\n"
	.string "mostrarà autèntica calidesa!$"

gTVNameRaterText05::
	.string "Un sobrenom molt fi que insinua\n"
	.string "grandesa futura.\p"
	.string "Tinc curiositat pel que el futur\n"
	.string "depara a aquest Pokémon.$"

gTVNameRaterText06::
	.string "Un bon sobrenom que hauria de fer\n"
	.string "el Pokémon sa i fort!\p"
	.string "Aquest Pokémon hauria de mantenir-se\n"
	.string "en forma durant molt de temps.$"

gTVNameRaterText07::
	.string "Un bon sobrenom que hauria de fer\n"
	.string "el Pokémon molt actiu!\p"
	.string "M'imagino que aquest Pokémon serà\n"
	.string "molt fort en els combats.$"

gTVNameRaterText08::
	.string "Un sobrenom atractiu que hauria de\n"
	.string "fer el Pokémon molt encantador!\p"
	.string "No dubto que aquest Pokémon\n"
	.string "serà tot un encant als Concursos.$"

gTVNameRaterText09::
	.string "El sobrenom {STR_VAR_1} s'arreleja\n"
	.string "en la lletra "{STR_VAR_3}."\p"
	.string "Aquesta lletra és recolzada per la\n"
	.string "primera lletra "{STR_VAR_2}", que li dóna\l"
	.string "una sòlida presència com a nom.$"

gTVNameRaterText10::
	.string "El sobrenom {STR_VAR_1} té una forma\n"
	.string "molt agradable.\p"
	.string "La presència de les lletres "{STR_VAR_2}"\n"
	.string "i "{STR_VAR_3}", és remarcablement bona!$"

gTVNameRaterText11::
	.string "El sobrenom {STR_VAR_1} té un\n"
	.string "tacte sublim i fluid.\p"
	.string "El flux de la lletra inicial "{STR_VAR_2}"\n"
	.string "a "{STR_VAR_3}" és meravellós.$"

gTVNameRaterText12::
	.string "Examinem altres exemples de bons\n"
	.string "sobrenoms, d'acord?$"

gTVNameRaterText13::
	.string "Proveu això. Agafeu una part del nom\n"
	.string "de l'Entrenador {STR_VAR_1} i acabeu\l"
	.string "amb el bon sobrenom {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "El sobrenom {STR_VAR_2}{STR_VAR_3} també\n"
	.string "funcionaria força bé.$"

gTVNameRaterText15::
	.string "El nom d'espècie del Pokémon,\n"
	.string "{STR_VAR_2}, es podria usar com a base\l"
	.string "per crear el sobrenom {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} també seria un sobrenom\n"
	.string "efectiu.$"

gTVNameRaterText17::
	.string "El que sempre s'ha d'evitar és usar\n"
	.string "el nom d'una altra espècie Pokémon.\p"
	.string "Per exemple, eviteu agafar el nom\n"
	.string "de {STR_VAR_2} per fer el sobrenom\l"
	.string "{STR_VAR_1}{STR_VAR_3}. Això és inacceptable.$"

gTVNameRaterText18::
	.string "He de dir que {STR_VAR_1} és un molt\n"
	.string "bon sobrenom.\p"
	.string "Espero que l'Entrenador continuï\n"
	.string "tractant {STR_VAR_1} amb amor.\p"
	.string "Això és tot per al programa d'avui.\n"
	.string "Que ens tornem a veure.$"

gTVPokemonAnglerText00::
	.string "Pescador de {STR_VAR_2}\p"
	.string "Presentador: Hola! Avui rebrem\n"
	.string "consells per pescar {STR_VAR_2}.\p"
	.string "Guru, quin consell pots donar\n"
	.string "per atrapar {STR_VAR_2}?\p"
	.string "Guru: Hm? Atrapar {STR_VAR_2}?\n"
	.string "Bé, t'ho dic clar: tingues paciència\l"
	.string "i espera. Això és fonamental.\p"
	.string "Veus {STR_VAR_1} d'allà?\n"
	.string "Aquell Entrenador n'és un bon\l"
	.string "exemple.\p"
	.string "A aquell Entrenador ja se li\n"
	.string "han escapat {STR_VAR_3} Pokémon.\p"
	.string "Però {STR_VAR_1} espera. Sense rendir-se.\n"
	.string "Aquesta és la llei per pescar\l"
	.string "{STR_VAR_2}.\p"
	.string "Presentador: Ja veig…\p"
	.string "Oh! {STR_VAR_1} finalment ha pescat\n"
	.string "un esquiu {STR_VAR_2}!\p"
	.string "L'Entrenador sembla a punt de\n"
	.string "plorar d'alegria!\p"
	.string "Veient aquella cara de felicitat,\n"
	.string "em ve de gust anar a pescar!\p"
	.string "Espectadors, per què no aprofiteu\n"
	.string "per pescar {STR_VAR_2}?\p"
	.string "Fins la propera emissió, adéu\n"
	.string "i bona pesca a tothom!$"

gTVPokemonAnglerText01::
	.string "Pescador de {STR_VAR_2}\p"
	.string "Presentador: Hola! Avui rebrem\n"
	.string "consells per pescar {STR_VAR_2}.\p"
	.string "Guru, quin consell pots donar\n"
	.string "per atrapar {STR_VAR_2}?\p"
	.string "Guru: Hm? Atrapar {STR_VAR_2}?\n"
	.string "Bé, t'ho dic clar: usa la Canya\l"
	.string "amb vigor!\p"
	.string "Veus {STR_VAR_1} d'allà?\n"
	.string "Veus com maneja la Canya?\p"
	.string "Aquell Entrenador ja n'ha\n"
	.string "atrapat {STR_VAR_3} seguits.\p"
	.string "Presentador: Increïble!\n"
	.string "Sembla una tempesta…\p"
	.string "Veient una tècnica d'aquest\n"
	.string "calibre, em ve de gust pescar.\p"
	.string "Espectadors, per què no aprofiteu\n"
	.string "per pescar {STR_VAR_2}?\p"
	.string "Fins la propera emissió, adéu\n"
	.string "i bona pesca a tothom!$"

gTVPokemonTodayFailedText00::
	.string "Hola!\p"
	.string "És l'hora de Pokémon Avui!\p"
	.string "Germana Gran: Ei! Tothom content\n"
	.string "i animat avui?\p"
	.string "Avui, veurem el Pokémon {STR_VAR_2}\n"
	.string "de {STR_VAR_1}!\p"
	.string "Germà Gran: Sí! Això és el que\n"
	.string "farem!$"

gTVPokemonTodayFailedText01::
	.string "Oh!\n"
	.string "Parlant de {STR_VAR_1}…\p"
	.string "Germana Gran, vaig veure\n"
	.string "l'Entrenador amb els meus ulls!\p"
	.string "Germana Gran: Oh, què vas veure?\p"
	.string "Germà Gran: Bé, vaig haver d'anar\n"
	.string "de viatge a {STR_VAR_2}.\p"
	.string "Llavors vaig trobar {STR_VAR_1}, que\n"
	.string "intentava atrapar el Pokémon\l"
	.string "{STR_VAR_3}, però…$"

gTVPokemonTodayFailedText02::
	.string "El Pokémon va aconseguir escapar!\p"
	.string "Va acabar malgastant tantes\n"
	.string "Poké Balls: {STR_VAR_2}!\p"
	.string "Havíeu d'haver vist la cara de\n"
	.string "frustració de {STR_VAR_1} quan el\l"
	.string "Pokémon va fugir!$"

gTVPokemonTodayFailedText03::
	.string "Però {STR_VAR_1} la va espifiar i va\n"
	.string "fer que el Pokémon es desmaiés!\p"
	.string "Va acabar malgastant tantes\n"
	.string "Poké Balls: {STR_VAR_2}!\p"
	.string "Havíeu d'haver vist la cara de\n"
	.string "consternació de {STR_VAR_1} quan el\l"
	.string "Pokémon es va desmaiar!$"

gTVPokemonTodayFailedText04::
	.string "Germana Gran: Ei, escolta!\n"
	.string "Això no està bé!\p"
	.string "No hauries de riure't de les\n"
	.string "desgràcies dels altres!\p"
	.string "Oh, pobre {STR_VAR_1}.\n"
	.string "Quina llàstima!\p"
	.string "Germà Gran: Tens raó!\n"
	.string "Perdó per riure.$"

gTVPokemonTodayFailedText05::
	.string "Germana Gran: Bufufu…\p"
	.string "Germà Gran: Ei!\n"
	.string "Tu també has rigut!\p"
	.string "Germana Gran: Què?!\p"
	.string "No he rigut!\n"
	.string "De veritat, no he rigut!\p"
	.string "Oh, pobre {STR_VAR_1}.\n"
	.string "Quina llàstima!\p"
	.string "Germà Gran: …$"

gTVPokemonTodayFailedText06::
	.string "Germana Gran: Prou ximpleries!\n"
	.string "Vegem el Pokémon d'avui…\p"
	.string "Eh?\n"
	.string "Ja no tenim temps?\p"
	.string "Oh!\n"
	.string "No hem pogut fer el perfil d'avui!\p"
	.string "Germà Gran: Ens veiem la propera!\p"
	.string "Germana Gran: Ei, no acabis el\n"
	.string "programa sense mi!$"

gTVPokemonTodaySuccessfulText00::
	.string "Hola!\p"
	.string "És l'hora de Pokémon Avui!\p"
	.string "Germana Gran: Ei! Tothom content\n"
	.string "i animat avui?\p"
	.string "Avui, veurem el Pokémon {STR_VAR_2}\n"
	.string "de {STR_VAR_1}!\p"
	.string "Germà Gran: Sí! Això és el que\n"
	.string "farem!$"

gTVPokemonTodaySuccessfulText01::
	.string "Germana Gran: {STR_VAR_1} li va posar\n"
	.string "el sobrenom {STR_VAR_3} al {STR_VAR_2}!\p"
	.string "Sembla que {STR_VAR_3} rep unes bones\n"
	.string "cures plenes d'amor!$"

gTVPokemonTodaySuccessfulText02::
	.string "Germà Gran: L'Entrenador va haver\n"
	.string "de llançar tantes Poké Balls\l"
	.string "per atrapar-lo: {STR_VAR_3}!\p"
	.string "Al final va bastar una sola\n"
	.string "{STR_VAR_2} per atrapar-lo!$"

gTVPokemonTodaySuccessfulText03::
	.string "Germana Gran: Si va ser tan fàcil\n"
	.string "d'atrapar, devia ser el destí el\l"
	.string "que va unir {STR_VAR_1} i el {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText04::
	.string "Germana Gran: Uau! Què bé!\p"
	.string "Però ja saps què diuen: un Pokémon\n"
	.string "que costa molt d'atrapar es guanya\l"
	.string "l'amor del seu Entrenador!$"

gTVPokemonTodaySuccessfulText05::
	.string "Germana Gran: El {STR_VAR_2}\n"
	.string "de {STR_VAR_1} és un Pokémon memorable\l"
	.string "perquè va caldre una Master Ball!\p"
	.string "Germà Gran: Uau! Mega-increïble!\p"
	.string "Germana Gran: {STR_VAR_1} devia voler\n"
	.string "molt aquell {STR_VAR_2}, segur!$"

gTVPokemonTodaySuccessfulText06::
	.string "Germà Gran: I llavors posar el\n"
	.string "sobrenom {STR_VAR_3} a aquell {STR_VAR_2}…\p"
	.string "Realment et fas una idea del sentit\n"
	.string "d'Entrenador de {STR_VAR_1}.\p"
	.string "Germana Gran: Hi estic d'acord!$"

gTVPokemonTodaySuccessfulText07::
	.string "Si fos jo, li posaria aquest sobrenom\n"
	.string "a alguna cosa com aquest {STR_VAR_3}!\p"
	.string "Germà Gran: Uau! Això podria ser\n"
	.string "l'inici d'alguna cosa nova!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} el {STR_VAR_1}?\n"
	.string "No sona perfecte?\p"
	.string "Les lletres i tot, sonen just bé\n"
	.string "per al Pokémon {STR_VAR_1}!\p"
	.string "Germà Gran: Sí, cert!$"

gTVPokemonTodaySuccessfulText09::
	.string "Pel que sé, cap Entrenador ha posat\n"
	.string "mai el sobrenom {STR_VAR_2} al seu\l"
	.string "{STR_VAR_1}!\p"
	.string "Germà Gran: Això demostra el bon\n"
	.string "gust de l'Entrenador per escollir\l"
	.string "sobrenoms!$"

gTVPokemonTodaySuccessfulText10::
	.string "La propera vegada que atrapi un\n"
	.string "Pokémon, li posaré el nom {STR_VAR_2}.\p"
	.string "Germà Gran: Eh? Jo també!\n"
	.string "Jo també usaré el sobrenom {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "Germana Gran: Oh, no!\n"
	.string "Mira quina hora és!\p"
	.string "Bé, amics, això és tot per avui.\n"
	.string "Ens veiem la propera vegada!\p"
	.string "Germà Gran: Recorda, el teu Pokémon\n"
	.string "podria ser el protagonista d'avui!$"

SmartShopper_Text_Intro::
	.string "Hola!\p"
	.string "És l'hora del Comprador Llest d'Avui.\p"
	.string "Entrevistador: Com esteu, espectadors?\p"
	.string "Avui visitem una botiga\n"
	.string "a {STR_VAR_2}.\p"
	.string "Vegem què s'ha venut bé\n"
	.string "últimament.$"

SmartShopper_Text_ClerkNormal::
	.string "Entrevistem el dependent per saber\n"
	.string "els detalls.\p"
	.string "Hola, com va el negoci?\p"
	.string "Dependent: Oh, ens va excel·lent.\p"
	.string "Recentment, {STR_VAR_2} s'ha venut\n"
	.string "especialment bé.\p"
	.string "De fet, l'altre dia un Entrenador\n"
	.string "anomenat {STR_VAR_1} en va comprar\l"
	.string "{STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "Entrevistador: L'Entrenador va\n"
	.string "comprar {STR_VAR_3} {STR_VAR_2}? Una bona\l"
	.string "compra!\p"
	.string "Si puc dir-ho, {STR_VAR_1} devia estar\n"
	.string "preparant-se per un llarg viatge\l"
	.string "a llocs llunyans.\p"
	.string "Per viatjar, els {STR_VAR_2} són\n"
	.string "molt importants!$"

SmartShopper_Text_RandomComment2::
	.string "Entrevistador: Parlant de l'objecte\n"
	.string "{STR_VAR_2}, jo acabo de comprar-ne\l"
	.string "{STR_VAR_3} recentment.\p"
	.string "Al cap i a la fi, {STR_VAR_2} és genial!$"

SmartShopper_Text_RandomComment3::
	.string "Entrevistador: {STR_VAR_2}?!\n"
	.string "Però {STR_VAR_3} unitats?!\p"
	.string "No pensava que ningú en compraria\n"
	.string "tants.\p"
	.string "Mare meva, jo només puc permetre'm\n"
	.string "un o dos de cop…$"

SmartShopper_Text_RandomComment4::
	.string "Entrevistador: Una vegada, vaig\n"
	.string "comprar molts {STR_VAR_2}.\p"
	.string "Però van resultar ser massa.\n"
	.string "Vaig acabar penedint-me…\p"
	.string "Des de llavors, només compro el\n"
	.string "que necessito estrictament…\p"
	.string "Ups!\p"
	.string "No té sentit parlar de mi!$"

SmartShopper_Text_SecondItem::
	.string "Dependent: {STR_VAR_1} també va comprar\n"
	.string "{STR_VAR_2} a l'engròs, {STR_VAR_3} unitats.\p"
	.string "Entrevistador: Oh, intel·ligent.\n"
	.string "{STR_VAR_2} és molt bon objecte.$"

SmartShopper_Text_ThirdItem::
	.string "Dependent: I l'Entrenador també\n"
	.string "va comprar {STR_VAR_3} de {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "Dependent: A més, era durant\n"
	.string "unes rebaixes. Compra intel·ligent.$"

SmartShopper_Text_OutroNormal::
	.string "Entrevistador: Hmm… {STR_VAR_1} sembla\n"
	.string "un autèntic caçador d'ofertes!\p"
	.string "En total, les compres de {STR_VAR_1}\n"
	.string "han sumat…\p"
	.string "¥{STR_VAR_2}?!\n"
	.string "Quina quantitat increïble!\p"
	.string "Ups! S'ha acabat el temps!\n"
	.string "Ens veiem a la propera emissió!$"

SmartShopper_Text_IsVIP::
	.string "Dependent: {STR_VAR_1} és un client VIP,\n"
	.string "sens dubte.$"

SmartShopper_Text_ClerkMax::
	.string "Entrevistem el dependent per saber\n"
	.string "els detalls.\p"
	.string "Hola, com va el negoci?\p"
	.string "Dependent: Oh, fem un negoci\n"
	.string "increïble. Gairebé aclaparant.\p"
	.string "Recentment, un Entrenador anomenat\n"
	.string "{STR_VAR_1} va comprar {STR_VAR_2}\l"
	.string "a l'engròs.\p"
	.string "L'Entrenador gairebé ens va buidar\n"
	.string "tot l'estoc de {STR_VAR_2}.\p"
	.string "Mai hauria imaginat que cap client\n"
	.string "necessités tants {STR_VAR_2}.\l"
	.string "No s'havia vist mai!\p"
	.string "Entrevistador: Seria com 100\n"
	.string "o 200 unitats?\p"
	.string "Dependent: Oh, no, molt més!\p"
	.string "Entrevistador: Mare meva!\n"
	.string "{STR_VAR_1} deu ser un comprador\l"
	.string "excepcional!\p"
	.string "Dependent: {STR_VAR_1} és un client VIP,\n"
	.string "sens dubte.$"

SmartShopper_Text_OutroMax::
	.string "Entrevistador: Hmm…\n"
	.string "Això és increïble.\p"
	.string "Però per què l'Entrenador necessita\n"
	.string "comprar-ne tants?\p"
	.string "… …\p"
	.string "El misteri s'aprofundeix, però no\n"
	.string "tenim més temps per avui.\l"
	.string "Ens veiem a la propera emissió!\p"
	.string "Tot i així, {STR_VAR_1} és un enigma…$"

gTVWorldOfMastersText00::
	.string "El Món dels Mestres\p"
	.string "Hola, espectadors.\p"
	.string "Potser coneixeu un Entrenador\n"
	.string "anomenat {STR_VAR_1}.\p"
	.string "{STR_VAR_1} és famós com a mestre\n"
	.string "en la captura de Pokémon.\p"
	.string "La recerca de Pokémon de {STR_VAR_1}\n"
	.string "depèn de cercar a peu acuradament.\p"
	.string "Un dia memorable, l'Entrenador\n"
	.string "va caminar {STR_VAR_2} passos.\p"
	.string "El total de Pokémon atrapats aquell\n"
	.string "dia va arribar a {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Aquella fita remarcable devia ser\n"
	.string "possible gràcies a la confiança\l"
	.string "entre l'Entrenador i {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "El mestre va atrapar l'últim\n"
	.string "{STR_VAR_3} del dia a prop de {STR_VAR_2}.\p"
	.string "Aquell Pokémon gaudeix d'un estatus\n"
	.string "especial com a posseïdor del rècord.\p"
	.string "Animem els Entrenadors hàbils\n"
	.string "a desafiar aquest bon rècord.\p"
	.string "Això és tot per avui.\n"
	.string "Sintonitzeu-nos la propera vegada.$"

gTVTodaysRivalTrainerText00::
	.string "El Rival d'Avui!\p"
	.string "Hola, Entrenadors Pokémon!\n"
	.string "Com anem tots avui?\p"
	.string "Avui, com cada dia,\n"
	.string "examinarem un dels nostres rivals!$"

gTVTodaysRivalTrainerText07::
	.string "El rival d'avui és {STR_VAR_1},\n"
	.string "que ara es troba per {STR_VAR_3}.\p"
	.string "{STR_VAR_1} ha registrat fins ara\n"
	.string "{STR_VAR_2} Pokémon a la Pokédex.$"

gTVTodaysRivalTrainerText08::
	.string "El rival d'avui és {STR_VAR_1},\n"
	.string "que ara és a una Base Secreta.\p"
	.string "{STR_VAR_1} ha registrat fins ara\n"
	.string "{STR_VAR_2} Pokémon a la Pokédex.$"

gTVTodaysRivalTrainerText09::
	.string "El rival d'avui és {STR_VAR_1}.\p"
	.string "Fins ara, {STR_VAR_1} ha registrat\n"
	.string "{STR_VAR_2} Pokémon a la Pokédex.$"

gTVTodaysRivalTrainerText10::
	.string "El rival d'avui és {STR_VAR_1},\n"
	.string "que ara és en un ferri.\p"
	.string "{STR_VAR_1} ha registrat fins ara\n"
	.string "{STR_VAR_2} Pokémon a la Pokédex.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "I quantes Medalles té el nostre\n"
	.string "rival? El nombre és {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Però el nostre rival encara no ha\n"
	.string "obtingut cap Medalla!$"

gTVTodaysRivalTrainerText03::
	.string "El nostre rival encara no ha obtingut\n"
	.string "cap Símbol de la Frontera de Combat.$"

gTVTodaysRivalTrainerText04::
	.string "Vegem quants Símbols de la Frontera\n"
	.string "de Combat té el nostre rival.\p"
	.string "Símbols d'Or: {STR_VAR_1}!\n"
	.string "Símbols de Plata: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "El nostre rival ha acumulat\n"
	.string "{STR_VAR_1} Punt(s) de Combat a la\l"
	.string "Frontera de Combat.$"

gTVTodaysRivalTrainerText06::
	.string "I tu, com et mesures en comparació\n"
	.string "amb {STR_VAR_1}?\p"
	.string "L'aventura continua!\p"
	.string "Entrenadors!\p"
	.string "Continuem avançant\n"
	.string "i superant els nostres rivals!$"

TrendWatcher_Text_Intro::
	.string "Xarxa de Tendències de Dewford!\p"
	.string "Presentador: Què tal?\n"
	.string "Us portem l'últim sobre el que és\l"
	.string "modern i passa a Dewford.\p"
	.string "El nostre convidat d'avui és un\n"
	.string "veterà que presumeix de ser\l"
	.string "l'autoritat en tot a Dewford.\p"
	.string "Vell: Encantat de ser aquí.\p"
	.string "Presentador: Anem al gra.\p"
	.string "Què dius que mou la bona gent\n"
	.string "de Dewford?\p"
	.string "Vell: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "Presentador: {STR_VAR_1} {STR_VAR_2},\n"
	.string "dius?\p"
	.string "Vell: No.\p"
	.string "{STR_VAR_1} {STR_VAR_2} mai\n"
	.string "es va fer popular.\p"
	.string "Vols que te'n parli?\p"
	.string "Presentador: Eh, no. El que volem\n"
	.string "saber és la moda del moment…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Vell: {STR_VAR_1} {STR_VAR_2}\n"
	.string "és el que {STR_VAR_3} de Litleroot\l"
	.string "em va ensenyar com a tendència…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Vell: {STR_VAR_1} {STR_VAR_2}\n"
	.string "és el que {STR_VAR_3} de Litleroot\l"
	.string "em va ensenyar com a tendència…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Però va ser un fracàs total.\p"
	.string "Festival {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Concurs {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Vaig intentar ensenyar-ho a tothom\n"
	.string "el millor que vaig poder, però…\p"
	.string "Potser la part de {STR_VAR_1}\n"
	.string "no era l'adequada…\p"
	.string "Presentador: Eh, perdona, amic,\n"
	.string "he de saber què és popular ara…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Vell: {STR_VAR_3}!\n"
	.string "Si us plau, explica'm alguna cosa\l"
	.string "més gran que {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Vell: {STR_VAR_3}!\n"
	.string "Si us plau, explica'm alguna cosa\l"
	.string "més gran que {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "Presentador: …Eh… Doncs, aquí\n"
	.string "ho teniu, fans de les tendències!\p"
	.string "{STR_VAR_1} {STR_VAR_2}…eh…\n"
	.string "No es va posar de moda a Dewford!\p"
	.string "Se m'ha acabat el temps. Adéu!\p"
	.string "Vell: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "Investigadors de Tresors de Hoenn!\p"
	.string "Hola a tothom!\n"
	.string "Heu trobat objectes secrets?\p"
	.string "Com sempre, examinarem informes\n"
	.string "de secrets d'arreu!\p"
	.string "Comencem amb una carta.\n"
	.string "Diu: "{STR_VAR_1} descobert!"$"

gTVHoennTreasureInvestigatorsText01::
	.string "Uau, millor que mirem aquesta carta!\n"
	.string "Deixeu que us la llegeixi.\p"
	.string "…Benvolguts Investigadors,\n"
	.string "espero que estigueu bé.\p"
	.string "Recentment vaig veure {STR_VAR_2}\n"
	.string "per les rodalies de {STR_VAR_3}.\p"
	.string "L'Entrenador va trobar l'objecte\n"
	.string "{STR_VAR_1}. Em va fer enveja.\p"
	.string "…Bé, ben fet, {STR_VAR_2}!\p"
	.string "Espectadors, que això us motivi a\n"
	.string "activar els Cercaobjectes i cercar!\p"
	.string "Estaré esperant notícies\n"
	.string "emocionants de tots vosaltres!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Uau, millor que mirem aquesta carta!\n"
	.string "Deixeu que us la llegeixi.\p"
	.string "…Benvolguts Investigadors,\n"
	.string "espero que estigueu bé.\p"
	.string "Recentment vaig veure {STR_VAR_2}\n"
	.string "en un ferri.\p"
	.string "L'Entrenador va trobar l'objecte\n"
	.string "{STR_VAR_1}. Em va fer enveja.\p"
	.string "…Bé, ben fet, {STR_VAR_2}!\p"
	.string "Espectadors, que això us motivi a\n"
	.string "activar els Cercaobjectes i cercar!\p"
	.string "Estaré esperant notícies\n"
	.string "emocionants de tots vosaltres!$"

gTVFindThatGamerText00::
	.string "Trobeu Aquell Jugador!\p"
	.string "Ei, jugadors!\n"
	.string "Com gira la vostra {STR_VAR_2}?\p"
	.string "Com sempre, posarem el focus en un\n"
	.string "Entrenador especial que ha visitat\l"
	.string "el Saló Recreatiu!\p"
	.string "Avui, el jugador número 1 és…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} va jugar a {STR_VAR_2}\n"
	.string "i va guanyar {STR_VAR_3} Monedes.\p"
	.string ""Quan {STR_VAR_1} ve, hem d'assegurar\n"
	.string "que tinguem prou Monedes."\p"
	.string "Això és el que diuen els dependents\n"
	.string "del Saló quan el jugador juga!\p"
	.string "Espectadors, vigileu les Monedes\n"
	.string "com {STR_VAR_1} si visiteu el Saló\l"
	.string "i jugueu a {STR_VAR_2}.\p"
	.string "Som en directe des del Saló\n"
	.string "Recreatiu, on es viu l'emoció!\p"
	.string "Això és tot per avui!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} va jugar a {STR_VAR_2}\n"
	.string "i va perdre {STR_VAR_3} Monedes.\p"
	.string ""Quan {STR_VAR_1} ve, les nostres\n"
	.string "vendes de Monedes augmenten."\p"
	.string "Això és el que diuen els dependents\n"
	.string "del Saló quan el jugador juga!$"

gTVFindThatGamerText03::
	.string "Espectadors, vigileu les Monedes\n"
	.string "com {STR_VAR_1} si visiteu el Saló\l"
	.string "i jugueu a {STR_VAR_2}.\p"
	.string "Som en directe des del Saló\n"
	.string "Recreatiu, on es viu l'emoció!\p"
	.string "Això és tot per avui!$"

gTVBreakingNewsText00::
	.string "Últimes Notícies!$"

gTVBreakingNewsText01::
	.string "{STR_VAR_2} rar atrapat per\n"
	.string "{STR_VAR_1}!\p"
	.string "Som en directe des de les rodalies\n"
	.string "de {STR_VAR_3}!\p"
	.string "{STR_VAR_1} ha capturat amb èxit\n"
	.string "un rar {STR_VAR_2} aquí!$"

gTVBreakingNewsText02::
	.string "Quan {STR_VAR_1} va trobar el rar\n"
	.string "{STR_VAR_2}, l'Entrenador va enviar\l"
	.string "el Pokémon {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "Al combat, el nombre de Poké Balls\n"
	.string "llançades per l'Entrenador va ser\l"
	.string "{STR_VAR_1}.\p"
	.string "Finalment, el Pokémon rar va ser\n"
	.string "atrapat amb la {STR_VAR_2} usada\l"
	.string "al final.$"

gTVBreakingNewsText04::
	.string "En aquell instant, {STR_VAR_2}\n"
	.string "va ressonar amb els crits de\l"
	.string "triomf de {STR_VAR_1}.\p"
	.string "He de dir que tinc una mica\n"
	.string "d'enveja de {STR_VAR_1}.\p"
	.string "…Aquí acaba la connexió en directe\n"
	.string "des del lloc de l'alegria!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} no aconsegueix capturar\n"
	.string "un rar {STR_VAR_2}!\p"
	.string "Som en directe des de les rodalies\n"
	.string "de {STR_VAR_3}!\p"
	.string "Aquí és on {STR_VAR_1} no va poder\n"
	.string "capturar un rar {STR_VAR_2}!$"

gTVBreakingNewsText06::
	.string "Quan {STR_VAR_1} va trobar el rar\n"
	.string "{STR_VAR_2}, l'Entrenador va enviar\l"
	.string "el Pokémon {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "L'Entrenador va fer que {STR_VAR_2}\n"
	.string "usés el moviment {STR_VAR_1}.\p"
	.string "Sense voler, l'Entrenador va fer\n"
	.string "que el Pokémon rar es desmaiés…$"

gTVBreakingNewsText12::
	.string "No obstant, {STR_VAR_1} va entrar\n"
	.string "en pànic en veure el rar {STR_VAR_2}.\p"
	.string "Confós, l'Entrenador va ordenar\n"
	.string "a {STR_VAR_3} que ataqués.\p"
	.string "Sense voler, l'Entrenador va fer\n"
	.string "que el Pokémon rar es desmaiés.$"

gTVBreakingNewsText08::
	.string "En aquell instant, {STR_VAR_2}\n"
	.string "va ressonar amb els crits de\l"
	.string "frustració de {STR_VAR_1}…$"

gTVBreakingNewsText09::
	.string "No obstant, {STR_VAR_1} sembla que\n"
	.string "es va quedar sense Poké Balls.\p"
	.string "L'Entrenador va haver d'abandonar\n"
	.string "el combat amb el rar {STR_VAR_2}.\p"
	.string "En aquell instant, {STR_VAR_3}\n"
	.string "va ressonar amb els crits de\l"
	.string "frustració de {STR_VAR_1}…$"

gTVBreakingNewsText10::
	.string "No obstant, el {STR_VAR_2} va fugir\n"
	.string "sense previ avís.\p"
	.string "En aquell instant, {STR_VAR_3}\n"
	.string "va ressonar amb els crits de\l"
	.string "frustració de {STR_VAR_1}…$"

gTVBreakingNewsText11::
	.string "He de dir que compadeixo {STR_VAR_1}.\n"
	.string "A mi també em fan ganes de cridar.\p"
	.string "…Aquí acaba la connexió en directe\n"
	.string "des del lloc de la tristesa!$"

gTVSecretBaseVisitText00::
	.string "Hola a tothom!\n"
	.string "És l'hora d'una altra\l"
	.string "Visita a la Base Secreta.\p"
	.string "Avui, visitem la Base Secreta\n"
	.string "de {STR_VAR_1}.\p"
	.string "Com ha personalitzat {STR_VAR_1}\n"
	.string "la Base Secreta?\p"
	.string "Descobrim-ho!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Oh!\n"
	.string "Que meravellós!\p"
	.string "Aquest {STR_VAR_2}…\n"
	.string "No és el que un esperaria trobar\l"
	.string "aquí!$"

gTVSecretBaseVisitText02::
	.string "Oh!\n"
	.string "Que remarcable!\p"
	.string "No hi ha ni un sol moble\n"
	.string "ni objecte d'interior!\p"
	.string "Simples mortals no podrien\n"
	.string "imitar aquesta declaració audaç!\p"
	.string "És simple, però rebenta, sí,\n"
	.string "rebenta de naturalitat!\p"
	.string "El meu barret fora, {STR_VAR_1}.\n"
	.string "Havies de ser tu!$"

gTVSecretBaseVisitText03::
	.string "Oh! Ja ho veig!\n"
	.string "Amb perfecta claredat!\p"
	.string "Que aquest {STR_VAR_2} sigui aquí…\n"
	.string "Envia un missatge efectiu!$"

gTVSecretBaseVisitText04::
	.string "Oh! Ja ho veig!\n"
	.string "Amb perfecta claredat!\p"
	.string "Aquest espai es manté deliberadament\n"
	.string "lliure d'objectes d'interior!\p"
	.string "Envia un missatge efectiu!$"

gTVSecretBaseVisitText05::
	.string "Uuuf!\p"
	.string "La combinació del {STR_VAR_2}\n"
	.string "amb el {STR_VAR_3}!\p"
	.string "És una combinació de somni\n"
	.string "de les que mai s'han vist!$"

gTVSecretBaseVisitText06::
	.string "Uuuf!\p"
	.string "La col·locació d'aquest {STR_VAR_2}\n"
	.string "just aquí…\p"
	.string "Té una presència que omple tota\n"
	.string "la Base Secreta!$"

gTVSecretBaseVisitText07::
	.string "Uuuf!\p"
	.string "No hi ha res col·locat aquí.\p"
	.string "Aquest espai buit té un efecte\n"
	.string "sobre tota la Base Secreta.$"

gTVSecretBaseVisitText08::
	.string "Oh!\n"
	.string "Aquí ve {STR_VAR_1}!\l"
	.string "Desafiem l'Entrenador!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Sospir…\n"
	.string "He de reconèixer-ho a {STR_VAR_1}.\p"
	.string "Els Pokémon de l'Entrenador eren\n"
	.string "dignes del títol de Campió.\p"
	.string "Van demostrar àmpliament la\n"
	.string "duresa de {STR_VAR_1} com a Entrenador.\p"
	.string "Que el {STR_VAR_2} sabés el moviment\n"
	.string "{STR_VAR_3}…\p"
	.string "Mostra quin tipus d'Entrenador\n"
	.string "és {STR_VAR_1}.\p"
	.string "Certament, ha estat tota una lliçó!$"

gTVSecretBaseVisitText10::
	.string "Ai!\n"
	.string "He de reconèixer-ho a {STR_VAR_1}.\p"
	.string "Els Pokémon de l'Entrenador eren\n"
	.string "monstruosament durs!\p"
	.string "Van demostrar àmpliament la\n"
	.string "tenacitat de {STR_VAR_1}.\p"
	.string "Que el {STR_VAR_2} sabés el moviment\n"
	.string "{STR_VAR_3}…\p"
	.string "Mostra quin tipus d'Entrenador\n"
	.string "és {STR_VAR_1}.\p"
	.string "Certament, ha estat tota una lliçó!$"

gTVSecretBaseVisitText11::
	.string "Uuuf!\n"
	.string "He de reconèixer-ho a {STR_VAR_1}.\p"
	.string "Els Pokémon de l'Entrenador estaven\n"
	.string "clarament criats de forma equilibrada.\p"
	.string "Van demostrar àmpliament la\n"
	.string "reflexió de {STR_VAR_1} com a\l"
	.string "Entrenador.\p"
	.string "Que el {STR_VAR_2} sabés el moviment\n"
	.string "{STR_VAR_3}…\p"
	.string "Mostra quin tipus d'Entrenador\n"
	.string "és {STR_VAR_1}.\p"
	.string "Certament, ha estat tota una lliçó!$"

gTVSecretBaseVisitText12::
	.string "Bé, bé!\n"
	.string "He de reconèixer-ho a {STR_VAR_1}.\p"
	.string "Els Pokémon de l'Entrenador\n"
	.string "mostraven gran promesa de futur.\p"
	.string "Representaven les esperances\n"
	.string "i somnis de {STR_VAR_1}.\p"
	.string "Que el {STR_VAR_2} sabés el moviment\n"
	.string "{STR_VAR_3}…\p"
	.string "Mostra quin tipus d'Entrenador\n"
	.string "és {STR_VAR_1}.\p"
	.string "Certament, ha estat tota una lliçó!$"

gTVSecretBaseVisitText13::
	.string "He de dir, quina Base Secreta\n"
	.string "tan superba!\p"
	.string "Espectadors, si teniu l'oportunitat,\n"
	.string "visiteu la Base de {STR_VAR_1}.\p"
	.string "Fins la propera, adéu!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Emocionant!\n"
	.string "Dramàtic!\p"
	.string "El Flash Informatiu del Guanyador\n"
	.string "de la Loteria Pokémon!\p"
	.string "Hola! Som en directe des del Racó\n"
	.string "de la Loteria Pokémon a la planta\l"
	.string "baixa dels Grans Magatzems\l"
	.string "de Lilycove!\p"
	.string "Com sempre, un altre Entrenador\n"
	.string "afortunat ha aparegut avui!\p"
	.string "El nom d'aquest Entrenador…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} ha guanyat el premi\n"
	.string "{STR_VAR_2} i s'emporta el {STR_VAR_3}!\p"
	.string "{STR_VAR_1}!\n"
	.string "Felicitats!\p"
	.string "Espectadors, no us quedeu mirant,\n"
	.string "participeu-hi!\p"
	.string "Tot l'equip dels Grans Magatzems\n"
	.string "de Lilycove espera la vostra visita!\p"
	.string "Aquesta ha estat una emissió en\n"
	.string "directe des dels Grans Magatzems\l"
	.string "de Lilycove, que us ofereixen la\l"
	.string "millor selecció de Hoenn!$"

gTVThePokemonBattleSeminarText00::
	.string "El Seminari de Combat Pokémon!\p"
	.string "Examinem combats per veure quines\n"
	.string "lliçons podem aprendre dels altres.\p"
	.string "L'estudi d'avui és sobre el combat\n"
	.string "de {STR_VAR_1}.\p"
	.string "El {STR_VAR_2} de {STR_VAR_1}\n"
	.string "combatia contra un {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "I va usar el moviment {STR_VAR_3}\n"
	.string "contra el {STR_VAR_2}…\p"
	.string "Hmm… {STR_VAR_1}!\n"
	.string "No s'havia de fer això!$"

gTVThePokemonBattleSeminarText02::
	.string "A més del moviment desastrós,\n"
	.string "el {STR_VAR_1} de l'Entrenador\l"
	.string "també coneixia$"

gTVThePokemonBattleSeminarText03::
	.string "els moviments {STR_VAR_1}, {STR_VAR_2}\n"
	.string "i {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "els moviments {STR_VAR_1} i\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "el moviment {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Doncs, en aquesta situació, què\n"
	.string "hauria d'haver usat l'Entrenador?\p"
	.string "… … … … … …\n"
	.string "El moviment {STR_VAR_1}!\p"
	.string "El moviment {STR_VAR_1} hauria estat\n"
	.string "absolutament millor que {STR_VAR_2}.\p"
	.string "Espectadors, us animo a aprendre\n"
	.string "d'aquest cas i combatre amb\l"
	.string "intel·ligència!\p"
	.string "Fins la propera, adéu!$"

gTVTrainerFanClubText00::
	.string "Tots plegats!\n"
	.string "Club de Fans d'Entrenadors!\p"
	.string "Presentador: Com va tot?\n"
	.string "Avui, hem reunit els fans de\l"
	.string "l'Entrenador superpopular\l"
	.string "{STR_VAR_1}!\p"
	.string "Fans: Wrooooooaaaaah!\p"
	.string "Fans: {STR_VAR_1}!\p"
	.string "Presentador: A tothom!\n"
	.string "Què us sembla {STR_VAR_1}?!\p"
	.string "Fans: Estimem {STR_VAR_1}!\p"
	.string "Presentador: Què us agrada de\n"
	.string "{STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "Fans: La seva forma genial de\n"
	.string "llançar Poké Balls!$"

gTVTrainerFanClubText02::
	.string "Fans: La seva forma adorable\n"
	.string "de córrer!$"

gTVTrainerFanClubText03::
	.string "Fans: Com l'Entrenador es fa fort\n"
	.string "quan les coses es posen difícils!$"

gTVTrainerFanClubText04::
	.string "Fans: El coneixement de Pokémon\n"
	.string "de l'Entrenador!$"

gTVTrainerFanClubText05::
	.string "Fans: L'amabilitat de l'Entrenador\n"
	.string "amb tots els Pokémon!$"

gTVTrainerFanClubText06::
	.string "Fans: Les increïbles tècniques\n"
	.string "de ciclisme de l'Entrenador!$"

gTVTrainerFanClubText07::
	.string "Fans: L'impressionant estil de\n"
	.string "comprar objectes de l'Entrenador!$"

gTVTrainerFanClubText08::
	.string "Fans: La manera encantadora de\n"
	.string "l'Entrenador de posar sobrenoms!$"

gTVTrainerFanClubText09::
	.string "Fans: L'estil elegant de decorar\n"
	.string "una Base Secreta de l'Entrenador!$"

gTVTrainerFanClubText10::
	.string "Fans: La forma audaç de\n"
	.string "l'Entrenador d'usar MTs!$"

gTVTrainerFanClubText11::
	.string "Presentador: Com acabeu de veure,\n"
	.string "{STR_VAR_1} és popular a morir!\p"
	.string "Entre els fans de {STR_VAR_1}\n"
	.string "hi ha un eslògan especial!\p"
	.string "Presentador: Quan dic {STR_VAR_1},\n"
	.string "vosaltres dieu…\p"
	.string "Fans: {STR_VAR_2}!\p"
	.string "Fans: {STR_VAR_3}!\p"
	.string "Fans: {STR_VAR_2}!\p"
	.string "Fans: {STR_VAR_3}!\p"
	.string "Presentador: Així és, quan algú\n"
	.string "diu "{STR_VAR_1}"…\p"
	.string "Responeu amb "{STR_VAR_2}\n"
	.string "{STR_VAR_3}!"\p"
	.string "Sona tan únic!\n"
	.string "Entenc per què la gent es fa fan\l"
	.string "de {STR_VAR_1}!\p"
	.string "Tu, davant la TV, uneix-t'hi!\n"
	.string "Tots plegats!\p"
	.string "Presentador: Quan dic {STR_VAR_1},\n"
	.string "vosaltres dieu…\p"
	.string "Fans: {STR_VAR_2}!\p"
	.string "Fans: {STR_VAR_3}!\p"
	.string "Fans: {STR_VAR_2}!\p"
	.string "Fans: {STR_VAR_3}!\p"
	.string "Presentador: Gràcies per ser-hi,\n"
	.string "fans salvatges de {STR_VAR_1}!\l"
	.string "Això és tot! Ens veiem!\p"
	.string "Presentador: Quan dic {STR_VAR_1},\n"
	.string "vosaltres dieu…\p"
	.string "Fans: {STR_VAR_2}!\p"
	.string "Fans: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "Trobeu els Bonics!\n"
	.string "Pokémon amb Cintes!\p"
	.string "Hola, estimats espectadors!\p"
	.string "Estic segur que hi estareu d'acord:\n"
	.string "un Pokémon amb Cintes és diví!\p"
	.string "Avui, vull compartir amb vosaltres\n"
	.string "un preciós Pokémon que vaig veure\l"
	.string "passejant per la ciutat.\p"
	.string "El Pokémon destacat d'avui\n"
	.string "és el {STR_VAR_2} de {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "El nombre de Cintes que porta\n"
	.string "{STR_VAR_2} és {STR_VAR_3}.\p"
	.string "Diu molt sobre com {STR_VAR_1}\n"
	.string "adora el Pokémon.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} porta unes increïbles\n"
	.string "{STR_VAR_3} Cintes!\p"
	.string "Parla a favor del compromís de\n"
	.string "{STR_VAR_1} amb el Pokémon!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} porta unes increïbles\n"
	.string "{STR_VAR_3} Cintes!\p"
	.string "Mostra la dedicació total de\n"
	.string "{STR_VAR_1} com a col·leccionista!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Mirem de prop les moltes Cintes\n"
	.string "que porta {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "La Cinta de Campió és especialment\n"
	.string "encantadora.\p"
	.string "{STR_VAR_2} la va rebre en entrar\n"
	.string "al Saló de la Fama.\p"
	.string "Realment destaca la valentia\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i la Cinta de Campió!\n"
	.string "La combinació és superefectiva!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "La Cinta Cool és especialment\n"
	.string "encantadora.\p"
	.string "{STR_VAR_2} la va rebre per guanyar\n"
	.string "un Concurs Cool.\p"
	.string "Realment destaca el factor cool\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i la Cinta Cool!\n"
	.string "La combinació és superefectiva!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "La Cinta de Bellesa és especialment\n"
	.string "encantadora.\p"
	.string "{STR_VAR_2} la va rebre per guanyar\n"
	.string "un Concurs de Bellesa.\p"
	.string "Realment destaca la bellesa\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i la Cinta de Bellesa!\n"
	.string "La combinació és superefectiva!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "La Cinta Cute és especialment\n"
	.string "encantadora.\p"
	.string "{STR_VAR_2} la va rebre per guanyar\n"
	.string "un Concurs Cute.\p"
	.string "Realment destaca la tendresa\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i la Cinta Cute!\n"
	.string "La combinació és superefectiva!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "La Cinta Smart és especialment\n"
	.string "encantadora.\p"
	.string "{STR_VAR_2} la va rebre per guanyar\n"
	.string "un Concurs Smart.\p"
	.string "Realment destaca la intel·ligència\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i la Cinta Smart!\n"
	.string "La combinació és superefectiva!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "La Cinta Tough és especialment\n"
	.string "encantadora.\p"
	.string "{STR_VAR_2} la va rebre per guanyar\n"
	.string "un Concurs Tough.\p"
	.string "Realment destaca la duresa\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i la Cinta Tough!\n"
	.string "La combinació és superefectiva!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "La Cinta Victoriosa és especialment\n"
	.string "encantadora.\p"
	.string "{STR_VAR_2} la va rebre per les seves\n"
	.string "gestes a la Torre de Combat.\p"
	.string "Realment destaca el poder\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i la Cinta Victoriosa!\n"
	.string "La combinació és superefectiva!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "La Cinta de Victòria és especialment\n"
	.string "encantadora.\p"
	.string "{STR_VAR_2} la va rebre per les seves\n"
	.string "gestes a la Torre de Combat.\p"
	.string "Realment destaca el poder\n"
	.string "increïble de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i la Cinta de Victòria!\n"
	.string "La combinació és superefectiva!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "La Cinta d'Artista és especialment\n"
	.string "encantadora.\p"
	.string "{STR_VAR_2} la va rebre per ser\n"
	.string "el model d'un artista.\p"
	.string "Realment destaca l'encant d'estrella\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i la Cinta d'Artista!\n"
	.string "La combinació és superefectiva!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "La Cinta de Treballador és\n"
	.string "especialment encantadora.\p"
	.string "{STR_VAR_2} la va rebre per ser\n"
	.string "un treballador especialment dedicat.\p"
	.string "Realment destaca la determinació\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} i la Cinta de Treballador!\n"
	.string "La combinació és superefectiva!$"

TVSpotTheCuties_Text_Outro::
	.string "…Sospir…\p"
	.string "Cintes i Pokémon…\n"
	.string "Fan tan bona parella!\p"
	.string "Abans que em desmai,\n"
	.string "adéu a tothom!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Salutacions!\n"
	.string "És l'hora de Notícies Pokémon.\p"
	.string "Tenim bones notícies de la\n"
	.string "Frontera de Combat.$"

gTVPokemonNewsBattleFrontierText01::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} victòries\l"
	.string "seguides al repte de Combat\l"
	.string "Individual de la Torre de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} victòries\l"
	.string "seguides al repte de Combat\l"
	.string "Doble de la Torre de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} victòries\l"
	.string "seguides al repte de Multi Combat\l"
	.string "de la Torre de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} victòries\l"
	.string "seguides al repte de Multi Combat\l"
	.string "per Enllaç de la Torre de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} campionats\l"
	.string "seguits als Tornejos de Combat\l"
	.string "Individual del Domo de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} campionats\l"
	.string "seguits als Tornejos de Combat\l"
	.string "Doble del Domo de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} victòries\l"
	.string "seguides al repte d'Intercanvi\l"
	.string "Individual de la Fàbrica de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} victòries\l"
	.string "seguides al repte d'Intercanvi\l"
	.string "Doble de la Fàbrica de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} sales\l"
	.string "superades al repte d'Elecció\l"
	.string "de Combat de la Pica de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} victòries\l"
	.string "seguides als Tornejos KO de\l"
	.string "l'Arena de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} victòries\l"
	.string "seguides al repte del Saló de\l"
	.string "Combat Individual del Palau de\l"
	.string "Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} victòries\l"
	.string "seguides al repte del Saló de\l"
	.string "Combat Doble del Palau de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "L'Entrenador {STR_VAR_1} ha establert\n"
	.string "un nou rècord de {STR_VAR_2} pisos\l"
	.string "superats al repte de la Missió de\l"
	.string "la Piràmide de Combat.\p"
	.string "Per {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "I als tres Pokémon, {STR_VAR_1},\n"
	.string "{STR_VAR_2} i {STR_VAR_3}!\p"
	.string "Felicitats per la vostra actuació\n"
	.string "que ha batut el rècord!$"

gTVPokemonNewsBattleFrontierText15::
	.string "I als dos Pokémon, {STR_VAR_1}\n"
	.string "i {STR_VAR_2}!\p"
	.string "Felicitats per la vostra actuació\n"
	.string "que ha batut el rècord!$"

gTVPokemonNewsBattleFrontierText16::
	.string "I als quatre Pokémon: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "I {STR_VAR_1}!\p"
	.string "Felicitats per la vostra actuació\n"
	.string "que ha batut el rècord!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Esperem més gestes que batin\n"
	.string "rècords de {STR_VAR_1} i els seus\l"
	.string "Pokémon fidels!\p"
	.string "Això és tot a Notícies Pokémon!$"

gTVWhatsNo1InHoennTodayText00::
	.string "Què és el Número 1 a Hoenn Avui?\n"
	.string "Sí, torna a ser l'hora!\p"
	.string "Hola, espectadors! Doneu el millor\n"
	.string "de vosaltres en tot?\p"
	.string "Vegem l'Entrenador que avui\n"
	.string "ha estat el millor!\p"
	.string "L'Entrenador número 1 d'avui és\n"
	.string "{STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "En un sol dia, {STR_VAR_1} va fer girar\n"
	.string "les Slots al Saló Recreatiu\l"
	.string "{STR_VAR_2} vegades.\p"
	.string "Mentre jugava, {STR_VAR_1} murmurava:\n"
	.string ""Per mi, els rodets ni es mouen…"\l"
	.string "No és interessant?$"

gTVWhatsNo1InHoennTodayText02::
	.string "En un sol dia, {STR_VAR_1} va jugar\n"
	.string "a la Ruleta del Saló Recreatiu\l"
	.string "{STR_VAR_2} vegades.\p"
	.string "Mentre jugava, {STR_VAR_1} cridava:\n"
	.string ""Que les boles decideixin!"\p"
	.string "Els ulls de l'Entrenador estaven\n"
	.string "fixos i la cara concentrada.$"

gTVWhatsNo1InHoennTodayText03::
	.string "En un sol dia, {STR_VAR_1} va combatre\n"
	.string "Pokémon salvatges {STR_VAR_2} vegades!\p"
	.string "Pel que sembla, els Pokémon de\n"
	.string "{STR_VAR_1} s'han fet molt més forts.\p"
	.string "Semblen ansiosos de combatre\n"
	.string "en qualsevol lloc i moment!$"

gTVWhatsNo1InHoennTodayText04::
	.string "En un sol dia, {STR_VAR_1} va fer girar\n"
	.string "la Barrejadora {STR_VAR_2} vegades!\p"
	.string "Cap al final, fins i tot {STR_VAR_1}\n"
	.string "semblava marejat.\p"
	.string "L'Entrenador es balancejava\n"
	.string "com un Spinda!$"

gTVWhatsNo1InHoennTodayText05::
	.string "En un sol dia, {STR_VAR_1} va plantar\n"
	.string "{STR_VAR_2} Baies!\p"
	.string "Com a resultat, la roba de {STR_VAR_1}\n"
	.string "va quedar bruta de terra.\p"
	.string "On va plantar, innombrables flors\n"
	.string "han florit.\p"
	.string "Es diu que les flors calmen\n"
	.string "les emocions de la gent.$"

gTVWhatsNo1InHoennTodayText06::
	.string "En un sol dia, {STR_VAR_1} va collir\n"
	.string "{STR_VAR_2} Baies!\p"
	.string "La Motxilla de {STR_VAR_1} va quedar\n"
	.string "tan plena de Baies que l'Entrenador\l"
	.string "tenia problemes per caminar!$"

gTVWhatsNo1InHoennTodayText07::
	.string "En un sol dia, {STR_VAR_1} va obtenir\n"
	.string "{STR_VAR_2} Punts de Combat!\p"
	.string "Després es va veure {STR_VAR_1}\n"
	.string "dubtant entre canviar els Punts\l"
	.string "per un objecte o per una\l"
	.string "decoració d'interior.\p"
	.string "L'Entrenador somreia mentre\n"
	.string "considerava les opcions.$"

gTVWhatsNo1InHoennTodayText08::
	.string "No és impressionant?\p"
	.string "{STR_VAR_1}!\n"
	.string "Ets l'Entrenador número 1 d'avui!\p"
	.string "Espectadors, inspireu-vos en\n"
	.string "{STR_VAR_1}! Tu també pots ser\l"
	.string "el número 1 cada dia!$"

TVSecretBaseSecrets_Text_Intro::
	.string "Secrets de la Base Secreta!\p"
	.string "Què fan els Entrenadors en la\n"
	.string "intimitat de les Bases Secretes?\p"
	.string "Avui, investiguem la Base Secreta\n"
	.string "de {STR_VAR_1}.\p"
	.string "Oh? Sembla que {STR_VAR_2} ha vingut\n"
	.string "de visita.\p"
	.string "Vegem què passa!\p"
	.string "Què farà {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Què farà {STR_VAR_2} ara?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "I ara, què farà {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Al final, {STR_VAR_2} va fer {STR_VAR_3}\n"
	.string "passos a la Base Secreta de\l"
	.string "{STR_VAR_1} abans de marxar.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm…\p"
	.string "Sembla que la Base Secreta\n"
	.string "de {STR_VAR_1} no ha interessat\l"
	.string "{STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} sembla haver gaudit\n"
	.string "a fons de la Base de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} sembla haver-se convertit\n"
	.string "en un gran fan de la Base Secreta\l"
	.string "de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Espectadors, potser voldreu visitar\n"
	.string "la Base Secreta de {STR_VAR_1}.\p"
	.string "Sintonitzeu la propera vegada per\n"
	.string "visitar una altra Base! Gràcies!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "El visitant s'ha aturat!\p"
	.string "El visitant no es mou gens!\p"
	.string "La Base Secreta de {STR_VAR_1} era\n"
	.string "tan poc impressionant?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "El visitant s'ha aturat!\p"
	.string "El visitant no es mou gens!\p"
	.string "És fatiga?\n"
	.string "S'ha cansat el visitant?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "El visitant s'ha assegut\n"
	.string "en una cadira!\p"
	.string "Mireu aquella cara de satisfacció!\p"
	.string "Aquella cadira deu ser molt còmoda\n"
	.string "per provocar aquesta reacció!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "El visitant s'ha llançat contra\n"
	.string "un globus!\p"
	.string "Ha petat!\n"
	.string "Mare meva, ha explotat!\p"
	.string "El visitant sembla sobresaltat\n"
	.string "pel soroll sobtat!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "El visitant ha entrat a una Tenda!\p"
	.string "El visitant corre d'un lloc a l'altre!\p"
	.string "Oh, el visitant s'ho passa d'allò més\n"
	.string "bé!\p"
	.string "El visitant sembla sorprès per\n"
	.string "la mida de la Tenda!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "El visitant està examinant\n"
	.string "una planta de test!\p"
	.string "El visitant té un gust\n"
	.string "sorprenentment madur!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "El visitant està examinant\n"
	.string "un Escut d'Or!\p"
	.string "Els ulls del visitant semblen\n"
	.string "brillar de meravella!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "El visitant està examinant\n"
	.string "un Escut de Plata!\p"
	.string "El visitant sembla tenir els ulls\n"
	.string "com taronges!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "El visitant està examinant\n"
	.string "un Ornament de Vidre!\p"
	.string "Oh, no!\p"
	.string "El visitant el toca!\p"
	.string "S'està omplint d'empremtes\n"
	.string "dactilars…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "El visitant mira la televisió!\p"
	.string "Sembla que tenim un gran fan de TV!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "El visitant ha trepitjat una Bola\n"
	.string "de Fang!\p"
	.string "El visitant sembla content!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…Oh?\p"
	.string "El visitant busca dins la seva\n"
	.string "Motxilla!\p"
	.string "El visitant n'ha tret\n"
	.string "un {STR_VAR_2}!\p"
	.string "Mireu com somriu el visitant\n"
	.string "amb el {STR_VAR_2} a la mà!\p"
	.string "Sembla un anunci de TV!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "El visitant agafa un coixí i…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…comença a colpejar-lo!\p"
	.string "El visitant està molt estressat?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…l'abraça fort!\p"
	.string "Podria ser que el visitant estigui\n"
	.string "content per alguna cosa?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "El visitant xerrà amb\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembla que tindran\n"
	.string "un combat!\p"
	.string "I…\p"
	.string "És el visitant!\n"
	.string "El visitant ha guanyat a fora!\p"
	.string "El visitant fa\n"
	.string "un ball de victòria!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "El visitant xerrà amb\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembla que tindran\n"
	.string "un combat!\p"
	.string "I…\p"
	.string "Ha guanyat {STR_VAR_1}!\n"
	.string "El visitant ha perdut!\p"
	.string "El visitant sembla abatut!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "El visitant xerrà amb\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembla que tindran\n"
	.string "un combat!\p"
	.string "I…\p"
	.string "No, el visitant ha rebutjat!\p"
	.string "No hi haurà combat!\p"
	.string "Ha trobat el visitant {STR_VAR_1}\n"
	.string "poc atractiu?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "El visitant mira fixament\n"
	.string "un pòster!\p"
	.string "Li agrada el pòster al visitant?\p"
	.string "…Però… Hi ha alguna cosa\n"
	.string "inquietant en les mirades.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "El visitant ha trepitjat una\n"
	.string "Estora Musical!\p"
	.string "…Hmm…\n"
	.string "El visitant ha compost una tonada!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "El visitant xerrà amb\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembla que tindran\n"
	.string "un combat!\p"
	.string "I…\p"
	.string "Empat!\n"
	.string "No s'ha resolt res!\p"
	.string "Ambdós Entrenadors semblen molt\n"
	.string "decebuts!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "El visitant ha trepitjat\n"
	.string "una Estora Giratòria!\p"
	.string "Sembla que el visitant està marejat!\p"
	.string "El visitant es tambaleja!\n"
	.string "Compte!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "El visitant toca un Ornament\n"
	.string "de Sorra!\p"
	.string "Oh!\p"
	.string "S'ha esbocinat!\n"
	.string "S'ha desfet!\p"
	.string "El visitant sembla avergonyit\n"
	.string "i culpable!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "El visitant frega l'escriptori\n"
	.string "amb el dit!\p"
	.string "Pel que sembla, el visitant no\n"
	.string "aprova la pols!\p"
	.string "El visitant és sorprenentment\n"
	.string "preocupat per la netedat!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "El visitant mira fixament un Maó!\p"
	.string "Potser el visitant pensa en\n"
	.string "l'objecte que hi ha a sobre.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "El visitant camina per sobre\n"
	.string "la Taula Sòlida.\p"
	.string "El visitant mira avall tot el rato.\p"
	.string "El visitant resulta ser tímid\n"
	.string "i cautelós!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "El visitant mira fixament\n"
	.string "una Tanca!\p"
	.string "Se li ha acudit una nova idea\n"
	.string "per a una trampa?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "El visitant ha trepitjat\n"
	.string "una Estora Brillant!\p"
	.string "El visitant fa tot de poses!\p"
	.string "El visitant sembla fantasiejar\n"
	.string "amb ser un ídol!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "El visitant mira fixament\n"
	.string "un Pneumàtic!\p"
	.string "Podria ser que el visitant pensi\n"
	.string "en quin cotxe l'usaria?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "El visitant ha pujat a una Grada!\p"
	.string "El visitant mira la Base de\n"
	.string "{STR_VAR_1} des de dalt!\p"
	.string "I…\p"
	.string "Deixa anar un crit!\n"
	.string "El visitant crida!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "El visitant s'ha llançat de cap\n"
	.string "contra una Porta Trencadissa!\p"
	.string "El visitant riu a carcallades!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "El visitant parla amb una Nina!\p"
	.string "…Fa una mica de respecte…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "El visitant puja l'escala\n"
	.string "d'un Tobogan!\p"
	.string "I…\p"
	.string "El visitant ha baixat lliscant!\p"
	.string "Sembla que el visitant s'ho passa\n"
	.string "d'allò més bé!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "El visitant puja l'escala\n"
	.string "d'un Tobogan!\p"
	.string "I…\p"
	.string "El visitant ha tornat a baixar\n"
	.string "per l'escala!\p"
	.string "Ha tingut por de sobte?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "El visitant ha trepitjat\n"
	.string "una Estora de Salt!\p"
	.string "El visitant ha saltat un cop!\p"
	.string "Ha saltat dos cops!\p"
	.string "I un aterratge reeixit!\p"
	.string "El visitant aplaudeix!\n"
	.string "Quina actuació en solitari!$"

gTVSafariFanClubText00::
	.string "Club de Fans del Safari!\p"
	.string "Reporter: Molt bé, companys!\n"
	.string "Llançant Safari Balls, oi?\p"
	.string "Aquí estic a la Zona Safari plena\n"
	.string "de Pokémon increïbles!\p"
	.string "Anem a xerrar amb aquest bon\n"
	.string "Guia del Safari!\p"
	.string "Molt bé, amic, com van els\n"
	.string "Entrenadors visitants?$"

gTVSafariFanClubText01::
	.string "Guia: Tothom sembla que s'hi\n"
	.string "esforça molt.\p"
	.string "{STR_VAR_1} ho fa especialment bé.\p"
	.string "De fet, abans {STR_VAR_1} va atrapar\n"
	.string "{STR_VAR_2} Pokémon.$"

gTVSafariFanClubText02::
	.string "L'Entrenador és hàbil amb els\n"
	.string "{POKEBLOCK}s. En va usar {STR_VAR_2},\l"
	.string "crec.$"

gTVSafariFanClubText03::
	.string "L'Entrenador no va usar ni un sol\n"
	.string "{POKEBLOCK}! Ni un!\p"
	.string "Això és un expert!$"

gTVSafariFanClubText04::
	.string "Reporter: Ah sí?\p"
	.string "Sembla que {STR_VAR_1} és un gran\n"
	.string "mestre del Safari!\p"
	.string "Guia: Espero que l'Entrenador torni\n"
	.string "i ens mostri aquella gran tècnica.$"

gTVSafariFanClubText05::
	.string "Guia: Ningú sembla anar gaire bé.\p"
	.string "{STR_VAR_1} ho ha tingut especialment\n"
	.string "malament.\p"
	.string "De fet, l'Entrenador només va\n"
	.string "aconseguir atrapar {STR_VAR_2} Pokémon.$"

gTVSafariFanClubText06::
	.string "Guia: Ningú sembla anar gaire bé.\p"
	.string "{STR_VAR_1} ho ha tingut especialment\n"
	.string "malament.\p"
	.string "De fet, l'Entrenador no va atrapar\n"
	.string "ni un Pokémon. Ni un!$"

gTVSafariFanClubText07::
	.string "L'Entrenador sí que usa {POKEBLOCK}s.\n"
	.string "En va usar {STR_VAR_2}, crec.\p"
	.string "Però, noi, m'agradaria que\n"
	.string "l'Entrenador millorés una mica.$"

gTVSafariFanClubText08::
	.string "Crec que l'Entrenador tindria més\n"
	.string "sort usant {POKEBLOCK}s, que no es\l"
	.string "van usar aquella vegada.$"

gTVSafariFanClubText09::
	.string "Reporter: Ah sí?\p"
	.string "Sembla que {STR_VAR_1} necessita\n"
	.string "més experiència al Safari.\p"
	.string "Guia: Espero que l'Entrenador\n"
	.string "visiti una i altra vegada per\l"
	.string "agafar-li el truc.$"

gTVSafariFanClubText10::
	.string "Reporter: Ben cert!\n"
	.string "Fer front als reptes és important!\p"
	.string "Espectadors, veniu a la Zona Safari\n"
	.string "i accepteu el repte!\p"
	.string "Fins la propera, adéu!$"

ContestLiveUpdates_Text_Intro::
	.string ""Concurs Pokémon en Directe!"\p"
	.string "Presentador: Gràcies per ser-hi!\p"
	.string "Som en directe des del lloc del\n"
	.string "{STR_VAR_1} que acaba de finalitzar.\p"
	.string "La sala encara és plena d'un públic\n"
	.string "que no vol marxar.\p"
	.string "Espectador: {STR_VAR_2}!\p"
	.string "Espectador: {STR_VAR_3}!\p"
	.string "Presentador: Com acabeu de sentir,\n"
	.string "el Concurs l'ha guanyat el Pokémon\l"
	.string "{STR_VAR_2} de {STR_VAR_3}.\p"
	.string "Espectador: {STR_VAR_2}!\n"
	.string "Ets el millor!\p"
	.string "Espectador: {STR_VAR_3}!\n"
	.string "Molt bé!\p"
	.string "Presentador: Sentim què diuen\n"
	.string "els fans d'aquest Concurs.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Espectador: El {STR_VAR_2} ha estat\n"
	.string "el millor en ambdues avaluacions!\p"
	.string "Aquell {STR_VAR_2} seguirà guanyant!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Espectador: El {STR_VAR_2} no va fer bé\n"
	.string "a la primera avaluació, però va\l"
	.string "arrasar a la segona!\p"
	.string "Va ser una remuntada miraculosa\n"
	.string "per al {STR_VAR_2}. Bé!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Espectador: El {STR_VAR_2} ha estat\n"
	.string "consistent en ambdues avaluacions.\p"
	.string "{STR_VAR_3} i el {STR_VAR_2},\n"
	.string "no són un combo qualsevol!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Espectador: En termes de ser\n"
	.string "{STR_VAR_1}, aquell {STR_VAR_2} era\l"
	.string "excepcional.\p"
	.string "Espero que faci millors actuacions\n"
	.string "la propera vegada.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Espectador: Quan el {STR_VAR_2} es va\n"
	.string "posar nerviós, no vaig poder evitar\l"
	.string "cridar-li ànims.\p"
	.string "Vull dir-li a aquell {STR_VAR_2}:\n"
	.string ""Felicitats!"$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Espectador: L'actuació d'aquell\n"
	.string "{STR_VAR_2} fins i tot m'ha sorprès!\p"
	.string "{STR_VAR_2}, has estat genial!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Espectador: L'actuació combo\n"
	.string "d'aquell {STR_VAR_2} era impressionant!\p"
	.string "M'ha sacsejat fins al moll de l'os!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Espectador: L'actuació del {STR_VAR_2}\n"
	.string "guanyador m'ha accelerat el cor!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "Has estat genial!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Has estat preciós!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "Has estat bonic!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "Has estat llest!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "Has estat dur!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Espectador: L'actuació del {STR_VAR_2}\n"
	.string "guanyador encara em fa batre el cor!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "Ets l'últim crit en genialitat!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Ets el més bonic!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "Ets simplement el més maco!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "Ets el més llest dels llests!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "Ets el més dur dels durs!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Espectador: Fins i tot quan el\n"
	.string "{STR_VAR_2} va deixar de fer actuacions,\l"
	.string "no podia apartar-li els ulls.\p"
	.string "Estic captivat per aquell {STR_VAR_2}.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Espectador: Quan el {STR_VAR_2} es va\n"
	.string "sobresaltar per l'actuació d'un\l"
	.string "altre Pokémon, gairebé ploro.\p"
	.string "{STR_VAR_2}, has estat resistent!\n"
	.string "Molt bé!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Espectador: Oh…\n"
	.string "El {STR_VAR_3} d'aquell {STR_VAR_2}!\l"
	.string "El {STR_VAR_3} de {STR_VAR_2}!\l"
	.string "El {STR_VAR_3} de {STR_VAR_2}!\l"
	.string "Com pot ser tan meravellós?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "Presentador: Doncs, aquí ho teniu.\n"
	.string "Aquest lloc és ple de fans del\l"
	.string "{STR_VAR_1}!\p"
	.string "També haig de mencionar que un\n"
	.string "altre Pokémon, el {STR_VAR_3} de\l"
	.string "{STR_VAR_2}, em va cridar l'atenció.\p"
	.string "El {STR_VAR_3} de {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "No va fer ni una sola actuació durant\n"
	.string "la segona avaluació pels nervis.\p"
	.string "La propera vegada, voldria veure\n"
	.string "aquest {STR_VAR_1} fer almenys una\l"
	.string "actuació.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Ha quedat últim en ambdues\n"
	.string "avaluacions.\p"
	.string "Espero que {STR_VAR_1} reentreni\n"
	.string "aquest {STR_VAR_2} i esborri la\l"
	.string "vergonya d'aquest indiscutible\l"
	.string "últim lloc.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "No ha sabut aprofitar l'emoció\n"
	.string "del públic per fer una actuació\l"
	.string "adequada.\p"
	.string "Esperem que {STR_VAR_1} aprengui a\n"
	.string "sentir el públic i portar la seva\l"
	.string "emoció al màxim la propera vegada.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Tot i acabar primer a la primera\n"
	.string "avaluació, les actuacions de la\l"
	.string "segona no van funcionar.\p"
	.string "Va patir una humiliant derrota\n"
	.string "per remuntada.\p"
	.string "Segur que {STR_VAR_1} ara estudia com\n"
	.string "fer actuacions més efectives.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "El públic mai es va emocionar amb\n"
	.string "les actuacions de la segona\l"
	.string "avaluació.\p"
	.string "Esperem que deixi de preocupar-se\n"
	.string "pels altres Pokémon i aprengui a\l"
	.string "dirigir les actuacions al públic.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Ha perdut contra el {STR_VAR_2}\n"
	.string "de {STR_VAR_1} per poc marge.\p"
	.string "Deu ser dolorós estar tan a prop\n"
	.string "de la victòria i fallar.\p"
	.string "No em sorprendria que {STR_VAR_3}\n"
	.string "plorés per aquest resultat.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Ha decebut el Jutge repetint\n"
	.string "les mateixes actuacions.\p"
	.string "És un error imperdonable en\n"
	.string "qualsevol Concurs, i ho ha pagat.\p"
	.string "{STR_VAR_1} hauria de sentir-se\n"
	.string "culpable per aquesta pobre actuació.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} va fer un esforç valent,\n"
	.string "però…\p"
	.string "Tot va ser en va, acabant últim.\p"
	.string "{STR_VAR_1} hauria d'aprendre d'aquesta\n"
	.string "derrota i aprofitar-ho bé.$"

ContestLiveUpdates_Text_Outro::
	.string "Vull acabar el programa amb el\n"
	.string "nostre habitual comiat als guanyadors.\p"
	.string "Aquesta vegada, és {STR_VAR_1} i\n"
	.string "el {STR_VAR_2}!\p"
	.string "Presentador: Tothom a punt?\n"
	.string "Tots plegats!\p"
	.string "Públic: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Felicitats!\l"
	.string "Ets el guanyador del Concurs!$"

gTVPokemonBattleUpdateText00::
	.string ""Actualització de Combat Pokémon!"\p"
	.string "Us portem els resultats dels combats\n"
	.string "Pokémon tal com arriben!$"

gTVPokemonBattleUpdateText01::
	.string "Els Entrenadors {STR_VAR_1} i\n"
	.string "{STR_VAR_2} s'han enfrontat en\l"
	.string "un Combat {STR_VAR_3}.\p"
	.string "Aquest combat ha acabat amb\n"
	.string "victòria per a {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "Al combat, el {STR_VAR_2}\n"
	.string "de {STR_VAR_1} ha estat una força\l"
	.string "formidable amb {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "El {STR_VAR_2} de {STR_VAR_1} ha fet\n"
	.string "una actuació feble que ha pesat.$"

gTVPokemonBattleUpdateText04::
	.string "Felicitats per la victòria,\n"
	.string "{STR_VAR_1}!\p"
	.string "I per al derrotat {STR_VAR_2},\n"
	.string "esperem un millor resultat!\p"
	.string "Aquí acaba aquest episodi\n"
	.string "d'"Actualització de Combat Pokémon!"$"

gTVPokemonBattleUpdateText05::
	.string "Els equips de {STR_VAR_1} i\n"
	.string "{STR_VAR_2} s'han trobat en un Multi\l"
	.string "Combat.\p"
	.string "Aquest combat ha acabat amb\n"
	.string "victòria per a l'equip de {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "Al combat, el {STR_VAR_2} de l'equip\n"
	.string "de {STR_VAR_1} ha estat una força\l"
	.string "formidable amb {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "L'actuació feble del {STR_VAR_3}\n"
	.string "de l'equip de {STR_VAR_2} ha pesat.\p"
	.string "Felicitats per la victòria del\n"
	.string "teu equip, {STR_VAR_1}!\p"
	.string "Quant a l'equip derrotat de\n"
	.string "{STR_VAR_2}, esperem millor sort!\p"
	.string "Aquí acaba aquest episodi\n"
	.string "d'"Actualització de Combat Pokémon!"$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "Gabby: Oh! Acabem de veure un\n"
	.string "Entrenador de pinta forta aquí!\p"
	.string "D'acord, càmera en marxa!\n"
	.string "Aconseguim l'entrevista.$"

GabbyAndTy_Text_GabbyIntro:
	.string "Gabby: Oh! Ets {PLAYER}! Hola!\n"
	.string "Ens recordes de l'última vegada?\p"
	.string "Ens pots mostrar com de fort t'has\n"
	.string "fet? D'acord, comencem l'entrevista!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "Gabby: Els meus ulls no m'enganyaven!\n"
	.string "He descobert un Entrenador increïble!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "Gabby: Genial! Genial!\n"
	.string "Qui ets?!\p"
	.string "Sabia que teníem alguna cosa\n"
	.string "quan et vam veure!\p"
	.string "Oh, deixa que m'expliqui. Viatgem\n"
	.string "per tot arreu entrevistant tot\l"
	.string "tipus d'Entrenadors.\p"
	.string "Ens podries dedicar una estona\n"
	.string "per una entrevista?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "Gabby: "{STR_VAR_1}!"\p"
	.string "Recordes? Aquesta és la cita que\n"
	.string "ens vas donar l'última vegada.\p"
	.string "No oblido mai coses així!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "L'última vegada, ens vas aixafar\n"
	.string "abans que poguéssim reaccionar…\p"
	.string "En fi, què en penses?\n"
	.string "Vols ser entrevistat de nou?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "L'última vegada, no ens vas llançar\n"
	.string "una Poké Ball?\p"
	.string "Ens vam quedar de pedra! Ho vam\n"
	.string "explicar a tothom, absolutament!\p"
	.string "En fi, què en penses?\n"
	.string "Vols ser entrevistat de nou?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "L'última vegada, les teves habilitats\n"
	.string "amb objectes ens van vèncer.\p"
	.string "En fi, què en penses?\n"
	.string "Vols ser entrevistat de nou?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "L'última vegada, vam aconseguir\n"
	.string "fer un bon paper.\p"
	.string "En fi, què en penses?\n"
	.string "Vols ser entrevistat de nou?$"

GabbyAndTy_Text_InterviewAgain:
	.string "En fi, què en penses?\n"
	.string "Vols ser entrevistat de nou?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Vols?\n"
	.string "Gràcies!\p"
	.string "D'acord, necessito que descriguis\n"
	.string "el que sents sobre el nostre\l"
	.string "combat, però curt i concís. Endavant!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "Gabby: Mmm, sí!\n"
	.string "El final perfecte!\p"
	.string "Tinc la sensació que això farà\n"
	.string "un gran programa de TV.\p"
	.string "Hi ha possibilitats que ho emetin\n"
	.string "per TV, així que busca'ns!\p"
	.string "D'acord!\n"
	.string "Ens veurem!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "Gabby: Oh…\p"
	.string "D'acord, però no et rendeixis!\n"
	.string "Estarem atents!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "Gabby: Estarem atents\n"
	.string "per si et veiem!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "Gabby: Hi ha algun Entrenador fort\n"
	.string "per aquí amb molts Pokémon?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "Gabby: Uau, ets increïble!\p"
	.string "T'has fet molt més fort des de\n"
	.string "l'última vegada que vam combatre.\p"
	.string "Teníem raó sobre tu quan et vam\n"
	.string "identificar com a gran Entrenador.\p"
	.string "Doncs, què en penses?\n"
	.string "Ens vols concedir una entrevista\l"
	.string "aquesta vegada?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "Gabby: Ha estat un combat intens!\n"
	.string "Ho has gravat tot amb la càmera?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "Ty: Ei, mira! Un Entrenador de pinta\n"
	.string "forta aquí, ni més ni menys!\l"
	.string "La càmera grava!$"

GabbyAndTy_Text_TyIntro:
	.string "Ty: Ei, mira!\n"
	.string "Et recordo!\p"
	.string "Gravaré tot aquest combat\n"
	.string "amb la càmera!$"

GabbyAndTy_Text_TyPostBattle:
	.string "Ty: Ets un natural!\n"
	.string "Tinc un material de primera!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "Ty: Només tens un Pokémon\n"
	.string "i prou?\p"
	.string "Si en tinguessis més, les imatges\n"
	.string "serien millors, però…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "Ty: Sí, hem trobat un gran Entrenador.\n"
	.string "Això és una exclusiva per nosaltres!$"

GabbyAndTy_Text_TyDefeat:
	.string "Ty: Sí, ho tinc tot.\n"
	.string "Tot el combat és a la càmera.$"

gTVInSearchOfTrainersText00::
	.string "A la Recerca d'Entrenadors…\p"
	.string "Gabby: Hola! Avui visito una zona\n"
	.string "a prop de {STR_VAR_1}.\p"
	.string "Estem intentant trobar nous talents\n"
	.string "prometedors.\p"
	.string "Avui, hem enfocat la càmera cap a\n"
	.string "l'Entrenador {PLAYER}.\p"
	.string "Hi ha alguna cosa en aquest\n"
	.string "Entrenador que ens ha intrigat.$"

gTVInSearchOfTrainersText01::
	.string "Ja hem combatut amb {PLAYER} abans,\n"
	.string "i podem confirmar que l'Entrenador\l"
	.string "ha millorat des de llavors.\p"
	.string "Sabia que teníem algú especial\n"
	.string "quan el vam veure!$"

gTVInSearchOfTrainersText02::
	.string "La millor manera de determinar\n"
	.string "com de fort és un Entrenador…\p"
	.string "La forma més ràpida és combatre.\n"
	.string "I així vam començar la investigació!\p"
	.string "… …\p"
	.string "Així és com vam acabar en combat\n"
	.string "amb {PLAYER}.\p"
	.string "Amb una actuació dominant, ens van\n"
	.string "aixafar, enrotllar i llençar!\p"
	.string "{PLAYER} és despietadament fort…\p"
	.string "Aquí teniu les nostres impressions\n"
	.string "després de combatre l'Entrenador.$"

gTVInSearchOfTrainersText03::
	.string "La combinació de {STR_VAR_1} i\n"
	.string "{STR_VAR_3} era divina!\p"
	.string "Veure'ls, {STR_VAR_1} i {STR_VAR_3},\n"
	.string "donant-se suport mútuament\l"
	.string "en el fragor de la batalla…\p"
	.string "Era un espectacle meravellós!\p"
	.string "{STR_VAR_2} va ser el moviment que\n"
	.string "va usar últim al nostre combat.\p"
	.string "El moviment {STR_VAR_2} és el signe\n"
	.string "d'amistat de {STR_VAR_1} i {STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "…Vaig perdre confiança en mi\n"
	.string "mateixa pel nostre encontre.\p"
	.string "Ens van vèncer abans de poder\n"
	.string "llançar un sol atac.\l"
	.string "Ohhh… Snif…\p"
	.string "Tot i així, els combats de {PLAYER}\n"
	.string "valen la pena de veure.\p"
	.string "Recomano als Entrenadors confiats\n"
	.string "que desafiïn {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Només hi ha una cosa a dir.\n"
	.string "No gosis llançar una Poké Ball\l"
	.string "durant un combat d'Entrenadors!\p"
	.string "{PLAYER} és fort, però no coneix\n"
	.string "les regles bàsiques.\p"
	.string "A la nostra audiència, una petició.\p"
	.string "Si veieu {PLAYER}, si us plau,\n"
	.string "advertiu l'Entrenador!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} és expert en llegir les\n"
	.string "accions de l'oponent.\p"
	.string "El moment d'usar els objectes era\n"
	.string "remarcablement efectiu!$"

gTVInSearchOfTrainersText07::
	.string "Sincerament, pensava que jo\n"
	.string "també era força bona.\p"
	.string "Tot i que vam acabar perdent, va ser\n"
	.string "un combat molt disputat.\p"
	.string "Però si lluites contra mi, encara\n"
	.string "et queda camí, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Després del combat, hem demanat a\n"
	.string "{PLAYER} un resum breu.\p"
	.string "L'Entrenador ha respost:\n"
	.string ""{STR_VAR_1}."\p"
	.string "Els Pokémon de {PLAYER}, {STR_VAR_2}\n"
	.string "i {STR_VAR_3}…\l"
	.string "I "{STR_VAR_1}"…\p"
	.string "Mmm! Profund! Hi ha un significat\n"
	.string "profund darrere d'aquesta cita!\p"
	.string "No és cap sorpresa: un bon Entrenador\n"
	.string "diu coses bones.\p"
	.string "Això és tot per avui!\n"
	.string "Ens veiem a la propera emissió!$"

ContestLadyShow_Text_Intro::
	.string ""Concurs Pokémon EN DIRECTE!"\p"
	.string "Presentador: Perdoneu la interrupció\n"
	.string "i gràcies per ser-hi!\p"
	.string "Us ho portem en directe des\n"
	.string "del lloc d'un {STR_VAR_1}\l"
	.string "acabat de completar!\p"
	.string "Espectadors: ?!!!!\p"
	.string "Presentador: Oh! Sembla que els\n"
	.string "participants venen cap aquí!\p"
	.string "Intentaré aconseguir una entrevista\n"
	.string "improvisada per vosaltres!\p"
	.string "Espectadors: ?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "Presentador: Perdona!\n"
	.string "Gràcies per ser a la TV en directe!\p"
	.string "Puc felicitar-te per la victòria?\p"
	.string "Quin ha estat el factor clau de\n"
	.string "la victòria d'avui?\p"
	.string "Noia: Avui hem donat el millor\n"
	.string "de nosaltres, el {STR_VAR_2} i jo!\p"
	.string "Però segur que no ho hauríem\n"
	.string "aconseguit sense tota l'ajuda\l"
	.string "que hem rebut abans del Concurs!\p"
	.string "Presentador: Tens algú especial amb\n"
	.string "qui vulguis compartir l'alegria?\l"
	.string "Sentim-ho en directe!\p"
	.string "Noia: Ei, allà fora!\p"
	.string "{STR_VAR_3}! Estàs mirant?\n"
	.string "Ho hem aconseguit!\l"
	.string "Gràcies!$"

ContestLadyShow_Text_Lost::
	.string "Presentador: Perdona!\n"
	.string "Gràcies per ser a la TV en directe!\p"
	.string "Deus estar decebuda. Tens algun\n"
	.string "comentari?\p"
	.string "Noia: Em fa molta pena…\n"
	.string "El meu {STR_VAR_2} i jo, ho vam donar\l"
	.string "tot…\p"
	.string "Però sento que he fallat a tots els\n"
	.string "que ens han donat suport.\p"
	.string "Presentador: No ho vull dir, però la\n"
	.string "coloració del Pokémon no era ideal.\p"
	.string "Noia: {STR_VAR_3}, ho sento molt…\n"
	.string "Ho faré millor, ho prometo…\l"
	.string "…Snif… Buaaaa!\p"
	.string "Espectadors: Heu vist?\n"
	.string "Pobra noia!\p"
	.string "Presentador: Eh… Ui…\p"
	.string "Eh… Això és tot per avui!\n"
	.string "Gràcies per sintonitzar-nos!$"

ContestLadyShow_Text_LostBadly::
	.string "Presentador: Perdona!\n"
	.string "Gràcies per ser a la TV en directe!\p"
	.string "Com ha anat la teva participació?\p"
	.string "Noia: Res ha anat bé…\n"
	.string "Per alguna raó, el meu {STR_VAR_2}\l"
	.string "no atreia gens de popularitat.\p"
	.string "Presentador: No ho vull dir, però la\n"
	.string "coloració del Pokémon no era ideal.\p"
	.string "Noia: … … … … … …\n"
	.string "…Snif… Buaaaa!\p"
	.string "Espectadors: Heu vist?\n"
	.string "Pobra noia!\p"
	.string "Presentador: Eh… Ui…\p"
	.string "Eh… Això és tot per avui!\n"
	.string "Gràcies per sintonitzar-nos!$"