ViridianForest_NorthEntrance_MapScripts::
	.byte 0

Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
	msgbox Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests, MSGBOX_NPC
    end

Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Molts Pokémon viuen només a\n"
    .string "boscos i coves.\p"
    .string "Has de ser persistent i buscar\n"
    .string "per tot arreu per trobar-ne\l"
    .string "de diferents.$"

Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "T'has fixat en els arbres prims\n"
    .string "a la vora del camí?\p"
    .string "Es poden tallar amb un moviment\n"
    .string "especial de Pokémon, he sentit.$"

Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Coneixes la tècnica de cancel·lar\n"
    .string "l'evolució?\p"
    .string "Quan un Pokémon evoluciona, pots\n"
    .string "aturar el procés.\p"
    .string "És una tècnica per criar Pokémon\n"
    .string "tal com són.$"
