SafariZone_West_RestHouse_MapScripts::
	.byte 0


SafariZone_West_RestHouse_EventScript_Man::
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
	end

SafariZone_West_Text_BaitMakesMonStickAround::
	.string "No tinc cap {POKEBLOCK}, però he capturat\n"
	.string "uns quants Pokémon.\p"
	.string "Pots millorar les teves opcions de\n"
	.string "captura acostant-te als Pokémon\l"
	.string "abans de llançar una Safari Ball.$"

SafariZone_West_RestHouse_EventScript_Scientist::
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
	end

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
	.string "He posat un {POKEBLOCK} al Dispensador\n"
	.string "de {POKEBLOCK}. Però sembla que ha\l"
	.string "desaparegut.\p"
	.string "Suposo que els Pokémon se l'han\n"
	.string "menjat sense que me n'adonés.$"


SafariZone_West_RestHouse_EventScript_CooltrainerF::
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
	end

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "He caminat molt, però no he vist\n"
    .string "cap Pokémon que volgués.$"
