PewterCity_House2_MapScripts::
	.byte 0

PewterCity_House2_EventScript_OldMan::
	msgbox PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow, MSGBOX_NPC
	end

PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "Els Pokémon aprenen tècniques\n"
    .string "noves a mesura que creixen.\p"
    .string "Però alguns moviments els han\n"
    .string "d'ensenyar les persones.$"

PewterCity_House2_EventScript_LittleBoy::
	msgbox PewterCity_House2_Text_MonsEasierCatchIfStatused, MSGBOX_NPC
	end

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "Un Pokémon és més fàcil de\n"
    .string "capturar si té un problema d'estat.\p"
    .string "Son, verí, cremada o paràlisi…\n"
    .string "Tots són efectius.\p"
    .string "Però capturar Pokémon mai no és\n"
    .string "cosa segura!$"
