# -*- coding: utf-8 -*-
"""Catalan translation for src/strings.c (part 2: PC, PokeGear, options,
Frontier, Mystery Gift, easy chat, misc)."""
KIND = 'c'
FILES = ['src/strings.c']

T = {
# ---- met / nature summary lines ----
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\\nmet at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\\ntrobat al {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\\nhatched at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\\nnascut al {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\\nobtained in a trade.": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\\nobtingut en un intercanvi.",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\\nobtained in a fateful\\nencounter at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\\nobtingut en una trobada\\ndel destí al {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\\nprobably met at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\\ntrobat potser al {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\\nmet somewhere at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\\ntrobat en algun lloc al {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\\nhatched somewhere at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\\nnascut en algun lloc al {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.",
"An odd Pokémon Egg found\\nby the Day Care couple.": "Un Ou de Pokémon estrany trobat\\nper la parella de la Guarderia.",
"A peculiar Pokémon Egg\\nobtained at the nice place.": "Un Ou de Pokémon peculiar\\nobtingut en aquell lloc tan bonic.",
"A peculiar Pokémon Egg\\nobtained in a trade.": "Un Ou de Pokémon peculiar\\nobtingut en un intercanvi.",
"A Pokémon Egg obtained\\nat the hot springs.": "Un Ou de Pokémon obtingut\\na les fonts termals.",
"An odd Pokémon Egg\\nobtained from a traveler.": "Un Ou de Pokémon estrany\\nobtingut d'un viatger.",
"{STR_VAR_1} hatched from the Egg!": "{STR_VAR_1} ha sortit de l'Ou!",
"Would you like to nickname the newly\\nhatched {STR_VAR_1}?": "Vols posar un sobrenom a\\n{STR_VAR_1}, que acaba de néixer?",

# ---- registry / decorations ----
"Is it okay to delete {STR_VAR_1}\\nfrom the registry?": "Vols esborrar {STR_VAR_1}\\ndel registre?",
"The registered data was deleted.{PAUSE_UNTIL_PRESS}": "S'han esborrat les dades registrades.{PAUSE_UNTIL_PRESS}",
"There is no registry.{PAUSE_UNTIL_PRESS}": "No hi ha cap registre.{PAUSE_UNTIL_PRESS}",
"Del Regist.": "Esb. registre",
"Decorate": "Decorar",
"Put away": "Retirar",
"Put out the selected decoration item.": "Col·loca la decoració triada.",
"Store the chosen decoration in the PC.": "Guarda la decoració triada al PC.",
"Throw away unwanted decorations.": "Llença les decoracions que no vols.",
"There are no decorations.{PAUSE_UNTIL_PRESS}": "No hi ha cap decoració.{PAUSE_UNTIL_PRESS}",
"Big Doll": "Nina gran",
"Chair": "Cadira",
"Plant": "Planta",
"Ornament": "Ornament",
"Mat": "Estora",
"Poster": "Pòster",
"Doll": "Nina",
"Cushion": "Coixí",
"Gold": "Or",
"Silver": "Plata",
"Bronze": "Bronze",
"Copper": "Coure",
"Place it here?": "Vols posar-ho aquí?",
"It can't be placed here.": "Aquí no es pot posar.",
"Cancel decorating?": "Vols deixar de decorar?",
"No more decorations can be placed.\\nThe most that can be placed are {STR_VAR_1}.": "No hi caben més decoracions.\\nEl màxim que hi cap és {STR_VAR_1}.",
"This can't be placed here.\\nIt must be on a Desk, etc.": "Aquí no es pot posar.\\nHa d'anar sobre una taula o similar.",
"This decoration can't be placed in\\nyour own room.": "Aquesta decoració no es pot posar\\na la teva habitació.",
"This decoration is in use.\\nIt can't be thrown away.": "Aquesta decoració s'està fent servir.\\nNo es pot llençar.",
"This {STR_VAR_1} will be discarded.\\nIs that okay?": "Es llençarà {STR_VAR_1}.\\nHi estàs d'acord?",
"The decoration item was thrown away.": "S'ha llençat la decoració.",
"Stop putting away decorations?": "Vols deixar de retirar decoracions?",
"There is no decoration item here.": "Aquí no hi ha cap decoració.",
"Return this decoration to the PC?": "Vols tornar aquesta decoració al PC?",
"The decoration was returned to the PC.": "La decoració s'ha tornat al PC.",
"There are no decorations in use.{PAUSE_UNTIL_PRESS}": "No hi ha cap decoració en ús.{PAUSE_UNTIL_PRESS}",
"Pretty Chair": "Cadira bonica",
"Pretty Desk": "Taula bonica",
"Glass Chair": "Cadira de vidre",
"Glass Desk": "Taula de vidre",

# ---- PC ----
"Turn off": "Apagar",
"Decoration": "Decoració",
"Item storage": "Magatzem d'objectes",
"Mailbox": "Bústia",
"Deposit item": "Dipositar objecte",
"Withdraw item": "Retirar objecte",
"Toss item": "Llençar objecte",
"Store items in the PC.": "Guarda objectes al PC.",
"Take out items from the PC.": "Treu objectes del PC.",
"Throw away items stored in the PC.": "Llença objectes guardats al PC.",
"There are no items.{PAUSE_UNTIL_PRESS}": "No hi ha cap objecte.{PAUSE_UNTIL_PRESS}",
"There is no more\\nroom in the Bag.": "Ja no queda espai\\na la motxilla.",
"Withdraw how many\\n{STR_VAR_1}(s)?": "Quants {STR_VAR_1}\\nvols retirar?",
"Withdrew {STR_VAR_2}\\n{STR_VAR_1}(s).": "S'han retirat {STR_VAR_2}\\n{STR_VAR_1}.",
"Move to Bag": "Passa a la motxilla",
"There's no mail here.{PAUSE_UNTIL_PRESS}": "Aquí no hi ha cap carta.{PAUSE_UNTIL_PRESS}",
"What would you like to do with\\n{STR_VAR_1}'s mail?": "Què vols fer amb la carta de\\n{STR_VAR_1}?",
"The message will be lost.\\nIs that okay?": "Es perdrà el missatge.\\nHi estàs d'acord?",
"The Bag is full.{PAUSE_UNTIL_PRESS}": "La motxilla és plena.{PAUSE_UNTIL_PRESS}",
"The mail was returned to the Bag\\nwith its message erased.{PAUSE_UNTIL_PRESS}": "La carta ha tornat a la motxilla\\namb el missatge esborrat.{PAUSE_UNTIL_PRESS}",
"Someone's PC": "El PC d'algú",
"{PLAYER}'s PC": "El PC de {PLAYER}",
"Log off": "Desconnectar",

# ---- storage system ----
"Exit from the box?": "Vols sortir de la caixa?",
"What do you want to do?": "Què vols fer?",
"Please pick a theme.": "Tria un tema.",
"Pick the wallpaper.": "Tria el fons.",
"{DYNAMIC 0} is selected.": "S'ha triat {DYNAMIC 0}.",
"Jump to which box?": "A quina caixa vols anar?",
"Deposit in which box?": "A quina caixa vols dipositar?",
"{DYNAMIC 0} was deposited.": "S'ha dipositat {DYNAMIC 0}.",
"The box is full.": "La caixa és plena.",
"Release this Pokémon?": "Vols alliberar aquest Pokémon?",
"{DYNAMIC 0} was released.": "S'ha alliberat {DYNAMIC 0}.",
"Bye-bye, {DYNAMIC 0}!": "Adéu, {DYNAMIC 0}!",
"Mark your Pokémon.": "Marca el teu Pokémon.",
"That's your last Pokémon!": "És el teu últim Pokémon!",
"Your party's full!": "Tens l'equip ple!",
"You're holding a Pokémon!": "Estàs agafant un Pokémon!",
"Which one will you take?": "Quin vols agafar?",
"You can't release an Egg.": "No pots alliberar un Ou.",
"Continue box operations?": "Vols continuar amb les caixes?",
"{DYNAMIC 0} came back!": "{DYNAMIC 0} ha tornat!",
"Was it worried about you?": "Estava preocupat per tu?",
"Please remove the mail.": "Retira la carta, si et plau.",
"Give to a Pokémon?": "Vols donar-ho a un Pokémon?",
"Placed item in the Bag.": "S'ha posat l'objecte a la motxilla.",
"The Bag is full.": "La motxilla és plena.",
"Put this item in the Bag?": "Vols posar l'objecte a la motxilla?",
"{DYNAMIC 0} is now held.": "Ara porta {DYNAMIC 0}.",
"Changed to {DYNAMIC 0}.": "S'ha canviat per {DYNAMIC 0}.",
"Mail can't be stored!": "Les cartes no es poden guardar!",
"Withdraw": "Retirar",
"Move": "Moure",
"Place": "Col·locar",
"Release": "Alliberar",
"Mark": "Marcar",
"Wallpaper": "Fons",
"Scenery 1": "Paisatge 1",
"Scenery 2": "Paisatge 2",
"Scenery 3": "Paisatge 3",
"Etcetera": "Altres",
"Friends": "Amics",
"Forest": "Bosc",
"City": "Ciutat",
"Desert": "Desert",
"Savanna": "Savana",
"Crag": "Cingle",
"Volcano": "Volcà",
"Snow": "Neu",
"Cave": "Cova",
"Beach": "Platja",
"Seafloor": "Fons marí",
"River": "Riu",
"Sky": "Cel",
"Polka-dot": "Pics",
"PokéCenter": "Centre Pokémon",
"Machine": "Màquina",
"Simple": "Senzill",
"Withdraw Pokémon": "Retirar Pokémon",
"Deposit Pokémon": "Dipositar Pokémon",
"Move Pokémon": "Moure Pokémon",
"Move items": "Moure objectes",
"See ya!": "Fins aviat!",
"Move Pokémon stored in boxes to\\nyour party.": "Passa Pokémon de les caixes\\na l'equip.",
"Store Pokémon in your party in boxes.": "Guarda a les caixes Pokémon\\nde l'equip.",
"Organize the Pokémon in boxes and\\nin your party.": "Organitza els Pokémon de les\\ncaixes i de l'equip.",
"Move items held by any Pokémon\\nin a box or your party.": "Mou objectes que porti qualsevol\\nPokémon d'una caixa o de l'equip.",
"Return to the previous menu.": "Torna al menú anterior.",
"There is just one Pokémon with you.": "Només portes un Pokémon.",
"Your party is full!": "Tens l'equip ple!",
"Box": "Caixa",

# ---- PokeGear ----
"PokéGear": "PokéGear",
"Check the map of the Kanto region.": "Consulta el mapa de la regió\\nde Kanto.",
"Check Pokémon in detail.": "Consulta els Pokémon en detall.",
"Call a registered Trainer.": "Truca a un entrenador registrat.",
"Check obtained Ribbons.": "Consulta les Cintes obtingudes.",
"Put away the PokéGear.": "Guarda el PokéGear.",
"There are no Ribbon winners.": "No hi ha guanyadors de Cintes.",
"No Trainers are registered.": "No hi ha cap entrenador registrat.",
"Check party Pokémon in detail.": "Consulta en detall els Pokémon\\nde l'equip.",
"Check all Pokémon in detail.": "Consulta en detall tots els Pokémon.",
"Return to the PokéGear menu.": "Torna al menú del PokéGear.",
"Find cool Pokémon.": "Cerca Pokémon guais.",
"Find beautiful Pokémon.": "Cerca Pokémon bonics.",
"Find cute Pokémon.": "Cerca Pokémon adorables.",
"Find smart Pokémon.": "Cerca Pokémon llestos.",
"Find tough Pokémon.": "Cerca Pokémon durs.",
"Return to the condition menu.": "Torna al menú de condició.",
"No. registered": "Núm. registrats",
"No. of battles": "Núm. de combats",
"Detail": "Detall",
"Call": "Trucar",
"Can't call opponent here.": "Aquí no pots trucar al rival.",
"Strategy": "Estratègia",
"Trainer's Pokémon": "Pokémon de l'entrenador",
"Self-introduction": "Presentació",
"A call can't be made from here.": "Des d'aquí no es pot trucar.",
"That Trainer is close by.\\nTalk to the Trainer in person!": "Aquest entrenador és a prop.\\nParla-hi en persona!",
"{A_BUTTON}Zoom {B_BUTTON}Cancel": "{A_BUTTON}Ampliar {B_BUTTON}Cancel·la",
"{A_BUTTON}Full {B_BUTTON}Cancel": "{A_BUTTON}Complet {B_BUTTON}Cancel·la",
"{A_BUTTON}Condition {B_BUTTON}Cancel": "{A_BUTTON}Condició {B_BUTTON}Cancel·la",
"{A_BUTTON}Markings {B_BUTTON}Cancel": "{A_BUTTON}Marques {B_BUTTON}Cancel·la",
"{A_BUTTON}Select mark {B_BUTTON}Cancel": "{A_BUTTON}Tria marca {B_BUTTON}Cancel·la",
"{A_BUTTON}Menu {B_BUTTON}Cancel": "{A_BUTTON}Menú {B_BUTTON}Cancel·la",
"{A_BUTTON}Ok {B_BUTTON}Cancel": "{A_BUTTON}D'acord {B_BUTTON}Cancel·la",
"{B_BUTTON}Cancel": "{B_BUTTON}Cancel·la",
"{A_BUTTON}Ribbons {B_BUTTON}Cancel": "{A_BUTTON}Cintes {B_BUTTON}Cancel·la",
"{A_BUTTON}Check {B_BUTTON}Cancel": "{A_BUTTON}Comprova {B_BUTTON}Cancel·la",
"No. {DYNAMIC 0}": "Núm. {DYNAMIC 0}",
"Ribbons {DYNAMIC 0}": "Cintes {DYNAMIC 0}",
"DexNav": "DexNav",

# ---- contests ----
"What's a Contest?": "Què és un concurs?",
"Types of Contests": "Tipus de concursos",
"Ranks": "Rangs",
"Judging": "Valoració",
"Coolness Contest": "Concurs de Estil",
"Beauty Contest": "Concurs de Bellesa",
"Cuteness Contest": "Concurs de Gràcia",
"Smartness Contest": "Concurs d'Enginy",
"Toughness Contest": "Concurs de Duresa",
"Cool": "Estil",
"Beauty": "Bellesa",
"Cute": "Gràcia",
"Smart": "Enginy",
"Tough": "Duresa",
"Coolness ": "L'estil ",
"Beauty ": "La bellesa ",
"Cuteness ": "La gràcia ",
"Smartness ": "L'enginy ",
"Toughness ": "La duresa ",
"was enhanced!": "ha millorat!",
"Nothing changed!": "No ha canviat res!",
"It won't eat anymore…": "Ja no en vol menjar més…",
" gets a {POKEBLOCK}?": " es menja un {POKEBLOCK}?",
"coolness": "estil",
"beauty": "bellesa",
"cuteness": "gràcia",
"smartness": "enginy",
"toughness": "duresa",
"Normal": "Normal",
"Super": "Súper",
"Hyper": "Híper",
"Master": "Mestre",
"Normal rank": "Rang normal",
"Super rank": "Rang súper",
"Hyper rank": "Rang híper",
"Master rank": "Rang mestre",
"Link contest": "Concurs per enllaç",
"Announcing the results!": "Es proclamen els resultats!",
"The preliminary results!": "Resultats preliminars!",
"Round 2 results!": "Resultats de la ronda 2!",
"{STR_VAR_1}'s {STR_VAR_2} won!": "Ha guanyat {STR_VAR_2} de {STR_VAR_1}!",
"{PLAYER}'s Link Contest Results": "Resultats del concurs per enllaç\\nde {PLAYER}",
"Won Contests W/Friends": "Concursos guanyats amb amics",

# ---- options ----
"Text speed": "Velocitat del text",
"Battle scene": "Escena de combat",
"Battle style": "Estil de combat",
"Sound": "So",
"Frame": "Marc",
"Follower": "Acompanyant",
"Button mode": "Mode de botons",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Partner": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Company",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Any": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Qualsevol",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}None": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Cap",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Slow": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Lenta",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Mid": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Mitjana",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Fast": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Ràpida",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}On": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Sí",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Off": "{COLOR GREEN}{SHADOW LIGHT_GREEN}No",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Shift": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Canvi",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Set": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Fix",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Mono": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Mono",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Stereo": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Estèreo",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Type": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Tipus",
"{COLOR GREEN}{SHADOW LIGHT_GREEN}Normal": "{COLOR GREEN}{SHADOW LIGHT_GREEN}Normal",

# ---- status abbreviations (3-char labels) ----
"PSN": "ENV",
"PAR": "PAR",
"SLP": "ADO",
"BRN": "CRE",
"FRZ": "GEL",
"Toxic": "Tòxic",
"Poison": "Verí",
"Sleep": "Son",
"Paralysis": "Paràlisi",
"Burn": "Cremada",
"Ice": "Gel",

# ---- yes/no & simple ----
"Ok": "D'acord",
"Saw it": "Vist",
"Not yet": "Encara no",
"Yes": "Sí",
"No": "No",
"Yes\\nNo": "Sí\\nNo",
"Single battle": "Combat individual",
"Double battle": "Combat doble",
"Multi battle": "Combat múltiple",
"Challenge": "Repte",
"Lv. 50": "Niv. 50",
"Open level": "Nivell obert",
"Open Lv.": "Niv. obert",
"No thanks!": "No, gràcies!",
"Good": "Bo",
"Very good": "Molt bo",
"So-so": "Regular",
"Bad": "Dolent",
"The worst": "El pitjor",
"Excellent": "Excel·lent",
"Not so good": "No gaire bo",
"Satisfied": "Satisfet",
"Dissatisfied": "Insatisfet",
"Right": "Dreta",
"Left": "Esquerra",
"Jump": "Saltar",
"Rest": "Descansar",
"Go on": "Continuar",
"Retire": "Retirar-se",
"Save": "Desar",
"Exit": "Sortir",
"Count": "Recompte",
"Registry": "Registre",
"Information": "Informació",
"Pack up": "Plegar",
"Opponent": "Rival",
"Trainer": "Entrenador",
"Friend": "Amic",
"Others": "Altres",
"Total": "Total",
"Current": "Actual",
"Prev.": "Ant.",
"Day": "Dia",
"Days": "Dies",
"Money": "Diners",
" points": " punts",
" seconds": " segons",
" time(s)": " vegada(es)",
"Powder": "Pols",
"Slots": "Escurabutxaques",
"Roulette": "Roulette",
"Quiz": "Qüestionari",
"Answer": "Resposta",
"Berry": "Baia",
"No need": "No cal",
"UPPER": "MAJ.",
"lower": "min.",
"Unique tag match": "Combat en parella únic",
"Normal tag match": "Combat en parella normal",
"Variety tag match": "Combat en parella variat",
"Expert tag match": "Combat en parella expert",
"Two styles": "Dos estils",
"Become leader": "Fer-se líder",
"Join group": "Unir-se al grup",

# ---- bike shop / drinks ----
"Bike ¥1,000,000": "Bici ¥1.000.000",
"Fresh Water{CLEAR_TO 0x48}¥200": "Aigua Fresca{CLEAR_TO 0x48}¥200",
"Soda Pop{CLEAR_TO 0x48}¥300": "Refresc{CLEAR_TO 0x48}¥300",
"Lemonade{CLEAR_TO 0x48}¥350": "Llimonada{CLEAR_TO 0x48}¥350",
"Fresh Water": "Aigua Fresca",
"Soda Pop": "Refresc",
"Lemonade": "Llimonada",
"How to ride": "Com muntar",
"How to turn": "Com girar",
"Sandy slopes": "Pendents de sorra",
"Wheelies": "Cavallets",
"Bunny-hops": "Bots de conill",

# ---- coins / game corner ----
"  50 coins    ¥1,000": "  50 fitxes    ¥1.000",
"500 coins  ¥10,000": "500 fitxes  ¥10.000",
"You've got 9,999 coins.": "Ja tens 9.999 fitxes.",
"You've run out of coins.\\nGame over!": "T'has quedat sense fitxes.\\nFi del joc!",
"You don't have three coins.": "No tens tres fitxes.",
"Reel Time\\nHere's your chance to take\\naim and nail marks!\\nReel Time continues for the\\nawarded number of spins.\\nIt all ends on a Big Bonus.": "Temps de Rodets\\nAra pots apuntar i encertar\\nles marques!\\nEl Temps de Rodets dura les\\ntirades que t'hagin donat.\\nS'acaba amb un Gran Premi.",
"jackpot": "premi gros",
"first": "primer",
"second": "segon",
"third": "tercer",
"spicy": "picant",
"dry": "sec",
"sweet": "dolç",
"bitter": "amarg",
"sour": "àcid",

# ---- shards / frontier ----
"Red Shard": "Fragment Vermell",
"Yellow Shard": "Fragment Groc",
"Blue Shard": "Fragment Blau",
"Green Shard": "Fragment Verd",
"Battle Frontier": "Frontera de Combat",
"Ranking hall": "Sala de rànquings",
"Exchange service": "Servei d'intercanvi",
"Rooftop": "Terrat",
"Now on:": "Ara a:",
"Tourney Tree": "Quadre del torneig",
"Ready to start": "A punt de començar",
"Single": "Individual",
"Double": "Doble",
"Multi": "Múltiple",
"Multi-link": "Múltiple per enllaç",
"Battle Bag": "Motxilla de combat",
"Held item": "Objecte portat",
"Held items": "Objectes portats",
"Hold items": "Objectes portats",
"About E-mode": "Sobre el mode E",
"About G-mode": "Sobre el mode G",
"E-mode": "Mode E",
"G-mode": "Mode G",
"Symbols": "Símbols",
"Record": "Registre",
"Battle PTS": "PTS de combat",
"Tower info": "Info de la torre",
"Battle {PKMN}": "{PKMN} de combat",
"Battle Salon": "Saló de combat",
"Battle rules": "Regles de combat",
"Judge: mind": "Jutge: ment",
"Judge: skill": "Jutge: destresa",
"Judge: body": "Jutge: cos",
"Matchup": "Enfrontament",
"Double KO": "KO doble",
"Basic rules": "Regles bàsiques",
"Swap: partner": "Canvi: company",
"Swap: number": "Canvi: número",
"Swap: notes": "Canvi: notes",
"Battle basics": "Bàsics del combat",
"Pokémon nature": "Naturalesa del Pokémon",
"Pokémon moves": "Moviments del Pokémon",
"Underpowered": "Massa feble",
"When in danger": "En cas de perill",
"Pyramid: Pokémon": "Piràmide: Pokémon",
"Pyramid: Trainers": "Piràmide: entrenadors",
"Pyramid: maze": "Piràmide: laberint",
"PokéGear and Bag": "PokéGear i motxilla",
"Pokémon order": "Ordre dels Pokémon",
"Battle Pokémon": "Pokémon de combat",
"Battle Trainers": "Entrenadors de combat",
"99 times +": "99 vegades +",
"1 minute +": "1 minut +",
"Battle Tower": "Torre de Combat",
"Battle Dome": "Cúpula de Combat",
"Battle Palace": "Palau de Combat",
"Battle Factory": "Fàbrica de Combat",
"Battle Arena": "Arena de Combat",
"Battle Pike": "Camí de Combat",
"Battle Pyramid": "Piràmide de Combat",
"Battle Tower Records": "Registres de la Torre de Combat",
"Lv.50 Singles": "Individuals niv.50",
"Lv.50 Doubles": "Dobles niv.50",
"Open Singles": "Individuals oberts",
"Open Doubles": "Dobles oberts",
"Symbols Earned": "Símbols obtinguts",
"Battle Record": "Registre de combats",
"Battle Points": "Punts de Combat",
"Battle Points won": "Punts de Combat guanyats",
"Check Battle Frontier map.": "Consulta el mapa de la Frontera\\nde Combat.",
"Check Trainer Card.": "Consulta la Fitxa d'Entrenador.",
"View recorded battle.": "Mira el combat gravat.",
"Put away the Frontier Pass.": "Guarda el Passi de Frontera.",
"Your current Battle Points.": "Els teus Punts de Combat actuals.",
"Your collected Symbols.": "Els Símbols que has recollit.",
"Battle Tower - Ability Symbol": "Torre de Combat - Símbol d'Aptitud",
"Battle Dome - Tactics Symbol": "Cúpula de Combat - Símbol de Tàctica",
"Battle Palace - Spirits Symbol": "Palau de Combat - Símbol d'Ànim",
"Battle Arena - Guts Symbol": "Arena de Combat - Símbol de Coratge",
"Battle Factory - Knowledge Symbol": "Fàbrica de Combat - Símbol de Saber",
"Battle Pike - Luck Symbol": "Camí de Combat - Símbol de Sort",
"Battle Pyramid - Brave Symbol": "Piràmide de Combat - Símbol de Valor",
"There is no Battle Record.": "No hi ha cap registre de combats.",
"KO opponents and aim for the top!\\nYour ability will be tested.": "Derrota els rivals i arriba al cim!\\nEs posarà a prova la teva aptitud.",
"Keep winning at the tournament!\\nYour tactics will be tested.": "Continua guanyant al torneig!\\nEs posarà a prova la teva tàctica.",
"Watch your Pokémon battle!\\nYour spirit will be tested.": "Mira com combaten els teus Pokémon!\\nEs posarà a prova el teu ànim.",
"Win battles with teamed-up Pokémon!\\nYour guts will be tested.": "Guanya combats amb Pokémon en equip!\\nEs posarà a prova el teu coratge.",
"Aim for victory using rental Pokémon!\\nYour knowledge will be tested.": "Guanya amb Pokémon de lloguer!\\nEs posarà a prova el teu saber.",
"Select one of three paths to battle!\\nYour luck will be tested.": "Tria un de tres camins per combatre!\\nEs posarà a prova la teva sort.",
"Aim for the top with exploration!\\nYour bravery will be tested.": "Arriba al cim explorant!\\nEs posarà a prova el teu valor.",
"Win streak: {STR_VAR_1}": "Ratxa de victòries: {STR_VAR_1}",
"Clear streak: {STR_VAR_1}": "Ratxa de superats: {STR_VAR_1}",
"Championships: {STR_VAR_1}": "Campionats: {STR_VAR_1}",
"Rooms cleared: {STR_VAR_1}": "Sales superades: {STR_VAR_1}",
"Times cleared:{CLEAR 0x05}{STR_VAR_1}": "Vegades superat:{CLEAR 0x05}{STR_VAR_1}",
"KOs in a row: {STR_VAR_1}": "KO seguits: {STR_VAR_1}",
"Times: {STR_VAR_1}": "Vegades: {STR_VAR_1}",
"Floors cleared: {STR_VAR_1}": "Plantes superades: {STR_VAR_1}",
"Win streak: {STR_VAR_2}": "Ratxa de victòries: {STR_VAR_2}",
"Clear streak: {STR_VAR_2}": "Ratxa de superats: {STR_VAR_2}",
"Rooms cleared: {STR_VAR_2}": "Sales superades: {STR_VAR_2}",
"KOs in a row: {STR_VAR_2}": "KO seguits: {STR_VAR_2}",
"Floors cleared: {STR_VAR_2}": "Plantes superades: {STR_VAR_2}",
"Rental/Swap": "Lloguer/Canvi",
"Floor 1": "Planta 1",
"Floor 2": "Planta 2",
"Floor 3": "Planta 3",
"Floor 4": "Planta 4",
"Floor 5": "Planta 5",
"Floor 6": "Planta 6",
"Floor 7": "Planta 7",
"Peak": "Cim",
"Battle Pyramid\\n{STR_VAR_1}": "Piràmide de Combat\\n{STR_VAR_1}",
"Safari Balls\\nStock: {STR_VAR_1}": "Safari Balls\\nExistències: {STR_VAR_1}",
}
