# -*- coding: utf-8 -*-
"""Catalan translation for src/strings.c (part 3: easy chat, link, Mystery
Gift, minigames, trainer-card profiles, prizes, weather, misc)."""
KIND = 'c'
FILES = ['src/strings.c']

T = {
# ---- easy chat ----
"Combine four words or phrases": "Combina quatre paraules o frases",
"and make your profile.": "i crea el teu perfil.",
"Combine six words or phrases": "Combina sis paraules o frases",
"and make a message.": "i crea un missatge.",
"Find words that describe your": "Cerca paraules que descriguin",
"feelings right now.": "com et sents ara mateix.",
"With four phrases,": "Amb quatre frases,",
"Combine nine words or phrases": "Combina nou paraules o frases",
"Change just one word or phrase": "Canvia només una paraula o frase",
"and improve the Bard's song.": "i millora la cançó del Bard.",
"Your profile": "El teu perfil",
"Your feeling at the battle's start": "Com et sents en començar el combat",
"What you say if you win a battle": "Què dius si guanyes un combat",
"What you say if you lose a battle": "Què dius si perds un combat",
"The answer": "La resposta",
"The mail message": "El missatge de la carta",
"The mail salutation": "La salutació de la carta",
"The new song": "La cançó nova",
"Combine two words or phrases": "Combina dues paraules o frases",
"and make a trendy saying.": "i crea una dita de moda.",
"The trendy saying": "La dita de moda",
"is as shown. Okay?": "queda així. Hi estàs d'acord?",
"to teach her a good saying.": "per ensenyar-li una bona dita.",
"Find words which fit": "Cerca paraules que encaixin",
"the Trainer's image.": "amb la imatge de l'entrenador.",
"The image:": "La imatge:",
"Out of the listed choices,": "D'entre les opcions de la llista,",
"select the answer to the quiz!": "tria la resposta del qüestionari!",
"and create a quiz!": "i crea un qüestionari!",
"Pick a word or phrase and": "Tria una paraula o frase i",
"set the quiz answer.": "posa-hi la resposta del qüestionari.",
"The answer:": "La resposta:",
"The quiz:": "El qüestionari:",
"Apprentice's phrase:": "Frase de l'aprenent:",
"Quit editing?": "Vols deixar d'editar?",
"Stop giving the Pokémon mail?": "Vols deixar de donar la carta\\nal Pokémon?",
"and fill out the questionnaire.": "i omple el qüestionari.",
"Let's reply to the interview!": "Contestem l'entrevista!",
"All the text being edited will": "Tot el text que s'està editant",
"be deleted. Is that okay?": "s'esborrarà. Hi estàs d'acord?",
"The edited text will not be saved.": "El text editat no es desarà.",
"Is that okay?": "Hi estàs d'acord?",
"Please enter a phrase or word.": "Escriu una frase o una paraula.",
"The entire text can't be deleted.": "No es pot esborrar tot el text.",
"Only one phrase may be changed.": "Només es pot canviar una frase.",
"The original song will be used.": "Es farà servir la cançó original.",
"That's trendy already!": "Això ja està de moda!",
"Combine two words or phrases.": "Combina dues paraules o frases.",
"Quit giving information?": "Vols deixar de donar informació?",
"Create a quiz!": "Crea un qüestionari!",
"Set the answer!": "Posa-hi la resposta!",
"Cancel the selection?": "Vols cancel·lar la selecció?",
"Profile": "Perfil",
"At the battle's start:": "En començar el combat:",
"Upon winning a battle:": "En guanyar un combat:",
"Upon losing a battle:": "En perdre un combat:",
"The Bard's Song": "La cançó del Bard",
"What's hip and happening?": "Què es porta ara?",
"Interview": "Entrevista",
"Good saying": "Bona dita",
"Fan's question": "Pregunta d'un fan",
"Apprentice's phrase": "Frase de l'aprenent",
"Questionnaire": "Qüestionari",
"You cannot quit here.": "Aquí no pots sortir.",
"This section must be completed.": "Cal completar aquesta secció.",
"{DYNAMIC 0}'s quiz": "Qüestionari de {DYNAMIC 0}",
"Lady": "Senyora",
"After you have read the quiz": "Quan hagis llegit la pregunta",
"question, press the A Button.": "del qüestionari, prem el botó A.",
"The quiz answer is?": "Quina és la resposta?",
"Would you like to quit this quiz": "Vols deixar aquest repte de",
"challenge?": "qüestionari?",
"Is this quiz OK?": "Et va bé aquest qüestionari?",
"Select the answer!": "Tria la resposta!",
"The lyrics can't be deleted.": "La lletra no es pot esborrar.",
"Tell him the words.": "Digues-li les paraules.",
"Greetings": "Salutacions",
"People": "Persones",
"Voices": "Veus",
"Speech": "Parla",
"Endings": "Finals",
"Feelings": "Sentiments",
"Conditions": "Condicions",
"Actions": "Accions",
"Lifestyle": "Estil de vida",
"Hobbies": "Aficions",
"Misc.": "Divers",
"Adjectives": "Adjectius",
"Move 1": "Moviment 1",
"Move 2": "Moviment 2",
"Trendy saying": "Dita de moda",
"Pokémon2": "Pokémon2",
"Your name?": "Com et dius?",
"Box name?": "Nom de la caixa?",
"{STR_VAR_1}'s nickname?": "Sobrenom de {STR_VAR_1}?",

# ---- chat room / link ----
"Quit chatting?": "Vols deixar el xat?",
"Register text where?": "On vols registrar el text?",
"Register text here?": "Vols registrar el text aquí?",
"Input text.": "Escriu el text.",
"{DYNAMIC 0} joined the chat!": "{DYNAMIC 0} s'ha unit al xat!",
"{DYNAMIC 0} left the chat.": "{DYNAMIC 0} ha deixat el xat.",
"Exiting the chat…": "S'està sortint del xat…",
"The leader, {DYNAMIC 0}, has\\nleft, ending the chat.": "El líder, {DYNAMIC 0}, ha marxat\\ni s'ha acabat el xat.",
"The registered text has been changed.\\nIs it okay to save the game?": "El text registrat ha canviat.\\nVols desar la partida?",
"There is already a saved file.\\nIs it okay to overwrite it?": "Ja hi ha una partida desada.\\nLa vols sobreescriure?",
"{DYNAMIC 0} saved the game.": "{DYNAMIC 0} ha desat la partida.",
"If the leader leaves, the chat\\nwill end. Is that okay?": "Si el líder marxa, s'acabarà\\nel xat. Hi estàs d'acord?",
"Hello": "Hola",
"Battle": "Combat",
"Let's": "Va",
"Ok!": "D'acord!",
"Sorry": "Perdó",
"Thank you": "Gràcies",
"Bye-bye!": "Adéu!",
"Communication standby…": "En espera de comunicació…",
"Communication standby…\\nB Button: Cancel": "En espera de comunicació…\\nBotó B: Cancel·lar",
"Communication standby…\\nAwaiting another player to choose.": "En espera de comunicació…\\nEsperant que un altre jugador triï.",
"Communicating…": "S'està comunicant…",
"Communication completed.": "Comunicació acabada.",
"Communication error.": "Error de comunicació.",
"Communication error…": "Error de comunicació…",
"Communication has been canceled.": "S'ha cancel·lat la comunicació.",
"Communication error…\\nPlease check all connections,\\nthen turn the power off and on.": "Error de comunicació…\\nComprova totes les connexions i\\napaga i engega la consola.",
"Move closer to your link partner(s).\\nAvoid obstacles between partners.": "Acosta't als teus companys d'enllaç.\\nEvita obstacles entre vosaltres.",
"Link standby…\\n… … B Button: Cancel": "Enllaç en espera…\\n… … Botó B: Cancel·lar",
"Press the A Button to load event.\\n… … B Button: Cancel": "Prem el botó A per carregar el fet.\\n… … Botó B: Cancel·lar",
"Loading event…": "S'està carregant el fet…",
"Don't remove the Game Link cable.\\nDon't turn off the power.": "No treguis el cable d'enllaç.\\nNo apaguis la consola.",
"The event was safely loaded.": "El fet s'ha carregat correctament.",
"Loading error.\\nEnding session.": "Error de càrrega.\\nS'acaba la sessió.",
"Waiting for the other Trainer to\\nfinish reading your Trainer Card.": "Esperant que l'altre entrenador\\nacabi de llegir la teva fitxa.",
"The battle was refused.{PAUSE 60}": "S'ha rebutjat el combat.{PAUSE 60}",
"Refused the battle.{PAUSE 60}": "Has rebutjat el combat.{PAUSE 60}",
"Trade Center": "Centre d'Intercanvi",
"Colosseum": "Colisseu",
"Record Corner": "Racó de Registres",
"Berry Crush": "Trituradora de Baies",
"Pokémon Jump": "Salt Pokémon",
"Dodrio Berry-Picking": "Recollida de Baies amb Dodrio",
"Link battles": "Combats per enllaç",
"Link Cable battles": "Combats per cable d'enllaç",
"Pokémon trades": "Intercanvis de Pokémon",
"Union trades & battles": "Intercanvis i combats a la Unió",
"{POKEBLOCK}s W/Friends": "{POKEBLOCK} amb amics",
"Mixing records…": "S'estan barrejant els registres…",
"Record mixing completed.\\nThank you for waiting.": "Barreja de registres acabada.\\nGràcies per esperar.",
"Wireless Communication Status": "Estat de la comunicació sense fils",
"People trading:": "Persones intercanviant:",
"People battling:": "Persones combatent:",
"People in the Union Room:": "Persones a la Sala d'Unió:",
"People communicating:": "Persones comunicant-se:",
"{DYNAMIC 0} players": "{DYNAMIC 0} jugadors",
"{DYNAMIC 1} players": "{DYNAMIC 1} jugadors",
"{DYNAMIC 2} players": "{DYNAMIC 2} jugadors",
"{DYNAMIC 3} players": "{DYNAMIC 3} jugadors",
"Wireless Communication": "Comunicació sense fils",
"{STR_VAR_1} Players": "{STR_VAR_1} jugadors",

# ---- mystery gift ----
"Wonder Cards": "Cartes Prodigi",
"Wonder News": "Notícies Prodigi",
"Receive": "Rebre",
"Send": "Enviar",
"A variety of events will be imported\\nover Wireless Communication.": "S'importaran diversos fets per\\ncomunicació sense fils.",
"Read the Wonder Cards in your\\npossession.": "Llegeix les Cartes Prodigi que\\ntens.",
"Read the News that arrived.": "Llegeix les notícies que han arribat.",
"Return to the title screen.": "Torna a la pantalla de títol.",
"You don't have a Wonder Card,\\nso a new Card will be input.": "No tens cap Carta Prodigi, així\\nque s'introduirà una de nova.",
"You don't have any Wonder News,\\nso new News will be input.": "No tens cap Notícia Prodigi, així\\nque s'introduirà una de nova.",
"Where should the Wonder Card\\nbe accessed?": "D'on vols obtenir la Carta\\nProdigi?",
"Where should the Wonder News\\nbe accessed?": "D'on vols obtenir la Notícia\\nProdigi?",
"Throw away the Wonder Card\\nand input a new Card?": "Vols llençar la Carta Prodigi\\ni introduir-ne una de nova?",
"You haven't received the Card's gift\\nyet. Input a new Card anyway?": "Encara no has rebut el regal de la\\ncarta. Vols introduir-ne una de nova?",
"A Wonder Card has been received\\nfrom {STR_VAR_1}.": "Has rebut una Carta Prodigi\\nde {STR_VAR_1}.",
"A Wonder News item has been\\nreceived from {STR_VAR_1}.": "Has rebut una Notícia Prodigi\\nde {STR_VAR_1}.",
"A new Wonder Card has been\\nreceived.": "Has rebut una Carta Prodigi\\nnova.",
"A new Wonder News item has been\\nreceived.": "Has rebut una Notícia Prodigi\\nnova.",
"A new Stamp has been received.": "Has rebut un Segell nou.",
"A new Trainer has arrived.": "Ha arribat un entrenador nou.",
"You already had that\\nWonder Card.": "Ja tenies aquesta\\nCarta Prodigi.",
"You already had that\\nWonder News item.": "Ja tenies aquesta\\nNotícia Prodigi.",
"You already had that\\nStamp.": "Ja tenies aquest\\nSegell.",
"There's no more room for adding\\nStamps.": "Ja no hi ha lloc per a més\\nSegells.",
"Your record has been uploaded via\\nWireless Communication.": "El teu registre s'ha enviat per\\ncomunicació sense fils.",
"You can't accept a Wonder Card\\nfrom this Trainer.": "No pots acceptar una Carta Prodigi\\nd'aquest entrenador.",
"You can't accept Wonder News\\nfrom this Trainer.": "No pots acceptar Notícies Prodigi\\nd'aquest entrenador.",
"Nothing was sent over…": "No s'ha enviat res…",
"What would you like to do\\nwith the Wonder Cards?": "Què vols fer amb les\\nCartes Prodigi?",
"What would you like to do\\nwith the Wonder News?": "Què vols fer amb les\\nNotícies Prodigi?",
"Sending your Wonder Card…": "S'envia la teva Carta Prodigi…",
"Sending your Wonder News item…": "S'envia la teva Notícia Prodigi…",
"Your Wonder Card has been sent\\nto {STR_VAR_1}.": "La teva Carta Prodigi s'ha enviat\\na {STR_VAR_1}.",
"Your Wonder News item has been\\nsent to {STR_VAR_1}.": "La teva Notícia Prodigi s'ha\\nenviat a {STR_VAR_1}.",
"A Stamp has been sent to {STR_VAR_1}.": "S'ha enviat un Segell a {STR_VAR_1}.",
"A Gift has been sent to {STR_VAR_1}.": "S'ha enviat un Regal a {STR_VAR_1}.",
"The other Trainer has the same\\nWonder Card already.": "L'altre entrenador ja té la\\nmateixa Carta Prodigi.",
"The other Trainer has the same\\nWonder News already.": "L'altre entrenador ja té la\\nmateixa Notícia Prodigi.",
"The other Trainer has the same\\nStamp already.": "L'altre entrenador ja té el\\nmateix Segell.",
"The other Trainer canceled\\ncommunication.": "L'altre entrenador ha cancel·lat\\nla comunicació.",
"You can't send a Mystery Gift to\\nthis Trainer.": "No pots enviar un Regal Misteriós\\na aquest entrenador.",
"If you throw away the Card,\\nits event won't happen. Okay?": "Si llences la carta, el seu fet\\nno passarà. Hi estàs d'acord?",
"Is it okay to discard this\\nNews item?": "Vols descartar aquesta\\nnotícia?",
"You haven't received the\\nGift. Is it okay to discard?": "Encara no has rebut el regal.\\nEl vols descartar?",
"The Wonder Card was thrown away.": "S'ha llençat la Carta Prodigi.",
"The Wonder News was thrown away.": "S'ha llençat la Notícia Prodigi.",

# ---- minigames ----
"Are you ready to Berry-Crush?\\nPlease pick a Berry for use.\\p": "Preparat per triturar baies?\\nTria una baia per fer servir.\\p",
"Please wait while each member\\nchooses a Berry.": "Espera mentre cada membre\\ntria una baia.",
"{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}You ended up with {STR_VAR_1} units of\\nsilky-smooth Berry Powder.{RESUME_MUSIC}\\pYour total amount of Berry Powder\\nis {STR_VAR_2}.\\p": "{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}Has obtingut {STR_VAR_1} unitats de\\nPols de Baia ben fina.{RESUME_MUSIC}\\pEn total tens {STR_VAR_2} de\\nPols de Baia.\\p",
"Recording your game results in the\\nsave file.\\lPlease wait.": "S'estan desant els resultats a la\\npartida.\\lEspera un moment.",
"Want to play Berry Crush again?": "Vols tornar a jugar a triturar baies?",
"You have no Berries.\\nThe game will be canceled.": "No tens baies.\\nEs cancel·larà el joc.",
"A member dropped out.\\nThe game will be canceled.": "Un membre ha marxat.\\nEs cancel·larà el joc.",
"Time's up.\\pGood Berry Powder could not be\\nmade…\\p": "S'ha acabat el temps.\\pNo s'ha pogut fer bona Pols de\\nBaia…\\p",
"{STR_VAR_1} Berry": "Baia {STR_VAR_1}",
"Time:": "Temps:",
"Pressing Speed:": "Velocitat de premuda:",
"Silkiness:": "Finor:",
" min. ": " min. ",
" sec.": " s",
" Times/sec.": " vegades/s",
"No. of Presses Rankings": "Rànquing de premudes",
"Crushing Results": "Resultats de la trituració",
"Neatness Rankings": "Rànquing de netedat",
"Cooperative Rankings": "Rànquing de cooperació",
"Pressing-Power Rankings": "Rànquing de força de premuda",
"Pressing-Speed Rankings": "Rànquing de velocitat de premuda",
"Dodrio Berry-Picking records": "Registres de recollida amb Dodrio",
"Berries picked:": "Baies recollides:",
"Best score:": "Millor puntuació:",
"Berries picked in a row with\\nfive players:": "Baies recollides seguides amb\\ncinc jugadors:",
"Announcing Berry-Picking results!": "Es proclamen els resultats de la\\nrecollida de baies!",
"Announcing rankings!": "Es proclamen els rànquings!",
"Announcing prizes!": "Es proclamen els premis!",
"The first-place winner gets\\nthis {DYNAMIC 0}!": "El guanyador del primer lloc rep\\naquest {DYNAMIC 0}!",
"You can't hold any more!": "Ja no en pots portar més!",
"It filled its storage space.": "S'ha omplert l'espai d'emmagatzematge.",
"Want to play again?": "Vols tornar a jugar?",
"Somebody dropped out.\\nThe link will be canceled.": "Algú ha marxat.\\nEs cancel·larà l'enllaç.",
"Pokémon Jump records": "Registres de Salt Pokémon",
"Jumps in a row:": "Salts seguits:",
"Excellents in a row:": "Excel·lents seguits:",
"Awesome score! You've\\nwon {DYNAMIC 1} {DYNAMIC 0}!": "Quina puntuació! Has\\nguanyat {DYNAMIC 1} {DYNAMIC 0}!",
"1st": "1r",
"2nd": "2n",
"3rd": "3r",
"4th": "4t",
"Berry Blender\\nmaximum speed record!": "Batedora de Baies\\nrècord de velocitat màxima!",
"2 Players\\n3 Players\\n4 Players": "2 jugadors\\n3 jugadors\\n4 jugadors",
"PEEKABOO!": "CUCUT!",
"Time board": "Marcador de temps",
"Time cleared ": "Temps aconseguit ",
"{STR_VAR_1} min. {STR_VAR_2}.{STR_VAR_3} sec.": "{STR_VAR_1} min {STR_VAR_2},{STR_VAR_3} s",

# ---- results screens ----
"{PLAYER}'s Single Battle Room Results": "Resultats de {PLAYER} a la Sala\\nde Combat Individual",
"{PLAYER}'s Double Battle Room Results": "Resultats de {PLAYER} a la Sala\\nde Combat Doble",
"{PLAYER}'s Multi Battle Room Results": "Resultats de {PLAYER} a la Sala\\nde Combat Múltiple",
"{PLAYER}'s Link Multi Battle Room Results": "Resultats de {PLAYER} a la Sala de\\nCombat Múltiple per Enllaç",
"{PLAYER}'s Single Battle Tourney Results": "Resultats de {PLAYER} al Torneig\\nde Combat Individual",
"{PLAYER}'s Double Battle Tourney Results": "Resultats de {PLAYER} al Torneig\\nde Combat Doble",
"{PLAYER}'s Single Battle Hall Results": "Resultats de {PLAYER} a la Sala\\nde Combat Individual",
"{PLAYER}'s Double Battle Hall Results": "Resultats de {PLAYER} a la Sala\\nde Combat Doble",
"{PLAYER}'s Battle Choice Results": "Resultats de Tria de Combat\\nde {PLAYER}",
"{PLAYER}'s Set KO Tourney Results": "Resultats del Torneig de KO\\nde {PLAYER}",
"{PLAYER}'s Battle Swap Single Results": "Resultats de Canvi de Combat\\nIndividual de {PLAYER}",
"{PLAYER}'s Battle Swap Double Results": "Resultats de Canvi de Combat\\nDoble de {PLAYER}",
"{PLAYER}'s Battle Quest Results": "Resultats de la Cerca de Combat\\nde {PLAYER}",
"{PLAYER}'s battle results": "Resultats de combat de {PLAYER}",
"Total record W:{STR_VAR_1} L:{STR_VAR_2} D:{STR_VAR_3}": "Registre total V:{STR_VAR_1} D:{STR_VAR_2} E:{STR_VAR_3}",
"{CLEAR_TO 0x53}Win{CLEAR_TO 0x80}Lose{CLEAR_TO 0xB0}Draw": "{CLEAR_TO 0x53}Vict.{CLEAR_TO 0x80}Derr.{CLEAR_TO 0xB0}Emp.",
"{STR_VAR_1} Single": "{STR_VAR_1} individual",
"{STR_VAR_1} Double": "{STR_VAR_1} doble",
"{STR_VAR_1} Multi": "{STR_VAR_1} múltiple",
"{STR_VAR_1} Link": "{STR_VAR_1} per enllaç",
"{STR_VAR_1}P Link": "Enllaç de {STR_VAR_1}J",

# ---- factory / swap ----
"Select the first Pokémon.": "Tria el primer Pokémon.",
"Select the second Pokémon.": "Tria el segon Pokémon.",
"Select the third Pokémon.": "Tria el tercer Pokémon.",
"Rent": "Llogar",
"Are these three Pokémon OK?": "Et van bé aquests tres Pokémon?",
"Can't select same {PKMN}.": "No pots triar el mateix {PKMN}.",
"Pokémon swap": "Canvi de Pokémon",
"Select Pokémon to swap.": "Tria el Pokémon per canviar.",
"Select Pokémon to accept.": "Tria el Pokémon que acceptes.",
"Swap": "Canviar",
"Rechoose": "Tornar a triar",
"Quit swapping?": "Vols deixar de canviar?",
"{PKMN} for swap": "{PKMN} per canviar",
"Accept": "Acceptar",
"Accept this Pokémon?": "Acceptes aquest Pokémon?",
"Same {PKMN} in party already.": "Ja tens el mateix {PKMN} a l'equip.",

# ---- fishing / daycare ----
"Oh! A bite!": "Oh! Ha picat!",
"A Pokémon's on the hook!{PAUSE_UNTIL_PRESS}": "Hi ha un Pokémon a l'ham!{PAUSE_UNTIL_PRESS}",
"Not even a nibble…{PAUSE_UNTIL_PRESS}": "No ha picat gens…{PAUSE_UNTIL_PRESS}",
"It got away…{PAUSE_UNTIL_PRESS}": "S'ha escapat…{PAUSE_UNTIL_PRESS}",
"{STR_VAR_2} will be\\nsent to {STR_VAR_1}.": "{STR_VAR_2} s'enviarà\\na {STR_VAR_1}.",
"Bye-bye, {STR_VAR_2}!": "Adéu, {STR_VAR_2}!",
"{STR_VAR_1} sent over {STR_VAR_3}.": "{STR_VAR_1} t'ha enviat {STR_VAR_3}.",
"Take good care of {STR_VAR_3}!": "Cuida bé {STR_VAR_3}!",
"The two seem to get along\\nvery well.": "Sembla que es porten\\nmolt bé.",
"The two seem to get along.": "Sembla que es porten bé.",
"The two don't seem to like\\neach other much.": "Sembla que no s'agraden\\ngaire.",
"The two prefer to play with other\\nPokémon than each other.": "Els dos prefereixen jugar amb\\naltres Pokémon que entre ells.",
"{STR_VAR_1} fainted…\\p\\n": "{STR_VAR_1} s'ha debilitat…\\p\\n",

# ---- trainer card profiles ----
"{PKMN} Prof.": "Prof. {PKMN}",
"Prof. Oak": "Prof. Oak",
"I prefer studying.": "Prefereixo estudiar.",
"I respect all Pokémon.": "Respecto tots els Pokémon.",
"Completing the PokéDex": "Completar el Pokédex",
"is my lifelong dream!": "és el somni de la meva vida!",
"Calm & kind": "Tranquil i amable",
"Prof.'s Aide": "Ajudant del Prof.",
"Rude neighbor": "Veí impertinent",
"I'm in the mood for battles.": "Tinc ganes de combatre.",
"I'll use any Pokémon to win!": "Faré servir qualsevol Pokémon\\nper guanyar!",
"If I see a strong trainer,": "Si veig un entrenador fort,",
"I'm gonna want to fight!": "em vindran ganes de lluitar!",
"Gym Guy": "Noi del gimnàs",
"Show me a good battle!": "Ensenya'm un bon combat!",
"I don't train Pokémon.": "Jo no entreno Pokémon.",
"I'm searching Kanto for the": "Recorro Kanto buscant els",
"strongest trainers!": "entrenadors més forts!",
"Inspector": "Inspector",
"I'm hunting Team Rocket!": "Vaig a la caça de l'Equip Rocket!",
"I like loyal Pokémon.": "M'agraden els Pokémon lleials.",
"I won't let Team Rocket": "No deixaré que l'Equip Rocket",
"escape justice!": "s'escapi de la justícia!",
"PokéManiac": "PokéManíac",
"I'm a true Pokémaniac!": "Sóc un autèntic Pokémaníac!",
"I turned into a Pokémon.": "Em vaig convertir en un Pokémon.",
"I invent things to help": "Invento coses per ajudar",
"both Pokémon and People!": "els Pokémon i les persones!",
"Attack the weak points!": "Ataca els punts febles!",
"Ultimate Steel Pokémon.": "El Pokémon d'Acer definitiu.",
"I'd climb even waterfalls": "Escalaria fins i tot cascades",
"to find a rare stone!": "per trobar una pedra rara!",
"I'm the strongest and most": "Sóc el més fort i el més",
"energetic after all!": "enèrgic de tots!",

# ---- weather names ----
"No weather": "Sense clima",
"Sunny": "Assolellat",
"Sunny2": "Assolellat2",
"Sunny3": "Assolellat3",
"Rain": "Pluja",
"Lightning": "Llamps",
"Fog": "Boira",
"Fog2": "Boira2",
"Volcano ash": "Cendra volcànica",
"Sandstorm": "Tempesta de sorra",
"Cloudy": "Ennuvolat",
"Heavy rain": "Pluja intensa",
"Seafloor2": "Fons marí2",

# ---- clock ----
"Reset RTC?\\nA: Confirm, B: Cancel": "Reiniciar el rellotge?\\nA: Confirmar, B: Cancel·lar",
"Present time in game": "Hora actual del joc",
"Previous time in game": "Hora anterior del joc",
"Please reset the time.": "Reinicia l'hora, si et plau.",
"The clock has been reset.\\nData will be saved. Please wait.": "S'ha reiniciat el rellotge.\\nEs desaran les dades. Espera.",
"There is no save file, so the time\\ncan't be set.": "No hi ha partida desada, així que\\nno es pot ajustar l'hora.",
"The in-game clock adjustment system\\nis now useable.": "Ja pots fer servir el sistema\\nd'ajust del rellotge del joc.",
"Is this the correct time?": "És aquesta l'hora correcta?",
"Game time": "Temps de joc",
"RTC time": "Hora del rellotge",
"Updated time": "Hora actualitzada",

# ---- places / misc ----
"Pokémon League": "Lliga Pokémon",
"Pokémon Center": "Centre Pokémon",
"Ferry": "Transbordador",
"Secret Base": "Base Secreta",
"Hideout": "Amagatall",
"Bill's PC": "PC del Bill",
"Del. all": "Esb. tot",
"Name: ": "Nom: ",
"From ": "De ",
"Rude neighbor ": "Veí impertinent ",
"0 pts": "0 pts",
"10 pts": "10 pts",
"20 pts": "20 pts",
"30 pts": "30 pts",
"40 pts": "40 pts",
"50 pts": "50 pts",
"60 pts": "60 pts",
"70 pts": "70 pts",
"80 pts": "80 pts",
"90 pts": "90 pts",
"100 pts": "100 pts",
"Don't remember": "No ho recordo",
"Big guy": "Campió",
"Big girl": "Campiona",
"son": "fill",
"daughter": "filla",
"PLAYER: {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\\n\\nThis document certifies\\nthat you have successfully\\ncompleted your Pokédex.\\n\\n{COLOR RED}{SHADOW LIGHT_RED}RetroGBA - PokéClassic": "JUGADOR: {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\\n\\nAquest document certifica\\nque has completat\\ncorrectament el teu Pokédex.\\n\\n{COLOR RED}{SHADOW LIGHT_RED}RetroGBA - PokéClassic",

# ---- prize / mart lists (names kept, price wording only) ----
"Treecko Doll 1,000 Coins": "Nina Treecko 1.000 fitxes",
"Torchic Doll 1,000 Coins": "Nina Torchic 1.000 fitxes",
"Mudkip Doll   1,000 Coins": "Nina Mudkip   1.000 fitxes",
"Meowth     500 Coins": "Meowth     500 fitxes",
"Clefairy   500 Coins": "Clefairy   500 fitxes",
"Jigglypuff 500 Coins": "Jigglypuff 500 fitxes",
"Ditto      750 Coins": "Ditto      750 fitxes",
"Pikachu    750 Coins": "Pikachu    750 fitxes",
"Rhydon    1,500 Coins": "Rhydon    1.500 fitxes",
"Lapras    1,500 Coins": "Lapras    1.500 fitxes",
"Snorlax   1,500 Coins": "Snorlax   1.500 fitxes",
"Venusaur  3,000 Coins": "Venusaur  3.000 fitxes",
"Charizard 3,000 Coins": "Charizard 3.000 fitxes",
"Blastoise 3,000 Coins": "Blastoise 3.000 fitxes",
"Poké Ball 150 Coins": "Poké Ball 150 fitxes",
"Water     250 Coins": "Aigua     250 fitxes",
"Fire      250 Coins": "Foc       250 fitxes",
"Grass     250 Coins": "Herba     250 fitxes",
"Pika      350 Coins": "Pika      350 fitxes",
"TM32{CLEAR_TO 0x48}1,500 Coins": "MT32{CLEAR_TO 0x48}1.500 fitxes",
"TM29{CLEAR_TO 0x48}3,500 Coins": "MT29{CLEAR_TO 0x48}3.500 fitxes",
"TM35{CLEAR_TO 0x48}4,000 Coins": "MT35{CLEAR_TO 0x48}4.000 fitxes",
"TM24{CLEAR_TO 0x48}4,000 Coins": "MT24{CLEAR_TO 0x48}4.000 fitxes",
"TM13{CLEAR_TO 0x48}4,000 Coins": "MT13{CLEAR_TO 0x48}4.000 fitxes",
"Red Tent": "Tenda vermella",
"Blue Tent": "Tenda blava",
}
