CinnabarIsland_Lab_Entrance_MapScripts::
	.byte 0

CinnabarIsland_PokemonLab_Entrance_EventScript_Scientist::
    msgbox CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively, MSGBOX_NPC
    end

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "Estudiem els Pokémon extensament\n"
    .string "cada dia.\p"
    .string "La gent sovint ens porta Pokémon\n"
    .string "rars per examinar.$"

CinnabarIsland_PokemonLab_Entrance_EventScript_DrFujiPhoto::
    msgbox CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji, MSGBOX_SIGN
    end

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "Una foto del fundador del Lab…\n"
    .string "Dr. Fuji?!$"

CinnabarIsland_PokemonLab_Entrance_EventScript_MeetingRoomSign::
    msgbox CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign, MSGBOX_SIGN
    end

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "Laboratori Pokémon\n"
    .string "Sala de Reunions$"

CinnabarIsland_PokemonLab_Entrance_EventScript_RAndDRoomSign::
    msgbox CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign, MSGBOX_SIGN
    end

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "Laboratori Pokémon\n"
    .string "Sala d'I+D$"

CinnabarIsland_PokemonLab_Entrance_EventScript_TestingRoomSign::
    msgbox CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign, MSGBOX_SIGN
    end

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "Laboratori Pokémon\n"
    .string "Sala de Proves$"
