SSAnne_2F_Room3_MapScripts::
	.byte 0

SSAnne_2F_Room3_EventScript_Gentleman::
	msgbox SSAnne_2F_Room3_Text_SeenMonsFerryPeople, MSGBOX_NPC
	end

SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
    .string "Ah, sí, he vist Pokémon que\n"
    .string "transporten gent per l'aigua!$"

SSAnne_2F_Room3_EventScript_OldMan::
	msgbox SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown, MSGBOX_NPC
	end

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
    .string "Els arbres petits es poden tallar\n"
    .string "amb el moviment tall.\p"
    .string "Però recorda-ho!\n"
    .string "Tall és una tècnica MO.\p"
    .string "Un cop apresa, no és tan fàcil\n"
    .string "d'oblidar.$"
