CeladonCity_House1_MapScripts::
	.byte 0

CeladonCity_House1_EventScript_RocketChief::
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
	end

CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "Hehehe!\p"
    .string "Les slots ens omplen de pasta,\n"
    .string "a lo gran!$"

CeladonCity_House1_EventScript_Rocket1::
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
	end

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "Cap!\p"
    .string "Avui hem enviat dos mil\n"
    .string "Ninots Pokémon més com a premis\l"
    .string "de les slots!\p"
    .string "I també estem buscant compradors\n"
    .string "pels Pokémon que hem segrestat.$"

CeladonCity_House1_EventScript_Rocket2::
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
	end

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "No toquis el pòster de la Sala\n"
    .string "de Jocs!\p"
    .string "No hi ha cap interruptor secret\n"
    .string "al darrere!$"

CeladonCity_House1_EventScript_PoliceChief::
    msgbox CeladonCity_House1_Text_BustedTheseRockets, MSGBOX_NPC
    end

CeladonCity_House1_Text_BustedTheseRockets::
    .string "Per fi hem enxampat els líders\n"
    .string "d'aquesta operació.$"

CeladonCity_House1_EventScript_Police1::
    msgbox CeladonCity_House1_Text_DontStepOnEvidence, MSGBOX_NPC
    end

CeladonCity_House1_Text_DontStepOnEvidence::
    .string "Ei! Vigila, nano!\n"
    .string "Estem recollint proves.$"

CeladonCity_House1_EventScript_Police2::
    msgbox CeladonCity_House1_Text_WhoDoesThat, MSGBOX_NPC
    end

CeladonCity_House1_Text_WhoDoesThat::
    .string "Segrestar i vendre Pokémon?\n"
    .string "Quin tipus de delinqüent fa això!$"
