# -*- coding: utf-8 -*-
"""Second pass: ability descriptions still over the 144px box."""
KIND = 'c'
FILES = ['src/data/text/abilities.h']
T = {
"Si el toquen, baixa la Vel. general.": "Si el toquen, baixa la Vel.",
"Si el toca, el rival cau en 3 torns.": "El rival cau en 3 torns.",
"Aguanta un cop. La neu el renova.": "Aguanta un cop amb neu.",
"Protegeix dels mov. de prioritat.": "Protegeix de la prioritat.",
"Reflecteix les baixades d'estad.": "Reflecteix les baixades.",
"Ajusta la potència al seu favor.": "Ajusta la potència.",
"Les estad. canvien si el toquen.": "Canvia estad. si el toquen.",
"Recupera una mica de PS si plou.": "Recupera PS si plou.",
"El contacte passa la protecció.": "Passa la protecció.",
"Canvia de tipus segons el camp.": "Pren el tipus del camp.",
"Afavoreix els efectes afegits.": "Puja els efectes afegits.",
"Només el toca el “molt eficaç”.": "Només rep el molt eficaç.",
"Les estad. canvien a poc a poc.": "Canvia estad. a poc a poc.",
"Els records li canvien el tipus.": "El record li dona el tipus.",
"Canvia habilitats en contacte.": "Intercanvia en contacte.",
"Actuar l'últim puja la potència.": "Anar últim dona potència.",
"Els mov. passen les habilitats.": "Ignora les habilitats.",
"Treu els canvis d'estat aliats.": "Neteja els estats aliats.",
"Protegeix els de tipus Planta.": "Protegeix els de Planta.",
"Els cops Sinistre pugen l'Atac.": "Cops Sinistre pugen l'Atac.",
"Els cops múltiples fan 5 cops.": "Els cops múltiples fan 5.",
"Fa crítics si el rival té verí.": "Crítics si el rival té verí.",
"Canvia precisió per potència.": "Precisió per potència.",
"Canvia al tipus del mov. rival.": "Pren el tipus del rival.",
"Protegeix del foc i cremades.": "Aguanta foc i cremades.",
"Canvia efectes per potència.": "Efectes per potència.",
"Canvia al tipus del mov. usat.": "Pren el tipus del mov.",
"No el toquen els atacs Terra.": "No el toquen atacs Terra.",
"Anul·la els efectes del clima.": "Anul·la el clima.",
"Puja els mov. d'Acer de l'aliat.": "Puja els mov. Acer aliats.",
"Puja els atacs del seu tipus.": "Puja atacs del seu tipus.",
"Puja la Defensa si el toquen.": "Puja Defensa si el toquen.",
"Inverteix els canvis d'estad.": "Inverteix els canvis.",
"Es cura en sortir del combat.": "Es cura en sortir.",
"Amb PS plens, meitat de dany.": "PS plens: meitat de dany.",
"La closca es trenca a mig PS.": "Closca trencada a mig PS.",
"Fereix els Pokémon adormits.": "Fereix els adormits.",
"Menja les baies abans d'hora.": "Menja les baies aviat.",
"Evita el robatori d'objectes.": "Evita robatoris.",
"Els mov. passen a ser Normal.": "Els mov. es fan Normal.",
"Anul·la totes les habilitats.": "Anul·la les habilitats.",
"Si el toquen, escup la presa.": "Si el toquen, escup presa.",
"Només el fereixen els atacs.": "Només el fereix un atac.",
"Només actua cada dos torns.": "Actua cada dos torns.",
"Bloqueja els estats amb sol.": "Bloqueja estats amb sol.",
"Pot reciclar una baia usada.": "Pot reciclar una baia.",
"Les cèl·lules l'ajuden si cau.": "Les cèl·lules l'ajuden.",
"Es reforça si el toca el foc.": "Es reforça amb el foc.",
"Els KO pugen la millor estad.": "Els KO pugen la millor.",
}
