# -*- coding: utf-8 -*-
"""Shorten Catalan ability descriptions to fit the 144px summary-screen box.
Abbreviations used consistently: mov. = moviment(s), estad. = estadistiques,
Vel. = Velocitat, At./Def. Esp. = special stats."""
KIND = 'c'
FILES = ['src/data/text/abilities.h']

T = {
"Reflecteix les baixades d'estadístiques.": "Reflecteix les baixades d'estad.",
"Les estadístiques canvien si el toquen.": "Les estad. canvien si el toquen.",
"Aguanta un cop. La calamarsa el renova.": "Aguanta un cop. La neu el renova.",
"Les estadístiques canvien a poc a poc.": "Les estad. canvien a poc a poc.",
"Protegeix dels moviments de prioritat.": "Protegeix dels mov. de prioritat.",
"Reforça els moviments d'Acer de l'aliat.": "Puja els mov. d'Acer de l'aliat.",
"Inverteix els canvis d'estadístiques.": "Inverteix els canvis d'estad.",
"Reforça els moviments de mossegada.": "Puja els mov. de mossegada.",
"Redueix el dany especial a la meitat.": "Meitat de dany especial.",
"Els moviments passen les habilitats.": "Els mov. passen les habilitats.",
"Perdre estadístiques puja l'At. Esp.": "Perdre estad. puja l'At. Esp.",
"Fa que tots els moviments encertin.": "Tots els mov. encerten.",
"Els moviments Normal passen a Fada.": "Mov. Normal passen a Fada.",
"Reforça els moviments de contacte.": "Puja els mov. de contacte.",
"Els moviments de so passen a Aigua.": "Mov. de so passen a Aigua.",
"Els cops múltiples encerten 5 cops.": "Els cops múltiples fan 5 cops.",
"Reforça els moviments de retrocés.": "Puja els mov. de retrocés.",
"Té canvis d'estadístiques bruscos.": "Té canvis d'estad. bruscos.",
"Ignora els canvis d'estadístiques.": "Ignora els canvis d'estad.",
"Els KO pugen la millor estadística.": "Els KO pugen la millor estad.",
"Amb PS plens rep la meitat de dany.": "Amb PS plens, meitat de dany.",
"Només el toquen els “molt eficaç”.": "Només el toca el “molt eficaç”.",
"Gastar l'objecte puja la Velocitat.": "Gastar l'objecte puja la Vel.",
"Els moviments passen a ser Normal.": "Els mov. passen a ser Normal.",
"Bescanvia habilitats en contacte.": "Canvia habilitats en contacte.",
"Recupera una mica de PS amb pluja.": "Recupera una mica de PS si plou.",
"Les cèl·lules l'ajuden si s'afebleix.": "Les cèl·lules l'ajuden si cau.",
"Es transforma amb la meitat de PS.": "Es transforma a mig PS.",
"Els moviments Normal passen a Gel.": "Mov. Normal passen a Gel.",
"Canvia al tipus del moviment rival.": "Canvia al tipus del mov. rival.",
"Si el toquen, baixa la Vel. de tots.": "Si el toquen, baixa la Vel. general.",
"Es reforça amb tempesta de sorra.": "Es reforça amb tempesta.",
"Canvia al tipus del moviment usat.": "Canvia al tipus del mov. usat.",
"Actuar l'últim reforça la potència.": "Actuar l'últim puja la potència.",
"Detecta els moviments perillosos.": "Detecta els mov. perillosos.",
"Si el toca, el rival cau en 3 torns.": "Si el toca, el rival cau en 3 torns.",
"Puja la Velocitat si té problemes.": "Puja la Vel. si té problemes.",
"Perdre estadístiques puja l'Atac.": "Perdre estad. puja l'Atac.",
"Reflecteix els moviments d'estat.": "Reflecteix els mov. d'estat.",
"Els moviments encerten dos cops.": "Els mov. encerten dos cops.",
"Els moviments Volador van primer.": "Els mov. Volador van primer.",
"Foc o Aigua li pugen la Velocitat.": "Foc o Aigua li pugen la Vel.",
"Els moviments de cura van primer.": "Els mov. de cura van primer.",
"Protegeix del foc i les cremades.": "Protegeix del foc i cremades.",
"Fa crítics als rivals enverinats.": "Fa crítics si el rival té verí.",
"Treu els canvis d'estat de l'aliat.": "Treu els canvis d'estat aliats.",
"Pot evitar els problemes d'estat.": "Pot evitar els mals d'estat.",
"Els rivals no poden menjar baies.": "Els rivals no mengen baies.",
"Els moviments d'estat van primer.": "Els mov. d'estat van primer.",
"Pot tocar els Pokémon Fantasma.": "Pot tocar els Fantasma.",
"Reforça els atacs del seu tipus.": "Puja els atacs del seu tipus.",
"Puja la Velocitat amb calamarsa.": "Puja la Vel. amb calamarsa.",
"Canvia al tipus de la seva Placa.": "Canvia al tipus de la Placa.",
"Reforça els moviments de l'aliat.": "Puja els mov. de l'aliat.",
"Puja la Defensa si té problemes.": "Puja la Defensa si té mals.",
"L'electricitat puja la Velocitat.": "L'electricitat puja la Vel.",
"Ajusta la potència al seu favor.": "Ajusta la potència al seu favor.",
"Impedeix perdre estadístiques.": "Evita perdre estad.",
"Impedeix el robatori d'objectes.": "Evita el robatori d'objectes.",
"Reforça els moviments Sinistre.": "Puja els mov. Sinistre.",
"Reforça els moviments Elèctric.": "Puja els mov. Elèctric.",
"Puja la Velocitat amb tempesta.": "Puja la Vel. amb tempesta.",
"Passa el seu objecte a un aliat.": "Passa l'objecte a un aliat.",
"Canvia de forma després d'un KO.": "Canvia de forma amb un KO.",
"Reforça els moviments Insecte.": "Puja els mov. Insecte.",
"Encomana els problemes d'estat.": "Encomana els mals d'estat.",
"Crea una tempesta si el toquen.": "Crea tempesta si el toquen.",
"Baixa la Velocitat en contacte.": "Baixa la Vel. en contacte.",
"Inverteix les habilitats d'aura.": "Inverteix les aures.",
"El contacte evita la protecció.": "El contacte passa la protecció.",
"Converteix l'electricitat en PS.": "Torna l'electricitat en PS.",
"Canvia de tipus segons el camp.": "Canvia de tipus segons el camp.",
"Anul·la els atacs de KO directe.": "Anul·la els KO directes.",
"Triga una estona a engegar-se.": "Triga a engegar-se.",
"Prefereix la humitat a la calor.": "Prefereix humitat a calor.",
"Impedeix limitar els moviments.": "Evita limitar els mov.",
"El contacte baixa la Velocitat.": "El contacte baixa la Vel.",
"Balla juntament amb els altres.": "Balla amb els altres.",
"Afavoreix els efectes afegits.": "Afavoreix els efectes afegits.",
"Reforça els moviments de puny.": "Puja els mov. de puny.",
"Endevina un moviment del rival.": "Endevina un mov. del rival.",
"En debilitar-se fereix el rival.": "En caure, fereix el rival.",
"Els records li canvien el tipus.": "Els records li canvien el tipus.",
"Recupera PS si està enverinat.": "Recupera PS si té verí.",
"Anul·la moviments en contacte.": "Anul·la mov. en contacte.",
"Es rendeix amb la meitat de PS.": "Es rendeix a mig PS.",
"Atreu els moviments elèctrics.": "Atreu els mov. elèctrics.",
"Reforça els “no gaire eficaç”.": "Puja el “no gaire eficaç”.",
"Reforça els moviments d'onada.": "Puja els mov. d'onada.",
"Pot reciclar una baia gastada.": "Pot reciclar una baia usada.",
"Invoca una tempesta de sorra.": "Invoca tempesta de sorra.",
"Puja la Velocitat si s'espanta.": "Puja la Vel. si s'espanta.",
"Protegeix els de tipus Planta.": "Protegeix els de tipus Planta.",
"Impedeix els efectes afegits.": "Evita els efectes afegits.",
"Els cops Sinistre pugen l'Atac.": "Els cops Sinistre pugen l'Atac.",
"Reforça els moviments febles.": "Puja els mov. febles.",
"Reforça els moviments Planta.": "Puja els mov. Planta.",
"Ignora la redirecció del rival.": "Ignora la redirecció rival.",
"Enverina el rival en contacte.": "Enverina en contacte.",
"Descobreix l'objecte del rival.": "Veu l'objecte del rival.",
"Protegeix de la calor i el foc.": "Protegeix de calor i foc.",
"Impedeix el dany de retrocés.": "Evita el dany de retrocés.",
"Es transforma mentre combat.": "Es transforma combatent.",
"Puja la Velocitat a poc a poc.": "Puja la Vel. a poc a poc.",
"Invoca llum del sol al combat.": "Invoca sol al combat.",
"Fereix el rival si el derroten.": "Fereix el rival si cau.",
"Canvia precisió per potència.": "Canvia precisió per potència.",
"Puja l'Atac si està enverinat.": "Puja l'Atac si té verí.",
"Puja l'Atac i fixa el moviment.": "Puja l'Atac i fixa el mov.",
"Canvia efectes per potència.": "Canvia efectes per potència.",
"Reforça els moviments d'Acer.": "Puja els mov. d'Acer.",
"Puja l'At. Esp. si està cremat.": "Puja l'At. Esp. si es crema.",
"No el toquen els atacs Terra.": "No el toquen els atacs Terra.",
"Anul·la els efectes del clima.": "Anul·la els efectes del clima.",
"Un ninot el protegeix un cop.": "Un ninot el tapa un cop.",
"Reforça els moviments Aigua.": "Puja els mov. Aigua.",
"Puja la Defensa si el toquen.": "Puja la Defensa si el toquen.",
"Protegeix del fred i la calor.": "Protegeix de fred i calor.",
"Es cura en sortir del combat.": "Es cura en sortir del combat.",
"Els Normal passen a Elèctric.": "Mov. Normal a Elèctric.",
"Duplica l'efecte de les baies.": "Duplica l'efecte de baies.",
"Canvia al tipus del moviment.": "Canvia al tipus del mov.",
"La closca es trenca a mig PS.": "La closca es trenca a mig PS.",
"Fereix els Pokémon adormits.": "Fereix els Pokémon adormits.",
"El camp passa a ser Elèctric.": "El camp passa a Elèctric.",
"Menja les baies abans d'hora.": "Menja les baies abans d'hora.",
"Impedeix que l'equip s'adormi.": "Evita que l'equip s'adormi.",
"Anul·la totes les habilitats.": "Anul·la totes les habilitats.",
"Si el toquen, escup la presa.": "Si el toquen, escup la presa.",
"Puja l'evasió si està confós.": "Puja l'evasió si és confós.",
"Només el fereixen els atacs.": "Només el fereixen els atacs.",
"Només actua cada dos torns.": "Només actua cada dos torns.",
"Impedeix la fugida del rival.": "Evita la fugida del rival.",
"Bloqueja els estats amb sol.": "Bloqueja els estats amb sol.",
"Reforça els moviments Fada.": "Puja els mov. Fada.",
"Es reforça si el toca el foc.": "Es reforça si el toca el foc.",
"Els Normal passen a Volador.": "Mov. Normal a Volador.",
}
