# -*- coding: utf-8 -*-
"""Linguistic fixes found in review:
- mint descriptions used masculine adjective forms that did not match the
  feminine nature names in nature_names.h; now they quote the nature name
- Cinturo Negr was a truncated word; use a clean abbreviation
- shard item names now match between items.h and the strings.c shop list
"""
KIND = 'c'
FILES = ['src/data/text/item_descriptions.h', 'src/data/text/trainer_class_names.h', 'src/strings.c']
T = {
"Menta que encanta als Pokémon. Gust Ferm.": "Menta per a la\\nnaturalesa\\nFerma.",
"Menta que encanta\\nals Pokémon. Gust\\nFerm.": "Menta per a la\\nnaturalesa\\nFerma.",
"Menta que encanta\\nals Pokémon.\\nGust Ferm.": "Menta per a la\\nnaturalesa\\nFerma.",
"Menta que encanta als Pokémon. Gust Audaç.": "Menta per a la\\nnaturalesa\\nAudaç.",
"Menta que encanta\\nals Pokémon. Gust\\nAudaç.": "Menta per a la\\nnaturalesa\\nAudaç.",
"Menta que encanta\\nals Pokémon.\\nGust Audaç.": "Menta per a la\\nnaturalesa\\nAudaç.",
"Menta que encanta als Pokémon. Gust Valent.": "Menta per a la\\nnaturalesa\\nValenta.",
"Menta que encanta\\nals Pokémon. Gust\\nValent.": "Menta per a la\\nnaturalesa\\nValenta.",
"Menta que encanta\\nals Pokémon.\\nGust Valent.": "Menta per a la\\nnaturalesa\\nValenta.",
"Menta que encanta als Pokémon. Gust Calmat.": "Menta per a la\\nnaturalesa\\nCalmada.",
"Menta que encanta\\nals Pokémon. Gust\\nCalmat.": "Menta per a la\\nnaturalesa\\nCalmada.",
"Menta que encanta\\nals Pokémon.\\nGust Calmat.": "Menta per a la\\nnaturalesa\\nCalmada.",
"Menta que encanta als Pokémon. Gust Curós.": "Menta per a la\\nnaturalesa\\nCurosa.",
"Menta que encanta\\nals Pokémon. Gust\\nCurós.": "Menta per a la\\nnaturalesa\\nCurosa.",
"Menta que encanta\\nals Pokémon.\\nGust Curós.": "Menta per a la\\nnaturalesa\\nCurosa.",
"Menta que encanta als Pokémon. Gust Amable.": "Menta per a la\\nnaturalesa\\nAmable.",
"Menta que encanta\\nals Pokémon. Gust\\nAmable.": "Menta per a la\\nnaturalesa\\nAmable.",
"Menta que encanta\\nals Pokémon.\\nGust Amable.": "Menta per a la\\nnaturalesa\\nAmable.",
"Menta que encanta als Pokémon. Gust Precipitat.": "Menta per a la\\nnaturalesa\\nPrecipitada.",
"Menta que encanta\\nals Pokémon. Gust\\nPrecipitat.": "Menta per a la\\nnaturalesa\\nPrecipitada.",
"Menta que encanta\\nals Pokémon.\\nGust Precipitat.": "Menta per a la\\nnaturalesa\\nPrecipitada.",
"Menta que encanta als Pokémon. Gust Pícar.": "Menta per a la\\nnaturalesa\\nPícara.",
"Menta que encanta\\nals Pokémon. Gust\\nPícar.": "Menta per a la\\nnaturalesa\\nPícara.",
"Menta que encanta\\nals Pokémon.\\nGust Pícar.": "Menta per a la\\nnaturalesa\\nPícara.",
"Menta que encanta als Pokémon. Gust Alegre.": "Menta per a la\\nnaturalesa\\nAlegre.",
"Menta que encanta\\nals Pokémon. Gust\\nAlegre.": "Menta per a la\\nnaturalesa\\nAlegre.",
"Menta que encanta\\nals Pokémon.\\nGust Alegre.": "Menta per a la\\nnaturalesa\\nAlegre.",
"Menta que encanta als Pokémon. Gust Fluix.": "Menta per a la\\nnaturalesa\\nFluixa.",
"Menta que encanta\\nals Pokémon. Gust\\nFluix.": "Menta per a la\\nnaturalesa\\nFluixa.",
"Menta que encanta\\nals Pokémon.\\nGust Fluix.": "Menta per a la\\nnaturalesa\\nFluixa.",
"Menta que encanta als Pokémon. Gust Solitari.": "Menta per a la\\nnaturalesa\\nSolitària.",
"Menta que encanta\\nals Pokémon. Gust\\nSolitari.": "Menta per a la\\nnaturalesa\\nSolitària.",
"Menta que encanta\\nals Pokémon.\\nGust Solitari.": "Menta per a la\\nnaturalesa\\nSolitària.",
"Menta que encanta als Pokémon. Gust Suau.": "Menta per a la\\nnaturalesa\\nSuau.",
"Menta que encanta\\nals Pokémon. Gust\\nSuau.": "Menta per a la\\nnaturalesa\\nSuau.",
"Menta que encanta\\nals Pokémon.\\nGust Suau.": "Menta per a la\\nnaturalesa\\nSuau.",
"Menta que encanta als Pokémon. Gust Modest.": "Menta per a la\\nnaturalesa\\nModesta.",
"Menta que encanta\\nals Pokémon. Gust\\nModest.": "Menta per a la\\nnaturalesa\\nModesta.",
"Menta que encanta\\nals Pokémon.\\nGust Modest.": "Menta per a la\\nnaturalesa\\nModesta.",
"Menta que encanta als Pokémon. Gust Ingenu.": "Menta per a la\\nnaturalesa\\nIngènua.",
"Menta que encanta\\nals Pokémon. Gust\\nIngenu.": "Menta per a la\\nnaturalesa\\nIngènua.",
"Menta que encanta\\nals Pokémon.\\nGust Ingenu.": "Menta per a la\\nnaturalesa\\nIngènua.",
"Menta que encanta als Pokémon. Gust Murri.": "Menta per a la\\nnaturalesa\\nMurri.",
"Menta que encanta\\nals Pokémon. Gust\\nMurri.": "Menta per a la\\nnaturalesa\\nMurri.",
"Menta que encanta\\nals Pokémon.\\nGust Murri.": "Menta per a la\\nnaturalesa\\nMurri.",
"Menta que encanta als Pokémon. Gust Tranquil.": "Menta per a la\\nnaturalesa\\nTranquil·la.",
"Menta que encanta\\nals Pokémon. Gust\\nTranquil.": "Menta per a la\\nnaturalesa\\nTranquil·la.",
"Menta que encanta\\nals Pokémon.\\nGust Tranquil.": "Menta per a la\\nnaturalesa\\nTranquil·la.",
"Menta que encanta als Pokémon. Gust Impulsiu.": "Menta per a la\\nnaturalesa\\nImpulsiva.",
"Menta que encanta\\nals Pokémon. Gust\\nImpulsiu.": "Menta per a la\\nnaturalesa\\nImpulsiva.",
"Menta que encanta\\nals Pokémon.\\nGust Impulsiu.": "Menta per a la\\nnaturalesa\\nImpulsiva.",
"Menta que encanta als Pokémon. Gust Relaxat.": "Menta per a la\\nnaturalesa\\nRelaxada.",
"Menta que encanta\\nals Pokémon. Gust\\nRelaxat.": "Menta per a la\\nnaturalesa\\nRelaxada.",
"Menta que encanta\\nals Pokémon.\\nGust Relaxat.": "Menta per a la\\nnaturalesa\\nRelaxada.",
"Menta que encanta als Pokémon. Gust Descarat.": "Menta per a la\\nnaturalesa\\nDescarada.",
"Menta que encanta\\nals Pokémon. Gust\\nDescarat.": "Menta per a la\\nnaturalesa\\nDescarada.",
"Menta que encanta\\nals Pokémon.\\nGust Descarat.": "Menta per a la\\nnaturalesa\\nDescarada.",
"Menta que encanta als Pokémon. Gust Seriós.": "Menta per a la\\nnaturalesa\\nSeriosa.",
"Menta que encanta\\nals Pokémon. Gust\\nSeriós.": "Menta per a la\\nnaturalesa\\nSeriosa.",
"Menta que encanta\\nals Pokémon.\\nGust Seriós.": "Menta per a la\\nnaturalesa\\nSeriosa.",
"Menta que encanta als Pokémon. Gust Tímid.": "Menta per a la\\nnaturalesa\\nTímida.",
"Menta que encanta\\nals Pokémon. Gust\\nTímid.": "Menta per a la\\nnaturalesa\\nTímida.",
"Menta que encanta\\nals Pokémon.\\nGust Tímid.": "Menta per a la\\nnaturalesa\\nTímida.",
"Cinturó Negr": "Cint. Negre",
"Fragment Vermell": "Frag. Vermell",
"Fragment Blau": "Frag. Blau",
"Fragment Groc": "Frag. Groc",
"Fragment Verd": "Frag. Verd",
}
