# -*- coding: utf-8 -*-
"""Catalan translation for src/strings.c  (part 1: menus, Pokedex, bag, shop).

Glossary:
  Trainer=Entrenador  Badge=Medalla  Bag=Motxilla  item=objecte
  move=moviment  Ability=Habilitat  nature=naturalesa  Berry=Baia
  HP=PS  Attack=Atac  Defense=Defensa  Speed=Velocitat
  Sp. Atk=At. Esp.  Sp. Def=Def. Esp.  Lv.=Niv.  Cancel=Cancel·lar
"""
KIND = 'c'
FILES = ['src/strings.c']

T = {
# ---- title / save ----
"New Game": "Partida Nova",
"Continue": "Continuar",
"Option": "Opcions",
"Mystery Gift": "Regal Misteriós",
"Mystery Events": "Fets Misteriosos",
"The Wireless Adapter is not\\nconnected.": "L'adaptador sense fils no\\nestà connectat.",
"Mystery Gift can't be used while\\nthe Wireless Adapter is attached.": "No es pot fer servir Regal Misteriós\\namb l'adaptador sense fils connectat.",
"Mystery Events can't be used while\\nthe Wireless Adapter is attached.": "No es poden fer servir els Fets\\nMisteriosos amb l'adaptador connectat.",
"Updating save file using external\\ndata. Please wait.": "S'actualitza la partida amb dades\\nexternes. Espera un moment.",
"The save file has been updated.": "La partida s'ha actualitzat.",
"The save file is corrupted. The\\nprevious save file will be loaded.": "La partida està malmesa. Es\\ncarregarà la partida anterior.",
"The save file has been erased\\ndue to corruption or damage.": "La partida s'ha esborrat perquè\\nestava malmesa o danyada.",
"The internal battery has run dry.\\nThe game can be played.\\pHowever, clock-based events will\\nno longer occur.": "La bateria interna s'ha esgotat.\\nEncara pots jugar.\\pPerò els fets basats en el rellotge\\nja no es produiran.",
"Saving…\\nDon't turn off the power.": "S'està desant…\\nNo apaguis la consola.",
"Save completed.": "S'ha desat la partida.",
"Save failed…": "No s'ha pogut desar…",
"Save failed. Checking the backup\\nmemory… Please wait.\\n{COLOR RED}“Time required: about 1 minute”": "Error en desar. Es comprova la\\nmemòria de reserva… Espera.\\n{COLOR RED}“Temps necessari: un minut”",
"The backup memory is damaged, or\\nthe internal battery has run dry.\\nYou can still play, but not save.": "La memòria de reserva està\\ndanyada o la bateria s'ha esgotat.\\nPots jugar, però no desar.",
"{COLOR RED}“Game play cannot be continued.\\nReturning to the title screen…”": "{COLOR RED}“No es pot continuar jugant.\\nEs torna a la pantalla de títol…”",
"Check completed.\\nAttempting to save again.\\nPlease wait.": "Comprovació acabada.\\nEs torna a intentar desar.\\nEspera un moment.",
"Save completed.\\n{COLOR RED}“Game play cannot be continued.\\nReturning to the title screen.”": "S'ha desat la partida.\\n{COLOR RED}“No es pot continuar jugant.\\nEs torna a la pantalla de títol.”",
"Save completed.\\n{COLOR RED}“Please press the A Button.”": "S'ha desat la partida.\\n{COLOR RED}“Prem el botó A.”",
"Data will be saved.\\nPlease wait.": "Es desaran les dades.\\nEspera un moment.",
"Save completed.\\nPlease press the A Button.": "S'ha desat la partida.\\nPrem el botó A.",
"Clear all save data areas?": "Vols esborrar totes les dades\\ndesades?",
"Clearing data…\\nPlease wait.": "S'esborren les dades…\\nEspera un moment.",
"Quit the game?": "Vols sortir del joc?",

# ---- trainer card / controls ----
"Player": "Jugador",
"Pokédex": "Pokédex",
"Time": "Temps",
"Badges": "Medalles",
"A Button": "Botó A",
"B Button": "Botó B",
"R Button": "Botó R",
"L Button": "Botó L",
"Start": "Start",
"Select": "Select",
"+ Control Pad": "+ Creueta",
"L Button  R Button": "Botó L  Botó R",
"Controls": "Controls",
"{DPAD_UPDOWN}Pick {A_BUTTON}Ok": "{DPAD_UPDOWN}Tria {A_BUTTON}D'acord",
"{A_BUTTON}Next": "{A_BUTTON}Següent",
"{A_BUTTON}Next {B_BUTTON}Back": "{A_BUTTON}Següent {B_BUTTON}Enrere",
"{DPAD_UPDOWN}Pick {A_BUTTON}Next {B_BUTTON}Cancel": "{DPAD_UPDOWN}Tria {A_BUTTON}Següent {B_BUTTON}Cancel·la",
"{DPAD_UPDOWN}Pick {A_BUTTON}{B_BUTTON}Cancel": "{DPAD_UPDOWN}Tria {A_BUTTON}{B_BUTTON}Cancel·la",
"{A_BUTTON}Exit": "{A_BUTTON}Surt",
"Boy": "Noi",
"Girl": "Noia",
"A Button: Registration Counter": "Botó A: Taulell de registre",
"A Button: Title Screen": "Botó A: Pantalla de títol",
"{DPAD_NONE}Move  {A_BUTTON}Ok  {B_BUTTON}Back": "{DPAD_NONE}Mou  {A_BUTTON}D'acord  {B_BUTTON}Enrere",
"{DPAD_UPDOWN}Pick {A_BUTTON}Ok {B_BUTTON}Exit": "{DPAD_UPDOWN}Tria {A_BUTTON}D'acord {B_BUTTON}Surt",
"{DPAD_UPDOWN}Pick {A_BUTTON}Ok {B_BUTTON}Cancel": "{DPAD_UPDOWN}Tria {A_BUTTON}D'acord {B_BUTTON}Cancel·la",

# ---- Pokedex ----
"This world…{PAUSE 96}\\p": "Aquest món…{PAUSE 96}\\p",
"????? Pokémon": "Pokémon ?????",
"????.? lbs.": "????.? lliures",
"        .   lbs.": "        .   lliures",
"                       Pokémon": "                       Pokémon",
"Cry of": "Crit de",
"Size compared to ": "Mida comparada amb ",
"Pokédex registration completed.": "Registre al Pokédex completat.",
"HT": "AL",
"WT": "PE",
"Searching…\\nPlease wait.": "S'està cercant…\\nEspera un moment.",
"Search completed.": "Cerca acabada.",
"No matching Pokémon were found.": "No s'ha trobat cap Pokémon\\nque hi coincideixi.",
"Search for Pokémon based on\\nselected parameters.": "Cerca Pokémon segons els\\nparàmetres triats.",
"Switch Pokédex listings.": "Canvia la llista del Pokédex.",
"Return to the Pokédex.": "Torna al Pokédex.",
"Select the Pokédex mode.": "Tria el mode del Pokédex.",
"Select the Pokédex listing mode.": "Tria el mode de llista del Pokédex.",
"List by the first letter in the name.\\nSpotted Pokémon only.": "Ordena per la primera lletra del nom.\\nNomés Pokémon vistos.",
"List by body color.\\nSpotted Pokémon only.": "Ordena per color del cos.\\nNomés Pokémon vistos.",
"List by type.\\nOwned Pokémon only.": "Ordena per tipus.\\nNomés Pokémon capturats.",
"Execute search/switch.": "Executa la cerca o el canvi.",
"Kanto Dex": "Dex de Kanto",
"National Dex": "Dex Nacional",
"Numerical mode": "Mode numèric",
"A to Z mode": "Mode A a Z",
"Heaviest mode": "Mode més pesat",
"Lightest mode": "Mode més lleuger",
"Tallest mode": "Mode més alt",
"Smallest mode": "Mode més petit",
"Red": "Vermell",
"Yellow": "Groc",
"Green": "Verd",
"Black": "Negre",
"Brown": "Marró",
"Purple": "Lila",
"Gray": "Gris",
"White": "Blanc",
"Pink": "Rosa",
"Kanto region's Pokédex": "Pokédex de la regió de Kanto",
"National edition Pokédex": "Pokédex en edició nacional",
"Pokémon are listed according to their\\nnumber.": "Els Pokémon s'ordenen segons el\\nseu número.",
"Spotted and owned Pokémon are listed\\nalphabetically.": "Els Pokémon vistos i capturats\\ns'ordenen alfabèticament.",
"Owned Pokémon are listed from the\\nheaviest to the lightest.": "Els Pokémon capturats s'ordenen\\ndel més pesat al més lleuger.",
"Owned Pokémon are listed from the\\nlightest to the heaviest.": "Els Pokémon capturats s'ordenen\\ndel més lleuger al més pesat.",
"Owned Pokémon are listed from the\\ntallest to the smallest.": "Els Pokémon capturats s'ordenen\\ndel més alt al més petit.",
"Owned Pokémon are listed from the\\nsmallest to the tallest.": "Els Pokémon capturats s'ordenen\\ndel més petit al més alt.",
"Don't specify.": "No ho especifiquis.",
"None": "Cap",
"Search for wild Pokémon.": "Cerca Pokémon salvatges.",

# ---- hall of fame ----
"Welcome to the Hall of Fame!": "Benvingut al Saló de la Fama!",
"Spotted Pokémon: {STR_VAR_1}!\\nOwned Pokémon: {STR_VAR_2}!\\pProf. Oak's Pokédex rating!\\pProf. Oak: Let's see…\\p": "Pokémon vistos: {STR_VAR_1}!\\nPokémon capturats: {STR_VAR_2}!\\pValoració del Pokédex del Prof. Oak!\\pProf. Oak: A veure…\\p",
"The Hall of Fame data is corrupted.": "Les dades del Saló de la Fama\\nestan malmeses.",
"Hall of Fame No. {STR_VAR_1}": "Saló de la Fama núm. {STR_VAR_1}",
"League Champion!\\nCongratulations!": "Campió de la Lliga!\\nEnhorabona!",
"Hall of Fame": "Saló de la Fama",
"Hall of Fame debut  ": "Debut al Saló de la Fama  ",

# ---- misc labels ----
"No. ": "Núm. ",
"Lv. ": "Niv. ",
"IDNo. /": "Núm. ID /",
"Name": "Nom",
"IDNo.": "Núm. ID",
"Prof. Birch is in trouble!\\nRelease a Pokémon and rescue him!": "El Prof. Birch està en perill!\\nTreu un Pokémon i salva'l!",
"Do you choose this Pokémon?": "Vols triar aquest Pokémon?",
"Fly to where?": "On vols volar?",
"Use": "Usar",
"Toss": "Llençar",
"Register": "Registrar",
"Register L": "Registrar L",
"Register R": "Registrar R",
"Give": "Donar",
"Check tag": "Veure etiqueta",
"Confirm": "Confirmar",
"Walk": "Caminar",
"Cancel": "Cancel·lar",
"Show": "Mostrar",
"Item": "Objecte",
"Mail": "Carta",
"Take": "Agafar",
"Store": "Guardar",
"Check": "Comprovar",
"Deselect": "Desmarcar",
"Go back to the\\nprevious menu.": "Torna al menú\\nanterior.",
"What would you like to do?": "Què vols fer?",
" Berry": " Baia",
"{STR_VAR_1} coins": "{STR_VAR_1} fitxes",
"Close Bag": "Tanca la motxilla",
"{STR_VAR_1} is\\nselected.": "S'ha triat\\n{STR_VAR_1}.",
"You can't write\\nmail here.": "Aquí no pots escriure\\ncartes.",
"There is no\\nPokémon.": "No hi ha cap\\nPokémon.",
"Move the\\n{STR_VAR_1}\\nwhere?": "On vols moure\\n{STR_VAR_1}?",
"The {STR_VAR_1} can't be held.": "No es pot portar {STR_VAR_1}.",
"The {STR_VAR_1} can't be held\\nhere.": "Aquí no es pot portar\\n{STR_VAR_1}.",
"Deposit how many\\n{STR_VAR_1}(s)?": "Quants {STR_VAR_1}\\nvols dipositar?",
"Deposited {STR_VAR_2}\\n{STR_VAR_1}(s).": "S'han dipositat {STR_VAR_2}\\n{STR_VAR_1}.",
"There's no room to\\nstore items.": "No hi ha espai per\\nguardar objectes.",
"Important items\\ncan't be stored in\\nthe PC!": "Els objectes importants\\nno es poden guardar\\nal PC!",
"That's much too\\nimportant to toss\\nout!": "Això és massa\\nimportant per\\nllençar-ho!",
"Toss out how many\\n{STR_VAR_1}(s)?": "Quants {STR_VAR_1}\\nvols llençar?",
"Threw away {STR_VAR_2}\\n{STR_VAR_1}(s).": "S'han llençat {STR_VAR_2}\\n{STR_VAR_1}.",
"Is it okay to\\nthrow away {STR_VAR_2}\\n{STR_VAR_1}(s)?": "Segur que vols\\nllençar {STR_VAR_2}\\n{STR_VAR_1}?",
"Oak's advice…\\n{PLAYER}, there's a time and place for\\leverything!{PAUSE_UNTIL_PRESS}": "Consell de l'Oak…\\n{PLAYER}, cada cosa té el seu\\lmoment i el seu lloc!{PAUSE_UNTIL_PRESS}",
"You can't dismount your bike here.{PAUSE_UNTIL_PRESS}": "Aquí no pots baixar de la bici.{PAUSE_UNTIL_PRESS}",
"Huh?\\nThe Itemfinder's responding!\\pThere's an item buried around here!{PAUSE_UNTIL_PRESS}": "Eh?\\nEl Cercaobjectes reacciona!\\pHi ha un objecte enterrat per aquí!{PAUSE_UNTIL_PRESS}",
"Oh!\\nThe Itemfinder's shaking wildly!{PAUSE_UNTIL_PRESS}": "Oh!\\nEl Cercaobjectes tremola molt!{PAUSE_UNTIL_PRESS}",
"… … … …Nope!\\nThere's no response.{PAUSE_UNTIL_PRESS}": "… … … …Res!\\nNo hi ha cap reacció.{PAUSE_UNTIL_PRESS}",
"Your coins:\\n{STR_VAR_1}{PAUSE_UNTIL_PRESS}": "Les teves fitxes:\\n{STR_VAR_1}{PAUSE_UNTIL_PRESS}",
"Booted up a TM.": "S'ha activat una MT.",
"Booted up an HM.": "S'ha activat una MO.",
"It contained\\n{STR_VAR_1}.\\pTeach {STR_VAR_1}\\nto a Pokémon?": "Contenia\\n{STR_VAR_1}.\\pVols ensenyar {STR_VAR_1}\\na un Pokémon?",
"{PLAYER} used the\\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}": "{PLAYER} ha fet servir\\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}",
"But the effects of a Repel\\nlingered from earlier.{PAUSE_UNTIL_PRESS}": "Però l'efecte d'un Repel·lent\\nencara durava.{PAUSE_UNTIL_PRESS}",
"{PLAYER} used the\\n{STR_VAR_2}.\\pWild Pokémon will be lured.{PAUSE_UNTIL_PRESS}": "{PLAYER} ha fet servir\\n{STR_VAR_2}.\\pAtraurà els Pokémon salvatges.{PAUSE_UNTIL_PRESS}",
"{PLAYER} used the\\n{STR_VAR_2}.\\pWild Pokémon will be repelled.{PAUSE_UNTIL_PRESS}": "{PLAYER} ha fet servir\\n{STR_VAR_2}.\\pRepel·lirà els Pokémon salvatges.{PAUSE_UNTIL_PRESS}",
"The box is full.{PAUSE_UNTIL_PRESS}": "La caixa és plena.{PAUSE_UNTIL_PRESS}",
"Powder qty: {STR_VAR_1}{PAUSE_UNTIL_PRESS}": "Quantitat de pols: {STR_VAR_1}{PAUSE_UNTIL_PRESS}",
"the field": "el terreny",
"the battle": "el combat",
"the Pokémon list": "la llista de Pokémon",
"the shop": "la botiga",
"the PC": "el PC",
"Return to\\n{STR_VAR_1}.": "Torna a\\n{STR_VAR_1}.",

# ---- bag pockets ----
"Items": "Objectes",
"Poké Balls": "Poké Balls",
"TMs & HMs": "MTs i MOs",
"Berries": "Baies",
"Key Items": "Objectes clau",
"Medicine": "Medicines",
"Battle Item": "Objectes de combat",
"Treasures": "Tresors",
"Bag": "Motxilla",

# ---- berry tag ----
"Size /": "Mida /",
"Firm /": "Fermesa /",
"Very soft": "Molt tova",
"Soft": "Tova",
"Hard": "Dura",
"Very hard": "Molt dura",
"Super hard": "Duríssima",
"Berry tag": "Etiqueta de baia",
"Spicy": "Picant",
"Dry": "Sec",
"Sweet": "Dolç",
"Bitter": "Amarg",
"Sour": "Àcid",
"Tasty": "Gustós",
"Feel": "Tacte",
"Stow Case.": "Guarda l'estoig.",
"Throw away this\\n{STR_VAR_1}?": "Vols llençar\\n{STR_VAR_1}?",
"The {STR_VAR_1}\\nwas thrown away.": "S'ha llençat\\n{STR_VAR_1}.",
"{STR_VAR_1} ate the\\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha menjat\\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} happily ate the\\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha menjat\\n{STR_VAR_2} ben content.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} disdainfully ate the\\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha menjat\\n{STR_VAR_2} amb menyspreu.{PAUSE_UNTIL_PRESS}",
"Red {POKEBLOCK}": "{POKEBLOCK} vermell",
"Blue {POKEBLOCK}": "{POKEBLOCK} blau",
"Pink {POKEBLOCK}": "{POKEBLOCK} rosa",
"Green {POKEBLOCK}": "{POKEBLOCK} verd",
"Yellow {POKEBLOCK}": "{POKEBLOCK} groc",
"Purple {POKEBLOCK}": "{POKEBLOCK} lila",
"Indigo {POKEBLOCK}": "{POKEBLOCK} indi",
"Brown {POKEBLOCK}": "{POKEBLOCK} marró",
"Liteblue {POKEBLOCK}": "{POKEBLOCK} cel",
"Olive {POKEBLOCK}": "{POKEBLOCK} oliva",
"Gray {POKEBLOCK}": "{POKEBLOCK} gris",
"Black {POKEBLOCK}": "{POKEBLOCK} negre",
"White {POKEBLOCK}": "{POKEBLOCK} blanc",
"Gold {POKEBLOCK}": "{POKEBLOCK} daurat",

# ---- shop ----
"Buy": "Comprar",
"Sell": "Vendre",
"Quit": "Sortir",
"In Bag: {STR_VAR_1}": "A la motxilla: {STR_VAR_1}",
"Quit shopping.": "Deixa de comprar.",
"{STR_VAR_1}? Certainly.\\nHow many would you like?": "{STR_VAR_1}? Molt bé.\\nQuants en vols?",
"{STR_VAR_1}? And you wanted {STR_VAR_2}?\\nThat will be ¥{STR_VAR_3}.": "{STR_VAR_1}? I en volies {STR_VAR_2}?\\nSón ¥{STR_VAR_3}.",
"{STR_VAR_1}, is it?\\nThat'll be ¥{STR_VAR_2}. Do you want it?": "{STR_VAR_1}, oi?\\nSón ¥{STR_VAR_2}. El vols?",
"You wanted {STR_VAR_1}?\\nThat'll be ¥{STR_VAR_2}. Will that be okay?": "En volies {STR_VAR_1}?\\nSón ¥{STR_VAR_2}. Et va bé?",
"Here you go!\\nThank you very much.": "Aquí ho tens!\\nMoltes gràcies.",
"Thank you!\\nI'll send it to your home PC.": "Gràcies!\\nT'ho enviaré al PC de casa.",
"Thanks!\\nI'll send it to your PC at home.": "Gràcies!\\nT'ho enviaré al PC de casa.",
"You don't have enough money.{PAUSE_UNTIL_PRESS}": "No tens prou diners.{PAUSE_UNTIL_PRESS}",
"You have no more room for this\\nitem.{PAUSE_UNTIL_PRESS}": "No et queda espai per a aquest\\nobjecte.{PAUSE_UNTIL_PRESS}",
"The space for {STR_VAR_1} is full.{PAUSE_UNTIL_PRESS}": "L'espai per a {STR_VAR_1} és ple.{PAUSE_UNTIL_PRESS}",
"Is there anything else I can help\\nyou with?": "Vols que t'ajudi amb res més?",
"Can I help you with anything else?": "Et puc ajudar amb res més?",
"I'll throw in a Premier Ball, too.{PAUSE_UNTIL_PRESS}": "T'hi afegeixo una Premier Ball.{PAUSE_UNTIL_PRESS}",
"I'll throw in some Premier Balls, too.{PAUSE_UNTIL_PRESS}": "T'hi afegeixo unes Premier Balls.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_2}? Oh, no.\\nI can't buy that.{PAUSE_UNTIL_PRESS}": "{STR_VAR_2}? Ai, no.\\nAixò no ho puc comprar.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_2}?\\nHow many would you like to sell?": "{STR_VAR_2}?\\nQuants en vols vendre?",
"I can pay ¥{STR_VAR_1}.\\nWould that be okay?": "Te'n puc pagar ¥{STR_VAR_1}.\\nEt va bé?",
"Turned over the {STR_VAR_2}\\nand received ¥{STR_VAR_1}.": "Has lliurat {STR_VAR_2}\\ni has rebut ¥{STR_VAR_1}.",
"I'm sorry, but that item is sold out.\\p": "Em sap greu, però aquest objecte\\nestà exhaurit.\\p",
"SOLD OUT": "EXHAURIT",

# ---- party menu ----
"Shift": "Canviar",
"Send out": "Treure",
"Switch": "Bescanviar",
"Summary": "Resum",
"Moves": "Moviments",
"Enter": "Entrar",
"No entry": "No entrar",
"Read": "Llegir",
"Trade": "Intercanviar",
"HP": "PS",
"Sp. Atk": "At. Esp.",
"Sp. Def": "Def. Esp.",
"Attack": "Atac",
"Defense": "Defensa",
"Speed": "Velocitat",
"Max. HP": "PS màx.",
"It won't have any effect.{PAUSE_UNTIL_PRESS}": "No tindrà cap efecte.{PAUSE_UNTIL_PRESS}",
"This can't be used on\\nthat Pokémon.{PAUSE_UNTIL_PRESS}": "Això no es pot fer servir amb\\naquest Pokémon.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} can't be switched\\nout!{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} no pot sortir\\ndel combat!{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} is already\\nin battle!{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} ja està\\ncombatent!{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} has already been\\nselected.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} ja s'ha\\ntriat.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} has no energy\\nleft to battle!{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} no té prou\\nenergia per combatre!{PAUSE_UNTIL_PRESS}",
"You can't switch {STR_VAR_1}'s\\nPokémon with one of yours!{PAUSE_UNTIL_PRESS}": "No pots bescanviar el Pokémon de\\n{STR_VAR_1} per un dels teus!{PAUSE_UNTIL_PRESS}",
"An Egg can't battle!{PAUSE_UNTIL_PRESS}": "Un Ou no pot combatre!{PAUSE_UNTIL_PRESS}",
"This can't be used until a new\\nBadge is obtained.{PAUSE_UNTIL_PRESS}": "No es pot fer servir fins que\\nno obtinguis una Medalla nova.{PAUSE_UNTIL_PRESS}",
"No more than {STR_VAR_1} Pokémon\\nmay enter.{PAUSE_UNTIL_PRESS}": "No hi poden entrar més de\\n{STR_VAR_1} Pokémon.{PAUSE_UNTIL_PRESS}",
"Send the removed mail to\\nyour PC?": "Vols enviar la carta retirada\\nal teu PC?",
"The mail was sent to your PC.{PAUSE_UNTIL_PRESS}": "La carta s'ha enviat al teu PC.{PAUSE_UNTIL_PRESS}",
"Your PC's mailbox is full.{PAUSE_UNTIL_PRESS}": "La bústia del teu PC és plena.{PAUSE_UNTIL_PRESS}",
"If the mail is removed, the\\nmessage will be lost. Okay?": "Si retires la carta, es perdrà\\nel missatge. Hi estàs d'acord?",
"Mail must be removed before\\nholding an item.{PAUSE_UNTIL_PRESS}": "Cal retirar la carta abans de\\nportar un objecte.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} was given the\\n{STR_VAR_2} to hold.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} porta\\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} is already holding\\none {STR_VAR_2}.\\pWould you like to switch the\\ntwo items?": "{STR_VAR_1} ja porta\\nun {STR_VAR_2}.\\pVols bescanviar els dos\\nobjectes?",
"{STR_VAR_1} isn't holding\\nanything.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} no porta\\nres.{PAUSE_UNTIL_PRESS}",
"Received the {STR_VAR_2}\\nfrom {STR_VAR_1}.{PAUSE_UNTIL_PRESS}": "Has rebut {STR_VAR_2}\\nde {STR_VAR_1}.{PAUSE_UNTIL_PRESS}",
"Mail was taken from the\\nPokémon.{PAUSE_UNTIL_PRESS}": "S'ha retirat la carta del\\nPokémon.{PAUSE_UNTIL_PRESS}",
"The {STR_VAR_2} was taken and\\nreplaced with the {STR_VAR_1}.{PAUSE_UNTIL_PRESS}": "S'ha retirat {STR_VAR_2} i\\ns'ha posat {STR_VAR_1}.{PAUSE_UNTIL_PRESS}",
"This Pokémon is holding an\\nitem. It cannot hold mail.{PAUSE_UNTIL_PRESS}": "Aquest Pokémon porta un objecte.\\nNo pot portar cartes.{PAUSE_UNTIL_PRESS}",
"Mail was transferred from\\nthe mailbox.{PAUSE_UNTIL_PRESS}": "La carta s'ha transferit des de\\nla bústia.{PAUSE_UNTIL_PRESS}",
"The Bag is full. The Pokémon's\\nitem could not be removed.{PAUSE_UNTIL_PRESS}": "La motxilla és plena. No s'ha pogut\\nretirar l'objecte del Pokémon.{PAUSE_UNTIL_PRESS}",

# ---- move learning ----
"{STR_VAR_1} learned\\n{STR_VAR_2}!": "{STR_VAR_1} ha après\\n{STR_VAR_2}!",
"{STR_VAR_1} and {STR_VAR_2}\\nare not compatible.\\p{STR_VAR_2} can't be\\nlearned.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} i {STR_VAR_2}\\nno són compatibles.\\pNo es pot aprendre\\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} wants to learn the\\nmove {STR_VAR_2}.\\pHowever, {STR_VAR_1} already\\nknows four moves.\\pShould a move be deleted and\\nreplaced with {STR_VAR_2}?": "{STR_VAR_1} vol aprendre el\\nmoviment {STR_VAR_2}.\\pPerò {STR_VAR_1} ja en\\nsap quatre.\\pVols esborrar un moviment i\\nposar-hi {STR_VAR_2}?",
"Stop trying to teach\\n{STR_VAR_2}?": "Vols deixar d'ensenyar\\n{STR_VAR_2}?",
"{STR_VAR_1} did not learn the\\nmove {STR_VAR_2}.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} no ha après el\\nmoviment {STR_VAR_2}.{PAUSE_UNTIL_PRESS}",
"Which move should be forgotten?{PAUSE_UNTIL_PRESS}": "Quin moviment vols oblidar?{PAUSE_UNTIL_PRESS}",
"1, {PAUSE 15}2, and{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Poof!\\p{STR_VAR_1} forgot how to\\nuse {STR_VAR_2}.\\pAnd…{PAUSE_UNTIL_PRESS}": "1, {PAUSE 15}2 i{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Puf!\\p{STR_VAR_1} ha oblidat com\\nfer servir {STR_VAR_2}.\\pI…{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} already knows\\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} ja sap\\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}",
"HM moves can't be\\nforgotten now.": "Ara no es poden oblidar\\nels moviments MO.",
"Teach which move to {STR_VAR_1}?": "Quin moviment vols ensenyar a\\n{STR_VAR_1}?",
"Teach {STR_VAR_2}?": "Vols ensenyar {STR_VAR_2}?",
"{STR_VAR_1} is trying to learn\\n{STR_VAR_2}.\\pBut {STR_VAR_1} can't learn more\\nthan four moves.\\pDelete an older move to make\\nroom for {STR_VAR_2}?": "{STR_VAR_1} intenta aprendre\\n{STR_VAR_2}.\\pPerò {STR_VAR_1} no pot saber més\\nde quatre moviments.\\pVols esborrar un moviment antic per\\nfer lloc a {STR_VAR_2}?",
"{PAUSE 32}1, {PAUSE 15}2, and {PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Poof!\\p": "{PAUSE 32}1, {PAUSE 15}2 i {PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Puf!\\p",
"{STR_VAR_1} forgot {STR_VAR_3}.\\pAnd…\\p{STR_VAR_1} learned {STR_VAR_2}.": "{STR_VAR_1} ha oblidat {STR_VAR_3}.\\pI…\\p{STR_VAR_1} ha après {STR_VAR_2}.",
"{STR_VAR_1} did not learn the\\nmove {STR_VAR_2}.": "{STR_VAR_1} no ha après el\\nmoviment {STR_VAR_2}.",
"Give up trying to teach a new\\nmove to {STR_VAR_1}?": "Vols deixar d'ensenyar un\\nmoviment nou a {STR_VAR_1}?",
"Which move should be\\nforgotten?\\p": "Quin moviment vols\\noblidar?\\p",
"PP/": "PP/",
"Power/": "Potència/",
"Accuracy/": "Precisió/",

# ---- healing / stat items ----
"{STR_VAR_1}'s HP was restored\\nby {STR_VAR_2} point(s).{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} ha recuperat\\n{STR_VAR_2} PS.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} was cured of its\\npoisoning.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha curat de\\nl'enverinament.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} was cured of\\nparalysis.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha curat de\\nla paràlisi.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} woke up.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha despertat.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1}'s burn was healed.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha curat la cremada.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} was thawed out.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha desglaçat.{PAUSE_UNTIL_PRESS}",
"PP was restored.{PAUSE_UNTIL_PRESS}": "S'han recuperat els PP.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} regained health.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} ha recuperat la salut.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} became healthy.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha posat bo.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1}'s PP increased.{PAUSE_UNTIL_PRESS}": "Els PP de {STR_VAR_1} han pujat.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} was elevated to\\nLv. {STR_VAR_2}.": "{STR_VAR_1} ha pujat al\\nniv. {STR_VAR_2}.",
"{STR_VAR_1}'s base {STR_VAR_2}\\nstat was raised.{PAUSE_UNTIL_PRESS}": "L'estadística {STR_VAR_2} base de\\n{STR_VAR_1} ha pujat.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1}'s core {STR_VAR_2}\\nstat was raised.{PAUSE_UNTIL_PRESS}": "L'estadística {STR_VAR_2} interna de\\n{STR_VAR_1} ha pujat.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1}'s core stats were raised.{PAUSE_UNTIL_PRESS}": "Les estadístiques internes de\\n{STR_VAR_1} han pujat.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} turned friendly.\\nThe base {STR_VAR_2} fell!{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha fet més amistós.\\nEl {STR_VAR_2} base ha baixat!{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} turned friendly.\\nThe core {STR_VAR_2} fell!{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha fet més amistós.\\nEl {STR_VAR_2} intern ha baixat!{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} turned friendly.\\nIts core stats completely fell!{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha fet més amistós.\\nLes estadístiques internes han caigut!{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} adores you!\\nThe base {STR_VAR_2} fell!{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} t'adora!\\nEl {STR_VAR_2} base ha baixat!{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} turned friendly.\\nThe base {STR_VAR_2} can't fall!{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} s'ha fet més amistós.\\nEl {STR_VAR_2} base no pot baixar!{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} snapped out of its\\nconfusion.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} ha sortit de la\\nconfusió.{PAUSE_UNTIL_PRESS}",
"{STR_VAR_1} got over its\\ninfatuation.{PAUSE_UNTIL_PRESS}": "{STR_VAR_1} ha superat\\nl'enamorament.{PAUSE_UNTIL_PRESS}",
"The {STR_VAR_1}\\nwas thrown away.{PAUSE_UNTIL_PRESS}": "S'ha llençat\\n{STR_VAR_1}.{PAUSE_UNTIL_PRESS}",
"Turned on the Exp. Share.\\pParty will now gain a portion\\nof the Experience Points.{PAUSE_UNTIL_PRESS}": "S'ha activat el Repartiexp.\\pL'equip rebrà una part dels\\nPunts d'Experiència.{PAUSE_UNTIL_PRESS}",
"Turned off the Exp. Share.\\pParty will no longer gain a portion\\nof any Experience Points.{PAUSE_UNTIL_PRESS}": "S'ha desactivat el Repartiexp.\\pL'equip ja no rebrà cap part dels\\nPunts d'Experiència.{PAUSE_UNTIL_PRESS}",

# ---- short prompts ----
"Teach which Pokémon?": "A quin Pokémon?",
"Choose a Pokémon.": "Tria un Pokémon.",
"Move to where?": "On ho vols moure?",
"Use on which Pokémon?": "Amb quin Pokémon?",
"Give to which Pokémon?": "A quin Pokémon?",
"Do what with this {PKMN}?": "Què vols fer amb aquest {PKMN}?",
"There's nothing to Cut.": "Aquí no hi ha res a tallar.",
"You can't Surf here.": "Aquí no pots fer surf.",
"You're already Surfing.": "Ja estàs fent surf.",
"Can't use that here.": "Aquí no ho pots fer servir.",
"Restore which move?": "Quin moviment vols recuperar?",
"Boost PP of which move?": "De quin moviment vols pujar els PP?",
"Do what with an item?": "Què vols fer amb l'objecte?",
"No Pokémon for battle!": "No tens Pokémon per combatre!",
"Not enough HP…": "No hi ha prou PS…",
"{STR_VAR_1} Pokémon are needed.": "Calen {STR_VAR_1} Pokémon.",
"Pokémon can't be the same.": "Els Pokémon no poden ser iguals.",
"No identical hold items.": "No pot haver-hi objectes iguals.",
"The current is much too fast!": "El corrent és massa fort!",
"Do what with the Mail?": "Què vols fer amb la carta?",
"Choose Pokémon or Cancel.": "Tria un Pokémon o cancel·la.",
"Choose Pokémon and confirm.": "Tria els Pokémon i confirma.",
"Let's enjoy cycling!": "Va, gaudim de la bici!",
"This is in use already.": "Això ja s'està fent servir.",
"{STR_VAR_1} is already holding\\none {STR_VAR_2}.": "{STR_VAR_1} ja porta\\nun {STR_VAR_2}.",
"No use.": "No serveix.",
"Able": "Pot",
"First": "Primer",
"Second": "Segon",
"Third": "Tercer",
"Fourth": "Quart",
"Not able": "No pot",
"Able!": "Pot!",
"Not able!": "No pot!",
"Learned": "Après",
"Have": "En té",
"Don't have": "No en té",
"That Pokémon can't participate.{PAUSE_UNTIL_PRESS}": "Aquest Pokémon no pot participar.{PAUSE_UNTIL_PRESS}",
"Cancel participation?": "Vols cancel·lar la participació?",
"Cancel the battle?": "Vols cancel·lar el combat?",
"Return to the waiting room?": "Vols tornar a la sala d'espera?",
"Cancel the challenge?": "Vols cancel·lar el repte?",
"Want to escape from here and return\\nto {STR_VAR_1}?": "Vols escapar d'aquí i tornar\\na {STR_VAR_1}?",
"Want to return to the healing spot\\nused last in {STR_VAR_1}?": "Vols tornar a l'últim punt de\\ncuració fet servir a {STR_VAR_1}?",
"That's your only\\nPokémon for battle.": "És el teu únic\\nPokémon per combatre.",
"That Pokémon can't be traded\\nnow.": "Ara no es pot intercanviar\\naquest Pokémon.",
"An Egg can't be traded now.": "Ara no es pot intercanviar un Ou.",
"The other Trainer's Pokémon\\ncan't be traded now.": "Ara no es pot intercanviar el\\nPokémon de l'altre entrenador.",
"The other Trainer can't accept\\nthat Pokémon now.": "L'altre entrenador no pot acceptar\\naquest Pokémon ara.",
"You can't trade with that\\nTrainer now.": "Ara no pots intercanviar amb\\naquest entrenador.",
"That isn't the type of Pokémon\\nthat the other Trainer wants.": "Aquest no és el tipus de Pokémon\\nque vol l'altre entrenador.",
"That isn't an Egg.": "Això no és un Ou.",

# ---- summary screen ----
"OT/": "EO/",
"Rental Pokémon": "Pokémon de lloguer",
"Type/": "Tipus/",
"Power": "Potència",
"Accuracy": "Precisió",
"Appeal": "Atractiu",
"Jam": "Bloqueig",
"Status": "Estat",
"Exp. Points": "Punts Exp.",
"Next Lv.": "Niv. següent",
"Ribbons: {STR_VAR_1}": "Cintes: {STR_VAR_1}",
"Events": "Fets",
"Pokémon info": "Info del Pokémon",
"Pokémon skills": "Aptituds del Pokémon",
"Battle moves": "Moviments de combat",
"Contest moves": "Moviments de concurs",
"Info": "Info",
"Nature/": "Naturalesa/",
"Ribbons": "Cintes",
"In party": "A l'equip",
"Unknown": "Desconegut",
"It looks like this Egg will\\ntake a long time to hatch.": "Sembla que aquest Ou tardarà\\nmolt a trencar-se.",
"What will hatch from this?\\nIt will take some time.": "Què en sortirà?\\nEncara tardarà una mica.",
"It moves occasionally.\\nIt should hatch soon.": "Es mou de tant en tant.\\nAviat es trencarà.",
"It's making sounds.\\nIt's about to hatch!": "Fa sorolls.\\nEstà a punt de trencar-se!",
"'s Base": " - Base",
}
