# -*- coding: utf-8 -*-
"""Catalan: Professor Oak's Lab - starter scene, Pokedex handout, aides."""
KIND = 'asm'
FILES = ['data/maps/PalletTown_ProfessorOaksLab/scripts.inc']

T = {
"{RIVAL}: Gramps!\\n": "{RIVAL}: Avi!\\n",
"I'm fed up with waiting!$": "Estic tip d'esperar!$",
"Oak: {RIVAL}?\\n": "Oak: {RIVAL}?\\n",
"Let me think…\\p": "Deixa'm pensar…\\p",
"Oh, that's right, I told you to\\n": "Ah, és clar, t'havia dit que\\n",
"come! Just wait!\\p": "vinguessis! Espera't una mica!\\p",
"Here, {PLAYER}.\\p": "Vine, {PLAYER}.\\p",
"There is a Pokéball on my desk.\\p": "Hi ha una Pokéball al meu escriptori.\\p",
"When I was young, I was a serious\\n": "Quan era jove, era un entrenador\\n",
"Pokémon trainer.\\p": "Pokémon de debò.\\p",
"But now, in my old age, I study\\n": "Però ara, de gran, estudio els\\n",
"Pokémon more than I battle.\\p": "Pokémon més que no combato.\\p",
"I'd like you to raise this\\n": "M'agradaria que criessis aquest\\n",
"Pokémon for me!$": "Pokémon per mi!$",
"{RIVAL}: Hey! Gramps! No fair!\\n": "{RIVAL}: Ei! Avi! No és just!\\n",
"What about me?$": "I jo què?$",
"Oak: Be patient, {RIVAL}.\\p": "Oak: Tingues paciència, {RIVAL}.\\p",
"I'll take you to catch \\n": "Després et portaré a capturar\\n",
"your own Pokémon later.$": "el teu propi Pokémon.$",
"{RIVAL}: Too slow, {PLAYER}!\\p": "{RIVAL}: Massa lent, {PLAYER}!\\p",
"This is what you get for\\n": "Això et passa per venir\\n",
"taking the long way around.$": "fent la volta llarga.$",
"Oak: {RIVAL}!\\p": "Oak: {RIVAL}!\\p",
"Sigh...alright.\\n": "Uf...està bé.\\n",
"That Pokémon is yours.\\p": "Aquest Pokémon és teu.\\p",
"{PLAYER}, come over here.$": "{PLAYER}, vine cap aquí.$",
"Oak: Do you not want a\\n": "Oak: No vols un\\n",
"Pokémon, {PLAYER}?$": "Pokémon, {PLAYER}?$",
"Oak: Technically, that was\\n": "Oak: Tècnicament, aquell no era\\n",
"not my last Pokémon.\\p": "el meu últim Pokémon.\\p",
"I still have the Pikachu\\n": "Encara tinc el Pikachu\\n",
"I caught earlier...\\p": "que he capturat abans...\\p",
"I was going to return it to\\n": "Pensava tornar-lo al seu\\n",
"its natural habitat, but\\l": "hàbitat natural, però\\l",
"perhaps you should take it.$": "potser val més que te'l quedis.$",
"Oak: Incredible!\\p": "Oak: Increïble!\\p",
"It broke free of its Pokéball!$": "Ha sortit de la seva Pokéball!$",
"Oak: It seems to have taken quite\\n": "Oak: Sembla que li has despertat\\n",
"an interest in you, {PLAYER}.\\p": "molt d'interès, {PLAYER}.\\p",
"It looks like Pikachu has already\\n": "Sembla que Pikachu ja ha pres\\n",
"made its decision!\\p": "la seva decisió!\\p",
"You should absolutely take this\\n": "Sens dubte t'has de quedar aquest\\n",
"Pokémon.$": "Pokémon.$",
"Pikachu decided to stay by\\n": "Pikachu ha decidit quedar-se al\\n",
"{PLAYER}'s side!$": "costat de {PLAYER}!$",
"Oak: Say, why don't you give\\n": "Oak: Escolta, per què no poses\\n",
"a nickname to your new partner?$": "un sobrenom al teu nou company?$",
"{RIVAL}: Wait, {PLAYER}!$": "{RIVAL}: Espera, {PLAYER}!$",
"Let's check out our Pokémon!\\p": "Provem els nostres Pokémon!\\p",
"Come on, I'll take you on!$": "Vinga, t'accepto el repte!$",
"{RIVAL}: WHAT?\\n": "{RIVAL}: QUÈ?\\n",
"Unbelievable!\\l": "No m'ho puc creure!\\l",
"I picked the wrong Pokémon!$": "He triat el Pokémon equivocat!$",
"{RIVAL}: Yeah!\\n": "{RIVAL}: Sí!\\n",
"Am I great or what?$": "Sóc bo o què?$",
"{RIVAL}: Okay! I'll make my\\n": "{RIVAL}: Molt bé! Faré combatre\\n",
"Pokémon battle to toughen it up!\\p": "el meu Pokémon per enfortir-lo!\\p",
"{PLAYER}! Gramps!\\n": "{PLAYER}! Avi!\\n",
"Smell you later!$": "Ja ens veurem!$",
"Oak: Oh, {PLAYER}!\\n": "Oak: Oh, {PLAYER}!\\n",
"How is your new Pokémon?\\p": "Com va el teu nou Pokémon?\\p",
"Well, it seems to be growing more\\n": "Bé, sembla que cada cop està més\\n",
"attached to you.\\p": "unit a tu.\\p",
"You must be talented as a Pokémon\\n": "Deus tenir talent com a entrenador\\n",
"trainer.\\p": "Pokémon.\\p",
"What's that?\\n": "Què és això?\\n",
"You have something for me?$": "Tens alguna cosa per mi?$",
"{PLAYER} delivered Oak's Parcel.$": "{PLAYER} ha lliurat el Paquet d'Oak.$",
"Ah! \\n": "Ah!\\n",
"It's the custom Poké Ball!\\p": "És la Poké Ball personalitzada!\\p",
"I had it on order.\\n": "L'havia encarregat.\\n",
"Thank you!$": "Gràcies!$",
"{RIVAL}: Gramps!$": "{RIVAL}: Avi!$",
"{RIVAL}: I almost forgot!\\n": "{RIVAL}: Quasi me n'oblido!\\n",
"What did you call me for?$": "Per què m'has fet venir?$",
"Oak: Oh, right!\\n": "Oak: Ah, és clar!\\n",
"I have a request for you two.$": "Tinc una petició per a tots dos.$",
"On the desk there is my invention,\\n": "A l'escriptori hi ha el meu invent,\\n",
"the Pokédex!\\p": "el Pokédex!\\p",
"It automatically records data on\\n": "Registra automàticament dades dels\\n",
"Pokémon you've seen or caught.\\p": "Pokémon que has vist o capturat.\\p",
"It's a high-tech encyclopedia!$": "És una enciclopèdia d'alta tecnologia!$",
"Oak: {PLAYER} and {RIVAL}.\\n": "Oak: {PLAYER} i {RIVAL}.\\n",
"Take these with you.$": "Emporteu-vos-els.$",
"{PLAYER} received the Pokédex\\n": "{PLAYER} ha rebut el Pokédex\\n",
"from Professor Oak!$": "del Professor Oak!$",
"Oak: You can't get detailed data\\n": "Oak: No pots obtenir dades detallades\\n",
"on Pokémon by just seeing them.\\p": "dels Pokémon només veient-los.\\p",
"You must catch them to obtain\\n": "Els has de capturar per obtenir\\n",
"complete data.\\p": "les dades completes.\\p",
"So, here are some tools for\\n": "Així que aquí tens uns estris per\\n",
"catching wild Pokémon.$": "capturar Pokémon salvatges.$",
"{PLAYER} received five Poké Balls.$": "{PLAYER} ha rebut cinc Poké Balls.$",
"When a wild Pokémon appears,\\n": "Quan apareix un Pokémon salvatge,\\n",
"it's fair game.\\p": "és una presa legítima.\\p",
"Just throw a Poké Ball at it and\\n": "Només has de llançar-li una Poké Ball\\n",
"try to catch it!\\p": "i provar de capturar-lo!\\p",
"This won't always work, however.\\p": "Però això no sempre funciona.\\p",
"A healthy Pokémon can escape.\\n": "Un Pokémon sa pot escapar.\\n",
"You have to be lucky!$": "Cal tenir sort!$",
"To make a complete guide on all\\n": "Fer una guia completa de tots\\n",
"the Pokémon in the world…\\p": "els Pokémon del món…\\p",
"That was my dream!\\p": "Aquest era el meu somni!\\p",
"But, I'm too old.\\n": "Però sóc massa gran.\\n",
"I can't get the job done.\\p": "No puc acabar la feina.\\p",
"So, I want you two to fulfill my\\n": "Per això vull que vosaltres dos\\n",
"dream for me.\\p": "compliu el meu somni.\\p",
"Get moving, you two.\\p": "Aneu-hi, tots dos.\\p",
"This is a great undertaking in\\n": "Això és una gran empresa en la\\n",
"Pokémon history!$": "història dels Pokémon!$",
"{RIVAL}: All right, Gramps!\\n": "{RIVAL}: Molt bé, avi!\\n",
"Leave it all to me!$": "Deixa-m'ho tot a mi!$",
"{PLAYER}, I hate to say it, but you\\n": "{PLAYER}, em sap greu dir-ho, però\\n",
"won't be necessary for this.\\p": "no ets necessari per a això.\\p",
"You're on your own from here, so\\n": "D'aquí endavant vas sol, així que\\n",
"don't bother calling me!\\p": "no et molestis a trucar-me!\\p",
"And don't try and get my number from\\n": "I no intentis aconseguir el meu número\\n",
"my sister, either.\\p": "de la meva germana, tampoc.\\p",
"I'll tell her not to give it to you,\\n": "Li diré que no te'l doni,\\n",
"{PLAYER}! Hahaha!$": "{PLAYER}! Ha, ha, ha!$",
"{RIVAL}: What, it's only {PLAYER}?\\n": "{RIVAL}: Què, només ets {PLAYER}?\\n",
"Gramps isn't around.$": "L'avi no hi és.$",
"{RIVAL}: Heh, I don't need to be\\n": "{RIVAL}: Bah, jo no necessito ser\\n",
"greedy like you. I'm mature!\\p": "cobdiciós com tu. Jo sóc madur!\\p",
"Go ahead and take it, {PLAYER}!$": "Vinga, queda-te'l, {PLAYER}!$",
"{RIVAL}: My Pokémon looks a lot\\n": "{RIVAL}: El meu Pokémon sembla molt\\n",
"tougher than yours, {PLAYER}.$": "més fort que el teu, {PLAYER}.$",
"There's an e-mail message here.\\p": "Aquí hi ha un correu electrònic.\\p",
"…\\p": "…\\p",
"Finally!\\n": "Per fi!\\n",
"The ultimate trainers of the\\l": "Els millors entrenadors de la\\l",
"Pokémon League are ready to\\l": "Lliga Pokémon estan a punt per\\l",
"take on all comers!\\p": "enfrontar-se a qui vulgui!\\p",
"Bring your best Pokémon and see\\n": "Porta els teus millors Pokémon i mira\\n",
"how you rate as a trainer!\\p": "quin nivell tens com a entrenador!\\p",
"Pokémon League HQ\\n": "Seu de la Lliga Pokémon\\n",
"Indigo Plateau\\p": "Altiplà Indigo\\p",
"Prof. Oak, please visit us!\\n": "Prof. Oak, vingui a veure'ns!\\n",
"…$": "…$",
"Press START to open the MENU!\\p": "Prem START per obrir el MENÚ!\\p",
"The SAVE option is on the MENU.\\n": "L'opció DESAR és al MENÚ.\\n",
"Use it regularly.$": "Fes-la servir sovint.$",
"All Pokémon types have strong and\\n": "Tots els tipus de Pokémon tenen punts\\n",
"weak points against others.$": "forts i febles contra els altres.$",
"I study Pokémon as Prof. Oak's\\n": "Estudio els Pokémon com a ajudant\\n",
"Aide.$": "del Prof. Oak.$",
"Cedar is the newest aide in the lab,\\n": "La Cedar és la nova ajudant del lab,\\n",
"so she is always out running errands.$": "així que sempre està fent encàrrecs.$",
"If I'm being honest, lab work can\\n": "Si he de ser sincer, la feina de lab\\n",
"get a little boring.\\p": "pot ser una mica avorrida.\\p",
"I teased her in the beginning, but\\n": "Al principi me'n reia, però ara\\n",
"now I'm a little jealous that Cedar\\l": "tinc una mica d'enveja que la Cedar\\l",
"had the chance to travel so often!$": "hagi pogut viatjar tant!$",
"Cedar: Hello. Nice to meet you!\\n": "Cedar: Hola. Encantada de conèixer-te!\\n",
"I recently joined Professor Oak's\\l": "Fa poc que m'he incorporat a l'equip\\l",
"team.\\p": "del Professor Oak.\\p",
"I'm excited to work with everyone.$": "Estic il·lusionada de treballar amb tots.$",
"Wow! You defeated the Elite Four?\\n": "Vaja! Has derrotat l'Alt Comandament?\\n",
"That's quite an accomplishment!\\p": "Això és tot un èxit!\\p",
"You know, there's still more Pokémon\\n": "Saps què? Encara hi ha més Pokémon\\n",
"to see out there.\\p": "per veure per aquí fora.\\p",
"This should help you complete your Pokédex!$": "Això t'ajudarà a completar el Pokédex!$",
"{PLAYER} earned the Catching Charm!": "{PLAYER} ha guanyat l'Amulet Captura!",
"Wow! You defeated Professor Oak?\\n": "Vaja! Has derrotat el Professor Oak?\\n",
"Raising Pokémon is just as important\\n": "Criar Pokémon és igual d'important\\n",
"as battling, you know.\\p": "que combatre, saps?\\p",
"This should help you raise new Pokémon!$": "Això t'ajudarà a criar nous Pokémon!$",
"{PLAYER} earned the Oval Charm!": "{PLAYER} ha guanyat l'Amulet Oval!",
"Incredible! You caught them all?\\n": "Increïble! Els has capturat tots?\\n",
"That's an amazing accomplishment!\\p": "Això és un èxit extraordinari!\\p",
"I've heard that Pokémon have rare\\n": "He sentit que els Pokémon tenen\\n",
"variations.\\p": "variants rares.\\p",
"I've never seen one, though...\\p": "Però jo no n'he vist mai cap...\\p",
"This might help you find them!$": "Això potser t'ajudarà a trobar-ne!$",
"{PLAYER} earned the Shiny Charm!": "{PLAYER} ha guanyat l'Amulet Lluent!",
"Cedar: Hi, {PLAYER}!\\n": "Cedar: Hola, {PLAYER}!\\n",
"Stopping by to see the Prof?\\p": "Véns a veure el professor?\\p",
"Oh? You came to see me?$": "Oh? Has vingut a veure'm a mi?$",
"Hmm, I don't have any new items\\n": "Mmm, ara mateix no tinc cap objecte\\n",
"to give you right now.\\p": "nou per donar-te.\\p",
"I'd love to keep hearing about your\\n": "Però m'encantaria continuar sentint\\n",
"adventures, though!\\p": "les teves aventures!\\p",
"If you have a good accomplishment\\n": "Si tens algun bon èxit per\\n",
"to tell me about, I could convince\\l": "explicar-me, podria convèncer\\l",
"Prof. Oak to give you something good!$": "el Prof. Oak que et doni alguna cosa bona!$",
"Cedar: Oh, {PLAYER}!\\n": "Cedar: Oh, {PLAYER}!\\n",
"It's so nice to see you.\\p": "Que bé veure't.\\p",
"I don't have any new items for you\\n": "Aquesta vegada no tinc cap objecte\\n",
"this time, though. Ha!\\p": "nou per tu, però. Ha!\\p",
"You know, when I joined Prof. Oak's\\n": "Saps? Quan vaig entrar al Laboratori\\n",
"Lab, I wasn't happy that I'd spend so\\l": "del Prof. Oak, no m'agradava haver de\\l",
"much time travelling away from it!\\p": "passar tant de temps viatjant fora!\\p",
"But, following your journey was also\\n": "Però seguir el teu viatge també ha\\n",
"an adventure for me!\\p": "estat una aventura per mi!\\p",
"I saw so much of Kanto, and got to\\n": "He vist molt de Kanto i he entès\\n",
"what life as a Trainer must be like.\\p": "com deu ser la vida d'un entrenador.\\p",
"I see now why Prof. Oak gave me that\\n": "Ara entenc per què el Prof. Oak em va\\n",
"assignment.\\p": "encarregar aquella feina.\\p",
"So, thanks for the adventure!$": "Així que gràcies per l'aventura!$",
"It's like an encyclopedia, but the\\n": "És com una enciclopèdia, però les\\n",
"pages are blank.$": "pàgines estan en blanc.$",
"That's Prof. Oak's last Pokémon.$": "És l'últim Pokémon del Prof. Oak.$",
"Oak: Now, {PLAYER}.\\p": "Oak: Molt bé, {PLAYER}.\\p",
"Inside that Pokéball is\\n": "Dins d'aquella Pokéball hi ha\\n",
"one of my Pokémon.\\p": "un dels meus Pokémon.\\p",
"Please take good care of it!$": "Cuida-me'l bé, si us plau!$",
"Oak: If a wild Pokémon appears,\\n": "Oak: Si apareix un Pokémon salvatge,\\n",
"your Pokémon can battle it.\\p": "el teu Pokémon pot combatre-hi.\\p",
"With it at your side, you should be\\n": "Amb ell al teu costat, hauries de\\n",
"able to reach the next town.$": "poder arribar al poble següent.$",
"Oak: {PLAYER}, raise your young\\n": "Oak: {PLAYER}, cria el teu jove\\n",
"Pokémon by making it battle.\\p": "Pokémon fent-lo combatre.\\p",
"It has to battle for it to grow.$": "Ha de combatre per créixer.$",
"Pokémon around the world wait for\\n": "Els Pokémon de tot el món t'esperen,\\n",
"you, {PLAYER}!$": "{PLAYER}!$",
}
