# -*- coding: utf-8 -*-
# Catalan move names. HARD LIMIT: 12 characters (B_EXPANDED_MOVE_NAMES == FALSE).
KIND = 'c'
FILES = ['src/data/text/move_names.h']

T = {
"-": "-",
"Absorb": "Absorció",
"Accelerock": "Accelerroca",
"Acid": "Àcid",
"Acid Armor": "ArmaduraÀcid",
"Acid Spray": "Ruixat Àcid",
"Acrobatics": "Acrobàcies",
"Acupressure": "Acupressió",
"Aerial Ace": "As Aeri",
"Aeroblast": "Aeroblast",
"After You": "Tu Primer",
"Agility": "Agilitat",
"Air Cutter": "Aire Afilat",
"Air Slash": "Tall d'Aire",
"Ally Switch": "Canvi Aliat",
"Amnesia": "Amnèsia",
"Anchor Shot": "Tir d'Àncora",
"AncientPower": "PoderAntic",
"Apple Acid": "Àcid Poma",
"Aqua Jet": "Acuajet",
"Aqua Ring": "Anell Aigua",
"Aqua Tail": "Cua Aquàtica",
"Arm Thrust": "Cop de Braç",
"Aromatherapy": "Aromateràpia",
"AromaticMist": "BoiraAromàt",
"Assist": "Assistència",
"Assurance": "Assegurança",
"Astonish": "Esglai",
"AstrlBarrage": "BarratgAstrl",
"Attack Order": "Ordre Atac",
"Attract": "Atracció",
"Aura Sphere": "Esfera Aura",
"Aura Wheel": "Roda d'Aura",
"Aurora Beam": "Raig Aurora",
"Aurora Veil": "Vel d'Aurora",
"Autotomize": "Autotomia",
"Avalanche": "Allau",
"BabyDollEyes": "UllsdeNina",
"Baddy Bad": "Malícia",
"BanefulBunkr": "BúnquerFatal",
"Barrage": "Bombardeig",
"Barrier": "Barrera",
"Baton Pass": "Relleu",
"Beak Blast": "Bec Explosiu",
"Beat Up": "Pallissa",
"BehemothBash": "CopBehemoth",
"BehemthBlade": "FullaBehemot",
"Belch": "Rot",
"Belly Drum": "Tambor Panxa",
"Bestow": "Ofrena",
"Bide": "Paciència",
"Bind": "Constrenyir",
"Bite": "Mordida",
"Blast Burn": "Anell Igni",
"Blaze Kick": "Puntada Foc",
"Blizzard": "Ventisca",
"Block": "Bloqueig",
"Blue Flare": "Flama Blava",
"Body Press": "Premsa Cos",
"Body Slam": "Cop de Cos",
"Bolt Beak": "Bec Elèctric",
"Bolt Strike": "Atac Elèctr",
"Bone Club": "Os Garrot",
"Bone Rush": "Atac Ossi",
"Bonemerang": "Ossomerang",
"Boomburst": "Estrèpit",
"Bounce": "Bot",
"BouncyBubble": "BombollaBot",
"Branch Poke": "PicaBranca",
"Brave Bird": "Ocell Valent",
"BreakngSwipe": "CopTrencador",
"Brick Break": "Trencateules",
"Brine": "Salmorra",
"BrningJelosy": "GelosiaArdnt",
"Brutal Swing": "Gir Brutal",
"Bubble": "Bombolla",
"Bubble Beam": "RaigBombolla",
"Bug Bite": "Picada Cuc",
"Bug Buzz": "Zumzeig",
"Bulk Up": "Corpulència",
"Bulldoze": "Anivellar",
"Bullet Punch": "Cop de Bala",
"Bullet Seed": "Llavor Bala",
"Burn Up": "Combustió",
"Buzzy Buzz": "Zzzap",
"Calm Mind": "Ment Calmada",
"Camouflage": "Camuflatge",
"Captivate": "Captivar",
"Celebrate": "Celebrar",
"Charge": "Càrrega",
"Charge Beam": "Raig Càrrega",
"Charm": "Encant",
"Chatter": "Xerrameca",
"Chip Away": "Desgast",
"Circle Throw": "LlançCircula",
"Clamp": "Tenalles",
"Clear Smog": "Boira Neta",
"ClngngScales": "EscatsAdhrnt",
"ClngrousSoul": "ÀnimaTenaç",
"Close Combat": "CombatProper",
"Coaching": "Entrenament",
"Coil": "Enroscar",
"Comet Punch": "Cop Cometa",
"Confide": "Confidència",
"Confuse Ray": "Raig Confús",
"Confusion": "Confusió",
"Constrict": "Constrènyer",
"Conversion": "Conversió",
"Conversion 2": "Conversió 2",
"Copycat": "Imitació",
"CoreEnforcer": "NucliImposar",
"CorrosiveGas": "GasCorrosiu",
"Cosmic Power": "Poder Còsmic",
"Cotton Guard": "GuardaCotó",
"Cotton Spore": "Espora Cotó",
"Counter": "Contraatac",
"Court Change": "Canvi Camp",
"Covet": "Cobejar",
"Crabhammer": "MartellCranc",
"CraftyShield": "EscutAstut",
"Cross Chop": "Tall Creuat",
"Cross Poison": "Verí Creuat",
"Crunch": "Triturar",
"Crush Claw": "Urpa Cruel",
"Crush Grip": "Presa Cruel",
"Curse": "Maledicció",
"Cut": "Tallar",
"Dark Pulse": "Onada Fosca",
"Dark Void": "Buit Fosc",
"DarkstLariat": "LlaçFosc",
"DazzlngGleam": "BrillEnlluer",
"Decorate": "Decorar",
"Defend Order": "OrdreDefensa",
"Defense Curl": "Enrotllar",
"Defog": "Esboirar",
"Destiny Bond": "Llaç Fatal",
"Detect": "Detectar",
"DiamondStorm": "TempstaDiamn",
"Dig": "Cavar",
"Disable": "Anul·lar",
"Discharge": "Descàrrega",
"DisrmngVoice": "VeuDesarmant",
"Dive": "Capbussada",
"Dizzy Punch": "Cop Marejant",
"Doom Desire": "Desig Fatal",
"Double Hit": "Doble Cop",
"Double Kick": "DoblePuntada",
"Double Slap": "Doble Bufeta",
"Double Team": "Doble Equip",
"Double-Edge": "Doble Fil",
"Draco Meteor": "Meteor Draco",
"Dragon Claw": "Urpa de Drac",
"Dragon Dance": "DansaDrac",
"Dragon Darts": "DardsDrac",
"Dragon Pulse": "Onada Drac",
"Dragon Rage": "Ira de Drac",
"Dragon Rush": "EnvitDrac",
"Dragon Tail": "Cua de Drac",
"DragonAscent": "AscensDrac",
"DragonBreath": "AlèDeDrac",
"DragonEnergy": "EnergiaDrac",
"DragonHammer": "MartellDrac",
"Drain Punch": "Cop Drenant",
"DrainingKiss": "BesDrenant",
"Dream Eater": "Menjasomnis",
"Drill Peck": "Bec Trepant",
"Drill Run": "Trepant",
"Drum Beating": "TocTambor",
"Dual Chop": "Doble Tall",
"DualWingbeat": "DobleAleteig",
"DublIronBash": "CopFerroDobl",
"DynamicPunch": "CopDinàmic",
"DynamxCannon": "CanóDinamax",
"Earth Power": "Poder Terra",
"Earthquake": "Terratrèmol",
"Echoed Voice": "Veu d'Eco",
"Eerie Spell": "EncísSinistr",
"EerieImpulse": "ImpulsSinist",
"Egg Bomb": "Bomba Ou",
"ElctrcTrrain": "CampElèctric",
"Electrify": "Electrificar",
"Electro Ball": "Bola Elèctri",
"Electroweb": "Electroxarxa",
"Embargo": "Embargament",
"Ember": "Brasa",
"Encore": "Repetició",
"Endeavor": "Esforç",
"Endure": "Aguantar",
"Energy Ball": "Bola Energia",
"Entrainment": "Arrossegar",
"Eruption": "Erupció",
"Eternabeam": "Raig Etern",
"ExpandngForc": "ForçaExpansv",
"Explosion": "Explosió",
"Extrasensory": "Extrasensori",
"ExtremeSpeed": "VelocitatMàx",
"Facade": "Façana",
"Fairy Lock": "Pany de Fada",
"Fairy Wind": "Vent de Fada",
"Fake Out": "Enganyada",
"Fake Tears": "PlorFals",
"FalsSurrendr": "RendicióFals",
"False Swipe": "Cop Fals",
"FeatherDance": "DansaPloma",
"Feint": "Fingiment",
"Feint Attack": "Atac Fingit",
"Fell Stinger": "Fibló Mortal",
"Fiery Dance": "Dansa de Foc",
"Fiery Wrath": "Ira de Foc",
"Final Gambit": "Gambit Final",
"Fire Blast": "Ràfega Foc",
"Fire Fang": "Ullal de Foc",
"Fire Lash": "Fuet de Foc",
"Fire Pledge": "Jurament Foc",
"Fire Punch": "Cop de Foc",
"Fire Spin": "Remolí Foc",
"FishiousRend": "TallBranquia",
"Fissure": "Fissura",
"Flail": "Fuetejar",
"Flame Burst": "Esclat Flama",
"Flame Charge": "CàrregaFlama",
"Flame Wheel": "Roda de Foc",
"Flamethrower": "Llançaflames",
"Flare Blitz": "Envit Ardent",
"Flash": "Flaix",
"Flash Cannon": "Canó Flaix",
"Flatter": "Afalagar",
"Fleur Cannon": "Canó Floral",
"Fling": "Llançar",
"Flip Turn": "Gir Aquàtic",
"Floaty Fall": "Caiguda Suau",
"FloralHealng": "CuraFloral",
"FlowerShield": "EscutFloral",
"Fly": "Volar",
"Flying Press": "PremsaVolant",
"Focus Blast": "Ràfega Focus",
"Focus Energy": "Focalitzar",
"Focus Punch": "CopFocalitzt",
"Follow Me": "Segueix-me",
"Force Palm": "PalmellForça",
"Foresight": "Clarividènci",
"Forest'sCurs": "MaledicBosc",
"Foul Play": "Joc Brut",
"Freeze Shock": "Xoc Glaçat",
"Freeze-Dry": "Liofilitzar",
"FreezngGlare": "MiradaGelada",
"Freezy Frost": "Gebre Glaçat",
"Frenzy Plant": "PlantaFeroç",
"Frost Breath": "Alè Gelat",
"FrstImpressn": "PrimeraImprs",
"Frustration": "Frustració",
"Fury Attack": "Atac Furiós",
"Fury Cutter": "Tall Furiós",
"Fury Swipes": "UrpadesFúria",
"Fusion Bolt": "Llamp Fusió",
"Fusion Flare": "Flama Fusió",
"Future Sight": "Premonició",
"Gastro Acid": "Àcid Gàstric",
"Gear Grind": "Engranatge",
"Gear Up": "Engranar",
"Geomancy": "Geomància",
"Giga Drain": "Gigadrenatge",
"Giga Impact": "Gigaimpacte",
"GlacialLance": "LlançaGlacil",
"Glaciate": "Glaçar",
"Glare": "Mirada Fixa",
"Glitzy Glow": "LlumBrillant",
"Grass Knot": "Nus d'Herba",
"Grass Pledge": "JuramentHerb",
"GrassWhistle": "XiuletHerba",
"Grassy Glide": "PlanejaHerba",
"Grav Apple": "Poma Greu",
"Gravity": "Gravetat",
"Growl": "Rugit",
"Growth": "Creixement",
"GrssyTerrain": "CampHerbós",
"Grudge": "Rancúnia",
"Guard Split": "PartirGuarda",
"Guard Swap": "CanviGuarda",
"Guillotine": "Guillotina",
"Gunk Shot": "TirdeBrossa",
"Gust": "Ràfega",
"Gyro Ball": "Bola Giro",
"Hail": "Calamarsa",
"Hammer Arm": "Braç Martell",
"Happy Hour": "Hora Feliç",
"Harden": "Endurir",
"Haze": "Bruma",
"Head Charge": "CàrregaCap",
"Head Smash": "Xoc de Cap",
"Headbutt": "Cop de Cap",
"Heal Bell": "Campana Cura",
"Heal Block": "Anticura",
"Heal Order": "Ordre Cura",
"Heal Pulse": "Onada Cura",
"Healing Wish": "DesigDeCura",
"Heart Stamp": "Segell Cor",
"Heart Swap": "Canvi de Cor",
"Heat Crash": "Xoc Tòrrid",
"Heat Wave": "Onada Calor",
"Heavy Slam": "Cop Pesant",
"Helping Hand": "Cop de Mà",
"Hex": "Malefici",
"Hidden Power": "Poder Ocult",
"HighHorsepwr": "CavallsForça",
"HighJumpKick": "PuntadaAlta",
"Hold Back": "Contenir",
"Hold Hands": "Donar Mans",
"Hone Claws": "EsmolarUrpes",
"Horn Attack": "Atac de Corn",
"Horn Drill": "Corn Trepant",
"Horn Leech": "Corn Drenant",
"Howl": "Udol",
"Hurricane": "Huracà",
"Hydro Cannon": "Hidrocanó",
"Hydro Pump": "Hidrobomba",
"Hyper Beam": "Hiperraig",
"Hyper Fang": "Hiperullal",
"Hyper Voice": "Hiperveu",
"Hypnosis": "Hipnosi",
"HyprspceFury": "FúriaHiprspc",
"HyprspceHole": "ForatHiprspc",
"Ice Ball": "Bola de Gel",
"Ice Beam": "Raig de Gel",
"Ice Burn": "Cremada Gel",
"Ice Fang": "Ullal de Gel",
"Ice Hammer": "Martell Gel",
"Ice Punch": "Cop de Gel",
"Ice Shard": "Fragment Gel",
"Icicle Crash": "CopCaramell",
"Icicle Spear": "LlançCaramll",
"Icy Wind": "Vent Gelat",
"Imprison": "Empresonar",
"Incinerate": "Incinerar",
"Inferno": "Infern",
"Infestation": "Infestació",
"Ingrain": "Arrelar",
"Instruct": "Instruir",
"Ion Deluge": "Diluvi Iònic",
"Iron Defense": "DefensaFerro",
"Iron Head": "Cap de Ferro",
"Iron Tail": "Cua de Ferro",
"Jaw Lock": "Mandíbula",
"Judgment": "Judici",
"Jump Kick": "Puntada Salt",
"JungleHealng": "CuraSelva",
"Karate Chop": "CopdeKarate",
"Kinesis": "Cinesi",
"King'sShield": "EscutReial",
"Knock Off": "Desarmar",
"Land's Wrath": "IraTerrestre",
"Laser Focus": "Focus Làser",
"Lash Out": "Arremetre",
"Last Resort": "Últim Recurs",
"Lava Plume": "Plomall Lava",
"Leaf Blade": "FullaAfilada",
"Leaf Storm": "TempestaFull",
"Leaf Tornado": "TornadoFulla",
"Leafage": "Fullatge",
"Leech Life": "Xuclavida",
"Leech Seed": "Llavor Xucla",
"Leer": "Ullada",
"Lick": "Llepada",
"Life Dew": "Rosada Vital",
"Light Screen": "PantallaLlum",
"LightOfRuin": "LlumdeRuïna",
"Liquidation": "Liquidació",
"Lock-On": "Fixar Blanc",
"Lovely Kiss": "BesEncisador",
"Low Kick": "PuntadaBaixa",
"Low Sweep": "Escombrada",
"Lucky Chant": "Cant de Sort",
"Lunar Dance": "Dansa Lunar",
"Lunge": "Escomesa",
"Luster Purge": "PurgaLluent",
"Mach Punch": "Cop Mach",
"Magic Coat": "Capa Màgica",
"Magic Powder": "Pols Màgica",
"Magic Room": "Sala Màgica",
"Magical Leaf": "Fulla Màgica",
"Magma Storm": "TempestMagma",
"Magnet Bomb": "Bomba Imant",
"Magnet Rise": "Levitació",
"MagneticFlux": "FluxMagnètic",
"Magnitude": "Magnitud",
"Mat Block": "Escut Estora",
"Me First": "Jo Primer",
"Mean Look": "Mala Mirada",
"Meditate": "Meditar",
"Mega Drain": "Megadrenatge",
"Mega Kick": "Megapuntada",
"Mega Punch": "Megacop",
"Megahorn": "Megacorn",
"Memento": "Llegat",
"Metal Burst": "EsclatMetall",
"Metal Claw": "UrpaMetall",
"Metal Sound": "So Metàl·lic",
"Meteor Beam": "Raig Meteor",
"Meteor Mash": "Cop Meteor",
"MeteorAssalt": "AssaltMeteor",
"Metronome": "Metrònom",
"Milk Drink": "Beure Llet",
"Mimic": "Mimetitzar",
"Mind Blown": "Ment Volada",
"Mind Reader": "Llegir Ment",
"Minimize": "Minimitzar",
"Miracle Eye": "Ull Miracle",
"Mirror Coat": "Capa Mirall",
"Mirror Move": "ReflexMirall",
"Mirror Shot": "TirdeMirall",
"Mist": "Boira",
"Mist Ball": "Bola Boira",
"MistyTerrain": "CampBoirós",
"Moonblast": "Llunablast",
"MoongestBeam": "RaigLunar",
"Moonlight": "LlumDeLluna",
"Morning Sun": "Sol Matinal",
"MstyExplsion": "ExplosióMíst",
"Mud Bomb": "BombaFang",
"Mud Shot": "Tir de Fang",
"Mud Sport": "Bany de Fang",
"Mud-Slap": "CopdeFang",
"Muddy Water": "AiguaTèrbola",
"Multi-Attack": "Multiatac",
"MysticalFire": "FocMístic",
"Nasty Plot": "Pla Maliciós",
"Natur'sMadns": "FúriaNatura",
"Natural Gift": "Do Natural",
"Nature Power": "PoderNatural",
"Needle Arm": "Braç Agulla",
"Night Daze": "Atordir Nit",
"Night Shade": "OmbraNocturn",
"Night Slash": "Tall Nocturn",
"Nightmare": "Malson",
"No Retreat": "Sense Retir",
"Noble Roar": "Rugit Noble",
"Nuzzle": "Fregada",
"OblivionWing": "AladOblit",
"Obstruct": "Obstruir",
"Octazooka": "Octazooka",
"Octolock": "Octopresa",
"Odor Sleuth": "Rastreig",
"Ominous Wind": "Vent Ominós",
"Origin Pulse": "OnadaOrigen",
"Outrage": "Enfuriment",
"Overdrive": "Sobrecàrrega",
"Overheat": "Sobrescalfar",
"Pain Split": "Partir Dolor",
"ParabolcChrg": "CàrregaParab",
"Parting Shot": "TirComiat",
"Pay Day": "Dia de Paga",
"Payback": "Revenja",
"Peck": "Picotada",
"Perish Song": "Cant Mortal",
"Petal Dance": "DansaPètals",
"PetalBlizzrd": "TempstaPètal",
"PhantomForce": "ForçaFantasm",
"PhotonGeyser": "GèiserFotons",
"Pika Papow": "PikaPapow",
"Pin Missile": "MíssilAgulla",
"Plasma Fists": "PunysPlasma",
"Play Nice": "Jugar Net",
"Play Rough": "Jugar Brut",
"Pluck": "Espicossar",
"Poison Fang": "Ullal Verí",
"Poison Gas": "Gas Verinós",
"Poison Jab": "Cop de Verí",
"Poison Sting": "Fibló Verí",
"Poison Tail": "Cua Verinosa",
"PoisonPowder": "PolsVerinosa",
"Pollen Puff": "BolaPol·len",
"Poltergeist": "Poltergeist",
"Pound": "Cop Sec",
"Powder": "Pols",
"Powder Snow": "Neu en Pols",
"Power Gem": "Gemma Poder",
"Power Split": "PartirPoder",
"Power Swap": "Canvi Poder",
"Power Trick": "TrucDePoder",
"Power Trip": "Viatge Poder",
"Power Whip": "FuetDePoder",
"PowerUpPunch": "CopPotenciat",
"PrcipceBldes": "FullesAbisme",
"Present": "Regal",
"Protect": "Protegir",
"PrsmaticLasr": "LàserPrismàt",
"Psybeam": "Psicoraig",
"Psych Up": "Autosuggest",
"PsychcTrrain": "CampPsíquic",
"Psychic": "Psíquic",
"PsychicFangs": "UllalsPsíqui",
"Psycho Boost": "PsicoImpuls",
"Psycho Cut": "Psicotall",
"Psycho Shift": "Psicocanvi",
"Psyshock": "Psicoxoc",
"Psystrike": "Psicocop",
"Psywave": "Psicoonada",
"Punishment": "Càstig",
"Purify": "Purificar",
"Pursuit": "Persecució",
"Pyro Ball": "BolaPiro",
"Quash": "Suprimir",
"Quick Attack": "Atac Ràpid",
"Quick Guard": "GuardaRàpida",
"Quiver Dance": "DansaAleteig",
"Rage": "Ràbia",
"Rage Powder": "PolsDeRàbia",
"Rain Dance": "Dansa Pluja",
"Rapid Spin": "Gir Ràpid",
"Razor Leaf": "FullaNavalla",
"Razor Shell": "Closca Tall",
"Razor Wind": "Vent Navalla",
"Recover": "Recuperar",
"Recycle": "Reciclar",
"Reflect": "Reflex",
"Reflect Type": "ReflexTipus",
"Refresh": "Refrescar",
"Relic Song": "CantRelíquia",
"Rest": "Descansar",
"Retaliate": "Represàlia",
"Return": "Retorn",
"Revenge": "Venjança",
"Reversal": "Inversió",
"RisngVoltage": "VoltatgeAsc",
"Roar": "Bramul",
"Roar of Time": "BramDelTemps",
"Rock Blast": "Ràfega Roca",
"Rock Climb": "Escalar Roca",
"Rock Polish": "Polir Roca",
"Rock Slide": "AllauDeRoca",
"Rock Smash": "Trencar Roca",
"Rock Throw": "Llançar Roca",
"Rock Tomb": "TombaDeRoca",
"Rock Wrecker": "TrencaRoques",
"Role Play": "Joc de Rol",
"Rolling Kick": "PuntadaGir",
"Rollout": "Rodolar",
"Roost": "Aixoplugar",
"Rototiller": "Motocultor",
"Round": "Cantúria",
"RvlationDnce": "DansaRevelac",
"Sacred Fire": "Foc Sagrat",
"Sacred Sword": "EspasaSagrad",
"Safeguard": "Salvaguarda",
"Sand Attack": "AtacDeSorra",
"Sand Tomb": "Tomba Sorra",
"Sandstorm": "TempstaSorra",
"Sappy Seed": "Llavor Saba",
"Scald": "Escaldar",
"Scale Shot": "TirdEscates",
"Scary Face": "CaraEspantos",
"ScorchngSnds": "SorresArdent",
"Scratch": "Esgarrapada",
"Screech": "Xiscle",
"Searing Shot": "Tir Roent",
"Secret Power": "Poder Secret",
"Secret Sword": "EspasaSecret",
"Seed Bomb": "Bomba Llavor",
"Seed Flare": "FulgorLlavor",
"Seismic Toss": "Llanç Sísmic",
"SelfDestruct": "Autodestruir",
"Shadow Ball": "Bola Ombra",
"Shadow Bone": "Os d'Ombra",
"Shadow Claw": "Urpa d'Ombra",
"Shadow Force": "Força Ombra",
"Shadow Punch": "Cop d'Ombra",
"Shadow Sneak": "OmbraFurtiva",
"Sharpen": "Esmolar",
"Sheer Cold": "Fred Absolut",
"Shell Smash": "TrencaClosca",
"Shell Trap": "TrampaClosca",
"ShellSideArm": "ArmaClosca",
"Shift Gear": "CanviarMarxa",
"Shock Wave": "Onada de Xoc",
"Shore Up": "Reforçar",
"Signal Beam": "Raig Senyal",
"Silver Wind": "VentdArgent",
"Simple Beam": "Raig Simple",
"Sing": "Cantar",
"Sizzly Slide": "LliscadaFoc",
"Sketch": "Esbós",
"Skill Swap": "CanviHabilit",
"SkitterSmack": "CopFurtiu",
"Skull Bash": "Cop de Crani",
"Sky Attack": "Atac Aeri",
"Sky Drop": "Caiguda Cel",
"Sky Uppercut": "Ganxo al Cel",
"Slack Off": "Relaxar-se",
"Slam": "Atonyinar",
"Slash": "Tall",
"Sleep Powder": "PolsSomnífer",
"Sleep Talk": "ParlarDormit",
"Sludge": "Residu",
"Sludge Bomb": "Bomba Residu",
"Sludge Wave": "Onada Residu",
"Smack Down": "Abatre",
"Smart Strike": "Cop Astut",
"SmellngSalts": "SalsAromàtic",
"Smog": "Fumarada",
"Smokescreen": "Cortina Fum",
"Snap Trap": "Parany",
"Snarl": "Rondinar",
"Snatch": "Arrabassar",
"Snipe Shot": "Tir Precís",
"Snore": "Roncar",
"SnsteelStrke": "CopAcerSagrt",
"Soak": "Xopar",
"Soft-Boiled": "Ou Passat",
"Solar Beam": "Raig Solar",
"Solar Blade": "Fulla Solar",
"Sonic Boom": "Sonicbum",
"Spacial Rend": "TallEspacial",
"Spark": "Espurna",
"SparklngAria": "ÀriaEspurnjt",
"SparklySwirl": "RemolíMàgic",
"SpectrlThief": "LladreEspect",
"Speed Swap": "CanviVelocit",
"Spider Web": "Teranyina",
"Spike Cannon": "CanóPunxes",
"Spikes": "Punxes",
"Spiky Shield": "EscutPunxes",
"Spirit Break": "TrencarÀnima",
"SpiritShackl": "CadenaÀnima",
"Spit Up": "Escopir",
"Spite": "Rancor",
"Splash": "Esquitxada",
"SplishySplsh": "XipXapElèctr",
"Spore": "Espora",
"Spotlight": "Focus",
"Stealth Rock": "RoquesTrampa",
"SteamErption": "ErupcióVapor",
"Steamroller": "Piconadora",
"Steel Beam": "Raig d'Acer",
"Steel Roller": "RodetAcer",
"Steel Wing": "Ala d'Acer",
"Sticky Web": "XarxaViscosa",
"StmpngTantrm": "RabiolaCops",
"Stockpile": "Emmagatzemar",
"Stomp": "Trepitjada",
"Stone Edge": "Fil de Pedra",
"Stored Power": "PoderReservt",
"Storm Throw": "LlançTempsta",
"StrangeSteam": "VaporEstrany",
"Strength": "Força",
"Strength Sap": "XuclarForça",
"String Shot": "Tir de Seda",
"Struggle": "Forcejar",
"Struggle Bug": "CucForcejant",
"Stuff Cheeks": "OmplirGaltes",
"Stun Spore": "EsporaParali",
"Submission": "Submissió",
"Substitute": "Substitut",
"Sucker Punch": "Cop Traïdor",
"Sunny Day": "Dia de Sol",
"Super Fang": "Superullal",
"Superpower": "Superforça",
"Supersonic": "Supersònic",
"Surf": "Surf",
"SurgngStrkes": "CopsTorrenti",
"Swagger": "Fatxenderia",
"Swallow": "Empassar",
"Sweet Kiss": "Bes Dolç",
"Sweet Scent": "Aroma Dolç",
"Swift": "Rapidesa",
"Switcheroo": "Trapelleria",
"Swords Dance": "Dansa Espasa",
"Synchronoise": "Sincronoise",
"Synthesis": "Síntesi",
"Tackle": "Placatge",
"Tail Glow": "CuaLluminosa",
"Tail Slap": "Cop de Cua",
"Tail Whip": "Moure la Cua",
"Tailwind": "Vent de Cua",
"Take Down": "Envestida",
"Tar Shot": "TirQuitrà",
"Taunt": "Mofa",
"Tearful Look": "MiradaPlorós",
"Teatime": "Hora del Te",
"Techno Blast": "Tecnoràfega",
"Teeter Dance": "DansaTrontll",
"Telekinesis": "Telecinesi",
"Teleport": "Teleportació",
"TerrainPulse": "OnadaDeCamp",
"Thief": "Lladre",
"ThnderusKick": "PuntadaTrò",
"ThousndArrws": "MilFletxes",
"ThousndWaves": "MilOnades",
"Thrash": "Fúria",
"Throat Chop": "Cop de Gola",
"Thunder": "Tro",
"Thunder Cage": "Gàbia Elèctr",
"Thunder Fang": "Ullal Elèctr",
"Thunder Wave": "Onada Tro",
"ThunderPunch": "CopElèctric",
"ThunderShock": "Xoc Elèctric",
"Thunderbolt": "Llampec",
"Tickle": "Pessigolles",
"Topsy-Turvy": "Capgirar",
"Torment": "Turment",
"Toxic": "Tòxic",
"Toxic Spikes": "PunxesTòxiqu",
"Toxic Thread": "Fil Tòxic",
"Transform": "Transformar",
"Tri Attack": "Triatac",
"Trick": "Truc",
"Trick Room": "SalaDeTrucs",
"TrickOrTreat": "TrucoTracte",
"Triple Axel": "Triple Axel",
"Triple Kick": "TriplePuntad",
"Trop Kick": "PuntadaTropi",
"Trump Card": "Carta Trumfo",
"Twineedle": "Doble Agulla",
"Twister": "Cicló",
"U-turn": "Gir en U",
"Uproar": "Aldarull",
"V-create": "V-create",
"Vacuum Wave": "Onada Buit",
"VeeveeVolley": "VeeveeVolea",
"Venom Drench": "BanyVerinós",
"Venoshock": "Verinoxoc",
"Vine Whip": "Fuet Vegetal",
"Vise Grip": "PresaTenalla",
"Vital Throw": "Llanç Vital",
"Volt Switch": "Canvi Volt",
"Volt Tackle": "PlacatgeVolt",
"Wake-Up Slap": "BufetadaDesp",
"Water Gun": "PistolaAigua",
"Water Pledge": "JuramentAigu",
"Water Pulse": "Onada Aigua",
"Water Sport": "Bany d'Aigua",
"Water Spout": "Brollador",
"Waterfall": "Cascada",
"WatrShuriken": "ShurikenAigu",
"Weather Ball": "Bola Clima",
"Whirlpool": "Remolí",
"Whirlwind": "Terbolí",
"Wicked Blow": "Cop Malèfic",
"Wide Guard": "Guarda Ampla",
"Wild Charge": "CàrregaSalvj",
"Will-o-Wisp": "Foc Follet",
"Wing Attack": "Atac d'Ala",
"Wish": "Desig",
"Withdraw": "Refugiar-se",
"Wonder Room": "Sala Prodigi",
"Wood Hammer": "MartellFusta",
"Work Up": "Encoratjar",
"Worry Seed": "LlavorNeguit",
"Wrap": "Embolicar",
"Wring Out": "Escórrer",
"X-Scissor": "Tisores X",
"Yawn": "Badall",
"Zap Cannon": "Electrocanó",
"Zen Headbutt": "CopZen",
"Zing Zap": "Zapzing",
"Zippy Zap": "ZipZap",
}
