# -*- coding: utf-8 -*-
"""Catalan: strings.c part 4 - shop/BP lists (kept consistent with the item and
move names chosen in map_items.py / map_move_names.py) plus leftovers.
Also finishes the translatable met_locations entries."""
KIND = 'c'
FILES = ['src/strings.c', 'src/data/text/met_locations.h']

T = {
# ---- leftovers ----
"Egg": "Ou",
"National": "Nacional",
"{PKMN} type & No.": "Tipus i núm. {PKMN}",
"BP": "PC",
"  5BP": "  5PC",
"10BP": "10PC",
"15BP": "15PC",
"Yay{EMOJI_BIGSMILE}": "Visca{EMOJI_BIGSMILE}",
"I'll battle now!": "Combatré ara mateix!",
"I won!": "He guanyat!",
"I lost!": "He perdut!",
"I won't tell.": "No ho penso dir.",
"slippery": "llefiscós",
"roundish": "rodonet",
"wham-ish": "contundent",
"shiny": "lluent",
"sticky": "enganxós",
"pointy": "punxegut",
"{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BP": "{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PC",
"W/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  Record/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}": "V/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  Rècord/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}",
"W:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  L:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}": "V:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  D:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}",

# ---- item names used standalone in strings.c ----
"DeepSeaTooth": "Dent Abissal",
"DeepSeaScale": "Escata Abissal",
"Blue Flute": "Flauta Blava",
"Yellow Flute": "Flauta Groga",
"Red Flute": "Flauta Verm.",
"White Flute": "Flauta Blanca",
"Black Flute": "Flauta Negra",
"Claw Fossil": "Fòssil Urpa",
"Root Fossil": "Fòssil Arrel",
"Helix Fossil": "Fòssil Hèlix",
"Dome Fossil": "Fòssil Cúpula",
"Old Amber": "Ambre Antic",

# ---- herb shop list ----
"Energypowder{CLEAR_TO 114}{FONT_SMALL}50": "Polsenergia{CLEAR_TO 114}{FONT_SMALL}50",
"Energy Root{CLEAR_TO 114}{FONT_SMALL}80": "Arrel Energia{CLEAR_TO 114}{FONT_SMALL}80",
"Heal Powder{CLEAR_TO 114}{FONT_SMALL}50": "Pols Curativa{CLEAR_TO 114}{FONT_SMALL}50",
"Revival Herb{CLEAR_TO 108}{FONT_SMALL}300": "Herba Revifant{CLEAR_TO 108}{FONT_SMALL}300",
"Protein{CLEAR_TO 99}{FONT_SMALL}1,000": "Proteïna{CLEAR_TO 99}{FONT_SMALL}1.000",
"Iron{CLEAR_TO 99}{FONT_SMALL}1,000": "Ferro{CLEAR_TO 99}{FONT_SMALL}1.000",
"Carbos{CLEAR_TO 99}{FONT_SMALL}1,000": "Carbs{CLEAR_TO 99}{FONT_SMALL}1.000",
"Calcium{CLEAR_TO 99}{FONT_SMALL}1,000": "Calci{CLEAR_TO 99}{FONT_SMALL}1.000",
"Zinc{CLEAR_TO 99}{FONT_SMALL}1,000": "Zinc{CLEAR_TO 99}{FONT_SMALL}1.000",
"HP Up{CLEAR_TO 99}{FONT_SMALL}1,000": "Més PS{CLEAR_TO 99}{FONT_SMALL}1.000",
"PP Up{CLEAR_TO 99}{FONT_SMALL}3,000": "Més PP{CLEAR_TO 99}{FONT_SMALL}3.000",

# ---- BP item exchange ----
"Razor Fang{CLEAR_TO 0x5E}48BP": "Ullal Afilat{CLEAR_TO 0x5E}48PC",
"Razor Claw{CLEAR_TO 0x5E}48BP": "Urpa Afilada{CLEAR_TO 0x5E}48PC",
"Choice Specs{CLEAR_TO 0x5E}48BP": "Ulleres Tria{CLEAR_TO 0x5E}48PC",
"Choice Scarf{CLEAR_TO 0x5E}48BP": "Mocador Tria{CLEAR_TO 0x5E}48PC",
"Muscle Band{CLEAR_TO 0x5E}48BP": "Cinta Múscul{CLEAR_TO 0x5E}48PC",
"Life Orb{CLEAR_TO 0x5E}48BP": "Orbe Vital{CLEAR_TO 0x5E}48PC",
"Power Herb{CLEAR_TO 0x5E}32BP": "Herba Poder{CLEAR_TO 0x5E}32PC",
"Wise Glasses{CLEAR_TO 0x5E}48BP": "Ulleres Sàvies{CLEAR_TO 0x5E}48PC",
"Red Card{CLEAR_TO 0x5E}16BP": "Targeta Roja{CLEAR_TO 0x5E}16PC",
"Power Anklet{CLEAR_TO 0x5E}16BP": "Anella Poder{CLEAR_TO 0x5E}16PC",
"Power Bracer{CLEAR_TO 0x5E}16BP": "Braçal Poder{CLEAR_TO 0x5E}16PC",
"Power Belt{CLEAR_TO 0x5E}16BP": "Cinturó Poder{CLEAR_TO 0x5E}16PC",
"Power Band{CLEAR_TO 0x5E}16BP": "Cinta Poder{CLEAR_TO 0x5E}16PC",
"Power Weight{CLEAR_TO 0x5E}16BP": "Pes Poder{CLEAR_TO 0x5E}16PC",
"Power Lens{CLEAR_TO 0x5E}16BP": "Lent Poder{CLEAR_TO 0x5E}16PC",
"HP Candy{CLEAR_TO 0x5E}24BP": "Caramel PS{CLEAR_TO 0x5E}24PC",
"Attack Candy{CLEAR_TO 0x5E}24BP": "Caramel Atac{CLEAR_TO 0x5E}24PC",
"Defense Candy{CLEAR_TO 0x5E}24BP": "Caramel Def.{CLEAR_TO 0x5E}24PC",
"Sp. Atk Candy{CLEAR_TO 0x5E}24BP": "Caramel At.Esp{CLEAR_TO 0x5E}24PC",
"Sp. Def Candy{CLEAR_TO 0x5E}24BP": "Caramel Df.Esp{CLEAR_TO 0x5E}24PC",
"Speed Candy{CLEAR_TO 0x5E}24BP": "Caramel Vel.{CLEAR_TO 0x5E}24PC",
"Max Candy{CLEAR_TO 0x5E}64BP": "Caramel Màx.{CLEAR_TO 0x5E}64PC",
"Reset Candy{CLEAR_TO 0x5E}8BP": "Caramel Zero{CLEAR_TO 0x5E}8PC",
"Kiss Poster{CLEAR_TO 0x5E}16BP": "Pòster Bes{CLEAR_TO 0x5E}16PC",
"Kiss Cushion{CLEAR_TO 0x5E}32BP": "Coixí Bes{CLEAR_TO 0x5E}32PC",
"Smoochum Doll{CLEAR_TO 0x5E}32BP": "Nina Smoochum{CLEAR_TO 0x5E}32PC",
"Togepi Doll{CLEAR_TO 0x5E}48BP": "Nina Togepi{CLEAR_TO 0x5E}48PC",
"Cyndaquil Doll{CLEAR_TO 0x5E}80BP": "Nina Cyndaquil{CLEAR_TO 0x5E}80PC",
"Chikorita Doll{CLEAR_TO 0x5E}80BP": "Nina Chikorita{CLEAR_TO 0x5E}80PC",
"Totodile Doll{CLEAR_TO 0x5E}80BP": "Nina Totodile{CLEAR_TO 0x5E}80PC",
"Protein{CLEAR_TO 0x64}1BP": "Proteïna{CLEAR_TO 0x64}1PC",
"Calcium{CLEAR_TO 0x64}1BP": "Calci{CLEAR_TO 0x64}1PC",
"Iron{CLEAR_TO 0x64}1BP": "Ferro{CLEAR_TO 0x64}1PC",
"Zinc{CLEAR_TO 0x64}1BP": "Zinc{CLEAR_TO 0x64}1PC",
"Carbos{CLEAR_TO 0x64}1BP": "Carbs{CLEAR_TO 0x64}1PC",
"HP Up{CLEAR_TO 0x64}1BP": "Més PS{CLEAR_TO 0x64}1PC",
"Leftovers{CLEAR_TO 0x5E}48BP": "Restes{CLEAR_TO 0x5E}48PC",
"White Herb{CLEAR_TO 0x5E}48BP": "Herba Blanca{CLEAR_TO 0x5E}48PC",
"Quick Claw{CLEAR_TO 0x5E}48BP": "Urpa Ràpida{CLEAR_TO 0x5E}48PC",
"Mental Herb{CLEAR_TO 0x5E}48BP": "Herba Mental{CLEAR_TO 0x5E}48PC",
"Brightpowder{CLEAR_TO 0x5E}64BP": "Pols Brillant{CLEAR_TO 0x5E}64PC",
"Choice Band{CLEAR_TO 0x5E}64BP": "Cinta Tria{CLEAR_TO 0x5E}64PC",
"King's Rock{CLEAR_TO 0x5E}64BP": "Roca Reial{CLEAR_TO 0x5E}64PC",
"Focus Band{CLEAR_TO 0x5E}64BP": "Cinta Focus{CLEAR_TO 0x5E}64PC",
"Scope Lens{CLEAR_TO 0x5E}64BP": "Lupa Precisió{CLEAR_TO 0x5E}64PC",
"Ability Capsule{CLEAR_TO 0x64}50BP": "Càpsula Habil.{CLEAR_TO 0x64}50PC",
"Ability Patch{CLEAR_TO 0x64}200BP": "Pegat Habil.{CLEAR_TO 0x64}200PC",
"Adamant Mint{CLEAR_TO 0x64}50BP": "Menta Ferma{CLEAR_TO 0x64}50PC",
"Bold Mint{CLEAR_TO 0x64}50BP": "Menta Audaç{CLEAR_TO 0x64}50PC",
"Brave Mint{CLEAR_TO 0x64}50BP": "Menta Valenta{CLEAR_TO 0x64}50PC",
"Calm Mint{CLEAR_TO 0x64}50BP": "Menta Calmada{CLEAR_TO 0x64}50PC",
"Careful Mint{CLEAR_TO 0x64}50BP": "Menta Curosa{CLEAR_TO 0x64}50PC",
"Gentle Mint{CLEAR_TO 0x64}50BP": "Menta Amable{CLEAR_TO 0x64}50PC",
"Hasty Mint{CLEAR_TO 0x64}50BP": "Menta Precip.{CLEAR_TO 0x64}50PC",
"Impish Mint{CLEAR_TO 0x64}50BP": "Menta Pícara{CLEAR_TO 0x64}50PC",
"Jolly Mint{CLEAR_TO 0x64}50BP": "Menta Alegre{CLEAR_TO 0x64}50PC",
"Lax Mint{CLEAR_TO 0x64}50BP": "Menta Fluixa{CLEAR_TO 0x64}50PC",
"Lonely Mint{CLEAR_TO 0x64}50BP": "Menta Solit.{CLEAR_TO 0x64}50PC",
"Mild Mint{CLEAR_TO 0x64}50BP": "Menta Suau{CLEAR_TO 0x64}50PC",
"Modest Mint{CLEAR_TO 0x64}50BP": "Menta Modesta{CLEAR_TO 0x64}50PC",
"Naive Mint{CLEAR_TO 0x64}50BP": "Menta Ingènua{CLEAR_TO 0x64}50PC",
"Naughty Mint{CLEAR_TO 0x64}50BP": "Menta Murri{CLEAR_TO 0x64}50PC",
"Quiet Mint{CLEAR_TO 0x64}50BP": "Menta Tranq.{CLEAR_TO 0x64}50PC",
"Rash Mint{CLEAR_TO 0x64}50BP": "Menta Impuls.{CLEAR_TO 0x64}50PC",
"Relaxed Mint{CLEAR_TO 0x64}50BP": "Menta Relax.{CLEAR_TO 0x64}50PC",
"Sassy Mint{CLEAR_TO 0x64}50BP": "Menta Descar.{CLEAR_TO 0x64}50PC",
"Serious Mint{CLEAR_TO 0x64}50BP": "Menta Seriosa{CLEAR_TO 0x64}50PC",
"Timid Mint{CLEAR_TO 0x64}50BP": "Menta Tímida{CLEAR_TO 0x64}50PC",

# ---- move tutor BP list (matches map_move_names.py) ----
"Softboiled{CLEAR_TO 0x4E}16BP": "Ou Passat{CLEAR_TO 0x4E}16PC",
"Seismic Toss{CLEAR_TO 0x4E}24BP": "Llanç Sísmic{CLEAR_TO 0x4E}24PC",
"Dream Eater{CLEAR_TO 0x4E}24BP": "Menjasomnis{CLEAR_TO 0x4E}24PC",
"Mega Punch{CLEAR_TO 0x4E}24BP": "Megacop{CLEAR_TO 0x4E}24PC",
"Mega Kick{CLEAR_TO 0x4E}48BP": "Megapuntada{CLEAR_TO 0x4E}48PC",
"Body Slam{CLEAR_TO 0x4E}48BP": "Cop de Cos{CLEAR_TO 0x4E}48PC",
"Rock Slide{CLEAR_TO 0x4E}48BP": "AllauDeRoca{CLEAR_TO 0x4E}48PC",
"Counter{CLEAR_TO 0x4E}48BP": "Contraatac{CLEAR_TO 0x4E}48PC",
"Thunder Wave{CLEAR_TO 0x4E}48BP": "Onada Tro{CLEAR_TO 0x4E}48PC",
"Swords Dance{CLEAR_TO 0x4E}48BP": "Dansa Espasa{CLEAR_TO 0x4E}48PC",
"Defense Curl{CLEAR_TO 0x4E}16BP": "Enrotllar{CLEAR_TO 0x4E}16PC",
"Snore{CLEAR_TO 0x4E}24BP": "Roncar{CLEAR_TO 0x4E}24PC",
"Mud-Slap{CLEAR_TO 0x4E}24BP": "CopdeFang{CLEAR_TO 0x4E}24PC",
"Swift{CLEAR_TO 0x4E}24BP": "Rapidesa{CLEAR_TO 0x4E}24PC",
"Icy Wind{CLEAR_TO 0x4E}24BP": "Vent Gelat{CLEAR_TO 0x4E}24PC",
"Endure{CLEAR_TO 0x4E}48BP": "Aguantar{CLEAR_TO 0x4E}48PC",
"Psych Up{CLEAR_TO 0x4E}48BP": "Autosuggest{CLEAR_TO 0x4E}48PC",
"Ice Punch{CLEAR_TO 0x4E}48BP": "Cop de Gel{CLEAR_TO 0x4E}48PC",
"Thunderpunch{CLEAR_TO 0x4E}48BP": "CopElèctric{CLEAR_TO 0x4E}48PC",
"Fire Punch{CLEAR_TO 0x4E}48BP": "Cop de Foc{CLEAR_TO 0x4E}48PC",

# ---- met locations: translatable remainder (<=17 chars) ----
"Battle Tower": "Torre de Combat",
"Mt. Battle": "Mt. Combat",
"Outskirt Stand": "Parada Afores",
"Phenac Stadium": "Estadi de Phenac",
"Pyrite Colosseum": "Colisseu Pyrite",
"Under Colosseum": "Colisseu Subsòl",
"Deep Colosseum": "Colisseu Profund",
"Mt.Btl Colosseum": "Colisseu Mt.Comb",
"Realgam Tower": "Torre Realgam",
"Realgamtwr Dome": "Cúpula Realgam",
"Realgamtwr Lobby": "Rebedor Realgam",
"Tower Colosseum": "Colisseu Torre",
"Orre Colosseum": "Colisseu d'Orre",
"Realgam Tower 2F": "Torre Realgam 2P",
"S.S. Libra": "S.S. Libra",
"BATTLE TOWER": "TORRE DE COMBAT",
"MT. BATTLE": "MT. COMBAT",
"OUTSKIRT STAND": "PARADA AFORES",
"PHENAC STADIUM": "ESTADI DE PHENAC",
"PYRITE COLOSSEUM": "COLISSEU PYRITE",
"UNDER COLOSSEUM": "COLISSEU SUBSÒL",
"DEEP COLOSSEUM": "COLISSEU PROFUND",
"MT.BTL COLOSSEUM": "COLISSEU MT.COMB",
"REALGAM TOWER": "TORRE REALGAM",
"REALGAMTWR DOME": "CÚPULA REALGAM",
"REALGAMTWR LOBBY": "REBEDOR REALGAM",
"TOWER COLOSSEUM": "COLISSEU TORRE",
"ORRE COLOSSEUM": "COLISSEU D'ORRE",
"REALGAM TOWER 2F": "TORRE REALGAM 2P",
}
