# -*- coding: utf-8 -*-
"""Catalan: Pallet Town, the player's and rival's houses, and Route 1."""
KIND = 'asm'
FILES = [
    'data/maps/PalletTown/scripts.inc',
    'data/maps/PalletTown_PlayersHouse_1F/scripts.inc',
    'data/maps/PalletTown_PlayersHouse_2F/scripts.inc',
    'data/maps/PalletTown_RivalsHouse/scripts.inc',
    'data/maps/Route1/scripts.inc',
]

T = {
# ---- Pallet Town ----
"Mom: {PLAYER}!\\p": "Mare: {PLAYER}!\\p",
"Did you meet with Professor Oak?$": "Has anat a veure el Professor Oak?$",
"Oh! What an adorable Pokémon!\\n": "Oh! Quin Pokémon més adorable!\\n",
"You got it from Prof. Oak? How nice!\\p": "Te l'ha donat el Prof. Oak? Que bé!\\p",
"And now you're on your way up to \\n": "I ara te'n vas cap a la\\n",
"Viridian City?\\p": "ciutat de Viridian?\\p",
"Well, I guess everyone dreams of\\n": "Bé, suposo que tothom somia de\\n",
"traveling. At least it said so on TV.\\p": "viatjar. Almenys ho deien a la tele.\\p",
"In that case, you wouldn't want to leave\\n": "En aquest cas, no voldràs marxar\\n",
"without your PokéGear, would you?$": "sense el teu PokéGear, oi?$",
"Your PokéGear has a map app, so\\n": "El PokéGear té una app de mapa,\\n",
"you should never get lost.\\p": "així que no et perdràs mai.\\p",
"I already registered my number\\n": "Ja he registrat el meu número\\n",
"in your Cell Phone, too.\\p": "al teu mòbil, també.\\p",
"Don't forget about your mom during\\n": "No t'oblidis de la teva mare durant\\n",
"your adventures. Call me sometime!$": "les aventures. Truca'm de tant en tant!$",
"{PLAYER} received the PokéGear\\n": "{PLAYER} ha rebut el PokéGear\\n",
"from Mom!$": "de la seva mare!$",
"Pallet Town\\n": "Poble Pallet\\n",
"Shades of your journey await!$": "Els matisos del teu viatge t'esperen!$",
"Trainer Tips:\\p": "Consells per a entrenadors:\\p",
"Press Start to open the Menu!$": "Prem Start per obrir el menú!$",
"Oak Pokémon Research Lab$": "Laboratori d'Investigació Pokémon\\nde l'Oak$",
"I'm raising Pokémon, too.\\p": "Jo també crio Pokémon.\\p",
"When they get strong, they can\\n": "Quan es fan forts, em poden\\n",
"protect me.$": "protegir.$",
"Signs are useful, aren't they?$": "Els rètols són útils, oi?$",
"You can learn quite a lot from\\n": "Es pot aprendre molt dels\\n",
"those Trainer Tips signs!$": "rètols de consells per a entrenadors!$",
"Technology is incredible!\\p": "La tecnologia és increïble!\\p",
"You can now store and recall items\\n": "Ara pots guardar i recuperar objectes\\n",
"and Pokémon as data via PC.$": "i Pokémon com a dades des del PC.$",
"{PLAYER}'s house$": "Casa de {PLAYER}$",
"{RIVAL}'s house$": "Casa de {RIVAL}$",

# ---- player's house 1F ----
"Mom: I didn't know you knew\\n": "Mare: No sabia que coneixies\\n",
"the famous PokéManiac, honey!\\p": "el famós PokéManíac, reina!\\p",
"He's such a gentleman!$": "És tot un cavaller!$",
"Strange stones? Hidden potential?\\p": "Pedres estranyes? Potencial ocult?\\p",
"The adventures never stop for you\\n": "Les aventures no s'acaben mai per a\\n",
"Pokémon trainers!$": "vosaltres, entrenadors Pokémon!$",
"Mom: You don't want to miss\\n": "Mare: No et convé perdre't\\n",
"Professor Oak!\\p": "el Professor Oak!\\p",
"You better hurry!$": "Val més que t'afanyis!$",
"There's a movie on TV.\\n": "Fan una pel·lícula a la tele.\\n",
"Four boys are walking on railroad\\l": "Quatre nois caminen per les vies\\l",
"tracks.\\p": "del tren.\\p",
"…I better go, too.$": "…Val més que jo també marxi.$",
"It's the instruction booklet for the\\n": "És el manual d'instruccions de les\\n",
"Running Shoes.\\p": "Sabates de Córrer.\\p",
"“Press the B Button to run while\\n": "“Prem el botó B per córrer mentre\\n",
"wearing your Running Shoes.\\p": "portes les Sabates de Córrer.\\p",
"Lace up your Running Shoes and hit\\n": "Corda't les Sabates de Córrer i\\n",
"the road running!”$": "surt a la carretera corrent!”$",
"Mom: {PLAYER}!\\n": "Mare: {PLAYER}!\\n",
"You should take a quick rest.$": "Hauries de descansar una mica.$",
"Mom: Oh, good! You and your\\n": "Mare: Oh, molt bé! Tu i els teus\\n",
"Pokémon are looking great.\\l": "Pokémon teniu molt bon aspecte.\\l",
"Take care now!$": "Aneu amb compte!$",
"Hey, {PLAYER}!\\n": "Ei, {PLAYER}!\\n",
"I've discovered something amazing!\\p": "He descobert una cosa increïble!\\p",
"I was doing some research for my\\n": "Estava investigant per a la meva\\n",
"Pokémon collection, when one of my\\l": "col·lecció Pokémon quan un dels meus\\l",
"scanners picked up a strange reading.\\p": "escàners ha detectat una lectura estranya.\\p",
"It seems that some Pokémon may have\\n": "Sembla que alguns Pokémon poden tenir\\n",
"some hidden potential that we haven't\\l": "un potencial ocult que encara no\\l",
"seen yet.\\p": "hem vist.\\p",
"And this reading seems to be the key!\\p": "I aquesta lectura sembla ser la clau!\\p",
"See, I found the source of the reading\\n": "Mira, he trobat l'origen de la lectura\\n",
"near the Sea Cottage\\p": "prop de la Casa del Mar\\p",
"It was a strange stone I'd never seen\\n": "Era una pedra estranya que no havia\\n",
"before!\\p": "vist mai!\\p",
"I brought it back to my lab, and I built\\n": "Me la vaig endur al laboratori i vaig\\n",
"a device to draw out its power!\\p": "fer un aparell per treure'n el poder!\\p",
"I want you to have it!$": "Vull que te'l quedis!$",
"Bill gave you a Mega Ring!$": "El Bill t'ha donat un Anell Mega!$",
"According to my readings, there\\n": "Segons les meves lectures, hi ha\\n",
"are more of those stones hidden\\l": "més pedres d'aquestes amagades\\l",
"across Kanto.\\p": "per tot Kanto.\\p",
"Now that you have the Mega Ring,\\n": "Ara que tens l'Anell Mega,\\n",
"you should be able to see them!\\p": "hauries de poder veure-les!\\p",
"We'll need to find a Mega Stone\\n": "Haurem de trobar una Pedra Mega\\n",
"to test my theory!$": "per provar la meva teoria!$",
"Bill: We'll need to find a\\n": "Bill: Haurem de trobar una\\n",
"Mega Stone to test my theory!$": "Pedra Mega per provar la teoria!$",
"Mom: Where are you going, {PLAYER}?\\p": "Mare: On vas, {PLAYER}?\\p",
"Aren't you going to say hello\\n": "No vas a saludar\\n",
"to our visitor?$": "el nostre convidat?$",
"Mom: Oh, {PLAYER}!\\n": "Mare: Oh, {PLAYER}!\\n",
"You're already up?\\p": "Ja t'has llevat?\\p",
"After everything you've been doing\\n": "Amb tot el que has estat fent\\n",
"I thought you'd need more rest.\\p": "pensava que necessitaries més descans.\\p",
"...\\p": "...\\p",
"You've really grown up, {PLAYER}.\\p": "Has crescut molt, {PLAYER}.\\p",
"I think your Pokémon can see that, too.\\p": "Crec que els teus Pokémon també ho veuen.\\p",
"They'll follow you anywhere!$": "Et seguiran a tot arreu!$",
"Your Follower settings in the Options\\n": "L'opció Acompanyant del menú d'Opcions\\n",
"menu can now be set to Any mode!\\p": "ja es pot posar en mode Qualsevol!\\p",
"When this is selected, your first\\n": "Quan la tries, el teu primer\\n",
"Pokémon will follow you around!$": "Pokémon et seguirà pertot!$",
"Mom: Just because you're the new\\n": "Mare: Que siguis el nou campió\\n",
"champion doesn't mean your story\\l": "no vol dir que la teva història\\l",
"is over!\\p": "s'hagi acabat!\\p",
"There's a whole world out there\\n": "Hi ha tot un món a fora\\n",
"for you and your Pokémon to explore!\\p": "per explorar amb els teus Pokémon!\\p",
"I'm so proud of you, {PLAYER}!\\n": "Estic molt orgullosa de tu, {PLAYER}!\\n",
"Go have fun with your Pokémon!$": "Ves a passar-t'ho bé amb els Pokémon!$",

# ---- player's house 2F ----
"Mom: {PLAYER}! I should have\\p": "Mare: {PLAYER}! M'ho podia\\p",
"known I'd find you playing\\n": "haver imaginat, que et trobaria\\n",
"games up here again.\\p": "jugant aquí dalt un altre cop.\\p",
"You should head downstairs.\\n": "Hauries de baixar.\\n",
"Someone is here to see you!$": "Hi ha algú que et vol veure!$",
"Mom: {PLAYER}! There you are!\\p": "Mare: {PLAYER}! Aquí estàs!\\p",
"Have you been playing games\\n": "Has estat jugant\\n",
"up here this whole time?\\p": "aquí dalt tota l'estona?\\p",
"Weren't you supposed to meet\\n": "No havies de trobar-te avui amb\\n",
"Professor Oak at his lab today?\\p": "el Professor Oak al seu laboratori?\\p",
"Do you even know what time it is?$": "Que saps quina hora és?$",
"You should hurry over to the lab,\\n": "Afanya't a anar al laboratori,\\n",
"you're going to miss the Professor!$": "que et perdràs el Professor!$",
"Oh! If you want to change your\\n": "Oh! Si vols canviar-te de\\n",
"clothes before you go out, \\l": "roba abans de sortir,\\l",
"I put your laundry in your dresser.$": "t'he posat la roba al calaix.$",
"It's an old game console.\\p": "És una consola de joc antiga.\\p",
"Retro-gaming is all the rage!$": "El retrogaming està molt de moda!$",

# ---- rival's house ----
"It's a big map of the Kanto region.\\p": "És un mapa gran de la regió de Kanto.\\p",
"Isn't it so much easier to use\\n": "No és molt més còmode fer servir\\n",
"the map from your PokéGear?!$": "el mapa del PokéGear?!$",
"The shelves are crammed full of\\n": "Les prestatgeries són plenes de\\n",
"books on Pokémon.$": "llibres sobre Pokémon.$",
"Daisy: Just like people, Pokémon\\n": "Daisy: Igual que les persones, els\\n",
"are living things.\\p": "Pokémon són éssers vius.\\p",
"When they get tired, please give\\n": "Quan es cansen, si us plau, deixa'ls\\n",
"them a rest.$": "descansar.$",
"Daisy: Hi, {PLAYER}!\\p": "Daisy: Hola, {PLAYER}!\\p",
"My brother, {RIVAL}, is out at\\n": "El meu germà, {RIVAL}, és al\\n",
"Grandpa's Lab.$": "laboratori de l'avi.$",
"Daisy: {PLAYER}, I heard you had\\n": "Daisy: {PLAYER}, m'han dit que has\\n",
"a battle against {RIVAL}.\\p": "combatut contra {RIVAL}.\\p",
"I wish I'd seen that!$": "Tant de bo ho hagués vist!$",
"Grandpa asked you to run an\\n": "L'avi t'ha demanat que li facis\\n",
"errand?\\p": "un encàrrec?\\p",
"And {RIVAL} wouldn't even give\\n": "I {RIVAL} no t'ha volgut donar\\n",
"you his number, either?\\p": "ni el seu número?\\p",
"Gee, that's rude of him.\\n": "Uf, quina poca educació.\\n",
"Here, let me help you.$": "Vine, deixa'm ajudar-te.$",
"Daisy: Hi, {PLAYER}!\\n": "Daisy: Hola, {PLAYER}!\\n",
"Good timing.\\p": "Arribes en bon moment.\\p",
"I'm about to have some tea.\\n": "Ara mateix anava a prendre un te.\\n",
"Would you like to join me?\\p": "Vols acompanyar-me?\\p",
"Oh, but look.\\n": "Oh, però mira.\\n",
"Your Pokémon are a little dirty.\\p": "Els teus Pokémon estan una mica bruts.\\p",
"Would you like me to groom one?$": "Vols que en pentini un?$",
"You don't need any grooming done?\\n": "No en vols pentinar cap?\\n",
"Okay, we'll just have tea.$": "D'acord, doncs només prendrem te.$",
"Which one should I groom?$": "Quin vols que pentini?$",
"Oh, sorry. I honestly can't\\n": "Oh, perdona. Sincerament, no puc\\n",
"groom an Egg.$": "pentinar un Ou.$",
"Daisy: Okay, I'll get it looking\\n": "Daisy: Molt bé, el deixaré ben\\n",
"nice in no time.$": "maco en un moment.$",
"{STR_VAR_1} looks dreamily content…\\p": "{STR_VAR_1} sembla content i somiador…\\p",
"Daisy: There you go! All done.\\n": "Daisy: Ja està! Acabat.\\n",
"See? Doesn't it look nice?\\p": "Ho veus? No està maco?\\p",
"Giggle…\\n": "Ha, ha…\\n",
"It's such a cute Pokémon.$": "Quin Pokémon més bonic.$",
"Daisy: Your Pokémon grow to love\\n": "Daisy: Els teus Pokémon t'arriben a\\n",
"you if you raise them with love.\\p": "estimar si els cries amb amor.\\p",
"For example, {PLAYER}, may I see\\n": "Per exemple, {PLAYER}, puc veure\\n",
"your first Pokémon?$": "el teu primer Pokémon?$",
"…Um, it's not easy for me to say\\n": "…Ehm, no em resulta fàcil dir-te\\n",
"this, but…\\p": "això, però…\\p",
"Is there some reason why your\\n": "Hi ha algun motiu perquè el teu\\n",
"Pokémon would hate you so much?$": "Pokémon t'odiï tant?$",
"{PLAYER}, I don't like the way it\\n": "{PLAYER}, no m'agrada com et\\n",
"glares at you.\\p": "mira de reüll.\\p",
"Could you try being a little nicer\\n": "Podries provar de ser una mica més\\n",
"to it?$": "amable amb ell?$",
"It's not quite familiar with you\\n": "Encara no t'acaba de tenir\\n",
"yet.\\p": "confiança.\\p",
"Pokémon are all quite wary when\\n": "Tots els Pokémon són desconfiats\\n",
"you first get them.$": "quan els acabes d'aconseguir.$",
"It's warming up to you.\\n": "S'està acostumant a tu.\\n",
"Trust must be growing between you.$": "La confiança va creixent entre vosaltres.$",
"It's quite friendly with you.\\n": "Es porta bastant bé amb tu.\\n",
"Keep being good to it!$": "Continua tractant-lo bé!$",
"It looks very happy.\\p": "Sembla molt content.\\p",
"I wish {RIVAL} could see this and\\n": "Tant de bo {RIVAL} ho pogués veure i\\n",
"learn something from it.$": "n'aprengués alguna cosa.$",
"It couldn't possibly love you\\n": "No et podria estimar més\\n",
"any more than it does now.\\p": "del que t'estima ara.\\p",
"Your Pokémon is happy beyond\\n": "El teu Pokémon és feliç més enllà\\n",
"words.$": "de les paraules.$",

# ---- Route 1 ----
"Oak: Hey! Wait!\\n": "Oak: Ei! Espera!\\n",
"Don't come out this way!$": "No vagis per aquí!$",
"OAK: It's unsafe!\\n": "OAK: És perillós!\\n",
"Wild Pokémon live in tall grass!\\p": "A l'herba alta hi viuen Pokémon salvatges!\\p",
"You need your own Pokémon for\\n": "Necessites el teu propi Pokémon per\\n",
"your protection.$": "protegir-te.$",
"Oak: That was close!\\n": "Oak: Per poc!\\n",
"But that's odd...\\p": "Però això és estrany...\\p",
"You don't often see Pikachu\\n": "No es veuen sovint Pikachu\\n",
"in this area...\\p": "per aquesta zona...\\p",
"Let's head back to my lab!$": "Tornem al meu laboratori!$",
"Hi!\\n": "Hola!\\n",
"I work at a Pokémon Mart.\\p": "Treballo en una botiga Pokémon.\\p",
"It's part of a convenient chain\\n": "Forma part d'una cadena molt pràctica\\n",
"selling all sorts of items.\\p": "que ven tota mena d'objectes.\\p",
"Please, visit us in Viridian City.\\p": "Vine a veure'ns a la ciutat de Viridian.\\p",
"I know, I'll give you a sample.\\n": "Ja ho sé, et donaré una mostra.\\n",
"Here you go!$": "Aquí ho tens!$",
"Please come see us if you need\\n": "Vine a veure'ns si necessites\\n",
"Poké Balls for catching Pokémon.$": "Poké Balls per capturar Pokémon.$",
"See those ledges along the road?\\p": "Veus aquells esglaons vora el camí?\\p",
"It's a bit scary, but you can jump\\n": "Fa una mica de por, però pots\\n",
"from them.\\p": "saltar-hi.\\p",
"You can get back to Pallet Town\\n": "Així pots tornar al Poble Pallet\\n",
"quicker that way.$": "més de pressa.$",
"Route 1\\n": "Ruta 1\\n",
"Pallet Town - Viridian City$": "Poble Pallet - Ciutat de Viridian$",
}
