# -*- coding: utf-8 -*-
"""Catalan battle messages, part 2: moves, abilities, items, encounters,
capture, menus, tourney."""
KIND = 'c'
FILES = ['src/battle_message.c']

T = {
# ---- uproar / stockpile / bide ----
"But {B_SCR_ACTIVE_NAME_WITH_PREFIX}'s Uproar\\nkept it awake!": "Però l'Aldarull de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nl'ha mantingut despert!",
"{B_ATK_NAME_WITH_PREFIX} woke up\\nin the Uproar!": "{B_ATK_NAME_WITH_PREFIX} s'ha despertat\\namb l'Aldarull!",
"{B_ATK_NAME_WITH_PREFIX} caused\\nan Uproar!": "{B_ATK_NAME_WITH_PREFIX} ha causat\\nun Aldarull!",
"{B_ATK_NAME_WITH_PREFIX} is making\\nan Uproar!": "{B_ATK_NAME_WITH_PREFIX} està fent\\nun Aldarull!",
"{B_ATK_NAME_WITH_PREFIX} calmed down.": "{B_ATK_NAME_WITH_PREFIX} s'ha calmat.",
"But {B_DEF_NAME_WITH_PREFIX} can't\\nsleep in an Uproar!": "Però {B_DEF_NAME_WITH_PREFIX} no pot\\ndormir amb un Aldarull!",
"But the Uproar kept\\n{B_DEF_NAME_WITH_PREFIX} awake!": "Però l'Aldarull ha mantingut\\n{B_DEF_NAME_WITH_PREFIX} despert!",
"{B_DEF_NAME_WITH_PREFIX} stayed awake\\nusing its {B_DEF_ABILITY}!": "{B_DEF_NAME_WITH_PREFIX} s'ha mantingut\\ndespert amb {B_DEF_ABILITY}!",
"{B_ATK_NAME_WITH_PREFIX} stockpiled\\n{B_BUFF1}!": "{B_ATK_NAME_WITH_PREFIX} ha emmagatzemat\\n{B_BUFF1}!",
"{B_ATK_NAME_WITH_PREFIX} can't\\nStockpile any more!": "{B_ATK_NAME_WITH_PREFIX} no pot\\nemmagatzemar més!",
"{B_ATK_NAME_WITH_PREFIX} is storing\\nenergy!": "{B_ATK_NAME_WITH_PREFIX} està\\nacumulant energia!",
"{B_ATK_NAME_WITH_PREFIX} unleashed\\nenergy!": "{B_ATK_NAME_WITH_PREFIX} ha deixat\\nanar l'energia!",
"But it failed to Spit Up\\na thing!": "Però no ha pogut escopir\\nres!",
"But it failed to Swallow\\na thing!": "Però no ha pogut empassar\\nres!",

# ---- substitute / transform ----
"{B_ATK_NAME_WITH_PREFIX} transformed\\ninto the {B_BUFF1} type!": "{B_ATK_NAME_WITH_PREFIX} s'ha convertit\\nen tipus {B_BUFF1}!",
"{B_ATK_NAME_WITH_PREFIX} transformed\\ninto {B_BUFF1}!": "{B_ATK_NAME_WITH_PREFIX} s'ha transformat\\nen {B_BUFF1}!",
"{B_ATK_NAME_WITH_PREFIX} made\\na Substitute!": "{B_ATK_NAME_WITH_PREFIX} ha creat\\nun Substitut!",
"{B_ATK_NAME_WITH_PREFIX} already\\nhas a Substitute!": "{B_ATK_NAME_WITH_PREFIX} ja\\nté un Substitut!",
"The Substitute took damage\\nfor {B_DEF_NAME_WITH_PREFIX}!\\p": "El Substitut ha rebut el dany\\nper {B_DEF_NAME_WITH_PREFIX}!\\p",
"{B_DEF_NAME_WITH_PREFIX}'s\\nSubstitute faded!\\p": "El Substitut de {B_DEF_NAME_WITH_PREFIX}\\nha desaparegut!\\p",
"It was too weak to make\\na Substitute!": "Estava massa feble per crear\\nun Substitut!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} transformed!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} s'ha transformat!",
"{B_DEF_NAME_WITH_PREFIX} transformed\\ninto the {B_BUFF1} type!": "{B_DEF_NAME_WITH_PREFIX} s'ha convertit\\nen tipus {B_BUFF1}!",
"{B_BUFF1} type was added to\\n{B_DEF_NAME_WITH_PREFIX}!": "S'ha afegit el tipus {B_BUFF1}\\na {B_DEF_NAME_WITH_PREFIX}!",
"{B_BUFF1}'s type\\nchanged to {B_BUFF2}!": "El tipus de {B_BUFF1}\\nha canviat a {B_BUFF2}!",
"{B_ATK_NAME_WITH_PREFIX}'s type\\nchanged to match the {B_DEF_NAME_WITH_PREFIX}'s!": "El tipus de {B_ATK_NAME_WITH_PREFIX} ha\\ncanviat per igualar {B_DEF_NAME_WITH_PREFIX}!",

# ---- rage / disable / encore ----
"{B_DEF_NAME_WITH_PREFIX}'s Rage\\nis building!": "La Ràbia de {B_DEF_NAME_WITH_PREFIX}\\nva creixent!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}\\nwas disabled!": "{B_BUFF1} de {B_DEF_NAME_WITH_PREFIX}\\nha quedat anul·lat!",
"{B_ATK_NAME_WITH_PREFIX} is disabled\\nno more!": "{B_ATK_NAME_WITH_PREFIX} ja no\\nestà anul·lat!",
"{B_DEF_NAME_WITH_PREFIX} got\\nan Encore!": "{B_DEF_NAME_WITH_PREFIX} ha rebut\\nuna Repetició!",
"{B_ATK_NAME_WITH_PREFIX}'s Encore\\nended!": "La Repetició de {B_ATK_NAME_WITH_PREFIX}\\ns'ha acabat!",
"{B_ATK_NAME_WITH_PREFIX} took aim\\nat {B_DEF_NAME_WITH_PREFIX}!": "{B_ATK_NAME_WITH_PREFIX} ha apuntat\\na {B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} Sketched\\n{B_BUFF1}!": "{B_ATK_NAME_WITH_PREFIX} ha esbossat\\n{B_BUFF1}!",
"{B_ATK_NAME_WITH_PREFIX} is trying\\nto take its foe with it!": "{B_ATK_NAME_WITH_PREFIX} intenta\\nendur-se el rival amb ell!",
"{B_DEF_NAME_WITH_PREFIX} took\\n{B_ATK_NAME_WITH_PREFIX} with it!": "{B_DEF_NAME_WITH_PREFIX} s'ha endut\\n{B_ATK_NAME_WITH_PREFIX} amb ell!",
"{B_ATK_NAME_WITH_PREFIX} chose\\n{B_CURRENT_MOVE} as its destiny!": "{B_ATK_NAME_WITH_PREFIX} ha triat\\n{B_CURRENT_MOVE} com a destí!",

# ---- items stolen / knocked off ----
"{B_ATK_NAME_WITH_PREFIX} stole\\n{B_DEF_NAME_WITH_PREFIX}'s {B_LAST_ITEM}!": "{B_ATK_NAME_WITH_PREFIX} ha robat\\n{B_LAST_ITEM} a {B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} knocked off\\n{B_DEF_NAME_WITH_PREFIX}'s {B_LAST_ITEM}!": "{B_ATK_NAME_WITH_PREFIX} ha fet caure\\n{B_LAST_ITEM} de {B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} stole and\\nate {B_DEF_NAME_WITH_PREFIX}'s {B_LAST_ITEM}!": "{B_ATK_NAME_WITH_PREFIX} ha robat i menjat\\n{B_LAST_ITEM} de {B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} stole and ate\\n{B_EFF_NAME_WITH_PREFIX}'s {B_LAST_ITEM}!": "{B_ATK_NAME_WITH_PREFIX} ha robat i menjat\\n{B_LAST_ITEM} de {B_EFF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} switched\\nitems with its opponent!": "{B_ATK_NAME_WITH_PREFIX} ha bescanviat\\nels objectes amb el rival!",
"{B_ATK_NAME_WITH_PREFIX} obtained\\n{B_BUFF1}.": "{B_ATK_NAME_WITH_PREFIX} ha obtingut\\n{B_BUFF1}.",
"{B_DEF_NAME_WITH_PREFIX} obtained\\n{B_BUFF2}.": "{B_DEF_NAME_WITH_PREFIX} ha obtingut\\n{B_BUFF2}.",
"{B_ATK_NAME_WITH_PREFIX} obtained\\n{B_BUFF1}.\\p{B_DEF_NAME_WITH_PREFIX} obtained\\n{B_BUFF2}.": "{B_ATK_NAME_WITH_PREFIX} ha obtingut\\n{B_BUFF1}.\\p{B_DEF_NAME_WITH_PREFIX} ha obtingut\\n{B_BUFF2}.",
"{B_ATK_NAME_WITH_PREFIX} found\\none {B_LAST_ITEM}!": "{B_ATK_NAME_WITH_PREFIX} ha trobat\\nun {B_LAST_ITEM}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} found\\na {B_LAST_ITEM}!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha trobat\\nun {B_LAST_ITEM}!",
"{B_ATK_NAME_WITH_PREFIX} flung its\\n{B_LAST_ITEM}!": "{B_ATK_NAME_WITH_PREFIX} ha llançat\\n{B_LAST_ITEM}!",
"{B_DEF_NAME_WITH_PREFIX} received {B_LAST_ITEM}\\nfrom {B_ATK_NAME_WITH_PREFIX}": "{B_DEF_NAME_WITH_PREFIX} ha rebut {B_LAST_ITEM}\\nde {B_ATK_NAME_WITH_PREFIX}",
"{B_DEF_NAME_WITH_PREFIX} received {B_LAST_ITEM}\\nfrom {B_ATK_NAME_WITH_PREFIX}!": "{B_DEF_NAME_WITH_PREFIX} ha rebut {B_LAST_ITEM}\\nde {B_ATK_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX} can't use\\nitems anymore!": "{B_DEF_NAME_WITH_PREFIX} ja no pot\\nfer servir objectes!",
"{B_ATK_NAME_WITH_PREFIX} can\\nuse items again!": "{B_ATK_NAME_WITH_PREFIX} ja pot\\ntornar a fer servir objectes!",
"{B_ATK_NAME_WITH_PREFIX}'s item cannot be removed!": "L'objecte de {B_ATK_NAME_WITH_PREFIX} no es pot treure!",
"The {B_LAST_ITEM} attached itself to\\n{B_ATK_NAME_WITH_PREFIX}!": "{B_LAST_ITEM} s'ha enganxat a\\n{B_ATK_NAME_WITH_PREFIX}!",
"Items can't be used now.{PAUSE 64}": "Ara no es poden fer servir objectes.{PAUSE 64}",
"For {B_SCR_ACTIVE_NAME_WITH_PREFIX},\\n{B_LAST_ITEM} {B_BUFF1}": "Per a {B_SCR_ACTIVE_NAME_WITH_PREFIX},\\n{B_LAST_ITEM} {B_BUFF1}",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} used\\n{B_LAST_ITEM} to get pumped!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha fet servir\\n{B_LAST_ITEM} per animar-se!",
"{B_ATK_NAME_WITH_PREFIX} harvested\\nits {B_LAST_ITEM}!": "{B_ATK_NAME_WITH_PREFIX} ha collit\\n{B_LAST_ITEM}!",
"{B_DEF_NAME_WITH_PREFIX} ate its {B_LAST_ITEM}!": "{B_DEF_NAME_WITH_PREFIX} s'ha menjat {B_LAST_ITEM}!",
"{B_ATK_NAME_WITH_PREFIX} frisked {B_DEF_NAME_WITH_PREFIX} and\\nfound its {B_LAST_ITEM}!": "{B_ATK_NAME_WITH_PREFIX} ha escorcollat {B_DEF_NAME_WITH_PREFIX}\\ni ha trobat {B_LAST_ITEM}!",
"{B_ATK_NAME_WITH_PREFIX} passed its {B_LAST_ITEM}\\nto {B_SCR_ACTIVE_NAME_WITH_PREFIX} through {B_ATK_ABILITY}!": "{B_ATK_NAME_WITH_PREFIX} ha passat {B_LAST_ITEM}\\na {B_SCR_ACTIVE_NAME_WITH_PREFIX} amb {B_ATK_ABILITY}!",
"{B_ATK_NAME_WITH_PREFIX} was hurt\\nby its {B_LAST_ITEM}!": "{B_LAST_ITEM} ha fet mal a\\n{B_ATK_NAME_WITH_PREFIX}!",
"{B_EFF_NAME_WITH_PREFIX} was badly \\npoisoned by the {B_LAST_ITEM}!": "{B_LAST_ITEM} ha enverinat greument\\n{B_EFF_NAME_WITH_PREFIX}!",
"{B_EFF_NAME_WITH_PREFIX} was burned\\nby the {B_LAST_ITEM}!": "{B_LAST_ITEM} ha cremat\\n{B_EFF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} became fully charged\\ndue to its {B_LAST_ITEM}!": "{B_ATK_NAME_WITH_PREFIX} s'ha carregat del tot\\ngràcies a {B_LAST_ITEM}!",
"{B_DEF_NAME_WITH_PREFIX} hung on\\nusing its {B_LAST_ITEM}!": "{B_DEF_NAME_WITH_PREFIX} ha aguantat\\namb {B_LAST_ITEM}!",
"{B_LAST_ITEM} allows the\\nuse of only {B_CURRENT_MOVE}!\\p": "{B_LAST_ITEM} només permet\\nfer servir {B_CURRENT_MOVE}!\\p",
"{B_ATK_ABILITY} allows the\\nuse of only {B_CURRENT_MOVE}!\\p": "{B_ATK_ABILITY} només permet\\nfer servir {B_CURRENT_MOVE}!\\p",
"{B_LAST_ITEM} strengthened\\n{B_ATK_NAME_WITH_PREFIX}'s power!": "{B_LAST_ITEM} ha reforçat\\nel poder de {B_ATK_NAME_WITH_PREFIX}!",
"{B_LAST_ITEM} weakened the damage\\nto {B_DEF_NAME_WITH_PREFIX}!": "{B_LAST_ITEM} ha reduït el dany\\na {B_DEF_NAME_WITH_PREFIX}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} floats in the air\\nwith its {B_LAST_ITEM}!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} flota en l'aire\\namb {B_LAST_ITEM}!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_LAST_ITEM} popped!": "{B_LAST_ITEM} de {B_DEF_NAME_WITH_PREFIX} ha esclatat!",
"{B_EFF_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\nwas burnt up!": "{B_LAST_ITEM} de {B_EFF_NAME_WITH_PREFIX}\\ns'ha cremat!",
"{B_DEF_NAME_WITH_PREFIX} is not affected\\nthanks to its {B_LAST_ITEM}!": "{B_DEF_NAME_WITH_PREFIX} no se'n veu afectat\\ngràcies a {B_LAST_ITEM}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} held up its {B_LAST_ITEM}\\nagainst {B_ATK_NAME_WITH_PREFIX}!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha mostrat {B_LAST_ITEM}\\na {B_ATK_NAME_WITH_PREFIX}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} is switched\\nout with the {B_LAST_ITEM}!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} surt del combat\\namb {B_LAST_ITEM}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} boosted the accuracy of its\\nnext move using {B_LAST_ITEM}!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha pujat la precisió del\\nseu proper moviment amb {B_LAST_ITEM}!",
"{B_LAST_ITEM}'s effects prevent\\nstatus moves from being used!\\p": "Els efectes de {B_LAST_ITEM} impedeixen\\nfer servir moviments d'estat!\\p",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\ncured paralysis!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha curat la paràlisi!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\ncured poison!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha curat el verí!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\nhealed its burn!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha curat la cremada!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\ndefrosted it!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nl'ha desglaçat!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\nwoke it from its sleep!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nl'ha despertat!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\nsnapped it out of confusion!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nl'ha tret de la confusió!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\ncured its {B_BUFF1} problem!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nli ha curat {B_BUFF1}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\nnormalized its status!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nli ha normalitzat l'estat!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\nrestored health!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nli ha recuperat la salut!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\nrestored {B_BUFF1}'s PP!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha recuperat els PP de {B_BUFF1}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\nrestored its status!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nli ha restaurat l'estat!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\\nrestored its HP a little!": "{B_LAST_ITEM} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nli ha recuperat una mica de PS!",

# ---- nightmare / curse / spikes ----
"{B_DEF_NAME_WITH_PREFIX} fell into\\na Nightmare!": "{B_DEF_NAME_WITH_PREFIX} ha caigut\\nen un Malson!",
"{B_ATK_NAME_WITH_PREFIX} is locked\\nin a Nightmare!": "{B_ATK_NAME_WITH_PREFIX} està atrapat\\nen un Malson!",
"{B_ATK_NAME_WITH_PREFIX} cut its own HP and\\nlaid a Curse on {B_DEF_NAME_WITH_PREFIX}!": "{B_ATK_NAME_WITH_PREFIX} ha sacrificat PS i ha\\nllançat una Maledicció a {B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} is afflicted\\nby the Curse!": "{B_ATK_NAME_WITH_PREFIX} pateix\\nla Maledicció!",
"Spikes were scattered all around\\nthe opponent's side!": "S'han escampat Punxes per tot\\nel costat del rival!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} is hurt\\nby Spikes!": "Les Punxes fan mal a\\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} blew away\\nSpikes!": "{B_ATK_NAME_WITH_PREFIX} ha escampat\\nles Punxes!",
"Poison Spikes were scattered all\\naround the opposing team's feet!": "S'han escampat Punxes Tòxiques\\nals peus de l'equip rival!",
"The poison spikes disappeared\\nfrom around the opposing team's feet!": "Les punxes tòxiques han desaparegut\\ndels peus de l'equip rival!",
"Pointed stones float in the air\\naround {B_DEF_TEAM2} team!": "Pedres punxegudes floten en l'aire\\nal voltant de {B_DEF_TEAM2} equip!",
"Pointed stones dug into\\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}!": "Les pedres punxegudes han ferit\\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}!",
"A sticky web spreads out on the\\nground around {B_DEF_TEAM2} team!": "Una xarxa viscosa s'estén pel terra\\nal voltant de {B_DEF_TEAM2} equip!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} was\\ncaught in a Sticky Web!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha quedat\\natrapat en una Xarxa Viscosa!",
"{B_ATK_NAME_WITH_PREFIX} blew away\\nToxic Spikes!": "{B_ATK_NAME_WITH_PREFIX} ha escampat\\nles Punxes Tòxiques!",
"{B_ATK_NAME_WITH_PREFIX} blew away\\nSticky Web!": "{B_ATK_NAME_WITH_PREFIX} ha escampat\\nla Xarxa Viscosa!",
"{B_ATK_NAME_WITH_PREFIX} blew away\\nStealth Rock!": "{B_ATK_NAME_WITH_PREFIX} ha escampat\\nles Roques Trampa!",
"{B_ATK_NAME_WITH_PREFIX} identified\\n{B_DEF_NAME_WITH_PREFIX}!": "{B_ATK_NAME_WITH_PREFIX} ha identificat\\n{B_DEF_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX} was \\nidentified!": "{B_DEF_NAME_WITH_PREFIX} ha estat\\nidentificat!",
"{B_ATK_NAME_WITH_PREFIX}'s Perish count\\nfell to {B_BUFF1}!": "El compte final de {B_ATK_NAME_WITH_PREFIX}\\nha baixat a {B_BUFF1}!",
"All affected Pokémon will\\nfaint in three turns!": "Tots els Pokémon afectats es\\ndebilitaran en tres torns!",
"Both Pokémon will perish\\nin three turns!": "Els dos Pokémon es debilitaran\\nen tres torns!",

# ---- leech seed / misc moves ----
"{B_DEF_NAME_WITH_PREFIX} was seeded!": "{B_DEF_NAME_WITH_PREFIX} ha rebut una llavor!",
"{B_ATK_NAME_WITH_PREFIX}'s health is\\nsapped by Leech Seed!": "Llavor Xucla drena la salut de\\n{B_ATK_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} shed\\nLeech Seed!": "{B_ATK_NAME_WITH_PREFIX} s'ha tret\\nLlavor Xucla!",
"{B_ATK_NAME_WITH_PREFIX} got free of\\n{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}!": "{B_ATK_NAME_WITH_PREFIX} s'ha alliberat de\\n{B_BUFF1} de {B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} cut its own HP\\nand maximized Attack!": "{B_ATK_NAME_WITH_PREFIX} ha sacrificat PS i\\nha maximitzat l'Atac!",
"{B_ATK_NAME_WITH_PREFIX} copied\\n{B_DEF_NAME_WITH_PREFIX}'s stat changes!": "{B_ATK_NAME_WITH_PREFIX} ha copiat els canvis\\nd'estadístiques de {B_DEF_NAME_WITH_PREFIX}!",
"Magnitude {B_BUFF1}!": "Magnitud {B_BUFF1}!",
"{B_ATK_NAME_WITH_PREFIX} foresaw\\nan attack!": "{B_ATK_NAME_WITH_PREFIX} ha previst\\nun atac!",
"{B_DEF_NAME_WITH_PREFIX} took the\\n{B_BUFF1} attack!": "{B_DEF_NAME_WITH_PREFIX} ha rebut\\nl'atac {B_BUFF1}!",
"{B_BUFF1}'s attack!": "Atac de {B_BUFF1}!",
"{B_DEF_NAME_WITH_PREFIX} became the\\ncenter of attention!": "{B_DEF_NAME_WITH_PREFIX} s'ha convertit\\nen el centre d'atenció!",
"Nature Power turned into\\n{B_CURRENT_MOVE}!": "Poder Natural s'ha convertit en\\n{B_CURRENT_MOVE}!",
"{B_ATK_NAME_WITH_PREFIX}'s status\\nreturned to normal!": "L'estat de {B_ATK_NAME_WITH_PREFIX}\\nha tornat a la normalitat!",
"{B_DEF_NAME_WITH_PREFIX} was subjected\\nto Torment!": "{B_DEF_NAME_WITH_PREFIX} ha estat\\nsotmès a Turment!",
"{B_DEF_NAME_WITH_PREFIX} fell for\\nthe Taunt!": "{B_DEF_NAME_WITH_PREFIX} ha caigut\\nen la Mofa!",
"{B_DEF_NAME_WITH_PREFIX} fell for\\nthe feint!": "{B_DEF_NAME_WITH_PREFIX} ha caigut\\nen el fingiment!",
"{B_ATK_NAME_WITH_PREFIX} is ready to\\nhelp {B_DEF_NAME_WITH_PREFIX}!": "{B_ATK_NAME_WITH_PREFIX} està a punt\\nd'ajudar {B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} copied\\n{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}!": "{B_ATK_NAME_WITH_PREFIX} ha copiat\\n{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} made a Wish!": "{B_ATK_NAME_WITH_PREFIX} ha fet un Desig!",
"{B_BUFF1}'s Wish\\ncame true!": "El Desig de {B_BUFF1}\\ns'ha complert!",
"{B_ATK_NAME_WITH_PREFIX} planted its roots!": "{B_ATK_NAME_WITH_PREFIX} ha arrelat!",
"{B_ATK_NAME_WITH_PREFIX} absorbed\\nnutrients with its roots!": "{B_ATK_NAME_WITH_PREFIX} ha absorbit\\nnutrients amb les arrels!",
"{B_DEF_NAME_WITH_PREFIX} anchored\\nitself with its roots!": "{B_DEF_NAME_WITH_PREFIX} s'ha ancorat\\namb les arrels!",
"{B_ATK_NAME_WITH_PREFIX} swapped abilities\\nwith its opponent!": "{B_ATK_NAME_WITH_PREFIX} ha bescanviat\\nles habilitats amb el rival!",
"{B_ATK_NAME_WITH_PREFIX} sealed the\\nopponent's move(s)!": "{B_ATK_NAME_WITH_PREFIX} ha segellat\\nels moviments del rival!",
"{B_ATK_NAME_WITH_PREFIX} wants the\\nopponent to bear a Grudge!": "{B_ATK_NAME_WITH_PREFIX} vol que el\\nrival li guardi Rancúnia!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_BUFF1} lost\\nall its PP due to the Grudge!": "{B_BUFF1} de {B_ATK_NAME_WITH_PREFIX} ha perdut\\ntots els PP per la Rancúnia!",
"{B_ATK_NAME_WITH_PREFIX} shrouded\\nitself in {B_CURRENT_MOVE}!": "{B_ATK_NAME_WITH_PREFIX} s'ha\\nembolcallat de {B_CURRENT_MOVE}!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_CURRENT_MOVE}\\nwas bounced back by Magic Coat!": "Capa Màgica ha rebotat {B_CURRENT_MOVE}\\nde {B_ATK_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} waits for a target\\nto make a move!": "{B_ATK_NAME_WITH_PREFIX} espera que un\\nobjectiu es mogui!",
"{B_DEF_NAME_WITH_PREFIX} Snatched\\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s move!": "{B_DEF_NAME_WITH_PREFIX} ha arrabassat el\\nmoviment de {B_SCR_ACTIVE_NAME_WITH_PREFIX}!",
"Electricity's power was\\nweakened!": "El poder de l'electricitat\\ns'ha afeblit!",
"Fire's power was\\nweakened!": "El poder del foc\\ns'ha afeblit!",
"A soothing aroma wafted\\nthrough the area!": "Un aroma relaxant s'ha estès\\nper la zona!",
"Coins scattered everywhere!": "S'han escampat monedes arreu!",
"The battlers shared\\ntheir pain!": "Els combatents han compartit\\nel dolor!",
"A bell chimed!": "Ha sonat una campana!",
"{B_DEF_NAME_WITH_PREFIX} was\\ndragged out!\\p": "{B_DEF_NAME_WITH_PREFIX} ha estat\\ntret a fora!\\p",
"{B_DEF_NAME_WITH_PREFIX}\\ntook the kind offer!": "{B_DEF_NAME_WITH_PREFIX}\\nha acceptat l'oferta!",
"{B_ATK_NAME_WITH_PREFIX} and\\n{B_SCR_ACTIVE_NAME_WITH_PREFIX} switched places!": "{B_ATK_NAME_WITH_PREFIX} i\\n{B_SCR_ACTIVE_NAME_WITH_PREFIX} han canviat de lloc!",
"{B_ATK_NAME_WITH_PREFIX} took\\n{B_DEF_NAME_WITH_PREFIX} into the sky!": "{B_ATK_NAME_WITH_PREFIX} s'ha endut\\n{B_DEF_NAME_WITH_PREFIX} al cel!",
"{B_ATK_NAME_WITH_PREFIX} took {B_DEF_NAME_WITH_PREFIX}\\ninto the air!": "{B_ATK_NAME_WITH_PREFIX} s'ha endut {B_DEF_NAME_WITH_PREFIX}\\nenlaire!",
"{B_DEF_NAME_WITH_PREFIX} was freed\\nfrom the Sky Drop!": "{B_DEF_NAME_WITH_PREFIX} s'ha alliberat\\nde Caiguda Cel!",
"But the target\\nwas too heavy!": "Però l'objectiu era\\nmassa pesat!",
"{B_DEF_NAME_WITH_PREFIX}'s move\\nwas postponed!": "El moviment de {B_DEF_NAME_WITH_PREFIX}\\ns'ha endarrerit!",
"The opposing {B_ATK_NAME_WITH_PREFIX}'s move was postponed!": "El moviment de {B_ATK_NAME_WITH_PREFIX} s'ha endarrerit!",
"{B_ATK_NAME_WITH_PREFIX} switched its\\nAttack and Defense!": "{B_ATK_NAME_WITH_PREFIX} ha intercanviat\\nl'Atac i la Defensa!",
"{B_ATK_NAME_WITH_PREFIX} switched all its\\nchanges to its Attack and\\pSp. Atk with the target!": "{B_ATK_NAME_WITH_PREFIX} ha intercanviat amb\\nl'objectiu els canvis d'Atac i\\pAt. Esp.!",
"{B_ATK_NAME_WITH_PREFIX} switched all its\\nchanges to its Defense and\\pSp. Def with the target!": "{B_ATK_NAME_WITH_PREFIX} ha intercanviat amb\\nl'objectiu els canvis de Defensa i\\pDef. Esp.!",
"{B_ATK_NAME_WITH_PREFIX} switched stat changes\\nwith the target!": "{B_ATK_NAME_WITH_PREFIX} ha intercanviat els canvis\\nd'estadístiques amb l'objectiu!",
"{B_ATK_NAME_WITH_PREFIX} shared its\\nguard with the target!": "{B_ATK_NAME_WITH_PREFIX} ha compartit la\\nseva defensa amb l'objectiu!",
"{B_ATK_NAME_WITH_PREFIX} shared its\\npower with the target!": "{B_ATK_NAME_WITH_PREFIX} ha compartit el\\nseu poder amb l'objectiu!",
"{B_ATK_NAME_WITH_PREFIX} stole the target's\\nboosted stats!": "{B_ATK_NAME_WITH_PREFIX} ha robat les millores\\nd'estadístiques de l'objectiu!",
"{B_ATK_NAME_WITH_PREFIX} surrounded itself\\nwith a veil of water!": "{B_ATK_NAME_WITH_PREFIX} s'ha envoltat\\nd'un vel d'aigua!",
"{B_ATK_NAME_WITH_PREFIX} levitated on\\nelectromagnetism!": "{B_ATK_NAME_WITH_PREFIX} levita per\\nelectromagnetisme!",
"electromagnetism": "electromagnetisme",
"{B_ATK_NAME_WITH_PREFIX} twisted\\nthe dimensions!": "{B_ATK_NAME_WITH_PREFIX} ha retorçat\\nles dimensions!",
"{B_ATK_NAME_WITH_PREFIX} was freed\\nfrom the telekinesis!": "{B_ATK_NAME_WITH_PREFIX} s'ha alliberat\\nde la telecinesi!",
"{B_ATK_NAME_WITH_PREFIX} can\\nuse sound-based moves again!": "{B_ATK_NAME_WITH_PREFIX} ja pot tornar a\\nfer servir moviments de so!",
"{B_ATK_NAME_WITH_PREFIX} is\\ntormented no more!": "{B_ATK_NAME_WITH_PREFIX} ja no\\nestà turmentat!",
"{B_ATK_NAME_WITH_PREFIX} is cured of\\nits heal block!": "{B_ATK_NAME_WITH_PREFIX} s'ha curat\\nde l'anticura!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} shook off\\nthe taunt!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} s'ha tret\\nla mofa de sobre!",
"{B_DEF_NAME_WITH_PREFIX} was prevented\\nfrom healing!": "S'ha impedit que {B_DEF_NAME_WITH_PREFIX}\\nes curi!",
"{B_ATK_NAME_WITH_PREFIX} was\\nprevented from healing!\\p": "S'ha impedit que {B_ATK_NAME_WITH_PREFIX}\\nes curi!\\p",
"{B_DEF_NAME_WITH_PREFIX} is covered in powder!": "{B_DEF_NAME_WITH_PREFIX} està cobert de pols!",
"When the flame touched the powder\\non the Pokémon, it exploded!": "Quan la flama ha tocat la pols del\\nPokémon, ha explotat!",
"{B_ATK_NAME_WITH_PREFIX} cured\\n{B_DEF_NAME_WITH_PREFIX}'s problem!": "{B_ATK_NAME_WITH_PREFIX} ha curat\\n{B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} burned itself out!": "{B_ATK_NAME_WITH_PREFIX} s'ha consumit del tot!",
"{B_ATK_NAME_WITH_PREFIX} used the move\\ninstructed by {B_BUFF1}!": "{B_ATK_NAME_WITH_PREFIX} ha usat el moviment\\nindicat per {B_BUFF1}!",
"{B_ATK_NAME_WITH_PREFIX} swapped the battle\\neffects affecting each side!": "{B_ATK_NAME_WITH_PREFIX} ha intercanviat els efectes\\nde combat de cada costat!",
"{B_ATK_NAME_WITH_PREFIX} can act faster,\\nthanks to {B_BUFF1}!": "{B_ATK_NAME_WITH_PREFIX} pot actuar més ràpid\\ngràcies a {B_BUFF1}!",
"{B_DEF_NAME_WITH_PREFIX} became\\nweaker to fire!": "{B_DEF_NAME_WITH_PREFIX} s'ha tornat\\nmés feble al foc!",
"{B_DEF_NAME_WITH_PREFIX} is about\\nto be attacked by its {B_BUFF1}!": "{B_DEF_NAME_WITH_PREFIX} està a punt\\nde rebre l'atac de {B_BUFF1}!",
"{B_DEF_NAME_WITH_PREFIX} was hurled\\ninto the air!": "{B_DEF_NAME_WITH_PREFIX} ha sortit\\ndisparat enlaire!",
"{B_DEF_NAME_WITH_PREFIX} fell\\nstraight down!": "{B_DEF_NAME_WITH_PREFIX} ha caigut\\nde ple!",
"{B_DEF_NAME_WITH_PREFIX} can't stay airborne\\nbecause of gravity!": "{B_DEF_NAME_WITH_PREFIX} no pot mantenir-se\\nenlaire per la gravetat!",
"{B_ATK_NAME_WITH_PREFIX} can't use {B_CURRENT_MOVE}\\nbecause of gravity!\\p": "{B_ATK_NAME_WITH_PREFIX} no pot usar {B_CURRENT_MOVE}\\nper la gravetat!\\p",
"Gravity intensified!": "La gravetat s'ha intensificat!",
"Gravity returned to normal!": "La gravetat ha tornat a la normalitat!",
"{B_ATK_NAME_WITH_PREFIX} cannot\\nuse {B_CURRENT_MOVE}!": "{B_ATK_NAME_WITH_PREFIX} no pot\\nusar {B_CURRENT_MOVE}!",
"But {B_ATK_NAME_WITH_PREFIX} can't\\nuse the move!": "Però {B_ATK_NAME_WITH_PREFIX} no pot\\nusar el moviment!",
"Belch cannot be used!\\p": "No es pot fer servir Rot!\\p",
"Stuff Cheeks cannot be\\nselected without a Berry!\\p": "No es pot triar Omplir Galtes\\nsense una baia!\\p",
"But Hoopa can't use it\\nthe way it is now!": "Però Hoopa no ho pot fer servir\\ntal com està ara!",
"This move effect is not done yet!\\p": "Aquest efecte encara no està fet!\\p",
"{B_ATK_NAME_WITH_PREFIX} appears incapable\\nof using its power!": "Sembla que {B_ATK_NAME_WITH_PREFIX} no pot\\nfer servir el seu poder!",

# ---- terrain / rooms ----
"{B_DEF_NAME_WITH_PREFIX} surrounds itself\\nwith a protective mist!": "{B_DEF_NAME_WITH_PREFIX} s'envolta\\nd'una boira protectora!",
"{B_DEF_NAME_WITH_PREFIX} surrounds itself\\nwith electrified terrain!": "{B_DEF_NAME_WITH_PREFIX} s'envolta\\nd'un camp electrificat!",
"{B_DEF_NAME_WITH_PREFIX} surrounds itself\\nwith psychic terrain!": "{B_DEF_NAME_WITH_PREFIX} s'envolta\\nd'un camp psíquic!",
"{B_DEF_NAME_WITH_PREFIX} surrounded itself\\nwith a veil of petals!": "{B_DEF_NAME_WITH_PREFIX} s'ha envoltat\\nd'un vel de pètals!",
"{B_DEF_NAME_WITH_PREFIX} surrounded itself\\nwith a veil of sweetness!": "{B_DEF_NAME_WITH_PREFIX} s'ha envoltat\\nd'un vel de dolçor!",
"{B_DEF_NAME_WITH_PREFIX} is protected\\nby an aromatic veil!": "{B_DEF_NAME_WITH_PREFIX} està protegit\\nper un vel aromàtic!",
"{B_DEF_NAME_WITH_PREFIX} is protected\\nby a pastel veil!": "{B_DEF_NAME_WITH_PREFIX} està protegit\\nper un vel pastel!",
"It created a bizarre area in which the\\nDefense and Sp.Def stats are swapped!": "S'ha creat una zona estranya on la Defensa\\ni la Def. Esp. estan intercanviades!",
"It created a bizarre area in which\\nPokémon's held items lose their effects!": "S'ha creat una zona estranya on els objectes\\ndels Pokémon perden els seus efectes!",
"The twisted dimensions returned to\\nnormal!": "Les dimensions retorçades han tornat\\na la normalitat!",
"Wonder Room wore off, and Defense\\nand Sp. Def stats returned to normal!": "Sala Prodigi s'ha esgotat i la Defensa\\ni la Def. Esp. han tornat a la normalitat!",
"Magic Room wore off, and held items'\\neffects returned to normal!": "Sala Màgica s'ha esgotat i els efectes\\ndels objectes han tornat a la normalitat!",
"The effects of Mud Sport have faded.": "Els efectes de Bany de Fang s'han esvaït.",
"The effects of Water Sport have faded.": "Els efectes de Bany d'Aigua s'han esvaït.",
"A deluge of ions showers\\nthe battlefield!": "Un diluvi d'ions banya\\nel camp de batalla!",
"Mist swirled about\\nthe battlefield!": "La boira ha envoltat\\nel camp de batalla!",
"Grass grew to cover\\nthe battlefield!": "L'herba ha crescut i cobreix\\nel camp de batalla!",
"An electric current runs across\\nthe battlefield!": "Un corrent elèctric recorre\\nel camp de batalla!",
"The battlefield got weird!": "El camp de batalla s'ha tornat estrany!",
"The electricity disappeared\\nfrom the battlefield.": "L'electricitat ha desaparegut\\ndel camp de batalla.",
"The mist disappeared\\nfrom the battlefield.": "La boira ha desaparegut\\ndel camp de batalla.",
"The weirdness disappeared\\nfrom the battlefield.": "L'estranyesa ha desaparegut\\ndel camp de batalla.",
"The grass disappeared\\nfrom the battlefield.": "L'herba ha desaparegut\\ndel camp de batalla.",
"The terrain returned to\\nnormal!": "El camp ha tornat a la\\nnormalitat!",
"The {B_DEF_NAME_WITH_PREFIX}'s moves\\nhave been electrified!": "Els moviments de {B_DEF_NAME_WITH_PREFIX}\\ns'han electrificat!",
"The tailwind blew from\\nbehind {B_ATK_TEAM2} team!": "Bufa vent de cua darrere\\n{B_ATK_TEAM2} equip!",
"{B_ATK_TEAM1} team's tailwind\\npetered out!": "El vent de cua de {B_ATK_TEAM1}\\nequip s'ha esgotat!",
"{B_ATK_TEAM1} team's Lucky Chant\\nwore off!": "El Cant de Sort de {B_ATK_TEAM1}\\nequip s'ha esgotat!",
"The {B_CURRENT_MOVE} shielded {B_ATK_TEAM2}\\nteam from critical hits!": "{B_CURRENT_MOVE} ha protegit {B_ATK_TEAM2}\\nequip dels cops crítics!",
"{B_CURRENT_MOVE} protected\\n{B_ATK_TEAM2} team!": "{B_CURRENT_MOVE} ha protegit\\n{B_ATK_TEAM2} equip!",
"The bursting flames\\nhit {B_SCR_ACTIVE_NAME_WITH_PREFIX}!": "Les flames esclatants han\\nferit {B_SCR_ACTIVE_NAME_WITH_PREFIX}!",
"It sucked up the\\nLiquid Ooze!": "Ha xuclat el\\nLlot Líquid!",

# ---- abilities ----
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nmade it rain!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha fet ploure!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nraised its Speed!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nli ha pujat la Velocitat!",
"{B_DEF_NAME_WITH_PREFIX} was protected\\nby {B_DEF_ABILITY}!": "{B_DEF_ABILITY} ha protegit\\n{B_DEF_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nprevents {B_ATK_NAME_WITH_PREFIX}\\lfrom using {B_CURRENT_MOVE}!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nimpedeix que {B_ATK_NAME_WITH_PREFIX}\\lusi {B_CURRENT_MOVE}!",
"{B_DEF_NAME_WITH_PREFIX} restored HP\\nusing its {B_DEF_ABILITY}!": "{B_DEF_NAME_WITH_PREFIX} ha recuperat PS\\namb {B_DEF_ABILITY}!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nmade {B_CURRENT_MOVE} useless!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nha fet inútil {B_CURRENT_MOVE}!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nmade it the {B_BUFF1} type!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nl'ha fet de tipus {B_BUFF1}!",
"{B_EFF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nprevents paralysis!": "{B_DEF_ABILITY} de {B_EFF_NAME_WITH_PREFIX}\\nimpedeix la paràlisi!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nprevents romance!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nimpedeix l'enamorament!",
"{B_EFF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nprevents poisoning!": "{B_DEF_ABILITY} de {B_EFF_NAME_WITH_PREFIX}\\nimpedeix l'enverinament!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nprevents confusion!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nimpedeix la confusió!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nraised its Fire power!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nli ha pujat el poder de Foc!",
"{B_DEF_NAME_WITH_PREFIX} anchors\\nitself with {B_DEF_ABILITY}!": "{B_DEF_NAME_WITH_PREFIX} s'ancora\\namb {B_DEF_ABILITY}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\ncuts {B_DEF_NAME_WITH_PREFIX}'s Attack!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nbaixa l'Atac de {B_DEF_NAME_WITH_PREFIX}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nprevents stat loss!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nimpedeix perdre estadístiques!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nhurt {B_ATK_NAME_WITH_PREFIX}!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nha fet mal a {B_ATK_NAME_WITH_PREFIX}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} Traced\\n{B_BUFF1}'s {B_BUFF2}!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha calcat\\n{B_BUFF2} de {B_BUFF1}!",
"{B_EFF_NAME_WITH_PREFIX}'s {B_EFF_ABILITY}\\nprevents burns!": "{B_EFF_ABILITY} de {B_EFF_NAME_WITH_PREFIX}\\nimpedeix les cremades!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nblocks {B_CURRENT_MOVE}!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nbloqueja {B_CURRENT_MOVE}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nblocks {B_CURRENT_MOVE}!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nbloqueja {B_CURRENT_MOVE}!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY}\\nrestored its HP a little!": "{B_ATK_ABILITY} de {B_ATK_NAME_WITH_PREFIX}\\nli ha recuperat una mica de PS!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nwhipped up a sandstorm!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha aixecat una tempesta de sorra!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nintensified the sun's rays!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha intensificat els raigs del sol!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nprevents {B_BUFF1} loss!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nimpedeix perdre {B_BUFF1}!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\ninfatuated {B_ATK_NAME_WITH_PREFIX}!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nha enamorat {B_ATK_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nmade {B_CURRENT_MOVE} ineffective!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nha fet ineficaç {B_CURRENT_MOVE}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\ncured its {B_BUFF1} problem!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nli ha curat {B_BUFF1}!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\ntook the attack!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nha rebut l'atac!",
"{B_BUFF1}'s {B_LAST_ABILITY}\\nprevents switching!\\p": "{B_LAST_ABILITY} de {B_BUFF1}\\nimpedeix el canvi!\\p",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nprevented {B_SCR_ACTIVE_NAME_WITH_PREFIX}'s\\l{B_BUFF1} from working!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nha impedit que {B_BUFF1} de\\l{B_SCR_ACTIVE_NAME_WITH_PREFIX} funcionés!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nmade it ineffective!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nho ha fet ineficaç!",
"{B_EFF_NAME_WITH_PREFIX}'s {B_EFF_ABILITY}\\nprevents flinching!": "{B_EFF_ABILITY} de {B_EFF_NAME_WITH_PREFIX}\\nimpedeix l'esglai!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY}\\nprevents {B_DEF_NAME_WITH_PREFIX}'s\\l{B_DEF_ABILITY} from working!": "{B_ATK_ABILITY} de {B_ATK_NAME_WITH_PREFIX}\\nimpedeix que {B_DEF_ABILITY} de\\l{B_DEF_NAME_WITH_PREFIX} funcioni!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nhad no effect on {B_EFF_NAME_WITH_PREFIX}!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nno ha afectat {B_EFF_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX} Endured\\nthe hit using {B_DEF_ABILITY}!": "{B_DEF_NAME_WITH_PREFIX} ha aguantat\\nel cop amb {B_DEF_ABILITY}!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY} activates!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX} s'activa!",
"{B_DEF_NAME_WITH_PREFIX}'s ability\\nwas suppressed!": "L'habilitat de {B_DEF_NAME_WITH_PREFIX}\\nha quedat suprimida!",
"{B_DEF_NAME_WITH_PREFIX} acquired\\n{B_DEF_ABILITY}!": "{B_DEF_NAME_WITH_PREFIX} ha adquirit\\n{B_DEF_ABILITY}!",
"{B_DEF_NAME_WITH_PREFIX} acquired\\nSimple!": "{B_DEF_NAME_WITH_PREFIX} ha adquirit\\nSenzillesa!",
"{B_ATK_NAME_WITH_PREFIX} acquired {B_LAST_ABILITY}!": "{B_ATK_NAME_WITH_PREFIX} ha adquirit {B_LAST_ABILITY}!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nraised its {B_BUFF1}!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nli ha pujat {B_BUFF1}!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nlowered its {B_BUFF1}!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\nli ha baixat {B_BUFF1}!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY}\\nraised its {B_BUFF1}!": "{B_ATK_ABILITY} de {B_ATK_NAME_WITH_PREFIX}\\nli ha pujat {B_BUFF1}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nraised its {B_BUFF1}!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nli ha pujat {B_BUFF1}!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\\nwore off!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX}\\ns'ha esgotat!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY} maxed\\nits {B_BUFF1}!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX} ha\\nmaximitzat {B_BUFF1}!",
"{B_DEF_ABILITY} raised {B_DEF_NAME_WITH_PREFIX}'s\\n{B_BUFF1} drastically!": "{B_DEF_ABILITY} ha pujat moltíssim\\n{B_BUFF1} de {B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_LAST_ABILITY}\\nraised its {B_BUFF1}!": "{B_LAST_ABILITY} de {B_ATK_NAME_WITH_PREFIX}\\nli ha pujat {B_BUFF1}!",
"{B_DEF_NAME_WITH_PREFIX} is tormented\\nby {B_ATK_ABILITY}!": "{B_ATK_ABILITY} turmenta\\n{B_DEF_NAME_WITH_PREFIX}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} breaks the mold!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} trenca el motlle!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} is radiating \\na bursting aura!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} irradia\\nuna aura explosiva!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} is radiating\\na blazing aura!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} irradia\\nuna aura ardent!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} is radiating\\na dark aura!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} irradia\\nuna aura fosca!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} is radiating\\na fairy aura!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} irradia\\nuna aura de fada!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} reversed all\\nother Pokémon's auras!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha invertit les\\naures de tots els altres Pokémon!",
"{B_DEF_NAME_WITH_PREFIX}'s aura flared to life!": "L'aura de {B_DEF_NAME_WITH_PREFIX} s'ha encès!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} can't get it going!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} no s'engega!",
"{B_ATK_NAME_WITH_PREFIX} finally got\\nits act together!": "{B_ATK_NAME_WITH_PREFIX} s'ha posat\\nles piles per fi!",
"The {B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY}\\ntakes its toll!": "{B_ATK_ABILITY} de {B_ATK_NAME_WITH_PREFIX}\\nes fa notar!",
"{B_ATK_NAME_WITH_PREFIX} is hurt!": "{B_ATK_NAME_WITH_PREFIX} rep dany!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} shuddered\\nin anticipation!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha tremolat\\nd'anticipació!",
"{B_SCR_ACTIVE_ABILITY} alerted {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nto the {B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}!": "{B_SCR_ACTIVE_ABILITY} ha avisat {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nde {B_BUFF1} de {B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY}\\nhealed it a little bit!": "{B_ATK_ABILITY} de {B_ATK_NAME_WITH_PREFIX}\\nl'ha curat una mica!",
"The opposing team is too nervous\\nto eat Berries!": "L'equip rival està massa nerviós\\nper menjar baies!",
"The {B_DEF_NAME_WITH_PREFIX} bounced the\\n{B_ATK_NAME_WITH_PREFIX} back!": "{B_DEF_NAME_WITH_PREFIX} ha fet rebotar\\n{B_ATK_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY} transformed\\nit into the {B_BUFF1} type!": "{B_ATK_ABILITY} de {B_ATK_NAME_WITH_PREFIX} l'ha\\nconvertit en tipus {B_BUFF1}!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_BUFF1} was disabled\\nby {B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX} ha anul·lat\\n{B_BUFF1} de {B_ATK_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_CURRENT_MOVE} was\\nbounced back by {B_DEF_NAME_WITH_PREFIX}'s\\l{B_DEF_ABILITY}!": "{B_DEF_ABILITY} de {B_DEF_NAME_WITH_PREFIX} ha\\nfet rebotar {B_CURRENT_MOVE} de\\l{B_ATK_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} transformed into\\n{B_DEF_NAME_WITH_PREFIX} using {B_LAST_ABILITY}!": "{B_ATK_NAME_WITH_PREFIX} s'ha transformat en\\n{B_DEF_NAME_WITH_PREFIX} amb {B_LAST_ABILITY}!",
"{B_DEF_NAME_WITH_PREFIX}'s Illusion wore off!": "La Il·lusió de {B_DEF_NAME_WITH_PREFIX} s'ha esgotat!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_LAST_ABILITY}\\ncured {B_SCR_ACTIVE_NAME_WITH_PREFIX}'s problem!": "{B_LAST_ABILITY} de {B_ATK_NAME_WITH_PREFIX}\\nha curat {B_SCR_ACTIVE_NAME_WITH_PREFIX}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nwas taken over!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha estat presa!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} is exerting its\\npressure!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} exerceix la seva\\npressió!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} has two Abilities!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} té dues Habilitats!",
"{B_DEF_NAME_WITH_PREFIX} swapped Abilities\\nwith its target!": "{B_DEF_NAME_WITH_PREFIX} ha bescanviat Habilitats\\namb el seu objectiu!",
"Neutralizing Gas filled the area!": "El Gas Neutralitzant ha omplert la zona!",
"The effects of Neutralizing\\nGas wore off!": "Els efectes del Gas Neutralitzant\\ns'han esgotat!",
"{B_ATK_NAME_WITH_PREFIX} went back\\nto {B_ATK_TRAINER_CLASS} {B_ATK_TRAINER_NAME}": "{B_ATK_NAME_WITH_PREFIX} ha tornat amb\\n{B_ATK_TRAINER_CLASS} {B_ATK_TRAINER_NAME}",

# ---- disobedience ----
"{B_ATK_NAME_WITH_PREFIX} ignored\\norders while asleep!": "{B_ATK_NAME_WITH_PREFIX} ha ignorat les\\nordres mentre dormia!",
"{B_ATK_NAME_WITH_PREFIX} ignored\\norders!": "{B_ATK_NAME_WITH_PREFIX} ha ignorat\\nles ordres!",
"{B_ATK_NAME_WITH_PREFIX} is\\nloafing around!": "{B_ATK_NAME_WITH_PREFIX} està\\nfent el gandul!",
"{B_ATK_NAME_WITH_PREFIX} won't\\nobey!": "{B_ATK_NAME_WITH_PREFIX} no vol\\nobeir!",
"{B_ATK_NAME_WITH_PREFIX} turned away!": "{B_ATK_NAME_WITH_PREFIX} ha girat la cara!",
"{B_ATK_NAME_WITH_PREFIX} pretended\\nnot to notice!": "{B_ATK_NAME_WITH_PREFIX} ha fet\\ncom si no ho sentís!",
"There's no PP left for\\nthis move!\\p": "No queden PP per a\\naquest moviment!\\p",
"But there was no PP left\\nfor the move!": "Però no quedaven PP per\\nal moviment!",
"{B_ACTIVE_NAME_WITH_PREFIX} has no\\nmoves left!\\p": "{B_ACTIVE_NAME_WITH_PREFIX} no li\\nqueden moviments!\\p",
"{B_ACTIVE_NAME_WITH_PREFIX}'s {B_CURRENT_MOVE}\\nis disabled!\\p": "{B_CURRENT_MOVE} de {B_ACTIVE_NAME_WITH_PREFIX}\\nestà anul·lat!\\p",
"{B_ACTIVE_NAME_WITH_PREFIX} can't use the same\\nmove in a row due to the Torment!\\p": "{B_ACTIVE_NAME_WITH_PREFIX} no pot repetir el\\nmateix moviment pel Turment!\\p",
"{B_ACTIVE_NAME_WITH_PREFIX} can't use\\n{B_CURRENT_MOVE} after the Taunt!\\p": "{B_ACTIVE_NAME_WITH_PREFIX} no pot usar\\n{B_CURRENT_MOVE} després de la Mofa!\\p",
"{B_ACTIVE_NAME_WITH_PREFIX} can't use the\\nsealed {B_CURRENT_MOVE}!\\p": "{B_ACTIVE_NAME_WITH_PREFIX} no pot usar\\n{B_CURRENT_MOVE}, que està segellat!\\p",
"{B_ACTIVE_NAME_WITH_PREFIX} can't use\\n{B_CURRENT_MOVE} due to Throat Chop!\\p": "{B_ACTIVE_NAME_WITH_PREFIX} no pot usar\\n{B_CURRENT_MOVE} per Cop de Gola!\\p",

# ---- encounters ----
"{B_OPPONENT_MON1_NAME} appeared!\\p": "Ha aparegut {B_OPPONENT_MON1_NAME}!\\p",
"Wild {B_OPPONENT_MON1_NAME} appeared!\\p": "Ha aparegut {B_OPPONENT_MON1_NAME} salvatge!\\p",
"Wild {B_OPPONENT_MON1_NAME} appeared!{PAUSE 127}": "Ha aparegut {B_OPPONENT_MON1_NAME} salvatge!{PAUSE 127}",
"Wild {B_OPPONENT_MON1_NAME} and\\n{B_OPPONENT_MON2_NAME} appeared!\\p": "Han aparegut {B_OPPONENT_MON1_NAME} i\\n{B_OPPONENT_MON2_NAME} salvatges!\\p",
"{B_TRAINER1_CLASS} {B_TRAINER1_NAME}\\nwould like to battle!\\p": "{B_TRAINER1_CLASS} {B_TRAINER1_NAME}\\nvol combatre!\\p",
"{B_LINK_OPPONENT1_NAME}\\nwants to battle!": "{B_LINK_OPPONENT1_NAME}\\nvol combatre!",
"{B_LINK_OPPONENT1_NAME} and {B_LINK_OPPONENT2_NAME}\\nwant to battle!": "{B_LINK_OPPONENT1_NAME} i {B_LINK_OPPONENT2_NAME}\\nvolen combatre!",
"{B_LINK_OPPONENT1_NAME}\\nwants to battle!{PAUSE 49}": "{B_LINK_OPPONENT1_NAME}\\nvol combatre!{PAUSE 49}",
"{B_LINK_OPPONENT1_NAME} and {B_LINK_OPPONENT2_NAME}\\nwant to battle!{PAUSE 49}": "{B_LINK_OPPONENT1_NAME} i {B_LINK_OPPONENT2_NAME}\\nvolen combatre!{PAUSE 49}",
"{B_TRAINER1_CLASS} {B_TRAINER1_NAME} sent\\nout {B_OPPONENT_MON1_NAME}!": "{B_TRAINER1_CLASS} {B_TRAINER1_NAME} ha tret\\n{B_OPPONENT_MON1_NAME}!",
"{B_TRAINER1_CLASS} {B_TRAINER1_NAME} sent\\nout {B_OPPONENT_MON1_NAME} and {B_OPPONENT_MON2_NAME}!": "{B_TRAINER1_CLASS} {B_TRAINER1_NAME} ha tret\\n{B_OPPONENT_MON1_NAME} i {B_OPPONENT_MON2_NAME}!",
"{B_TRAINER1_CLASS} {B_TRAINER1_NAME} sent\\nout {B_BUFF1}!": "{B_TRAINER1_CLASS} {B_TRAINER1_NAME} ha tret\\n{B_BUFF1}!",
"{B_LINK_OPPONENT1_NAME} sent out\\n{B_OPPONENT_MON1_NAME}!": "{B_LINK_OPPONENT1_NAME} ha tret\\n{B_OPPONENT_MON1_NAME}!",
"{B_LINK_OPPONENT1_NAME} sent out\\n{B_OPPONENT_MON1_NAME} and {B_OPPONENT_MON2_NAME}!": "{B_LINK_OPPONENT1_NAME} ha tret\\n{B_OPPONENT_MON1_NAME} i {B_OPPONENT_MON2_NAME}!",
"{B_LINK_OPPONENT1_NAME} sent out {B_LINK_OPPONENT_MON1_NAME}!\\n{B_LINK_OPPONENT2_NAME} sent out {B_LINK_OPPONENT_MON2_NAME}!": "{B_LINK_OPPONENT1_NAME} ha tret {B_LINK_OPPONENT_MON1_NAME}!\\n{B_LINK_OPPONENT2_NAME} ha tret {B_LINK_OPPONENT_MON2_NAME}!",
"{B_LINK_OPPONENT1_NAME} sent out\\n{B_BUFF1}!": "{B_LINK_OPPONENT1_NAME} ha tret\\n{B_BUFF1}!",
"{B_LINK_SCR_TRAINER_NAME} sent out\\n{B_BUFF1}!": "{B_LINK_SCR_TRAINER_NAME} ha tret\\n{B_BUFF1}!",
"Go! {B_PLAYER_MON1_NAME}!": "Vinga, {B_PLAYER_MON1_NAME}!",
"Go! {B_PLAYER_MON1_NAME} and\\n{B_PLAYER_MON2_NAME}!": "Vinga, {B_PLAYER_MON1_NAME} i\\n{B_PLAYER_MON2_NAME}!",
"Go! {B_BUFF1}!": "Vinga, {B_BUFF1}!",
"Do it! {B_BUFF1}!": "Endavant, {B_BUFF1}!",
"Go for it, {B_BUFF1}!": "A per ells, {B_BUFF1}!",
"Your foe's weak!\\nGet 'em, {B_BUFF1}!": "El rival està feble!\\nA per ell, {B_BUFF1}!",
"{B_LINK_PARTNER_NAME} sent out {B_LINK_PLAYER_MON2_NAME}!\\nGo! {B_LINK_PLAYER_MON1_NAME}!": "{B_LINK_PARTNER_NAME} ha tret {B_LINK_PLAYER_MON2_NAME}!\\nVinga, {B_LINK_PLAYER_MON1_NAME}!",
"{B_BUFF1}, that's enough!\\nCome back!": "{B_BUFF1}, ja n'hi ha prou!\\nTorna!",
"{B_BUFF1}, come back!": "{B_BUFF1}, torna!",
"{B_BUFF1}, Ok!\\nCome back!": "{B_BUFF1}, molt bé!\\nTorna!",
"{B_BUFF1}, good!\\nCome back!": "{B_BUFF1}, bona feina!\\nTorna!",
"{B_TRAINER1_CLASS} {B_TRAINER1_NAME}\\nwithdrew {B_BUFF1}!": "{B_TRAINER1_CLASS} {B_TRAINER1_NAME}\\nha retirat {B_BUFF1}!",
"{B_LINK_OPPONENT1_NAME} withdrew\\n{B_BUFF1}!": "{B_LINK_OPPONENT1_NAME} ha retirat\\n{B_BUFF1}!",
"{B_LINK_SCR_TRAINER_NAME} withdrew\\n{B_BUFF1}!": "{B_LINK_SCR_TRAINER_NAME} ha retirat\\n{B_BUFF1}!",
"{B_TRAINER1_CLASS} {B_TRAINER1_NAME} is\\nabout to use {B_BUFF2}.\\pWill {B_PLAYER_NAME} change\\nPokémon?": "{B_TRAINER1_CLASS} {B_TRAINER1_NAME} està\\na punt d'usar {B_BUFF2}.\\pVol canviar de Pokémon,\\n{B_PLAYER_NAME}?",
"Player defeated\\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}!\\p": "Has derrotat\\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}!\\p",
"Player defeated\\n{B_LINK_OPPONENT1_NAME}!": "Has derrotat\\n{B_LINK_OPPONENT1_NAME}!",
"Player beat {B_LINK_OPPONENT1_NAME}\\nand {B_LINK_OPPONENT2_NAME}!": "Has vençut {B_LINK_OPPONENT1_NAME}\\ni {B_LINK_OPPONENT2_NAME}!",
"Player lost against\\n{B_LINK_OPPONENT1_NAME}!": "Has perdut contra\\n{B_LINK_OPPONENT1_NAME}!",
"Player lost to {B_LINK_OPPONENT1_NAME}\\nand {B_LINK_OPPONENT2_NAME}!": "Has perdut contra {B_LINK_OPPONENT1_NAME}\\ni {B_LINK_OPPONENT2_NAME}!",
"Player battled to a draw against\\n{B_LINK_OPPONENT1_NAME}!": "Has empatat contra\\n{B_LINK_OPPONENT1_NAME}!",
"Player battled to a draw against\\n{B_LINK_OPPONENT1_NAME} and {B_LINK_OPPONENT2_NAME}!": "Has empatat contra\\n{B_LINK_OPPONENT1_NAME} i {B_LINK_OPPONENT2_NAME}!",
"Player lost against\\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}!": "Has perdut contra\\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}!",
"Player battled to a draw against\\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}!": "Has empatat contra\\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}!",
"{PLAY_SE SE_FLEE}{B_LINK_OPPONENT1_NAME} fled!": "{PLAY_SE SE_FLEE}{B_LINK_OPPONENT1_NAME} ha fugit!",
"{PLAY_SE SE_FLEE}{B_LINK_OPPONENT1_NAME} and\\n{B_LINK_OPPONENT2_NAME} fled!": "{PLAY_SE SE_FLEE}{B_LINK_OPPONENT1_NAME} i\\n{B_LINK_OPPONENT2_NAME} han fugit!",
"{PLAY_SE SE_FLEE}{B_TRAINER1_CLASS} {B_TRAINER1_NAME} fled!": "{PLAY_SE SE_FLEE}{B_TRAINER1_CLASS} {B_TRAINER1_NAME} ha fugit!",
"Prof. Birch: Don't leave me like this!\\p": "Prof. Birch: No em deixis així!\\p",

# ---- safari ----
"{B_PLAYER_NAME} crept closer to\\n{B_OPPONENT_MON1_NAME}!": "{B_PLAYER_NAME} s'ha acostat a\\n{B_OPPONENT_MON1_NAME}!",
"{B_PLAYER_NAME} can't get any closer!": "{B_PLAYER_NAME} no pot acostar-se més!",
"{B_OPPONENT_MON1_NAME} is watching\\ncarefully!": "{B_OPPONENT_MON1_NAME} està observant\\namb atenció!",
"{B_OPPONENT_MON1_NAME} is curious about\\nthe {B_BUFF1}!": "{B_OPPONENT_MON1_NAME} sent curiositat\\nper {B_BUFF1}!",
"{B_OPPONENT_MON1_NAME} is enthralled by\\nthe {B_BUFF1}!": "{B_OPPONENT_MON1_NAME} està encisat\\nper {B_BUFF1}!",
"{B_OPPONENT_MON1_NAME} completely ignored\\nthe {B_BUFF1}!": "{B_OPPONENT_MON1_NAME} ha ignorat\\ncompletament {B_BUFF1}!",
"{B_PLAYER_NAME} threw a {POKEBLOCK}\\nat the {B_OPPONENT_MON1_NAME}!": "{B_PLAYER_NAME} ha llançat un {POKEBLOCK}\\na {B_OPPONENT_MON1_NAME}!",
"{PLAY_SE SE_DING_DONG}Announcer: You're out of\\nSafari Balls! Game over!\\p": "{PLAY_SE SE_DING_DONG}Locutor: T'has quedat sense\\nSafari Balls! Fi del joc!\\p",
"{HIGHLIGHT DARK_GRAY}Safari Balls": "{HIGHLIGHT DARK_GRAY}Safari Balls",
"{HIGHLIGHT DARK_GRAY}Left: ${HIGHLIGHT DARK_GRAY}": "{HIGHLIGHT DARK_GRAY}Queden: ${HIGHLIGHT DARK_GRAY}",

# ---- capture ----
"{B_PLAYER_NAME} used\\n{B_LAST_ITEM}!": "{B_PLAYER_NAME} ha fet servir\\n{B_LAST_ITEM}!",
"Professor Oak used\\n{B_LAST_ITEM}!": "El Professor Oak ha fet servir\\n{B_LAST_ITEM}!",
"{B_TRAINER1_CLASS} {B_TRAINER1_NAME}\\nused {B_LAST_ITEM}!": "{B_TRAINER1_CLASS} {B_TRAINER1_NAME}\\nha fet servir {B_LAST_ITEM}!",
"The Trainer blocked the Ball!": "L'entrenador ha bloquejat la Ball!",
"Don't be a thief!": "No siguis lladre!",
"It dodged the thrown Ball!\\nThis Pokémon can't be caught!": "Ha esquivat la Ball!\\nAquest Pokémon no es pot capturar!",
"You missed the Pokémon!": "No has encertat el Pokémon!",
"Oh, no!\\nThe Pokémon broke free!": "Oh, no!\\nEl Pokémon s'ha escapat!",
"Aww!\\nIt appeared to be caught!": "Vaja!\\nSemblava que estava capturat!",
"Aargh!\\nAlmost had it!": "Ai!\\nGairebé el tenies!",
"Shoot!\\nIt was so close, too!": "Llàstima!\\nHi era a punt!",
"Gotcha!\\n{B_DEF_NAME} was caught!{WAIT_SE}{PLAY_BGM MUS_CAUGHT}\\p": "Ben fet!\\nHas capturat {B_DEF_NAME}!{WAIT_SE}{PLAY_BGM MUS_CAUGHT}\\p",
"Gotcha!\\n{B_DEF_NAME} was caught!{WAIT_SE}{PLAY_BGM MUS_CAUGHT}{PAUSE 127}": "Ben fet!\\nHas capturat {B_DEF_NAME}!{WAIT_SE}{PLAY_BGM MUS_CAUGHT}{PAUSE 127}",
"Give a nickname to the\\ncaptured {B_DEF_NAME}?": "Vols posar un sobrenom a\\n{B_DEF_NAME}, que has capturat?",
"{B_DEF_NAME} was sent to\\n{B_PC_CREATOR_NAME} PC.": "{B_DEF_NAME} s'ha enviat al\\nPC {B_PC_CREATOR_NAME}.",
"someone's": "d'algú",
"Bill's": "del Bill",
"{B_OPPONENT_MON1_NAME}'s data was\\nadded to the Pokédex.\\p": "Les dades de {B_OPPONENT_MON1_NAME}\\ns'han afegit al Pokédex.\\p",
"The box is full!\\nYou can't catch any more!\\p": "La caixa és plena!\\nNo pots capturar-ne més!\\p",
"Pay attention, {B_PLAYER_NAME}.\\nThis is how you catch a Pokémon!": "Fixa-t'hi bé, {B_PLAYER_NAME}.\\nAixí es captura un Pokémon!",

# ---- mega / primal / z-moves ----
"{B_ATK_NAME_WITH_PREFIX}'s {B_LAST_ITEM} is \\nreacting to {B_ATK_TRAINER_NAME}'s Mega Ring!": "{B_LAST_ITEM} de {B_ATK_NAME_WITH_PREFIX} reacciona\\na l'Anell Mega de {B_ATK_TRAINER_NAME}!",
"{B_ATK_TRAINER_NAME}'s fervent wish\\nhas reached {B_ATK_NAME_WITH_PREFIX}!": "El desig fervent de {B_ATK_TRAINER_NAME}\\nha arribat a {B_ATK_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} has Mega Evolved into\\nMega {B_BUFF1}!": "{B_ATK_NAME_WITH_PREFIX} ha Megaevolucionat a\\nMega {B_BUFF1}!",
"{B_ATK_NAME_WITH_PREFIX}'s Primal Reversion!\\nIt reverted to its primal form!": "Regressió Primigènia de {B_ATK_NAME_WITH_PREFIX}!\\nHa tornat a la forma primigènia!",
"{B_ATK_NAME_WITH_PREFIX} surrounds\\nitself with its Z-Power!": "{B_ATK_NAME_WITH_PREFIX} s'envolta\\ndel seu Poder Z!",
"{B_ATK_NAME_WITH_PREFIX} unleashes\\nits full-force Z-Move!": "{B_ATK_NAME_WITH_PREFIX} deixa anar\\nel seu Moviment Z a tota potència!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} returned its\\ndecreased stats to normal using\\lits Z-Power!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha tornat les\\nestadístiques baixades a la normalitat\\lamb el seu Poder Z!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} boosted all\\nof its stats using its Z-Power!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha pujat totes\\nles estadístiques amb el seu Poder Z!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} boosted its\\ncritical-hit ratio using its Z-Power!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha pujat el seu\\nratio de crítics amb el seu Poder Z!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} restored its\\nHP using its Z-Power!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha recuperat\\nPS amb el seu Poder Z!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} boosted\\nits stats using its Z-Power!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha pujat les\\nseves estadístiques amb el seu Poder Z!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s HP was restored by the Z-Power!": "El Poder Z ha recuperat els PS de {B_SCR_ACTIVE_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} became fully charged\\ndue to its bond with its trainer!\\p": "{B_ATK_NAME_WITH_PREFIX} s'ha carregat del tot\\npel vincle amb el seu entrenador!\\p",
"{B_ATK_NAME_WITH_PREFIX} became Ash-{B_BUFF1}!\\p": "{B_ATK_NAME_WITH_PREFIX} s'ha convertit en Ash-{B_BUFF1}!\\p",
"A glint appears in\\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s eyes!": "Una llumeta apareix als\\nulls de {B_SCR_ACTIVE_NAME_WITH_PREFIX}!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} is getting into\\nposition!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} s'està posant\\nen posició!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} began growling deeply!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha començat a rugir greument!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} is eager for more!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} en vol més!",

# ---- evolution ----
"What?\\n{STR_VAR_1} is evolving!": "Què?\\n{STR_VAR_1} està evolucionant!",
"Congratulations! Your {STR_VAR_1}\\nevolved into {STR_VAR_2}!{WAIT_SE}\\p": "Enhorabona! El teu {STR_VAR_1}\\nha evolucionat a {STR_VAR_2}!{WAIT_SE}\\p",
"Huh? {STR_VAR_1}\\nstopped evolving!\\p": "Eh? {STR_VAR_1}\\nha deixat d'evolucionar!\\p",
"Congratulations, {B_PLAYER_NAME}!": "Enhorabona, {B_PLAYER_NAME}!",

# ---- battle menus ----
"What will\\n{B_ACTIVE_NAME2} do?": "Què farà\\n{B_ACTIVE_NAME2}?",
"What will\\n{B_PLAYER_NAME} do?": "Què farà\\n{B_PLAYER_NAME}?",
"Professor Oak\\nis thinking...": "El Professor Oak\\nestà pensant...",
"{PAUSE 16}Link standby…": "{PAUSE 16}Enllaç en espera…",
"Fight{CLEAR_TO 56}Bag\\nPokémon{CLEAR_TO 56}Run": "Lluitar{CLEAR_TO 56}Motxilla\\nPokémon{CLEAR_TO 56}Fugir",
"Ball{CLEAR_TO 56}{POKEBLOCK}\\nGo near{CLEAR_TO 56}Run": "Ball{CLEAR_TO 56}{POKEBLOCK}\\nAcostar{CLEAR_TO 56}Fugir",
"PP ": "PP ",
"Type/": "Tipus/",
"{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR4 DYNAMIC_COLOR5 DYNAMIC_COLOR6}PP\\nType/": "{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR4 DYNAMIC_COLOR5 DYNAMIC_COLOR6}PP\\nTipus/",
"{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR4 DYNAMIC_COLOR5 DYNAMIC_COLOR6}Which move should\\nbe forgotten?": "{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR4 DYNAMIC_COLOR5 DYNAMIC_COLOR6}Quin moviment vols\\noblidar?",
"{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR4 DYNAMIC_COLOR5 DYNAMIC_COLOR6}Yes\\nNo": "{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR4 DYNAMIC_COLOR5 DYNAMIC_COLOR6}Sí\\nNo",
"{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR4 DYNAMIC_COLOR5 DYNAMIC_COLOR6}Switch\\nwhich?": "{PALETTE 5}{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR4 DYNAMIC_COLOR5 DYNAMIC_COLOR6}Quin vols\\nbescanviar?",
"HM moves can't be\\nforgotten now.\\p": "Ara no es poden oblidar\\nels moviments MO.\\p",
"{PAUSE 32}1, {PAUSE 15}2, and{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Poof!\\p": "{PAUSE 32}1, {PAUSE 15}2 i{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Puf!\\p",
"And…\\p": "I…\\p",

# ---- status words used in sentences ----
"sleep": "la son",
"poison": "el verí",
"burn": "la cremada",
"paralysis": "la paràlisi",
"ice": "el gel",
"confusion": "la confusió",
"love": "l'amor",
" and ": " i ",
"are": "són",
" is": " és",
"Bad Egg": "Ou Dolent",
"Professor Oak": "Professor Oak",
"{HIGHLIGHT TRANSPARENT}Win": "{HIGHLIGHT TRANSPARENT}Vict.",
"{HIGHLIGHT TRANSPARENT}Loss": "{HIGHLIGHT TRANSPARENT}Derr.",
"{HIGHLIGHT TRANSPARENT}Draw": "{HIGHLIGHT TRANSPARENT}Emp.",
"was too spicy!": "era massa picant!",
"was too dry!": "era massa sec!",
"was too sweet!": "era massa dolç!",
"was too bitter!": "era massa amarg!",
"was too sour!": "era massa àcid!",
"Enigma Berry": "Baia Enigma",
" Berry": " Baia",

# ---- move type descriptions ----
"a Normal move": "un moviment Normal",
"a Fighting move": "un moviment Lluita",
"a Flying move": "un moviment Volador",
"a Poison move": "un moviment Verí",
"a Ground move": "un moviment Terra",
"a Rock move": "un moviment Roca",
"a Bug move": "un moviment Insecte",
"a Ghost move": "un moviment Fantasma",
"a Steel move": "un moviment Acer",
"a ??? move": "un moviment ???",
"a Fire move": "un moviment Foc",
"a Water move": "un moviment Aigua",
"a Grass move": "un moviment Planta",
"an Electric move": "un moviment Elèctric",
"a Psychic move": "un moviment Psíquic",
"an Ice move": "un moviment Gel",
"a Dragon move": "un moviment Drac",
"a Dark move": "un moviment Sinistre",
"a Fairy move": "un moviment Fada",

# ---- tourney / arena ----
"Battle Tourney": "Torneig de Combat",
"Round 1": "Ronda 1",
"Round 2": "Ronda 2",
"Semifinal": "Semifinal",
"Final": "Final",
"The great new hope!\\p": "La gran nova esperança!\\p",
"Will the championship dream come true?!\\p": "Es farà realitat el somni del campionat?!\\p",
"A former Champion!\\p": "Un antic campió!\\p",
"The previous Champion!\\p": "L'anterior campió!\\p",
"The unbeaten Champion!\\p": "El campió invicte!\\p",
"Mind": "Ment",
"Skill": "Destresa",
"Body": "Cos",
"{B_BUFF1}{CLEAR 13}Judgment{CLEAR 13}{B_BUFF2}": "{B_BUFF1}{CLEAR 13}Veredicte{CLEAR 13}{B_BUFF2}",
"{B_TRAINER1_CLASS} {B_TRAINER1_NAME} sent\\nout {B_OPPONENT_MON1_NAME}!\\p{B_TRAINER2_CLASS} {B_TRAINER2_NAME} sent\\nout {B_OPPONENT_MON2_NAME}!": "{B_TRAINER1_CLASS} {B_TRAINER1_NAME} ha tret\\n{B_OPPONENT_MON1_NAME}!\\p{B_TRAINER2_CLASS} {B_TRAINER2_NAME} ha tret\\n{B_OPPONENT_MON2_NAME}!",
"{B_TRAINER2_CLASS} {B_TRAINER2_NAME} sent\\nout {B_BUFF1}!": "{B_TRAINER2_CLASS} {B_TRAINER2_NAME} ha tret\\n{B_BUFF1}!",
"{B_TRAINER1_CLASS} {B_TRAINER1_NAME} and\\n{B_TRAINER2_CLASS} {B_TRAINER2_NAME}\\lwant to battle!\\p": "{B_TRAINER1_CLASS} {B_TRAINER1_NAME} i\\n{B_TRAINER2_CLASS} {B_TRAINER2_NAME}\\lvolen combatre!\\p",
"{B_PARTNER_CLASS} {B_PARTNER_NAME} sent\\nout {B_PLAYER_MON2_NAME}!\\lGo, {B_PLAYER_MON1_NAME}!": "{B_PARTNER_CLASS} {B_PARTNER_NAME} ha tret\\n{B_PLAYER_MON2_NAME}!\\lVinga, {B_PLAYER_MON1_NAME}!",
"{B_TRAINER1_CLASS} {B_TRAINER1_NAME} and\\n{B_TRAINER2_CLASS} {B_TRAINER2_NAME}\\lwere defeated!\\p": "{B_TRAINER1_CLASS} {B_TRAINER1_NAME} i\\n{B_TRAINER2_CLASS} {B_TRAINER2_NAME}\\lhan estat derrotats!\\p",
"Referee: If nothing is decided in\\n3 turns, we will go to judging!": "Àrbitre: Si no es decideix en\\n3 torns, passarem a la valoració!",
"Referee: That's it! We will now go to\\njudging to determine the winner!": "Àrbitre: Prou! Ara passarem a la\\nvaloració per decidir el guanyador!",
"Referee: Judging category 1, Mind!\\nThe Pokémon showing the most guts!\\p": "Àrbitre: Categoria 1, Ment!\\nEl Pokémon amb més coratge!\\p",
"Referee: Judging category 2, Skill!\\nThe Pokémon using moves the best!\\p": "Àrbitre: Categoria 2, Destresa!\\nEl Pokémon que usa millor els moviments!\\p",
"Referee: Judging category 3, Body!\\nThe Pokémon with the most vitality!\\p": "Àrbitre: Categoria 3, Cos!\\nEl Pokémon amb més vitalitat!\\p",
"Referee: Judgment: {B_BUFF1} to {B_BUFF2}!\\nThe winner is {B_PLAYER_NAME}'s {B_PLAYER_MON1_NAME}!\\p": "Àrbitre: Veredicte: {B_BUFF1} a {B_BUFF2}!\\nGuanya {B_PLAYER_MON1_NAME} de {B_PLAYER_NAME}!\\p",
"Referee: Judgment: {B_BUFF1} to {B_BUFF2}!\\nThe winner is {B_TRAINER1_NAME}'s {B_OPPONENT_MON1_NAME}!\\p": "Àrbitre: Veredicte: {B_BUFF1} a {B_BUFF2}!\\nGuanya {B_OPPONENT_MON1_NAME} de {B_TRAINER1_NAME}!\\p",
"Referee: Judgment: 3 to 3!\\nWe have a draw!\\p": "Àrbitre: Veredicte: 3 a 3!\\nHi ha empat!\\p",
"{B_PLAYER_MON1_NAME} defeated the opponent\\n{B_OPPONENT_MON1_NAME} in a Referee's decision!": "{B_PLAYER_MON1_NAME} ha derrotat\\n{B_OPPONENT_MON1_NAME} per decisió arbitral!",
"{B_PLAYER_MON1_NAME} lost to the opponent\\n{B_OPPONENT_MON1_NAME} in a Referee's decision!": "{B_PLAYER_MON1_NAME} ha perdut contra\\n{B_OPPONENT_MON1_NAME} per decisió arbitral!",
"{B_PLAYER_MON1_NAME} tied the opponent\\n{B_OPPONENT_MON1_NAME} in a Referee's decision!": "{B_PLAYER_MON1_NAME} ha empatat amb\\n{B_OPPONENT_MON1_NAME} per decisió arbitral!",
"Referee: {B_PLAYER_MON1_NAME} VS {B_OPPONENT_MON1_NAME}!\\nCommence battling!": "Àrbitre: {B_PLAYER_MON1_NAME} VS {B_OPPONENT_MON1_NAME}!\\nComenceu a combatre!",
"Would you like to forfeit the match\\nand quit now?": "Vols abandonar el combat\\ni plegar ara?",
"{B_PLAYER_NAME} forfeited the match!": "{B_PLAYER_NAME} ha abandonat el combat!",
"Would you like to record your battle\\non your Frontier Pass?": "Vols gravar el combat al teu\\nPassi de Frontera?",
"{B_PLAYER_NAME}'s battle result was recorded\\non the Frontier Pass.": "El resultat del combat de {B_PLAYER_NAME}\\ns'ha gravat al Passi de Frontera.",
}
