# -*- coding: utf-8 -*-
# Catalan move names for the B_EXPANDED_MOVE_NAMES block. LIMIT: 16 characters.
KIND = 'c'
FILES = ['src/data/text/move_names.h']
LIMIT = 16

T = {
"10000000 Volt Thunderbolt": "Llampec Gegant",
"Acid Downpour": "Diluvi Àcid",
"All Out Pummeling": "Pallissa Total",
"Ancient Power": "Poder Antic",
"Aromatic Mist": "Boira Aromàtica",
"Astral Barrage": "Barratge Astral",
"Baby-Doll Eyes": "Ulls de Nina",
"Baneful Bunker": "Búnquer Fatal",
"Behemoth Bash": "Cop Behemoth",
"Behemoth Blade": "Fulla Behemoth",
"Black Hole Eclipse": "Eclipsi Negre",
"Bloom Doom": "Floració Fatal",
"Bouncy Bubble": "Bombolla Bot",
"Breaking Swipe": "Cop Trencador",
"Breakneck Blitz": "Envit Temerari",
"Burning Jealousy": "Gelosia Ardent",
"Catastropika": "Catastropika",
"Clanging Scales": "Escates Sonores",
"Clangorous Soul": "Ànima Tenaç",
"Clangorous Soulblaze": "Ànima Flamejant",
"Continental Crush": "Xoc Continental",
"Core Enforcer": "Nucli Imposar",
"Corkscrew Crash": "Xoc Barrina",
"Corrosive Gas": "Gas Corrosiu",
"Crafty Shield": "Escut Astut",
"Darkest Lariat": "Llaç Fosc",
"Dazzling Gleam": "Enlluernament",
"Devastating Drake": "Drac Devastador",
"Diamond Storm": "TempestaDiamant",
"Disarming Voice": "Veu Desarmant",
"Double Iron Bash": "Cop Ferro Doble",
"Dragon Ascent": "Ascens de Drac",
"Dragon Breath": "Alè de Drac",
"Dragon Energy": "Energia de Drac",
"Dragon Hammer": "Martell de Drac",
"Draining Kiss": "Bes Drenant",
"Dual Wingbeat": "Doble Aleteig",
"Dynamax Cannon": "Canó Dinamax",
"Dynamic Punch": "Cop Dinàmic",
"Eerie Impulse": "Impuls Sinistre",
"Electric Terrain": "Camp Elèctric",
"Expanding Force": "Força Expansiva",
"Extreme Evoboost": "EvoimpulsExtrem",
"Extreme Speed": "VelocitatMàxima",
"False Surrender": "Rendició Falsa",
"Feather Dance": "Dansa de Ploma",
"First Impression": "PrimeraImpressi",
"Fishious Rend": "Tall Brànquia",
"Floral Healng": "Cura Floral",
"Flower Shield": "Escut Floral",
"Forest's Curse": "MalediccióBosc",
"Freezing Glare": "Mirada Gelada",
"Genesis Supernova": "SupernovaGènesi",
"Gigavolt Havoc": "Gigavolt Cruel",
"Glacial Lance": "Llança Glacial",
"Grass Whistle": "Xiulet d'Herba",
"Grassy Terrain": "Camp Herbós",
"Guardian Of Alola": "Guardià d'Alola",
"High Horsepower": "CavallsdeForça",
"High Jump Kick": "Puntada Alta",
"Hydro Vortex": "Vòrtex Hídric",
"Hyperspace Fury": "FúriaHiperspaci",
"Hyprspace Hole": "ForatHiperspaci",
"Inferno Overdrive": "InfernDescontro",
"Jungle Healng": "Cura de Selva",
"King's Shield": "Escut Reial",
"Let's Snuggle Forever": "AbraçadaEterna",
"Light Of Ruin": "Llum de Ruïna",
"Light That Burns The Sky": "Llum Crema Cel",
"Magnetic Flux": "Flux Magnètic",
"Malicious Moonsault": "Salt Maliciós",
"Menacing Moonraze Maelstrom": "Maelstrom Lunar",
"Meteor Assault": "Assalt Meteor",
"Misty Explosion": "ExplosióMística",
"Misty Terrain": "Camp Boirós",
"Moongeist Beam": "Raig Lunar",
"Mystical Fire": "Foc Místic",
"Nature's Madness": "FúriadeNatura",
"Never Ending Nightmare": "Malson Etern",
"Oblivion Wing": "Ala de l'Oblit",
"Oceanic Operetta": "OpuscleOceànic",
"Parabolic Charge": "CàrregaParabòl",
"Petal Blizzard": "TempestaPètals",
"Phantom Force": "Força Fantasma",
"Photon Geyser": "GèiserdeFotons",
"Poison Powder": "Pols Verinosa",
"Power-Up Punch": "Cop Potenciat",
"Precipice Blades": "Fullesd'Abisme",
"Prismatic Laser": "LàserPrismàtic",
"Psychic Fangs": "UllalsPsíquics",
"Psychic Terrain": "Camp Psíquic",
"Pulverizing Pancake": "CopPolvoritzad",
"Revelation Dance": "DansaRevelació",
"Rising Voltage": "VoltatgeAscend",
"Savage Spin Out": "Gir Salvatge",
"Scorching Sands": "Sorres Ardents",
"Searing Sunraze Smash": "Cop Solar Roent",
"Self-Destruct": "Autodestruir",
"Shattered Psyche": "Psique Trencada",
"Shell Side Arm": "Arma de Closca",
"Sinister Arrow Raid": "FletxesSinistrs",
"Skitter Smack": "Cop Furtiu",
"Smelling Salts": "SalsAromàtiques",
"Soul Stealing 7 Star Strike": "Cop 7 Estrelles",
"Sparkling Aria": "ÀriaEspurnejant",
"Sparkly Swirl": "Remolí Màgic",
"Spectral Thief": "LladreEspectral",
"Spirit Shackle": "Cadena d'Ànima",
"Splintered Stormshards": "Escletxes Roca",
"Splishy Splash": "Xip-XapElèctric",
"Steam Eruption": "ErupciódeVapor",
"Stoked Sparksurfer": "Surf Elèctric",
"Stomping Tantrum": "RabioladeCops",
"Strange Steam": "Vapor Estrany",
"Subzero Slammer": "Cop Sotazero",
"Sunsteel Strike": "Cop Acer Sagrat",
"Supersonic Skystrike": "Cop Supersònic",
"Surging Strikes": "CopsTorrencials",
"Tectonic Rage": "Ira Tectònica",
"Terrain Pulse": "Onada de Camp",
"Thousand Arrows": "Mil Fletxes",
"Thousand Waves": "Mil Onades",
"Thunder Punch": "Cop Elèctric",
"Thunder Shock": "Xoc Elèctric",
"Thunderous Kick": "Puntada de Tro",
"Trick-Or-Treat": "Truc o Tracte",
"Twinkle Tackle": "PlacatgeBrill",
"Veevee Volley": "Veevee Volea",
"Water Shuriken": "Shurikend'Aigua",
}
