# -*- coding: utf-8 -*-
"""Catalan: natures, characteristics, trainer classes (<=12 bytes),
met locations, ribbon descriptions."""
KIND = 'c'
FILES = [
    'src/data/text/nature_names.h',
    'src/data/text/characteristics.h',
    'src/data/text/trainer_class_names.h',
    'src/data/text/met_locations.h',
    'src/data/text/ribbon_descriptions.h',
    'src/data/text/gift_ribbon_descriptions.h',
]

T = {
# ---- natures ----
"Hardy": "Robusta",
"Lonely": "Solitària",
"Brave": "Valenta",
"Adamant": "Ferma",
"Naughty": "Murri",
"Bold": "Audaç",
"Docile": "Dòcil",
"Relaxed": "Relaxada",
"Impish": "Pícara",
"Lax": "Fluixa",
"Timid": "Tímida",
"Hasty": "Precipitada",
"Serious": "Seriosa",
"Jolly": "Alegre",
"Naive": "Ingènua",
"Modest": "Modesta",
"Mild": "Suau",
"Quiet": "Tranquil·la",
"Bashful": "Vergonyosa",
"Rash": "Impulsiva",
"Calm": "Calmada",
"Gentle": "Amable",
"Sassy": "Descarada",
"Careful": "Curosa",
"Quirky": "Rara",

# ---- characteristics ----
"Loves to eat.": "Li encanta menjar.",
"Proud of its power.": "Orgullós de la seva força.",
"Sturdy body.": "Cos robust.",
"Likes to run.": "Li agrada córrer.",
"Highly curious.": "Molt curiós.",
"Strong willed.": "De voluntat forta.",
"Takes plenty of siestas.": "Fa moltes migdiades.",
"Likes to thrash about.": "Li agrada rebolcar-se.",
"Capable of taking hits.": "Capaç d'aguantar cops.",
"Alert to sounds.": "Atent als sorolls.",
"Mischievous.": "Entremaliat.",
"Somewhat vain.": "Una mica vanitós.",
"Nods off a lot.": "S'adorm sovint.",
"A little quick tempered.": "Una mica geniüt.",
"Highly persistent.": "Molt persistent.",
"Impetuous and silly.": "Impetuós i ximple.",
"Thoroughly cunning.": "Molt astut.",
"Strongly defiant.": "Molt desafiant.",
"Scatters things often.": "Ho escampa tot sovint.",
"Likes to fight.": "Li agrada lluitar.",
"Good endurance.": "Bona resistència.",
"Somewhat of a clown.": "Una mica pallasso.",
"Often lost in thought.": "Sovint distret.",
"Hates to lose.": "Odia perdre.",
"Likes to relax.": "Li agrada relaxar-se.",
"Quick tempered.": "Geniüt.",
"Good perseverance.": "Molt perseverant.",
"Quick to flee.": "Fuig de seguida.",
"Very finicky.": "Molt exigent.",
"Somewhat stubborn.": "Una mica tossut.",
"Likes {COLOR 5}{SHADOW 6}spicy{COLOR 7}{SHADOW 8} food.": "Li agrada el menjar {COLOR 5}{SHADOW 6}picant{COLOR 7}{SHADOW 8}.",
"Likes {COLOR 5}{SHADOW 6}dry{COLOR 7}{SHADOW 8} food.": "Li agrada el menjar {COLOR 5}{SHADOW 6}sec{COLOR 7}{SHADOW 8}.",
"Likes {COLOR 5}{SHADOW 6}sweet{COLOR 7}{SHADOW 8} food.": "Li agrada el menjar {COLOR 5}{SHADOW 6}dolç{COLOR 7}{SHADOW 8}.",
"Likes {COLOR 5}{SHADOW 6}bitter{COLOR 7}{SHADOW 8} food.": "Li agrada el menjar {COLOR 5}{SHADOW 6}amarg{COLOR 7}{SHADOW 8}.",
"Likes {COLOR 5}{SHADOW 6}sour{COLOR 7}{SHADOW 8} food.": "Li agrada el menjar {COLOR 5}{SHADOW 6}àcid{COLOR 7}{SHADOW 8}.",
"Happily eats anything.": "Menja de tot content.",

# ---- trainer classes (<= 12 bytes; {PKMN} = 2 bytes) ----
"{PKMN} Trainer": "Entren. {PKMN}",
"Hiker": "Excursionist",
"Team Aqua": "Equip Aqua",
"{PKMN} Breeder": "Criador {PKMN}",
"Cooltrainer": "Entren. Guai",
"Bird Keeper": "Ocellaire",
"Collector": "Col·leccion.",
"Swimmer♂": "Nedador♂",
"Team Magma": "Equip Magma",
"Expert": "Expert",
"Aqua Admin": "Cap Aqua",
"Black Belt": "Cinturó Negr",
"Aqua Leader": "Líder Aqua",
"Hex Maniac": "Bruixa",
"Aroma Lady": "Dama Aroma",
"Ruin Maniac": "Arqueòleg",
"Interviewer": "Reporter",
"Tuber": "Banyista",
"Lady": "Senyora",
"Beauty": "Bellesa",
"Rich Boy": "Nen Ric",
"Pokémaniac": "Pokémaníac",
"Guitarist": "Guitarrista",
"Kindler": "Piròman",
"Camper": "Campista",
"Picnicker": "Piquenic",
"Bug Maniac": "Cucmaníac",
"Psychic": "Psíquic",
"Gentleman": "Senyor",
"Elite Four": "Alt Comand.",
"Leader": "Líder",
"School Kid": "Escolar",
"Sr. and Jr.": "Gran i Petit",
"Pokéfan": "Pokéfan",
"Youngster": "Marrec",
"Champion": "Campió",
"Fisherman": "Pescador",
"Triathlete": "Triatleta",
"Dragon Tamer": "Domadrac",
"Ninja Boy": "Ninja",
"Battle Girl": "Lluitadora",
"Parasol Lady": "Dama Ombrel.",
"Swimmer♀": "Nedadora♀",
"Twins": "Bessons",
"Sailor": "Mariner",
"Magma Admin": "Cap Magma",
"Rival": "Rival",
"Bug Catcher": "Cacacucs",
"{PKMN} Ranger": "Ranger {PKMN}",
"Magma Leader": "Líder Magma",
"Lass": "Noieta",
"Young Couple": "Parella Jove",
"Old Couple": "Parella Gran",
"Sis and Bro": "Germans",
"Salon Maiden": "Dama Saló",
"Dome Ace": "As Cúpula",
"Palace Maven": "Savi Palau",
"Arena Tycoon": "Amo Arena",
"Factory Head": "Cap Fàbrica",
"Pike Queen": "Reina Camí",
"Pyramid King": "Rei Piràmide",
"Team Rocket": "Equip Rocket",
"Rocket Boss": "Cap Rocket",
"Super Nerd": "Superempoll",
"Biker": "Motorista",
"Burglar": "Lladre",
"Channeler": "Mèdium",
"Crush Girl": "Noia Karate",
"Crush Kin": "Germans Kar.",
"Cue Ball": "Pinxo",
"Gambler": "Jugador",
"Juggler": "Malabarista",
"Painter": "Pintor",
"Rocker": "Rocker",
"Scientist": "Científic",
"Tamer": "Domador",
"Engineer": "Enginyer",
"Cool Couple": "Parella Guai",
"PKMN Prof.": "Prof. PKMN",

# ---- met locations (generic ones only; proper names kept) ----
"A Distant Land": "Terra Llunyana",
"Mayor's House": "Casa de l'Alcalde",
"Pre Gym": "Pregimnàs",
"Laboratory": "Laboratori",
"Front Of Lab": "Davant del Lab.",
"Rock": "Roca",
"Oasis": "Oasi",
"Cave": "Cova",
"Relic Cave": "Cova de Relíquies",
"Pyrite Cave": "Cova de Pyrite",
"Pyrite Town": "Poble de Pyrite",
"Pyrite Bldg": "Edifici Pyrite",
"Agate Village": "Vila d'Agate",
"Phenac City": "Ciutat de Phenac",
"Snagem Hideout": "Cau de Snagem",
"Miror's Hideout": "Cau de Miror",
"Kaminko's House": "Casa de Kaminko",
"Gateon Port": "Port de Gateon",
"Citadark Isle": "Illa Citadark",
"Cipher Key Lair": "Cau Clau Cipher",
"Cipher Lab": "Lab. Cipher",
"Pokémon HQ Lab": "Lab. Central Pkmn",
"The Under": "El Subsòl",
"The Under Subway": "Metro del Subsòl",
"MAYOR'S HOUSE": "CASA DE L'ALCALDE",
"PRE GYM": "PREGIMNÀS",
"LABORATORY": "LABORATORI",
"FRONT OF LAB": "DAVANT DEL LAB.",
"ROCK": "ROCA",
"OASIS": "OASI",
"CAVE": "COVA",
"A DISTANT LAND": "TERRA LLUNYANA",
"RELIC CAVE": "COVA DE RELÍQUIES",
"PYRITE CAVE": "COVA DE PYRITE",
"PYRITE TOWN": "POBLE DE PYRITE",
"PYRITE BLDG": "EDIFICI PYRITE",
"AGATE VILLAGE": "VILA D'AGATE",
"PHENAC CITY": "CIUTAT DE PHENAC",
"SNAGEM HIDEOUT": "CAU DE SNAGEM",
"MIROR'S HIDEOUT": "CAU DE MIROR",
"KAMINKO'S HOUSE": "CASA DE KAMINKO",
"GATEON PORT": "PORT DE GATEON",
"CITADARK ISLE": "ILLA CITADARK",
"CIPHER KEY LAIR": "CAU CLAU CIPHER",
"CIPHER LAB": "LAB. CIPHER",
"POKÉMON HQ LAB": "LAB. CENTRAL PKMN",
"THE UNDER": "EL SUBSÒL",
"THE UNDER SUBWAY": "METRO DEL SUBSÒL",
", Kanto": ", Kanto",
", KANTO": ", KANTO",

# ---- egg / met summary blocks ----
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1} nature.\\n\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 5}{DYNAMIC 1}\\nMet at {LV_2}{DYNAMIC 3}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}.\\n\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 5}{DYNAMIC 1}\\nTrobat al {LV_2}{DYNAMIC 3}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1} nature.\\n\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 5}{DYNAMIC 1}\\nHatched at {LV_2}{DYNAMIC 3}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}.\\n\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 5}{DYNAMIC 1}\\nNascut al {LV_2}{DYNAMIC 3}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1} nature.\\n\\nObtained in {DYNAMIC 0}a trade{DYNAMIC 1}.\\n\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}.\\n\\nObtingut en {DYNAMIC 0}un intercanvi{DYNAMIC 1}.\\n\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1} nature.\\n\\nObtained in a\\n{DYNAMIC 0}fateful encounter{DYNAMIC 1} at {LV_2}{DYNAMIC 3}.\\n{DYNAMIC 6}\\n{DYNAMIC 7}": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}.\\n\\nObtingut en una\\n{DYNAMIC 0}trobada del destí{DYNAMIC 1} al {LV_2}{DYNAMIC 3}.\\n{DYNAMIC 6}\\n{DYNAMIC 7}",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1} nature.\\n\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 5}{DYNAMIC 1}\\nApparently met at {LV_2}{DYNAMIC 3}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}.\\n\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 5}{DYNAMIC 1}\\nSembla trobat al {LV_2}{DYNAMIC 3}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1} nature.\\n\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 5}{DYNAMIC 1}\\nApparently hatched at {LV_2}{DYNAMIC 3}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}.\\n\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 5}{DYNAMIC 1}\\nSembla nascut al {LV_2}{DYNAMIC 3}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}",
"An odd Pokémon Egg found\\nby {DYNAMIC 0}the Day Care couple{DYNAMIC 1}.\\n\\n\\n“The Egg Watch”\\n{DYNAMIC 2}": "Un Ou de Pokémon estrany trobat\\nper {DYNAMIC 0}la parella de la Guarderia{DYNAMIC 1}.\\n\\n\\n“Vigilància de l'Ou”\\n{DYNAMIC 2}",
"An peculiar Pokémon Egg\\nobtained in a trade.\\n\\n\\n“The Egg Watch”\\n{DYNAMIC 2}": "Un Ou de Pokémon peculiar\\nobtingut en un intercanvi.\\n\\n\\n“Vigilància de l'Ou”\\n{DYNAMIC 2}",
"A peculiar Pokémon Egg\\nobtained at {DYNAMIC 0}a nice place{DYNAMIC 1}.\\n\\n\\n“The Egg Watch”\\n{DYNAMIC 2}": "Un Ou de Pokémon peculiar\\nobtingut en {DYNAMIC 0}un lloc bonic{DYNAMIC 1}.\\n\\n\\n“Vigilància de l'Ou”\\n{DYNAMIC 2}",
"A peculiar Pokémon Egg\\nobtained in a trade.\\n\\n\\n“The Egg Watch”\\n{DYNAMIC 2}": "Un Ou de Pokémon peculiar\\nobtingut en un intercanvi.\\n\\n\\n“Vigilància de l'Ou”\\n{DYNAMIC 2}",
"A Pokémon Egg obtained\\nat {DYNAMIC 0}the hot springs{DYNAMIC 1}.\\n\\n\\n“The Egg Watch”\\n{DYNAMIC 2}": "Un Ou de Pokémon obtingut\\na {DYNAMIC 0}les fonts termals{DYNAMIC 1}.\\n\\n\\n“Vigilància de l'Ou”\\n{DYNAMIC 2}",
"An odd Pokémon Egg\\nobtained from {DYNAMIC 0}a traveler{DYNAMIC 1}.\\n\\n\\n“The Egg Watch”\\n{DYNAMIC 2}": "Un Ou de Pokémon estrany\\nobtingut d'{DYNAMIC 0}un viatger{DYNAMIC 1}.\\n\\n\\n“Vigilància de l'Ou”\\n{DYNAMIC 2}",
"An odd Pokémon Egg found\\nby {DYNAMIC 0}the Day Care couple{DYNAMIC 1}\\nin the {DYNAMIC 0}Kanto{DYNAMIC 1} region.\\n\\n“The Egg Watch”\\n{DYNAMIC 2}": "Un Ou de Pokémon estrany trobat\\nper {DYNAMIC 0}la parella de la Guarderia{DYNAMIC 1}\\na la regió de {DYNAMIC 0}Kanto{DYNAMIC 1}.\\n\\n“Vigilància de l'Ou”\\n{DYNAMIC 2}",
"A Pokémon Egg obtained\\nfrom {DYNAMIC 0}Brigette{DYNAMIC 1}.\\n\\n\\n“The Egg Watch”\\n{DYNAMIC 2}": "Un Ou de Pokémon obtingut\\nde {DYNAMIC 0}Brigette{DYNAMIC 1}.\\n\\n\\n“Vigilància de l'Ou”\\n{DYNAMIC 2}",
"A very mysterious\\nPokémon Egg.\\n\\n\\n“The Egg Watch”\\n{DYNAMIC 2}": "Un Ou de Pokémon\\nmolt misteriós.\\n\\n\\n“Vigilància de l'Ou”\\n{DYNAMIC 2}",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1} nature,\\n\\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}'s old friend\\nfrom {DYNAMIC 0}Orre{DYNAMIC 1}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1},\\n\\nvell amic de {DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}\\nd'{DYNAMIC 0}Orre{DYNAMIC 1}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1} nature,\\n\\nreceived from {DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}\\nin {DYNAMIC 0}Orre{DYNAMIC 1}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1},\\n\\nrebut de {DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}\\na {DYNAMIC 0}Orre{DYNAMIC 1}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}",
"{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1} nature,\\n\\ngiven to {DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1} by his dad\\nin {DYNAMIC 0}Orre{DYNAMIC 1}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}": "Naturalesa {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1},\\n\\ndonat a {DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1} pel seu pare\\na {DYNAMIC 0}Orre{DYNAMIC 1}.\\n\\n{DYNAMIC 6}\\n{DYNAMIC 7}",

# ---- ribbon descriptions ----
"Champion-beating, Hall": "Cinta de membre del Saló",
"of Fame Member Ribbon": "de la Fama per guanyar",
"Cool Contest": "Concurs d'Estil",
"Beauty Contest": "Concurs de Bellesa",
"Cute Contest": "Concurs de Gràcia",
"Smart Contest": "Concurs d'Enginy",
"Tough Contest": "Concurs de Duresa",
"Normal Rank winner!": "Guanyador del rang normal!",
"Super Rank winner!": "Guanyador del rang súper!",
"Hyper Rank winner!": "Guanyador del rang híper!",
"Master Rank winner!": "Guanyador del rang mestre!",
"For clearing LV50": "Per superar el niv. 50",
"at the Battle Tower.": "a la Torre de Combat.",
"For clearing Open Level": "Per superar el nivell obert",
"Ribbon for being chosen": "Cinta per haver estat triat",
"as a super sketch model.": "com a model d'un gran esbós.",
"Ribbon awarded for": "Cinta atorgada per",
"being a hard worker.": "ser molt treballador.",
"2003 Regional Tourney": "Torneig regional del 2003",
"Champion Ribbon": "Cinta de campió",
"2003 National Tourney": "Torneig nacional del 2003",
"2003 Global Cup": "Copa mundial del 2003",
"Runner-up Ribbon": "Cinta de subcampió",
"Semifinalist Ribbon": "Cinta de semifinalista",
"2004 Regional Tourney": "Torneig regional del 2004",
"2004 National Tourney": "Torneig nacional del 2004",
"2004 Global Cup": "Copa mundial del 2004",
"2005 Regional Tourney": "Torneig regional del 2005",
"2005 National Tourney": "Torneig nacional del 2005",
"2005 Global Cup": "Copa mundial del 2005",
"Pokémon Battle Cup": "Copa de Combat Pokémon",
"Participation Ribbon": "Cinta de participació",
"Pokémon League": "Lliga Pokémon",
"Advance Cup": "Copa Advance",
"Pokémon Tournament": "Torneig Pokémon",
"Pokémon Event": "Fet Pokémon",
"Pokémon Festival": "Festival Pokémon",
"Difficulty-clearing": "Cinta commemorativa per",
"Commemorative Ribbon": "haver superat la dificultat",
"clearing all challenges.": "superar tots els reptes.",
"100-straight Win": "100 victòries seguides",
"Darkness Tower Clear": "Torre de la Foscor superada",
"Red Tower Clear": "Torre Vermella superada",
"Blackiron Tower Clear": "Torre de Ferro superada",
"Final Tower Clear": "Torre Final superada",
"Legend-making": "Creadora de llegendes",
"Pokémon Center Tokyo": "Centre Pokémon de Tòquio",
"Pokémon Center Osaka": "Centre Pokémon d'Osaka",
"Pokémon Center Nagoya": "Centre Pokémon de Nagoya",
"Pokémon Center NY": "Centre Pokémon de NY",
"Summer Holidays Ribbon": "Cinta de vacances d'estiu",
"Winter Holidays Ribbon": "Cinta de vacances d'hivern",
"Spring Holidays Ribbon": "Cinta de vacances de primavera",
"Evergreen Ribbon": "Cinta perenne",
"Special Holiday Ribbon": "Cinta de festa especial",
"Hard Worker Ribbon": "Cinta de treballador",
"Lots of Friends Ribbon": "Cinta de molts amics",
"Full of Energy Ribbon": "Cinta ple d'energia",
"A commemorative Ribbon": "Cinta commemorativa",
"for a loved Pokémon.": "per a un Pokémon estimat.",
"Ribbon that shows": "Cinta que mostra",
"love for Pokémon.": "amor pels Pokémon.",
}
