# -*- coding: utf-8 -*-
"""Catalan battle messages, part 1.

Name prefixes are *prepended* to the Pokemon name by the engine, so they are
rendered as short labels: "Rival Pikachu", "Salvatge Pikachu", "Aliat Pikachu".
Sentences are phrased so that reads naturally.

Stat changes are assembled as [adverb]+[direction], so the direction pieces are
adverbial ("amunt!"/"avall!") and take "molt "/"moltissim " prefixes cleanly.
"""
KIND = 'c'
FILES = ['src/battle_message.c']

T = {
# ---- prefixes ----
"Wild ": "Salvatge ",
"Foe ": "Rival ",
"Foe": "Rival",
"Ally": "Aliat",
"Your": "El teu",
"The opposing": "El rival",
"your": "el teu",
"the opposing": "el rival",

# ---- exp / level ----
"{B_BUFF1} gained{B_BUFF2}\\n{B_BUFF3} Exp. Points!\\p": "{B_BUFF1} ha guanyat{B_BUFF2}\\n{B_BUFF3} Punts d'Exp.!\\p",
" a boosted": " uns augmentats",
"{B_BUFF1} grew to\\nLV. {B_BUFF2}!{WAIT_SE}\\p": "{B_BUFF1} ha pujat al\\nNIV. {B_BUFF2}!{WAIT_SE}\\p",
"{B_BUFF1} learned\\n{B_BUFF2}!{WAIT_SE}\\p": "{B_BUFF1} ha après\\n{B_BUFF2}!{WAIT_SE}\\p",
"{B_BUFF1} is trying to\\nlearn {B_BUFF2}.\\p": "{B_BUFF1} intenta aprendre\\n{B_BUFF2}.\\p",
"But, {B_BUFF1} can't learn\\nmore than four moves.\\p": "Però {B_BUFF1} no pot saber\\nmés de quatre moviments.\\p",
"Delete a move to make\\nroom for {B_BUFF2}?": "Vols esborrar un moviment per\\nfer lloc a {B_BUFF2}?",
"{B_BUFF1} forgot\\n{B_BUFF2}.\\p": "{B_BUFF1} ha oblidat\\n{B_BUFF2}.\\p",
"{PAUSE 32}Stop learning\\n{B_BUFF2}?": "{PAUSE 32}Vols deixar d'aprendre\\n{B_BUFF2}?",
"{B_BUFF1} did not learn\\n{B_BUFF2}.\\p": "{B_BUFF1} no ha après\\n{B_BUFF2}.\\p",
"Use next Pokémon?": "Vols fer servir el següent Pokémon?",
"{B_ATK_NAME_WITH_PREFIX} learned\\n{B_BUFF1}!": "{B_ATK_NAME_WITH_PREFIX} ha après\\n{B_BUFF1}!",

# ---- hit / miss / faint ----
"{B_ATK_NAME_WITH_PREFIX}'s\\nattack missed!": "L'atac de {B_ATK_NAME_WITH_PREFIX}\\nha fallat!",
"{B_DEF_NAME_WITH_PREFIX}\\nprotected itself!": "{B_DEF_NAME_WITH_PREFIX}\\ns'ha protegit!",
"{B_DEF_NAME_WITH_PREFIX} avoided\\ndamage with {B_DEF_ABILITY}!": "{B_DEF_NAME_WITH_PREFIX} ha evitat\\nel dany amb {B_DEF_ABILITY}!",
"{B_DEF_NAME_WITH_PREFIX} makes Ground\\nmoves miss with {B_DEF_ABILITY}!": "{B_DEF_NAME_WITH_PREFIX} fa fallar els\\nmoviments Terra amb {B_DEF_ABILITY}!",
"{B_DEF_NAME_WITH_PREFIX} avoided\\nthe attack!": "{B_DEF_NAME_WITH_PREFIX} ha evitat\\nl'atac!",
"It doesn't affect\\n{B_DEF_NAME_WITH_PREFIX}…": "No afecta\\n{B_DEF_NAME_WITH_PREFIX}…",
"{B_ATK_NAME_WITH_PREFIX}\\nfainted!\\p": "{B_ATK_NAME_WITH_PREFIX}\\ns'ha debilitat!\\p",
"{B_DEF_NAME_WITH_PREFIX}\\nfainted!\\p": "{B_DEF_NAME_WITH_PREFIX}\\ns'ha debilitat!\\p",
"A critical hit!": "Un cop crític!",
"It's a one-hit KO!": "KO d'un sol cop!",
"It's not very effective…": "No és gaire eficaç…",
"It's super effective!": "És molt eficaç!",
"Hit {B_BUFF1} time(s)!": "Ha encertat {B_BUFF1} vegada(es)!",
"But nothing happened!": "Però no ha passat res!",
"But it failed!": "Però ha fallat!",
"But it had no effect!": "Però no ha tingut cap efecte!",
"It hurt itself in its\\nconfusion!": "S'ha fet mal a si mateix\\nper la confusió!",
"The Mirror Move failed!": "El Reflex Mirall ha fallat!",
"It had no effect\\non {B_DEF_NAME_WITH_PREFIX}!": "No ha tingut cap efecte\\nen {B_DEF_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX} is\\nunaffected!": "{B_DEF_NAME_WITH_PREFIX} no\\nse'n veu afectat!",
"{B_DEF_NAME_WITH_PREFIX}\\nwasn't affected!": "{B_DEF_NAME_WITH_PREFIX}\\nno se'n ha vist afectat!",
"{B_ATK_NAME_WITH_PREFIX} used\\n{B_BUFF3}!": "{B_ATK_NAME_WITH_PREFIX} ha usat\\n{B_BUFF3}!",
"It broke through the\\n{B_DEF_NAME_WITH_PREFIX}'s protection!": "Ha traspassat la protecció de\\n{B_DEF_NAME_WITH_PREFIX}!",

# ---- money / loss ----
"{B_PLAYER_NAME} got ¥{B_BUFF1}\\nfor winning!\\p": "{B_PLAYER_NAME} ha guanyat ¥{B_BUFF1}\\nper la victòria!\\p",
"{B_PLAYER_NAME} is out of\\nusable POKéMON!\\pPlayer lost against\\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}!{PAUSE_UNTIL_PRESS}": "{B_PLAYER_NAME} no té cap POKéMON\\nen condicions!\\pHa perdut contra\\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}!{PAUSE_UNTIL_PRESS}",
"{B_PLAYER_NAME} paid ¥{B_BUFF1} as the prize\\nmoney…\\p… … … …\\p{B_PLAYER_NAME} whited out!{PAUSE_UNTIL_PRESS}": "{B_PLAYER_NAME} ha pagat ¥{B_BUFF1} de\\npremi…\\p… … … …\\p{B_PLAYER_NAME} s'ha desmaiat!{PAUSE_UNTIL_PRESS}",
"{B_PLAYER_NAME} paid ¥{B_BUFF1} as the prize\\nmoney…\\p… … … …{PAUSE_UNTIL_PRESS}": "{B_PLAYER_NAME} ha pagat ¥{B_BUFF1} de\\npremi…\\p… … … …{PAUSE_UNTIL_PRESS}",
"{B_PLAYER_NAME} is out of\\nusable POKéMON!\\p": "{B_PLAYER_NAME} no té cap POKéMON\\nen condicions!\\p",
"{B_PLAYER_NAME} panicked and lost ¥{B_BUFF1}…\\p… … … …\\p{B_PLAYER_NAME} whited out!{PAUSE_UNTIL_PRESS}": "{B_PLAYER_NAME} s'ha espantat i ha perdut ¥{B_BUFF1}…\\p… … … …\\p{B_PLAYER_NAME} s'ha desmaiat!{PAUSE_UNTIL_PRESS}",
"{B_PLAYER_NAME} whited out!{PAUSE_UNTIL_PRESS}": "{B_PLAYER_NAME} s'ha desmaiat!{PAUSE_UNTIL_PRESS}",
"{B_PLAYER_NAME} panicked and lost ¥{B_BUFF1}…\\p… … … …{PAUSE_UNTIL_PRESS}": "{B_PLAYER_NAME} s'ha espantat i ha perdut ¥{B_BUFF1}…\\p… … … …{PAUSE_UNTIL_PRESS}",
"{B_PLAYER_NAME} lost the battle!{PAUSE_UNTIL_PRESS}": "{B_PLAYER_NAME} ha perdut el combat!{PAUSE_UNTIL_PRESS}",
"{B_PLAYER_NAME} picked up\\n¥{B_BUFF1}!\\p": "{B_PLAYER_NAME} ha recollit\\n¥{B_BUFF1}!\\p",

# ---- escape ----
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} prevents\\nescape with {B_SCR_ACTIVE_ABILITY}!\\p": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} impedeix\\nla fugida amb {B_SCR_ACTIVE_ABILITY}!\\p",
"Can't escape!\\p": "No es pot escapar!\\p",
"{B_ATK_NAME_WITH_PREFIX} can't escape!": "{B_ATK_NAME_WITH_PREFIX} no pot escapar!",
"{PLAY_SE SE_FLEE}Got away safely!\\p": "{PLAY_SE SE_FLEE}Has fugit sense problemes!\\p",
"{PLAY_SE SE_FLEE}{B_ATK_NAME_WITH_PREFIX} fled\\nusing its {B_LAST_ITEM}!\\p": "{PLAY_SE SE_FLEE}{B_ATK_NAME_WITH_PREFIX} ha fugit\\namb {B_LAST_ITEM}!\\p",
"{PLAY_SE SE_FLEE}{B_ATK_NAME_WITH_PREFIX} fled\\nusing {B_ATK_ABILITY}!\\p": "{PLAY_SE SE_FLEE}{B_ATK_NAME_WITH_PREFIX} ha fugit\\namb {B_ATK_ABILITY}!\\p",
"{PLAY_SE SE_FLEE}Wild {B_BUFF1} fled!": "{PLAY_SE SE_FLEE}{B_BUFF1} salvatge ha fugit!",
"No! There's no running\\nfrom a Trainer battle!\\p": "No! No pots fugir del combat\\ncontra un entrenador!\\p",
"{B_ATK_NAME_WITH_PREFIX} fled from\\nbattle!": "{B_ATK_NAME_WITH_PREFIX} ha fugit\\ndel combat!",
"Neither Pokémon can run away!": "Cap dels dos Pokémon pot fugir!",
"No one will be able to run away\\nduring the next turn!": "Ningú no podrà fugir durant\\nel torn següent!",

# ---- status: sleep ----
"{B_EFF_NAME_WITH_PREFIX}\\nfell asleep!": "{B_EFF_NAME_WITH_PREFIX}\\ns'ha adormit!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nmade {B_EFF_NAME_WITH_PREFIX} sleep!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha adormit {B_EFF_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX} is\\nalready asleep!": "{B_DEF_NAME_WITH_PREFIX} ja\\nestà adormit!",
"{B_ATK_NAME_WITH_PREFIX} is\\nalready asleep!": "{B_ATK_NAME_WITH_PREFIX} ja\\nestà adormit!",
"{B_ATK_NAME_WITH_PREFIX} is fast\\nasleep.": "{B_ATK_NAME_WITH_PREFIX} dorm\\nprofundament.",
"{B_ATK_NAME_WITH_PREFIX} woke up!": "{B_ATK_NAME_WITH_PREFIX} s'ha despertat!",
"{B_DEF_NAME_WITH_PREFIX} woke up!": "{B_DEF_NAME_WITH_PREFIX} s'ha despertat!",
"{B_ATK_NAME_WITH_PREFIX} went\\nto sleep!": "{B_ATK_NAME_WITH_PREFIX} s'ha\\nadormit!",
"{B_ATK_NAME_WITH_PREFIX} slept and\\nbecame healthy!": "{B_ATK_NAME_WITH_PREFIX} ha dormit\\ni s'ha recuperat!",
"{B_ATK_NAME_WITH_PREFIX} began to nap!": "{B_ATK_NAME_WITH_PREFIX} s'ha posat a dormir!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} is drowsing!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} té son!",
"{B_ATK_NAME_WITH_PREFIX} made\\n{B_DEF_NAME_WITH_PREFIX} drowsy!": "{B_ATK_NAME_WITH_PREFIX} ha fet venir\\nson a {B_DEF_NAME_WITH_PREFIX}!",

# ---- status: poison ----
"{B_EFF_NAME_WITH_PREFIX}\\nwas poisoned!": "{B_EFF_NAME_WITH_PREFIX}\\ns'ha enverinat!",
"{B_EFF_NAME_WITH_PREFIX} was poisoned by\\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_BUFF1}!": "{B_BUFF1} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha enverinat {B_EFF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} is hurt\\nby poison!": "El verí fa mal a\\n{B_ATK_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX} is already\\npoisoned.": "{B_DEF_NAME_WITH_PREFIX} ja està\\nenverinat.",
"{B_EFF_NAME_WITH_PREFIX} is badly\\npoisoned!": "{B_EFF_NAME_WITH_PREFIX} està greument\\nenverinat!",
"{B_DEF_NAME_WITH_PREFIX} was cured\\nof its poisoning!": "{B_DEF_NAME_WITH_PREFIX} s'ha curat\\nde l'enverinament!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} was poisoned!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} s'ha enverinat!",
"The poisoning healed {B_ATK_NAME_WITH_PREFIX}\\na little bit!": "L'enverinament ha curat una mica\\n{B_ATK_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX} had its\\nenergy drained!": "{B_DEF_NAME_WITH_PREFIX} ha perdut\\nenergia!",

# ---- status: burn ----
"{B_EFF_NAME_WITH_PREFIX} was burned!": "{B_EFF_NAME_WITH_PREFIX} s'ha cremat!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nburned {B_EFF_NAME_WITH_PREFIX}!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha cremat {B_EFF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} is hurt\\nby its burn!": "La cremada fa mal a\\n{B_ATK_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX} already\\nhas a burn.": "{B_DEF_NAME_WITH_PREFIX} ja\\nestà cremat.",
"{B_DEF_NAME_WITH_PREFIX}'s\\nburn was healed.": "La cremada de {B_DEF_NAME_WITH_PREFIX}\\ns'ha curat.",

# ---- status: freeze ----
"{B_EFF_NAME_WITH_PREFIX} was\\nfrozen solid!": "{B_EFF_NAME_WITH_PREFIX} s'ha\\ncongelat!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nfroze {B_EFF_NAME_WITH_PREFIX} solid!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha congelat {B_EFF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} is\\nfrozen solid!": "{B_ATK_NAME_WITH_PREFIX} està\\ncongelat!",
"{B_DEF_NAME_WITH_PREFIX} was\\ndefrosted!": "{B_DEF_NAME_WITH_PREFIX} s'ha\\ndesglaçat!",
"{B_ATK_NAME_WITH_PREFIX} was\\ndefrosted!": "{B_ATK_NAME_WITH_PREFIX} s'ha\\ndesglaçat!",
"{B_ATK_NAME_WITH_PREFIX} was\\ndefrosted by {B_CURRENT_MOVE}!": "{B_CURRENT_MOVE} ha desglaçat\\n{B_ATK_NAME_WITH_PREFIX}!",

# ---- status: paralysis ----
"{B_EFF_NAME_WITH_PREFIX} is paralyzed!\\nIt may be unable to move!": "{B_EFF_NAME_WITH_PREFIX} està paralitzat!\\nPotser no es podrà moure!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\\nparalyzed {B_EFF_NAME_WITH_PREFIX}!\\lIt may be unable to move!": "{B_SCR_ACTIVE_ABILITY} de {B_SCR_ACTIVE_NAME_WITH_PREFIX}\\nha paralitzat {B_EFF_NAME_WITH_PREFIX}!\\lPotser no es podrà moure!",
"{B_ATK_NAME_WITH_PREFIX} is paralyzed!\\nIt can't move!": "{B_ATK_NAME_WITH_PREFIX} està paralitzat!\\nNo es pot moure!",
"{B_DEF_NAME_WITH_PREFIX} is\\nalready paralyzed!": "{B_DEF_NAME_WITH_PREFIX} ja\\nestà paralitzat!",
"{B_DEF_NAME_WITH_PREFIX} was\\nhealed of paralysis!": "{B_DEF_NAME_WITH_PREFIX} s'ha\\ncurat de la paràlisi!",

# ---- confusion / love ----
"{B_ATK_NAME_WITH_PREFIX} is\\nconfused!": "{B_ATK_NAME_WITH_PREFIX} està\\nconfós!",
"{B_ATK_NAME_WITH_PREFIX} snapped\\nout of confusion!": "{B_ATK_NAME_WITH_PREFIX} ha sortit\\nde la confusió!",
"{B_EFF_NAME_WITH_PREFIX} became\\nconfused!": "{B_EFF_NAME_WITH_PREFIX} s'ha\\nconfós!",
"{B_DEF_NAME_WITH_PREFIX} is\\nalready confused!": "{B_DEF_NAME_WITH_PREFIX} ja\\nestà confós!",
"{B_ATK_NAME_WITH_PREFIX} became\\nconfused due to fatigue!": "{B_ATK_NAME_WITH_PREFIX} s'ha confós\\nper la fatiga!",
"{B_DEF_NAME_WITH_PREFIX}\\nfell in love!": "{B_DEF_NAME_WITH_PREFIX}\\ns'ha enamorat!",
"{B_ATK_NAME_WITH_PREFIX} is in love\\nwith {B_SCR_ACTIVE_NAME_WITH_PREFIX}!": "{B_ATK_NAME_WITH_PREFIX} està enamorat\\nde {B_SCR_ACTIVE_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} is\\nimmobilized by love!": "L'amor ha immobilitzat\\n{B_ATK_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} got over\\nits infatuation!": "{B_ATK_NAME_WITH_PREFIX} ha superat\\nl'enamorament!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} got over\\nits infatuation!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} ha superat\\nl'enamorament!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} fell in love\\nfrom the {B_LAST_ITEM}!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} s'ha enamorat\\nper {B_LAST_ITEM}!",

# ---- stat changes ----
"sharply ": "molt ",
"harshly ": "molt ",
"drastically ": "moltíssim ",
"severely ": "moltíssim ",
"rose!": "amunt!",
"fell!": "avall!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_BUFF1}\\n{B_BUFF2}": "{B_BUFF1} de {B_ATK_NAME_WITH_PREFIX}\\n{B_BUFF2}",
"{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}\\n{B_BUFF2}": "{B_BUFF1} de {B_DEF_NAME_WITH_PREFIX}\\n{B_BUFF2}",
"Using {B_LAST_ITEM}, the {B_BUFF1}\\nof {B_SCR_ACTIVE_NAME_WITH_PREFIX} {B_BUFF2}": "Amb {B_LAST_ITEM}, {B_BUFF1}\\nde {B_SCR_ACTIVE_NAME_WITH_PREFIX} {B_BUFF2}",
"{B_ATK_NAME_WITH_PREFIX}'s stats won't\\ngo any higher!": "Les estadístiques de {B_ATK_NAME_WITH_PREFIX}\\nno poden pujar més!",
"{B_DEF_NAME_WITH_PREFIX}'s stats won't\\ngo any lower!": "Les estadístiques de {B_DEF_NAME_WITH_PREFIX}\\nno poden baixar més!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_BUFF1}\\nwon't go higher!": "{B_BUFF1} de {B_ATK_NAME_WITH_PREFIX}\\nno pot pujar més!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}\\nwon't go lower!": "{B_BUFF1} de {B_DEF_NAME_WITH_PREFIX}\\nno pot baixar més!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}\\nwon't go higher!": "{B_BUFF1} de {B_DEF_NAME_WITH_PREFIX}\\nno pot pujar més!",
"{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}\\nwas not lowered!": "{B_BUFF1} de {B_DEF_NAME_WITH_PREFIX}\\nno ha baixat!",
"Reduced {B_DEF_NAME_WITH_PREFIX}'s\\n{B_BUFF1} by {B_BUFF2}!": "{B_BUFF1} de {B_DEF_NAME_WITH_PREFIX}\\nha baixat {B_BUFF2}!",
"All stat changes were\\neliminated!": "S'han eliminat tots els canvis\\nd'estadístiques!",
"{B_DEF_NAME_WITH_PREFIX}'s stat changes\\nwere removed!": "S'han tret els canvis d'estadístiques\\nde {B_DEF_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX}'s stat changes were\\nall reversed!": "S'han invertit tots els canvis\\nd'estadístiques de {B_DEF_NAME_WITH_PREFIX}!",
"{B_EFF_NAME_WITH_PREFIX}'s\\nstat changes were reset!": "S'han reiniciat els canvis\\nd'estadístiques de {B_EFF_NAME_WITH_PREFIX}!",
"Your team's {B_BUFF1}\\nstopped working!": "{B_BUFF1} del teu equip\\nha deixat de funcionar!",
"The foe's {B_BUFF1}\\nstopped working!": "{B_BUFF1} de l'equip rival\\nha deixat de funcionar!",
"HP": "PS",
"Attack": "Atac",
"Defense": "Defensa",
"Speed": "Velocitat",
"Sp. Atk": "At. Esp.",
"Sp. Def": "Def. Esp.",
"accuracy": "precisió",
"evasiveness": "evasió",

# ---- healing ----
"{B_DEF_NAME_WITH_PREFIX} regained\\nhealth!": "{B_DEF_NAME_WITH_PREFIX} ha recuperat\\nsalut!",
"{B_DEF_NAME_WITH_PREFIX}'s\\nHP is full!": "{B_DEF_NAME_WITH_PREFIX} té\\nels PS al màxim!",
"{B_ATK_NAME_WITH_PREFIX} regained health!": "{B_ATK_NAME_WITH_PREFIX} ha recuperat salut!",
"{B_DEF_NAME_WITH_PREFIX}'s HP was restored!": "{B_DEF_NAME_WITH_PREFIX} ha recuperat PS!",
"Aqua Ring restored\\n{B_ATK_NAME_WITH_PREFIX}'s HP!": "Anell Aigua ha recuperat els PS\\nde {B_ATK_NAME_WITH_PREFIX}!",
"The healing wish came true\\nfor {B_ATK_NAME_WITH_PREFIX}!": "El desig de cura s'ha complert\\nper a {B_ATK_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} is healed\\nby the grassy terrain!": "El camp herbós cura\\n{B_ATK_NAME_WITH_PREFIX}!",

# ---- screens / veils ----
"{B_ATK_PREFIX2}'s {B_CURRENT_MOVE}\\nraised Sp. Def!": "{B_CURRENT_MOVE} de {B_ATK_PREFIX2}\\nha pujat la Def. Esp.!",
"{B_ATK_PREFIX2}'s {B_CURRENT_MOVE}\\nraised Sp. Def a little!": "{B_CURRENT_MOVE} de {B_ATK_PREFIX2}\\nha pujat una mica la Def. Esp.!",
"{B_ATK_PREFIX2}'s {B_CURRENT_MOVE}\\nraised Defense!": "{B_CURRENT_MOVE} de {B_ATK_PREFIX2}\\nha pujat la Defensa!",
"{B_ATK_PREFIX2}'s {B_CURRENT_MOVE}\\nraised Defense a little!": "{B_CURRENT_MOVE} de {B_ATK_PREFIX2}\\nha pujat una mica la Defensa!",
"{B_ATK_PREFIX2}'s party is covered\\nby a veil!": "L'equip de {B_ATK_PREFIX2} està\\ncobert per un vel!",
"{B_DEF_NAME_WITH_PREFIX}'s party is protected\\nby Safeguard!": "L'equip de {B_DEF_NAME_WITH_PREFIX} està\\nprotegit per Salvaguarda!",
"{B_ATK_PREFIX3}'s party is no longer\\nprotected by Safeguard!": "L'equip de {B_ATK_PREFIX3} ja no\\nestà protegit per Salvaguarda!",
"The wall shattered!": "El mur s'ha trencat!",
"All screens on the field were\\ncleansed!": "S'han eliminat totes les barreres\\ndel camp!",
"{B_ATK_PREFIX1}'s {B_BUFF1}\\nwore off!": "{B_BUFF1} de {B_ATK_PREFIX1}\\ns'ha esgotat!",
"{B_ATK_NAME_WITH_PREFIX}'s {B_BUFF1}\\nwore off!": "{B_BUFF1} de {B_ATK_NAME_WITH_PREFIX}\\ns'ha esgotat!",

# ---- charging moves ----
"{B_ATK_NAME_WITH_PREFIX} whipped\\nup a whirlwind!": "{B_ATK_NAME_WITH_PREFIX} ha aixecat\\nun remolí!",
"{B_ATK_NAME_WITH_PREFIX} took\\nin sunlight!": "{B_ATK_NAME_WITH_PREFIX} ha absorbit\\nllum del sol!",
"{B_ATK_NAME_WITH_PREFIX} lowered\\nits head!": "{B_ATK_NAME_WITH_PREFIX} ha abaixat\\nel cap!",
"{B_ATK_NAME_WITH_PREFIX} is glowing!": "{B_ATK_NAME_WITH_PREFIX} brilla!",
"{B_ATK_NAME_WITH_PREFIX} flew\\nup high!": "{B_ATK_NAME_WITH_PREFIX} ha volat\\nben amunt!",
"{B_ATK_NAME_WITH_PREFIX} dug a hole!": "{B_ATK_NAME_WITH_PREFIX} ha cavat un forat!",
"{B_ATK_NAME_WITH_PREFIX} hid\\nunderwater!": "{B_ATK_NAME_WITH_PREFIX} s'ha amagat\\nsota l'aigua!",
"{B_ATK_NAME_WITH_PREFIX} sprang up!": "{B_ATK_NAME_WITH_PREFIX} ha fet un bot!",
"{B_ATK_NAME_WITH_PREFIX} vanished\\ninstantly!": "{B_ATK_NAME_WITH_PREFIX} ha desaparegut\\na l'instant!",
"{B_ATK_NAME_WITH_PREFIX} became cloaked\\nin a freezing light!": "{B_ATK_NAME_WITH_PREFIX} s'ha cobert\\nd'una llum glaçada!",
"{B_ATK_NAME_WITH_PREFIX} became cloaked\\nin mystical moonlight!": "{B_ATK_NAME_WITH_PREFIX} s'ha cobert\\nde llum lunar mística!",
"It became cloaked in mystical\\nmoonlight!": "S'ha cobert de llum lunar\\nmística!",
"{B_ATK_NAME_WITH_PREFIX} began\\ncharging power!": "{B_ATK_NAME_WITH_PREFIX} ha començat\\na acumular poder!",
"{B_ATK_NAME_WITH_PREFIX} is absorbing power!": "{B_ATK_NAME_WITH_PREFIX} absorbeix poder!",
"{B_ATK_NAME_WITH_PREFIX} started\\nheating up its beak!": "{B_ATK_NAME_WITH_PREFIX} ha començat\\na escalfar-se el bec!",
"{B_ATK_NAME_WITH_PREFIX} is overflowing\\nwith space energy!": "{B_ATK_NAME_WITH_PREFIX} desborda\\nd'energia espacial!",
"{B_ATK_NAME_WITH_PREFIX} must\\nrecharge!": "{B_ATK_NAME_WITH_PREFIX} ha de\\nrecuperar forces!",
"{B_ATK_NAME_WITH_PREFIX} kept going\\nand crashed!": "{B_ATK_NAME_WITH_PREFIX} ha continuat\\ni s'ha estavellat!",
"{B_ATK_NAME_WITH_PREFIX} is hit\\nwith recoil!": "{B_ATK_NAME_WITH_PREFIX} rep\\ndany de retrocés!",
"{B_ATK_NAME_WITH_PREFIX} is getting\\npumped!": "{B_ATK_NAME_WITH_PREFIX} s'està\\nanimant!",
"{B_ATK_NAME_WITH_PREFIX} is tightening\\nits focus!": "{B_ATK_NAME_WITH_PREFIX} es concentra\\namb força!",
"{B_ATK_NAME_WITH_PREFIX}\\nconcentrated intensely!": "{B_ATK_NAME_WITH_PREFIX}\\ns'ha concentrat intensament!",
"{B_ATK_NAME_WITH_PREFIX} lost its\\nfocus and couldn't move!": "{B_ATK_NAME_WITH_PREFIX} ha perdut la\\nconcentració i no s'ha pogut moure!",
"{B_ATK_NAME_WITH_PREFIX} became nimble!": "{B_ATK_NAME_WITH_PREFIX} s'ha tornat àgil!",
"{B_ATK_NAME_WITH_PREFIX} flinched!": "{B_ATK_NAME_WITH_PREFIX} s'ha esglaiat!",
"{B_ATK_NAME_WITH_PREFIX} protected\\nitself!": "{B_ATK_NAME_WITH_PREFIX} s'ha\\nprotegit!",
"{B_ATK_NAME_WITH_PREFIX} braced\\nitself!": "{B_ATK_NAME_WITH_PREFIX} s'ha\\npreparat per aguantar!",
"{B_DEF_NAME_WITH_PREFIX} Endured\\nthe hit!": "{B_DEF_NAME_WITH_PREFIX} ha aguantat\\nel cop!",
"{B_DEF_NAME_WITH_PREFIX} evaded\\nthe attack!": "{B_DEF_NAME_WITH_PREFIX} ha esquivat\\nl'atac!",
"{B_DEF_NAME_WITH_PREFIX} was\\nblown away!": "{B_DEF_NAME_WITH_PREFIX} ha sortit\\nvolant!",

# ---- trapping ----
"{B_DEF_NAME_WITH_PREFIX} got trapped\\nby a snap trap!": "{B_DEF_NAME_WITH_PREFIX} ha quedat\\natrapat en un parany!",
"{B_DEF_NAME_WITH_PREFIX} was squeezed by\\n{B_ATK_NAME_WITH_PREFIX}'s Bind!": "{B_ATK_NAME_WITH_PREFIX} ha constret\\n{B_DEF_NAME_WITH_PREFIX}!",
"{B_DEF_NAME_WITH_PREFIX} was trapped\\nin the vortex!": "{B_DEF_NAME_WITH_PREFIX} ha quedat\\natrapat al remolí!",
"{B_DEF_NAME_WITH_PREFIX} was trapped\\nby Sand Tomb!": "{B_DEF_NAME_WITH_PREFIX} ha quedat\\natrapat per Tomba Sorra!",
"{B_DEF_NAME_WITH_PREFIX} was wrapped by\\n{B_ATK_NAME_WITH_PREFIX}!": "{B_ATK_NAME_WITH_PREFIX} ha embolicat\\n{B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} clamped\\n{B_DEF_NAME_WITH_PREFIX}!": "{B_ATK_NAME_WITH_PREFIX} ha atrapat\\n{B_DEF_NAME_WITH_PREFIX} amb tenalles!",
"{B_ATK_NAME_WITH_PREFIX} is hurt\\nby {B_BUFF1}!": "{B_BUFF1} fa mal a\\n{B_ATK_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} was freed\\nfrom {B_BUFF1}!": "{B_ATK_NAME_WITH_PREFIX} s'ha alliberat\\nde {B_BUFF1}!",
"{B_DEF_NAME_WITH_PREFIX} can't\\nescape now!": "Ara {B_DEF_NAME_WITH_PREFIX}\\nno pot escapar!",
"{B_DEF_NAME_WITH_PREFIX} became\\ntrapped by swirling magma!": "{B_DEF_NAME_WITH_PREFIX} ha quedat\\natrapat en magma giratori!",
"{B_DEF_NAME_WITH_PREFIX} has been afflicted\\nwith an infestation by {B_ATK_NAME_WITH_PREFIX}!": "{B_ATK_NAME_WITH_PREFIX} ha infestat\\n{B_DEF_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} can no longer escape\\nbecause it used {B_CURRENT_MOVE}!": "{B_ATK_NAME_WITH_PREFIX} ja no pot escapar\\nperquè ha usat {B_CURRENT_MOVE}!",
"{B_DEF_NAME_WITH_PREFIX} can no longer escape\\nbecause of {B_CURRENT_MOVE}!": "{B_DEF_NAME_WITH_PREFIX} ja no pot escapar\\nper culpa de {B_CURRENT_MOVE}!",

# ---- mist / weather-ish ----
"{B_ATK_PREFIX2} became\\nshrouded in Mist!": "{B_ATK_PREFIX2} s'ha\\nembolcallat de Boira!",
"{B_SCR_ACTIVE_NAME_WITH_PREFIX} is protected\\nby Mist!": "{B_SCR_ACTIVE_NAME_WITH_PREFIX} està protegit\\nper la Boira!",
"{B_ATK_NAME_WITH_PREFIX} is buffeted\\nby the sandstorm!": "La tempesta de sorra colpeja\\n{B_ATK_NAME_WITH_PREFIX}!",
"{B_ATK_NAME_WITH_PREFIX} is pelted\\nby Hail!": "La calamarsa colpeja\\n{B_ATK_NAME_WITH_PREFIX}!",
"It started to rain!": "Ha començat a ploure!",
"A downpour started!": "Ha començat un xàfec!",
"Rain continues to fall.": "Continua plovent.",
"The downpour continues.": "El xàfec continua.",
"The rain stopped.": "Ha parat de ploure.",
"A sandstorm brewed!": "S'ha format una tempesta de sorra!",
"A sandstorm kicked up!": "S'ha aixecat una tempesta de sorra!",
"The sandstorm rages.": "La tempesta de sorra brama.",
"The sandstorm subsided.": "La tempesta de sorra ha parat.",
"The sunlight got bright!": "La llum del sol s'ha intensificat!",
"The sunlight is strong.": "La llum del sol és forta.",
"The sunlight faded.": "La llum del sol s'ha afeblit.",
"It started to hail!": "Ha començat a calamarsejar!",
"Hail continues to fall.": "Continua calamarsejant.",
"The hail stopped.": "Ha parat de calamarsejar.",
"It is raining.": "Està plovent.",
"A sandstorm is raging.": "Hi ha una tempesta de sorra.",
"The effects of weather\\ndisappeared.": "Els efectes del clima\\nhan desaparegut.",
"The wind turned into a\\nHeat Wave!": "El vent s'ha convertit en\\nuna Onada de Calor!",
"The sunlight turned\\nextremely harsh!": "La llum del sol s'ha tornat\\nextremament intensa!",
"The extreme sunlight faded.{PAUSE 64}": "La llum del sol extrema s'ha afeblit.{PAUSE 64}",
"The Water-type attack evaporated\\nin the harsh sunlight!": "L'atac de tipus Aigua s'ha evaporat\\namb la llum del sol intensa!",
"The extremely harsh sunlight\\nwas not lessened at all!": "La llum del sol extremament intensa\\nno s'ha afeblit gens!",
"A heavy rain began to fall!": "Ha començat a ploure amb força!",
"The heavy rain has lifted!{PAUSE 64}": "La pluja intensa ha parat!{PAUSE 64}",
"The Fire-type attack fizzled out\\nin the heavy rain!": "L'atac de tipus Foc s'ha apagat\\namb la pluja intensa!",
"There is no relief from\\nthis heavy rain!": "No hi ha manera d'aturar\\naquesta pluja intensa!",
"A mysterious air current is\\nprotecting Flying-type Pokémon!": "Un corrent d'aire misteriós\\nprotegeix els Pokémon Volador!",
"The mysterious strong winds\\nhave dissipated!{PAUSE 64}": "Els vents forts misteriosos\\ns'han dissipat!{PAUSE 64}",
"The mysterious air current\\nblows on regardless!": "El corrent d'aire misteriós\\nbufa igualment!",
"The mysterious strong winds\\nweakened the attack!": "Els vents forts misteriosos\\nhan afeblit l'atac!",
}
