# -*- coding: utf-8 -*-
"""Catalan item names. HARD LIMIT: ITEM_NAME_LENGTH = 14 encoded bytes.
{POKEBLOCK} counts as 5 bytes, {PKMN} as 2."""
KIND = 'c'
FILES = ['src/data/items.h']
LIMIT = 14
LIMIT_EXEMPT = ('{POKEBLOCK}',)

T = {
# --- balls ---
"Master Ball": "Master Ball",
"Ultra Ball": "Ultra Ball",
"Great Ball": "Great Ball",
"Poké Ball": "Poké Ball",
"Safari Ball": "Safari Ball",
"Net Ball": "Net Ball",
"Dive Ball": "Dive Ball",
"Nest Ball": "Nest Ball",
"Repeat Ball": "Repeat Ball",
"Timer Ball": "Timer Ball",
"Luxury Ball": "Luxury Ball",
"Premier Ball": "Premier Ball",
# --- medicine ---
"Potion": "Poció",
"Antidote": "Antídot",
"Burn Heal": "Anticremada",
"Ice Heal": "Antigel",
"Awakening": "Despertar",
"Parlyz Heal": "Antiparàlisi",
"Full Restore": "Restaurador",
"Max Potion": "Poció Màxima",
"Hyper Potion": "Hiperpoció",
"Super Potion": "Superpoció",
"Full Heal": "Cura Total",
"Revive": "Revifador",
"Max Revive": "Revifador Màx",
"Fresh Water": "Aigua Fresca",
"Soda Pop": "Refresc",
"Lemonade": "Llimonada",
"Moomoo Milk": "Llet Mumú",
"Energypowder": "Polsenergia",
"Energy Root": "Arrel Energia",
"Heal Powder": "Pols Curativa",
"Revival Herb": "Herba Revifant",
"Ether": "Èter",
"Max Ether": "Èter Màxim",
"Elixir": "Elixir",
"Max Elixir": "Elixir Màxim",
"Lava Cookie": "Galeta de Lava",
"Berry Juice": "Suc de Baia",
"Sacred Ash": "Cendra Sagrada",
# --- flutes ---
"Blue Flute": "Flauta Blava",
"Yellow Flute": "Flauta Groga",
"Red Flute": "Flauta Verm.",
"Black Flute": "Flauta Negra",
"White Flute": "Flauta Blanca",
# --- treasures ---
"Shoal Salt": "Sal de Banc",
"Shoal Shell": "Closca de Banc",
"Red Shard": "Frag. Vermell",
"Blue Shard": "Frag. Blau",
"Yellow Shard": "Frag. Groc",
"Green Shard": "Frag. Verd",
"Tinymushroom": "Bolet Petit",
"Big Mushroom": "Bolet Gran",
"Pearl": "Perla",
"Big Pearl": "Perla Gran",
"Stardust": "Pols Estel·lar",
"Star Piece": "Tros d'Estel",
"Nugget": "Pepita",
"Heart Scale": "Escata Cor",
"Ruby": "Robí",
"Sapphire": "Safir",
# --- vitamins ---
"HP Up": "Més PS",
"Protein": "Proteïna",
"Iron": "Ferro",
"Carbos": "Carbs",
"Calcium": "Calci",
"Rare Candy": "Caramel Rar",
"PP Up": "Més PP",
"Zinc": "Zinc",
"PP Max": "PP Màx",
# --- battle items ---
"Guard Spec.": "Prot. Espec.",
"Dire Hit": "Cop Crític",
"X Attack": "Atac X",
"X Defend": "Defensa X",
"X Speed": "Velocitat X",
"X Accuracy": "Precisió X",
"X Special": "Especial X",
"Poké Doll": "Nina Poké",
"Fluffy Tail": "Cua Suau",
# --- repels ---
"Super Repel": "Súper Repel.",
"Max Repel": "Màx. Repel.",
"Escape Rope": "Corda Fugida",
"Repel": "Repel·lent",
# --- stones ---
"Sun Stone": "Pedra Solar",
"Moon Stone": "Pedra Lunar",
"Fire Stone": "Pedra Foc",
"ThunderStone": "Pedra Tro",
"Water Stone": "Pedra Aigua",
"Leaf Stone": "Pedra Fulla",
"Power Stone": "Pedra Poder",
# --- mail ---
"Orange Mail": "Carta Taronja",
"Harbor Mail": "Carta Port",
"Glitter Mail": "Carta Brillant",
"Mech Mail": "Carta Mecànica",
"Wood Mail": "Carta Fusta",
"Wave Mail": "Carta Onada",
"Bead Mail": "Carta Perles",
"Shadow Mail": "Carta Ombra",
"Tropic Mail": "Carta Tropical",
"Dream Mail": "Carta Somni",
"Fab Mail": "Carta Fabulosa",
"Retro Mail": "Carta Retro",
# --- berries ---
"Cheri Berry": "Baia Cheri",
"Chesto Berry": "Baia Chesto",
"Pecha Berry": "Baia Pecha",
"Rawst Berry": "Baia Rawst",
"Aspear Berry": "Baia Aspear",
"Leppa Berry": "Baia Leppa",
"Oran Berry": "Baia Oran",
"Persim Berry": "Baia Persim",
"Lum Berry": "Baia Lum",
"Sitrus Berry": "Baia Sitrus",
"Figy Berry": "Baia Figy",
"Wiki Berry": "Baia Wiki",
"Mago Berry": "Baia Mago",
"Aguav Berry": "Baia Aguav",
"Iapapa Berry": "Baia Iapapa",
"Razz Berry": "Baia Razz",
"Bluk Berry": "Baia Bluk",
"Nanab Berry": "Baia Nanab",
"Wepear Berry": "Baia Wepear",
"Pinap Berry": "Baia Pinap",
"Pomeg Berry": "Baia Pomeg",
"Kelpsy Berry": "Baia Kelpsy",
"Qualot Berry": "Baia Qualot",
"Hondew Berry": "Baia Hondew",
"Grepa Berry": "Baia Grepa",
"Tamato Berry": "Baia Tamato",
"Cornn Berry": "Baia Cornn",
"Magost Berry": "Baia Magost",
"Rabuta Berry": "Baia Rabuta",
"Nomel Berry": "Baia Nomel",
"Spelon Berry": "Baia Spelon",
"Pamtre Berry": "Baia Pamtre",
"Watmel Berry": "Baia Watmel",
"Durin Berry": "Baia Durin",
"Belue Berry": "Baia Belue",
"Liechi Berry": "Baia Liechi",
"Ganlon Berry": "Baia Ganlon",
"Salac Berry": "Baia Salac",
"Petaya Berry": "Baia Petaya",
"Apicot Berry": "Baia Apicot",
"Lansat Berry": "Baia Lansat",
"Starf Berry": "Baia Starf",
"Enigma Berry": "Baia Enigma",
# --- hold items ---
"Brightpowder": "Pols Brillant",
"White Herb": "Herba Blanca",
"Macho Brace": "Braçal Ferm",
"Exp. Share": "Repartiexp",
"Quick Claw": "Urpa Ràpida",
"Soothe Bell": "Camp. Calma",
"Mental Herb": "Herba Mental",
"Choice Band": "Cinta Tria",
"King's Rock": "Roca Reial",
"SilverPowder": "Pols Argent",
"Amulet Coin": "Moneda Amulet",
"Cleanse Tag": "Amulet Purga",
"Soul Dew": "Rosada Ànima",
"DeepSeaTooth": "Dent Abissal",
"DeepSeaScale": "Escata Abissal",
"Smoke Ball": "Bola de Fum",
"Everstone": "Pedra Eterna",
"Focus Band": "Cinta Focus",
"Lucky Egg": "Ou de Sort",
"Scope Lens": "Lupa Precisió",
"Metal Coat": "Capa Metall",
"Leftovers": "Restes",
"Dragon Scale": "Escata Drac",
"Light Ball": "Bola Llum",
"Soft Sand": "Sorra Fina",
"Hard Stone": "Pedra Dura",
"Miracle Seed": "Llavor Miracle",
"BlackGlasses": "Ulleres Negres",
"Black Belt": "Cinturó Negre",
"Magnet": "Imant",
"Mystic Water": "Aigua Mística",
"Sharp Beak": "Bec Esmolat",
"Poison Barb": "Punxa Verinosa",
"NeverMeltIce": "Gel Etern",
"Spell Tag": "Amulet Encís",
"Twistedspoon": "Cullera Torta",
"Charcoal": "Carbó",
"Dragon Fang": "Ullal de Drac",
"Silk Scarf": "Mocador Seda",
"Up-Grade": "Millora",
"Shell Bell": "Camp. Closca",
"Sea Incense": "Encens Marí",
"Lax Incense": "Encens Suau",
"Lucky Punch": "Cop de Sort",
"Metal Powder": "Pols Metall",
"Thick Club": "Os Gruixut",
"Stick": "Tija",
"Eviolite": "Eviolita",
"Red Scarf": "Mocador Verm.",
"Blue Scarf": "Mocador Blau",
"Pink Scarf": "Mocador Rosa",
"Green Scarf": "Mocador Verd",
"Yellow Scarf": "Mocador Groc",
# --- key items ---
"Bicycle": "Bicicleta",
"Bicylce": "Bicicleta",
"Coin Case": "Moneder",
"Itemfinder": "Cercaobjectes",
"Old Rod": "Canya Vella",
"Good Rod": "Canya Bona",
"Super Rod": "Súper Canya",
"S.S. Ticket": "Bitllet S.S.",
"Contest Pass": "Passi Concurs",
"Watering Can": "Regadora",
"Rocket Plans": "Plans Rocket",
"Soot Sack": "Sac de Sutge",
"Basement Key": "Clau Soterrani",
"{POKEBLOCK} Case": "Estoig {POKEBLOCK}",
"Letter": "Carta",
"Eon Ticket": "Bitllet Eó",
"Red Orb": "Orbe Vermell",
"Blue Orb": "Orbe Blau",
"Scanner": "Escàner",
"Go-Goggles": "Ulleres Go",
"Meteorite": "Meteorit",
"Rm. 1 Key": "Clau Sala 1",
"Rm. 2 Key": "Clau Sala 2",
"Rm. 4 Key": "Clau Sala 4",
"Rm. 6 Key": "Clau Sala 6",
"Storage Key": "Clau Magatzem",
"Root Fossil": "Fòssil Arrel",
"Claw Fossil": "Fòssil Urpa",
"Devon Scope": "Visor Devon",
"Oak's Parcel": "Paquet d'Oak",
"Poké Flute": "Flauta Poké",
"Secret Key": "Clau Secreta",
"Bike Voucher": "Val de Bici",
"Gold Teeth": "Dents d'Or",
"Old Amber": "Ambre Antic",
"Card Key": "Clau Targeta",
"Lift Key": "Clau Ascensor",
"Helix Fossil": "Fòssil Hèlix",
"Dome Fossil": "Fòssil Cúpula",
"Silph Scope": "Visor Silph",
"Town Map": "Mapa Poble",
"Vs Seeker": "Cerca Combat",
"Fame Checker": "Guia Famosos",
"TM Case": "Estoig MT",
"Berry Pouch": "Bossa Baies",
"Teachy TV": "TV Educativa",
"Tri-Pass": "Tripassi",
"Rainbow Pass": "Passi Arc Iris",
"Tea": "Te",
"MysticTicket": "Bitllet Místic",
"AuroraTicket": "Bitllet Aurora",
"Powder Jar": "Pot de Pols",
"Magma Emblem": "Emblema Magma",
"Old Sea Map": "Mapa Mar Antic",
# --- mints ---
"Adamant Mint": "Menta Ferma",
"Bold Mint": "Menta Audaç",
"Brave Mint": "Menta Valenta",
"Calm Mint": "Menta Calmada",
"Careful Mint": "Menta Curosa",
"Gentle Mint": "Menta Amable",
"Hasty Mint": "Menta Precip.",
"Impish Mint": "Menta Pícara",
"Jolly Mint": "Menta Alegre",
"Lax Mint": "Menta Fluixa",
"Lonely Mint": "Menta Solit.",
"Mild Mint": "Menta Suau",
"Modest Mint": "Menta Modesta",
"Naive Mint": "Menta Ingènua",
"Naughty Mint": "Menta Murri",
"Quiet Mint": "Menta Tranq.",
"Rash Mint": "Menta Impuls.",
"Relaxed Mint": "Menta Relax.",
"Sassy Mint": "Menta Descar.",
"Serious Mint": "Menta Seriosa",
"Timid Mint": "Menta Tímida",
# --- competitive hold items ---
"AbilityCapsle": "Càpsula Habil.",
"AbilityPatch": "Pegat Habil.",
"Muscle Band": "Cinta Múscul",
"Wise Glasses": "Ulleres Sàvies",
"Expert Belt": "Cinturó Expert",
"Light Clay": "Argila Lleu",
"Life Orb": "Orbe Vital",
"Power Herb": "Herba Poder",
"Power Weight": "Pes Poder",
"Power Bracer": "Braçal Poder",
"Power Belt": "Cinturó Poder",
"Power Lens": "Lent Poder",
"Power Band": "Cinta Poder",
"Power Anklet": "Anella Poder",
"Black Sludge": "Residu Negre",
"Big Root": "Arrel Gran",
"Red Card": "Targeta Roja",
"ProtectvePads": "Coixinets Prot",
"Rocky Helmet": "Casc Rocós",
"Razor Claw": "Urpa Afilada",
"Razor Fang": "Ullal Afilat",
"Choice Specs": "Ulleres Tria",
"Choice Scarf": "Mocador Tria",
"Damp Rock": "Roca Humida",
"Heat Rock": "Roca Calenta",
"Smooth Rock": "Roca Llisa",
"Icy Rock": "Roca Gelada",
"Destiny Knot": "Nus Destí",
"Pixie Dust": "Pols de Fada",
"Oval Charm": "Amulet Oval",
"Shiny Charm": "Amulet Lluent",
"CatchngCharm": "Amulet Captura",
# --- mega stones ---
"Venusaurite": "Venusaurita",
"CharizarditeX": "CharizarditaX",
"CharizarditeY": "CharizarditaY",
"Blastoisinite": "Blastoisinita",
"Beedrillite": "Beedrillita",
"Pidgeotite": "Pidgeotita",
"Alakazite": "Alakazita",
"Slowbronite": "Slowbronita",
"Gengarite": "Gengarita",
"Kangaskhanite": "Kangaskhanita",
"Pinsirite": "Pinsirita",
"Gyaradosite": "Gyaradosita",
"Aerodactylite": "Aerodactylita",
"Mewtwonite X": "Mewtwonita X",
"Mewtwonite Y": "Mewtwonita Y",
"Mega Ring": "Anell Mega",
# --- EV candies ---
"HP Candy": "Caramel PS",
"Attack Candy": "Caramel Atac",
"Defense Candy": "Caramel Def.",
"Sp.Atk Candy": "Caramel At.Esp",
"Sp.Def Candy": "Caramel Df.Esp",
"Speed Candy": "Caramel Vel.",
"Max Candy": "Caramel Màx.",
"Reset Candy": "Caramel Zero",
# --- TMs / HMs ---
**{f"TM{i:02d}": f"MT{i:02d}" for i in range(1, 51)},
**{f"HM{i:02d}": f"MO{i:02d}" for i in range(1, 9)},
}
