# -*- coding: utf-8 -*-
"""Catalan ability names and descriptions.
Names are kept <= 12 chars so BOTH gAbilityNames tables compile regardless of
B_EXPANDED_ABILITY_NAMES."""
KIND = 'c'
FILES = ['src/data/text/abilities.h']
LIMIT = 12

T = {
# ---------------- names ----------------
"Stench": "Pudor",
"Drizzle": "Plugim",
"Speed Boost": "Impuls Vel.",
"Battle Armor": "Cuirassa",
"Sturdy": "Robustesa",
"Damp": "Humitat",
"Limber": "Flexibilitat",
"Sand Veil": "Vel Sorra",
"Static": "Estàtica",
"Volt Absorb": "Absorb. Volt",
"Water Absorb": "Absorb.Aigua",
"Oblivious": "Despreocupat",
"Cloud Nine": "Antinúvol",
"Compound Eyes": "UllsComposts",
"Insomnia": "Insomni",
"Color Change": "Canvi Color",
"Immunity": "Immunitat",
"Flash Fire": "Foc Fatu",
"Shield Dust": "Pols Escut",
"Own Tempo": "Ritme Propi",
"Suction Cups": "Ventoses",
"Intimidate": "Intimidació",
"Shadow Tag": "Ombra Fixa",
"Rough Skin": "Pell Rugosa",
"Wonder Guard": "EscutProdigi",
"Levitate": "Levitació",
"Effect Spore": "Espora",
"Synchronize": "Sincronia",
"Clear Body": "Cos Pur",
"Natural Cure": "Cura Natural",
"Lightning Rod": "Parallamps",
"Serene Grace": "Gràcia",
"Swift Swim": "Natació Ràp.",
"Chlorophyll": "Clorofil·la",
"Illuminate": "Il·luminació",
"Trace": "Calc",
"Huge Power": "Gran Poder",
"Poison Point": "Punt Verí",
"Inner Focus": "Focus Intern",
"Magma Armor": "CuirassMagma",
"Water Veil": "Vel d'Aigua",
"Magnet Pull": "Imant",
"Soundproof": "Insonor",
"Rain Dish": "Cura Pluja",
"Sand Stream": "Flux Sorra",
"Pressure": "Pressió",
"Thick Fat": "Greix",
"Early Bird": "Matinador",
"Flame Body": "Cos Flama",
"Run Away": "Fugida",
"Keen Eye": "Vista Fina",
"Hyper Cutter": "Hipertall",
"Pickup": "Recollir",
"Truant": "Gandul",
"Hustle": "Entusiasme",
"Cute Charm": "Encant",
"Plus": "Més",
"Minus": "Menys",
"Forecast": "Pronòstic",
"Sticky Hold": "PresaViscosa",
"Shed Skin": "Muda",
"Guts": "Coratge",
"Marvel Scale": "EscataMàgica",
"Liquid Ooze": "Llot Líquid",
"Overgrow": "Espessor",
"Blaze": "Flama",
"Torrent": "Torrent",
"Swarm": "Eixam",
"Rock Head": "Cap Dur",
"Drought": "Sequera",
"Arena Trap": "Trampa Arena",
"Vital Spirit": "EsperitVital",
"White Smoke": "Fum Blanc",
"Pure Power": "Poder Pur",
"Shell Armor": "Closca Dura",
"Air Lock": "Pany d'Aire",
"Tangled Feet": "PeusEmbolics",
"Motor Drive": "Electromotor",
"Rivalry": "Rivalitat",
"Steadfast": "Ferm",
"Snow Cloak": "Mantell Neu",
"Gluttony": "Golafreria",
"Anger Point": "Punt Ràbia",
"Unburden": "Alliberat",
"Heatproof": "Ignífug",
"Simple": "Senzillesa",
"Dry Skin": "Pell Seca",
"Download": "Descàrrega",
"Iron Fist": "PunyDeFerro",
"Poison Heal": "Cura Verí",
"Adaptability": "Adaptable",
"Skill Link": "Enllaç",
"Hydration": "Hidratació",
"Solar Power": "Poder Solar",
"Quick Feet": "Peus Ràpids",
"Normalize": "Normalitzar",
"Sniper": "Franctirador",
"Magic Guard": "Escut Màgic",
"No Guard": "Sense Escut",
"Stall": "Endarrerit",
"Technician": "Tècnic",
"Leaf Guard": "Escut Fulla",
"Klutz": "Maldestre",
"Mold Breaker": "TrencaMotlle",
"Super Luck": "Súper Sort",
"Aftermath": "Detonació",
"Anticipation": "Anticipació",
"Forewarn": "Advertència",
"Unaware": "Ignorant",
"Tinted Lens": "Lent Tintada",
"Filter": "Filtre",
"Slow Start": "Inici Lent",
"Scrappy": "Intrèpid",
"Storm Drain": "Drenatge",
"Ice Body": "Cos de Gel",
"Solid Rock": "Roca Sòlida",
"Snow Warning": "Alerta Neu",
"Honey Gather": "Recull Mel",
"Frisk": "Escorcoll",
"Reckless": "Temerari",
"Multitype": "Multitipus",
"Flower Gift": "Do Floral",
"Bad Dreams": "Malsons",
"Pickpocket": "Carterista",
"Sheer Force": "Força Bruta",
"Contrary": "Contrari",
"Unnerve": "Nerviosisme",
"Defiant": "Desafiant",
"Defeatist": "Derrotista",
"Cursed Body": "Cos Maleït",
"Healer": "Curador",
"Friend Guard": "Escut Amic",
"Weak Armor": "CuirassFeble",
"Heavy Metal": "MetallPesant",
"Light Metal": "MetallLleu",
"Multiscale": "Multiescata",
"Toxic Boost": "Impuls Tòxic",
"Flare Boost": "Impuls Flama",
"Harvest": "Collita",
"Telepathy": "Telepatia",
"Moody": "Malhumorat",
"Overcoat": "Sobretot",
"Poison Touch": "Toc Verinós",
"Regenerator": "Regenerador",
"Big Pecks": "Gran Pit",
"Sand Rush": "Ràfega Sorra",
"Wonder Skin": "Pell Prodigi",
"Analytic": "Analític",
"Illusion": "Il·lusió",
"Imposter": "Impostor",
"Infiltrator": "Infiltrador",
"Mummy": "Mòmia",
"Moxie": "Autoestima",
"Justified": "Justicier",
"Rattled": "Espantadís",
"Magic Bounce": "Rebot Màgic",
"Sap Sipper": "Xucla Saba",
"Prankster": "Trapella",
"Sand Force": "Força Sorra",
"Iron Barbs": "Punxes Ferro",
"Zen Mode": "Mode Zen",
"Victory Star": "EstelVictòri",
"Turboblaze": "Turboflama",
"Teravolt": "Teravolt",
"Aroma Veil": "Vel Aroma",
"Flower Veil": "Vel Floral",
"Cheek Pouch": "Galta Bossa",
"Protean": "Proteic",
"Fur Coat": "Abric Pèl",
"Magician": "Mag",
"Bulletproof": "Antibales",
"Competitive": "Competitiu",
"Strong Jaw": "Mandíbula",
"Refrigerate": "Refrigerar",
"Sweet Veil": "Vel Dolç",
"Stance Change": "CanviPostura",
"Gale Wings": "Ales Vent",
"Mega Launcher": "Megallançad.",
"Grass Pelt": "Pell Herba",
"Symbiosis": "Simbiosi",
"Tough Claws": "Urpes Dures",
"Pixilate": "Pell de Fada",
"Gooey": "Viscós",
"Aerilate": "Pell Aèria",
"Parental Bond": "VinclePatern",
"Dark Aura": "Aura Fosca",
"Fairy Aura": "Aura de Fada",
"Aura Break": "Trenca Aura",
"Primordial Sea": "MarPrimordil",
"Desolate Land": "Terra Erma",
"Delta Stream": "Flux Delta",
"Stamina": "Resistència",
"Wimp Out": "Fugida Fàcil",
"Emergency Exit": "SortidaUrgnt",
"Water Compaction": "Hidrocompact",
"Merciless": "Sense Pietat",
"Shields Down": "EscutsBaixos",
"Stakeout": "Vigilància",
"Water Bubble": "Bombolla",
"Steelworker": "Metal·lúrgic",
"Berserk": "Enfurit",
"Slush Rush": "Ràfega Neu",
"Long Reach": "Gran Abast",
"Liquid Voice": "Veu Líquida",
"Triage": "Triatge",
"Galvanize": "Galvanitzar",
"Surge Surfer": "Surfista",
"Schooling": "BancDePeixos",
"Disguise": "Disfressa",
"Battle Bond": "VincleCombat",
"Power Construct": "Construir",
"Corrosion": "Corrosió",
"Comatose": "Comatós",
"Queenly Majesty": "Majestat",
"Innards Out": "Entranyes",
"Dancer": "Ballarí",
"Battery": "Bateria",
"Fluffy": "Pelut",
"Dazzling": "Enlluernant",
"Soul-Heart": "Cor d'Ànima",
"Tangling Hair": "Pèl Embolic",
"Receiver": "Receptor",
"Power Of Alchemy": "Alquímia",
"Beast Boost": "ImpulsBèstia",
"RKS System": "Sistema RKS",
"Electric Surge": "OnadaElèctr",
"Psychic Surge": "OnadaPsíquic",
"Misty Surge": "Onada Boira",
"Grassy Surge": "Onada Herba",
"Full Metal Body": "CosMetàl·lic",
"Shadow Shield": "Escut Ombra",
"Prism Armor": "CuirassPrism",
"Neuroforce": "Neuroforça",
"Intrepid Sword": "EspasaIntrèp",
"Dauntless Shield": "Escut Ferm",
"Libero": "Libero",
"Ball Fetch": "Recull Ball",
"Cotton Down": "Cotó Caigut",
"Propeller Tail": "Cua Hèlice",
"Mirror Armor": "CuirassMiral",
"Gulp Missile": "MíssilEmpass",
"Stalwart": "Lleial",
"Steam Engine": "MàquinaVapor",
"Punk Rock": "Punk Rock",
"Sand Spit": "Escup Sorra",
"Ice Scales": "Escates Gel",
"Ripen": "Maduració",
"Ice Face": "Cara de Gel",
"Power Spot": "PuntDePoder",
"Mimicry": "Mimetisme",
"Screen Cleaner": "NetejaEscuts",
"Steely Spirit": "Esperit Acer",
"Perish Body": "Cos Mortal",
"Wandering Spirit": "EsperitErrnt",
"Gorilla Tactics": "TàcticaGoril",
"Neutralizing Gas": "GasNeutralit",
"Pastel Veil": "Vel Pastel",
"Hunger Switch": "CanviDeGana",
"Quick Draw": "Traç Ràpid",
"Unseen Fist": "PunyInvisibl",
"Curious Medicine": "MedicinaCuri",
"Transistor": "Transistor",
"Dragon's Maw": "Boca de Drac",
"Chilling Neigh": "Renill Gelat",
"Grim Neigh": "Renill Fosc",
"As One": "Com Un",

# ---------------- descriptions ----------------
"No special ability.": "Cap habilitat especial.",
"May cause a foe to flinch.": "Pot esglaiar el rival.",
"Summons rain in battle.": "Invoca pluja al combat.",
"Gradually boosts Speed.": "Puja la Velocitat a poc a poc.",
"Blocks critical hits.": "Bloqueja els cops crítics.",
"Negates 1-hit KO attacks.": "Anul·la els atacs de KO directe.",
"Prevents self-destruction.": "Impedeix l'autodestrucció.",
"Prevents paralysis.": "Impedeix la paràlisi.",
"Ups evasion in a sandstorm.": "Puja l'evasió amb tempesta.",
"Paralyzes on contact.": "Paralitza en contacte.",
"Turns electricity into HP.": "Converteix l'electricitat en PS.",
"Changes water into HP.": "Converteix l'aigua en PS.",
"Prevents attraction.": "Impedeix l'atracció.",
"Negates weather effects.": "Anul·la els efectes del clima.",
"Raises accuracy.": "Puja la precisió.",
"Prevents sleep.": "Impedeix la son.",
"Changes type to foe's move.": "Canvia al tipus del moviment rival.",
"Prevents poisoning.": "Impedeix l'enverinament.",
"Powers up if hit by fire.": "Es reforça si el toca el foc.",
"Prevents added effects.": "Impedeix els efectes afegits.",
"Prevents confusion.": "Impedeix la confusió.",
"Firmly anchors the body.": "Ancora el cos amb fermesa.",
"Lowers the foe's Attack.": "Baixa l'Atac del rival.",
"Prevents the foe's escape.": "Impedeix la fugida del rival.",
"Hurts to touch.": "Fa mal si el toques.",
"“Super effective” hits.": "Només el toquen els “molt eficaç”.",
"Not hit by Ground attacks.": "No el toquen els atacs Terra.",
"Leaves spores on contact.": "Deixa espores en contacte.",
"Passes on status problems.": "Encomana els problemes d'estat.",
"Prevents ability reduction.": "Impedeix perdre estadístiques.",
"Heals upon switching out.": "Es cura en sortir del combat.",
"Draws electrical moves.": "Atreu els moviments elèctrics.",
"Promotes added effects.": "Afavoreix els efectes afegits.",
"Raises Speed in rain.": "Puja la Velocitat amb pluja.",
"Raises Speed in sunshine.": "Puja la Velocitat amb sol.",
"Encounter rate increases.": "Augmenta les trobades.",
"Copies special ability.": "Copia l'habilitat especial.",
"Raises Attack.": "Puja l'Atac.",
"Poisons foe on contact.": "Enverina el rival en contacte.",
"Prevents flinching.": "Impedeix l'esglai.",
"Prevents freezing.": "Impedeix la congelació.",
"Prevents burns.": "Impedeix les cremades.",
"Traps Steel-type Pokémon.": "Atrapa els Pokémon d'Acer.",
"Avoids sound-based moves.": "Evita els moviments de so.",
"Slight HP recovery in rain.": "Recupera una mica de PS amb pluja.",
"Summons a sandstorm.": "Invoca una tempesta de sorra.",
"Raises foe's PP usage.": "Fa gastar més PP al rival.",
"Heat-and-cold protection.": "Protegeix del fred i la calor.",
"Awakens quickly from sleep.": "Es desperta ràpidament.",
"Burns the foe on contact.": "Crema el rival en contacte.",
"Makes escaping easier.": "Facilita la fugida.",
"Prevents loss of accuracy.": "Impedeix perdre precisió.",
"Prevents Attack reduction.": "Impedeix perdre Atac.",
"May pick up items.": "Pot recollir objectes.",
"Moves only every two turns.": "Només actua cada dos torns.",
"Trades accuracy for power.": "Canvia precisió per potència.",
"Infatuates on contact.": "Enamora en contacte.",
"Powers up with Minus.": "Es reforça amb Menys.",
"Powers up with Plus.": "Es reforça amb Més.",
"Changes with the weather.": "Canvia segons el clima.",
"Prevents item theft.": "Impedeix el robatori d'objectes.",
"Heals the body by shedding.": "Es cura mudant la pell.",
"Ups Attack if suffering.": "Puja l'Atac si té problemes.",
"Ups Defense if suffering.": "Puja la Defensa si té problemes.",
"Draining causes injury.": "Drenar-lo causa dany.",
"Ups Grass moves in a pinch.": "Reforça els moviments Planta.",
"Ups Fire moves in a pinch.": "Reforça els moviments Foc.",
"Ups Water moves in a pinch.": "Reforça els moviments Aigua.",
"Ups Bug moves in a pinch.": "Reforça els moviments Insecte.",
"Prevents recoil damage.": "Impedeix el dany de retrocés.",
"Summons sunlight in battle.": "Invoca llum del sol al combat.",
"Prevents fleeing.": "Impedeix la fugida.",
"Ups evasion if confused.": "Puja l'evasió si està confós.",
"Electricity raises Speed.": "L'electricitat puja la Velocitat.",
"Powers up against rivals.": "Es reforça contra rivals.",
"Flinching raises Speed.": "L'esglai puja la Velocitat.",
"Ups evasion in Hail.": "Puja l'evasió amb calamarsa.",
"Eats Berries early.": "Menja les baies abans d'hora.",
"Critical hits raise Attack.": "Els crítics pujen l'Atac.",
"Using a hold item ups Speed.": "Gastar l'objecte puja la Velocitat.",
"Heat and burn protection.": "Protegeix de la calor i el foc.",
"Prone to wild stat changes.": "Té canvis d'estadístiques bruscos.",
"Prefers moisture to heat.": "Prefereix la humitat a la calor.",
"Adjusts power favorably.": "Ajusta la potència al seu favor.",
"Boosts punching moves.": "Reforça els moviments de puny.",
"Restores HP if poisoned.": "Recupera PS si està enverinat.",
"Boosts same type attacks.": "Reforça els atacs del seu tipus.",
"Multi-hit moves hit 5 times.": "Els cops múltiples encerten 5 cops.",
"Cures status in rain.": "Cura l'estat amb pluja.",
"Powers up in sunshine.": "Es reforça amb sol.",
"Ups Speed if suffering.": "Puja la Velocitat si té problemes.",
"Moves become Normal-type.": "Els moviments passen a ser Normal.",
"Boosts critical hits.": "Reforça els cops crítics.",
"Only damaged by attacks.": "Només el fereixen els atacs.",
"Ensures that all moves hit.": "Fa que tots els moviments encertin.",
"Always moves last.": "Sempre actua l'últim.",
"Boosts weaker moves.": "Reforça els moviments febles.",
"Blocks status in sunshine.": "Bloqueja els estats amb sol.",
"Can't use hold items.": "No pot fer servir objectes.",
"Moves hit through abilities.": "Els moviments passen les habilitats.",
"Critical hits land often.": "Fa crítics més sovint.",
"Fainting damages the foe.": "En debilitar-se fereix el rival.",
"Senses dangerous moves.": "Detecta els moviments perillosos.",
"Determines a foe's move.": "Endevina un moviment del rival.",
"Ignores stat changes.": "Ignora els canvis d'estadístiques.",
"Ups “not very effective”.": "Reforça els “no gaire eficaç”.",
"Weakens “supereffective”.": "Afebleix els “molt eficaç”.",
"Takes a while to get going.": "Triga una estona a engegar-se.",
"Hits Ghost-type Pokémon.": "Pot tocar els Pokémon Fantasma.",
"Draws in Water moves.": "Atreu els moviments d'Aigua.",
"Slight HP recovery in Hail.": "Recupera PS amb calamarsa.",
"Summons a hailstorm.": "Invoca calamarsa.",
"May gather Honey.": "Pot recollir mel.",
"Checks a foe's item.": "Descobreix l'objecte del rival.",
"Boosts moves with recoil.": "Reforça els moviments de retrocés.",
"Changes type to its Plate.": "Canvia al tipus de la seva Placa.",
"Transforms in sunshine.": "Es transforma amb sol.",
"Damages sleeping Pokémon.": "Fereix els Pokémon adormits.",
"Steals the foe's held item.": "Roba l'objecte del rival.",
"Trades effects for power.": "Canvia efectes per potència.",
"Inverts stat changes.": "Inverteix els canvis d'estadístiques.",
"Foes can't eat Berries.": "Els rivals no poden menjar baies.",
"Lowered stats up Attack.": "Perdre estadístiques puja l'Atac.",
"Gives up at half HP.": "Es rendeix amb la meitat de PS.",
"Disables moves on contact.": "Anul·la moviments en contacte.",
"Heals partner Pokémon.": "Cura el Pokémon company.",
"Lowers damage to partner.": "Redueix el dany al company.",
"Its stats change when hit.": "Les estadístiques canvien si el toquen.",
"Doubles weight.": "Duplica el pes.",
"Halves weight.": "Redueix el pes a la meitat.",
"Halves damage at full HP.": "Amb PS plens rep la meitat de dany.",
"Ups Attack if poisoned.": "Puja l'Atac si està enverinat.",
"Ups Sp. Atk if burned.": "Puja l'At. Esp. si està cremat.",
"May recycle a used Berry.": "Pot reciclar una baia gastada.",
"Can't be damaged by an ally.": "Un aliat no li pot fer mal.",
"Stats change gradually.": "Les estadístiques canvien a poc a poc.",
"Blocks weather and powder.": "Bloqueja el clima i les pols.",
"Prevents Defense loss.": "Impedeix perdre Defensa.",
"Ups Speed in a sandstorm.": "Puja la Velocitat amb tempesta.",
"May avoid status problems.": "Pot evitar els problemes d'estat.",
"Moving last boosts power.": "Actuar l'últim reforça la potència.",
"Appears as a partner.": "Apareix com un company.",
"Transforms into the foe.": "Es transforma en el rival.",
"Passes through barriers.": "Travessa les barreres.",
"Spreads with contact.": "S'encomana en contacte.",
"KOs raise Attack.": "Els KO pugen l'Atac.",
"Dark hits raise Attack.": "Els cops Sinistre pugen l'Atac.",
"Raises Speed when scared.": "Puja la Velocitat si s'espanta.",
"Reflects status moves.": "Reflecteix els moviments d'estat.",
"Grass increases Attack.": "L'herba puja l'Atac.",
"Status moves go first.": "Els moviments d'estat van primer.",
"Powers up in a sandstorm.": "Es reforça amb tempesta de sorra.",
"Transforms at half HP.": "Es transforma amb la meitat de PS.",
"Raises party accuracy.": "Puja la precisió de l'equip.",
"Prevents limiting of moves.": "Impedeix limitar els moviments.",
"Protects Grass-types.": "Protegeix els de tipus Planta.",
"Eating Berries restores HP.": "Menjar baies recupera PS.",
"Changes type to used move.": "Canvia al tipus del moviment usat.",
"Raises Defense.": "Puja la Defensa.",
"Avoids some projectiles.": "Evita alguns projectils.",
"Lowered stats up Sp. Atk.": "Perdre estadístiques puja l'At. Esp.",
"Boosts biting moves.": "Reforça els moviments de mossegada.",
"Normal moves become Ice.": "Els moviments Normal passen a Gel.",
"Prevents party from sleep.": "Impedeix que l'equip s'adormi.",
"Transforms as it battles.": "Es transforma mentre combat.",
"Flying moves go first.": "Els moviments Volador van primer.",
"Boosts pulse moves.": "Reforça els moviments d'onada.",
"Ups Defense in grass.": "Puja la Defensa a l'herba.",
"Passes its item to an ally.": "Passa el seu objecte a un aliat.",
"Boosts contact moves.": "Reforça els moviments de contacte.",
"Normal moves become Fairy.": "Els moviments Normal passen a Fada.",
"Lowers Speed on contact.": "Baixa la Velocitat en contacte.",
"Normal moves become Flying.": "Els Normal passen a Volador.",
"Moves hit twice.": "Els moviments encerten dos cops.",
"Boosts Dark moves.": "Reforça els moviments Sinistre.",
"Boosts Fairy moves.": "Reforça els moviments Fada.",
"Reverse aura abilities.": "Inverteix les habilitats d'aura.",
"Summons heavy rain.": "Invoca pluja intensa.",
"Summons intense sunlight.": "Invoca llum del sol intensa.",
"Summons strong winds.": "Invoca vents forts.",
"Boosts Defense when hit.": "Puja la Defensa si el toquen.",
"Flees at half HP.": "Fuig amb la meitat de PS.",
"Water boosts Defense.": "L'aigua puja la Defensa.",
"Criticals poisoned foes.": "Fa crítics als rivals enverinats.",
"Shell breaks at half HP.": "La closca es trenca a mig PS.",
"Stronger as foes switch in.": "Més fort si el rival entra.",
"Guards from fire and burns.": "Protegeix del foc i les cremades.",
"Powers up Steel moves.": "Reforça els moviments d'Acer.",
"Boosts Sp. Atk at low HP.": "Puja l'At. Esp. amb pocs PS.",
"Raises Speed in hail.": "Puja la Velocitat amb calamarsa.",
"Never makes contact.": "Mai no fa contacte.",
"Makes sound moves Water.": "Els moviments de so passen a Aigua.",
"Healing moves go first.": "Els moviments de cura van primer.",
"Normal moves turn Electric.": "Els Normal passen a Elèctric.",
"Faster on electricity.": "Més ràpid amb electricitat.",
"Forms a school when strong.": "Forma un banc si és fort.",
"Decoy protects it once.": "Un ninot el protegeix un cop.",
"Changes form after a KO.": "Canvia de forma després d'un KO.",
"Cells aid it when weakened.": "Les cèl·lules l'ajuden si s'afebleix.",
"Poisons any type.": "Enverina qualsevol tipus.",
"Always drowsing.": "Sempre està endormiscat.",
"Protects from priority.": "Protegeix dels moviments de prioritat.",
"Hurts foe when defeated.": "Fereix el rival si el derroten.",
"Dances along with others.": "Balla juntament amb els altres.",
"Boosts ally's Sp. Atk.": "Puja l'At. Esp. de l'aliat.",
"Tougher but flammable.": "Més dur però inflamable.",
"KOs raise Sp. Atk.": "Els KO pugen l'At. Esp.",
"Contact lowers Speed.": "El contacte baixa la Velocitat.",
"Copies ally's ability.": "Copia l'habilitat de l'aliat.",
"KOs boost best stat.": "Els KO pugen la millor estadística.",
"Memories change its type.": "Els records li canvien el tipus.",
"Field becomes Electric.": "El camp passa a ser Elèctric.",
"Field becomes weird.": "El camp es torna estrany.",
"Field becomes misty.": "El camp s'omple de boira.",
"Field becomes grassy.": "El camp s'omple d'herba.",
"Prevents stat reduction.": "Impedeix perdre estadístiques.",
"Ups “supereffective”.": "Reforça els “molt eficaç”.",
"Ups Attack on entry.": "Puja l'Atac en entrar.",
"Ups Defense on entry.": "Puja la Defensa en entrar.",
"Changes type to move's.": "Canvia al tipus del moviment.",
"Fetches failed Poké Ball.": "Recull la Poké Ball fallada.",
"Lower Speed of all when hit.": "Si el toquen, baixa la Vel. de tots.",
"Ignores foe's redirection.": "Ignora la redirecció del rival.",
"Reflect stat decreases.": "Reflecteix les baixades d'estadístiques.",
"If hit, spits prey from sea.": "Si el toquen, escup la presa.",
"Fire or Water hits up Speed.": "Foc o Aigua li pugen la Velocitat.",
"Ups and resists sound.": "Reforça i resisteix el so.",
"Creates a sandstorm if hit.": "Crea una tempesta si el toquen.",
"Halves special damage.": "Redueix el dany especial a la meitat.",
"Doubles effect of Berries.": "Duplica l'efecte de les baies.",
"Take a free hit. Hail renews.": "Aguanta un cop. La calamarsa el renova.",
"Powers up ally moves.": "Reforça els moviments de l'aliat.",
"Changes type on terrain.": "Canvia de tipus segons el camp.",
"Removes walls of light.": "Elimina els murs de llum.",
"Boosts ally's Steel moves.": "Reforça els moviments d'Acer de l'aliat.",
"Foe faints in 3 turns if hit.": "Si el toca, el rival cau en 3 torns.",
"Trade abilities on contact.": "Bescanvia habilitats en contacte.",
"Ups Attack and locks move.": "Puja l'Atac i fixa el moviment.",
"All Abilities are nullified.": "Anul·la totes les habilitats.",
"Protects team from poison.": "Protegeix l'equip del verí.",
"Changes form each turn.": "Canvia de forma cada torn.",
"Moves first occasionally.": "De vegades actua primer.",
"Contact evades protection.": "El contacte evita la protecció.",
"Remove ally's stat changes.": "Treu els canvis d'estat de l'aliat.",
"Ups Electric-type moves.": "Reforça els moviments Elèctric.",
"Ups Dragon-type moves.": "Reforça els moviments Drac.",
"KOs boost Attack stat.": "Els KO pugen l'Atac.",
"KOs boost Sp. Atk stat.": "Els KO pugen l'At. Esp.",
"Unnerve and Chilling Neigh.": "Nerviosisme i Renill Gelat.",
"Unnerve and Grim Neigh.": "Nerviosisme i Renill Fosc.",
}
