SSAnne_2F_Room6_MapScripts::
	.byte 0

SSAnne_2F_Room6_EventScript_Woman1::
	msgbox SSAnne_2F_Room6_Text_CaptainIsAwfullySick, MSGBOX_NPC
	end

SSAnne_2F_Room6_Text_CaptainIsAwfullySick::
    .string "El Capità tenia molt mala cara.\n"
    .string "Estava tot pàl·lid.$"


SSAnne_2F_Room6_EventScript_Woman2::
	msgbox SSAnne_2F_Room6_Text_ManyPeopleGetSeasick, MSGBOX_NPC
	end

SSAnne_2F_Room6_Text_ManyPeopleGetSeasick::
    .string "He sentit que molta gent es\n"
    .string "mareja al mar.$"
