FuchsiaCity_SafariZone_Office_MapScripts::
	.byte 0

FuchsiaCity_SafariZone_Office_EventScript_Worker1::
	msgbox FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "Hem posat de malnom al Guardià\n"

    .string "“Slowpoke.”\p"

    .string "Saps, té aquella mirada buida\n"

    .string "com un Slowpoke.$"


FuchsiaCity_SafariZone_Office_EventScript_Worker2::
	msgbox FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "El Guardià Slowpoke sap molt\n"

    .string "sobre Pokémon.\p"

    .string "Fins i tot té fòssils de Pokémon\n"

    .string "rars i extints.$"


FuchsiaCity_SafariZone_Office_EventScript_Worker3::
	msgbox FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "El Guardià Slowpoke ha vingut,\n"

    .string "però no l'he pogut entendre.\p"

    .string "Crec que té un problema de parla!$"


FuchsiaCity_SafariZone_Office_EventScript_Worker4::
	msgbox FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "El Guardià Slowpoke està fent\n"

    .string "una campanya de promoció.\p"

    .string "Intenta arribar al racó més\n"

    .string "llunyà de la Zona Safari.\p"

    .string "Si ho aconsegueixes, guanyaràs\n"

    .string "un premi molt pràctic.$"

