CeladonCity_DepartmentStore_3F_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_3F_EventScript_GBAKid1::
	msgbox CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .string "Els Pokémon capturats es registren\n"

    .string "amb un Núm. ID i l'EO.\p"

    .string "EO vol dir “Entrenador Original” -\n"

    .string "l'entrenador que el va capturar.$"


CeladonCity_DepartmentStore_3F_EventScript_GBAKid2::
	msgbox CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .string "Molt bé!\p"

    .string "El meu amic m'intercanviarà el\n"

    .string "seu Kangaskhan pel meu Haunter!$"


CeladonCity_DepartmentStore_3F_EventScript_GBAKid3::
	msgbox CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .string "Vinga, Haunter!\p"

    .string "M'encanta Haunter!\n"

    .string "Els col·lecciono!\p"

    .string "Eh?\p"

    .string "Haunter s'ha convertit en un\n"

    .string "Pokémon diferent en intercanviar!$"


CeladonCity_DepartmentStore_3F_EventScript_LittleGirl::
	msgbox CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .string "Pots identificar els Pokémon\n"

    .string "d'intercanvi pel Número d'ID.$"


CeladonCity_DepartmentStore_3F_EventScript_SuperNES::
	msgbox CeladonCity_DepartmentStore_3F_Text_ItsSuperNES, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "És una Super NES.$"


CeladonCity_DepartmentStore_3F_EventScript_TV1::
	msgbox CeladonCity_DepartmentStore_3F_Text_AnRPG, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "Un RPG!\n"

    .string "No hi ha temps per a això!$"


CeladonCity_DepartmentStore_3F_EventScript_TV2::
	msgbox CeladonCity_DepartmentStore_3F_Text_SportsGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "Un joc d'esports!\n"

    .string "Al papa li agradarà!$"


CeladonCity_DepartmentStore_3F_EventScript_TV3::
	msgbox CeladonCity_DepartmentStore_3F_Text_PuzzleGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "Un joc de puzles!\n"

    .string "Sembla addictiu!$"


CeladonCity_DepartmentStore_3F_EventScript_TV4::
	msgbox CeladonCity_DepartmentStore_3F_Text_FightingGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "Un joc de lluita!\n"

    .string "Sembla difícil!$"


CeladonCity_DepartmentStore_3F_EventScript_FloorSign::
	msgbox CeladonCity_DepartmentStore_3F_Text_TVGameShop, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "3F: Botiga de Videojocs$"


CeladonCity_DepartmentStore_3F_EventScript_Poster::
	msgbox CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "Red i Green!\n"

    .string "Tots dos són Pokémon!$"

